### ISSUE TITLE
Dungeon Mobs, Lycanites Mobs crash on start

### ISSUE THREAD

**Issue by Kaotic** [Teneted/Tenet#10]
Tested with clean server & clean mods configs

Dungeon Mobs (dungeonmobs-5.8.3-MC1.12.2) crash on start :
```
Description: Exception in server tick loop

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Dungeon Mobs (dungeonmobs)
Caused by: java.lang.IllegalArgumentException: value already present: class com.gw.dm.projectile.EntityEyeRay
	at com.google.common.collect.HashBiMap.put(HashBiMap.java:287)
	at com.google.common.collect.HashBiMap.put(HashBiMap.java:262)
	at net.minecraft.util.registry.RegistrySimple.func_82595_a(SourceFile:42)
	at net.minecraft.util.registry.RegistryNamespaced.func_177775_a(SourceFile:22)
	at net.minecraftforge.fml.common.registry.EntityRegistry$EntityRegistration.<init>(EntityRegistry.java:91)
	at net.minecraftforge.fml.common.registry.EntityRegistry$EntityRegistration.<init>(EntityRegistry.java:71)
	at net.minecraftforge.fml.common.registry.EntityRegistry.doModEntityRegistration(EntityRegistry.java:209)
	at net.minecraftforge.fml.common.registry.EntityRegistry.registerModEntity(EntityRegistry.java:181)
	at com.gw.dm.util.MobRegistrar.registerMobs(MobRegistrar.java:237)
	at com.gw.dm.DungeonMobs.preInit(DungeonMobs.java:62)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:626)
	at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:103)
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:328)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:167)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:608)
	at java.lang.Thread.run(Unknown Source)
```
Lycanites Mobs (lycanitesmobs-1.12.2-2.0.0.4) cause crash on start :
```
Description: Exception in server tick loop

java.lang.IllegalArgumentException: value already present: class com.lycanitesmobs.core.entity.EntityProjectileCustom
	at com.google.common.collect.HashBiMap.put(HashBiMap.java:287)
	at com.google.common.collect.HashBiMap.put(HashBiMap.java:262)
	at net.minecraft.util.registry.RegistrySimple.func_82595_a(SourceFile:42)
	at net.minecraft.util.registry.RegistryNamespaced.func_177775_a(SourceFile:22)
	at net.minecraftforge.fml.common.registry.EntityRegistry$EntityRegistration.<init>(EntityRegistry.java:91)
	at net.minecraftforge.fml.common.registry.EntityEntryBuilder$BuiltEntityEntry.createRegistration(EntityEntryBuilder.java:353)
	at net.minecraftforge.fml.common.registry.EntityEntryBuilder$BuiltEntityEntry.addedToRegistry(EntityEntryBuilder.java:336)
	at net.minecraftforge.registries.GameData$EntityCallbacks.onAdd(GameData.java:515)
	at net.minecraftforge.registries.GameData$EntityCallbacks.onAdd(GameData.java:506)
	at net.minecraftforge.registries.ForgeRegistry.add(ForgeRegistry.java:350)
	at net.minecraftforge.registries.ForgeRegistry.add(ForgeRegistry.java:281)
	at net.minecraftforge.registries.ForgeRegistry.register(ForgeRegistry.java:113)
	at com.lycanitesmobs.core.info.projectile.ProjectileManager.registerEntities(ProjectileManager.java:125)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_470_ProjectileManager_registerEntities_Register.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:146)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:186)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:863)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:627)
	at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:103)
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:328)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:167)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:608)
	at java.lang.Thread.run(Unknown Source)
```

**Comment by Mgazul** [comment]
Fixed
