### ISSUE TITLE
[1.7.10] Galacticraft (MicdoodleCore) incompatible with Mohist

### ISSUE THREAD

**Issue by bagomot** [Teneted/Tenet#100]
The MicdoodleCore (library for Galacticraft mod) is not compatible with a mohist version newer than Mohist-1.7.10-1614-server.
MicdoodleCore ver.: 1.7-3.0.12.504
```
[16:17:48] [main/INFO]: [micdoodle8.mods.miccore.MicdoodleTransformer:printResultsAndReset:1908]: Potential problem: Galacticraft did not complete injection of bytecode into: oi (4 / 6)
[16:17:48] [main/INFO]: [micdoodle8.mods.miccore.MicdoodleTransformer:printLog:1992]: Galacticraft successfully injected bytecode into: sv (1 / 1)
[16:17:48] [main/INFO]: Launching wrapped minecraft {net.minecraft.server.MinecraftServer}
[16:17:48] [main/INFO]: [micdoodle8.mods.miccore.MicdoodleTransformer:printLog:1992]: Galacticraft successfully injected bytecode into: xk (1 / 1)
[16:17:48] [main/INFO]: Patching leaves.
[16:17:48] [main/INFO]: Found leaf Class: net/minecraft/block/BlockLeavesBase
[16:17:48] [main/INFO]: Found hooks for net.minecraft.item.ItemBlock (abh)
[16:17:48] [main/INFO]: [micdoodle8.mods.miccore.MicdoodleTransformer:printLog:1992]: Galacticraft successfully injected bytecode into: zc (1 / 1)
[16:17:48] [main/ERROR]: Unable to launch
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_241]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_241]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_241]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_241]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:133) [Mohist-1.7.10-aaeea53-server.jar:aaeea53]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:26) [Mohist-1.7.10-aaeea53-server.jar:aaeea53]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_241]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_241]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_241]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_241]
	at red.mohist.Mohist.main(Mohist.java:76) [Mohist-1.7.10-aaeea53-server.jar:aaeea53]
Caused by: java.lang.VerifyError: Expecting a stackmap frame at branch target 233
Exception Details:
  Location:
    net/minecraft/item/ItemBlock.func_77648_a(Lnet/minecraft/item/ItemStack;Lnet/minecraft/entity/player/EntityPlayer;Lnet/minecraft/world/World;IIIIFFF)Z @228: ifne
  Reason:
    Expected stackmap frame at this location.
  Bytecode:
    0x0000000: 2d15 0415 0515 06b6 0028 3a0b 190b b200
    0x0000010: 2da6 001a 2d15 0415 0515 06b6 0031 1007
    0x0000020: 7e04 a200 0904 3607 a700 5f19 0bb2 0034
    0x0000030: a500 5719 0bb2 0038 a500 4f19 0bb2 003c
    0x0000040: a500 4719 0b2d 1504 1505 1506 b600 409a
    0x0000050: 0038 1507 9a00 0684 05ff 1507 04a0 0006
    0x0000060: 8405 0115 0705 a000 0684 06ff 1507 06a0
    0x0000070: 0006 8406 0115 0707 a000 0684 04ff 1507
    0x0000080: 08a0 0006 8404 012b b400 469a 0005 03ac
    0x0000090: 2c15 0415 0515 0615 072b b600 4c9a 0005
    0x00000a0: 03ac 1505 1100 ffa0 0012 2ab4 0017 b600
    0x00000b0: 50b6 0056 9900 0503 ac2d 2ab4 0017 1504
    0x00000c0: 1505 1506 0315 072c 2bb6 005a 9900 a5b8
    0x00000d0: 0060 2b2c 2d2a b400 1715 0415 0515 0615
    0x00000e0: 07b6 0064 9a00 0503 ac2a 2bb6 0068 b600
    0x00000f0: 6c36 0c2a b400 172d 1504 1505 1506 1507
    0x0000100: 1708 1709 170a 150c b600 7036 0d2a 2b2c
    0x0000110: 2d15 0415 0515 0615 0717 0817 0917 0a15
    0x0000120: 0db6 0074 9900 4b2d 1504 8612 7562 8d15
    0x0000130: 0586 1275 628d 1506 8612 7562 8d2a b400
    0x0000140: 17b4 0079 b600 7d2a b400 17b4 0079 b600
    0x0000150: 810c 620d 6e2a b400 17b4 0079 b600 8412
    0x0000160: 856a b600 892b 59b4 0046 0464 b500 4604
    0x0000170: ac03 ac                                
  Stackmap Table:
    append_frame(@43,Object[#9])
    same_frame(@90)
    same_frame(@99)
    same_frame(@108)
    same_frame(@117)
    same_frame(@126)
    same_frame(@135)
    same_frame(@144)
    same_frame(@162)
    same_frame(@185)
    append_frame(@367,Integer,Integer)
    chop_frame(@369,2)

	at net.minecraft.item.Item.func_150900_l(Item.java:419) ~[adb.class:?]
	at net.minecraft.init.Bootstrap.func_151354_b(Bootstrap.java:716) ~[kl.class:?]
	at net.minecraft.server.MinecraftServer.main(MinecraftServer.java:1616) ~[MinecraftServer.class:?]
	... 11 more
[16:17:48] [main/INFO]: [red.mohist.Mohist:main:80]: A problem occurred running the Server launcher.
[16:17:48] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: java.lang.reflect.InvocationTargetException
[16:17:48] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[16:17:48] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[16:17:48] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[16:17:48] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[16:17:48] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at red.mohist.Mohist.main(Mohist.java:76)
[16:17:48] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: Caused by: cpw.mods.fml.relauncher.FMLSecurityManager$ExitTrappedException
[16:17:48] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at cpw.mods.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:28)
[16:17:48] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.SecurityManager.checkExit(Unknown Source)
[16:17:48] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.Runtime.exit(Unknown Source)
[16:17:48] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.System.exit(Unknown Source)
[16:17:48] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:136)
[16:17:48] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:26)
[16:17:48] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	... 5 more
[16:17:48] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: java.lang.ArrayIndexOutOfBoundsException: 5
[16:17:48] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at cpw.mods.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:24)
[16:17:48] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.SecurityManager.checkExit(Unknown Source)
[16:17:48] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.Runtime.exit(Unknown Source)
[16:17:48] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.System.exit(Unknown Source)
[16:17:48] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at red.mohist.Mohist.main(Mohist.java:82)
```

**Comment by bagomot** [comment]
Sorry, this is the effect of the addon for Galacticraft (my development).
