### ISSUE TITLE
Backpacked mod - crash

### ISSUE THREAD

**Issue by ghost** [Teneted/Tenet#1005]
Build mohist 380
https://www.curseforge.com/minecraft/mc-mods/backpacked/files/3223654

---- Minecraft Crash Report ----
// Everything's going to plan. No, really, that was supposed to happen.

Time: 3/2/21 7:20 AM
Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
	at net.minecraftforge.fml.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:86) ~[forge:?] {re:classloading}
	at net.minecraftforge.fml.server.ServerModLoader.load(ServerModLoader.java:51) ~[forge:?] {re:classloading}
	at net.minecraft.server.Main.main(Main.java:121) ~[?:?] {re:classloading}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_275] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_275] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_275] {}
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_275] {}
	at net.minecraftforge.fml.loading.FMLServerLaunchProvider.lambda$launchService$0(FMLServerLaunchProvider.java:51) ~[server.jar:36.0] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {}
	at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:66) [server.jar:?] {}
	at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:63) [server.jar:?] {}
	at net.minecraftforge.server.ServerMain.main(ServerMain.java:60) [server.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: main
Stacktrace:
	at net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:71) ~[server.jar:36.0] {}
-- MOD backpacked --
Details:
	Mod File: backpacked-1.8.0-1.16.3.jar
	Failure message: Backpacked (backpacked) has failed to load correctly
		java.lang.RuntimeException: Attempted to load class net/minecraft/client/multiplayer/PlayerController for invalid dist DEDICATED_SERVER
	Mod Version: 1.8.0
	Mod Issue URL: NOT PROVIDED
	Exception message: java.lang.RuntimeException: Attempted to load class net/minecraft/client/multiplayer/PlayerController for invalid dist DEDICATED_SERVER
Stacktrace:
	at net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:71) ~[server.jar:36.0] {}
	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:85) ~[modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:265) ~[modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136) ~[modlauncher-8.0.9.jar:?] {re:classloading}
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98) ~[modlauncher-8.0.9.jar:?] {re:classloading}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_275] {}
	at java.lang.Class.getDeclaredConstructors0(Native Method) ~[?:1.8.0_275] {}
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671) ~[?:1.8.0_275] {}
	at java.lang.Class.getConstructor0(Class.java:3075) ~[?:1.8.0_275] {}
	at java.lang.Class.getConstructor(Class.java:1825) ~[?:1.8.0_275] {}
	at net.minecraftforge.eventbus.api.EventListenerHelper.computeListenerList(EventListenerHelper.java:96) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.api.EventListenerHelper.getListenerListInternal(EventListenerHelper.java:63) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.api.EventListenerHelper.getListenerList(EventListenerHelper.java:48) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.addToListeners(EventBus.java:263) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.register(EventBus.java:256) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.registerListener(EventBus.java:150) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$null$6(EventBus.java:98) ~[eventbus-4.0.0.jar:?] {}
	at java.util.Optional.ifPresent(Optional.java:159) ~[?:1.8.0_275] {}
	at net.minecraftforge.eventbus.EventBus.lambda$registerObject$7(EventBus.java:98) ~[eventbus-4.0.0.jar:?] {}
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:1.8.0_275] {}
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[?:1.8.0_275] {}
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948) ~[?:1.8.0_275] {}
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482) ~[?:1.8.0_275] {}
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[?:1.8.0_275] {}
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:1.8.0_275] {}
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:1.8.0_275] {}
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_275] {}
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:485) ~[?:1.8.0_275] {}
	at net.minecraftforge.eventbus.EventBus.registerObject(EventBus.java:94) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.register(EventBus.java:120) ~[eventbus-4.0.0.jar:?] {}
	at com.mrcrayfish.backpacked.Backpacked.<init>(Backpacked.java:66) ~[backpacked:1.8.0] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_275] {}
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_275] {}
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_275] {}
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_275] {}
	at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_275] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:82) ~[forge:36.0] {re:classloading}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:120) ~[forge:?] {re:classloading}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1640) ~[?:1.8.0_275] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1632) ~[?:1.8.0_275] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_275] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_275] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) ~[?:1.8.0_275] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175) ~[?:1.8.0_275] {}

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Linux (amd64) version 3.10.0-1160.11.1.el7.x86_64
	Java Version: 1.8.0_275, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 507380848 bytes (483 MB) / 1395654656 bytes (1331 MB) up to 2863661056 bytes (2731 MB)
	CPUs: 16
	JVM Flags: 2 total; -Xms128M -Xmx3072M
	ModLauncher: 8.0.9+86+master.3cf110c
	ModLauncher launch target: fmlserver
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/server.jar object_holder_definalize PLUGINSERVICE 
		/server.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/server.jar capability_inject_definalize PLUGINSERVICE 
		/server.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/server.jar fml TRANSFORMATIONSERVICE 
	FML: 36.0
	Forge: net.minecraftforge:36.0.42
	FML Language Providers: 
		javafml@36.0
		minecraft@1
	Mod List: 
		forge-1.16.5-36.0.42-server.jar                   |Minecraft                     |minecraft                     |1.16.5              |CREATE_REG|NOSIGNATURE
		forge-1.16.5-36.0.42-universal.jar                |Forge                         |forge                         |36.0.42             |CREATE_REG|NOSIGNATURE
		randompatches-2.4.4-forge.jar                     |RandomPatches                 |randompatches                 |2.4.4-forge         |CREATE_REG|92:f6:29:d4:09:89:f5:f5:98:5e:20:34:31:d0:7b:58:22:06:bd:a5:d1:6a:92:6e:ac:3d:8d:18:c5:b2:5b:d7
		curios-forge-1.16.5-4.0.4.0.jar                   |Curios API                    |curios                        |1.16.5-4.0.4.0      |CREATE_REG|NOSIGNATURE
		backpacked-1.8.0-1.16.3.jar                       |Backpacked                    |backpacked                    |1.8.0               |ERROR     |NOSIGNATURE
		BiomesOPlenty-1.16.4-13.0.0.431-universal.jar     |Biomes O' Plenty              |biomesoplenty                 |1.16.4-13.0.0.431   |CREATE_REG|NOSIGNATURE
		chiselsandbits-0.2.10-RELEASE.jar                 |Chisels & bits                |chiselsandbits                |NONE                |CREATE_REG|NOSIGNATURE
		AutoRegLib-1.6-47.jar                             |AutoRegLib                    |autoreglib                    |1.6-47              |CREATE_REG|NOSIGNATURE
		Quark-r2.4-308.jar                                |Quark                         |quark                         |r2.4-308            |CREATE_REG|NOSIGNATURE
	Crash Report UUID: a0cf1546-e9d0-4995-96ef-fecc7d720583
	CraftBukkit Information: 
   Running: 
   Failed to handle CraftCrashReport:
java.lang.NullPointerException
	at org.bukkit.Bukkit.getName(Bukkit.java:100)
	at org.bukkit.craftbukkit.v1_16_R3.CraftCrashReport.call(CraftCrashReport.java:23)
	at net.minecraft.crash.CrashReportCategory.func_189529_a(CrashReportCategory.java:81)
	at net.minecraft.crash.CrashReport.func_71504_g(CrashReport.java:73)
	at net.minecraft.crash.CrashReport.<init>(CrashReport.java:38)
	at net.minecraft.crash.CrashReport.func_85055_a(CrashReport.java:242)
	at net.minecraftforge.fml.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:86)
	at net.minecraftforge.fml.server.ServerModLoader.load(ServerModLoader.java:51)
	at net.minecraft.server.Main.main(Main.java:121)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraftforge.fml.loading.FMLServerLaunchProvider.lambda$launchService$0(FMLServerLaunchProvider.java:51)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)
	at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:66)
	at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:63)
	at net.minecraftforge.server.ServerMain.main(ServerMain.java:60)

**Comment by KR33PYK1NG** [comment]
This is a mod issue, Mohist has nothing to do about it.
