### ISSUE TITLE
[1.12.2] Fatal errors on the server because of java.lang.NullPointerException

### ISSUE THREAD

**Issue by Vladg24YT** [Teneted/Tenet#1019]
### System info
- *java -version* output:
```
openjdk version "1.8.0_265"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_265-b01)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.265-b01, mixed mode)
```
- OS: Windows 10 Pro x64 (build 19042.804)
### Server info:
- Mohist version: 1.12.2-192
<details>
<summary>Installed Mods:</summary>
  
- Antique Atlas (4.6.3)
- AppleCore (3.4.0)
- Backpack (3.0.2)
- Baubles (1.5.2)
- Biomes O' Plenty (7.0.1.2444-universal)
- Bookshelf (2.3.590)
- Clumps (3.1.2)
- CodeChickenLib (3.2.3.358-universal)
- CoFHCore (4.6.6.1-universal)
- CoFHWorld (1.4.0.1-universal)
- CoroUtil (1.2.37)
- CustomNPCs (05Jul20)
- FastFurnace (1.3.1)
- FastWorkbench (1.7.3)
- FTB Backups (1.1.0.1)
- Galacticraft Core (4.0.2.280)
- Galacticraft Planets (4.0.2.280)
- GregTech: Community Edition (1.12.0.662)
- Hardcore Questing Mode (5.4.0-hotfix1)
- HWYLA (1.8.26-B41)
- IndustrialCraft 2 (2.8.221-ex112)
- Lost Cities (2.0.22)
- Lycanite's Mobs (2.0.7.2)
- Micdoodle Core (4.0.2.280)
- MrCrayfish's Furniture Mod (6.3.1)
- MrCrayfish's Vehicle Mod (0.44.1)
- No More Recipe Conflict (0.13)
- Obfuscate (0.4.2)
- OpenBlocks (1.8.1)
- OpenMods Lib (0.12.2)
- Patchouli (23.6)
- Placebo (1.6.0)
- PrimalCore (0.6.105)
- Random Patches (1.22.1.10)
- Redstone Flux (2.1.1.1-universal)
- New TARDIS Mod (0.1.4A)
- Techguns (2.0.2.0_pre3.2)
- Thermal Dynamics (2.5.6.1-universal)
- Thermal Expansion (5.5.7.1-universal)
- Thermal Foundation (2.6.7.1-universal)
- ToolBelt (1.9.13)
- Tough As Nails (3.4.0.141-universal)
- WAWLA (2.6.275)
- Weather 2 (2.6.12)
</details>  

- Server launch command:
```
java -Xms7G -Xmx7G -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1 -Dusing.aikars.flags=https://mcflags.emc.gs -Daikars.new.flags=true -jar mohist-1.12.2-192-server.jar
```

### The issue
When I enter the server, the game stops responding to any kind of entity/block interaction. First time I got a similar error, the game just kicked me from the server, but now it's just responding like it has a very low TPS.   
The error message looks like this:  
```
[hh:mm:ss] [Server thread/FATAL] [net.minecraft.server.MinecraftServer]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_265]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_265]
	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:846) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:467) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:784) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:630) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_265]
Caused by: java.lang.NullPointerException
	at net.minecraft.network.NetHandlerPlayServer.func_147347_a(NetHandlerPlayServer.java:762) ~[pa.class:?]
	at net.minecraft.network.play.client.CPacketPlayer.func_148833_a(CPacketPlayer.java:33) ~[lk.class:?]
	at net.minecraft.network.play.client.CPacketPlayer$Position.func_148833_a(CPacketPlayer.java:76) ~[lk$a.class:?]
	at net.minecraft.network.PacketThreadUtil.lambda$checkThreadAndEnqueue$0(PacketThreadUtil.java:16) ~[hv.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_265]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_265]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	... 5 more
```
This error occures about 18 times per second and is flooding the log file.  

[`latest.log`](https://github.com/Mohist-Community/Mohist/files/6085961/latest.log)

**Comment by Vladg24YT** [comment]
Updated Mohist to 1.12.2-193, the issue seems to be gone
