### ISSUE TITLE
Crash on Mohist-1.7.10-aaeea53-server

### ISSUE THREAD

**Issue by Maks-Haswell** [Teneted/Tenet#102]
Time: 24.02.20 10:51
Description: Exception in server tick loop

java.lang.NoClassDefFoundError: net/md_5/specialsource/transformer/MappingTransformer
	at org.bukkit.craftbukkit.v1_7_R4.SpigotTimings.<clinit>(SpigotTimings.java:43)
	at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftTask.<init>(CraftTask.java:50)
	at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftTask.<init>(CraftTask.java:54)
	at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftTask.<init>(CraftTask.java:29)
	at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftScheduler.<init>(CraftScheduler.java:52)
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.<init>(CraftServer.java:152)
	at net.minecraft.server.management.ServerConfigurationManager.<init>(ServerConfigurationManager.java:130)
	at net.minecraft.server.dedicated.DedicatedPlayerList.<init>(SourceFile:14)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:236)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:646)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: net.md_5.specialsource.transformer.MappingTransformer
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:229)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 11 more
Caused by: java.lang.NullPointerException

**Comment by bagomot** [comment]
You have an old version of the library. Delete your `libraries` directory and start the server, it will download and unzip the archive from. After that, restart the server.

**Comment by Mgazul** [comment]
Yes, new version you need to download the lib again

**Comment by CraftDream** [comment]
Download `libraries` again to fix the problem.
