### ISSUE TITLE
1.16.5|mohist-384|apotheosis mod

### ISSUE THREAD

**Issue by 6371peter** [Teneted/Tenet#1027]
Unable to open enchanting_table GUI.

[09:51:09 WARN]: java.lang.NullPointerException
[09:51:09 WARN]:        at shadows.apotheosis.ench.table.ApothEnchantContainer.func_75130_a(ApothEnchantContainer.java:164)
[09:51:09 WARN]:        at net.minecraft.inventory.container.EnchantmentContainer$1.func_70296_d(EnchantmentContainer.java:43)
[09:51:09 WARN]:        at net.minecraft.inventory.Inventory.func_70299_a(Inventory.java:179)
[09:51:09 WARN]:        at net.minecraft.inventory.container.Slot.func_75215_d(Slot.java:61)
[09:51:09 WARN]:        at net.minecraft.inventory.container.EnchantmentContainer.handler$zzd000$open(EnchantmentContainer.java:544)
[09:51:09 WARN]:        at net.minecraft.inventory.container.EnchantmentContainer.<init>(EnchantmentContainer.java:110)
[09:51:09 WARN]:        at shadows.apotheosis.ench.table.ApothEnchantContainer.<init>(ApothEnchantContainer.java:69)
[09:51:09 WARN]:        at shadows.apotheosis.ench.table.ApothEnchantBlock.lambda$getContainer$0(ApothEnchantBlock.java:34)
[09:51:09 WARN]:        at net.minecraft.inventory.container.SimpleNamedContainerProvider.createMenu(SourceFile:25)
[09:51:09 WARN]:        at net.minecraft.entity.player.ServerPlayerEntity.func_213829_a(ServerPlayerEntity.java:1194)
[09:51:09 WARN]:        at net.minecraft.block.EnchantingTableBlock.func_225533_a_(EnchantingTableBlock.java:83)
[09:51:09 WARN]:        at net.minecraft.block.AbstractBlock$AbstractBlockState.func_227031_a_(AbstractBlock.java:640)
[09:51:09 WARN]:        at net.minecraft.server.management.PlayerInteractionManager.func_219441_a(PlayerInteractionManager.java:435)
[09:51:09 WARN]:        at net.minecraft.network.play.ServerPlayNetHandler.func_184337_a(ServerPlayNetHandler.java:1414)
[09:51:09 WARN]:        at net.minecraft.network.play.client.CPlayerTryUseItemOnBlockPacket.func_148833_a(CPlayerTryUseItemOnBlockPacket.java:38)
[09:51:09 WARN]:        at net.minecraft.network.play.client.CPlayerTryUseItemOnBlockPacket.func_148833_a(CPlayerTryUseItemOnBlockPacket.java:12)
[09:51:09 WARN]:        at net.minecraft.network.PacketThreadUtil.lambda$checkThreadAndEnqueue$0(PacketThreadUtil.java:22)
[09:51:09 WARN]:        at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18)
[09:51:09 WARN]:        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(ThreadTaskExecutor.java:136)
[09:51:09 WARN]:        at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23)
[09:51:09 WARN]:        at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:873)
[09:51:09 WARN]:        at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:183)
[09:51:09 WARN]:        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(ThreadTaskExecutor.java:109)
[09:51:09 WARN]:        at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:856)
[09:51:09 WARN]:        at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:850)
[09:51:09 WARN]:        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(ThreadTaskExecutor.java:119)
[09:51:09 WARN]:        at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:836)
[09:51:09 WARN]:        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:768)
[09:51:09 WARN]:        at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:276)
[09:51:09 WARN]:        at java.lang.Thread.run(Unknown Source)

**Comment by KR33PYK1NG** [comment]
Enchanting table w/ Apotheosis mod opens fine on latest Mohist build. Do you still experience the issue?

**Comment by CloWnicide** [comment]
Can confirm this is still an issue on #514 for 1.16.5
