### ISSUE TITLE
NPE with CMI

### ISSUE THREAD

**Issue by duplexsystem** [Teneted/Tenet#1038]
```[18:44:02 ERROR]: Could not pass event ProjectileLaunchEvent to CMI v8.8.2.0
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:319) ~[forge:?] {re:classloading}
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[forge:?] {re:classloading}
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[forge:?] {re:classloading}
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:574) ~[forge:?] {re:classloading}
	at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callProjectileLaunchEvent(CraftEventFactory.java:1164) ~[forge:?] {re:classloading}
	at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.doEntityAddEventCalling(CraftEventFactory.java:524) ~[forge:?] {re:classloading}
	at net.minecraft.world.server.ServerWorld.addEntity0(ServerWorld.java:918) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:abnormals_core.mixins.json:ServerWorldMixin,pl:mixin:APP:starlight.mixins.json:common.world.ServerWorldMixin,pl:mixin:APP:endergetic.mixins.json:ServerWorldMixin,pl:mixin:APP:quark.mixins.json:ServerWorldMixin,pl:mixin:APP:fabrication.mixins.json:c_tweaks.alt_absorption_sound.MixinServerWorld,pl:mixin:APP:fabrication.mixins.json:b_utility.item_despawn.MixinServerWorld,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.world.server.ServerWorld.func_217376_c(ServerWorld.java:845) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:abnormals_core.mixins.json:ServerWorldMixin,pl:mixin:APP:starlight.mixins.json:common.world.ServerWorldMixin,pl:mixin:APP:endergetic.mixins.json:ServerWorldMixin,pl:mixin:APP:quark.mixins.json:ServerWorldMixin,pl:mixin:APP:fabrication.mixins.json:c_tweaks.alt_absorption_sound.MixinServerWorld,pl:mixin:APP:fabrication.mixins.json:b_utility.item_despawn.MixinServerWorld,pl:mixin:A,pl:runtimedistcleaner:A}
	at com.minecraftabnormals.savageandravage.core.other.SREvents.onExplosion(SREvents.java:160) ~[savageandravage:3.1.0] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_121_SREvents_onExplosion_Detonate.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.event.ForgeEventFactory.onExplosionDetonate(ForgeEventFactory.java:485) ~[forge:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.world.Explosion.func_77278_a(Explosion.java:194) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.world.World.func_230546_a_(World.java:759) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:starlight.mixins.json:common.world.WorldMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.world.server.ServerWorld.func_230546_a_(ServerWorld.java:1221) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:abnormals_core.mixins.json:ServerWorldMixin,pl:mixin:APP:starlight.mixins.json:common.world.ServerWorldMixin,pl:mixin:APP:endergetic.mixins.json:ServerWorldMixin,pl:mixin:APP:quark.mixins.json:ServerWorldMixin,pl:mixin:APP:fabrication.mixins.json:c_tweaks.alt_absorption_sound.MixinServerWorld,pl:mixin:APP:fabrication.mixins.json:b_utility.item_despawn.MixinServerWorld,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.world.World.func_217398_a(World.java:753) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:starlight.mixins.json:common.world.WorldMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.entity.monster.CreeperEntity.func_146077_cc(CreeperEntity.java:238) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:fabrication.mixins.json:c_tweaks.creepers_explode_when_on_fire.MixinCreeperEntity,pl:mixin:APP:fabrication.mixins.json:b_utility.taggable_players.MixinCreeperEntity,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.entity.monster.CreeperEntity.func_70071_h_(CreeperEntity.java:149) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:fabrication.mixins.json:c_tweaks.creepers_explode_when_on_fire.MixinCreeperEntity,pl:mixin:APP:fabrication.mixins.json:b_utility.taggable_players.MixinCreeperEntity,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:697) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:abnormals_core.mixins.json:ServerWorldMixin,pl:mixin:APP:starlight.mixins.json:common.world.ServerWorldMixin,pl:mixin:APP:endergetic.mixins.json:ServerWorldMixin,pl:mixin:APP:quark.mixins.json:ServerWorldMixin,pl:mixin:APP:fabrication.mixins.json:c_tweaks.alt_absorption_sound.MixinServerWorld,pl:mixin:APP:fabrication.mixins.json:b_utility.item_despawn.MixinServerWorld,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.world.World.func_217390_a(World.java:736) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:starlight.mixins.json:common.world.WorldMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:470) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:abnormals_core.mixins.json:ServerWorldMixin,pl:mixin:APP:starlight.mixins.json:common.world.ServerWorldMixin,pl:mixin:APP:endergetic.mixins.json:ServerWorldMixin,pl:mixin:APP:quark.mixins.json:ServerWorldMixin,pl:mixin:APP:fabrication.mixins.json:c_tweaks.alt_absorption_sound.MixinServerWorld,pl:mixin:APP:fabrication.mixins.json:b_utility.item_despawn.MixinServerWorld,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1015) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixin.terraforged.json:common.MixinMinecraftServer,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:333) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:929) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixin.terraforged.json:common.MixinMinecraftServer,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:764) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixin.terraforged.json:common.MixinMinecraftServer,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:276) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixin.terraforged.json:common.MixinMinecraftServer,pl:mixin:A,pl:runtimedistcleaner:A}
	at java.lang.Thread.run(Thread.java:834) [?:?] {}
Caused by: java.lang.ClassCastException: class com.minecraftabnormals.savageandravage.common.entity.SporeCloudEntity cannot be cast to class net.minecraft.entity.projectile.ProjectileItemEntity (com.minecraftabnormals.savageandravage.common.entity.SporeCloudEntity and net.minecraft.entity.projectile.ProjectileItemEntity are in unnamed module of loader cpw.mods.modlauncher.TransformingClassLoader @7f4701b1)
	at com.mohistmc.entity.CraftCustomThrowableEntity.getHandle(CraftCustomThrowableEntity.java:23) ~[forge:?] {re:classloading}
	at com.mohistmc.entity.CraftCustomThrowableEntity.getHandle(CraftCustomThrowableEntity.java:9) ~[forge:?] {re:classloading}
	at org.bukkit.craftbukkit.v1_16_R3.entity.CraftProjectile.getShooter(CraftProjectile.java:15) ~[forge:?] {re:classloading}
	at com.Zrips.CMI.AllListeners.UserCuffedEvents.onProjectileLaunchEvent(UserCuffedEvents.java:96) ~[?:?] {re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading}
	at jdk.internal.reflect.GeneratedMethodAccessor201.invoke(Unknown Source) ~[?:?] {re:classloading,re:classloading}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {re:classloading}
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?] {}
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:315) ~[forge:?] {re:classloading}
	... 28 more
```

Mods:
```Save My Stronghold!, Fish in Planks, Abnormals Core, Buzzier Bees, Berry Good, Enhanced Mushrooms, Bayou Blues, Caelus API, Colytra, Better Badlands, Extra Boats, Create, YUNG's Better Caves, Addendum, TerraForged, Citadel, Alex's Mobs, YUNG's API, Environmental, Fabrication, Starlight, Voyage, Allurement, Caverns & Chasms, Forge, Waddles, Nether Extension, Dynamic Surroundings, Dynamic Surroundings: Sound Control, Dynamic Surroundings: Environs, Dynamic Surroundings: Mob Effects, Dash, Upgrade Aquatic, The Endergetic Expansion, Farmer's Delight, Dynmap, Repurposed Structures, Mouse Tweaks, Abundance, Toughness Bar, Lepton, Personality, Atmospheric, spark, Savage & Ravage, Leap, Autumnity, More Respawn Anchors, AutoRegLib, Quark, Abnormals Delight, WorldEdit, AppleSkin, Ferrite Core, Cherished Worlds, Chlorine, Overloaded Armor Bar, YUNG's Better Mineshafts, Step, OpenLoader```

**Comment by KR33PYK1NG** [comment]
Fixed in cf8f48d
