### ISSUE TITLE
newer builds wont work with resourceful bees

### ISSUE THREAD

**Issue by DeRp-MaSte5** [Teneted/Tenet#1055]
i have tested it and only newer builds (higher than 385) give a crash with resourceful bees

 Mixin apply failed resourcefulbees.mixins.json:MixinBeeEntity$MixinEnterBeehiveGoal -> net.minecraft.entity.passive.BeeEntity$EnterBeehiveGoal: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException @Shadow field beeEntity was not located in the target class net.minecraft.entity.passive.BeeEntity$EnterBeehiveGoal. Using refmap resourcefulbees.refmap.json
org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: @Shadow field beeEntity was not located in the target class net.minecraft.entity.passive.BeeEntity$EnterBeehiveGoal. Using refmap resourcefulbees.refmap.json
        at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachFields(MixinPreProcessorStandard.java:616) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown] {}
        at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:292) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown] {}
        at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:267) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown] {}
        at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1271) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown] {}
        at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:287) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown] {}
        at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown] {}
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:569) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown] {}
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown] {}
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:223) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown] {}
        at org.spongepowered.asm.mixin.transformer.MixinTransformationHandler.processClass(MixinTransformationHandler.java:121) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown] {}
        at org.spongepowered.asm.launch.MixinLaunchPlugin.processClass(MixinLaunchPlugin.java:131) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown] {}
        at cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:154) ~[modlauncher-8.0.9.jar:8.0.9+86+master.3cf110c] {}
        at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:85) ~[modlauncher-8.0.9.jar:?] {}
        at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-8.0.9.jar:?] {}
        at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:265) ~[modlauncher-8.0.9.jar:?] {}
        at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136) ~[modlauncher-8.0.9.jar:?] {re:classloading}
        at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98) ~[modlauncher-8.0.9.jar:?] {re:classloading}
        at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?] {}
        at net.minecraft.entity.EntityType.<clinit>(EntityType.java:154) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.world.gen.feature.DungeonsFeature.<clinit>(DungeonsFeature.java:24) ~[?:?] {re:classloading}
        at net.minecraft.world.gen.feature.Feature.<clinit>(Feature.java:37) ~[?:?] {re:classloading}
        at net.minecraft.world.gen.feature.Features.<clinit>(SourceFile:92) ~[?:?] {re:classloading}
        at net.minecraft.util.registry.WorldGenRegistries.func_243672_e(WorldGenRegistries.java:39) ~[?:?] {re:classloading}
        at net.minecraft.util.registry.WorldGenRegistries.lambda$static$8(WorldGenRegistries.java:89) ~[?:?] {re:classloading}
        at java.util.LinkedHashMap.forEach(LinkedHashMap.java:684) ~[?:?] {}
        at net.minecraft.util.registry.WorldGenRegistries.<clinit>(WorldGenRegistries.java:88) ~[?:?] {re:classloading}
        at net.minecraft.util.registry.Registry.<clinit>(Registry.java:464) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:runtimedistcleaner:A}
        at net.minecraft.util.registry.Bootstrap.func_151354_b(Bootstrap.java:41) ~[?:?] {re:classloading}
        at net.minecraft.server.Main.main(Main.java:120) ~[?:?] {re:classloading}
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?] {}
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?] {}
        at net.minecraftforge.fml.loading.FMLServerLaunchProvider.lambda$launchService$0(FMLServerLaunchProvider.java:51) ~[mohist-1.16.5-385-server.jar:36.0] {}
        at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
        at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {}
        at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {}
        at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:66) [mohist-1.16.5-385-server.jar:?] {}
        at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:63) [mohist-1.16.5-385-server.jar:?] {}
        at net.minecraftforge.server.ServerMain.main(ServerMain.java:60) [mohist-1.16.5-385-server.jar:?] {}

**Comment by KR33PYK1NG** [comment]
Fixed in f7f1f7a
