### ISSUE TITLE
[1.12.2] /TPS command not working

### ISSUE THREAD

**Issue by Zilacon** [Teneted/Tenet#107]
```
[21:44:01 WARN]: Unexpected exception while parsing console command "tps"
 org.bukkit.command.CommandException: Unhandled exception executing 'tps' in org.spigotmc.TicksPerSecondCommand(tps)
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[SimpleCommandMap.class:6b9b03a]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:748) ~[CraftServer.class:6b9b03a]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchServerCommand(CraftServer.java:734) [CraftServer.class:6b9b03a]
	at net.minecraft.server.dedicated.DedicatedServer.func_71333_ah(DedicatedServer.java:511) [nz.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:469) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:778) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:621) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:821) [?:1.8.0_242]
Caused by: java.lang.NullPointerException
	at org.spigotmc.TicksPerSecondCommand.mean(TicksPerSecondCommand.java:91) ~[TicksPerSecondCommand.class:6b9b03a]
	at org.spigotmc.TicksPerSecondCommand.execute(TicksPerSecondCommand.java:49) ~[TicksPerSecondCommand.class:6b9b03a]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:145) ~[SimpleCommandMap.class:6b9b03a]
	... 7 more
```

**Comment by TansuoTro** [comment]
What version of Mohist are you used

**Comment by Zilacon** [comment]
https://ci.codemc.io/job/Mohist-Community/job/Mohist-1.12.2/316/

**Comment by TansuoTro** [comment]
Ok, pls try use build#318

**Comment by Zilacon** [comment]
Same issue with build #318
```
[22:20:42 WARN]: Unexpected exception while parsing console command "tps"
 org.bukkit.command.CommandException: Unhandled exception executing 'tps' in org.spigotmc.TicksPerSecondCommand(tps)
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[SimpleCommandMap.class:c2aa55a]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:748) ~[CraftServer.class:c2aa55a]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchServerCommand(CraftServer.java:734) [CraftServer.class:c2aa55a]
	at net.minecraft.server.dedicated.DedicatedServer.func_71333_ah(DedicatedServer.java:511) [nz.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:469) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:778) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:621) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:821) [?:1.8.0_242]
Caused by: java.lang.NullPointerException
	at org.spigotmc.TicksPerSecondCommand.mean(TicksPerSecondCommand.java:91) ~[TicksPerSecondCommand.class:c2aa55a]
	at org.spigotmc.TicksPerSecondCommand.execute(TicksPerSecondCommand.java:49) ~[TicksPerSecondCommand.class:c2aa55a]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:145) ~[SimpleCommandMap.class:c2aa55a]
	... 7 more
```

**Comment by TansuoTro** [comment]
What plugin did you installed

**Comment by Zilacon** [comment]
```
[22:24:08 INFO]: Plugins (24): APOC-AutoRestart, APOC-CMD, APOC-CoreAPI, Apoc-Forecast, APOC-GlobalPlugins, APOC-PayDay, APOC-Revival, APOC-Transmission, APOC-WorldControl, CoreProtect, EmptyWorldGenerator, EnjinMinecraftPlugin, FastAsyncWorldEdit, GriefPreventionPlus, GroupManager, HolographicDisplays, KaisRandomTP, LagAssist, mcMMO, MultiWorld, Towny, WorldBorder, WorldEdit, WorldGuard
```

**Comment by TansuoTro** [comment]
ummmmmm, i can't find the problem, maybe you can use this plugin
[Click me](http://www.minerealms.cn/download/GetTPS.jar)
[From MCBBS](https://www.mcbbs.net/thread-214383-1-1.html)

**Comment by Zilacon** [comment]
...why would i use that?

**Comment by TansuoTro** [comment]
Because I couldn't find the problem, this plugin can get tps and as a temporary solution.

**Comment by TansuoTro** [comment]
Command:/gettps or tps, gtps, ttps

**Comment by Zilacon** [comment]
So i report an error with the tps command thats built into the server, and you tell me "yeah its broken, just use this crap plugin as a replacement".

Viewing the TPS is not an issue, theres 10 different commands on the server that show the TPS. However mohist shows dimension numbers, world names, processing time, and tps from the main server thread. Others only report TPS from the forge or bukkit threads. Which give different values.

Why would i use a plugin for something thats supposed to be built in?

**Comment by TansuoTro** [comment]
No problem, the author will fix it after seeing this iusse.
I just provide you a temporary solution, it is only used as a solution until the author fixes this problem :D

**Comment by Iltotore** [comment]
Have you tried `/forge tps` ?

**Comment by Zilacon** [comment]
> Have you tried /forge tps ?

Bruh...

> Viewing the TPS is not an issue, theres 10 different commands on the server that show the TPS.

I literally just said this...
