### ISSUE TITLE
[1.12.2] Multiple Unknown Crashes

### ISSUE THREAD

**Issue by Zilacon** [Teneted/Tenet#108]
```
java.util.ConcurrentModificationException
    at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:909)
    at java.util.ArrayList$Itr.next(ArrayList.java:859)
    at net.minecraft.server.management.PlayerChunkMap$3.computeNext(PlayerChunkMap.java:78)
    at net.minecraft.server.management.PlayerChunkMap$3.computeNext(PlayerChunkMap.java:71)
    at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:145)
    at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:140)
    at com.google.common.collect.ImmutableCollection$Builder.addAll(ImmutableCollection.java:436)
    at com.google.common.collect.ImmutableSet$Builder.addAll(ImmutableSet.java:534)
    at net.minecraftforge.common.ForgeChunkManager.getPersistentChunksIterableFor(ForgeChunkManager.java:150)
    at net.minecraft.world.World.getPersistentChunkIterable(World.java:4348)
    at net.minecraft.world.WorldServer.func_147456_g(WorldServer.java:635)
    at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:450)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:890)
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:468)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:778)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:621)
    at java.lang.Thread.run(Thread.java:821)
```
```
java.util.ConcurrentModificationException
    at java.util.LinkedList$ListItr.checkForComodification(LinkedList.java:966)
    at java.util.LinkedList$ListItr.remove(LinkedList.java:921)
    at net.minecraft.server.management.PlayerChunkMap.func_72693_b(PlayerChunkMap.java:208)
    at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:454)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:890)
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:468)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:778)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:621)
    at java.lang.Thread.run(Thread.java:821)
```
```
java.lang.NullPointerException: Ticking player
    at java.util.LinkedList$ListItr.next(LinkedList.java:893)
    at net.minecraft.entity.player.EntityPlayerMP.func_70071_h_(EntityPlayerMP.java:437)
    at net.minecraft.world.World.func_72866_a(World.java:2363)
    at net.minecraft.world.World.func_72870_g(World.java:2314)
    at net.minecraft.world.WorldServer.func_184147_l(WorldServer.java:884)
    at net.minecraft.world.World.func_72939_s(World.java:2064)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:854)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:903)
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:468)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:778)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:621)
    at java.lang.Thread.run(Thread.java:821)
```

Crash Reports:
[crash-2020-02-27_16.40.57-server.txt](https://github.com/Mohist-Community/Mohist/files/4265464/crash-2020-02-27_16.40.57-server.txt)
[crash-2020-02-27_22.03.04-server.txt](https://github.com/Mohist-Community/Mohist/files/4265465/crash-2020-02-27_22.03.04-server.txt)
[crash-2020-02-27_14.58.55-server.txt](https://github.com/Mohist-Community/Mohist/files/4265466/crash-2020-02-27_14.58.55-server.txt)

**Comment by Mgazul** [comment]
I think this is related to TickProfiler, more information is needed
