### ISSUE TITLE
Error with UltimateSkyblock

### ISSUE THREAD

**Issue by Kompanion8** [Teneted/Tenet#109]
On spigot this plugin starts normaly
But on Mohist - no :(
Version used: 2.3.4 and 2.3.5
Mohist version: latest

> Error occurred while enabling uSkyBlock v2.7.4 (Is it up to date?)
java.lang.NullPointerException: null
	at us.talabrek.ultimateskyblock.utils.reflection.ReflectionUtil.getPackageName(ReflectionUtil.java:78) ~[?:?]
	at us.talabrek.ultimateskyblock.utils.nbt.CraftBukkitNBTTagger.getNBTTagParser(CraftBukkitNBTTagger.java:86) ~[?:?]
	at us.talabrek.ultimateskyblock.utils.nbt.CraftBukkitNBTTagger.addNBTTag(CraftBukkitNBTTagger.java:49) ~[?:?]
	at us.talabrek.ultimateskyblock.utils.nbt.NBTUtil.addNBTTag(NBTUtil.java:54) ~[?:?]
	at us.talabrek.ultimateskyblock.utils.util.ItemStackUtil.createItemsWithProbabilty(ItemStackUtil.java:43) ~[?:?]
	at us.talabrek.ultimateskyblock.challenge.ChallengeFactory.createReward(ChallengeFactory.java:113) ~[?:?]
	at us.talabrek.ultimateskyblock.challenge.ChallengeFactory.createChallenge(ChallengeFactory.java:64) ~[?:?]
	at us.talabrek.ultimateskyblock.challenge.Rank.<init>(Rank.java:31) ~[?:?]
	at us.talabrek.ultimateskyblock.challenge.ChallengeFactory.createRankMap(ChallengeFactory.java:125) ~[?:?]
	at us.talabrek.ultimateskyblock.challenge.ChallengeLogic.<init>(ChallengeLogic.java:69) ~[?:?]
	at us.talabrek.ultimateskyblock.uSkyBlock.reloadConfigs(uSkyBlock.java:1008) ~[?:?]
	at us.talabrek.ultimateskyblock.uSkyBlock.onEnable(uSkyBlock.java:222) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:177) ~[JavaPlugin.class:ec1b975]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:327) [JavaPluginLoader.class:ec1b975]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:399) [SimplePluginManager.class:ec1b975]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:474) [CraftServer.class:ec1b975]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:415) [CraftServer.class:ec1b975]
	at net.minecraft.world.storage.SaveHandler.initBukkitData(SaveHandler.java:394) [bfb.class:?]
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:345) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:319) [nz.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:587) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_241]

**Comment by CraftDream** [comment]
I see from the error report that you are using uSkyBlock v2.7.4
Please try `v2.7.5-bukkit-1.12-pre-20180725` [Click](https://github.com/rlf/uSkyBlock/releases/tag/v2.7.5-bukkit-1.12-pre-20180725)
It is the last version of uSkyBlock that supports Minecraft 1.12.2

**Comment by Kompanion8** [comment]
I used 2.7.5 too.  Same error

**Comment by CraftDream** [comment]
Is this error running on Minecraft1.12.2?

**Comment by Kompanion8** [comment]
Yes

**Comment by CraftDream** [comment]
What version of Mohist do you use?

**Comment by Kompanion8** [comment]
Latest

**Comment by Mgazul** [comment]
[MuSkyBlock](https://github.com/Mohist-Community/MuSkyBlock/releases/download/pre/MuSkyBlock-1.0-SNAPSHOT.jar)
