### ISSUE TITLE
[1.12.2] PacketListenerAPI plugin don't work

### ISSUE THREAD

**Issue by Ru-Nan-i** [Teneted/Tenet#1117]
[22:21:56] [Server thread/ERROR] [Mohist]: Could not load plugins\PacketListenerAPI_v3.8.0-SNAPSHOT.jar in folder plugins because plugin invalid
org.bukkit.plugin.InvalidPluginException: Cannot find main class `org.inventivetalent.packetlistener.PacketListenerPlugin'
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:61) ~[PluginClassLoader.class:?]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:126) ~[JavaPluginLoader.class:?]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:323) ~[SimplePluginManager.class:?]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:245) [SimplePluginManager.class:?]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.loadPlugins(CraftServer.java:392) [CraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:345) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:316) [nz.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:596) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_281]
Caused by: java.lang.ClassNotFoundException: Failed to remap class org.inventivetalent.packetlistener.PacketListenerPlugin
	at org.bukkit.plugin.java.PluginClassLoader.remappedFindClass(PluginClassLoader.java:190) ~[PluginClassLoader.class:?]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:104) ~[PluginClassLoader.class:?]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:81) ~[PluginClassLoader.class:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_281]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_281]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_281]
	at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_281]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:59) ~[PluginClassLoader.class:?]
	... 8 more
Caused by: java.lang.IllegalArgumentException
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:185) ~[asm-debug-all-5.2.jar:5.2]
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:168) ~[asm-debug-all-5.2.jar:5.2]
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:439) ~[asm-debug-all-5.2.jar:5.2]
	at com.mohistmc.bukkit.nms.remappers.MohistJarRemapper.remapClassFile(MohistJarRemapper.java:156) ~[MohistJarRemapper.class:?]
	at org.bukkit.plugin.java.PluginClassLoader.remappedFindClass(PluginClassLoader.java:160) ~[PluginClassLoader.class:?]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:104) ~[PluginClassLoader.class:?]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:81) ~[PluginClassLoader.class:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_281]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_281]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_281]
	at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_281]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:59) ~[PluginClassLoader.class:?]
	... 8 more

https://www.spigotmc.org/resources/api-packetlistenerapi.2930/

**Comment by Mgazul** [comment]
Versions after 3.8 require Java 11+
But mohist only supports 1.8, so you need to use PacketListenerAPI_v3.7.9-SNAPSHOT
