### ISSUE TITLE
[1.16.5] server randomly crashes

### ISSUE THREAD

**Issue by semenishchev** [Teneted/Tenet#1126]
Crash report:
`
java.lang.NoSuchMethodError: net.minecraft.inventory.container.StonecutterContainer.func_217076_f()Ljava/util/List;
	at net.minecraft.inventory.container.StonecutterContainer.func_75140_a(StonecutterContainer.java:157) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.network.play.ServerPlayNetHandler.func_147338_a(ServerPlayNetHandler.java:2401) ~[?:?] {re:classloading}
	at net.minecraft.network.play.client.CEnchantItemPacket.func_148833_a(SourceFile:22) ~[?:?] {re:classloading}
	at net.minecraft.network.play.client.CEnchantItemPacket.func_148833_a(SourceFile:8) ~[?:?] {re:classloading}
	at net.minecraft.network.PacketThreadUtil.func_225383_a(PacketThreadUtil.java:22) ~[?:?] {re:classloading}
	at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?] {re:classloading}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(ThreadTaskExecutor.java:136) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?] {re:classloading}
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:874) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:184) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(ThreadTaskExecutor.java:109) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:857) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:851) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(ThreadTaskExecutor.java:97) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:836) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:769) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:277) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_282] {}`
	Mods: NetherPortalFix and Luckperms pluigin

**Comment by semenishchev** [comment]
Upd: crashes with no mods and plugins
