### ISSUE TITLE
Deployer [CreateMod] and bucket fill event. 

### ISSUE THREAD

**Issue by muriplz** [Teneted/Tenet#1174]
Mohist 453
Create mod 0.3e/0.3.1
also tried:
LuckPerms
GriefDefender
Deployers have trouble when getting liquids into a bucket, there is no log errors apart from when adding a protection plugin it says "Could not register BucketFillEvent", on plugin debug the action is recognized and accepted and still does not work. (example: milking a cow)

**Comment by Mgazul** [comment]
Provide a complete log

**Comment by muriplz** [comment]
```
06.04 16:36:23 [Server] ERROR Could not pass event PlayerBucketFillEvent to GriefDefender v1.5.10
06.04 16:36:23 [Server] INFO org.bukkit.event.EventException: null
06.04 16:36:23 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:319) ~[forge:?] {re:classloading}
06.04 16:36:23 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[forge:?] {re:classloading}
06.04 16:36:23 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[forge:?] {re:classloading}
06.04 16:36:23 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:574) ~[forge:?] {re:classloading}
06.04 16:36:23 [Server] INFO at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.getPlayerBucketEvent(CraftEventFactory.java:389) ~[forge:?] {re:classloading}
06.04 16:36:23 [Server] INFO at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callPlayerBucketFillEvent(CraftEventFactory.java:366) ~[forge:?] {re:classloading}
06.04 16:36:23 [Server] INFO at net.minecraft.item.BucketItem.func_77659_a(BucketItem.java:80) ~[?:?] {re:classloading,xf:fml:forge:bucketitem}
06.04 16:36:23 [Server] INFO at com.simibubi.create.content.contraptions.components.deployer.DeployerHandler.activateInner(DeployerHandler.java:294) ~[create:mc1.16.5_v0.3.1+122] {re:classloading}
06.04 16:36:23 [Server] INFO at com.simibubi.create.content.contraptions.components.deployer.DeployerHandler.activate(DeployerHandler.java:118) ~[create:mc1.16.5_v0.3.1+122] {re:classloading}
06.04 16:36:23 [Server] INFO at com.simibubi.create.content.contraptions.components.deployer.DeployerTileEntity.activate(DeployerTileEntity.java:260) ~[create:mc1.16.5_v0.3.1+122] {re:classloading}
06.04 16:36:23 [Server] INFO at com.simibubi.create.content.contraptions.components.deployer.DeployerTileEntity.func_73660_a(DeployerTileEntity.java:188) ~[create:mc1.16.5_v0.3.1+122] {re:classloading}
06.04 16:36:23 [Server] INFO at net.minecraft.world.World.func_217391_K(World.java:656) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
06.04 16:36:23 [Server] INFO at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:459) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
06.04 16:36:23 [Server] INFO at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1017) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
06.04 16:36:23 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:333) ~[?:?] {re:classloading,pl:accesstransformer:B}
06.04 16:36:23 [Server] INFO at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:926) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
06.04 16:36:23 [Server] INFO at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:759) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
06.04 16:36:23 [Server] INFO at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:271) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
06.04 16:36:23 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_282] {}
06.04 16:36:23 [Server] INFO Caused by: java.lang.AbstractMethodError: Method com/simibubi/create/content/contraptions/components/deployer/DeployerHandler$ItemUseWorld.getMinecraftWorld()Lnet/minecraft/world/server/ServerWorld; is abstract
06.04 16:36:23 [Server] INFO at com.simibubi.create.content.contraptions.components.deployer.DeployerHandler$ItemUseWorld.getMinecraftWorld(DeployerHandler.java) ~[create:mc1.16.5_v0.3.1+122] {re:classloading}
06.04 16:36:23 [Server] INFO at org.bukkit.craftbukkit.v1_16_R3.block.CraftBlock.getWorld(CraftBlock.java:85) ~[forge:?] {re:classloading}
06.04 16:36:23 [Server] INFO at org.bukkit.craftbukkit.v1_16_R3.block.CraftBlock.getRelative(CraftBlock.java:242) ~[forge:?] {re:classloading}
06.04 16:36:23 [Server] INFO at org.bukkit.craftbukkit.v1_16_R3.block.CraftBlock.getRelative(CraftBlock.java:252) ~[forge:?] {re:classloading}
06.04 16:36:23 [Server] INFO at org.bukkit.craftbukkit.v1_16_R3.block.CraftBlock.getRelative(CraftBlock.java:247) ~[forge:?] {re:classloading}
06.04 16:36:23 [Server] INFO at com.griefdefender.listener.PlayerEventHandler.onPlayerBucketEvent(PlayerEventHandler.java:749) ~[?:?] {re:classloading,re:classloading,re:classloading,re:classloading,re:classloading}
06.04 16:36:23 [Server] INFO at com.griefdefender.listener.PlayerEventHandler.onPlayerBucketFillEvent(PlayerEventHandler.java:732) ~[?:?] {re:classloading,re:classloading,re:classloading,re:classloading,re:classloading}
06.04 16:36:23 [Server] INFO at sun.reflect.GeneratedMethodAccessor102.invoke(Unknown Source) ~[?:?] {}
```

**Comment by muriplz** [comment]
it got fixed(even with the prot plugin), but still gives out some log errors (only with the protection plugin):
```
08.04 17:29:56 [Server] ERROR Could not pass event PlayerBucketFillEvent to GriefDefender v1.5.10
08.04 17:29:56 [Server] INFO org.bukkit.event.EventException: null
08.04 17:29:56 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:319) ~[forge:?] {re:classloading}
08.04 17:29:56 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[forge:?] {re:classloading}
08.04 17:29:56 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[forge:?] {re:classloading}
08.04 17:29:56 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:574) ~[forge:?] {re:classloading}
08.04 17:29:56 [Server] INFO at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.getPlayerBucketEvent(CraftEventFactory.java:389) ~[forge:?] {re:classloading}
08.04 17:29:56 [Server] INFO at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callPlayerBucketFillEvent(CraftEventFactory.java:366) ~[forge:?] {re:classloading}
08.04 17:29:56 [Server] INFO at net.minecraft.item.BucketItem.func_77659_a(BucketItem.java:80) ~[?:?] {re:classloading,xf:fml:forge:bucketitem}
08.04 17:29:56 [Server] INFO at com.simibubi.create.content.contraptions.components.deployer.DeployerHandler.activateInner(DeployerHandler.java:294) ~[create:mc1.16.5_v0.3.1+122] {re:classloading}
08.04 17:29:56 [Server] INFO at com.simibubi.create.content.contraptions.components.deployer.DeployerHandler.activate(DeployerHandler.java:118) ~[create:mc1.16.5_v0.3.1+122] {re:classloading}
08.04 17:29:56 [Server] INFO at com.simibubi.create.content.contraptions.components.deployer.DeployerTileEntity.activate(DeployerTileEntity.java:260) ~[create:mc1.16.5_v0.3.1+122] {re:classloading}
08.04 17:29:56 [Server] INFO at com.simibubi.create.content.contraptions.components.deployer.DeployerTileEntity.func_73660_a(DeployerTileEntity.java:188) ~[create:mc1.16.5_v0.3.1+122] {re:classloading}
08.04 17:29:56 [Server] INFO at net.minecraft.world.World.func_217391_K(World.java:656) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
08.04 17:29:56 [Server] INFO at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:459) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
08.04 17:29:56 [Server] INFO at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1017) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
08.04 17:29:56 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:333) ~[?:?] {re:classloading,pl:accesstransformer:B}
08.04 17:29:56 [Server] INFO at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:926) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
08.04 17:29:56 [Server] INFO at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:759) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
08.04 17:29:56 [Server] INFO at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:271) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
08.04 17:29:56 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_282] {}
08.04 17:29:56 [Server] INFO Caused by: java.lang.StackOverflowError
08.04 17:29:56 [Server] INFO at net.minecraft.world.IWorld.getMinecraftWorld(IWorld.java:59) ~[?:?] {re:classloading}
08.04 17:29:56 [Server] INFO at net.minecraft.world.IWorld.getMinecraftWorld(IWorld.java:59) ~[?:?] {re:classloading}
08.04 17:29:56 [Server] INFO at net.minecraft.world.IWorld.getMinecraftWorld(IWorld.java:59) ~[?:?] {re:classloading}
08.04 17:29:56 [Server] INFO at net.minecraft.world.IWorld.getMinecraftWorld(IWorld.java:59) ~[?:?] {re:classloading}
08.04 17:29:56 [Server] INFO at net.minecraft.world.IWorld.getMinecraftWorld(IWorld.java:59) ~[?:?] {re:classloading}
08.04 17:29:56 [Server] INFO at net.minecraft.world.IWorld.getMinecraftWorld(IWorld.java:59) ~[?:?] {re:classloading}
08.04 17:29:56 [Server] INFO at net.minecraft.world.IWorld.getMinecraftWorld(IWorld.java:59) ~[?:?] {re:classloading}
08.04 17:29:56 [Server] INFO at net.minecraft.world.IWorld.getMinecraftWorld(IWorld.java:59) ~[?:?] {re:classloading}
```
