### ISSUE TITLE
[1.12.2] Unable to start. InvocationTargetException

### ISSUE THREAD

**Issue by Zilacon** [Teneted/Tenet#119]
```
A problem occurred running the Server launcher.
java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:82)
    at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:37)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at red.mohist.Mohist.main(Mohist.java:49)
Caused by: net.minecraftforge.fml.relauncher.FMLSecurityManager$ExitTrappedException
    at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:49)
    at java.lang.SecurityManager.checkExit(SecurityManager.java:761)
    at java.lang.Runtime.exit(Runtime.java:108)
    at java.lang.System.exit(System.java:345)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:138)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
    ... 11 more
```

**Comment by Mgazul** [comment]
Unable to judge, need latest.log

**Comment by Zilacon** [comment]
@Mgazul 
[2020-03-02-1.log](https://github.com/Mohist-Community/Mohist/files/4280445/2020-03-02-1.log)
