### ISSUE TITLE
[1.12.2] Doesn't work plugin in mohist

### ISSUE THREAD

**Issue by Ru-Nan-i** [Teneted/Tenet#1197]
I use mohist last version
 plugin : https://www.spigotmc.org/resources/nicknamer-integrated-api.5341/ 
 
log:
[13:42:13 ERROR]: Error occurred while enabling NickNamer v3.18.6-SNAPSHOT (Is it up to date?)
 java.lang.ExceptionInInitializerError: null
        at org.inventivetalent.nicknamer.api.NickNamerAPI.init(NickNamerAPI.java:140) ~[?:?]
        at org.inventivetalent.apihelper.RegisteredAPI.init(RegisteredAPI.java:55) ~[?:?]
        at org.inventivetalent.apihelper.APIManager.initAPI(APIManager.java:96) ~[?:?]
        at org.inventivetalent.apihelper.APIManager.initAPI(APIManager.java:127) ~[?:?]
        at org.inventivetalent.nicknamer.NickNamerPlugin.onEnable(NickNamerPlugin.java:181) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:177) ~[JavaPlugin.class:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:318) [JavaPluginLoader.class:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:399) [SimplePluginManager.class:?]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:477) [CraftServer.class:?]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:418) [CraftServer.class:?]
        at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:389) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:316) [nz.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:596) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_281]
Caused by: java.lang.IllegalArgumentException: class cannot be null
        at org.inventivetalent.nicknamer.reflection.resolver.MemberResolver.<init>(MemberResolver.java:20) ~[?:?]
        at org.inventivetalent.nicknamer.reflection.resolver.MethodResolver.<init>(MethodResolver.java:14) ~[?:?]
        at org.inventivetalent.nicknamer.api.PacketListener.<clinit>(PacketListener.java:69) ~[?:?]
        ... 14 more

**Comment by Mgazul** [comment]
Update your plugin

**Comment by Ru-Nan-i** [comment]
> Update your plugin

Which version should I use?

**Comment by Ru-Nan-i** [comment]
> Update your plugin

I update my plugin but doens't work it
