### ISSUE TITLE
[1.16.5] Interacting with forge entities by plugin

### ISSUE THREAD

**Issue by MrHell228** [Teneted/Tenet#1207]
There is 1 request:
- Create forge entities registry in bukkit so it could be accessed in plugin by EntityType.valueOf() like forge items does (with Material.valueOf()). At the moment all forge entitities are 'UNKNOWN' constant in bukkit.

And 1 issue:
- When I hit forge entity, EntityDamageByEntityEvent (bukkit) isn't calling. Maybe it's related to the problem above (but when the UNKNOWN entity hit me, that event works fine).

**Comment by KR33PYK1NG** [comment]
Are you sure about UNKNOWN entity types? EntityType.valueOf(...) should work just fine.

**Comment by MrHell228** [comment]
Oh, I seem to get it. EntityType.valueOf () works, however in bukkit events all forge entity types are defined as UNKNOWN. Also, I cannot spawn a mob through World.spawnEntity (loc, type) (bukkit), when I use the type obtained through EntityType.valueOf (), attach the error code below (in the defence method, I try to spawn a mob)

`Caused by: java.lang.IllegalArgumentException: Cannot spawn an entity for com.mohistmc.entity.CraftCustomEntity
        at org.bukkit.craftbukkit.v1_16_R3.CraftWorld.createEntity(CraftWorld.java:1811) ~[forge:1.16.5-475] {re:classloading}
        at org.bukkit.craftbukkit.v1_16_R3.CraftWorld.spawn(CraftWorld.java:1836) ~[forge:1.16.5-475] {re:classloading}
        at org.bukkit.craftbukkit.v1_16_R3.CraftWorld.spawn(CraftWorld.java:1416) ~[forge:1.16.5-475] {re:classloading}
        at org.bukkit.craftbukkit.v1_16_R3.CraftWorld.spawnEntity(CraftWorld.java:658) ~[forge:1.16.5-475] {re:classloading}
        at mod.event.ItemEvents.defence(ItemEvents.java:217) ~[?:?] {re:classloading,re:classloading,re:classloading}
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {re:classloading}
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?] {re:classloading}
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {re:classloading}
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?] {}
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[forge:?] {re:classloading}
        ... 45 more`
