### ISSUE TITLE
1.16.5 Java update

### ISSUE THREAD

**Issue by LLIaMMaH** [Teneted/Tenet#1208]
https://wiki.mohistmc.com#/install/windows - This software requires Java 8.
https://wiki.mohistmc.com#/install/linux - Mohist 1.12.2 requires Java 8 and Mohist 1.16.5 requires up to Java 8.

Mohist 1.16.5 469 and higher require higher version java.

Downloaded https://www.oracle.com/java/technologies/javase-jdk11-downloads.html, but even with it the server does not start.
`
 __    __   ______   __  __   __   ______   ______
/\ "-./  \ /\  __ \ /\ \_\ \ /\ \ /\  ___\ /\__  _\
\ \ \-./\ \\ \ \/\ \\ \  __ \\ \ \\ \___  \\/_/\ \/
 \ \_\ \ \_\\ \_____\\ \_\ \_\\ \_\\/\_____\  \ \_\
  \/_/  \/_/ \/_____/ \/_/\/_/ \/_/ \/_____/   \/_/

                                      Приветствуем в Mohist 1.16.5 ! - Команда Разработки Mohist
Проверка библиотек, пожалуйста подождите...
С библиотеками всё в порядке :) !
Проверка установки, пожалуйста подождите.
[Mohist] Создание jar файла для сервера Forge.  Это займет от нескольких секунд до 1 минуты.
Процесс проверки установки завершен ! Сервер запустится через несколько секунд...
Проверка обновлений...
Если вы хотите отключить проверку обновлений, задайте для check_update в mohist-config/mohist.yml аргумент false
Обновлений не найдено, последняя версия: (1-1.16.5-471) текущая версия: (1-1.16.5-471)
[18:42:07 INFO]: ModLauncher running: args [--gameDir, ., --launchTarget, fmlserver, --fml.forgeVersion, 36.1.4, --fml.mcpVersion, 20210115.111550, --fml.mcVersion, 1.16.5, --fml.forgeGroup, net.minecraftforge]
[18:42:07 INFO]: ModLauncher 8.0.9+86+master.3cf110c starting: java version 11.0.10 by Oracle Corporation
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by cpw.mods.modlauncher.SecureJarHandler (file:/G:/MineCraft/Server/MohistMC/1.16.5/20210414-LookAround/libraries/cpw/mods/modlauncher/8.0.9/modlauncher-8.0.9.jar) to field java.util.jar.Manifest.jv
WARNING: Please consider reporting this to the maintainers of cpw.mods.modlauncher.SecureJarHandler
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[18:42:08 INFO]: Added Lets Encrypt root certificates as additional trust
[18:42:08 INFO]: SpongePowered MIXIN Subsystem Version=0.8.2 Source=file:/G:/MineCraft/Server/MohistMC/1.16.5/20210414-LookAround/libraries/org/spongepowered/mixin/0.8.2/mixin-0.8.2.jar Service=ModLauncher Env=SERVER
[18:42:09 INFO]: [jdk.nashorn.api.scripting.NashornScriptEngine:<init>:143]: Warning: Nashorn engine is planned to be removed from a future JDK release
[18:42:09 INFO]: [jdk.nashorn.api.scripting.NashornScriptEngine:<init>:143]: Warning: Nashorn engine is planned to be removed from a future JDK release
[18:42:09 INFO]: [jdk.nashorn.api.scripting.NashornScriptEngine:<init>:143]: Warning: Nashorn engine is planned to be removed from a future JDK release
[18:42:09 INFO]: [jdk.nashorn.api.scripting.NashornScriptEngine:<init>:143]: Warning: Nashorn engine is planned to be removed from a future JDK release
[18:42:09 INFO]: [jdk.nashorn.api.scripting.NashornScriptEngine:<init>:143]: Warning: Nashorn engine is planned to be removed from a future JDK release
[18:42:10 INFO]: [jdk.nashorn.api.scripting.NashornScriptEngine:<init>:143]: Warning: Nashorn engine is planned to be removed from a future JDK release
[18:42:10 INFO]: [jdk.nashorn.api.scripting.NashornScriptEngine:<init>:143]: Warning: Nashorn engine is planned to be removed from a future JDK release
[18:42:10 INFO]: [jdk.nashorn.api.scripting.NashornScriptEngine:<init>:143]: Warning: Nashorn engine is planned to be removed from a future JDK release
[18:42:10 INFO]: [jdk.nashorn.api.scripting.NashornScriptEngine:<init>:143]: Warning: Nashorn engine is planned to be removed from a future JDK release
[18:42:10 INFO]: [jdk.nashorn.api.scripting.NashornScriptEngine:<init>:143]: Warning: Nashorn engine is planned to be removed from a future JDK release
[18:42:10 INFO]: [jdk.nashorn.api.scripting.NashornScriptEngine:<init>:143]: Warning: Nashorn engine is planned to be removed from a future JDK release
[18:42:10 INFO]: [jdk.nashorn.api.scripting.NashornScriptEngine:<init>:143]: Warning: Nashorn engine is planned to be removed from a future JDK release
[18:42:10 INFO]: [org.antlr.v4.runtime.ConsoleErrorListener:syntaxError:38]: line 1:0 token recognition error at: '~'
[18:42:11 INFO]: Successfully loaded Mixin Connector [shetiphian.core.mixins.MixinConnector]
[18:42:11 INFO]: Successfully loaded Mixin Connector [vazkii.botania.common.MixinConnector]
[18:42:11 INFO]: Successfully loaded Mixin Connector [vazkii.patchouli.common.MixinConnector]
[18:42:11 INFO]: Launching target 'fmlserver' with arguments [--gameDir, .]
[18:42:14 INFO]: Patching DataPackRegistries#<init>
[SolarFlux]: Patching DataPackRegistries#<init>
[Serene Seasons Transformer]: Transforming func_201854_a in net/minecraft/world/biome/Biome
[Serene Seasons Transformer]: Patched 1 calls
[Serene Seasons Transformer]: Transforming func_201850_b in net/minecraft/world/biome/Biome
[Serene Seasons Transformer]: Patched 1 calls
[Serene Seasons Transformer]: Transforming func_201854_a in net/minecraft/world/biome/Biome
[Serene Seasons Transformer]: Patched 1 calls
[Serene Seasons Transformer]: Transforming func_201850_b in net/minecraft/world/biome/Biome
[Serene Seasons Transformer]: Patched 1 calls
[Serene Seasons Transformer]: Transforming func_176224_k in net/minecraft/block/CauldronBlock
[Serene Seasons Transformer]: Patched 1 calls
[Serene Seasons Transformer]: Transforming func_70636_d in net/minecraft/entity/passive/SnowGolemEntity
[Serene Seasons Transformer]: Patched 2 calls
[18:42:27 WARN]: Error loading class: javafx/util/Pair (java.lang.ClassNotFoundException: null)
Exception in thread "main" [18:42:27 INFO]: [java.lang.ThreadGroup:uncaughtException:1050]: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
[18:42:27 INFO]: [java.lang.ThreadGroup:uncaughtException:1050]:        at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:39)
[18:42:27 INFO]: [java.lang.ThreadGroup:uncaughtException:1050]:        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
[18:42:27 INFO]: [java.lang.ThreadGroup:uncaughtException:1050]:        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
[18:42:27 INFO]: [java.lang.ThreadGroup:uncaughtException:1050]:        at cpw.mods.modlauncher.Launcher.run(Launcher.java:82)
[18:42:27 INFO]: [java.lang.ThreadGroup:uncaughtException:1050]:        at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)
[18:42:27 INFO]: [java.lang.ThreadGroup:uncaughtException:1050]:        at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:66)
[18:42:27 INFO]: [java.lang.ThreadGroup:uncaughtException:1050]:        at net.minecraftforge.server.ServerMain.main(ServerMain.java:60)
[18:42:27 INFO]: [java.lang.ThreadGroup:uncaughtException:1059]: Caused by: java.lang.reflect.InvocationTargetException
[18:42:27 INFO]: [java.lang.ThreadGroup:uncaughtException:1059]:        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[18:42:27 INFO]: [java.lang.ThreadGroup:uncaughtException:1059]:        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[18:42:27 INFO]: [java.lang.ThreadGroup:uncaughtException:1059]:        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[18:42:27 INFO]: [java.lang.ThreadGroup:uncaughtException:1059]:        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[18:42:27 INFO]: [java.lang.ThreadGroup:uncaughtException:1059]:        at net.minecraftforge.fml.loading.FMLServerLaunchProvider.lambda$launchService$0(FMLServerLaunchProvider.java:51)
[18:42:27 INFO]: [java.lang.ThreadGroup:uncaughtException:1059]:        at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
[18:42:27 INFO]: [java.lang.ThreadGroup:uncaughtException:1059]:        ... 6 more
[18:42:27 INFO]: [java.lang.Throwable:printStackTrace:648]: Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
[18:42:27 INFO]: [java.lang.Throwable:printStackTrace:648]:     at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
[18:42:27 INFO]: [java.lang.Throwable:printStackTrace:648]:     at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:223)
[18:42:27 INFO]: [java.lang.Throwable:printStackTrace:648]:     at org.spongepowered.asm.mixin.transformer.MixinTransformationHandler.processClass(MixinTransformationHandler.java:121)
[18:42:27 INFO]: [java.lang.Throwable:printStackTrace:648]:     at org.spongepowered.asm.launch.MixinLaunchPlugin.processClass(MixinLaunchPlugin.java:131)
[18:42:27 INFO]: [java.lang.Throwable:printStackTrace:648]:     at cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:154)
[18:42:27 INFO]: [java.lang.Throwable:printStackTrace:648]:     at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:85)
[18:42:27 INFO]: [java.lang.Throwable:printStackTrace:648]:     at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120)
[18:42:27 INFO]: [java.lang.Throwable:printStackTrace:648]:     at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:265)
[18:42:27 INFO]: [java.lang.Throwable:printStackTrace:648]:     at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136)
[18:42:27 INFO]: [java.lang.Throwable:printStackTrace:648]:     at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98)
[18:42:27 INFO]: [java.lang.Throwable:printStackTrace:648]:     at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
[18:42:27 INFO]: [java.lang.Throwable:printStackTrace:648]:     at net.minecraft.util.registry.Registry.func_218353_F(Registry.java:159)
[18:42:27 INFO]: [java.lang.Throwable:printStackTrace:648]:     at net.minecraft.util.registry.Registry.lambda$static$51(Registry.java:466)
[18:42:27 INFO]: [java.lang.Throwable:printStackTrace:648]:     at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:684)
[18:42:27 INFO]: [java.lang.Throwable:printStackTrace:648]:     at net.minecraft.util.registry.Registry.<clinit>(Registry.java:465)
[18:42:27 INFO]: [java.lang.Throwable:printStackTrace:648]:     at net.minecraft.util.registry.Bootstrap.func_151354_b(Bootstrap.java:41)
[18:42:27 INFO]: [java.lang.Throwable:printStackTrace:648]:     at net.minecraft.server.Main.main(Main.java:118)
[18:42:27 INFO]: [java.lang.Throwable:printStackTrace:648]:     ... 12 more
[18:42:27 INFO]: [java.lang.Throwable:printStackTrace:671]: Caused by: org.spongepowered.asm.mixin.throwables.ClassMetadataNotFoundException: javafx.util.Pair
[18:42:27 INFO]: [java.lang.Throwable:printStackTrace:671]:     at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transformMethod(MixinPreProcessorStandard.java:741)
[18:42:27 INFO]: [java.lang.Throwable:printStackTrace:671]:     at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transform(MixinPreProcessorStandard.java:726)
[18:42:27 INFO]: [java.lang.Throwable:printStackTrace:671]:     at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:297)
[18:42:27 INFO]: [java.lang.Throwable:printStackTrace:671]:     at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:267)
[18:42:27 INFO]: [java.lang.Throwable:printStackTrace:671]:     at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1271)
[18:42:27 INFO]: [java.lang.Throwable:printStackTrace:671]:     at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:287)
[18:42:27 INFO]: [java.lang.Throwable:printStackTrace:671]:     at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
[18:42:27 INFO]: [java.lang.Throwable:printStackTrace:671]:     at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:569)
[18:42:27 INFO]: [java.lang.Throwable:printStackTrace:671]:     at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351)
[18:42:27 INFO]: [java.lang.Throwable:printStackTrace:671]:     ... 28 more
Press any key to continue . . .`

**Comment by KR33PYK1NG** [comment]
It seems that you're lacking JavaFX libraries along with your Java 11 installation.
Regular Java and JavaFX are split since Java 9.

**Comment by LLIaMMaH** [comment]
Подскажите, в wiki будет исправлена информация, что конкретно нужно устанавливать для новых версий ядра?

Tell me, in the wiki the information will be corrected, what exactly needs to be installed for new versions of the kernel?
