### ISSUE TITLE
Fresh 1.16.5 Server crash

### ISSUE THREAD

**Issue by fwis1** [Teneted/Tenet#1218]
There seems to have been another post about an hour ago, but the console messages here seem to be different.
```17.04 18:43:13 [Multicraft] Loading server properties
17.04 18:43:13 [Multicraft] Starting server!
17.04 18:43:13 [Multicraft] Loaded config for "Custom JAR (Place "custom.jar" in base directory)"
17.04 18:43:14 [Multicraft] Updating eula.txt file
17.04 18:43:14 [Server] INFO Error: A JNI error has occurred, please check your installation and try again
17.04 18:43:14 [Server] INFO Exception in thread "main" java.lang.UnsupportedClassVersionError: net/minecraftforge/server/ServerMain has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
17.04 18:43:14 [Server] INFO at java.lang.ClassLoader.defineClass1(Native Method)
17.04 18:43:14 [Server] INFO at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
17.04 18:43:14 [Server] INFO at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
17.04 18:43:14 [Server] INFO at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
17.04 18:43:14 [Server] INFO at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
17.04 18:43:14 [Server] INFO at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
17.04 18:43:14 [Server] INFO at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
17.04 18:43:14 [Server] INFO at java.security.AccessController.doPrivileged(Native Method)
17.04 18:43:14 [Server] INFO at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
17.04 18:43:14 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
17.04 18:43:14 [Server] INFO at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
17.04 18:43:14 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
17.04 18:43:14 [Server] INFO at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:495)
17.04 18:43:14 [Multicraft] Server shut down (starting)
17.04 18:43:14 [Multicraft] Maximum number of automatic restarts reached (15 within 300 seconds). Not restarting crashed server
17.04 18:43:14 [Multicraft] Stopping server!
17.04 18:43:16 [Multicraft] Looks like a crash, check the server console. Return value: 1
17.04 18:43:16 [Multicraft] Server stopped

**Comment by KR33PYK1NG** [comment]
You must use Java 11 since the latest builds.
