### ISSUE TITLE
[1.16.5] Am i missing something here?

### ISSUE THREAD

**Issue by Zilacon** [Teneted/Tenet#1243]
First time trying 1.16.5.
Got build 615, got the latest OpenJ9 JDK11 release, and Valhesia 3 modpack.
Launched.

Now its telling me the mods that are already there, need to be the same versions that they are to launch...
But, but, but...

```
---- Minecraft Crash Report ----
// Shall we play a game?

Time: 4/23/21, 10:00 AM
Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
	at net.minecraftforge.fml.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:86) [forge:?] {re:classloading}
	at net.minecraftforge.fml.server.ServerModLoader.load(ServerModLoader.java:51) [forge:?] {re:classloading}
	at net.minecraft.server.Main.main(Main.java:121) [?:?] {re:classloading}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.fml.loading.FMLServerLaunchProvider.lambda$launchService$0(FMLServerLaunchProvider.java:51) [V3.jar:36.1] {}
	at net.minecraftforge.fml.loading.FMLServerLaunchProvider$$Lambda$588/0x0000000000000000.call(Unknown Source) [V3.jar:36.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {}
	at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:95) [V3.jar:?] {}
	at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:92) [V3.jar:?] {}
	at net.minecraftforge.server.ServerMain.main(ServerMain.java:89) [V3.jar:?] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: main
Stacktrace:
	at net.minecraftforge.fml.CrashReportExtender.lambda$dumpModLoadingCrashReport$7(CrashReportExtender.java:89) ~[forge:?] {re:classloading}
-- MOD tetra --
Details:
	Mod File: tetra-1.16.5-3.8.0.jar
	Failure message: Mod tetra only supports curios 4 or above
		Currently, curios is 1.16.5-4.0.5.0
	Mod Version: 3.8.0
	Mod Issue URL: https://github.com/mickelus/tetra/issues/new
	Exception message: MISSING EXCEPTION MESSAGE
Stacktrace:
	at net.minecraftforge.fml.CrashReportExtender.lambda$dumpModLoadingCrashReport$7(CrashReportExtender.java:89) ~[forge:?] {re:classloading}
	at net.minecraftforge.fml.CrashReportExtender$$Lambda$2975/0x0000000000000000.accept(Unknown Source) ~[?:?] {}
	at java.util.ArrayList.forEach(Unknown Source) ~[?:?] {}
	at net.minecraftforge.fml.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:87) [forge:?] {re:classloading}
	at net.minecraftforge.fml.server.ServerModLoader.load(ServerModLoader.java:51) [forge:?] {re:classloading}
	at net.minecraft.server.Main.main(Main.java:121) [?:?] {re:classloading}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.fml.loading.FMLServerLaunchProvider.lambda$launchService$0(FMLServerLaunchProvider.java:51) [V3.jar:36.1] {}
	at net.minecraftforge.fml.loading.FMLServerLaunchProvider$$Lambda$588/0x0000000000000000.call(Unknown Source) [V3.jar:36.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {}
	at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:95) [V3.jar:?] {}
	at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:92) [V3.jar:?] {}
	at net.minecraftforge.server.ServerMain.main(ServerMain.java:89) [V3.jar:?] {}


-- MOD aquaculture --
Details:
	Mod File: Aquaculture-1.16.5-2.1.16.jar
	Failure message: Mod aquaculture only supports biomesoplenty 13.0.0.420 or above
		Currently, biomesoplenty is 1.16.4-13.0.0.431
	Mod Version: 1.16.5-2.1.16
	Mod Issue URL: NOT PROVIDED
	Exception message: MISSING EXCEPTION MESSAGE

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Linux (amd64) version 5.4.0-70-generic
	Java Version: 11.0.11, AdoptOpenJDK
	Java VM Version: Eclipse OpenJ9 VM (JRE 11 Linux amd64-64-Bit Compressed References 20210421_975 (JIT enabled, AOT enabled)
OpenJ9   - b4cc246d9
OMR      - 162e6f729
JCL      - 7796c80419 based on jdk-11.0.11+9), Eclipse OpenJ9
	Memory: 169681736 bytes (161 MB) / 516947968 bytes (493 MB) up to 8589934592 bytes (8192 MB)
	CPUs: 4
	JVM Flags: 43 total; -Xoptionsfile=/home/apoc/Servers/1165-Servers/zOJ9_1165/lib/options.default -Xlockword:mode=default,noLockword=java/lang/String,noLockword=java/util/MapEntry,noLockword=java/util/HashMap$Entry,noLockword=org/apache/harmony/luni/util/ModifiedMap$Entry,noLockword=java/util/Hashtable$Entry,noLockword=java/lang/invoke/MethodType,noLockword=java/lang/invoke/MethodHandle,noLockword=java/lang/invoke/CollectHandle,noLockword=java/lang/invoke/ConstructorHandle,noLockword=java/lang/invoke/ConvertHandle,noLockword=java/lang/invoke/ArgumentConversionHandle,noLockword=java/lang/invoke/AsTypeHandle,noLockword=java/lang/invoke/ExplicitCastHandle,noLockword=java/lang/invoke/FilterReturnHandle,noLockword=java/lang/invoke/DirectHandle,noLockword=java/lang/invoke/ReceiverBoundHandle,noLockword=java/lang/invoke/DynamicInvokerHandle,noLockword=java/lang/invoke/FieldHandle,noLockword=java/lang/invoke/FieldGetterHandle,noLockword=java/lang/invoke/FieldSetterHandle,noLockword=java/lang/invoke/StaticFieldGetterHandle,noLockword=java/lang/invoke/StaticFieldSetterHandle,noLockword=java/lang/invoke/IndirectHandle,noLockword=java/lang/invoke/InterfaceHandle,noLockword=java/lang/invoke/VirtualHandle,noLockword=java/lang/invoke/PrimitiveHandle,noLockword=java/lang/invoke/InvokeExactHandle,noLockword=java/lang/invoke/InvokeGenericHandle,noLockword=java/lang/invoke/VarargsCollectorHandle,noLockword=java/lang/invoke/ThunkTuple -Xjcl:jclse29 -Xms128m -Xmx8G -Xmns64m -Xmnx256m -Xshareclasses:cacheDir=/home/apoc/Servers/1165-Servers/zCache_1165 -XX:UseSSE=4 -Xalwaysclassgc -Xcompactgc -Xgcpolicy:gencon -Xgc:concurrentScavenge -Xgc:scvNoAdaptiveTenure -Xaggressive -Xnocompactexplicitgc -Xdisableexcessivegc -Xgcthreads2 -Xnuma:none -Xtune:virtualized -XX:ActiveProcessorCount=4 -XX:+UseLargePages -XX:-UseISM -XX:+ScavengeBeforeFullGC -XX:+CMSScavengeBeforeRemark -XX:-RelaxAccessControlCheck -XX:+UseCompressedStrings -XX:+AggressiveOpts -XX:LargePageSizeInBytes=4m -XX:+CompactStrings -Xdisableexplicitgc -XX:+UseCompressedOops -Xcompressedrefs -XX:+UseFastAccessorMethods -XX:+UseBiasedLocking -XX:+UseCodeCacheFlushing -XX:+UseStringCache -XX:+OptimizeStringConcat -XX:+UnlockExperimentalVMOptions -XX:+TieredCompilation -XX:+EliminateLocks -XX:-HeapDumpOnOutOfMemoryError -Xverify:none
	ModLauncher: 8.0.9+86+master.3cf110c
	ModLauncher launch target: fmlserver
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/V3.jar object_holder_definalize PLUGINSERVICE 
		/V3.jar runtime_enum_extender PLUGINSERVICE 
		/V3.jar capability_inject_definalize PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/V3.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/V3.jar fml TRANSFORMATIONSERVICE 
	FML: 36.1
	Forge: net.minecraftforge:36.1.12
	FML Language Providers: 
		javafml@36.1
		minecraft@1
	Mod List: 
		forge-1.16.5-36.1.12-server.jar                   |Minecraft                     |minecraft                     |1.16.5              |NONE      |NOSIGNATURE
		forge-1.16.5-36.1.12-universal.jar                |Forge                         |forge                         |36.1.12             |NONE      |NOSIGNATURE
	CraftBukkit Information: 
   Running: 
   Failed to handle CraftCrashReport: craftbukkit not runs
```

**Comment by kencinder** [comment]
Broken in the changes made in build 516, build 514 works fine.

**Comment by Mgazul** [comment]
The same error exists when starting valhelsia-3 with forge-1.16.5-36.1.12, so this is not a mohist problem

**Comment by Mgazul** [comment]
net.minecraftforge.fml.ModLoadingException: Mod §eaquaculture§r only supports §3biomesoplenty§r §o13.0.0.420 or above§r
§7Currently, §3biomesoplenty§r§7 is §o1.16.4-13.0.0.431

**Comment by Mgazul** [comment]
https://github.com/MinecraftForge/MinecraftForge/commit/c4b1df1fc7cf4e64be4418215f4e59adba7f08f4
