### ISSUE TITLE
Server crashing on startup 1.16.5

### ISSUE THREAD

**Issue by Tshar147** [Teneted/Tenet#1281]
Server crashes on startup, using Bisect Hosting running Custom Java 11.

Log goes as follows on startup.

[29.04 16:51:19] [Server]  __    __   ______   __  __   __   ______   ______  
[29.04 16:51:19] [Server] /\ "-./  \ /\  __ \ /\ \_\ \ /\ \ /\  ___\ /\__  _\ 
[29.04 16:51:19] [Server] \ \ \-./\ \\ \ \/\ \\ \  __ \\ \ \\ \___  \\/_/\ \/ 
[29.04 16:51:19] [Server]  \ \_\ \ \_\\ \_____\\ \_\ \_\\ \_\\/\_____\  \ \_\ 
[29.04 16:51:19] [Server]   \/_/  \/_/ \/_____/ \/_/\/_/ \/_/ \/_____/   \/_/ 
[29.04 16:51:19] [Server]                                       Welcome to Mohist 1.16.! - Mohist Developement Group
[29.04 16:51:19] [Server] Checking libraries, please wait...
[29.04 16:51:20] [Server] All libraries are nice :) !
[29.04 16:51:20] [Server] Checking the installation, please wait.
[29.04 16:51:20] [Server] Finished the install verification process !
[29.04 16:51:20] [Server] Update in check...
[29.04 16:51:20] [Server] If you don't want to enable update check, set check_update in mohist-config/mohist.yml to false
[29.04 16:51:22] [Server] No update found, latest version(1-1.16.5-537) current version: (1-1.16.5-537)
[29.04 16:51:24] [Server] 2021-04-16:51:24,146 main WARN Advanced terminal features are not available in this environment
[29.04 16:51:24] [Server] [INFO] ModLauncher running: args [--gameDir, ., --launchTarget, fmlserver, --fml.forgeVersion, 36.1.13, --fml.mcpVersion, 20210115.111550, --fml.mcVersion, 1.16.5, --fml.forgeGroup, net.minecraftforge, nogui]
[29.04 16:51:24] [Server] [INFO] ModLauncher 8.0.9+86+master.3cf110c starting: java version 11.0.10 by Oracle Corporation
[29.04 16:51:24] [Server] WARNINGAn illegal reflective access operation has occurred
[29.04 16:51:24] [Server] WARNINGIllegal reflective access by cpw.mods.modlauncher.SecureJarHandler (file:/libraries/cpw/mods/modlauncher/8.0.9/modlauncher-8.0.9.jar) to field java.util.jar.Manifest.jv
[29.04 16:51:24] [Server] WARNINGPlease consider reporting this to the maintainers of cpw.mods.modlauncher.SecureJarHandler
[29.04 16:51:24] [Server] WARNINGUse --illegal-access=warn to enable warnings of further illegal reflective access operations
[29.04 16:51:24] [Server] WARNINGAll illegal access operations will be denied in a future release
[29.04 16:51:24] [Server] [INFO] Added Lets Encrypt root certificates as additional trust
[29.04 16:51:24] [Server] [INFO] SpongePowered MIXIN Subsystem Version=0.8.2 Source=file:/libraries/org/spongepowered/mixin/0.8.2/mixin-0.8.2.jar Service=ModLauncher Env=SERVER
[29.04 16:51:25] [Server] [INFO] [jdk.nashorn.api.scripting.NashornScriptEngine:<init>:143]: Warning: Nashorn engine is planned to be removed from a future JDK release
[29.04 16:51:25] [Server] [INFO] [jdk.nashorn.api.scripting.NashornScriptEngine:<init>:143]: Warning: Nashorn engine is planned to be removed from a future JDK release
[29.04 16:51:25] [Server] [INFO] [jdk.nashorn.api.scripting.NashornScriptEngine:<init>:143]: Warning: Nashorn engine is planned to be removed from a future JDK release
[29.04 16:51:25] [Server] [INFO] [jdk.nashorn.api.scripting.NashornScriptEngine:<init>:143]: Warning: Nashorn engine is planned to be removed from a future JDK release
[29.04 16:51:25] [Server] [INFO] [jdk.nashorn.api.scripting.NashornScriptEngine:<init>:143]: Warning: Nashorn engine is planned to be removed from a future JDK release
[29.04 16:51:25] [Server] [INFO] [jdk.nashorn.api.scripting.NashornScriptEngine:<init>:143]: Warning: Nashorn engine is planned to be removed from a future JDK release
[29.04 16:51:25] [Server] [INFO] [jdk.nashorn.api.scripting.NashornScriptEngine:<init>:143]: Warning: Nashorn engine is planned to be removed from a future JDK release
[29.04 16:51:25] [Server] [INFO] [jdk.nashorn.api.scripting.NashornScriptEngine:<init>:143]: Warning: Nashorn engine is planned to be removed from a future JDK release
[29.04 16:51:25] [Server] [INFO] [jdk.nashorn.api.scripting.NashornScriptEngine:<init>:143]: Warning: Nashorn engine is planned to be removed from a future JDK release
[29.04 16:51:25] [Server] [INFO] [jdk.nashorn.api.scripting.NashornScriptEngine:<init>:143]: Warning: Nashorn engine is planned to be removed from a future JDK release
[29.04 16:51:25] [Server] [INFO] [jdk.nashorn.api.scripting.NashornScriptEngine:<init>:143]: Warning: Nashorn engine is planned to be removed from a future JDK release
[29.04 16:51:25] [Server] [INFO] [jdk.nashorn.api.scripting.NashornScriptEngine:<init>:143]: Warning: Nashorn engine is planned to be removed from a future JDK release
[29.04 16:51:25] [Server] [INFO] [jdk.nashorn.api.scripting.NashornScriptEngine:<init>:143]: Warning: Nashorn engine is planned to be removed from a future JDK release
[29.04 16:51:25] [Server] [INFO] [jdk.nashorn.api.scripting.NashornScriptEngine:<init>:143]: Warning: Nashorn engine is planned to be removed from a future JDK release
[29.04 16:51:25] [Server] [INFO] [jdk.nashorn.api.scripting.NashornScriptEngine:<init>:143]: Warning: Nashorn engine is planned to be removed from a future JDK release
[29.04 16:51:25] [Server] [INFO] [jdk.nashorn.api.scripting.NashornScriptEngine:<init>:143]: Warning: Nashorn engine is planned to be removed from a future JDK release
[29.04 16:51:25] [Server] [INFO] [jdk.nashorn.api.scripting.NashornScriptEngine:<init>:143]: Warning: Nashorn engine is planned to be removed from a future JDK release
[29.04 16:51:25] [Server] [INFO] [jdk.nashorn.api.scripting.NashornScriptEngine:<init>:143]: Warning: Nashorn engine is planned to be removed from a future JDK release
[29.04 16:51:25] [Server] [INFO] [jdk.nashorn.api.scripting.NashornScriptEngine:<init>:143]: Warning: Nashorn engine is planned to be removed from a future JDK release
[29.04 16:51:25] [Server] [INFO] [jdk.nashorn.api.scripting.NashornScriptEngine:<init>:143]: Warning: Nashorn engine is planned to be removed from a future JDK release
[29.04 16:51:25] [Server] [INFO] [jdk.nashorn.api.scripting.NashornScriptEngine:<init>:143]: Warning: Nashorn engine is planned to be removed from a future JDK release
[29.04 16:51:25] [Server] [INFO] [jdk.nashorn.api.scripting.NashornScriptEngine:<init>:143]: Warning: Nashorn engine is planned to be removed from a future JDK release
[29.04 16:51:25] [Server] [INFO] [jdk.nashorn.api.scripting.NashornScriptEngine:<init>:143]: Warning: Nashorn engine is planned to be removed from a future JDK release
[29.04 16:51:25] [Server] [INFO] [jdk.nashorn.api.scripting.NashornScriptEngine:<init>:143]: Warning: Nashorn engine is planned to be removed from a future JDK release
[29.04 16:51:25] [Server] [INFO] [jdk.nashorn.api.scripting.NashornScriptEngine:<init>:143]: Warning: Nashorn engine is planned to be removed from a future JDK release
[29.04 16:51:25] [Server] [INFO] [jdk.nashorn.api.scripting.NashornScriptEngine:<init>:143]: Warning: Nashorn engine is planned to be removed from a future JDK release
[29.04 16:51:25] [Server] [INFO] [jdk.nashorn.api.scripting.NashornScriptEngine:<init>:143]: Warning: Nashorn engine is planned to be removed from a future JDK release
[29.04 16:51:25] [Server] [INFO] [jdk.nashorn.api.scripting.NashornScriptEngine:<init>:143]: Warning: Nashorn engine is planned to be removed from a future JDK release
[29.04 16:51:25] [Server] [INFO] [jdk.nashorn.api.scripting.NashornScriptEngine:<init>:143]: Warning: Nashorn engine is planned to be removed from a future JDK release
[29.04 16:51:25] [Server] [INFO] [jdk.nashorn.api.scripting.NashornScriptEngine:<init>:143]: Warning: Nashorn engine is planned to be removed from a future JDK release
[29.04 16:51:25] [Server] [INFO] [jdk.nashorn.api.scripting.NashornScriptEngine:<init>:143]: Warning: Nashorn engine is planned to be removed from a future JDK release
[29.04 16:51:25] [Server] [INFO] [jdk.nashorn.api.scripting.NashornScriptEngine:<init>:143]: Warning: Nashorn engine is planned to be removed from a future JDK release
[29.04 16:51:26] [Server] [INFO] [org.antlr.v4.runtime.ConsoleErrorListener:syntaxError:38]: line 1:0 token recognition error at: '~'
[29.04 16:51:27] [Server] [INFO] Successfully loaded Mixin Connector [vazkii.patchouli.common.MixinConnector]
[29.04 16:51:27] [Server] [INFO] Successfully loaded Mixin Connector [thelm.jaopca.mixins.JAOPCAMixinConnector]
[29.04 16:51:27] [Server] [INFO] Successfully loaded Mixin Connector [com.performant.coremod.mixin.Connector]
[29.04 16:51:27] [Server] [INFO] Launching target 'fmlserver' with arguments [--gameDir, ., nogui]
[29.04 16:51:27] [Server] [INFO] Performant configs loaded
[29.04 16:51:28] [Server] [INFO] Adding 'add_custom_entity_collision' ASM patch...
[29.04 16:51:28] [Server] [INFO] Added 'add_custom_entity_collision' ASM patch!
[29.04 16:51:28] [Server] [INFO] Adding 'reach_set_server_entity_interact' ASM patch...
[29.04 16:51:28] [Server] [INFO] Added 'reach_set_server_entity_interact' ASM patch!
[29.04 16:51:28] [Server] [INFO] Adding 'allow_entity_interaction' ASM patch...
[29.04 16:51:28] [Server] [INFO] Added 'allow_entity_interaction' ASM patch!
[29.04 16:51:28] [Server] [INFO] Adding 'set_player_field' ASM patch...
[29.04 16:51:29] [Server] [INFO] Added 'set_player_field' ASM patch!
[29.04 16:51:29] [Server] [INFO] Adding 'water_movement_slowdown_prevention' ASM patch...
[29.04 16:51:29] [Server] [INFO] Added 'water_movement_slowdown_prevention' ASM patch!
[29.04 16:51:29] [Server] [INFO] Patching DataPackRegistries#<init>
[29.04 16:51:29] [Server] [INFO] Patching LootTableManager#apply
[29.04 16:51:30] [Server] [INFO] Adding 'add_enchantment_helper_levels' ASM patch...
[29.04 16:51:30] [Server] [INFO] Added 'add_enchantment_helper_levels' ASM patch!
[29.04 16:51:30] [Server] [INFO] Adding 'add_enchantment_helper_enchantments' ASM patch...
[29.04 16:51:30] [Server] [INFO] Added 'add_enchantment_helper_enchantments' ASM patch!
[29.04 16:51:30] [Server] [INFO] Adding 'add_enchantment_helper_apply_modifier' ASM patch...
[29.04 16:51:30] [Server] [INFO] Added 'add_enchantment_helper_apply_modifier' ASM patch!
[29.04 16:51:30] [Server] [INFO] Adding 'add_missing_tag_enchantment_tooltip' ASM patch...
[29.04 16:51:30] [Server] [INFO] Added 'add_missing_tag_enchantment_tooltip' ASM patch!
[29.04 16:51:30] [Server] [INFO] Adding 'add_enchantment_tooltip' ASM patch...
[29.04 16:51:30] [Server] [INFO] Added 'add_enchantment_tooltip' ASM patch!
[29.04 16:51:30] [Server] [INFO] Not enabling mixin forcom.performant.coremod.mixin.forge.BasicEventHooksMixin as config disables it.
[29.04 16:51:30] [Server] [INFO] Not enabling mixin forcom.performant.coremod.mixin.entity.LivingEntityUpdateEventMixin as config disables it.
[29.04 16:51:31] [Server] [INFO] Adding 'on_block_change' ASM patch...
[29.04 16:51:31] [Server] [INFO] Added 'on_block_change' ASM patch!
[29.04 16:51:31] [Server] [INFO] Adding 'sun_brightness_server' ASM patch...
[29.04 16:51:31] [Server] [INFO] Added 'sun_brightness_server' ASM patch!
[29.04 16:51:31] [Server] [WARN] @Mixin target net/minecraft/world/server/ChunkManager$EntityTracker is public in performant.mixins.json:world.chunk.ChunkManagerEntityTrackMixin and should be specified in value
[29.04 16:51:31] [Server] [INFO] Adding 'post_process_vanilla' ASM patch...
[29.04 16:51:31] [Server] [INFO] Added 'post_process_vanilla' ASM patch!
[29.04 16:51:31] [Server] [INFO] Adding 'on_block_change' ASM patch...
[29.04 16:51:31] [Server] [INFO] Added 'on_block_change' ASM patch!
[29.04 16:51:31] [Server] [INFO] Adding 'sun_brightness_server' ASM patch...
[29.04 16:51:31] [Server] [INFO] Added 'sun_brightness_server' ASM patch!
[29.04 16:51:32] [Server] [INFO] Adding 'add_custom_entity_collision' ASM patch...
[29.04 16:51:32] [Server] [INFO] Added 'add_custom_entity_collision' ASM patch!
[29.04 16:51:32] [Server] [INFO] Adding 'set_player_field' ASM patch...
[29.04 16:51:32] [Server] [INFO] Added 'set_player_field' ASM patch!
[29.04 16:51:32] [Server] [INFO] Adding 'water_movement_slowdown_prevention' ASM patch...
[29.04 16:51:32] [Server] [INFO] Added 'water_movement_slowdown_prevention' ASM patch!
[29.04 16:51:34] [Server] [INFO] Using Java 9+ class definer
[29.04 16:51:37] [Server] [INFO] Adding 'add_missing_tag_enchantment_tooltip' ASM patch...
[29.04 16:51:37] [Server] [INFO] Added 'add_missing_tag_enchantment_tooltip' ASM patch!
[29.04 16:51:37] [Server] [INFO] Adding 'add_enchantment_tooltip' ASM patch...
[29.04 16:51:37] [Server] [INFO] Added 'add_enchantment_tooltip' ASM patch!
[29.04 16:51:40] [Server] [INFO] Potentially Dangerous alternative prefix `citadel` for name `debug`, expected `minecraft`. This could be a intended override, but in most cases indicates a broken mod.
[29.04 16:51:40] [Server] [INFO] Potentially Dangerous alternative prefix `citadel` for name `citadel_book`, expected `minecraft`. This could be a intended override, but in most cases indicates a broken mod.
[29.04 16:51:41] [Server] [INFO] Scanning classes for titanium
[29.04 16:51:41] [Server] [INFO] Found FeaturePluginInstance for class DefaultResourceRegistryPlugin for plugin resources
[29.04 16:51:41] [Server] [INFO] Potentially Dangerous alternative prefix `forbidden_arcanus` for name `edelwood_sign`, expected `minecraft`. This could be a intended override, but in most cases indicates a broken mod.
[29.04 16:51:41] [Server] [INFO] Potentially Dangerous alternative prefix `forbidden_arcanus` for name `edelwood_wall_sign`, expected `minecraft`. This could be a intended override, but in most cases indicates a broken mod.
[29.04 16:51:41] [Server] [INFO] Potentially Dangerous alternative prefix `forbidden_arcanus` for name `cherrywood_sign`, expected `minecraft`. This could be a intended override, but in most cases indicates a broken mod.
[29.04 16:51:41] [Server] [INFO] Potentially Dangerous alternative prefix `forbidden_arcanus` for name `cherrywood_wall_sign`, expected `minecraft`. This could be a intended override, but in most cases indicates a broken mod.
[29.04 16:51:41] [Server] [INFO] Potentially Dangerous alternative prefix `forbidden_arcanus` for name `mysterywood_sign`, expected `minecraft`. This could be a intended override, but in most cases indicates a broken mod.
[29.04 16:51:41] [Server] [INFO] Potentially Dangerous alternative prefix `forbidden_arcanus` for name `mysterywood_wall_sign`, expected `minecraft`. This could be a intended override, but in most cases indicates a broken mod.
[29.04 16:51:41] [Server] [ERROR] Running on a dedicated server, disabling mod.
[29.04 16:51:41] [Server] [INFO] Patching DataPackRegistries#<init>
[29.04 16:51:41] [Server] [INFO] Forge mod loading, version 36.1.13, for MC 1.16.5 with MCP 20210115.111550
[29.04 16:51:41] [Server] [INFO] MinecraftForge v36.1.13 Initialized
[29.04 16:51:41] [Server] [INFO] [yalter.mousetweaks.Logger:Log:6]: [Mouse Tweaks] Disabled because not running on the client.
[29.04 16:51:41] [Server] [INFO] Scanning classes for titanium
[29.04 16:51:42] [Server] [INFO] Constructed class DefaultResourceRegistryPlugin for plugin resources for mod titanium
[29.04 16:51:42] [Server] [INFO] Executing phase CONSTRUCTION for plugin class DefaultResourceRegistryPlugin
[29.04 16:51:42] [Server] [INFO] Patching LootTableManager#apply
[29.04 16:51:42] [Server] [INFO] EventDispatcherRegistry initialized
[29.04 16:51:42] [Server] [WARN] @Final field field_187234_c:Ljava/util/Map; in performant.mixins.json:entity.EntityDataManagerMixin should be final
[29.04 16:51:42] [Server] [INFO] Detected new forge version, registering events reflectively.
[29.04 16:51:42] [Server] [INFO] Detected new forge version, registering events reflectively.
[29.04 16:51:42] [Server] [ERROR] Failed to create mod instance. ModID: structurize, class com.ldtteam.structurize.Structurize
[29.04 16:51:42] [Server] java.lang.IncompatibleClassChangeErrorInconsistent constant pool data in classfile for class com/ldtteam/structurize/api/blocks/IBlockCollection. Method lambda$create$0(Lcom/ldtteam/structurize/api/blocks/BlockType;)Lnet/minecraft/block/Block; at index 147 is CONSTANT_MethodRef and should be CONSTANT_InterfaceMethodRef
[29.04 16:51:42] [Server] 	at com.ldtteam.structurize.api.blocks.IBlockCollection.create(IBlockCollection.java:91) ~[structurize:0.13.163-ALPHA]
[29.04 16:51:42] [Server] 	at com.ldtteam.structurize.blocks.CactusCollection.<init>(CactusCollection.java:27) ~[structurize:0.13.163-ALPHA]
[29.04 16:51:42] [Server] 	at com.ldtteam.structurize.blocks.ModBlocks.<clinit>(ModBlocks.java:61) ~[structurize:0.13.163-ALPHA]
[29.04 16:51:42] [Server] 	at com.ldtteam.structurize.Structurize.<init>(Structurize.java:48) ~[structurize:0.13.163-ALPHA]
[29.04 16:51:42] [Server] 	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
[29.04 16:51:42] [Server] 	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:?]
[29.04 16:51:42] [Server] 	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
[29.04 16:51:42] [Server] 	at java.lang.reflect.Constructor.newInstance(Constructor.java:490) ~[?:?]
[29.04 16:51:42] [Server] 	at java.lang.Class.newInstance(Class.java:584) ~[?:?]
[29.04 16:51:42] [Server] 	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:82) ~[forge:36.1]
[29.04 16:51:42] [Server] 	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:120) ~[forge:?]
[29.04 16:51:42] [Server] 	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1736) [?:?]
[29.04 16:51:42] [Server] 	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1728) [?:?]
[29.04 16:51:42] [Server] 	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290) [?:?]
[29.04 16:51:42] [Server] 	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020) [?:?]
[29.04 16:51:42] [Server] 	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656) [?:?]
[29.04 16:51:42] [Server] 	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594) [?:?]
[29.04 16:51:42] [Server] 	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) [?:?]
[29.04 16:51:42] [Server] [INFO] Detected new forge version, registering events reflectively.
[29.04 16:51:42] [Server] [INFO] Adding 'cooldown_tracker_set' ASM patch...
[29.04 16:51:42] [Server] [INFO] Added 'cooldown_tracker_set' ASM patch!
[29.04 16:51:42] [Server] [INFO] Found 1 RS API injection point
[29.04 16:51:42] [Server] [INFO] Injected RS API in com.refinedmods.refinedstorageaddons.RSAddons RSAPI
[29.04 16:51:43] [Server] [INFO] [wayoftime.bloodmagic.structures.DungeonRoomLoader:loadDungeons:69]: # schematics: 5
[29.04 16:51:43] [Server] [INFO] Hello, World! (You will only see this line once in console, during startup)
[29.04 16:51:43] [Server] [INFO] Loaded script startup_scripts:script.js in 0.183 s
[29.04 16:51:43] [Server] [INFO] Loaded 1/1 KubeJS startup scripts in 0.439 s
[29.04 16:51:43] [Server] [INFO] Adding 'post_process_vanilla' ASM patch...
[29.04 16:51:43] [Server] [INFO] Added 'post_process_vanilla' ASM patch!
[29.04 16:51:43] [Server] [INFO] Loaded common.properties
[29.04 16:51:44] [Server] [INFO] Adding 'reach_set_server_entity_interact' ASM patch...
[29.04 16:51:44] [Server] [INFO] Added 'reach_set_server_entity_interact' ASM patch!
[29.04 16:51:44] [Server] [INFO] Adding 'allow_entity_interaction' ASM patch...
[29.04 16:51:44] [Server] [INFO] Added 'allow_entity_interaction' ASM patch!
[29.04 16:51:44] [Server] [INFO] Adding 'add_player_field' ASM patch...
[29.04 16:51:44] [Server] [INFO] Added 'add_player_field' ASM patch!
[29.04 16:51:44] [Server] [FATAL] Failed to complete lifecycle event CONSTRUCT, 1 errors found
[29.04 16:51:44] [Server] [FATAL] Preparing crash report with UUID 22c3159e-69ff-45a6-8dd2-f139e5b88b8d
[29.04 16:51:44] [Server] [INFO] [net.minecraft.crash.CrashReport:func_85057_a:197]: Negative index in crash report handler (16/18)
[29.04 16:51:44] [Server] [FATAL] Crash report saved to ./crash-reports/crash-2021-04-29_16.51.44-fml.txt
[29.04 16:51:44] [Server] ---- Minecraft Crash Report ----
[29.04 16:51:44] [Server] // Sorry :(
[29.04 16:51:44] [Server] Time4/29/21, 4:51 PM
[29.04 16:51:44] [Server] DescriptionMod loading error has occurred
[29.04 16:51:44] [Server] java.lang.ExceptionMod Loading has failed
[29.04 16:51:44] [Server] 	at net.minecraftforge.fml.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:86) ~[forge:?] {re:classloading}
[29.04 16:51:44] [Server] 	at net.minecraftforge.fml.server.ServerModLoader.load(ServerModLoader.java:51) ~[forge:?] {re:classloading}
[29.04 16:51:44] [Server] 	at net.minecraft.server.Main.main(Main.java:121) ~[?:?] {re:classloading}
[29.04 16:51:44] [Server] 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
[29.04 16:51:44] [Server] 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?] {}
[29.04 16:51:44] [Server] 	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
[29.04 16:51:44] [Server] 	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?] {}
[29.04 16:51:44] [Server] 	at net.minecraftforge.fml.loading.FMLServerLaunchProvider.lambda$launchService$0(FMLServerLaunchProvider.java:51) ~[customjava11.jar:36.{}
[29.04 16:51:44] [Server] 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
[29.04 16:51:44] [Server] 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
[29.04 16:51:44] [Server] 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
[29.04 16:51:44] [Server] 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {}
[29.04 16:51:44] [Server] 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {}
[29.04 16:51:44] [Server] 	at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:98) [customjava11.jar:?] {}
[29.04 16:51:44] [Server] 	at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:95) [customjava11.jar:?] {}
[29.04 16:51:44] [Server] 	at net.minecraftforge.server.ServerMain.main(ServerMain.java:92) [customjava11.jar:?] {}
[29.04 16:51:44] [Server] A detailed walkthrough of the error, its code path and all known details is as follows:
[29.04 16:51:44] [Server] ---------------------------------------------------------------------------------------
[29.04 16:51:44] [Server] -- Head --
[29.04 16:51:44] [Server] Threadmain
[29.04 16:51:44] [Server] Stacktrace:
[29.04 16:51:44] [Server] 	at com.ldtteam.structurize.api.blocks.IBlockCollection.create(IBlockCollection.java:91) ~[structurize:0.13.163-ALPHA] {re:classloading}
[29.04 16:51:44] [Server] -- MOD structurize --
[29.04 16:51:44] [Server] Details:
[29.04 16:51:44] [Server] 	Mod Filestructurize-0.13.163-ALPHA-universal.jar
[29.04 16:51:44] [Server] 	Failure messageStructurize (structurize) has failed to load correctly
[29.04 16:51:44] [Server] 		java.lang.IncompatibleClassChangeErrorInconsistent constant pool data in classfile for class com/ldtteam/structurize/api/blocks/IBlockCollection. Method lambda$create$0(Lcom/ldtteam/structurize/api/blocks/BlockType;)Lnet/minecraft/block/Block; at index 147 is CONSTANT_MethodRef and should be CONSTANT_InterfaceMethodRef
[29.04 16:51:44] [Server] 	Mod Version0.13.163-ALPHA
[29.04 16:51:44] [Server] 	Mod Issue URLhttps://github.com/ldtteam/structurize/issues/new/choose
[29.04 16:51:44] [Server] 	Exception messagejava.lang.IncompatibleClassChangeError: Inconsistent constant pool data in classfile for class com/ldtteam/structurize/api/blocks/IBlockCollection. Method lambda$create$0(Lcom/ldtteam/structurize/api/blocks/BlockType;)Lnet/minecraft/block/Block; at index 147 is CONSTANT_MethodRef and should be CONSTANT_InterfaceMethodRef
[29.04 16:51:44] [Server] Stacktrace:
[29.04 16:51:44] [Server] 	at com.ldtteam.structurize.api.blocks.IBlockCollection.create(IBlockCollection.java:91) ~[structurize:0.13.163-ALPHA] {re:classloading}
[29.04 16:51:44] [Server] 	at com.ldtteam.structurize.blocks.CactusCollection.<init>(CactusCollection.java:27) ~[structurize:0.13.163-ALPHA] {re:classloading}
[29.04 16:51:44] [Server] 	at com.ldtteam.structurize.blocks.ModBlocks.<clinit>(ModBlocks.java:61) ~[structurize:0.13.163-ALPHA] {re:classloading}
[29.04 16:51:44] [Server] 	at com.ldtteam.structurize.Structurize.<init>(Structurize.java:48) ~[structurize:0.13.163-ALPHA] {re:classloading}
[29.04 16:51:44] [Server] 	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {re:classloading,re:classloading,re:classloading}
[29.04 16:51:44] [Server] 	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:?] {re:classloading,re:classloading,re:classloading}
[29.04 16:51:44] [Server] 	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {re:classloading,re:classloading,re:classloading}
[29.04 16:51:44] [Server] 	at java.lang.reflect.Constructor.newInstance(Constructor.java:490) ~[?:?] {}
[29.04 16:51:44] [Server] 	at java.lang.Class.newInstance(Class.java:584) ~[?:?] {}
[29.04 16:51:44] [Server] 	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:82) ~[forge:36.{re:classloading}
[29.04 16:51:44] [Server] 	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:120) ~[forge:?] {re:classloading}
[29.04 16:51:44] [Server] 	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1736) ~[?:?] {}
[29.04 16:51:44] [Server] 	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1728) ~[?:?] {}
[29.04 16:51:44] [Server] 	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290) ~[?:?] {}
[29.04 16:51:44] [Server] 	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020) ~[?:?] {}
[29.04 16:51:44] [Server] 	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656) ~[?:?] {}
[29.04 16:51:44] [Server] 	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594) ~[?:?] {}
[29.04 16:51:44] [Server] 	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) ~[?:?] {}
[29.04 16:51:44] [Server] -- System Details --
[29.04 16:51:44] [Server] Details:
[29.04 16:51:44] [Server] 	Minecraft Version1.16.5
[29.04 16:51:44] [Server] 	Minecraft Version ID1.16.5
[29.04 16:51:44] [Server] 	Operating SystemLinux (amd64) version 4.15.0-39-generic
[29.04 16:51:44] [Server] 	Java Version11.0.10, Oracle Corporation
[29.04 16:51:44] [Server] 	Java VM VersionJava HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
[29.04 16:51:44] [Server] 	Memory1696595968 bytes (1618 MB) / 3592421376 bytes (3426 MB) up to 6442450944 bytes (6144 MB)
[29.04 16:51:44] [Server] 	CPUs40
[29.04 16:51:44] [Server] 	JVM Flags10 total; -Xmx6144M -Xms512M -XX:+UnlockExperimentalVMOptions -XX:-UseParallelGC -XX:-UseParallelOldGC -XX:-UseG1GC -XX:+UseZGC -XX:+DisableExplicitGC -XX:+CMSClassUnloadingEnabled -XX:ParallelGCThreads=16
[29.04 16:51:44] [Server] 	ModLauncher8.0.9+86+master.3cf110c
[29.04 16:51:44] [Server] 	ModLauncher launch targetfmlserver
[29.04 16:51:44] [Server] 	ModLauncher namingsrg
[29.04 16:51:44] [Server] 	ModLauncher services
[29.04 16:51:44] [Server] 		/mixin-0.8.2.jar mixin PLUGINSERVICE 
[29.04 16:51:44] [Server] 		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
[29.04 16:51:44] [Server] 		/customjava11.jar object_holder_definalize PLUGINSERVICE 
[29.04 16:51:44] [Server] 		/customjava11.jar runtime_enum_extender PLUGINSERVICE 
[29.04 16:51:44] [Server] 		/customjava11.jar capability_inject_definalize PLUGINSERVICE 
[29.04 16:51:44] [Server] 		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
[29.04 16:51:44] [Server] 		/customjava11.jar runtimedistcleaner PLUGINSERVICE 
[29.04 16:51:44] [Server] 		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
[29.04 16:51:44] [Server] 		/customjava11.jar fml TRANSFORMATIONSERVICE 
[29.04 16:51:44] [Server] 	FML36.1
[29.04 16:51:44] [Server] 	Forgenet.minecraftforge:36.1.13
[29.04 16:51:44] [Server] 	FML Language Providers
[29.04 16:51:44] [Server] 		javafml@36.1
[29.04 16:51:44] [Server] 		minecraft@1
[29.04 16:51:44] [Server] 	Mod List
[29.04 16:51:45] [Multicraft] Server shut down (starting)

**Comment by NocturnalSergal** [comment]
You need to update Structurize to V0.13.166-ALPHA or higher to use Java9 or higher. or use Java8. you may need to update minecolonies aswell if you are using that.

**Comment by Shawiizz** [comment]
Is this solved ? For now I close this. If it's not solved tell it here and I'll reopen the issue

**Comment by NocturnalSergal** [comment]
Sorry yes this has been solved by updating both mohist and essentialsX.
