### ISSUE TITLE
[1.16.5] Error on console when a player on a voice channel quits minecraft

### ISSUE THREAD

**Issue by muriplz** [Teneted/Tenet#1282]
**Minecraft Version :** {1.16.5}

**Mohist Version :** {535}

**Operating System :** {Ubuntu}

**Concerned plugin** : {Minecord}

**Logs :** 
```
Could not pass event PlayerQuitEvent to Minecord v1.7.14_2
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:312) ~[forge:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[forge:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[forge:?]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:588) ~[forge:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:573) ~[forge:?]
        at net.minecraft.server.management.PlayerList.func_72367_e(PlayerList.java:441) ~[?:?]
        at net.minecraft.server.management.PlayerList.disconnect(PlayerList.java:426) ~[?:?]
        at net.minecraft.network.play.ServerPlayNetHandler.func_147231_a(ServerPlayNetHandler.java:1540) ~[?:?]
        at net.minecraft.network.NetworkManager.func_179293_l(NetworkManager.java:383) ~[?:?]
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:160) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1054) ~[?:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:331) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:944) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:759) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:270) ~[?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.NullPointerException
        at me.spomg.minecord.listeners.PlayerQuitListener.onPlayerQuit(PlayerQuitListener.java:37) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[forge:?]
        ... 15 more
```

**Comment by Shawiizz** [comment]
The paste doesn't exists. Please update it :)

**Comment by muriplz** [comment]
this also comes out, not sure if it means anything:
```
[04:54:20 WARN]: [Minecord] Task #11 for Minecord v1.7.14_2 generated an exception
java.lang.NullPointerException: null
        at me.spomg.minecord.linking.LinkingReminderScheduler.lambda$run$0(LinkingReminderScheduler.java:31) ~[?:?]
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:176) ~[?:?]
        at java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:720) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497) ~[?:?]
        at me.spomg.minecord.linking.LinkingReminderScheduler.run(LinkingReminderScheduler.java:32) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100) ~[forge:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:462) ~[forge:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:998) ~[?:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:331) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:944) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:759) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:270) ~[?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
```
