### ISSUE TITLE
[1.12.2]randompatches-MOD报错

### ISSUE THREAD

**Issue by 864063334** [Teneted/Tenet#129]
MOD列表foamfix，randompatches
插件列表CMI8.6.20.0，CMIEInjector[经济]1.0.2.1，LuckPerms-Bukkit-5.0.72，Multiverse-Core-2.5.0，PlaceholderAPI-2.10.4，ProtocolLib4.4.0，Vault-1.7.3
[06:06:41 ERROR]: Failed to transform class: net.minecraft.network.NetHandlerPlayServer
 java.lang.NullPointerException: null
        at org.objectweb.asm.tree.InsnList.insert(Unknown Source) ~[asm-all-5.2.jar:5.2]
        at com.therandomlabs.randompatches.patch.NetHandlerPlayServerPatch.patchUpdate(NetHandlerPlayServerPatch.java:121) ~[NetHandlerPlayServerPatch.class:?]
        at com.therandomlabs.randompatches.patch.NetHandlerPlayServerPatch.apply(NetHandlerPlayServerPatch.java:26) ~[NetHandlerPlayServerPatch.class:?]
        at com.therandomlabs.randompatches.core.RPTransformer.transform(RPTransformer.java:37) [randompatches-1.12.2-1.21.0.0.jar:?]
        at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:256) [ASMTransformerWrapper$TransformerWrapper.class:47369ab]
        at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) [launchwrapper-1.12.jar:?]
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) [launchwrapper-1.12.jar:?]
        at java.lang.ClassLoader.loadClass(Unknown Source) [?:1.8.0_241]
        at java.lang.ClassLoader.loadClass(Unknown Source) [?:1.8.0_241]
        at java.lang.Class.forName0(Native Method) ~[?:1.8.0_241]
        at java.lang.Class.forName(Unknown Source) [?:1.8.0_241]
        at red.mohist.common.remap.remappers.MohistInheritanceProvider.fineNMSParents(MohistInheritanceProvider.java:33) [MohistInheritanceProvider.class:47369ab]
        at red.mohist.common.remap.remappers.MohistInheritanceProvider.fineParents(MohistInheritanceProvider.java:21) [MohistInheritanceProvider.class:47369ab]
        at red.mohist.common.remap.remappers.MohistInheritanceProvider.getParents(MohistInheritanceProvider.java:16) [MohistInheritanceProvider.class:47369ab]
        at red.mohist.common.remap.remappers.MohistInheritanceProvider.getParents(MohistInheritanceProvider.java:10) [MohistInheritanceProvider.class:47369ab]
        at red.mohist.common.remap.remappers.MohistJarMapping.tryClimb(MohistJarMapping.java:253) [MohistJarMapping.class:47369ab]
        at red.mohist.common.remap.remappers.MohistJarRemapper.mapMethodName(MohistJarRemapper.java:109) [MohistJarRemapper.class:47369ab]
        at net.md_5.specialsource.CustomRemapper.mapMethodName(CustomRemapper.java:41) [CustomRemapper.class:?]
        at org.objectweb.asm.commons.MethodRemapper.doVisitMethodInsn(Unknown Source) [asm-all-5.2.jar:5.2]
        at org.objectweb.asm.commons.MethodRemapper.visitMethodInsn(Unknown Source) [asm-all-5.2.jar:5.2]
        at org.objectweb.asm.tree.MethodInsnNode.accept(Unknown Source) [asm-all-5.2.jar:5.2]
        at org.objectweb.asm.tree.InsnList.accept(Unknown Source) [asm-all-5.2.jar:5.2]
        at org.objectweb.asm.tree.MethodNode.accept(Unknown Source) [asm-all-5.2.jar:5.2]
        at org.objectweb.asm.tree.MethodNode.accept(Unknown Source) [asm-all-5.2.jar:5.2]
        at org.objectweb.asm.tree.ClassNode.accept(Unknown Source) [asm-all-5.2.jar:5.2]
        at red.mohist.common.remap.RemapUtils.remapFindClass(RemapUtils.java:79) [RemapUtils.class:47369ab]
        at org.bukkit.plugin.java.PluginClassLoader.remappedFindClass(PluginClassLoader.java:156) [PluginClassLoader.class:47369ab]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:99) [PluginClassLoader.class:47369ab]
        at org.bukkit.plugin.java.JavaPluginLoader.getClassByName(JavaPluginLoader.java:205) [JavaPluginLoader.class:47369ab]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:95) [PluginClassLoader.class:47369ab]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:76) [PluginClassLoader.class:47369ab]
        at java.lang.ClassLoader.loadClass(Unknown Source) [?:1.8.0_241]
        at java.lang.ClassLoader.loadClass(Unknown Source) [?:1.8.0_241]
        at java.lang.Class.forName0(Native Method) ~[?:1.8.0_241]
        at java.lang.Class.forName(Unknown Source) [?:1.8.0_241]
        at red.mohist.common.remap.proxy.ProxyClass.forName(ProxyClass.java:23) [ProxyClass.class:47369ab]
        at red.mohist.common.remap.proxy.ProxyClass.forName(ProxyClass.java:19) [ProxyClass.class:47369ab]
        at com.Zrips.CMI.CMI.onEnable(CMI.java:1248) [CMI8.6.20.0.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:177) [JavaPlugin.class:47369ab]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:327) [JavaPluginLoader.class:47369ab]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:398) [SimplePluginManager.class:47369ab]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:490) [CraftServer.class:47369ab]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:419) [CraftServer.class:47369ab]
        at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:382) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:319) [nz.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:585) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_241]

**Comment by CraftDream** [comment]
> RandomPatches only contains features that require ASM transformers. Tweaks that don't require ASM transformers go in RandomTweaks, which I recommend as a companion mod.

I think you should use randomtweets without ASM.

**Comment by huangsijun17** [comment]
删除libratry重新下载看一下，你这报错就扯到Library里了。

**Comment by 864063334** [comment]
> 删除libratry重新下载看一下，你这报错就扯到Library里了。

我刚刚重新使用群公告的重新下载安装，也是报错

**Comment by huangsijun17** [comment]
8ddfa96d9fc93957c07dbed3962543ce247bcab6 179d43f77f4252549e242b6b1b0b3851a7ba767c 
Both of your fixes have been added to Mohist for compatibility. What's your version of Mohist?

**Comment by 864063334** [comment]
> [8ddfa96](https://github.com/Mohist-Community/Mohist/commit/8ddfa96d9fc93957c07dbed3962543ce247bcab6) [179d43f](https://github.com/Mohist-Community/Mohist/commit/179d43f77f4252549e242b6b1b0b3851a7ba767c)
> Both of your fixes have been added to Mohist for compatibility. What's your version of Mohist?

Mohist-47369ab-server

**Comment by 864063334** [comment]
solved
