### ISSUE TITLE
[1.16.5] Deployer(fakeplayer) error on console. Create Mod

### ISSUE THREAD

**Issue by muriplz** [Teneted/Tenet#1292]
**Minecraft Version :** 1.16.5

**Mohist Version :** 539

**Operating System :** Ubuntu

**Concerned mod / plugin** : Create mod 0.3.1c

**Logs :**
```
Could not pass event BlockPlaceEvent to GriefDefender v1.5.11-DEV
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:312) ~[forge:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[forge:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[forge:?]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:588) ~[forge:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:573) ~[forge:?]
        at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callBlockPlaceEvent(CraftEventFactory.java:338) ~[forge:?]
        at net.minecraft.item.BlockItem.func_195942_a(BlockItem.java:76) ~[?:?]
        at net.minecraft.item.BlockItem.func_195939_a(BlockItem.java:43) ~[?:?]
        at net.minecraftforge.common.ForgeHooks.onPlaceItemIntoWorld(ForgeHooks.java:651) ~[forge:?]
        at net.minecraft.item.ItemStack.func_196084_a(ItemStack.java:212) ~[?:?]
        at com.simibubi.create.content.contraptions.components.deployer.DeployerHandler.activateInner(DeployerHandler.java:283) ~[create:mc1.16.5_v0.3.1c+151]
        at com.simibubi.create.content.contraptions.components.deployer.DeployerHandler.activate(DeployerHandler.java:118) ~[create:mc1.16.5_v0.3.1c+151]
        at com.simibubi.create.content.contraptions.components.deployer.DeployerMovementBehaviour.activate(DeployerMovementBehaviour.java:88) ~[create:mc1.16.5_v0.3.1c+151]
        at com.simibubi.create.content.contraptions.components.deployer.DeployerMovementBehaviour.visitNewPosition(DeployerMovementBehaviour.java:69) ~[create:mc1.16.5_v0.3.1c+151]
        at com.simibubi.create.content.contraptions.components.structureMovement.AbstractContraptionEntity.tickActors(AbstractContraptionEntity.java:272) ~[create:mc1.16.5_v0.3.1c+151]
        at com.simibubi.create.content.contraptions.components.structureMovement.ControlledContraptionEntity.tickContraption(ControlledContraptionEntity.java:134) ~[create:mc1.16.5_v0.3.1c+151]
        at com.simibubi.create.content.contraptions.components.structureMovement.AbstractContraptionEntity.func_70071_h_(AbstractContraptionEntity.java:238) ~[create:mc1.16.5_v0.3.1c+151]
        at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:774) ~[?:?]
        at net.minecraft.world.World.func_217390_a(World.java:734) ~[?:?]
        at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:524) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1031) ~[?:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:331) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:944) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:759) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:270) ~[?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.NullPointerException: obj
        at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:787) ~[server-1.16.5-20210115.111550-extra.jar:?]
        at com.griefdefender.event.GDCauseStackManager.pushCause(GDCauseStackManager.java:66) ~[?:?]
        at com.griefdefender.listener.BlockEventHandler.onBlockPlace(BlockEventHandler.java:667) ~[?:?]
        at jdk.internal.reflect.GeneratedMethodAccessor68.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[forge:?]
        ... 25 more
```

description: Happened when a deployer tried to place a sapling. Happens unconsistently

**Comment by muriplz** [comment]
this issue was on my end
