### ISSUE TITLE
Startup bug

### ISSUE THREAD

**Issue by Minionguyjpro** [Teneted/Tenet#1302]
Hello im using Mohist as server software but when im trying to start the server i get this error:
`Exception in thread "main" [16:51:02 INFO]: [java.lang.ThreadGroup:uncaughtException:1050]: java.lang.RuntimeException: java.io.IOException: User limit of inotify instances reached or too many open files
[16:51:02 INFO]: [java.lang.ThreadGroup:uncaughtException:1050]:        at com.electronwill.nightconfig.core.file.FileWatcher$WatchedDir.<init>(FileWatcher.java:220)
[16:51:02 INFO]: [java.lang.ThreadGroup:uncaughtException:1050]:        at com.electronwill.nightconfig.core.file.FileWatcher$WatchedDir.<init>(FileWatcher.java:210)
[16:51:02 INFO]: [java.lang.ThreadGroup:uncaughtException:1050]:        at com.electronwill.nightconfig.core.file.FileWatcher.lambda$addWatch$0(FileWatcher.java:81)
[16:51:02 INFO]: [java.lang.ThreadGroup:uncaughtException:1050]:        at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1705)
[16:51:02 INFO]: [java.lang.ThreadGroup:uncaughtException:1050]:        at com.electronwill.nightconfig.core.file.FileWatcher.addWatch(FileWatcher.java:81)
[16:51:02 INFO]: [java.lang.ThreadGroup:uncaughtException:1050]:        at com.electronwill.nightconfig.core.file.FileWatcher.addWatch(FileWatcher.java:69)
[16:51:02 INFO]: [java.lang.ThreadGroup:uncaughtException:1050]:        at com.electronwill.nightconfig.core.file.AutoreloadFileConfig.<init>(AutoreloadFileConfig.java:18)
[16:51:02 INFO]: [java.lang.ThreadGroup:uncaughtException:1050]:        at com.electronwill.nightconfig.core.file.GenericBuilder.build(GenericBuilder.java:242)
[16:51:02 INFO]: [java.lang.ThreadGroup:uncaughtException:1050]:        at net.minecraftforge.fml.loading.FMLConfig.loadFrom(FMLConfig.java:54)
[16:51:02 INFO]: [java.lang.ThreadGroup:uncaughtException:1050]:        at net.minecraftforge.fml.loading.FMLConfig.load(FMLConfig.java:74)
[16:51:02 INFO]: [java.lang.ThreadGroup:uncaughtException:1050]:        at net.minecraftforge.fml.loading.FMLServiceProvider.initialize(FMLServiceProvider.java:81)
[16:51:02 INFO]: [java.lang.ThreadGroup:uncaughtException:1050]:        at cpw.mods.modlauncher.TransformationServiceDecorator.onInitialize(TransformationServiceDecorator.java:68)
[16:51:02 INFO]: [java.lang.ThreadGroup:uncaughtException:1050]:        at cpw.mods.modlauncher.TransformationServicesHandler.lambda$initialiseTransformationServices$7(TransformationServicesHandler.java:107)
[16:51:02 INFO]: [java.lang.ThreadGroup:uncaughtException:1050]:        at java.base/java.util.HashMap$Values.forEach(HashMap.java:976)
[16:51:02 INFO]: [java.lang.ThreadGroup:uncaughtException:1050]:        at cpw.mods.modlauncher.TransformationServicesHandler.initialiseTransformationServices(TransformationServicesHandler.java:107)
[16:51:02 INFO]: [java.lang.ThreadGroup:uncaughtException:1050]:        at cpw.mods.modlauncher.TransformationServicesHandler.initializeTransformationServices(TransformationServicesHandler.java:59)
[16:51:02 INFO]: [java.lang.ThreadGroup:uncaughtException:1050]:        at cpw.mods.modlauncher.Launcher.run(Launcher.java:76)
[16:51:03 INFO]: [java.lang.ThreadGroup:uncaughtException:1050]:        at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)
[16:51:03 INFO]: [java.lang.ThreadGroup:uncaughtException:1050]:        at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:98)
[16:51:03 INFO]: [java.lang.ThreadGroup:uncaughtException:1050]:        at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:95)
[16:51:03 INFO]: [java.lang.ThreadGroup:uncaughtException:1050]:        at net.minecraftforge.server.ServerMain.main(ServerMain.java:92)
[16:51:03 INFO]: [java.lang.ThreadGroup:uncaughtException:1059]: Caused by: java.io.IOException: User limit of inotify instances reached or too many open files
[16:51:03 INFO]: [java.lang.ThreadGroup:uncaughtException:1059]:        at java.base/sun.nio.fs.LinuxWatchService.<init>(LinuxWatchService.java:64)
[16:51:03 INFO]: [java.lang.ThreadGroup:uncaughtException:1059]:        at java.base/sun.nio.fs.LinuxFileSystem.newWatchService(LinuxFileSystem.java:47)
[16:51:03 INFO]: [java.lang.ThreadGroup:uncaughtException:1059]:        at com.electronwill.nightconfig.core.file.FileWatcher$WatchedDir.<init>(FileWatcher.java:218)
[16:51:03 INFO]: [java.lang.ThreadGroup:uncaughtException:1059]:        ... 20 more
` how to fix this?

**Comment by KR33PYK1NG** [comment]
Close opened files in your system or increase the limit for those.
