### ISSUE TITLE
[1.12.2] Could not pass event TransactionEvent to ChestShop v3.9.2 (build 86) build mohist #359

### ISSUE THREAD

**Issue by Maks-Haswell** [Teneted/Tenet#132]
[12:39:29] [Server thread/ERROR] [Mohist]: Could not pass event TransactionEvent to ChestShop v3.9.2 (build 86)
org.bukkit.event.EventException: null
	at com.destroystokyo.paper.event.executor.StaticMethodHandleEventExecutor.execute(StaticMethodHandleEventExecutor.java:36) ~[StaticMethodHandleEventExecutor.class:a33c315]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66) ~[RegisteredListener.class:a33c315]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [SimplePluginManager.class:a33c315]
	at com.Acrobot.ChestShop.Listeners.Player.PlayerInteract.onInteract(PlayerInteract.java:132) [ChestShop.jar:?]
	at com.destroystokyo.paper.event.executor.StaticMethodHandleEventExecutor.execute(StaticMethodHandleEventExecutor.java:34) [StaticMethodHandleEventExecutor.class:a33c315]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66) [RegisteredListener.class:a33c315]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [SimplePluginManager.class:a33c315]
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:331) [CraftEventFactory.class:a33c315]
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:298) [CraftEventFactory.class:a33c315]
	at net.minecraft.server.management.PlayerInteractionManager.func_180784_a(PlayerInteractionManager.java:154) [or.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147345_a(NetHandlerPlayServer.java:1075) [pa.class:?]
	at net.minecraft.network.play.client.CPacketPlayerDigging.func_148833_a(SourceFile:40) [lp.class:?]
	at net.minecraft.network.play.client.CPacketPlayerDigging.func_148833_a(SourceFile:10) [lp.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_232]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_232]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:841) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:468) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:775) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:618) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]
Caused by: java.lang.IllegalArgumentException: Cannot generate code for item ItemStack{GALACTICRAFTPLANETS_MARS x 1} with maximum length of 0 (code Galacticraftplanets Mars:2 results in item ItemStack{GALACTICRAFTPLANETS_MARS x 1})
	at com.Acrobot.Breeze.Utils.MaterialUtil.getName(MaterialUtil.java:199) ~[?:?]
	at com.Acrobot.Breeze.Utils.MaterialUtil.getName(MaterialUtil.java:128) ~[?:?]
	at com.Acrobot.ChestShop.Listeners.PostTransaction.TransactionLogger.onTransaction(TransactionLogger.java:29) ~[?:?]
	at com.destroystokyo.paper.event.executor.StaticMethodHandleEventExecutor.execute(StaticMethodHandleEventExecutor.java:34) ~[StaticMethodHandleEventExecutor.class:a33c315]
	... 21 more
[12:39:29] [Server thread/ERROR] [Mohist]: Could not pass event TransactionEvent to ChestShop v3.9.2 (build 86)
org.bukkit.event.EventException: null
	at com.destroystokyo.paper.event.executor.StaticMethodHandleEventExecutor.execute(StaticMethodHandleEventExecutor.java:36) ~[StaticMethodHandleEventExecutor.class:a33c315]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66) ~[RegisteredListener.class:a33c315]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [SimplePluginManager.class:a33c315]
	at com.Acrobot.ChestShop.Listeners.Player.PlayerInteract.onInteract(PlayerInteract.java:132) [ChestShop.jar:?]
	at com.destroystokyo.paper.event.executor.StaticMethodHandleEventExecutor.execute(StaticMethodHandleEventExecutor.java:34) [StaticMethodHandleEventExecutor.class:a33c315]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66) [RegisteredListener.class:a33c315]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [SimplePluginManager.class:a33c315]
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:331) [CraftEventFactory.class:a33c315]
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:298) [CraftEventFactory.class:a33c315]
	at net.minecraft.server.management.PlayerInteractionManager.func_180784_a(PlayerInteractionManager.java:154) [or.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147345_a(NetHandlerPlayServer.java:1075) [pa.class:?]
	at net.minecraft.network.play.client.CPacketPlayerDigging.func_148833_a(SourceFile:40) [lp.class:?]
	at net.minecraft.network.play.client.CPacketPlayerDigging.func_148833_a(SourceFile:10) [lp.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_232]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_232]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:841) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:468) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:775) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:618) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]
Caused by: java.lang.IllegalArgumentException: Cannot generate code for item ItemStack{GALACTICRAFTPLANETS_MARS x 1} with maximum length of 0 (code Galacticraftplanets Mars:2 results in item ItemStack{GALACTICRAFTPLANETS_MARS x 1})
	at com.Acrobot.Breeze.Utils.MaterialUtil.getName(MaterialUtil.java:199) ~[?:?]
	at com.Acrobot.Breeze.Utils.MaterialUtil.getName(MaterialUtil.java:128) ~[?:?]
	at com.Acrobot.ChestShop.Listeners.PostTransaction.TransactionMessageSender.parseItemInformation(TransactionMessageSender.java:90) ~[?:?]
	at com.Acrobot.ChestShop.Listeners.PostTransaction.TransactionMessageSender.sendMessage(TransactionMessageSender.java:81) ~[?:?]
	at com.Acrobot.ChestShop.Listeners.PostTransaction.TransactionMessageSender.sendBuyMessage(TransactionMessageSender.java:42) ~[?:?]
	at com.Acrobot.ChestShop.Listeners.PostTransaction.TransactionMessageSender.onTransaction(TransactionMessageSender.java:30) ~[?:?]
	at com.destroystokyo.paper.event.executor.StaticMethodHandleEventExecutor.execute(StaticMethodHandleEventExecutor.java:34) ~[StaticMethodHandleEventExecutor.class:a33c315]
	... 21 more

**Comment by Mgazul** [comment]
Items that cannot be used by the plugin: GALACTICRAFTPLANETS_MARS
