### ISSUE TITLE
[1.12.2] Mod crash since Mohist-54641fd

### ISSUE THREAD

**Issue by jsaneu** [Teneted/Tenet#138]
### Description

Mod __Vampirism-1.12.2-1.6.2__ crash since https://github.com/Mohist-Community/Mohist/commit/54641fd39cafee29e041bdc564f6d2c227c1b758

### Crashreport
```
java.lang.NullPointerException: null
	at de.teamlapen.vampirism.tileentity.TileTotem.func_189515_b(TileTotem.java:778) ~[TileTotem.class:?]
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75820_a(AnvilChunkLoader.java:394) [aye.class:?]
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75816_a(AnvilChunkLoader.java:174) [aye.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73242_b(ChunkProviderServer.java:219) [on.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_186027_a(ChunkProviderServer.java:244) [on.class:?]
	at net.minecraft.world.WorldServer.func_73044_a(WorldServer.java:1298) [oo.class:?]
	at net.minecraft.server.MinecraftServer.func_71267_a(MinecraftServer.java:476) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71260_j(MinecraftServer.java:528) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:668) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]
```
### Information

Mohist version: [Mohist-54641fd](https://ci.codemc.io/job/Mohist-Community/job/Mohist-1.12.2/375/)
Mod version: [Vampirism-1.12.2-1.6.2](https://www.curseforge.com/minecraft/mc-mods/vampirism-become-a-vampire/files/2890062)

**Comment by jsaneu** [comment]
I think it's the Mod
