### ISSUE TITLE
[MOHIST 1.16.5 Build 611 ] WorldEdit

### ISSUE THREAD

**Issue by Frankulinn** [Teneted/Tenet#1391]
WorldEdit's command bugs :
- /brush smooth (doesn't work : do nothing )
- /brush sphere <block id> <height> (spawn sphere on you and not at the place pointed to by the item . Work like that with all blocks ) 
- when server stop there are a lot of errors in the console :

Steps to reproduce this : 
1- start the serveur with WorldEdit 
2- try this command with an item in your hand "/brush smooth 4" 
3- right clic with your item to the flor and see the reaction 
3-For trying brush sphere : execute the command with an item in your hand "/brush sphere grass_block 4"
4-right clic with your item to the flor and see the reaction
  
-------------------------------------------ERRORS TYPE-----------------------------------------------------------------------------------
 [10:33:24 ERROR]: Could not dispatch event: com.sk89q.worldedit.event.platform.PlatformReadyEvent@f1abaf1 to handler EventHandler{priority=NORMAL}
java.lang.reflect.InvocationTargetException: null
        at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:75) ~[worldedit:?]
        at com.sk89q.worldedit.util.eventbus.EventBus.dispatch(EventBus.java:193) ~[worldedit:?]
        at com.sk89q.worldedit.util.eventbus.EventBus.post(EventBus.java:181) ~[worldedit:?]
        at com.sk89q.worldedit.forge.ForgeWorldEdit.serverStarted(ForgeWorldEdit.java:214) ~[worldedit:?]
        at net.minecraftforge.eventbus.ASMEventHandler_11_ForgeWorldEdit_serverStarted_FMLServerStartedEvent.invoke(.dynamic) ~[?:?]
        at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?]
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?]
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?]
        at net.minecraftforge.fml.server.ServerLifecycleHooks.handleServerStarted(ServerLifecycleHooks.java:108) ~[forge:?]
        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:722) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:270) ~[?:?]
        at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: java.lang.reflect.InvocationTargetException
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
        at com.sk89q.worldedit.util.eventbus.MethodEventHandler.dispatch(MethodEventHandler.java:58) ~[worldedit:?]
        at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:73) ~[worldedit:?]
        ... 11 more
Caused by: java.lang.NullPointerException
        at jdk.internal.reflect.UnsafeFieldAccessorImpl.ensureObj(Unknown Source) ~[?:?]
        at jdk.internal.reflect.UnsafeQualifiedLongFieldAccessorImpl.getLong(Unknown Source) ~[?:?]
        at jdk.internal.reflect.UnsafeQualifiedLongFieldAccessorImpl.get(Unknown Source) ~[?:?]
        at java.lang.reflect.Field.get(Unknown Source) ~[?:?]
        at com.sk89q.worldedit.bukkit.adapter.impl.Spigot_v1_16_R3$SpigotWatchdog.tick(Spigot_v1_16_R3.java:936) ~[?:?]
        at com.sk89q.worldedit.bukkit.adapter.impl.Spigot_v1_16_R3.tickWatchdog(Spigot_v1_16_R3.java:915) ~[?:?]
        at com.sk89q.worldedit.bukkit.BukkitWatchdog.tick(BukkitWatchdog.java:35) ~[?:?]
        at com.sk89q.worldedit.world.block.BlockState.generateStateMap(BlockState.java:122) ~[worldedit:?]
        at com.sk89q.worldedit.world.block.BlockType.lambda$new$3(BlockType.java:61) ~[worldedit:?]
        at com.sk89q.worldedit.util.concurrency.LazyReference.getValue(LazyReference.java:68) ~[worldedit:?]
        at com.sk89q.worldedit.world.block.BlockType.getBlockStatesMap(BlockType.java:91) ~[worldedit:?]
        at com.sk89q.worldedit.world.block.BlockType.getAllStates(BlockType.java:175) ~[worldedit:?]
        at com.sk89q.worldedit.extension.platform.Capability$4.initialize(Capability.java:92) ~[worldedit:?]
        at com.sk89q.worldedit.extension.platform.PlatformManager.choosePreferred(PlatformManager.java:187) ~[worldedit:?]
        at com.sk89q.worldedit.extension.platform.PlatformManager.handlePlatformReady(PlatformManager.java:300) ~[worldedit:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
        at com.sk89q.worldedit.util.eventbus.MethodEventHandler.dispatch(MethodEventHandler.java:58) ~[worldedit:?]
        at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:73) ~[worldedit:?]
        ... 11 more

**Comment by Dokman** [comment]
because world edit cannot parse modded blocks

**Comment by Frankulinn** [comment]
There is exactly the same problem with WorldEdit in mod . try with WD forge and see . WorldEdit forge support modded blocks

**Comment by Dokman** [comment]
Fixed plugin in the discord server. officially fixed

**Comment by Dokman** [comment]
close this issue it's fixed
