### ISSUE TITLE
[1.16.5] The EssentialsX plugin doesn't work

### ISSUE THREAD

**Issue by frogden** [Teneted/Tenet#1417]
Minecraft version: 1.16.5

Provide Mohist build number: 627

Hi!
An error occurs when running the plugin

```
[Essentials] Plugin Essentials v2.19.0-dev+99-fd961d5 generated an exception while executing task 65366
org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register task while disabled
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.validate(CraftScheduler.java:529) ~[forge:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:206) ~[forge:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:191) ~[forge:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.scheduleSyncRepeatingTask(CraftScheduler.java:186) ~[forge:?]
        at com.earth2me.essentials.Essentials.scheduleSyncRepeatingTask(Essentials.java:972) ~[?:?]
        at com.earth2me.essentials.Backup.startTask(Backup.java:53) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:97) ~[forge:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) [forge:?]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:20) [forge:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:829) [?:?]
```

**Comment by Romaindu35** [comment]
This issue is normal, plugin detect paper in latest build
Please use build#625
