### ISSUE TITLE
[1.16.5] Dynmap spiggot and bukkit plugin do not work

### ISSUE THREAD

**Issue by DNAmaster10** [Teneted/Tenet#1434]
Minecraft Version : 1.16.5
Mohist Version : mohist-1.16.5-627-server

Operating System : Windows 10

**Concerned mod / plugin** : Dynmap (both spigot and bukit versions)

**Logs :**`[23:48:59] [Server thread/ERROR] [Minecraft/]: Could not load 'plugins\Dynmap-3.1-forge-1.16.5.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
	at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:171) ~[forge:?]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:144) ~[forge:?]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.loadPlugins(CraftServer.java:381) ~[forge:04df07fe-ebe18b9b-9fb885e8]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:208) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:721) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:270) ~[?:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: java.io.FileNotFoundException: Jar does not contain plugin.yml`

**Steps to Reproduce :**
 1. Add the dynmap plugin to the plugins folder

**Description of issue :** Error in logs, and plugin wont start.

**Comment by Shawiizz** [comment]
Your problem is that you put Dynmap Forge in plugins folder instead of mods folder.
