### ISSUE TITLE
Cannot send actionbar via plugin

### ISSUE THREAD

**Issue by H4kt** [Teneted/Tenet#1440]
**Minecraft Version :** 1.16.5

**Mohist Version :** 646

**Operating System :** Windows 10

**Logs :**
```
java.lang.NoSuchMethodError: 'void org.bukkit.entity.Player.sendActionBar(java.lang.String)'
        at ru.h4kt.admintools.AdminTools.sendActionBars(AdminTools.java:75) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:97) ~[forge:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) [forge:?]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:20) [forge:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
        at java.lang.Thread.run(Unknown Source) [?:?]
```

**Mod list :** none

**Plugin list :** only my self-written AdminTools

**Description of issue :**
There are probably more methods which have the same issue. For instance AsyncPlayerPreLoginEvent#getPlayerProfile() which is added by Paper.

**Comment by Romaindu35** [comment]
This is a paper method ?

**Comment by H4kt** [comment]
> This is a paper method ?

No. That method is from Bukkit

**Comment by Romaindu35** [comment]
Can you send your code ? (Just the code that call sendActionBar)

**Comment by H4kt** [comment]
Plugin's onEnable registers a schduled task
```java
Bukkit.getScheduler().runTaskTimer(this, this::sendActionBars, 0, 10L);
```

sendActionsBars() method
```java
for (ToolsUser user : ToolsUser.listAll()) { //Looping through every online user

    boolean vanished = user.isVanished();
    boolean surrounded = user.isSurrounded();
	
    Player player = user.getPlayer();
    if (vanished && surrounded) {
	player.sendActionBar("currently vanished & surrounded");
    } else if (vanished) {
	player.sendActionBar("currently vanished");
    } else if (surrounded) {
        player.sendActionBar("currently surrounded");
    }
	
}
```

**Comment by H4kt** [comment]
Compiling it with paper 1.16.5 will show that the method is deprecated
However it is still not removed, so should be in mohist too for backwards compatibility.

**Comment by Romaindu35** [comment]
I think it is fix in lastest update

**Comment by H4kt** [comment]
Updated to build 648
Nothing changed, the issue still persists

**Comment by Romaindu35** [comment]
oops, jenkin don't finish to build my lastest commit

**Comment by Romaindu35** [comment]
Try with the build#650 (when the build have finish to build)

**Comment by H4kt** [comment]
`Player#sendActionBar()` now works fine.
In the initial message I've also mentioned `AsyncPlayerPreLoginEvent#getPlayerProfile()` which is added by Paper.
There is another way to implement the same thing w/o using `PlayerProfile`
However I'd like you to look into it
Thanks in advance

```
[19:48:56 ERROR]: Could not pass event AsyncPlayerPreLoginEvent to AdminTools v1.1.2
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:305) ~[forge:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[forge:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[forge:?]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:588) [forge:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:570) [forge:?]
        at net.minecraft.network.login.ServerLoginNetHandler$LoginHandler.fireEvents(ServerLoginNetHandler.java:286) [?:?]
        at net.minecraft.network.login.ServerLoginNetHandler$2.run(ServerLoginNetHandler.java:241) [?:?]
Caused by: java.lang.NoSuchMethodError: 'com.destroystokyo.paper.profile.PlayerProfile org.bukkit.event.player.AsyncPlayerPreLoginEvent.getPlayerProfile()'
        at ru.h4kt.admintools.listeners.UserListener.onPreLogin(UserListener.java:27) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:303) ~[forge:?]
        ... 6 more
```

```java
@EventHandler (priority = EventPriority.MONITOR)
public void onPreLogin(AsyncPlayerPreLoginEvent event) {

    if (event.getLoginResult() != AsyncPlayerPreLoginEvent.Result.ALLOWED) {
        return;
    }

    PlayerProfile profile = event.getPlayerProfile(); // <-- Here
    ToolsUser.create(profile.getId(), profile.getName()).fetch();

}
```

**Comment by Romaindu35** [comment]
Normally fix in build#651

**Comment by H4kt** [comment]
> Normally fix in build#651

Thanks. I'll check it out tomorrow.

**Comment by Romaindu35** [comment]
Or  no, the build have failed, I fix that when I have the time

**Comment by H4kt** [comment]
Any news on that?

**Comment by Romaindu35** [comment]
This is normally fix
