### ISSUE TITLE
Error executing the /mohist item command

### ISSUE THREAD

**Issue by AncientDarkFire** [Teneted/Tenet#145]
This error occurs when executing the command: https://hastebin.com/raw/osayedonuy

issued server command: /mohist item
> [04:36:46 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing 'mohist item' in red.mohist.command.MohistCommand(mohist)
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[SimpleCommandMap.class:c890208]
at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:763) ~[CraftServer.class:c890208]
at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:1580) [pa.class:?]
at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:1421) [pa.class:?]
at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(CPacketChatMessage.java:46) [la.class:?]
at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(CPacketChatMessage.java:9) [la.class:?]
at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_212]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_212]
at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:842) [MinecraftServer.class:?]
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:468) [nz.class:?]
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:780) [MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:624) [MinecraftServer.class:?]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: java.lang.ArrayIndexOutOfBoundsException: 1
at red.mohist.command.MohistCommand.execute(MohistCommand.java:80) ~[MohistCommand.class:c890208]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:145) ~[SimpleCommandMap.class:c890208]
... 14 more

**Comment by Iltotore** [comment]
Found the error:
> if ("info".equals(args[1].toLowerCase(Locale.ENGLISH)))
You need to pass "info" as the second argument.

Also, this class need to be reworked. Maybe I'll do that this week.
