### ISSUE TITLE
[1.12.2] [MC.Eternal 1.3.4] java.io.IOException: Bad packet id 26

### ISSUE THREAD

**Issue by braddevans** [Teneted/Tenet#146]
Exception: io.netty.handler.codec.DecoderException: java.io.IOException: Bad packet id 26

```java
[20:09:11 INFO]: UUID of player braddevans is fcd17554-3037-44f6-8e92-06b3746285d0
[20:09:11 WARN]: Failed to handle packet for /127.0.0.1:62511
 java.lang.NullPointerException: null
        at net.minecraft.server.management.PlayerList.allowUserToConnect(PlayerList.java:700) ~[pl.class:?]
        at net.minecraft.server.network.NetHandlerLoginServer.func_147326_c(NetHandlerLoginServer.java:146) ~[pc.class:?]
        at net.minecraft.server.network.NetHandlerLoginServer.func_73660_a(NetHandlerLoginServer.java:71) ~[pc.class:?]
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:296) ~[gw.class:?]
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:187) [oz.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:926) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:468) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:778) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:622) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_241]
[20:09:11 INFO]: com.mojang.authlib.GameProfile@44cc7abd[id=fcd17554-3037-44f6-8e92-06b3746285d0,name=braddevans,properties={textures=[com.mojang.authlib.properties.Property@6cc7ec8a]},legacy=false] (/127.0.0.1:62511) lost connection: Internal server error
```

**Comment by Mgazul** [comment]
Related to FastWorkbench

**Comment by Mgazul** [comment]
"Disable Recipe Book"=false
