### ISSUE TITLE
[1.16.5] ServerChatEvent and Vanilla/Forge Forge like CommandSource build don't work

### ISSUE THREAD

**Issue by GeheimagentNr1** [Teneted/Tenet#1477]
**Minecraft Version :** 1.16.5

**Mohist Version :** 553/666

**Operating System :** Windows 10
**Concerned mod / plugin** : Discord Integration (https://www.curseforge.com/minecraft/mc-mods/discord-integration/files)

**Logs :**
Server Log:
```
[02:21:52 WARN]: [JDA MainWS-ReadThread] ERROR lib.net.dv8tion.jda.api.JDA - One of the EventListeners had an uncaught exception
[02:21:52 WARN]: java.lang.AbstractMethodError: Receiver class de.geheimagentnr1.discordintegration.elements.discord.DiscordCommandSource does not define or inherit an implementation of the resolved method 'abstract org.bukkit.command.CommandSender getBukkitSender(net.minecraft.command.CommandSource)' of interface net.minecraft.command.ICommandSource.
[02:21:52 WARN]:        at net.minecraft.command.CommandSource.getBukkitSender(CommandSource.java:276)
[02:21:52 WARN]:        at net.minecraft.command.Commands.func_197059_a(Commands.java:247)
[02:21:52 WARN]:        at de.geheimagentnr1.discordintegration.elements.discord.DiscordCommandHandler.handleCommand(DiscordCommandHandler.java:30)
[02:21:52 WARN]:        at de.geheimagentnr1.discordintegration.elements.discord.DiscordEventHandler.handleCommands(DiscordEventHandler.java:63)
[02:21:52 WARN]:        at de.geheimagentnr1.discordintegration.elements.discord.DiscordEventHandler.onGuildMessageReceived(DiscordEventHandler.java:35)
[02:21:52 WARN]:        at lib.net.dv8tion.jda.api.hooks.ListenerAdapter.onEvent(ListenerAdapter.java:445)
[02:21:52 WARN]:        at lib.net.dv8tion.jda.api.hooks.InterfacedEventManager.handle(InterfacedEventManager.java:96)
[02:21:52 WARN]:        at lib.net.dv8tion.jda.internal.hooks.EventManagerProxy.handleInternally(EventManagerProxy.java:88)
[02:21:52 WARN]:        at lib.net.dv8tion.jda.internal.hooks.EventManagerProxy.handle(EventManagerProxy.java:70)
[02:21:52 WARN]:        at lib.net.dv8tion.jda.internal.JDAImpl.handleEvent(JDAImpl.java:151)
[02:21:52 WARN]:        at lib.net.dv8tion.jda.internal.handle.MessageCreateHandler.handleInternally(MessageCreateHandler.java:97)
[02:21:52 WARN]:        at lib.net.dv8tion.jda.internal.handle.SocketHandler.handle(SocketHandler.java:36)
[02:21:52 WARN]:        at lib.net.dv8tion.jda.internal.requests.WebSocketClient.onDispatch(WebSocketClient.java:952)
[02:21:52 WARN]:        at lib.net.dv8tion.jda.internal.requests.WebSocketClient.onEvent(WebSocketClient.java:839)
[02:21:52 WARN]:        at lib.net.dv8tion.jda.internal.requests.WebSocketClient.handleEvent(WebSocketClient.java:817)
[02:21:52 WARN]:        at lib.net.dv8tion.jda.internal.requests.WebSocketClient.onBinaryMessage(WebSocketClient.java:990)
[02:21:52 WARN]:        at lib.com.neovisionaries.ws.client.ListenerManager.callOnBinaryMessage(ListenerManager.java:385)
[02:21:52 WARN]:        at lib.com.neovisionaries.ws.client.ReadingThread.callOnBinaryMessage(ReadingThread.java:276)
[02:21:52 WARN]:        at lib.com.neovisionaries.ws.client.ReadingThread.handleBinaryFrame(ReadingThread.java:996)
[02:21:52 WARN]:        at lib.com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:755)
[02:21:52 WARN]:        at lib.com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:108)
[02:21:52 WARN]:        at lib.com.neovisionaries.ws.client.ReadingThread.runMain(ReadingThread.java:64)
[02:21:52 WARN]:        at lib.com.neovisionaries.ws.client.WebSocketThread.run(WebSocketThread.java:45)
> say Test
[02:24:20 INFO]: [Server] Test
[02:29:17 INFO]: UUID of player GeheimagentNr1 is e8288f86-ab11-4157-83bc-ee2d4e8341e8
[02:29:17 INFO]: Client attempting to join with 2 mods : minecraft, forge
[02:29:18 INFO]: Using new advancement loading for net.minecraft.advancements.PlayerAdvancements@14f57b13
[02:29:18 INFO]: GeheimagentNr1[/127.0.0.1:59198] logged in with entity id 150 at (85,031, 74, -188,112)
[02:29:23 INFO]: <GeheimagentNr1> Test
[02:29:31 INFO]: [SecretAgentNo1] Test
[02:29:42 INFO]: GeheimagentNr1 lost connection: Disconnected
[02:29:42 INFO]: GeheimagentNr1 left the game
```
![image](https://user-images.githubusercontent.com/20889593/123529564-d5f50880-d6f1-11eb-8e34-f8c5ad810f7c.png)

**Steps to Reproduce :**
Minecraft -> Discord Chat doesn't work:
 1. Write a chat massage in Minecraft and see, that it doesn't appear in the Discord chat.
Discord Commands doesn't work
 1. Run a command like "!help" and see, the error message mentioned in **Logs :**

**Description of issue :**
@Steveplays28 reported a bug for my mod "Discord Integration", that the Minecraft to Discord chat and the Discord Commands doesn't work:
https://github.com/GeheimagentNr1/DiscordIntegration/issues/5
In my investigations I found out, that the Forge ServerChatEvent seem to be not fired, because otherwise the Minecraft chat messages would be sent to the Discord chat and
that an AbstractMethodError is thrown, if a Discord command is run, because my DiscordCommandSource only implements the Minecraft Vanilla/Forge CommandSource and not the Bukkit CommandSource, because it is only a Minecraft Forge mod.

**Comment by Romaindu35** [comment]
Would it be possible to send the source code, or at least the source code of the class with the event?

**Comment by GeheimagentNr1** [comment]
Forge Source: [https://github.com/MinecraftForge/MinecraftForge](https://github.com/MinecraftForge/MinecraftForge)  
Mod Source: https://github.com/GeheimagentNr1/DiscordIntegration/tree/master_1.16.5

Forge ServerChatEvent firing by ForgeHooks: https://github.com/MinecraftForge/MinecraftForge/blob/29f175743b473cabd4f180485f1884e82d1b24cb/src/main/java/net/minecraftforge/common/ForgeHooks.java#L484  
Forge ServerChatEvent: https://github.com/MinecraftForge/MinecraftForge/blob/1.16.x/src/main/java/net/minecraftforge/event/ServerChatEvent.java  
Mod ServerChatEvent Handler: [https://github.com/GeheimagentNr1/DiscordIntegration/blob/master_1.16.5/src/main/java/de/geheimagentnr1/discordintegration/handlers/ForgeEventHandler.java#L80](https://github.com/GeheimagentNr1/DiscordIntegration/blob/master_1.16.5/src/main/java/de/geheimagentnr1/discordintegration/handlers/ForgeEventHandler.java#L80)

Mod DiscordCommandSource: https://github.com/GeheimagentNr1/DiscordIntegration/blob/master_1.16.5/src/main/java/de/geheimagentnr1/discordintegration/elements/discord/DiscordCommandSource.java
