### ISSUE TITLE
[MC VERSION] Dynmap wont work?

### ISSUE THREAD

**Issue by JamesBayhaner** [Teneted/Tenet#1493]
**Minecraft Version :** 1.16.5

**Mohist Version :** 680

**Operating System :** Windows 10

**Concerned mod / plugin** : https://dev.bukkit.org/projects/dynmap/files/3369608

**Logs :** `[13:44:46 INFO]: [dynmap] Loading dynmap v3.1-beta5-431
[13:44:46 INFO]: [dynmap] version=1.16.5-680 (MC: 1.16.5)
[13:44:47 ERROR]: [dynmap] Cannot find [Lnet.minecraft.server.BiomeBase;
[13:44:47 ERROR]: [dynmap] Cannot find net.minecraft.server.BiomeStorage
[13:44:47 ERROR]: Error initializing dynmap - bukkit version incompatible! initializing dynmap v3.1-beta5-431 (Is it up to date?)
java.lang.IllegalArgumentException: Error initializing dynmap - bukkit version incompatible!
        at org.dynmap.bukkit.helper.BukkitVersionHelperGeneric.<init>(BukkitVersionHelperGeneric.java:166) ~[?:?]
        at org.dynmap.bukkit.helper.v116_4.BukkitVersionHelperSpigot116_4.<init>(BukkitVersionHelperSpigot116_4.java:31) ~[?:?]
        at org.dynmap.bukkit.Helper.getHelper(Helper.java:50) ~[?:?]
        at org.dynmap.bukkit.DynmapPlugin.onLoad(DynmapPlugin.java:821) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.loadPlugins(CraftServer.java:391) ~[forge:7e29f765-296df566-9fb885e8]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:208) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:728) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:271) ~[?:?]
        at java.lang.Thread.run(Thread.java:829) [?:?]`

**Steps to Reproduce :**
1. Use Dynmap (happens accross every version i tested)

**Description of issue :** Dynmap wont work

**Comment by Romaindu35** [comment]
Same #1435
