### ISSUE TITLE
1.16.5 mohist plugin

### ISSUE THREAD

**Issue by ookami1414** [Teneted/Tenet#1498]
I can't get the plugin to work.
The plugin I am using is called "slot machine", URL "https://www.spigotmc.org/resources/slot-machine.22023/".

I've placed a slot machine and played with it.
After that, when I try to quit the slot machine, a bug occurs.
After quitting, I can't access the slot anymore.

Server Log
 at org.bukkit.craftbukkit.v1_16_R3.entity.CraftPlayer.stopSound(CraftPlayer.java:613) ~[forge:?]
comes up every time I open my inventory.

Translated with www.DeepL.com/Translator (free version)

**Comment by Mgazul** [comment]
Please provide the complete error message, thank you

**Comment by ookami1414** [comment]
@Mgazul 
Right this way.
at org.bukkit.craftbukkit.v1_16_R3.entity.CraftPlayer.stopSound(CraftPlayer.java:613) ~[forge:?]
[20:47:42 ERROR]: 		java.base@11.0.10/java.util.regex.Matcher.replaceAll(Unknown Source)
[20:47:48 ERROR]: 		github.scarsz.discordsrv.objects.log4j.ConsoleAppender.append(ConsoleAppender.java:124)
[20:47:48 ERROR]: 		app//org.apache.logging.log4j.core.config.AppenderControl.tryCallAppender(AppenderControl.java:156)
[20:47:48 ERROR]: 		app//org.apache.logging.log4j.core.config.AppenderControl.callAppender0(AppenderControl.java:129)
[20:47:48 ERROR]: 		app//org.apache.logging.log4j.core.config.AppenderControl.callAppenderPreventRecursion(AppenderControl.java:120)
[20:47:48 ERROR]: 		app//org.apache.logging.log4j.core.config.AppenderControl.callAppender(AppenderControl.java:84)
[20:47:48 ERROR]: 		app//org.apache.logging.log4j.core.config.LoggerConfig.callAppenders(LoggerConfig.java:464)
[20:47:48 ERROR]: 		app//org.apache.logging.log4j.core.config.LoggerConfig.processLogEvent(LoggerConfig.java:448)
[20:47:48 ERROR]: 		app//org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:431)
[20:47:48 ERROR]: 		app//org.apache.logging.log4j.core.config.LoggerConfig.logParent(LoggerConfig.java:455)
[20:47:48 ERROR]: 		app//org.apache.logging.log4j.core.config.LoggerConfig.processLogEvent(LoggerConfig.java:450)
[20:47:48 ERROR]: 		app//org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:431)
[20:47:48 ERROR]: 		app//org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:406)
[20:47:48 ERROR]: 		app//org.apache.logging.log4j.core.config.AwaitCompletionReliabilityStrategy.log(AwaitCompletionReliabilityStrategy.java:63)
[20:47:48 ERROR]: 		app//org.apache.logging.log4j.core.Logger.logMessage(Logger.java:146)
[20:47:48 ERROR]: 		app//org.apache.logging.log4j.spi.AbstractLogger.tryLogMessage(AbstractLogger.java:2170)
[20:47:48 ERROR]: 		app//org.apache.logging.log4j.spi.AbstractLogger.logMessageTrackRecursion(AbstractLogger.java:2125)
[20:47:48 ERROR]: 		app//org.apache.logging.log4j.spi.AbstractLogger.logMessageSafely(AbstractLogger.java:2108)
[20:47:48 ERROR]: 		app//org.apache.logging.log4j.spi.AbstractLogger.logMessage(AbstractLogger.java:2002)
[20:47:48 ERROR]: 		app//org.apache.logging.log4j.spi.AbstractLogger.logIfEnabled(AbstractLogger.java:1974)
[20:47:48 ERROR]: 		app//org.apache.logging.log4j.spi.AbstractLogger.warn(AbstractLogger.java:2624)
[20:47:48 ERROR]: 		net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:757)
[20:47:48 ERROR]: 		net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:283)
[20:47:48 ERROR]: 		net.minecraft.server.MinecraftServer$$Lambda$19133/0x0000000802cc5440.run(Unknown Source)
[20:47:48 ERROR]: 		java.base@11.0.10/java.lang.Thread.run(Unknown Source)
[20:47:48 ERROR]: ------------------------------
[20:47:48 ERROR]: --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH ---

**Comment by Romaindu35** [comment]
This is not a bug, just a warn

**Comment by Shawiizz** [comment]
Does the server crash ?
