### ISSUE TITLE
Не запускается плагин Dynmap-3.0-beta-5-spigot  на Mohist-694c08d

### ISSUE THREAD

**Issue by Maks-Haswell** [Teneted/Tenet#15]
Не запускается плагин Dynmap-3.0-beta-5-spigot  на Mohist-694c08d работает только forge версия плагина Dynmap 
[13:22:50] [Server thread/INFO] [Mohist]: Loading dynmap v3.0-beta-5-218
[13:22:50] [Server thread/INFO] [Mohist]: [dynmap] version=1.4-694c08d (MC: 1.12.2)
[13:22:50] [Server thread/ERROR] [Mohist]: [dynmap] Error finding net.minecraft.server packages
[13:22:50] [Server thread/ERROR] [Mohist]: [dynmap] Cannot find [Lnet.minecraft.server.BiomeBase;
[13:22:50] [Server thread/ERROR] [org.bukkit.craftbukkit.v1_12_R1.CraftServer]: Error initializing dynmap - bukkit version incompatible! initializing dynmap v3.0-beta-5-218 (Is it up to date?)
java.lang.IllegalArgumentException: Error initializing dynmap - bukkit version incompatible!
	at org.dynmap.bukkit.helper.BukkitVersionHelperGeneric.<init>(BukkitVersionHelperGeneric.java:159) ~[?:?]
	at org.dynmap.bukkit.helper.BukkitVersionHelperCB.<init>(BukkitVersionHelperCB.java:45) ~[?:?]
	at org.dynmap.bukkit.Helper.getHelper(Helper.java:55) ~[?:?]
	at org.dynmap.bukkit.DynmapPlugin.onLoad(DynmapPlugin.java:791) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.loadPlugins(CraftServer.java:385) [CraftServer.class:694c08d]
	at net.minecraft.world.storage.SaveHandler.initBukkitData(SaveHandler.java:393) [bfb.class:?]
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:320) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:322) [nz.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:608) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]

**Comment by Mgazul** [comment]
Please use the forge version of Dynmap, the bukkit version official instructions no longer support forge+bukkit

**Comment by Maks-Haswell** [comment]
> Please use the forge version of Dynmap, the bukkit version official instructions no longer support forge+bukkit

а возможно ли добавить поддержку в мохист ?

**Comment by Mgazul** [comment]
Вы можете перейти на GitHub Dynmap, чтобы отправить запрос.
