### ISSUE TITLE
v1_12_R1.block.CraftSign.load

### ISSUE THREAD

**Issue by LoopRich161** [Teneted/Tenet#150]
Version Mohist-1.12.2-9d300c6
Its problem mohist, not my plugins
Error:
[07:11:47] [Server thread/ERROR] [Mohist]: Could not pass event PlayerInteractEvent to WorldGuard v6.2.2-SNAPSHOT;8eeab68
org.bukkit.event.EventException: null
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:63) ~[EventExecutor.class:9d300c6]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66) ~[RegisteredListener.class:9d300c6]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [SimplePluginManager.class:9d300c6]
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:331) [CraftEventFactory.class:9d300c6]
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:298) [CraftEventFactory.class:9d300c6]
	at net.minecraft.server.management.PlayerInteractionManager.func_180784_a(PlayerInteractionManager.java:159) [or.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147345_a(NetHandlerPlayServer.java:1080) [pa.class:?]
	at net.minecraft.network.play.client.CPacketPlayerDigging.func_148833_a(SourceFile:40) [lp.class:?]
	at net.minecraft.network.play.client.CPacketPlayerDigging.func_148833_a(SourceFile:10) [lp.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_222]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_222]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:840) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:468) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:778) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:622) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
Caused by: java.lang.NullPointerException
	at org.bukkit.craftbukkit.v1_12_R1.block.CraftSign.load(CraftSign.java:53) ~[CraftSign.class:9d300c6]
	at org.bukkit.craftbukkit.v1_12_R1.block.CraftSign.load(CraftSign.java:11) ~[CraftSign.class:9d300c6]
	at org.bukkit.craftbukkit.v1_12_R1.block.CraftBlockEntityState.<init>(CraftBlockEntityState.java:26) ~[CraftBlockEntityState.class:9d300c6]
	at org.bukkit.craftbukkit.v1_12_R1.block.CraftSign.<init>(CraftSign.java:16) ~[CraftSign.class:9d300c6]
	at org.bukkit.craftbukkit.v1_12_R1.block.CraftBlock.getState(CraftBlock.java:310) ~[CraftBlock.class:9d300c6]
	at com.sk89q.worldguard.bukkit.util.Blocks.getConnected(Blocks.java:50) ~[?:?]
	at com.sk89q.worldguard.bukkit.listener.EventAbstractionListener.onPlayerInteract(EventAbstractionListener.java:382) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor123.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:61) ~[EventExecutor.class:9d300c6]
	... 17 more
[07:11:48] [Server thread/ERROR] [Mohist]: Could not pass event BlockBreakEvent to MyCommand v5.6.0
org.bukkit.event.EventException: null
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:63) ~[EventExecutor.class:9d300c6]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66) ~[RegisteredListener.class:9d300c6]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [SimplePluginManager.class:9d300c6]
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callBlockBreakEvent(CraftEventFactory.java:1260) [CraftEventFactory.class:9d300c6]
	at net.minecraftforge.event.world.BlockEvent$BreakEvent.<init>(BlockEvent.java:132) [BlockEvent$BreakEvent.class:9d300c6]
	at net.minecraftforge.common.ForgeHooks.onBlockBreakEvent(ForgeHooks.java:685) [ForgeHooks.class:9d300c6]
	at net.minecraft.server.management.PlayerInteractionManager.func_180237_b(PlayerInteractionManager.java:358) [or.class:?]
	at net.minecraft.server.management.PlayerInteractionManager.func_180785_a(PlayerInteractionManager.java:310) [or.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147345_a(NetHandlerPlayServer.java:1099) [pa.class:?]
	at net.minecraft.network.play.client.CPacketPlayerDigging.func_148833_a(SourceFile:40) [lp.class:?]
	at net.minecraft.network.play.client.CPacketPlayerDigging.func_148833_a(SourceFile:10) [lp.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_222]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_222]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:840) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:468) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:778) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:622) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
Caused by: java.lang.NullPointerException
	at org.bukkit.craftbukkit.v1_12_R1.block.CraftSign.load(CraftSign.java:53) ~[CraftSign.class:9d300c6]
	at org.bukkit.craftbukkit.v1_12_R1.block.CraftSign.load(CraftSign.java:11) ~[CraftSign.class:9d300c6]
	at org.bukkit.craftbukkit.v1_12_R1.block.CraftBlockEntityState.<init>(CraftBlockEntityState.java:26) ~[CraftBlockEntityState.class:9d300c6]
	at org.bukkit.craftbukkit.v1_12_R1.block.CraftSign.<init>(CraftSign.java:16) ~[CraftSign.class:9d300c6]
	at org.bukkit.craftbukkit.v1_12_R1.block.CraftBlock.getState(CraftBlock.java:310) ~[CraftBlock.class:9d300c6]
	at it.mri.mycommand.listener.SignListener.onBlockBreak(SignListener.java:70) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor206.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:61) ~[EventExecutor.class:9d300c6]
	... 19 more
[07:11:48] [Server thread/ERROR] [Mohist]: Could not pass event BlockBreakEvent to CoreProtect v2.14.4
org.bukkit.event.EventException: null
	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:38) ~[MethodHandleEventExecutor.class:9d300c6]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66) ~[RegisteredListener.class:9d300c6]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [SimplePluginManager.class:9d300c6]
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callBlockBreakEvent(CraftEventFactory.java:1260) [CraftEventFactory.class:9d300c6]
	at net.minecraftforge.event.world.BlockEvent$BreakEvent.<init>(BlockEvent.java:132) [BlockEvent$BreakEvent.class:9d300c6]
	at net.minecraftforge.common.ForgeHooks.onBlockBreakEvent(ForgeHooks.java:685) [ForgeHooks.class:9d300c6]
	at net.minecraft.server.management.PlayerInteractionManager.func_180237_b(PlayerInteractionManager.java:358) [or.class:?]
	at net.minecraft.server.management.PlayerInteractionManager.func_180785_a(PlayerInteractionManager.java:310) [or.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147345_a(NetHandlerPlayServer.java:1099) [pa.class:?]
	at net.minecraft.network.play.client.CPacketPlayerDigging.func_148833_a(SourceFile:40) [lp.class:?]
	at net.minecraft.network.play.client.CPacketPlayerDigging.func_148833_a(SourceFile:10) [lp.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_222]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_222]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:840) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:468) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:778) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:622) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
Caused by: java.lang.NullPointerException
	at org.bukkit.craftbukkit.v1_12_R1.block.CraftSign.load(CraftSign.java:53) ~[CraftSign.class:9d300c6]
	at org.bukkit.craftbukkit.v1_12_R1.block.CraftSign.load(CraftSign.java:11) ~[CraftSign.class:9d300c6]
	at org.bukkit.craftbukkit.v1_12_R1.block.CraftBlockEntityState.<init>(CraftBlockEntityState.java:26) ~[CraftBlockEntityState.class:9d300c6]
	at org.bukkit.craftbukkit.v1_12_R1.block.CraftSign.<init>(CraftSign.java:16) ~[CraftSign.class:9d300c6]
	at org.bukkit.craftbukkit.v1_12_R1.block.CraftBlock.getState(CraftBlock.java:310) ~[CraftBlock.class:9d300c6]
	at net.coreprotect.listener.BlockListener.onBlockBreak(BlockListener.java:191) ~[?:?]
	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:36) ~[MethodHandleEventExecutor.class:9d300c6]
	... 19 more
[07:11:48] [Server thread/ERROR] [Mohist]: Could not pass event PlayerInteractEvent to WorldGuard v6.2.2-SNAPSHOT;8eeab68
org.bukkit.event.EventException: null
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:63) ~[EventExecutor.class:9d300c6]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66) ~[RegisteredListener.class:9d300c6]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [SimplePluginManager.class:9d300c6]
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:331) [CraftEventFactory.class:9d300c6]
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:298) [CraftEventFactory.class:9d300c6]
	at net.minecraft.server.management.PlayerInteractionManager.func_180784_a(PlayerInteractionManager.java:159) [or.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147345_a(NetHandlerPlayServer.java:1080) [pa.class:?]
	at net.minecraft.network.play.client.CPacketPlayerDigging.func_148833_a(SourceFile:40) [lp.class:?]
	at net.minecraft.network.play.client.CPacketPlayerDigging.func_148833_a(SourceFile:10) [lp.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_222]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_222]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:840) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:468) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:778) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:622) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
Caused by: java.lang.NullPointerException
	at org.bukkit.craftbukkit.v1_12_R1.block.CraftSign.load(CraftSign.java:53) ~[CraftSign.class:9d300c6]
	at org.bukkit.craftbukkit.v1_12_R1.block.CraftSign.load(CraftSign.java:11) ~[CraftSign.class:9d300c6]
	at org.bukkit.craftbukkit.v1_12_R1.block.CraftBlockEntityState.<init>(CraftBlockEntityState.java:26) ~[CraftBlockEntityState.class:9d300c6]
	at org.bukkit.craftbukkit.v1_12_R1.block.CraftSign.<init>(CraftSign.java:16) ~[CraftSign.class:9d300c6]
	at org.bukkit.craftbukkit.v1_12_R1.block.CraftBlock.getState(CraftBlock.java:310) ~[CraftBlock.class:9d300c6]
	at com.sk89q.worldguard.bukkit.util.Blocks.getConnected(Blocks.java:50) ~[?:?]
	at com.sk89q.worldguard.bukkit.listener.EventAbstractionListener.onPlayerInteract(EventAbstractionListener.java:382) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor123.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:61) ~[EventExecutor.class:9d300c6]
	... 17 more
[07:11:48] [Server thread/ERROR] [Mohist]: Could not pass event BlockBreakEvent to MyCommand v5.6.0
org.bukkit.event.EventException: null
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:63) ~[EventExecutor.class:9d300c6]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66) ~[RegisteredListener.class:9d300c6]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [SimplePluginManager.class:9d300c6]
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callBlockBreakEvent(CraftEventFactory.java:1260) [CraftEventFactory.class:9d300c6]
	at net.minecraftforge.event.world.BlockEvent$BreakEvent.<init>(BlockEvent.java:132) [BlockEvent$BreakEvent.class:9d300c6]
	at net.minecraftforge.common.ForgeHooks.onBlockBreakEvent(ForgeHooks.java:685) [ForgeHooks.class:9d300c6]
	at net.minecraft.server.management.PlayerInteractionManager.func_180237_b(PlayerInteractionManager.java:358) [or.class:?]
	at net.minecraft.server.management.PlayerInteractionManager.func_180785_a(PlayerInteractionManager.java:310) [or.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147345_a(NetHandlerPlayServer.java:1099) [pa.class:?]
	at net.minecraft.network.play.client.CPacketPlayerDigging.func_148833_a(SourceFile:40) [lp.class:?]
	at net.minecraft.network.play.client.CPacketPlayerDigging.func_148833_a(SourceFile:10) [lp.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_222]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_222]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:840) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:468) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:778) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:622) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
Caused by: java.lang.NullPointerException
	at org.bukkit.craftbukkit.v1_12_R1.block.CraftSign.load(CraftSign.java:53) ~[CraftSign.class:9d300c6]
	at org.bukkit.craftbukkit.v1_12_R1.block.CraftSign.load(CraftSign.java:11) ~[CraftSign.class:9d300c6]
	at org.bukkit.craftbukkit.v1_12_R1.block.CraftBlockEntityState.<init>(CraftBlockEntityState.java:26) ~[CraftBlockEntityState.class:9d300c6]
	at org.bukkit.craftbukkit.v1_12_R1.block.CraftSign.<init>(CraftSign.java:16) ~[CraftSign.class:9d300c6]
	at org.bukkit.craftbukkit.v1_12_R1.block.CraftBlock.getState(CraftBlock.java:310) ~[CraftBlock.class:9d300c6]
	at it.mri.mycommand.listener.SignListener.onBlockBreak(SignListener.java:70) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor206.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:61) ~[EventExecutor.class:9d300c6]
	... 19 more
[07:11:49] [Server thread/ERROR] [Mohist]: Could not pass event BlockBreakEvent to CoreProtect v2.14.4
org.bukkit.event.EventException: null
	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:38) ~[MethodHandleEventExecutor.class:9d300c6]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66) ~[RegisteredListener.class:9d300c6]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [SimplePluginManager.class:9d300c6]
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callBlockBreakEvent(CraftEventFactory.java:1260) [CraftEventFactory.class:9d300c6]
	at net.minecraftforge.event.world.BlockEvent$BreakEvent.<init>(BlockEvent.java:132) [BlockEvent$BreakEvent.class:9d300c6]
	at net.minecraftforge.common.ForgeHooks.onBlockBreakEvent(ForgeHooks.java:685) [ForgeHooks.class:9d300c6]
	at net.minecraft.server.management.PlayerInteractionManager.func_180237_b(PlayerInteractionManager.java:358) [or.class:?]
	at net.minecraft.server.management.PlayerInteractionManager.func_180785_a(PlayerInteractionManager.java:310) [or.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147345_a(NetHandlerPlayServer.java:1099) [pa.class:?]
	at net.minecraft.network.play.client.CPacketPlayerDigging.func_148833_a(SourceFile:40) [lp.class:?]
	at net.minecraft.network.play.client.CPacketPlayerDigging.func_148833_a(SourceFile:10) [lp.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_222]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_222]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:840) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:468) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:778) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:622) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
Caused by: java.lang.NullPointerException
	at org.bukkit.craftbukkit.v1_12_R1.block.CraftSign.load(CraftSign.java:53) ~[CraftSign.class:9d300c6]
	at org.bukkit.craftbukkit.v1_12_R1.block.CraftSign.load(CraftSign.java:11) ~[CraftSign.class:9d300c6]
	at org.bukkit.craftbukkit.v1_12_R1.block.CraftBlockEntityState.<init>(CraftBlockEntityState.java:26) ~[CraftBlockEntityState.class:9d300c6]
	at org.bukkit.craftbukkit.v1_12_R1.block.CraftSign.<init>(CraftSign.java:16) ~[CraftSign.class:9d300c6]
	at org.bukkit.craftbukkit.v1_12_R1.block.CraftBlock.getState(CraftBlock.java:310) ~[CraftBlock.class:9d300c6]
	at net.coreprotect.listener.BlockListener.onBlockBreak(BlockListener.java:191) ~[?:?]
	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:36) ~[MethodHandleEventExecutor.class:9d300c6]
	... 19 more

**Comment by Maks-Haswell** [comment]
I myself encountered such an error, but my question was simply closed ...

**Comment by LoopRich161** [comment]
> I myself encountered such an error, but my question was simply closed ...

I hope they fix it ...
