### ISSUE TITLE
Kicked for Packet processing error

### ISSUE THREAD

**Issue by Switch-Back18** [Teneted/Tenet#1517]
**Minecraft Version : 1.16.5

**Mohist Version :** 697

**Operating System :** Ubuntu

**Logs :** 

[19:33:41 ERROR]: Error whilst processing packet net.minecraft.network.play.client.CPlayerDiggingPacket@6ec35310 for walbibi[/81.164.12.39:62701]
java.lang.NullPointerException: null
        at net.minecraft.server.management.PlayerInteractionManager.func_225416_a(PlayerInteractionManager.java:140) ~[?:?]
        at net.minecraft.network.play.ServerPlayNetHandler.func_147345_a(ServerPlayNetHandler.java:1429) ~[?:?]
        at net.minecraft.network.play.client.CPlayerDiggingPacket.func_148833_a(SourceFile:40) ~[?:?]
        at net.minecraft.network.play.client.CPlayerDiggingPacket.func_148833_a(SourceFile:10) ~[?:?]
        at net.minecraft.network.PacketThreadUtil.lambda$ensureRunningOnSameThread$1(PacketThreadUtil.java:28) ~[?:?]
        at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?]
        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(ThreadTaskExecutor.java:152) ~[?:?]
        at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:899) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:179) ~[?:?]
        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(ThreadTaskExecutor.java:125) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:882) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:876) ~[?:?]
        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(ThreadTaskExecutor.java:135) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:956) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:778) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:283) ~[?:?]
        at java.lang.Thread.run(Unknown Source) [?:?]

**Mod list :** https://hastebin.com/copiqeluci.csharp

**Plugin list :**https://haste.mohistmc.com/eguqigarah

**Description of issue :** When you are dead and u do something like dig block you get kicked et the message in the console is coming

**Comment by Romaindu35** [comment]
Same #1516
