### ISSUE TITLE
Kicked after deatg for net.minecraft.network.play.client.CClientStatusPacket

### ISSUE THREAD

**Issue by Switch-Back18** [Teneted/Tenet#1524]
**Minecraft Version :** 1.16.5

**Mohist Version :** 698

**Operating System :** Ubuntu

**Logs :** 

[11:41:50 ERROR]: Error whilst processing packet net.minecraft.network.play.client.CClientStatusPacket@1e260be0 for MathisSkate[/82.66.25.113:50962]
java.lang.ClassCastException: class net.minecraft.tags.TagRegistry$NamedTag cannot be cast to class net.minecraft.tags.Tag (net.minecraft.tags.TagRegistry$NamedTag and net.minecraft.tags.Tag are in unnamed module of loader cpw.mods.modlauncher.TransformingClassLoader @153cf928)
        at net.minecraft.server.management.PlayerList.moveToWorld(PlayerList.java:732) ~[?:?]
        at net.minecraft.server.management.PlayerList.func_232644_a_(PlayerList.java:647) ~[?:?]
        at net.minecraft.network.play.ServerPlayNetHandler.func_147342_a(ServerPlayNetHandler.java:2119) ~[?:?]
        at net.minecraft.network.play.client.CClientStatusPacket.func_148833_a(SourceFile:30) ~[?:?]
        at net.minecraft.network.play.client.CClientStatusPacket.func_148833_a(SourceFile:8) ~[?:?]
        at net.minecraft.network.PacketThreadUtil.lambda$ensureRunningOnSameThread$1(PacketThreadUtil.java:28) ~[?:?]
        at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?]
        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(ThreadTaskExecutor.java:152) ~[?:?]
        at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:899) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:179) ~[?:?]
        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(ThreadTaskExecutor.java:125) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:882) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:876) ~[?:?]
        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(ThreadTaskExecutor.java:135) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:862) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:782) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:283) ~[?:?]
        at java.lang.Thread.run(Unknown Source) [?:?]

**Mod list :** https://hastebin.com/copiqeluci.csharp

**Plugin list :** https://haste.mohistmc.com/eguqigarah

**Description of issue :** When someone is dead and wanna respawn, he his kicked and when he reconnect to the server he is dead again and kicked, dead, etc...

**Comment by GitJhopa** [comment]
yes +++ the same problem all players kicked..

**Comment by GitJhopa** [comment]
and where is the fix? players can't play normally
please

**Comment by Shawiizz** [comment]
Just wait

**Comment by GitJhopa** [comment]
ok bro

**Comment by Black-INV** [comment]
I had the same error and solve it deleting playerdata folder wolrd\playerdata. For some reason the .dat and .dat_old files are not compatible with the new build and cause the Packet error when pressing the respawn button
