### ISSUE TITLE
[BUG 1.16.5]  Error whilst processing packet net.minecraft.network.play.client.CClientStatusPacket@6b502989

### ISSUE THREAD

**Issue by GitJhopa** [Teneted/Tenet#1525]
Minecraft Version : 1.16.5

Mohist Version : 698

Operating System : Windows 10 64 bit
Logs :

[16:19:32 ERROR]: Error whilst processing packet net.minecraft.network.play.client.CClientStatusPacket@6cfada97 for ewka00[/95.83.143.102:63212]
java.lang.ClassCastException: class net.minecraft.tags.TagRegistry$NamedTag cannot be cast to class net.minecraft.tags.Tag (net.minecraft.tags.TagRegistry$NamedTag and net.minecraft.tags.Tag are in unnamed module of loader cpw.mods.modlauncher.TransformingClassLoader @5eb5da12)
        at net.minecraft.server.management.PlayerList.moveToWorld(PlayerList.java:732) ~[?:?]
        at net.minecraft.server.management.PlayerList.func_232644_a_(PlayerList.java:647) ~[?:?]
        at net.minecraft.network.play.ServerPlayNetHandler.func_147342_a(ServerPlayNetHandler.java:2119) ~[?:?]
        at net.minecraft.network.play.client.CClientStatusPacket.func_148833_a(SourceFile:30) ~[?:?]
        at net.minecraft.network.play.client.CClientStatusPacket.func_148833_a(SourceFile:8) ~[?:?]
        at net.minecraft.network.PacketThreadUtil.lambda$ensureRunningOnSameThread$1(PacketThreadUtil.java:28) ~[?:?]
        at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?]
        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(ThreadTaskExecutor.java:152) ~[?:?]
        at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:899) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:179) ~[?:?]
        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(ThreadTaskExecutor.java:125) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:882) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:876) ~[?:?]
        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(ThreadTaskExecutor.java:135) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:862) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:782) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:283) ~[?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
[16:19:32 INFO]: ewka00 lost connection: Packet processing error

Mod list : custom

Plugin list : custom

Description of issue : When someone is dead and wanna respawn, he his kicked and when he reconnect to the server he is dead again and kicked, dead, etc...

**Comment by GitJhopa** [comment]
hehe boy
![image](https://user-images.githubusercontent.com/86250668/125084003-b8e90e00-e0d1-11eb-84b1-5682d4c3512b.png)

**Comment by Romaindu35** [comment]
JUST STOP OPEN DUPLUICATE ISSUE !!!!!
