### ISSUE TITLE
error kick when player died

### ISSUE THREAD

**Issue by Tealwen** [Teneted/Tenet#1528]
**Minecraft Version :** 1.16.5

**Mohist Version :** latest

**Operating System :** Ubuntu

**Logs :** 
`Error whilst processing packet net.minecraft.network.play.client.CClientStatusPacket@1d14fd02 for Droopi29[/176.163.248.52:60523]
Console19:26:16
java.lang.ClassCastException: class net.minecraft.tags.TagRegistry$NamedTag cannot be cast to class net.minecraft.tags.Tag (net.minecraft.tags.TagRegistry$NamedTag and net.minecraft.tags.Tag are in unnamed module of loader cpw.mods.modlauncher.TransformingClassLoader @7708b66a)
at net.minecraft.server.management.PlayerList.moveToWorld(PlayerList.java:735) ~[?:?]
at net.minecraft.server.management.PlayerList.func_232644_a_(PlayerList.java:647) ~[?:?]
at net.minecraft.network.play.ServerPlayNetHandler.func_147342_a(ServerPlayNetHandler.java:2119) ~[?:?]
at net.minecraft.network.play.client.CClientStatusPacket.func_148833_a(SourceFile:30) ~[?:?]
at net.minecraft.network.play.client.CClientStatusPacket.func_148833_a(SourceFile:8) ~[?:?]
at net.minecraft.network.PacketThreadUtil.lambda$ensureRunningOnSameThread$1(PacketThreadUtil.java:28) ~[?:?]
at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?]
at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(ThreadTaskExecutor.java:152) ~[?:?]
at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?]
at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:899) ~[?:?]
at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:179) ~[?:?]
at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(ThreadTaskExecutor.java:125) ~[?:?]
at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:882) ~[?:?]
at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:876) ~[?:?]
at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(ThreadTaskExecutor.java:135) ~[?:?]
at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:862) ~[?:?]
at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:782) ~[?:?]
at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:283) ~[?:?]
at java.lang.Thread.run(Thread.java:829) [?:?]`

**Mod list :** Engineer life 2

**Plugin list :** LuckPerms, Harbor, Automessage, EggRespawn, BanItem, ClearLag, RedProtect, Vault, LoneLibs, TrixCore, LPC, ProtocolLib, WitherSound, ServerBooster, AuthMe, TAB, CMILib, CMI

**Description of issue :** error when player died !

**Comment by Shawiizz** [comment]
Please use last build.

**Comment by Tealwen** [comment]
i use the version 700

**Comment by Romaindu35** [comment]
Are tou this errors with empty server ?
Because me, when I died and respawn, I don't have any errors

**Comment by Tealwen** [comment]
i have the error whe i died withe other player on it , but maybee when the bug is present before the update we have to reset playerdata =D

**Comment by Tealwen** [comment]
a player died just now and it's alway kicked for the same things !

**Comment by Romaindu35** [comment]
I know !!

**Comment by Shawiizz** [comment]
@Tealwen please be patient.
