### ISSUE TITLE
[1.12.2] Mohist erroring from DynamicTrees

### ISSUE THREAD

**Issue by Zilacon** [Teneted/Tenet#155]
Never seen this error until build 407.
```
[13:45:36 WARN]: Warning: Tried to create a EntityFallingTree with no branch blocks. This shouldn't be possible.
[13:45:36 WARN]: java.lang.Exception
[13:45:36 WARN]: 	at com.ferreusveritas.dynamictrees.entities.EntityFallingTree.setData(EntityFallingTree.java:101)
[13:45:36 WARN]: 	at com.ferreusveritas.dynamictrees.entities.EntityFallingTree.dropTree(EntityFallingTree.java:462)
[13:45:36 WARN]: 	at com.ferreusveritas.dynamictrees.blocks.BlockBranch.futureBreak(BlockBranch.java:433)
[13:45:36 WARN]: 	at com.ferreusveritas.dynamictrees.event.FutureBreak.process(FutureBreak.java:48)
[13:45:36 WARN]: 	at com.ferreusveritas.dynamictrees.event.CommonEventHandler.onWorldTick(CommonEventHandler.java:21)
[13:45:36 WARN]: 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_406_CommonEventHandler_onWorldTick_WorldTickEvent.invoke(.dynamic)
[13:45:36 WARN]: 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
[13:45:36 WARN]: 	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:189)
[13:45:36 WARN]: 	at net.minecraftforge.fml.common.FMLCommonHandler.onPreWorldTick(FMLCommonHandler.java:287)
[13:45:36 WARN]: 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:889)
[13:45:36 WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:468)
[13:45:36 WARN]: 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:786)
[13:45:36 WARN]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:630)
[13:45:36 WARN]: 	at java.lang.Thread.run(Thread.java:821)
```
https://github.com/Mohist-Community/Mohist/issues/147 is still an issue on build 407, in fact its worse. Now its deadlocking from loading usercache at start up instead of shutdown.

**Comment by CKATEPTb** [comment]
Was this problem resolved on its own? During testing, I do not notice such an error, please double-check on the latest build.

**Comment by Shawiizz** [comment]
Hi, after testing i don't see any problems. The mod works perfectly without any warn / errors.
