### ISSUE TITLE
[1.16.5] The plugin "Lands" does not work

### ISSUE THREAD

**Issue by frogden** [Teneted/Tenet#1556]
**Minecraft Version: 1.16.5

**Mohist Version : 1.16.5, build 707

**Operating System : Debian 10/Windows 10

Plugin: "Lands"

Log: (https://haste.avemedoed.online/vuzuqomefa)
[18:17:04 ERROR]: Could not pass event BlockFromToEvent to Lands v5.12.0
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:305) ~[forge:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[forge:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[forge:?]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:588) ~[forge:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:573) ~[forge:?]
        at net.minecraft.fluid.FlowingFluid.func_207937_a(FlowingFluid.java:163) ~[?:?]
        at net.minecraft.fluid.FlowingFluid.func_205575_a(FlowingFluid.java:139) ~[?:?]
        at net.minecraft.fluid.FlowingFluid.func_207191_a(FlowingFluid.java:444) ~[?:?]
        at net.minecraft.fluid.FluidState.func_206880_a(FluidState.java:70) ~[?:?]
        at net.minecraft.world.server.ServerWorld.lambda$tickLiquid$9(ServerWorld.java:768) ~[?:?]
        at java.util.Optional.ifPresent(Unknown Source) ~[?:?]
        at net.minecraft.world.server.ServerWorld.func_205339_a(ServerWorld.java:765) ~[?:?]
        at net.minecraft.world.server.ServerTickList.func_205365_a(ServerTickList.java:91) ~[?:?]
        at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:490) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1032) ~[?:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:945) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:760) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:270) ~[?:?]
        at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: java.lang.NoSuchMethodError: 'org.bukkit.Chunk org.bukkit.block.Block.getChunk()'
        at me.angeschossen.lands.CouHF.Ftlnw.Ftlnw(?:2783) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:303) ~[forge:?]
        ... 19 more

**Comment by KR33PYK1NG** [comment]
Fixed in build 708.
