### ISSUE TITLE
[1.16.5 BUG] no working Infernal Expansion latest beta

### ISSUE THREAD

**Issue by MrJorman** [Teneted/Tenet#1569]
crash.. fix pls. test you **infernal-expansion** latest beta and run..

**Comment by MrJorman** [comment]
```[14:43:24 INFO]: Launching target 'fmlserver' with arguments [--gameDir, .]
[14:43:24 WARN]: Reference map 'nethers_delight.refmap.json' for nethers_delight.mixins.json could not be read. If this is a development environment you can ignore this message
[14:43:25 WARN]: Error loading class: net/minecraft/client/renderer/entity/UndeadHorseRenderer (java.lang.ClassNotFoundException: null)
[14:43:25 WARN]: @Mixin target net.minecraft.client.renderer.entity.UndeadHorseRenderer was not found supplementaries.mixins.json:UndeadHorseRendererMixin
[14:43:25 FATAL]: Attempted to load class net/minecraft/client/entity/player/ClientPlayerEntity for invalid dist DEDICATED_SERVER
[14:43:25 WARN]: Error loading class: net/minecraft/client/entity/player/ClientPlayerEntity (java.lang.RuntimeException: Attempted to load class net/minecraft/client/entity/player/ClientPlayerEntity for invalid dist DEDICATED_SERVER)
[14:43:25 WARN]: @Mixin target net.minecraft.client.entity.player.ClientPlayerEntity was not found ars_nouveau.mixins.json:ClientElytraMixin
[14:43:25 INFO]: Adding 'on_block_change' ASM patch...
[14:43:26 INFO]: Added 'on_block_change' ASM patch!
[14:43:26 INFO]: Adding 'on_block_change' ASM patch...
[14:43:26 INFO]: Added 'on_block_change' ASM patch!
Exception in thread "main" [14:43:26 INFO]: [java.lang.ThreadGroup:uncaughtException:1050]: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
[14:43:26 INFO]: [java.lang.ThreadGroup:uncaughtException:1050]:        at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:39)
[14:43:26 INFO]: [java.lang.ThreadGroup:uncaughtException:1050]:        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
[14:43:26 INFO]: [java.lang.ThreadGroup:uncaughtException:1050]:        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
[14:43:26 INFO]: [java.lang.ThreadGroup:uncaughtException:1050]:        at cpw.mods.modlauncher.Launcher.run(Launcher.java:82)
[14:43:26 INFO]: [java.lang.ThreadGroup:uncaughtException:1050]:        at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)
[14:43:26 INFO]: [java.lang.ThreadGroup:uncaughtException:1050]:        at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:95)
[14:43:26 INFO]: [java.lang.ThreadGroup:uncaughtException:1050]:        at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:92)
[14:43:26 INFO]: [java.lang.ThreadGroup:uncaughtException:1050]:        at net.minecraftforge.server.ServerMain.main(ServerMain.java:89)
[14:43:26 INFO]: [java.lang.ThreadGroup:uncaughtException:1050]:        at pro.gravit.launcher.server.ServerWrapper.run(ServerWrapper.java:209)
[14:43:26 INFO]: [java.lang.ThreadGroup:uncaughtException:1050]:        at pro.gravit.launcher.server.ServerWrapper.main(ServerWrapper.java:70)
[14:43:26 INFO]: [java.lang.ThreadGroup:uncaughtException:1059]: Caused by: java.lang.reflect.InvocationTargetException
[14:43:26 INFO]: [java.lang.ThreadGroup:uncaughtException:1059]:        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[14:43:26 INFO]: [java.lang.ThreadGroup:uncaughtException:1059]:        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[14:43:26 INFO]: [java.lang.ThreadGroup:uncaughtException:1059]:        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[14:43:26 INFO]: [java.lang.ThreadGroup:uncaughtException:1059]:        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[14:43:26 INFO]: [java.lang.ThreadGroup:uncaughtException:1059]:        at net.minecraftforge.fml.loading.FMLServerLaunchProvider.lambda$launchService$0(FMLServerLaunchProvider.java:51)
[14:43:26 INFO]: [java.lang.ThreadGroup:uncaughtException:1059]:        at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
[14:43:26 INFO]: [java.lang.ThreadGroup:uncaughtException:1059]:        ... 9 more
[14:43:26 INFO]: [java.lang.Throwable:printStackTrace:648]: Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
[14:43:26 INFO]: [java.lang.Throwable:printStackTrace:648]:     at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
[14:43:26 INFO]: [java.lang.Throwable:printStackTrace:648]:     at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:223)
[14:43:26 INFO]: [java.lang.Throwable:printStackTrace:648]:     at org.spongepowered.asm.mixin.transformer.MixinTransformationHandler.processClass(MixinTransformationHandler.java:121)
[14:43:26 INFO]: [java.lang.Throwable:printStackTrace:648]:     at org.spongepowered.asm.launch.MixinLaunchPlugin.processClass(MixinLaunchPlugin.java:131)
[14:43:26 INFO]: [java.lang.Throwable:printStackTrace:648]:     at cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:154)
[14:43:26 INFO]: [java.lang.Throwable:printStackTrace:648]:     at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:85)
[14:43:26 INFO]: [java.lang.Throwable:printStackTrace:648]:     at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120)
[14:43:26 INFO]: [java.lang.Throwable:printStackTrace:648]:     at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:265)
[14:43:26 INFO]: [java.lang.Throwable:printStackTrace:648]:     at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136)
[14:43:26 INFO]: [java.lang.Throwable:printStackTrace:648]:     at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98)
[14:43:26 INFO]: [java.lang.Throwable:printStackTrace:648]:     at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
[14:43:26 INFO]: [java.lang.Throwable:printStackTrace:648]:     at net.minecraft.server.MinecraftServer.<clinit>(MinecraftServer.java:180)
[14:43:26 INFO]: [java.lang.Throwable:printStackTrace:648]:     at net.minecraft.server.Main.main(Main.java:116)
[14:43:26 INFO]: [java.lang.Throwable:printStackTrace:648]:     ... 15 more
[14:43:26 INFO]: [java.lang.Throwable:printStackTrace:671]: Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Callback method IE_setCustomFireFromLava(Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V in infernal-expansion.mixins.json:common.MixinEntity failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap infernal-expansion.refmap.json
[14:43:26 INFO]: [java.lang.Throwable:printStackTrace:671]:     at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:408)
[14:43:26 INFO]: [java.lang.Throwable:printStackTrace:671]:     at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1291)
[14:43:26 INFO]: [java.lang.Throwable:printStackTrace:671]:     at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1042)
[14:43:26 INFO]: [java.lang.Throwable:printStackTrace:671]:     at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395)
[14:43:26 INFO]: [java.lang.Throwable:printStackTrace:671]:     at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320)
[14:43:26 INFO]: [java.lang.Throwable:printStackTrace:671]:     at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
[14:43:26 INFO]: [java.lang.Throwable:printStackTrace:671]:     at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:569)
[14:43:26 INFO]: [java.lang.Throwable:printStackTrace:671]:     at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351)
[14:43:26 INFO]: [java.lang.Throwable:printStackTrace:671]:     ... 27 more```

**Comment by Romaindu35** [comment]
You just use client mod on server. It is not mohist error !

**Comment by Romaindu35** [comment]
Please sure that the bugs is relative at mohist before create issue
