### ISSUE TITLE
[1.16.5] Unable to use chat formatting plugins.

### ISSUE THREAD

**Issue by demiafk101** [Teneted/Tenet#1605]
**Minecraft Version :** 1.16.5

**Mohist Version :** 735

**Operating System :** Windows/Linux both.

**Concerned mod / plugin** : LuckPerms, Vault, Essentials, EssentialsChat (Fresh install)

**Logs :** 
[17:04:58] [Async Chat Thread - 2/ERROR] [Minecraft/]: Could not pass event AsyncPlayerChatEvent to EssentialsChat v2.19.0-dev+221-1556b91
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:305) ~[forge:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[forge:?]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[forge:?]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:588) ~[forge:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:570) ~[forge:?]
	at net.minecraft.network.play.ServerPlayNetHandler.chat(ServerPlayNetHandler.java:1747) ~[?:?]
	at net.minecraft.network.play.ServerPlayNetHandler.func_147354_a(ServerPlayNetHandler.java:1685) ~[?:?]
	at net.minecraft.network.play.client.CChatMessagePacket.lambda$handle$0(CChatMessagePacket.java:35) ~[?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:?]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: java.lang.NoSuchMethodError: 'boolean com.earth2me.essentials.User.isToggleShout()'
	at com.earth2me.essentials.chat.EssentialsChatPlayer.getChatType(EssentialsChatPlayer.java:39) ~[?:?]
	at com.earth2me.essentials.chat.EssentialsChatPlayerListenerLowest.onPlayerChat(EssentialsChatPlayerListenerLowest.java:36) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:303) ~[forge:?]
	... 12 more

**Steps to Reproduce :**
 1. Install EssentialsChat
 2. Add some suffix
 3. Use chat

**Description of issue :** Works fine on build 695

**Comment by Romaindu35** [comment]
Essential has been installed ? 
Because the problem is that essential method is missing.
Else, can you try on spigot server ?

**Comment by joaoespanhol** [comment]
my server, no have this problem.

![image](https://user-images.githubusercontent.com/22871432/128614032-82c07a46-abe0-4b01-a3f9-9023fec269ea.png)

**Comment by demiafk101** [comment]
Hi, 

On spigot server works fine, and the build 695 too. Actually in my Mohist: 1.16.5-734 have installed EssentialsX-2.18.2.0.jar(working) and EssentialsXChat-2.18.2.0.jar.

BR.

**Comment by demiafk101** [comment]
Testing on the last version I dont have any error message but I can't use the chat.

![image](https://user-images.githubusercontent.com/88058491/128614650-adddfd3a-1ade-4df9-86e9-57f0ee38f742.png)
