### ISSUE TITLE
[1.16.5] Lib's Disguises 10.0.26 can not be enable.

### ISSUE THREAD

**Issue by YKDZ** [Teneted/Tenet#1636]
**Minecraft Version : 1.16.5

**Mohist Version : mohist-1.16.5-744-server

**Operating System : centos 7

**Concerned mod / plugin** : https://www.spigotmc.org/resources/libs-disguises.32453/

**Logs 

```
[22:26:23 ERROR]: Error occurred while enabling LibsDisguises v10.0.26 (Is it up to date?)
java.lang.NullPointerException: null
	at com.mohistmc.bukkit.nms.proxy.ProxyClass.getDeclaredField(ProxyClass.java:40) ~[forge:?]
	at me.libraryaddict.disguise.utilities.reflection.ReflectionManager.getNmsField(ReflectionManager.java:961) ~[?:?]
	at me.libraryaddict.disguise.utilities.reflection.ReflectionManager.getNmsField(ReflectionManager.java:973) ~[?:?]
	at me.libraryaddict.disguise.utilities.reflection.ReflectionManager.init(ReflectionManager.java:323) ~[?:?]
	at me.libraryaddict.disguise.LibsDisguises.onEnable(LibsDisguises.java:212) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[forge:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) ~[forge:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:479) ~[forge:?]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:497) ~[forge:7e29f765-296df566-9fb885e8]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:411) ~[forge:7e29f765-296df566-9fb885e8]
	at net.minecraft.server.MinecraftServer.func_240787_a_(MinecraftServer.java:431) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240800_l__(MinecraftServer.java:350) ~[?:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:218) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:721) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:270) ~[?:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]
```

**Comment by Romaindu35** [comment]
Same #1413
