### ISSUE TITLE
[1.16.5] Skript can not be enabled

### ISSUE THREAD

**Issue by YKDZ** [Teneted/Tenet#1639]
**Minecraft Version : 1.16.5

**Mohist Version : build 742

**Operating System : centos 7

**Concerned mod / plugin** : https://github.com/SkriptLang/Skript/releases
**Logs 

`
[13:01:33] [Server thread/INFO] [ch.njol.skript.Skript/]: [Skript] Enabling Skript v2.6-beta2
[13:01:34] [Server thread/INFO] [Minecraft/]: [Skript] Your configuration has been updated to the latest version. A backup of your old config file has been created as config_2021-08-06_13-01-34.sk
[13:01:34] [Server thread/ERROR] [Minecraft/]: Error occurred while enabling Skript v2.6-beta2 (Is it up to date?)
java.lang.NoSuchFieldError: Legacy field ordinal: LEGACY_AIR
	at org.bukkit.craftbukkit.v1_16_R3.util.CraftLegacy.modern_ordinal(CraftLegacy.java:39) ~[forge:?]
	at ch.njol.skript.aliases.MaterialRegistry.load(MaterialRegistry.java:65) ~[?:?]
	at ch.njol.skript.aliases.ItemData.<clinit>(ItemData.java:101) ~[?:?]
	at ch.njol.skript.aliases.Aliases.<clinit>(Aliases.java:142) ~[?:?]
	at ch.njol.skript.Skript.onEnable(Skript.java:434) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[forge:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) ~[forge:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:479) ~[forge:?]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:497) ~[forge:7e29f765-296df566-9fb885e8]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:411) ~[forge:7e29f765-296df566-9fb885e8]
	at net.minecraft.server.MinecraftServer.func_240787_a_(MinecraftServer.java:431) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240800_l__(MinecraftServer.java:350) ~[?:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:218) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:721) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:270) ~[?:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]
`

**Comment by wdog5** [comment]
Please use the lastest version of the plugin,I have tested and find it no problem!
