### ISSUE TITLE
В процессе работы сервера на Mohist-e5dcef8 ошибка сохранения чанка иногда проскальзывает

### ISSUE THREAD

**Issue by Maks-Haswell** [Teneted/Tenet#18]
[20:13:21] [File IO Thread/ERROR] [net.minecraft.world.chunk.storage.AnvilChunkLoader]: Failed to save chunk
java.util.ConcurrentModificationException: null
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1445) ~[?:1.8.0_222]
	at java.util.HashMap$KeyIterator.next(HashMap.java:1469) ~[?:1.8.0_222]
	at net.minecraft.nbt.NBTTagCompound.func_74734_a(NBTTagCompound.java:32) ~[fy.class:?]
	at net.minecraft.nbt.CompressedStreamTools.func_150663_a(CompressedStreamTools.java:118) ~[gi.class:?]
	at net.minecraft.nbt.CompressedStreamTools.func_74800_a(CompressedStreamTools.java:108) ~[gi.class:?]
	at net.minecraft.world.chunk.storage.RegionFileCache.getChunkOutputStream(RegionFileCache.java:138) ~[ayk.class:?]
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_183013_b(AnvilChunkLoader.java:249) ~[aye.class:?]
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.processSaveQueueEntry(AnvilChunkLoader.java:225) [aye.class:?]
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75814_c(AnvilChunkLoader.java:197) [aye.class:?]
	at net.minecraft.world.storage.ThreadedFileIOBase.func_75736_b(SourceFile:37) [bgx.class:?]
	at net.minecraft.world.storage.ThreadedFileIOBase.run(SourceFile:30) [bgx.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]

**Comment by Mgazul** [comment]
Have you started the asyn world save? It is not recommended

**Comment by Maks-Haswell** [comment]
не понимаю ...19.10.2019, 15:21, "Mgazul" <notifications@github.com>:Have you started the asyn world save? It is not recommended

**Comment by Mgazul** [comment]
mohist-config/mohist.yml
asyn:
  worldsave: false

**Comment by Maks-Haswell** [comment]
у меня так и стоит worldsave: false  но всё равно данная ошибка  попадается иногда 19.10.2019, 15:28, "Mgazul" <notifications@github.com>:mohist-config/mohist.yml
asyn:
worldsave: false
