### ISSUE TITLE
1.12.2 not loading bukkit plugins on latest release

### ISSUE THREAD

**Issue by sentest** [Teneted/Tenet#185]
[14:47:11] [Server thread/ERROR] [Mohist]: Could not load plugins/Clearlag.jar in folder plugins because plugin invalid
org.bukkit.plugin.InvalidPluginException: java.lang.IllegalStateException: JavaPlugin requires org.bukkit.plugin.java.PluginClassLoader
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:133) ~[JavaPluginLoader.class:6cfee20]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:323) ~[SimplePluginManager.class:6cfee20]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:245) [SimplePluginManager.class:6cfee20]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.loadPlugins(CraftServer.java:388) [CraftServer.class:6cfee20]
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:347) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:316) [nz.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:595) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
Caused by: java.lang.IllegalStateException: JavaPlugin requires org.bukkit.plugin.java.PluginClassLoader
	at org.bukkit.plugin.java.JavaPlugin.<init>(JavaPlugin.java:48) ~[JavaPlugin.class:6cfee20]
	at me.minebuilders.clearlag.Clearlag.<init>(Clearlag.java:17) ~[Clearlag.class:?]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_242]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_242]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_242]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_242]
	at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_242]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:65) ~[PluginClassLoader.class:6cfee20]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:129) ~[JavaPluginLoader.class:6cfee20]
	... 7 more
[14:47:11] [Server thread/ERROR] [Mohist]: Could not load plugins/PerfectBackup.jar in folder plugins because plugin invalid
org.bukkit.plugin.InvalidPluginException: java.lang.IllegalStateException: JavaPlugin requires org.bukkit.plugin.java.PluginClassLoader
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:133) ~[JavaPluginLoader.class:6cfee20]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:323) ~[SimplePluginManager.class:6cfee20]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:245) [SimplePluginManager.class:6cfee20]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.loadPlugins(CraftServer.java:388) [CraftServer.class:6cfee20]
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:347) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:316) [nz.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:595) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
Caused by: java.lang.IllegalStateException: JavaPlugin requires org.bukkit.plugin.java.PluginClassLoader
	at org.bukkit.plugin.java.JavaPlugin.<init>(JavaPlugin.java:48) ~[JavaPlugin.class:6cfee20]
	at me.au2001.PerfectBackup.PerfectBackup.<init>(PerfectBackup.java:19) ~[PerfectBackup.class:?]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_242]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_242]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_242]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_242]
	at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_242]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:65) ~[PluginClassLoader.class:6cfee20]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:129) ~[JavaPluginLoader.class:6cfee20]
	... 7 more
[14:47:12] [Server thread/ERROR] [Mohist]: Could not load plugins/movemenow-1.2-17.jar in folder plugins because plugin invalid
org.bukkit.plugin.InvalidPluginException: Cannot find main class `net.craftminecraft.bungee.movemenow.MoveMeNow'
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:55) ~[PluginClassLoader.class:6cfee20]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:129) ~[JavaPluginLoader.class:6cfee20]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:323) ~[SimplePluginManager.class:6cfee20]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:245) [SimplePluginManager.class:6cfee20]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.loadPlugins(CraftServer.java:388) [CraftServer.class:6cfee20]
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:347) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:316) [nz.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:595) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
Caused by: java.lang.ClassNotFoundException: Failed to remap class net.craftminecraft.bungee.movemenow.MoveMeNow
	at org.bukkit.plugin.java.PluginClassLoader.remappedFindClass(PluginClassLoader.java:174) ~[PluginClassLoader.class:6cfee20]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:98) ~[PluginClassLoader.class:6cfee20]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:75) ~[PluginClassLoader.class:6cfee20]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:419) ~[?:1.8.0_242]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:352) ~[?:1.8.0_242]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_242]
	at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_242]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:53) ~[PluginClassLoader.class:6cfee20]
	... 8 more
Caused by: java.lang.NoClassDefFoundError: net/md_5/bungee/api/plugin/Plugin
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_242]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:757) ~[?:1.8.0_242]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.8.0_242]
	at org.bukkit.plugin.java.PluginClassLoader.remappedFindClass(PluginClassLoader.java:166) ~[PluginClassLoader.class:6cfee20]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:98) ~[PluginClassLoader.class:6cfee20]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:75) ~[PluginClassLoader.class:6cfee20]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:419) ~[?:1.8.0_242]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:352) ~[?:1.8.0_242]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_242]
	at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_242]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:53) ~[PluginClassLoader.class:6cfee20]
	... 8 more
Caused by: java.lang.ClassNotFoundException: net.md_5.bungee.api.plugin.Plugin
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:106) ~[PluginClassLoader.class:6cfee20]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:75) ~[PluginClassLoader.class:6cfee20]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:419) ~[?:1.8.0_242]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:352) ~[?:1.8.0_242]
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_242]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:757) ~[?:1.8.0_242]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.8.0_242]
	at org.bukkit.plugin.java.PluginClassLoader.remappedFindClass(PluginClassLoader.java:166) ~[PluginClassLoader.class:6cfee20]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:98) ~[PluginClassLoader.class:6cfee20]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:75) ~[PluginClassLoader.class:6cfee20]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:419) ~[?:1.8.0_242]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:352) ~[?:1.8.0_242]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_242]
	at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_242]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:53) ~[PluginClassLoader.class:6cfee20]
	... 8 more
[14:47:12] [Server thread/ERROR] [Mohist]: Could not load plugins/PlugMan.jar in folder plugins because plugin invalid
org.bukkit.plugin.InvalidPluginException: java.lang.IllegalStateException: JavaPlugin requires org.bukkit.plugin.java.PluginClassLoader
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:133) ~[JavaPluginLoader.class:6cfee20]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:323) ~[SimplePluginManager.class:6cfee20]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:245) [SimplePluginManager.class:6cfee20]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.loadPlugins(CraftServer.java:388) [CraftServer.class:6cfee20]
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:347) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:316) [nz.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:595) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
Caused by: java.lang.IllegalStateException: JavaPlugin requires org.bukkit.plugin.java.PluginClassLoader
	at org.bukkit.plugin.java.JavaPlugin.<init>(JavaPlugin.java:48) ~[JavaPlugin.class:6cfee20]
	at com.rylinaux.plugman.PlugMan.<init>(PlugMan.java:40) ~[PlugMan.class:?]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_242]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_242]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_242]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_242]
	at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_242]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:65) ~[PluginClassLoader.class:6cfee20]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:129) ~[JavaPluginLoader.class:6cfee20]
	... 7 more
[14:47:12] [Server thread/ERROR] [Mohist]: Could not load plugins/SkinsRestorer.jar in folder plugins because plugin invalid
org.bukkit.plugin.InvalidPluginException: java.lang.IllegalStateException: JavaPlugin requires org.bukkit.plugin.java.PluginClassLoader
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:133) ~[JavaPluginLoader.class:6cfee20]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:323) ~[SimplePluginManager.class:6cfee20]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:245) [SimplePluginManager.class:6cfee20]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.loadPlugins(CraftServer.java:388) [CraftServer.class:6cfee20]
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:347) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:316) [nz.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:595) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
Caused by: java.lang.IllegalStateException: JavaPlugin requires org.bukkit.plugin.java.PluginClassLoader
	at org.bukkit.plugin.java.JavaPlugin.<init>(JavaPlugin.java:48) ~[JavaPlugin.class:6cfee20]
	at skinsrestorer.bukkit.SkinsRestorer.<init>(SkinsRestorer.java:34) ~[SkinsRestorer.class:?]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_242]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_242]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_242]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_242]
	at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_242]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:65) ~[PluginClassLoader.class:6cfee20]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:129) ~[JavaPluginLoader.class:6cfee20]
	... 7 more
[14:47:12] [Server thread/ERROR] [Mohist]: Could not load plugins/EntityWatch.jar in folder plugins because plugin invalid
org.bukkit.plugin.InvalidPluginException: java.lang.IllegalStateException: JavaPlugin requires org.bukkit.plugin.java.PluginClassLoader
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:133) ~[JavaPluginLoader.class:6cfee20]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:323) ~[SimplePluginManager.class:6cfee20]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:245) [SimplePluginManager.class:6cfee20]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.loadPlugins(CraftServer.java:388) [CraftServer.class:6cfee20]
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:347) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:316) [nz.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:595) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
Caused by: java.lang.IllegalStateException: JavaPlugin requires org.bukkit.plugin.java.PluginClassLoader
	at org.bukkit.plugin.java.JavaPlugin.<init>(JavaPlugin.java:48) ~[JavaPlugin.class:6cfee20]
	at com.hm.ew.EntityWatch.<init>(EntityWatch.java:87) ~[EntityWatch.class:?]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_242]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_242]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_242]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_242]
	at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_242]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:65) ~[PluginClassLoader.class:6cfee20]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:129) ~[JavaPluginLoader.class:6cfee20]
	... 7 more
[14:47:12] [Server thread/ERROR] [Mohist]: Could not load plugins/SaveDeathDrops.jar in folder plugins,
org.bukkit.plugin.UnknownDependencyException: The plugin load need a depend:ClearLag
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:220) [SimplePluginManager.class:6cfee20]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.loadPlugins(CraftServer.java:388) [CraftServer.class:6cfee20]
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:347) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:316) [nz.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:595) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
[14:47:12] [Server thread/ERROR] [Mohist]: Could not load plugins/ServerSelectorX-Connector-2.1.0.jar in folder plugins because plugin invalid
org.bukkit.plugin.InvalidPluginException: java.lang.IllegalStateException: JavaPlugin requires org.bukkit.plugin.java.PluginClassLoader
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:133) ~[JavaPluginLoader.class:6cfee20]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:323) ~[SimplePluginManager.class:6cfee20]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:245) [SimplePluginManager.class:6cfee20]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.loadPlugins(CraftServer.java:388) [CraftServer.class:6cfee20]
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:347) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:316) [nz.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:595) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
Caused by: java.lang.IllegalStateException: JavaPlugin requires org.bukkit.plugin.java.PluginClassLoader
	at org.bukkit.plugin.java.JavaPlugin.<init>(JavaPlugin.java:48) ~[JavaPlugin.class:6cfee20]
	at xyz.derkades.ssx_connector.Main.<init>(Main.java:19) ~[Main.class:?]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_242]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_242]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_242]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_242]
	at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_242]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:65) ~[PluginClassLoader.class:6cfee20]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:129) ~[JavaPluginLoader.class:6cfee20]
	... 7 more

**Comment by Mgazul** [comment]
Check if your plugin is damaged, I tested it many times without encountering your problem
