### ISSUE TITLE
库文件下载地址失效

### ISSUE THREAD

**Issue by LTHPKBTE** [Teneted/Tenet#19]
第一次启动服务器，没有库文件，自动下载报错如下：
`检测到你的库文件存在新版本或者不存在，即将自动下载......

请在库文件获取完毕后, 重启服务器
java.net.UnknownHostException:  mohist-community.gitee.io
        at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
        at java.net.PlainSocketImpl.connect(Unknown Source)
        at java.net.SocksSocketImpl.connect(Unknown Source)
        at java.net.Socket.connect(Unknown Source)
        at sun.security.ssl.SSLSocketImpl.connect(Unknown Source)
        at sun.net.NetworkClient.doConnect(Unknown Source)
        at sun.net.www.http.HttpClient.openServer(Unknown Source)
        at sun.net.www.http.HttpClient.openServer(Unknown Source)
        at sun.net.www.protocol.https.HttpsClient.<init>(Unknown Source)
        at sun.net.www.protocol.https.HttpsClient.New(Unknown Source)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(Unknown Source)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(Unknown Source)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
        at java.net.HttpURLConnection.getResponseCode(Unknown Source)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(Unknown Source)
        at red.mohist.down.Download.<init>(Download.java:23)
        at red.mohist.down.DownloadLibraries.run(DownloadLibraries.java:26)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Exception in thread "pool-1-thread-1" java.lang.RuntimeException: libraries.zipThe file indicated does not exist.
        at red.mohist.down.DownloadLibraries.unZip(DownloadLibraries.java:35)
        at red.mohist.down.DownloadLibraries.run(DownloadLibraries.java:28)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)`
直接用浏览器访问mohist-community.gitee.io返回404。

**Comment by Mgazul** [comment]
我测试了 没问题呀 检查你的网络

**Comment by LTHPKBTE** [comment]
。。。原来是没有检测到minecraft_server.1.12.2.jar
我给改名了

**Comment by Mgazul** [comment]
不需要minecraft_server.1.12.2.jar的  它已经包含在lib里面了 你用的旧版核心？

**Comment by LTHPKBTE** [comment]
刚刚下载的Mohist-51fee0d-server.jar

**Comment by Mgazul** [comment]
https://ci.codemc.io/job/Mohist-Community/job/Mohist-1.12.2/  在这里下载最新构建

**Comment by LTHPKBTE** [comment]
更新检测中......
如果你不想启用更新检测, 请将 mohist-config/mohist.yml 里 check_update 设为false
Exception in thread "main" java.lang.StringIndexOutOfBoundsException: String index out of range: 22
        at java.lang.String.substring(Unknown Source)
        at red.mohist.down.Update.hasLatestVersion(Update.java:34)
        at red.mohist.Mohist.main(Mohist.java:65)
这是什么问题?libraries刚刚看了没有问题

**Comment by Mgazul** [comment]
你把更新检测关了就行

**Comment by Mgazul** [comment]
我测试了一下 应该是网络访问炸了 然后读不到数据就炸了

**Comment by LTHPKBTE** [comment]
启动了，谢谢

**Comment by LTHPKBTE** [comment]
VeinMiner报的方块ID找不到正常吗

**Comment by LTHPKBTE** [comment]
[VeinMiner] Block id minecraft:XXXXX not found! Ignoring这样的

**Comment by LTHPKBTE** [comment]
VeinMiner是连锁挖矿服务器插件版，目前好像全部矿物都无法识别

**Comment by Mgazul** [comment]
https://jq.qq.com/?_wv=1027&k=5YIRYnH 如果你有qq 去群里讨论问题吧
