### ISSUE TITLE
Issues with block/multiblocks

### ISSUE THREAD

**Issue by kaziu687** [Teneted/Tenet#195]
After update (works well at 0356c95f8fd8a153b1450874149f3723b713ca8b) some blocks from ic2 (not only cable multiblock) are replaced like that in whole chunks:

![chrome_Xe9ygd6YFs](https://user-images.githubusercontent.com/1757563/78458117-452aab00-76af-11ea-9cbc-0f5b8a2c1448.png)

Probably not only ic2 is affected, someone submitted me "empty storage drawers" after some period of time. I will send stacktrace/more info when occurs (for now grep found nothing interesting).

**Comment by kaziu687** [comment]
Probably crash affected by bug

```
Description: Ticking block entity

java.lang.IllegalArgumentException: Cannot get property PropertyEnum{name=variant, clazz=class vazkii.botania.api.state.enums.AltarVariant, values=[DEFAULT, FOREST, PLAINS, MOUNTAIN, FUNGAL, SWAMP, DESERT, TAIGA, MESA, MOSSY]} as it does not exist in BlockStateContainer{block=minecraft:air, properties=[]}
        at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177229_b(BlockStateContainer.java:201)
        at vazkii.botania.common.block.tile.TileAltar.collideEntityItem(TileAltar.java:89)
        at vazkii.botania.common.block.tile.TileAltar.func_73660_a(TileAltar.java:241)
        at net.minecraft.world.World.func_72939_s(World.java:2212)
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:746)
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:909)
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:466)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:788)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:632)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by kaziu687** [comment]
Today problem affected every loaded chunk with ic2 cables after crash (two NPE in independent mods), maybe problem with saving world data when crash occurs?

**Comment by kaziu687** [comment]
No major issues for now, closing.
