### ISSUE TITLE
[1.16.5] Item Borders and BrassAmberBattleTowers incompatibility

### ISSUE THREAD

**Issue by SkullDiamond** [Teneted/Tenet#1956]
**Minecraft Version :** 1.16.5

**Mohist Version :** 904

**Operating System :** Windows 10

**Concerned mod / plugin** : BrassAmberBattleTowers (mod) / Item Borders (mod)

**Logs :** 
---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 1/1/22 21:47
Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
	at net.minecraftforge.fml.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:86) ~[forge:?] {re:classloading}
	at net.minecraftforge.fml.server.ServerModLoader.load(ServerModLoader.java:51) ~[forge:?] {re:classloading}
	at net.minecraft.server.Main.main(Main.java:144) ~[?:?] {re:classloading,re:mixin,pl:mixin:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.FMLServerLaunchProvider.lambda$launchService$0(FMLServerLaunchProvider.java:51) ~[mohist-1.16.5-904-server.jar:36.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {}
	at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:131) [mohist-1.16.5-904-server.jar:?] {}
	at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:128) [mohist-1.16.5-904-server.jar:?] {}
	at net.minecraftforge.server.ServerMain.main(ServerMain.java:112) [mohist-1.16.5-904-server.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: main
Stacktrace:
	at java.lang.ClassLoader.findClass(ClassLoader.java:718) ~[?:?] {}
-- MOD itemborders --
Details:
	Caused by 0: java.lang.NoClassDefFoundError: net/minecraft/client/util/ITooltipFlag
		at com.anthonyhilyard.itemborders.ItemBordersConfig.<init>(ItemBordersConfig.java:106) ~[itemborders:1.1.6] {re:classloading}
		at net.minecraftforge.common.ForgeConfigSpec$Builder.configure(ForgeConfigSpec.java:613) ~[forge:?] {re:classloading}
		at com.anthonyhilyard.itemborders.ItemBordersConfig.<clinit>(ItemBordersConfig.java:39) ~[itemborders:1.1.6] {re:classloading}
		at java.lang.Class.forName0(Native Method) ~[?:?] {}
		at java.lang.Class.forName(Class.java:467) ~[?:?] {}
		at net.minecraftforge.fml.AutomaticEventSubscriber.lambda$inject$6(AutomaticEventSubscriber.java:76) ~[forge:?] {re:classloading}
		at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?] {}
		at net.minecraftforge.fml.AutomaticEventSubscriber.inject(AutomaticEventSubscriber.java:63) ~[forge:?] {re:classloading}
		at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:92) ~[forge:36.2] {re:classloading}
		at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:120) ~[forge:?] {re:classloading}
		at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
		at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:computing_frames}
		at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:computing_frames}
		at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}

	Mod File: ItemBorders-1.16.5-1.1.6.jar
	Failure message: Item Borders (itemborders) has failed to load correctly
		java.lang.NoClassDefFoundError: net/minecraft/client/util/ITooltipFlag
	Mod Version: 1.1.6
	Mod Issue URL: NOT PROVIDED
	Exception message: java.lang.ClassNotFoundException: net.minecraft.client.util.ITooltipFlag
Stacktrace:
	at java.lang.ClassLoader.findClass(ClassLoader.java:718) ~[?:?] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:587) ~[?:?] {}
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:106) ~[modlauncher-8.0.9.jar:?] {re:classloading}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {}
	at com.anthonyhilyard.itemborders.ItemBordersConfig.<init>(ItemBordersConfig.java:106) ~[itemborders:1.1.6] {re:classloading}
	at net.minecraftforge.common.ForgeConfigSpec$Builder.configure(ForgeConfigSpec.java:613) ~[forge:?] {re:classloading}
	at com.anthonyhilyard.itemborders.ItemBordersConfig.<clinit>(ItemBordersConfig.java:39) ~[itemborders:1.1.6] {re:classloading}
	at java.lang.Class.forName0(Native Method) ~[?:?] {}
	at java.lang.Class.forName(Class.java:467) ~[?:?] {}
	at net.minecraftforge.fml.AutomaticEventSubscriber.lambda$inject$6(AutomaticEventSubscriber.java:76) ~[forge:?] {re:classloading}
	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?] {}
	at net.minecraftforge.fml.AutomaticEventSubscriber.inject(AutomaticEventSubscriber.java:63) ~[forge:?] {re:classloading}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:92) ~[forge:36.2] {re:classloading}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:120) ~[forge:?] {re:classloading}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:computing_frames}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}

-- MOD ba_bt --
Details:
	Mod File: BrassAmberBattleTowers-1.16.5-1.1.3.jar
	Failure message: Brass Amber BattleTowers (ba_bt) has failed to load correctly
		java.lang.RuntimeException: Attempted to load class net/minecraft/client/renderer/texture/AtlasTexture for invalid dist DEDICATED_SERVER
	Mod Version: 1.16.5-1.1.3
	Mod Issue URL: NOT PROVIDED
	Exception message: java.lang.RuntimeException: Attempted to load class net/minecraft/client/renderer/texture/AtlasTexture for invalid dist DEDICATED_SERVER
Stacktrace:
	at net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:71) ~[mohist-1.16.5-904-server.jar:36.2] {}
	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:85) ~[modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:265) ~[modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136) ~[modlauncher-8.0.9.jar:?] {re:classloading}
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98) ~[modlauncher-8.0.9.jar:?] {re:classloading}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {}
	at java.lang.Class.getDeclaredConstructors0(Native Method) ~[?:?] {}
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:3373) ~[?:?] {}
	at java.lang.Class.getConstructor0(Class.java:3578) ~[?:?] {}
	at java.lang.Class.getConstructor(Class.java:2271) ~[?:?] {}
	at net.minecraftforge.eventbus.api.EventListenerHelper.computeListenerList(EventListenerHelper.java:96) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.api.EventListenerHelper.getListenerListInternal(EventListenerHelper.java:63) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.api.EventListenerHelper.getListenerList(EventListenerHelper.java:48) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.addToListeners(EventBus.java:263) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.register(EventBus.java:256) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.registerListener(EventBus.java:150) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$registerClass$2(EventBus.java:78) ~[eventbus-4.0.0.jar:?] {}
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?] {}
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?] {}
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?] {}
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992) ~[?:?] {}
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?] {}
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?] {}
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?] {}
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?] {}
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?] {}
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.registerClass(EventBus.java:78) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.register(EventBus.java:118) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.fml.AutomaticEventSubscriber.lambda$inject$6(AutomaticEventSubscriber.java:76) ~[forge:?] {re:classloading}
	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?] {}
	at net.minecraftforge.fml.AutomaticEventSubscriber.inject(AutomaticEventSubscriber.java:63) ~[forge:?] {re:classloading}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:92) ~[forge:36.2] {re:classloading}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:120) ~[forge:?] {re:classloading}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:computing_frames}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}

**Steps to Reproduce :**
 1. Create a new world 
 
**Description of issue :** Give all details about your issue

**Comment by MagnusHJensen** [comment]
We have not had any problems with Item Borders on our server.

**Comment by SkullDiamond** [comment]
So why is saying this ? Failure message: Item Borders (itemborders) has failed to load correctly

**Comment by joaoespanhol** [comment]
> So why is saying this ? Failure message: Item Borders (itemborders) has failed to load correctly

SEND LOG AND DEBUG PLEASE :)

**Comment by SkullDiamond** [comment]
[latest.log](https://github.com/MohistMC/Mohist/files/7798375/latest.log)
[debug.log](https://github.com/MohistMC/Mohist/files/7798376/debug.log)

**Comment by joaoespanhol** [comment]
> [latest.log](https://github.com/MohistMC/Mohist/files/7798375/latest.log) [debug.log](https://github.com/MohistMC/Mohist/files/7798376/debug.log)

i forget soliciting Crash report saved to .\crash-reports\crash-2022-01-02_01.04.09-fml.txt

Send please

**Comment by joaoespanhol** [comment]
![image](https://user-images.githubusercontent.com/22871432/147862936-7a267a0a-43eb-4357-b531-613587c995ac.png)

**Comment by joaoespanhol** [comment]
More info: 

This is problem mod: https://github.com/JMilamber/Brass_Amber_BattleTowers/issues/51

**Comment by SkullDiamond** [comment]
oh my bad, so sorry didnt see it was client side and that there was a post already for the BattleTower <3
