### ISSUE TITLE
[1.12.2] Nether is being disabled incorrectly

### ISSUE THREAD

**Issue by Serega007RU** [Teneted/Tenet#1963]
**Minecraft Version :** 1.12.2

**Mohist Version :** 295

**Operating System :** Linux Ubuntu Server 21.10

**Logs :** [latest.log](https://github.com/MohistMC/Mohist/files/7809105/latest.log)

**Mod list :** https://haste.mohistmc.com/nadonudeci (no mods)

**Plugin list :** https://haste.mohistmc.com/akorowosor (no plugins)

**Description of issue :** If you set the "allow-nether" parameter to false in server.properties and try to log in to Nether through the portal, then the console will be spammed with this error
```
[19:51:49] [Server thread/FATAL] [net.minecraft.server.MinecraftServer]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_311]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_311]
	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:840) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:461) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:778) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:624) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_311]
Caused by: java.lang.NullPointerException
	at net.minecraft.network.NetHandlerPlayServer.func_147347_a(NetHandlerPlayServer.java:770) ~[pa.class:?]
	at net.minecraft.network.play.client.CPacketPlayer.func_148833_a(CPacketPlayer.java:33) ~[lk.class:?]
	at net.minecraft.network.play.client.CPacketPlayer$Position.func_148833_a(CPacketPlayer.java:76) ~[lk$a.class:?]
	at net.minecraft.network.PacketThreadUtil.lambda$checkThreadAndEnqueue$0(PacketThreadUtil.java:16) ~[hv.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_311]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_311]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	... 5 more
```
There is no such problem on mohist version 162, but I don't know exactly from which version this problem appeared

**Comment by Serega007RU** [comment]
So, I found out that this commit ab5db672ce88b8340c47707d3c0a30474577cb7c is to blame for this error
Now it remains to parse the code and understand why this error occurs

**Comment by Serega007RU** [comment]
Also, the cancellation of the PlayerPortalEvent in bukkit is broken
Here is a video that clearly demonstrates this
https://drive.google.com/file/d/1vlKZFRleGy6qnd2gc0BAnxGFCokk24pB/view?usp=sharing

**Comment by Serega007RU** [comment]
Well, the problem is solved
