### ISSUE TITLE
[1.16.5] Server Crash after dead

### ISSUE THREAD

**Issue by lxgnzlz05** [Teneted/Tenet#1966]
**Mohist Version :** 905

  **Concerned mod / plugin** : [Locks](https://www.curseforge.com/minecraft/mc-mods/locks) && [Dungeons gear](https://www.curseforge.com/minecraft/mc-mods/dungeons-gear)

**Logs :**
```
[23:50:37 INFO]: 4lex_2 was slain by Pyro Zombie
[23:50:37 INFO]: The player 4lex_2 has successfully been saved
[23:50:40 ERROR]: Exception caught during firing event: Cannot invoke "com.infamous.dungeons_gear.capabilities.combo.ICombo.getSouls()" because the return value of "com.infamous.dungeons_gear.utilties.CapabilityHelper.getComboCapability(net.minecraft.entity.Entity)" is null
        Index: 17
        Listeners:
                0: HIGHEST
                1: ASM: net.minecraftforge.common.ForgeInternalHandler@dbd0363 onEntityJoinWorld(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
                2: HIGH
                3: ASM: tschipp.carryon.common.event.ItemEvents@53b986c3 onItemDropped(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
                4: ASM: tschipp.carryon.common.event.ItemEntityEvents@51caa2e0 onItemDropped(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
                5: NORMAL
                6: ASM: class net.mehvahdjukaar.supplementaries.events.ServerEvents onEntityJoin(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
                7: ASM: class net.mehvahdjukaar.dummmmmmy.common.Events onEntityJoinWorld(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
                8: net.minecraftforge.eventbus.EventBus$$Lambda$2921/0x0000000801571e88@3e9b21e6
                9: ASM: doggytalents.common.event.EventHandler@7c44ebcf onEntitySpawn(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
                10: ASM: class com.builtbroken.ai.improvements.modifier.ModifierSystem onEntityJoinWorld(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
                11: ASM: class com.lilypuree.connectiblechains.events.EventHandler onEntitySpawn(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
                12: ASM: class com.blackgear.cavesandcliffs.common.events.EntityEvents onEntityJoinWorld(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
                13: net.minecraftforge.eventbus.EventBus$$Lambda$2921/0x0000000801571e88@55360d29
                14: net.minecraftforge.eventbus.EventBus$$Lambda$2921/0x0000000801571e88@1d8d7da
                15: ASM: class com.infamous.dungeons_gear.items.artifacts.ArtifactEvents reAddSummonableGoals(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
                16: ASM: class com.infamous.dungeons_gear.items.artifacts.ArtifactEvents onArrowJoinWorld(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
                17: ASM: class com.infamous.dungeons_gear.GlobalEvents onArrowJoinWorld(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
                18: ASM: com.bobmowzie.mowziesmobs.server.ServerEventHandler@9458598 onJoinWorld(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
                19: ASM: class mod.chiselsandbits.events.PlayerJoinedWorldEventHandler onPlayerJoinedWorld(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
                20: ASM: com.oitsjustjose.vtweaks.common.event.mobtweaks.PetArmory@136a1432 registerEvent(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
                21: ASM: com.oitsjustjose.vtweaks.common.event.mobtweaks.ChallengerParticles@3fc60d5 registerEvent(Lnet/minecraftforge/event/entity/EntityEvent;)V
java.lang.NullPointerException: Cannot invoke "com.infamous.dungeons_gear.capabilities.combo.ICombo.getSouls()" because the return value of "com.infamous.dungeons_gear.utilties.CapabilityHelper.getComboCapability(net.minecraft.entity.Entity)" is null
        at com.infamous.dungeons_gear.GlobalEvents.onArrowJoinWorld(GlobalEvents.java:79)
        at net.minecraftforge.eventbus.ASMEventHandler_473_GlobalEvents_onArrowJoinWorld_EntityJoinWorldEvent.invoke(.dynamic)
        at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
        at net.minecraft.world.server.ServerWorld.func_217448_f(ServerWorld.java:1041)
        at net.minecraft.world.server.ServerWorld.func_217433_d(ServerWorld.java:1037)
        at net.minecraft.server.management.PlayerList.respawn(PlayerList.java:639)
        at net.minecraft.server.management.PlayerList.func_232644_a_(PlayerList.java:535)
        at net.minecraft.network.play.ServerPlayNetHandler.func_147342_a(ServerPlayNetHandler.java:2054)
        at net.minecraft.network.play.client.CClientStatusPacket.func_148833_a(SourceFile:30)
        at net.minecraft.network.play.client.CClientStatusPacket.func_148833_a(SourceFile:8)
        at net.minecraft.network.PacketThreadUtil.lambda$ensureRunningOnSameThread$0(PacketThreadUtil.java:26)
        at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18)
        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(ThreadTaskExecutor.java:153)
        at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23)
        at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:942)
        at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:176)
        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(ThreadTaskExecutor.java:126)
        at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:925)
        at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:919)
        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(ThreadTaskExecutor.java:136)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:998)
        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:821)
        at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:269)
        at java.base/java.lang.Thread.run(Thread.java:833)

[23:50:40 FATAL]: Error executing task on Server
[23:50:40 WARN]: java.lang.NullPointerException: Cannot invoke "com.infamous.dungeons_gear.capabilities.combo.ICombo.getSouls()" because the return value of "com.infamous.dungeons_gear.utilties.CapabilityHelper.getComboCapability(net.minecraft.entity.Entity)" is null
[23:50:40 WARN]:        at com.infamous.dungeons_gear.GlobalEvents.onArrowJoinWorld(GlobalEvents.java:79)
[23:50:40 WARN]:        at net.minecraftforge.eventbus.ASMEventHandler_473_GlobalEvents_onArrowJoinWorld_EntityJoinWorldEvent.invoke(.dynamic)
[23:50:40 WARN]:        at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
[23:50:40 WARN]:        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
[23:50:40 WARN]:        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
[23:50:40 WARN]:        at net.minecraft.world.server.ServerWorld.func_217448_f(ServerWorld.java:1041)
[23:50:40 WARN]:        at net.minecraft.world.server.ServerWorld.func_217433_d(ServerWorld.java:1037)
[23:50:40 WARN]:        at net.minecraft.server.management.PlayerList.respawn(PlayerList.java:639)
[23:50:40 WARN]:        at net.minecraft.server.management.PlayerList.func_232644_a_(PlayerList.java:535)
[23:50:40 WARN]:        at net.minecraft.network.play.ServerPlayNetHandler.func_147342_a(ServerPlayNetHandler.java:2054)
[23:50:40 WARN]:        at net.minecraft.network.play.client.CClientStatusPacket.func_148833_a(SourceFile:30)
[23:50:40 WARN]:        at net.minecraft.network.play.client.CClientStatusPacket.func_148833_a(SourceFile:8)
[23:50:40 WARN]:        at net.minecraft.network.PacketThreadUtil.lambda$ensureRunningOnSameThread$0(PacketThreadUtil.java:26)
[23:50:40 WARN]:        at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18)
[23:50:40 WARN]:        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(ThreadTaskExecutor.java:153)
[23:50:40 WARN]:        at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23)
[23:50:40 WARN]:        at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:942)
[23:50:40 WARN]:        at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:176)
[23:50:40 WARN]:        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(ThreadTaskExecutor.java:126)
[23:50:40 WARN]:        at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:925)
[23:50:40 WARN]:        at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:919)
[23:50:40 WARN]:        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(ThreadTaskExecutor.java:136)
[23:50:40 WARN]:        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:998)
[23:50:40 WARN]:        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:821)
[23:50:40 WARN]:        at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:269)
[23:50:40 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[23:50:40 ERROR]: Exception caught during firing event: Cannot invoke "melonslise.locks.common.capability.ISelection.get()" because "select" is null
        Index: 4
        Listeners:
                0: NORMAL
                1: ASM: class net.blay09.mods.forgivingvoid.ForgivingVoid onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                2: net.minecraftforge.eventbus.EventBus$$Lambda$2921/0x0000000801571e88@760dc04f
                3: ASM: class net.mehvahdjukaar.supplementaries.events.ServerEvents onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                4: ASM: class melonslise.locks.common.event.LocksForgeEvents onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                5: ASM: alpvax.mc.goprone.GoProne@31c6803f onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                6: ASM: class com.infamous.dungeons_gear.items.artifacts.ArtifactEvents checkSummonedMobIsDead(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                7: ASM: class com.infamous.dungeons_gear.items.armor.ArmorEvents respawnPetBat(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                8: ASM: class com.infamous.dungeons_gear.items.armor.ArmorEvents onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                9: ASM: class com.infamous.dungeons_gear.enchantments.melee_ranged.PoisonCloudEnchantment onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                10: ASM: class com.infamous.dungeons_gear.enchantments.melee.EchoEnchantment onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                11: ASM: class com.infamous.dungeons_gear.enchantments.armor.SnowballEnchantment onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                12: ASM: class com.infamous.dungeons_gear.enchantments.armor.RecklessEnchantment onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                13: ASM: class com.infamous.dungeons_gear.enchantments.armor.LuckyExplorerEnchantment onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                14: ASM: com.bobmowzie.mowziesmobs.server.ServerEventHandler@9458598 onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                15: ASM: class com.infamous.dungeons_gear.enchantments.armor.GravityPulseEnchantment onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                16: ASM: class com.infamous.dungeons_gear.enchantments.armor.FrenziedEnchantment onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                17: ASM: class com.infamous.dungeons_gear.enchantments.armor.ExplorerEnchantment onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                18: ASM: class com.infamous.dungeons_gear.enchantments.armor.CowardiceEnchantment onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                19: ASM: class com.infamous.dungeons_gear.enchantments.armor.ChillingEnchantment onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                20: ASM: class com.infamous.dungeons_gear.enchantments.armor.BurningEnchantment onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                21: ASM: com.shynieke.statues.handlers.SpecialHandler@1249ec77 playerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                22: ASM: class com.teammetallurgy.aquaculture.item.neptunium.NeptuniumArmor onLivingTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                23: ASM: class nefdecomod.procedures.Wardrobe6UpdateTickProcedure$GlobalTrigger onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                24: ASM: class nefdecomod.procedures.Wardrobe5UpdateTickProcedure$GlobalTrigger onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                25: ASM: class nefdecomod.procedures.Wardrobe4UpdateTickProcedure$GlobalTrigger onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                26: ASM: class nefdecomod.procedures.Wardrobe3UpdateTickProcedure$GlobalTrigger onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                27: ASM: class nefdecomod.procedures.Wardrobe2UpdateTickProcedure$GlobalTrigger onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                28: ASM: class nefdecomod.procedures.Wardrobe1UpdateTickProcedure$GlobalTrigger onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
java.lang.NullPointerException: Cannot invoke "melonslise.locks.common.capability.ISelection.get()" because "select" is null
        at melonslise.locks.common.event.LocksForgeEvents.onPlayerTick(LocksForgeEvents.java:214)
        at net.minecraftforge.eventbus.ASMEventHandler_267_LocksForgeEvents_onPlayerTick_PlayerTickEvent.invoke(.dynamic)
        at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
        at net.minecraftforge.fml.hooks.BasicEventHooks.onPlayerPreTick(BasicEventHooks.java:97)
        at net.minecraft.entity.player.PlayerEntity.func_70071_h_(PlayerEntity.java:224)
        at net.minecraft.entity.player.ServerPlayerEntity.func_71127_g(ServerPlayerEntity.java:526)
        at net.minecraft.network.play.ServerPlayNetHandler.func_73660_a(ServerPlayNetHandler.java:297)
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:242)
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:142)
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1116)
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:1006)
        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:821)
        at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:269)
        at java.base/java.lang.Thread.run(Thread.java:833)

[23:50:40 FATAL]: Preparing crash report with UUID 9f447112-d17f-4e1f-8213-1922d6016ac6
[23:50:40 WARN]: Failed to handle packet for /66.81.185.113:10209
net.minecraft.crash.ReportedException: Ticking player
        at net.minecraft.entity.player.ServerPlayerEntity.func_71127_g(ServerPlayerEntity.java:605) ~[?:?]
        at net.minecraft.network.play.ServerPlayNetHandler.func_73660_a(ServerPlayNetHandler.java:297) ~[?:?]
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:242) ~[?:?]
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:142) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1116) ~[?:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:1006) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:821) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:269) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "melonslise.locks.common.capability.ISelection.get()" because "select" is null
        at melonslise.locks.common.event.LocksForgeEvents.onPlayerTick(LocksForgeEvents.java:214) ~[locks:3.0.3]
        at net.minecraftforge.eventbus.ASMEventHandler_267_LocksForgeEvents_onPlayerTick_PlayerTickEvent.invoke(.dynamic) ~[?:?]
        at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?]
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?]
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?]
        at net.minecraftforge.fml.hooks.BasicEventHooks.onPlayerPreTick(BasicEventHooks.java:97) ~[forge:?]
        at net.minecraft.entity.player.PlayerEntity.func_70071_h_(PlayerEntity.java:224) ~[?:?]
        at net.minecraft.entity.player.ServerPlayerEntity.func_71127_g(ServerPlayerEntity.java:526) ~[?:?]
        ... 9 more
[23:50:40 INFO]: 4lex_2 lost connection: Internal server error
[23:50:40 ERROR]: Exception caught during firing event: Cannot invoke "melonslise.locks.common.capability.ISelection.get()" because "select" is null
        Index: 4
        Listeners:
                0: NORMAL
                1: ASM: class net.blay09.mods.forgivingvoid.ForgivingVoid onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                2: net.minecraftforge.eventbus.EventBus$$Lambda$2921/0x0000000801571e88@760dc04f
                3: ASM: class net.mehvahdjukaar.supplementaries.events.ServerEvents onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                4: ASM: class melonslise.locks.common.event.LocksForgeEvents onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                5: ASM: alpvax.mc.goprone.GoProne@31c6803f onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                6: ASM: class com.infamous.dungeons_gear.items.artifacts.ArtifactEvents checkSummonedMobIsDead(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                7: ASM: class com.infamous.dungeons_gear.items.armor.ArmorEvents respawnPetBat(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                8: ASM: class com.infamous.dungeons_gear.items.armor.ArmorEvents onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                9: ASM: class com.infamous.dungeons_gear.enchantments.melee_ranged.PoisonCloudEnchantment onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                10: ASM: class com.infamous.dungeons_gear.enchantments.melee.EchoEnchantment onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                11: ASM: class com.infamous.dungeons_gear.enchantments.armor.SnowballEnchantment onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                12: ASM: class com.infamous.dungeons_gear.enchantments.armor.RecklessEnchantment onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                13: ASM: class com.infamous.dungeons_gear.enchantments.armor.LuckyExplorerEnchantment onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                14: ASM: com.bobmowzie.mowziesmobs.server.ServerEventHandler@9458598 onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                15: ASM: class com.infamous.dungeons_gear.enchantments.armor.GravityPulseEnchantment onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                16: ASM: class com.infamous.dungeons_gear.enchantments.armor.FrenziedEnchantment onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                17: ASM: class com.infamous.dungeons_gear.enchantments.armor.ExplorerEnchantment onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                18: ASM: class com.infamous.dungeons_gear.enchantments.armor.CowardiceEnchantment onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                19: ASM: class com.infamous.dungeons_gear.enchantments.armor.ChillingEnchantment onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                20: ASM: class com.infamous.dungeons_gear.enchantments.armor.BurningEnchantment onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                21: ASM: com.shynieke.statues.handlers.SpecialHandler@1249ec77 playerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                22: ASM: class com.teammetallurgy.aquaculture.item.neptunium.NeptuniumArmor onLivingTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                23: ASM: class nefdecomod.procedures.Wardrobe6UpdateTickProcedure$GlobalTrigger onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                24: ASM: class nefdecomod.procedures.Wardrobe5UpdateTickProcedure$GlobalTrigger onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                25: ASM: class nefdecomod.procedures.Wardrobe4UpdateTickProcedure$GlobalTrigger onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                26: ASM: class nefdecomod.procedures.Wardrobe3UpdateTickProcedure$GlobalTrigger onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                27: ASM: class nefdecomod.procedures.Wardrobe2UpdateTickProcedure$GlobalTrigger onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                28: ASM: class nefdecomod.procedures.Wardrobe1UpdateTickProcedure$GlobalTrigger onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
java.lang.NullPointerException: Cannot invoke "melonslise.locks.common.capability.ISelection.get()" because "select" is null
        at melonslise.locks.common.event.LocksForgeEvents.onPlayerTick(LocksForgeEvents.java:214)
        at net.minecraftforge.eventbus.ASMEventHandler_267_LocksForgeEvents_onPlayerTick_PlayerTickEvent.invoke(.dynamic)
        at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
        at net.minecraftforge.fml.hooks.BasicEventHooks.onPlayerPreTick(BasicEventHooks.java:97)
        at net.minecraft.entity.player.PlayerEntity.func_70071_h_(PlayerEntity.java:224)
        at net.minecraft.entity.player.ServerPlayerEntity.func_71127_g(ServerPlayerEntity.java:526)
        at net.minecraft.server.management.PlayerList.func_72367_e(PlayerList.java:397)
        at net.minecraft.server.management.PlayerList.disconnect(PlayerList.java:380)
        at net.minecraft.network.play.ServerPlayNetHandler.func_147231_a(ServerPlayNetHandler.java:1535)
        at net.minecraft.network.NetworkManager.func_179293_l(NetworkManager.java:385)
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:161)
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1116)
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:1006)
        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:821)
        at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:269)
        at java.base/java.lang.Thread.run(Thread.java:833)

[23:50:40 FATAL]: Preparing crash report with UUID e8a7ca94-4e4a-43d3-9982-00191007cbfd
[23:50:40 ERROR]: Encountered an unexpected exception
[23:50:40 ERROR]:       Cause of unexpected exception was
[23:50:40 ERROR]: This crash report has been saved to: /home/container/./crash-reports/crash-2022-01-05_23.50.40-server.txt
[23:50:40 INFO]: Stopping server
[23:50:40 INFO]: [eGlow] Disabling eGlow v3.1.2
[23:50:40 INFO]: [PlaceholderAPI] Unregistered placeholder expansion: eglow
[23:50:40 INFO]: [TAB-Additions] Disabling TAB-Additions v1.6.1
[23:50:40 INFO]: [Iridescent] Disabling Iridescent v1.2.2
[23:50:40 INFO]: [SkinsRestorer] Disabling SkinsRestorer v14.1.10
[23:50:40 INFO]: [TAB] Disabling TAB v3.0.0
[23:50:40 INFO]: [TAB] Disabled in 5ms
[23:50:40 INFO]: [ProtocolLib] Disabling ProtocolLib v4.5.1
[23:50:40 INFO]: [PlaceholderAPI] Disabling PlaceholderAPI v2.10.10
[23:50:40 INFO]: [ConsoleSpamFix] Disabling ConsoleSpamFix v1.8.6
[23:50:40 INFO]: [ConsoleSpamFix] Messages hidden since the server started: 3
[23:50:40 INFO]: [ConsoleSpamFix] ConsoleSpamFix is disabled!
[23:50:40 INFO]: [Essentials] Disabling Essentials v2.19.1-dev+48-c45c741
[23:50:40 ERROR]: There's a good chance you're reloading your server right now. If that's the case, why do you hate yourself? Expect no support from the EssentialsX team when using /reload.
[23:50:40 INFO]: [LuckPerms] Disabling LuckPerms v5.3.1
[23:50:40 INFO]: [LuckPerms] Starting shutdown process...
[23:50:41 INFO]: [LuckPerms] Closing storage...
[23:50:41 INFO]: [LuckPerms] Goodbye!
[23:50:41 INFO]: Saving players
[23:50:41 INFO]: Saving worlds
[23:50:41 INFO]: Saving chunks for level 'ServerLevel[ServerWorld]'/minecraft:overworld
[23:50:41 INFO]: Updating offline player location 4lex_2 x:343.5 y: 64.0999984741211 z: -79.5
[23:51:12 INFO]: ThreadedAnvilChunkStorage (ServerWorld): All chunks are saved
[23:51:12 INFO]: Saving chunks for level 'ServerLevel[DIM-1]'/minecraft:the_nether
[23:51:12 INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[23:51:12 INFO]: Saving chunks for level 'ServerLevel[DIM1]'/minecraft:the_end
[23:51:12 INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[23:51:13 ERROR]: Cound not schedule mailbox
java.util.concurrent.RejectedExecutionException: Task IOWorker-chunk 2 false rejected from java.util.concurrent.ThreadPoolExecutor@89c7f9c[Shutting down, pool size = 1, active threads = 1, queued tasks = 0, completed tasks = 291305]
        at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2065) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:833) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1365) ~[?:?]
        at net.minecraft.util.concurrent.DelegatedTaskExecutor.func_213143_f(DelegatedTaskExecutor.java:122) [?:?]
        at net.minecraft.util.concurrent.DelegatedTaskExecutor.run(DelegatedTaskExecutor.java:106) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
```

**Steps to Reproduce :**
 1. Dead
 2. Respawn
 >1 && 2 = Error

**Comment by Mgazul** [comment]
Maybe build#910 is useful

**Comment by joaoespanhol** [comment]
> 

you lose all permissions when you die, that's why it happens.

I have exact problem with.

Install Luckyperms.
Plugin system.

dead server

write: /list

the server has no player online


Version 904 no have this problem

**Comment by lxgnzlz05** [comment]
tmorrow i go to test the lastest build

**Comment by lxgnzlz05** [comment]
and the permissions

**Comment by lxgnzlz05** [comment]
> Maybe build#910 is useful

https://haste.mohistmc.com/otapowevot
the same

**Comment by Souperhero** [comment]
same with my pack, specifically with Mine And slash (age of Exile) -- mmorpg)

https://pastebin.com/fiqUhNcS

**Comment by BlockyBlockling** [comment]
Same here with LuckPerms installed.
