### ISSUE TITLE
[1.16.5] Failed to save chunk

### ISSUE THREAD

**Issue by lxgnzlz05** [Teneted/Tenet#1970]
**Mohist Version :** 905

**Logs :** 
```
[02:45:24 INFO]: 4lex_2[/66.81.185.113:10220] logged in with entity id 433 at (467.205, 80.16, -220.817)
[02:48:17 ERROR]: Failed to save chunk [44, -13]
java.util.concurrent.CompletionException: java.lang.ClassCastException: class net.minecraft.tileentity.ChestTileEntity cannot be cast to class net.minecraft.entity.Entity (net.minecraft.tileentity.ChestTileEntity and net.minecraft.entity.Entity are in unnamed module of loader cpw.mods.modlauncher.TransformingClassLoader @2e7bf7b7)
        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
        at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:722) ~[?:?]
        at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
        at net.minecraft.world.server.ChunkManager.func_223155_b(ChunkManager.java:416) ~[?:?]
        at net.minecraft.world.server.ChunkManager.func_219204_a(ChunkManager.java:394) ~[?:?]
        at net.minecraft.world.server.ServerChunkProvider.func_217207_a(ServerChunkProvider.java:388) ~[?:?]
        at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:489) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1093) ~[?:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:1006) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:821) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:269) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.ClassCastException: class net.minecraft.tileentity.ChestTileEntity cannot be cast to class net.minecraft.entity.Entity (net.minecraft.tileentity.ChestTileEntity and net.minecraft.entity.Entity are in unnamed module of loader cpw.mods.modlauncher.TransformingClassLoader @2e7bf7b7)
        at net.minecraft.world.server.ServerWorld.redirect$zeh000$onEntityRemoved(ServerWorld.java:2431) ~[?:?]
        at net.minecraft.world.server.ServerWorld.func_217466_a(ServerWorld.java:1139) ~[?:?]
        at net.minecraft.world.server.ChunkManager.func_219185_a(ChunkManager.java:437) ~[?:?]
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
        ... 11 more
```

**Steps to Reproduce :**
 1. Luck wile you are exploring/generating chunks
 
(edit) 2.I have noticed that it happens when previously unopened chests are generated like in mineshafts, villagers...

**Mods & Plugins :** 
> Mods: [99/Server](https://haste.mohistmc.com/civukilamo.json) [105/Client](https://haste.mohistmc.com/agakakebor.json)
> Plugins: [10](https://haste.mohistmc.com/udajiruhoj.json)

**Comment by lxgnzlz05** [comment]
also with another mod, but similar https://haste.mohistmc.com/jisirucoje.css

**Comment by lxgnzlz05** [comment]
The origin: RoadRunner mod
removed = Fixed
