### ISSUE TITLE
[1.16.5] WorldEdit use inventory failure

### ISSUE THREAD

**Issue by HYDRA66666** [Teneted/Tenet#1979]
**Minecraft Version :** 1.16.5

**Mohist Version :** 910

**Operating System :** win11

**Concerned mod / plugin** : worldedit

**Logs :** [latest.log](https://github.com/MohistMC/Mohist/files/7843091/latest.log)
[01:45:06] [Server thread/ERROR] [com.sk89q.worldedit.extension.platform.PlatformCommandManager/]: An unexpected error while handling a WorldEdit command
java.lang.IllegalArgumentException: Could not parse data: timeless_and_classic:box_308block
	at org.bukkit.craftbukkit.v1_16_R3.block.data.CraftBlockData.newData(CraftBlockData.java:522) ~[forge:?]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.createBlockData(CraftServer.java:1987) ~[forge:7e29f765-296df566-9fb885e8]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.createBlockData(CraftServer.java:1980) ~[forge:7e29f765-296df566-9fb885e8]
	at org.bukkit.Bukkit.createBlockData(Bukkit.java:1480) ~[forge:?]
	at com.sk89q.worldedit.bukkit.BukkitAdapter.lambda$adapt$7(BukkitAdapter.java:491) ~[?:?]
	at com.sk89q.worldedit.bukkit.fastutil.ints.Int2ObjectOpenHashMap.computeIfAbsent(Int2ObjectOpenHashMap.java:499) ~[?:?]
	at com.sk89q.worldedit.bukkit.BukkitAdapter.adapt(BukkitAdapter.java:491) ~[?:?]
	at net.coreprotect.worldedit.WorldEditLogger.postProcess(WorldEditLogger.java:55) ~[?:?]
	at net.coreprotect.worldedit.CoreProtectLogger.setBlock(CoreProtectLogger.java:56) ~[?:?]
	at com.sk89q.worldedit.function.operation.SetBlockMap.resume(SetBlockMap.java:45) ~[?:?]
	at com.sk89q.worldedit.extent.reorder.MultiStageReorder$1.resume(MultiStageReorder.java:275) ~[?:?]
	at com.sk89q.worldedit.function.operation.OperationQueue.resume(OperationQueue.java:92) ~[?:?]
	at com.sk89q.worldedit.function.operation.OperationQueue.resume(OperationQueue.java:92) ~[?:?]
	at com.sk89q.worldedit.function.operation.Operations.completeBlindly(Operations.java:74) ~[?:?]
	at com.sk89q.worldedit.EditSession.internalFlushSession(EditSession.java:938) ~[?:?]
	at com.sk89q.worldedit.EditSession.undo(EditSession.java:832) ~[?:?]
	at com.sk89q.worldedit.LocalSession.undo(LocalSession.java:260) ~[?:?]
	at com.sk89q.worldedit.command.HistoryCommands.undo(HistoryCommands.java:81) ~[?:?]
	at com.sk89q.worldedit.command.HistoryCommandsRegistration.cmd$undo(HistoryCommandsRegistration.java:133) ~[?:?]
	at org.enginehub.piston.CommandManager.execute(CommandManager.java:157) ~[?:?]
	at com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommand(PlatformCommandManager.java:497) ~[?:?]
	at com.sk89q.worldedit.util.eventbus.MethodHandleEventHandler.dispatch(MethodHandleEventHandler.java:51) ~[?:?]
	at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:73) ~[?:?]
	at com.sk89q.worldedit.util.eventbus.EventBus.dispatch(EventBus.java:193) ~[?:?]
	at com.sk89q.worldedit.util.eventbus.EventBus.post(EventBus.java:181) ~[?:?]
	at com.sk89q.worldedit.bukkit.WorldEditPlugin.onCommand(WorldEditPlugin.java:383) ~[?:?]
	at com.sk89q.bukkit.util.DynamicPluginCommand.execute(DynamicPluginCommand.java:55) ~[?:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:157) ~[forge:?]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:769) ~[forge:7e29f765-296df566-9fb885e8]
	at net.minecraft.network.play.ServerPlayNetHandler.func_147361_d(ServerPlayNetHandler.java:1832) ~[?:?]
	at net.minecraft.network.play.ServerPlayNetHandler.func_147354_a(ServerPlayNetHandler.java:1667) ~[?:?]
	at net.minecraft.network.play.client.CChatMessagePacket.func_148833_a(CChatMessagePacket.java:39) ~[?:?]
	at net.minecraft.network.play.client.CChatMessagePacket.func_148833_a(CChatMessagePacket.java:10) ~[?:?]
	at net.minecraft.network.PacketThreadUtil.lambda$ensureRunningOnSameThread$0(PacketThreadUtil.java:26) ~[?:?]
	at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(ThreadTaskExecutor.java:153) ~[?:?]
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:942) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:176) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(ThreadTaskExecutor.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:925) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:919) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(ThreadTaskExecutor.java:136) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:905) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:825) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:269) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
	Suppressed: java.lang.IllegalArgumentException: Could not parse data: timeless_and_classic:box_308block
		at org.bukkit.craftbukkit.v1_16_R3.block.data.CraftBlockData.newData(CraftBlockData.java:522) ~[forge:?]
		at org.bukkit.craftbukkit.v1_16_R3.CraftServer.createBlockData(CraftServer.java:1987) ~[forge:7e29f765-296df566-9fb885e8]
		at org.bukkit.craftbukkit.v1_16_R3.CraftServer.createBlockData(CraftServer.java:1980) ~[forge:7e29f765-296df566-9fb885e8]
		at org.bukkit.Bukkit.createBlockData(Bukkit.java:1480) ~[forge:?]
		at com.sk89q.worldedit.bukkit.BukkitAdapter.lambda$adapt$7(BukkitAdapter.java:491) ~[?:?]
		at com.sk89q.worldedit.bukkit.fastutil.ints.Int2ObjectOpenHashMap.computeIfAbsent(Int2ObjectOpenHashMap.java:499) ~[?:?]
		at com.sk89q.worldedit.bukkit.BukkitAdapter.adapt(BukkitAdapter.java:491) ~[?:?]
		at net.coreprotect.worldedit.WorldEditLogger.postProcess(WorldEditLogger.java:55) ~[?:?]
		at net.coreprotect.worldedit.CoreProtectLogger.setBlock(CoreProtectLogger.java:56) ~[?:?]
		at com.sk89q.worldedit.function.operation.SetBlockMap.resume(SetBlockMap.java:45) ~[?:?]
		at com.sk89q.worldedit.extent.reorder.MultiStageReorder$1.resume(MultiStageReorder.java:275) ~[?:?]
		at com.sk89q.worldedit.function.operation.OperationQueue.resume(OperationQueue.java:92) ~[?:?]
		at com.sk89q.worldedit.function.operation.OperationQueue.resume(OperationQueue.java:92) ~[?:?]
		at com.sk89q.worldedit.function.operation.Operations.completeBlindly(Operations.java:74) ~[?:?]
		at com.sk89q.worldedit.EditSession.internalFlushSession(EditSession.java:938) ~[?:?]
		at com.sk89q.worldedit.EditSession.close(EditSession.java:882) ~[?:?]
		at com.sk89q.worldedit.LocalSession.undo(LocalSession.java:255) ~[?:?]
		at com.sk89q.worldedit.command.HistoryCommands.undo(HistoryCommands.java:81) ~[?:?]
		at com.sk89q.worldedit.command.HistoryCommandsRegistration.cmd$undo(HistoryCommandsRegistration.java:133) ~[?:?]
		at org.enginehub.piston.CommandManager.execute(CommandManager.java:157) ~[?:?]
		at com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommand(PlatformCommandManager.java:497) ~[?:?]
		at com.sk89q.worldedit.util.eventbus.MethodHandleEventHandler.dispatch(MethodHandleEventHandler.java:51) ~[?:?]
		at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:73) ~[?:?]
		at com.sk89q.worldedit.util.eventbus.EventBus.dispatch(EventBus.java:193) ~[?:?]
		at com.sk89q.worldedit.util.eventbus.EventBus.post(EventBus.java:181) ~[?:?]
		at com.sk89q.worldedit.bukkit.WorldEditPlugin.onCommand(WorldEditPlugin.java:383) ~[?:?]
		at com.sk89q.bukkit.util.DynamicPluginCommand.execute(DynamicPluginCommand.java:55) ~[?:?]
		at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:157) ~[forge:?]
		at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:769) ~[forge:7e29f765-296df566-9fb885e8]
		at net.minecraft.network.play.ServerPlayNetHandler.func_147361_d(ServerPlayNetHandler.java:1832) ~[?:?]
		at net.minecraft.network.play.ServerPlayNetHandler.func_147354_a(ServerPlayNetHandler.java:1667) ~[?:?]
		at net.minecraft.network.play.client.CChatMessagePacket.func_148833_a(CChatMessagePacket.java:39) ~[?:?]
		at net.minecraft.network.play.client.CChatMessagePacket.func_148833_a(CChatMessagePacket.java:10) ~[?:?]
		at net.minecraft.network.PacketThreadUtil.lambda$ensureRunningOnSameThread$0(PacketThreadUtil.java:26) ~[?:?]
		at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?]
		at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(ThreadTaskExecutor.java:153) ~[?:?]
		at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?]
		at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:942) ~[?:?]
		at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:176) ~[?:?]
		at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(ThreadTaskExecutor.java:126) ~[?:?]
		at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:925) ~[?:?]
		at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:919) ~[?:?]
		at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(ThreadTaskExecutor.java:136) ~[?:?]
		at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:905) ~[?:?]
		at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:825) ~[?:?]
		at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:269) ~[?:?]
		at java.lang.Thread.run(Thread.java:833) [?:?]
	Caused by: com.mojang.brigadier.exceptions.CommandSyntaxException: Unknown block type 'timeless_and_classic:box_308block' at position 0: <--[HERE]
Caused by: com.mojang.brigadier.exceptions.CommandSyntaxException: Unknown block type 'timeless_and_classic:box_308block' at position 0: <--[HERE]

**Steps to Reproduce :**
 1. install worldedit and start the server
 2. edit the WE's config as 
use-inventory:
    enable: true
    allow-override: false
    creative-mode-overrides: false
 3.excute a command as //set to set some blocks

**Description of issue :**only one or two of all those blocks can be placed correctly, and the console sent the message as above .I have tried WE 7.2.3&7.2.8,mohist 909&910,and can be sure that WE works fine with spgiot

**Comment by HYDRA66666** [comment]
（怕我英文不好所以用中文又写了一遍）
Minecraft Version : 1.16.5

Mohist Version : 910

Operating System : win11

Concerned mod / plugin : worldedit

Logs : 上面有链接，下面节选自日志
[01:45:06] [Server thread/ERROR] [com.sk89q.worldedit.extension.platform.PlatformCommandManager/]: An unexpected error while handling a WorldEdit command
java.lang.IllegalArgumentException: Could not parse data: timeless_and_classic:box_308block
at org.bukkit.craftbukkit.v1_16_R3.block.data.CraftBlockData.newData(CraftBlockData.java:522) ~[forge:?]
at org.bukkit.craftbukkit.v1_16_R3.CraftServer.createBlockData(CraftServer.java:1987) ~[forge:7e29f765-296df566-9fb885e8]
at org.bukkit.craftbukkit.v1_16_R3.CraftServer.createBlockData(CraftServer.java:1980) ~[forge:7e29f765-296df566-9fb885e8]
at org.bukkit.Bukkit.createBlockData(Bukkit.java:1480) ~[forge:?]
at com.sk89q.worldedit.bukkit.BukkitAdapter.lambda$adapt$7(BukkitAdapter.java:491) ~[?:?]
at com.sk89q.worldedit.bukkit.fastutil.ints.Int2ObjectOpenHashMap.computeIfAbsent(Int2ObjectOpenHashMap.java:499) ~[?:?]
at com.sk89q.worldedit.bukkit.BukkitAdapter.adapt(BukkitAdapter.java:491) ~[?:?]
at net.coreprotect.worldedit.WorldEditLogger.postProcess(WorldEditLogger.java:55) ~[?:?]
at net.coreprotect.worldedit.CoreProtectLogger.setBlock(CoreProtectLogger.java:56) ~[?:?]
at com.sk89q.worldedit.function.operation.SetBlockMap.resume(SetBlockMap.java:45) ~[?:?]
at com.sk89q.worldedit.extent.reorder.MultiStageReorder$1.resume(MultiStageReorder.java:275) ~[?:?]
at com.sk89q.worldedit.function.operation.OperationQueue.resume(OperationQueue.java:92) ~[?:?]
at com.sk89q.worldedit.function.operation.OperationQueue.resume(OperationQueue.java:92) ~[?:?]
at com.sk89q.worldedit.function.operation.Operations.completeBlindly(Operations.java:74) ~[?:?]
at com.sk89q.worldedit.EditSession.internalFlushSession(EditSession.java:938) ~[?:?]
at com.sk89q.worldedit.EditSession.undo(EditSession.java:832) ~[?:?]
at com.sk89q.worldedit.LocalSession.undo(LocalSession.java:260) ~[?:?]
at com.sk89q.worldedit.command.HistoryCommands.undo(HistoryCommands.java:81) ~[?:?]
at com.sk89q.worldedit.command.HistoryCommandsRegistration.cmd$undo(HistoryCommandsRegistration.java:133) ~[?:?]
at org.enginehub.piston.CommandManager.execute(CommandManager.java:157) ~[?:?]
at com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommand(PlatformCommandManager.java:497) ~[?:?]
at com.sk89q.worldedit.util.eventbus.MethodHandleEventHandler.dispatch(MethodHandleEventHandler.java:51) ~[?:?]
at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:73) ~[?:?]
at com.sk89q.worldedit.util.eventbus.EventBus.dispatch(EventBus.java:193) ~[?:?]
at com.sk89q.worldedit.util.eventbus.EventBus.post(EventBus.java:181) ~[?:?]
at com.sk89q.worldedit.bukkit.WorldEditPlugin.onCommand(WorldEditPlugin.java:383) ~[?:?]
at com.sk89q.bukkit.util.DynamicPluginCommand.execute(DynamicPluginCommand.java:55) ~[?:?]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:157) ~[forge:?]
at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:769) ~[forge:7e29f765-296df566-9fb885e8]
at net.minecraft.network.play.ServerPlayNetHandler.func_147361_d(ServerPlayNetHandler.java:1832) ~[?:?]
at net.minecraft.network.play.ServerPlayNetHandler.func_147354_a(ServerPlayNetHandler.java:1667) ~[?:?]
at net.minecraft.network.play.client.CChatMessagePacket.func_148833_a(CChatMessagePacket.java:39) ~[?:?]
at net.minecraft.network.play.client.CChatMessagePacket.func_148833_a(CChatMessagePacket.java:10) ~[?:?]
at net.minecraft.network.PacketThreadUtil.lambda$ensureRunningOnSameThread$0(PacketThreadUtil.java:26) ~[?:?]
at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?]
at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(ThreadTaskExecutor.java:153) ~[?:?]
at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?]
at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:942) ~[?:?]
at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:176) ~[?:?]
at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(ThreadTaskExecutor.java:126) ~[?:?]
at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:925) ~[?:?]
at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:919) ~[?:?]
at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(ThreadTaskExecutor.java:136) ~[?:?]
at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:905) ~[?:?]
at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:825) ~[?:?]
at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:269) ~[?:?]
at java.lang.Thread.run(Thread.java:833) [?:?]
Suppressed: java.lang.IllegalArgumentException: Could not parse data: timeless_and_classic:box_308block
at org.bukkit.craftbukkit.v1_16_R3.block.data.CraftBlockData.newData(CraftBlockData.java:522) ~[forge:?]
at org.bukkit.craftbukkit.v1_16_R3.CraftServer.createBlockData(CraftServer.java:1987) ~[forge:7e29f765-296df566-9fb885e8]
at org.bukkit.craftbukkit.v1_16_R3.CraftServer.createBlockData(CraftServer.java:1980) ~[forge:7e29f765-296df566-9fb885e8]
at org.bukkit.Bukkit.createBlockData(Bukkit.java:1480) ~[forge:?]
at com.sk89q.worldedit.bukkit.BukkitAdapter.lambda$adapt$7(BukkitAdapter.java:491) ~[?:?]
at com.sk89q.worldedit.bukkit.fastutil.ints.Int2ObjectOpenHashMap.computeIfAbsent(Int2ObjectOpenHashMap.java:499) ~[?:?]
at com.sk89q.worldedit.bukkit.BukkitAdapter.adapt(BukkitAdapter.java:491) ~[?:?]
at net.coreprotect.worldedit.WorldEditLogger.postProcess(WorldEditLogger.java:55) ~[?:?]
at net.coreprotect.worldedit.CoreProtectLogger.setBlock(CoreProtectLogger.java:56) ~[?:?]
at com.sk89q.worldedit.function.operation.SetBlockMap.resume(SetBlockMap.java:45) ~[?:?]
at com.sk89q.worldedit.extent.reorder.MultiStageReorder$1.resume(MultiStageReorder.java:275) ~[?:?]
at com.sk89q.worldedit.function.operation.OperationQueue.resume(OperationQueue.java:92) ~[?:?]
at com.sk89q.worldedit.function.operation.OperationQueue.resume(OperationQueue.java:92) ~[?:?]
at com.sk89q.worldedit.function.operation.Operations.completeBlindly(Operations.java:74) ~[?:?]
at com.sk89q.worldedit.EditSession.internalFlushSession(EditSession.java:938) ~[?:?]
at com.sk89q.worldedit.EditSession.close(EditSession.java:882) ~[?:?]
at com.sk89q.worldedit.LocalSession.undo(LocalSession.java:255) ~[?:?]
at com.sk89q.worldedit.command.HistoryCommands.undo(HistoryCommands.java:81) ~[?:?]
at com.sk89q.worldedit.command.HistoryCommandsRegistration.cmd$undo(HistoryCommandsRegistration.java:133) ~[?:?]
at org.enginehub.piston.CommandManager.execute(CommandManager.java:157) ~[?:?]
at com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommand(PlatformCommandManager.java:497) ~[?:?]
at com.sk89q.worldedit.util.eventbus.MethodHandleEventHandler.dispatch(MethodHandleEventHandler.java:51) ~[?:?]
at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:73) ~[?:?]
at com.sk89q.worldedit.util.eventbus.EventBus.dispatch(EventBus.java:193) ~[?:?]
at com.sk89q.worldedit.util.eventbus.EventBus.post(EventBus.java:181) ~[?:?]
at com.sk89q.worldedit.bukkit.WorldEditPlugin.onCommand(WorldEditPlugin.java:383) ~[?:?]
at com.sk89q.bukkit.util.DynamicPluginCommand.execute(DynamicPluginCommand.java:55) ~[?:?]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:157) ~[forge:?]
at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:769) ~[forge:7e29f765-296df566-9fb885e8]
at net.minecraft.network.play.ServerPlayNetHandler.func_147361_d(ServerPlayNetHandler.java:1832) ~[?:?]
at net.minecraft.network.play.ServerPlayNetHandler.func_147354_a(ServerPlayNetHandler.java:1667) ~[?:?]
at net.minecraft.network.play.client.CChatMessagePacket.func_148833_a(CChatMessagePacket.java:39) ~[?:?]
at net.minecraft.network.play.client.CChatMessagePacket.func_148833_a(CChatMessagePacket.java:10) ~[?:?]
at net.minecraft.network.PacketThreadUtil.lambda$ensureRunningOnSameThread$0(PacketThreadUtil.java:26) ~[?:?]
at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?]
at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(ThreadTaskExecutor.java:153) ~[?:?]
at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?]
at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:942) ~[?:?]
at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:176) ~[?:?]
at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(ThreadTaskExecutor.java:126) ~[?:?]
at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:925) ~[?:?]
at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:919) ~[?:?]
at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(ThreadTaskExecutor.java:136) ~[?:?]
at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:905) ~[?:?]
at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:825) ~[?:?]
at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:269) ~[?:?]
at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: com.mojang.brigadier.exceptions.CommandSyntaxException: Unknown block type 'timeless_and_classic:box_308block' at position 0: <--[HERE]
Caused by: com.mojang.brigadier.exceptions.CommandSyntaxException: Unknown block type 'timeless_and_classic:box_308block' at position 0: <--[HERE]

Steps to Reproduce :
1.安装WE插件
2.把WE的配置文件更改为：
use-inventory:
enable: true
allow-override: false
creative-mode-overrides: false
3.进入服务器，使用//set 命令放置一些方块
**Description of issue :**方块不能正确放置，一般只有一两个方块能放出来，然后控制台报错如上。我试过WE的7.2.3和7.2.8以及mohist的909和910都不行，但是WE使用背包这个功能在spgiot上能正常工作

**Comment by Mgazul** [comment]
#997
