### ISSUE TITLE
无法运行Bukkit卫星地图插件Dynmap

### ISSUE THREAD

**Issue by ccicnce113424** [Teneted/Tenet#200]
[Dynmap下载](https://dev.bukkit.org/projects/dynmap/files)
Dynmap任何版本都无法运行在Mohist上
以下是错误日志：
[19:20:06 INFO]: [dynmap] version=git-Mohist-1.12.2-6a04bfe (MC: 1.12.2)
[19:20:06 ERROR]: [dynmap] Error finding net.minecraft.server packages
[19:20:06 ERROR]: [dynmap] Cannot find [Lnet.minecraft.server.BiomeBase;
[19:20:06 ERROR]: [dynmap] Cannot find net.minecraft.server.BiomeStorage
[19:20:06 ERROR]: Error initializing dynmap - bukkit version incompatible! initializing dynmap v3.0-beta-10-257 (Is it up to date?)
 java.lang.IllegalArgumentException: Error initializing dynmap - bukkit version incompatible!
        at org.dynmap.bukkit.helper.BukkitVersionHelperGeneric.<init>(BukkitVersionHelperGeneric.java:166) ~[?:?]
        at org.dynmap.bukkit.helper.BukkitVersionHelperCB.<init>(BukkitVersionHelperCB.java:45) ~[?:?]
        at org.dynmap.bukkit.Helper.getHelper(Helper.java:59) ~[?:?]
        at org.dynmap.bukkit.DynmapPlugin.onLoad(DynmapPlugin.java:810) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.loadPlugins(CraftServer.java:393) [CraftServer.class:6a04bfe]
        at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:350) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:316) [nz.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:598) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_241]

**Comment by ccicnce113424** [comment]
Dynmap 2.6和2.5同样无法运行

**Comment by ccicnce113424** [comment]
翻了一下找到了解决方案
#182
