### ISSUE TITLE
[1.16.5 ] Could not pass event PlayerJoinEvent to BetterTeams v4.2.1

### ISSUE THREAD

**Issue by lxgnzlz05** [Teneted/Tenet#2034]
**Mohist Version :** 1.16.5-923

**Concerned mod / plugin** : [BetterTeams](https://www.spigotmc.org/resources/better-teams.17129/)

**Logs :**
```
[21:59:52 INFO]: EJ0007x[/xxx.xxx.xx.xxx:59843] logged in with entity id 896,879 at (4,879.341, 36, -4,208.804)
[21:59:53 WARN]: An avaliable team cannot be found, be prepared for a lot of errors. (this should never happen, and should always be reported to booksaw)
[21:59:53 WARN]: This catch is merely here to stop the server crashing
[21:59:53 ERROR]: Could not pass event PlayerJoinEvent to BetterTeams v4.2.1
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:303) ~[forge:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[forge:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[forge:?]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:588) ~[forge:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:573) ~[forge:?]
        at net.minecraft.server.management.PlayerList.func_72355_a(PlayerList.java:212) ~[?:?]
        at net.minecraft.network.login.ServerLoginNetHandler.func_147326_c(ServerLoginNetHandler.java:173) ~[?:?]
        at net.minecraft.network.login.ServerLoginNetHandler.func_73660_a(ServerLoginNetHandler.java:75) ~[?:?]
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:238) ~[?:?]
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:142) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1116) ~[?:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:1006) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:821) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:269) ~[?:?]
        at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: java.lang.NullPointerException
        at com.booksaw.betterTeams.events.MCTeamManagement.displayBelowName(MCTeamManagement.java:62) ~[?:?]
        at com.booksaw.betterTeams.events.MCTeamManagement.playerJoinEvent(MCTeamManagement.java:109) ~[?:?]
        at jdk.internal.reflect.GeneratedMethodAccessor378.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:301) ~[forge:?]
        ... 15 more
[21:59:53 INFO]: [AuthMe] EJ0007x logged in xxx.xxx.xx.xxx
[21:59:56 WARN]: El_Morris moved wrongly!
```

**Steps to Reproduce :**
When the player join, it generate this issue

**Comment by Mgazul** [comment]
I am using BetterTeams v4.3.3 and cannot reproduce the issue
