### ISSUE TITLE
Cannot Startup The server.

### ISSUE THREAD

**Issue by StayCake** [Teneted/Tenet#244]
Try to use #483 (Jenkins) and i've got this error.

java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:82)
        at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:37)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at red.mohist.Mohist.main(Mohist.java:44)
Caused by: java.lang.ExceptionInInitializerError
        at net.minecraftforge.fml.relauncher.FMLInjectionData.build(FMLInjectionData.java:44)
        at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:93)
        at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupServer(FMLLaunchHandler.java:88)
        at net.minecraftforge.fml.relauncher.FMLLaunchHandler.configureForServerLaunch(FMLLaunchHandler.java:47)
        at net.minecraftforge.fml.common.launcher.FMLServerTweaker.injectIntoClassLoader(FMLServerTweaker.java:62)
        at net.minecraft.launchwrapper.Launch.launch(Launch.java:115)
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
        ... 11 more
Caused by: java.lang.NullPointerException
        at net.minecraftforge.common.ForgeVersion.<clinit>(ForgeVersion.java:57)

Even it continues full of dev builds until #480.

**Comment by Zilacon** [comment]
Getting this exact same error as well. Had to rollback the version.

**Comment by StayCake** [comment]
![image](https://user-images.githubusercontent.com/36215887/79821086-c761e180-83c8-11ea-891c-17dacc6797f0.png)
It still...
