### ISSUE TITLE
Improve support for NMS-based bukkit plugins; remap fields and methods inherited from NMS classes.

### ISSUE THREAD

**Issue by Jannyboy11** [Teneted/Tenet#2501]
**Is your feature request related to a problem? Please describe.**
When implementing an NMS-based plugin, Mohist's doesn't remap methods of classes that inherit from net.minecraf.server classes.
The current workaround is to re-implement these methods with their SRG-names, as I did in https://github.com/Jannyboy11/InvSee-plus-plus/commit/8eaf120a7adb858225b0f33e7b3573b2c81a5ae2
The same goes for field-accesses of protected and public fields.

**Describe the solution you'd like**
I think the best solution is to add the classes from bukkit plugins to the inheritance map of Mohist's remapper.

**Additional context**

**Comment by Mgazul** [comment]
I don't quite understand, did the remapping error occur before you did the fix? If yes, please provide me relevant error log

**Comment by Jannyboy11** [comment]
Yes remapping did not occur and that is exactly the problem, I got NoSuchMethodError and such. Hence my workaround is to do the remapping manually (as indicated by my commit). I will provide you with a stacktrace tomorrow (I am not at my pc anymore today).

Here is what I think the issue is:
Mohist's remapper remaps calls to methods on NMS-based classes only if the reciever object is known to be a class from vanilla minecraft. The remapping does not occur when the method is from a subclass of an NMS-class.

So for example, suppose we have a class from vanilla Minecraft:
```
public class VanillaClass {
    public void vanillaMethod() { /*impl* }
}
```
And a class in a plugin:
```
public PluginClass extends VanillaClass {
    @Override void vanillaMethod() { /*impl*/ }
}
```
Since I am using mojang-mapped CraftBukkit as a dependency and md-5's SpecialSource maven plugin, the `vanillaMethod` will be remapped to some obfuscated name, let's say it is `a`.

The following snippet (from inside a plugin) works correctly on CraftBukkit:
```
new PluginClass().vanillaMethod();
```
because callers also get the remapping applied at build time (meaning the bytecode will be equivalent to `new PluginClass().a();`).

Mohist applies another level of remapping at class-load time, to use SRG-names at runtime (I think), but Mohist fails to remap calls to nonvanilla classes, even if they override vanilla methods, which causes the override method not to override anymore.
The following snipped DOES remap correctly on Mohist:
```
((VanillaClass) new PluginClass()).vanillaMethod()
```
since now Mohist sees that it is an nms method, and so it remaps the caller to use te SRG name as well. The result however is still not the result that we desire, since the base method is called and not the child method (because the child method isn't remapped to SRG).

If the VanillaClass is an interface, we even get an AbstractMethodError, because PluginClass#vanillaMethod() is not remapped to the SRG-name (whilst VanillaClass#vanillaMethod() is).

I hope this clarifies it.

**Comment by Jannyboy11** [comment]
Stacktrace:
```
[13:36:59 INFO]: Jannyboy11 issued server command: /invsee Jankoekenpan
[13:37:02 ERROR]: [InvSee++] Error while trying to create main-inventory spectator inventory
java.util.concurrent.CompletionException: java.lang.NoSuchMethodError: 'void com.janboerman.invsee.spigot.impl_1_19_4_R3.FakeEntityHuman.a(net.minecraft.nbt.CompoundTag)'
        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?] {}
        at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?] {}
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770) ~[?:?] {}
        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftTask.run(CraftTask.java:77) ~[forge-1.19.4-45.0.66-universal.jar%23158!/:?] {re:classloading}
        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:415) ~[forge-1.19.4-45.0.66-universal.jar%23158!/:?] {re:classloading}
        at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:1234) ~[server-1.19.4-20230314.122934-srg.jar%23153!/:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:339) ~[server-1.19.4-20230314.122934-srg.jar%23153!/:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:1173) ~[server-1.19.4-20230314.122934-srg.jar%23153!/:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:1001) ~[server-1.19.4-20230314.122934-srg.jar%23153!/:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:298) ~[server-1.19.4-20230314.122934-srg.jar%23153!/:?] {re:classloading,pl:accesstransformer:B}
        at java.lang.Thread.run(Thread.java:1623) [?:?] {}
Caused by: java.lang.NoSuchMethodError: 'void com.janboerman.invsee.spigot.impl_1_19_4_R3.FakeEntityHuman.a(net.minecraft.nbt.CompoundTag)'
        at com.janboerman.invsee.spigot.impl_1_19_4_R3.InvseeImpl.lambda$createOffline$0(InvseeImpl.java:195) ~[?:?] {}
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?] {}
        ... 8 more
```
in this example, the method FakeEntityHuman.readAdditionalSaveData(CompoundTag) could not be found, because it is not remapped to the SRG name.

So I figured, since the problem only occurs with classes that inherit from vanilla classes, probably the best solution is to add them to Mohist's remapper's inheritance map, although I'm not too sure how the remapping process is set up. I assume that override methods and calls to inherited fields and methods are then remapped correctly to SRG.
