### ISSUE TITLE
Offline mode with bungee - failed to verify username

### ISSUE THREAD

**Issue by kaziu687** [Teneted/Tenet#253]
For now, when mojang authentication servers are down my server in offline mode (in bungee too) refuses to connect some (not all) players. They are disconnected with "Failed to verify username!". They are using offline launcher.

1.12.2 version

**Comment by kaziu687** [comment]
```Failed to verify username!
java.lang.IllegalArgumentException: Name and ID cannot both be blank
	at com.mojang.authlib.GameProfile.<init>(GameProfile.java:26)
	at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillGameProfile(YggdrasilMinecraftSessionService.java:186)
	at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillProfileProperties(YggdrasilMinecraftSessionService.java:173)
	at com.destroystokyo.paper.profile.CraftPlayerProfile.complete(CraftPlayerProfile.java:220)
	at net.minecraft.server.network.NetHandlerLoginServer$LoginHandler.fireEvents(NetHandlerLoginServer.java:313)
	at net.minecraft.server.network.NetHandlerLoginServer$2.run(NetHandlerLoginServer.java:214)

**Comment by kaziu687** [comment]
Will push fix today, may ignore that issue.
