### ISSUE TITLE
Can't connect to the server with ATM3Lite Modpack

### ISSUE THREAD

**Issue by tbringuier** [Teneted/Tenet#254]
Hello,
I recently wanted to try Mohist for my modpack server of ATM3Lite.
I installed Mohist and kept the mods and the config, then launched the server.
There was no errors when it started to launch, but when i try to connect it says in the console :

```
[12:08:23 WARN]: Failed to handle packet for /90.91.149.7:55549
java.lang.NullPointerException: null
at net.minecraft.server.management.PlayerList.allowUserToConnect(PlayerList.java:709) ~[pl.class:?]
at net.minecraft.server.network.NetHandlerLoginServer.func_147326_c(NetHandlerLoginServer.java:150) ~[pc.class:?]
at net.minecraft.server.network.NetHandlerLoginServer.func_73660_a(NetHandlerLoginServer.java:73) ~[pc.class:?]
at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:296) ~[gw.class:?]
at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:195) [oz.class:?]
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:936) [MinecraftServer.class:?]
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:466) [nz.class:?]
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:788) [MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:632) [MinecraftServer.class:?]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
```

Do you have any solutions ?

**Comment by paqpiiiah** [comment]
do u have FastWorkbench mod installed? if yes, set "is quat here"=false to true in fastbench.cfg
(have no idea why this option called that way)

**Comment by Shawiizz** [comment]
Yeah this error is related to FastWorkbench mod. Please remove it and try again :-)

**Comment by tbringuier** [comment]
It would be preferable to add it to the list of non-compatible mods. I saw that at launch he was checking for compatible mods.

Thanks a lot 👍
