### ISSUE TITLE
Create big cannons crash on assemble - mohist-1.19.2-35-server.jar Forge: 43.2.18

### ISSUE THREAD

**Issue by dikovmaxim** [Teneted/Tenet#2594]
Minecraft verion 1.19.2
mohist-1.19.2-35-server.jar Forge: 43.2.18

Mods: create-1.19.2-0.5.1.c (other versions like b or a are not woring aswell.)
createbigcannons-forge-1.19.2-0.5.2-nightly-4c0e630 (latest version for now)

Afterbuiding a cannon and pulling the lever to assemble it, server craashes. After restert the cannon disappears.
Error message:
`net.minecraft.ReportedException: Exception ticking world
        at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:1009) ~[server-1.19.2-20220805.130853-srg.jar%23131!/:?]
        at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:327) ~[server-1.19.2-20220805.130853-srg.jar%23131!/:?]
        at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:944) ~[server-1.19.2-20220805.130853-srg.jar%23131!/:?]
        at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:791) ~[server-1.19.2-20220805.130853-srg.jar%23131!/:?]
        at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:278) ~[server-1.19.2-20220805.130853-srg.jar%23131!/:?]
        at java.lang.Thread.run(Thread.java:1623) [?:?]
Caused by: java.lang.ClassCastException: class com.simibubi.create.content.contraptions.ContraptionWorld cannot be cast to class net.minecraft.server.level.ServerLevel (com.simibubi.create.content.contraptions.ContraptionWorld is in module create@0.5.1.c of loader 'TRANSFORMER' @77c10a5f; net.minecraft.server.level.ServerLevel is in module minecraft@1.19.2 of loader 'TRANSFORMER' @77c10a5f)
        at net.minecraft.world.level.Level.<init>(Level.java:186) ~[server-1.19.2-20220805.130853-srg.jar%23131!/:?]
        at com.simibubi.create.foundation.utility.worldWrappers.WrappedWorld.<init>(WrappedWorld.java:44) ~[create-1.19.2-0.5.1.c.jar%23128!/:0.5.1.c]
        at com.simibubi.create.content.contraptions.ContraptionWorld.<init>(ContraptionWorld.java:20) ~[create-1.19.2-0.5.1.c.jar%23128!/:0.5.1.c]
        at com.simibubi.create.content.contraptions.Contraption.getContraptionWorld(Contraption.java:190) ~[create-1.19.2-0.5.1.c.jar%23128!/:0.5.1.c]
        at com.simibubi.create.content.contraptions.Contraption.gatherBBsOffThread(Contraption.java:1314) ~[create-1.19.2-0.5.1.c.jar%23128!/:0.5.1.c]
        at com.simibubi.create.content.contraptions.Contraption.onEntityCreated(Contraption.java:269) ~[create-1.19.2-0.5.1.c.jar%23128!/:0.5.1.c]
        at com.simibubi.create.content.contraptions.AbstractContraptionEntity.setContraption(AbstractContraptionEntity.java:116) ~[create-1.19.2-0.5.1.c.jar%23128!/:0.5.1.c]
        at rbasamoyai.createbigcannons.cannon_control.contraption.PitchOrientedContraptionEntity.create(PitchOrientedContraptionEntity.java:46) ~[createbigcannons-forge-1.19.2-0.5.2-nightly-4c0e630.jar%23129!/:?]
        at rbasamoyai.createbigcannons.cannon_control.contraption.PitchOrientedContraptionEntity.create(PitchOrientedContraptionEntity.java:54) ~[createbigcannons-forge-1.19.2-0.5.2-nightly-4c0e630.jar%23129!/:?]
        at rbasamoyai.createbigcannons.cannon_control.cannon_mount.CannonMountBlockEntity.assemble(CannonMountBlockEntity.java:241) ~[createbigcannons-forge-1.19.2-0.5.2-nightly-4c0e630.jar%23129!/:?]
        at rbasamoyai.createbigcannons.cannon_control.cannon_mount.CannonMountBlockEntity.onRedstoneUpdate(CannonMountBlockEntity.java:153) ~[createbigcannons-forge-1.19.2-0.5.2-nightly-4c0e630.jar%23129!/:?]
        at rbasamoyai.createbigcannons.cannon_control.cannon_mount.CannonMountBlock.lambda$tick$0(CannonMountBlock.java:99) ~[createbigcannons-forge-1.19.2-0.5.2-nightly-4c0e630.jar%23129!/:?]
        at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
        at com.simibubi.create.foundation.block.IBE.withBlockEntityDo(IBE.java:29) ~[create-1.19.2-0.5.1.c.jar%23128!/:0.5.1.c]
        at rbasamoyai.createbigcannons.cannon_control.cannon_mount.CannonMountBlock.m_213897_(CannonMountBlock.java:99) ~[createbigcannons-forge-1.19.2-0.5.2-nightly-4c0e630.jar%23129!/:?]
        at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.m_222963_(BlockBehaviour.java:694) ~[server-1.19.2-20220805.130853-srg.jar%23131!/:?]
        at net.minecraft.server.level.ServerLevel.m_184112_(ServerLevel.java:692) ~[server-1.19.2-20220805.130853-srg.jar%23131!/:?]
        at net.minecraft.world.ticks.LevelTicks.m_193272_(LevelTicks.java:215) ~[server-1.19.2-20220805.130853-srg.jar%23131!/:?]
        at net.minecraft.world.ticks.LevelTicks.m_193225_(LevelTicks.java:98) ~[server-1.19.2-20220805.130853-srg.jar%23131!/:?]
        at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:322) ~[server-1.19.2-20220805.130853-srg.jar%23131!/:?]
        at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:1005) ~[server-1.19.2-20220805.130853-srg.jar%23131!/:?]
        ... 5 more`
thx in advice

**Comment by dikovmaxim** [comment]
Is there any fix or sth?
Because I talked to CBC core developer and they told me that I have to contact you and get a feedback from you and they will patch the mod if nessesarry
