### ISSUE TITLE
1.19.4 Crash Again

### ISSUE THREAD

**Issue by SaGye9816** [Teneted/Tenet#2597]
**Minecraft Version :** {Minecraft version}
1.19.4
**Mohist Version :** {Provide Mohist build number}
161
**Operating System :** {Provide the name of your OS}
window
**Logs :** {Link(s) of logs and crash reports if you have}
---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 2023-08-06 22:05:04
Description: Exception in server tick loop

java.lang.IllegalStateException: Failed to initialize server
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:948) ~[server-1.19.4-20230314.122934-srg.jar%23159!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:298) ~[server-1.19.4-20230314.122934-srg.jar%23159!/:?] {re:classloading,pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:833) [?:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.19.4
	Minecraft Version ID: 1.19.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.8, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 315623192 bytes (301 MiB) / 650117120 bytes (620 MiB) up to 8568963072 bytes (8172 MiB)
	CPUs: 16
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 7 5800X 8-Core Processor             
	Identifier: AuthenticAMD Family 25 Model 33 Stepping 0
	Microarchitecture: Zen 3
	Frequency (GHz): 4.20
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: NVIDIA GeForce RTX 3060 Ti
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x2489
	Graphics card #0 versionInfo: DriverVersion=31.0.15.3179
	Memory slot #0 capacity (MB): 16384.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 16384.00
	Memory slot #1 clockSpeed (GHz): 3.20
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 34727.43
	Virtual memory used (MB): 21037.38
	Swap memory total (MB): 2048.00
	Swap memory used (MB): 0.00
	JVM Flags: 0 total; 
	CraftBukkit Information: CraftServer is not running yet
	Server Running: true
	Data Packs: vanilla, mod:forge
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable
	Is Modded: Definitely; Server brand changed to 'Mohist'
	Type: Dedicated Server (map_server.txt)
	ModLauncher: 10.0.8+10.0.8+main.0ef7e830
	ModLauncher launch target: forgeserver
	ModLauncher naming: srg
	ModLauncher services: 
		mixin-0.8.5.jar mixin PLUGINSERVICE 
		eventbus-6.0.5.jar eventbus PLUGINSERVICE 
		fmlloader-1.19.4-45.1.16.jar slf4jfixer PLUGINSERVICE 
		fmlloader-1.19.4-45.1.16.jar object_holder_definalize PLUGINSERVICE 
		fmlloader-1.19.4-45.1.16.jar runtime_enum_extender PLUGINSERVICE 
		fmlloader-1.19.4-45.1.16.jar capability_token_subclass PLUGINSERVICE 
		accesstransformers-8.0.4.jar accesstransformer PLUGINSERVICE 
		fmlloader-1.19.4-45.1.16.jar runtimedistcleaner PLUGINSERVICE 
		modlauncher-10.0.8.jar mixin TRANSFORMATIONSERVICE 
		modlauncher-10.0.8.jar fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		lowcodefml@null
		javafml@null
	Mod List: 
		server-1.19.4-20230314.122934-srg.jar             |Minecraft                     |minecraft                     |1.19.4              |DONE      |Manifest: NOSIGNATURE
		forge-1.19.4-45.1.16-universal.jar                |Forge                         |forge                         |45.1.16             |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: 0d67c913-93e7-4bd2-b006-bef96b41d073
	FML: 0.0
	Forge: net.minecraftforge:45.1.16
**Mod list :** {List of your mods. You can also use /getmodlist command on your server}

**Plugin list :** {List of your plugins. You can also use /getpluginlist command on your server}

**Description of issue :** {Give all details about your issue}

**Comment by SaGye9816** [comment]
2023-08-06 22:04:56,813 INFO  [main] c.m.m.Launcher.main(76): ModLauncher running: args [--launchTarget, forgeserver, --fml.forgeVersion, 45.1.16, --fml.mcVersion, 1.19.4, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20230314.122934]
2023-08-06 22:04:56,819 INFO  [main] c.m.m.Launcher.<init>(51): ModLauncher 10.0.8+10.0.8+main.0ef7e830 starting: java version 17.0.8 by Oracle Corporation; OS Windows 10 arch amd64 version 10.0
2023-08-06 22:04:56,909 INFO  [main] mixin.info(97): SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/C:/Users/D/Desktop/1.19.4_2/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar%2393!/ Service=ModLauncher Env=SERVER
2023-08-06 22:04:57,141 INFO  [main] n.m.f.l.m.JarInJarDependencyLocator.scanMods(54): No dependencies to load found. Skipping!
2023-08-06 22:04:58,030 INFO  [main] c.m.m.LaunchServiceHandler.launch(52): Launching target 'forgeserver' with arguments []
2023-08-06 22:05:01,789 INFO  [modloading-worker-0] n.m.c.ForgeMod.<init>(431): Forge mod loading, version 45.1.16, for MC 1.19.4 with MCP 20230314.122934
2023-08-06 22:05:01,790 INFO  [modloading-worker-0] n.m.c.MinecraftForge.initialize(41): MinecraftForge v45.1.16 Initialized
2023-08-06 22:05:01,810 INFO  [modloading-worker-0] c.m.MohistMC.<init>(25): Mohist loading.....
2023-08-06 22:05:01,888 INFO  [modloading-worker-0] c.m.MohistMC.init(41): EventDispatcherRegistry initialized
2023-08-06 22:05:02,033 INFO  [Forge Version Check] n.m.f.VersionChecker.run(109): Global Forge version check system disabled, no further processing.
2023-08-06 22:05:02,724 INFO  [main] c.m.a.y.YggdrasilAuthenticationService.<init>(74): Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
2023-08-06 22:05:03,876 INFO  [main] n.m.w.i.c.RecipeManager.m_5787_(103): Loaded 7 recipes
2023-08-06 22:05:04,084 INFO  [main] n.m.a.AdvancementList.m_139333_(90): Loaded 1179 advancements
2023-08-06 22:05:04,428 INFO  [Server thread] n.m.s.d.DedicatedServer.m_7038_(152): Starting minecraft server version 1.19.4
2023-08-06 22:05:04,428 INFO  [Server thread] n.m.s.d.DedicatedServer.m_7038_(157): Loading properties
2023-08-06 22:05:04,428 INFO  [Server thread] n.m.s.d.DedicatedServer.m_7038_(173): Default game type: SURVIVAL
2023-08-06 22:05:04,428 INFO  [Server thread] n.m.s.MinecraftServer.m_129793_(1454): Generating keypair
2023-08-06 22:05:04,478 INFO  [Server thread] n.m.s.d.DedicatedServer.m_7038_(184): Starting Minecraft server on *:25565
2023-08-06 22:05:04,519 INFO  [Server thread] n.m.s.n.ServerConnectionListener.m_9711_(84): Using default channel type
2023-08-06 22:05:04,688 WARN  [Server thread] n.m.s.d.DedicatedServer.m_7038_(189): **** FAILED TO BIND TO PORT!
2023-08-06 22:05:04,689 WARN  [Server thread] n.m.s.d.DedicatedServer.m_7038_(190): The exception was: java.net.BindException: Address already in use: bind
2023-08-06 22:05:04,689 WARN  [Server thread] n.m.s.d.DedicatedServer.m_7038_(191): Perhaps a server is already running on that port?
2023-08-06 22:05:04,689 ERROR [Server thread] n.m.s.MinecraftServer.m_130011_(1014): Encountered an unexpected exception
java.lang.IllegalStateException: Failed to initialize server
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:948) ~[server-1.19.4-20230314.122934-srg.jar%23159!/:?]
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:298) ~[server-1.19.4-20230314.122934-srg.jar%23159!/:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
2023-08-06 22:05:04,788 FATAL [Server thread] n.m.c.ForgeMod.lambda$new$30(436): Preparing crash report with UUID 0d67c913-93e7-4bd2-b006-bef96b41d073
2023-08-06 22:05:04,789 ERROR [Server thread] n.m.s.MinecraftServer.m_130011_(1025): This crash report has been saved to: C:\Users\D\Desktop\1.19.4_2\.\crash-reports\crash-2023-08-06_22.05.04-server.txt
2023-08-06 22:05:04,789 INFO  [Server thread] n.m.s.MinecraftServer.m_7041_(791): Stopping server
2023-08-06 22:05:04,789 INFO  [Server thread] n.m.s.MinecraftServer.m_7041_(809): Saving worlds
2023-08-06 22:05:04,790 ERROR [Server thread] n.m.s.MinecraftServer.m_130011_(1037): Exception stopping the server
java.lang.NullPointerException: Cannot invoke "net.minecraft.server.level.ServerLevel.m_6857_()" because "serverlevel2" is null
	at net.minecraft.server.MinecraftServer.m_129885_(MinecraftServer.java:737) ~[server-1.19.4-20230314.122934-srg.jar%23159!/:?]
	at net.minecraft.server.MinecraftServer.m_7041_(MinecraftServer.java:832) ~[server-1.19.4-20230314.122934-srg.jar%23159!/:?]
	at net.minecraft.server.dedicated.DedicatedServer.m_7041_(DedicatedServer.java:615) ~[server-1.19.4-20230314.122934-srg.jar%23159!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:1035) ~[server-1.19.4-20230314.122934-srg.jar%23159!/:?]
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:298) ~[server-1.19.4-20230314.122934-srg.jar%23159!/:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]

**Comment by Mgazul** [comment]
Perhaps a server is already running on that port?
