### ISSUE TITLE
[Crash]1.20.1Crash on start up, related mod ItemProductionLib

### ISSUE THREAD

**Issue by Tollainmear** [Teneted/Tenet#2849]
**Minecraft Version :** 1.20.1

**Mohist Version :** `#511`

**Operating System :** Win10

**Logs :** Below

**Mod list :** ItemProductionLib-1.20.1-1.0.0a-all

**Plugin list :** NONE

**Description of issue :** {Give all details about your issue}
```
[01:00:23 INFO]: Initializing MixinExtras via com.llamalad7.mixinextras.service.MixinExtrasServiceImpl(version=0.2.1).
Exception in thread "main" java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:32)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.run(Launcher.java:108)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.main(Launcher.java:78)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
        at cpw.mods.bootstraplauncher@1.1.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141)
        at com.mohistmc.MohistMCStart.main(MohistMCStart.java:104)
Caused by: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at MC-BOOTSTRAP/fmlloader@1.20.1-47.2.17/net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111)
        at MC-BOOTSTRAP/fmlloader@1.20.1-47.2.17/net.minecraftforge.fml.loading.targets.CommonLaunchHandler.serverService(CommonLaunchHandler.java:103)
        at MC-BOOTSTRAP/fmlloader@1.20.1-47.2.17/net.minecraftforge.fml.loading.targets.CommonServerLaunchHandler.lambda$makeService$0(CommonServerLaunchHandler.java:27)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30)
        ... 8 more
Caused by: java.lang.NoClassDefFoundError: net/minecraft/world/inventory/SmithingMenu
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.block.Blocks.<clinit>(Blocks.java:894)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.block.FireBlock.m_53484_(FireBlock.java:358)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.Bootstrap.m_135870_(Bootstrap.java:46)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.Main.main(Main.java:161)
        ... 16 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.world.inventory.SmithingMenu
        at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:157)
        at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
        ... 20 more
```

**Comment by Tollainmear** [comment]
@Mgazul Hi, crash still occured in `#512` with [ItemProductionLib-1.20.1-1.0.0a-all] (only one mod loaded)

```
感谢使用Mohist - 1.20.1-542, Java(17.0.7) 61.0

检查库文件中，请稍等...
库文件检查完成，未发现问题 :)
搜索不兼容的MOD中...
[00:25:06 INFO]: ModLauncher running: args [--launchTarget, forgeserver, --fml.forgeVersion, 47.2.17, --fml.mcVersion, 1.20.1, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20230612.114412, -nogui]
[00:25:06 INFO]: ModLauncher 10.0.9+10.0.9+main.dcd20f30 starting: java version 17.0.7 by OpenLogic; OS Windows 10 arch amd64 version 10.0
[00:25:06 INFO]: ImmediateWindowProvider not loading because launch target is forgeserver
[00:25:06 INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/D:/Games/MCServer-1.20.1/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar%23111!/ Service=ModLauncher Env=SERVER
[00:25:06 INFO]: Found 2 dependencies adding them to mods collection
[00:25:07 INFO]: Compatibility level set to JAVA_17
[00:25:07 INFO]: Launching target 'forgeserver' with arguments [-nogui]
[00:25:07 WARN]: Error loading class: tfar/davespotioneering/blockentity/AdvancedBrewingStandBlockEntity (java.lang.ClassNotFoundException: tfar.davespotioneering.blockentity.AdvancedBrewingStandBlockEntity)
[00:25:07 WARN]: @Mixin target tfar.davespotioneering.blockentity.AdvancedBrewingStandBlockEntity was not found itemproductionlib.mixins.json:davespotioneering/AdvancedBrewingStandBlockEntityMixin
[00:25:07 WARN]: Error loading class: vectorwing/farmersdelight/common/block/entity/CookingPotBlockEntity (java.lang.ClassNotFoundException: vectorwing.farmersdelight.common.block.entity.CookingPotBlockEntity)
[00:25:07 WARN]: @Mixin target vectorwing.farmersdelight.common.block.entity.CookingPotBlockEntity was not found itemproductionlib.mixins.json:farmersdelight/CookingPotBlockEntityMixin
[00:25:07 WARN]: Error loading class: vectorwing/farmersdelight/common/block/entity/StoveBlockEntity (java.lang.ClassNotFoundException: vectorwing.farmersdelight.common.block.entity.StoveBlockEntity)
[00:25:07 WARN]: @Mixin target vectorwing.farmersdelight.common.block.entity.StoveBlockEntity was not found itemproductionlib.mixins.json:farmersdelight/StoveBlockEntityMixin
[00:25:07 INFO]: Initializing MixinExtras via com.llamalad7.mixinextras.service.MixinExtrasServiceImpl(version=0.2.1).
Exception in thread "main" java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:32)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.run(Launcher.java:108)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.main(Launcher.java:78)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
        at cpw.mods.bootstraplauncher@1.1.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141)
        at com.mohistmc.MohistMCStart.main(MohistMCStart.java:104)
Caused by: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at MC-BOOTSTRAP/fmlloader@1.20.1-47.2.17/net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111)
        at MC-BOOTSTRAP/fmlloader@1.20.1-47.2.17/net.minecraftforge.fml.loading.targets.CommonLaunchHandler.serverService(CommonLaunchHandler.java:103)
        at MC-BOOTSTRAP/fmlloader@1.20.1-47.2.17/net.minecraftforge.fml.loading.targets.CommonServerLaunchHandler.lambda$makeService$0(CommonServerLaunchHandler.java:27)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30)
        ... 8 more
Caused by: java.lang.NoClassDefFoundError: net/minecraft/world/inventory/SmithingMenu
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.block.Blocks.<clinit>(Blocks.java:894)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.block.FireBlock.m_53484_(FireBlock.java:358)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.Bootstrap.m_135870_(Bootstrap.java:46)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.Main.main(Main.java:161)
        ... 16 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.world.inventory.SmithingMenu
        at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:157)
        at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
        ... 20 more
```

**Comment by Tollainmear** [comment]
### Another crash with Advanced backups mod(ver3.4)
```感谢使用Mohist - 1.20.1-542, Java(17.0.7) 61.0

检查库文件中，请稍等...
库文件检查完成，未发现问题 :)
搜索不兼容的MOD中...
[02:42:42 INFO]: ModLauncher running: args [--launchTarget, forgeserver, --fml.forgeVersion, 47.2.17, --fml.mcVersion, 1.20.1, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20230612.114412, -nogui]
[02:42:42 INFO]: ModLauncher 10.0.9+10.0.9+main.dcd20f30 starting: java version 17.0.7 by OpenLogic; OS Windows 10 arch amd64 version 10.0
[02:42:42 INFO]: ImmediateWindowProvider not loading because launch target is forgeserver
[02:42:42 INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/D:/Games/MCServer-1.20.1/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar%23111!/ Service=ModLauncher Env=SERVER
[02:42:43 INFO]: No dependencies to load found. Skipping!
Exception in thread "main" java.lang.module.ResolutionException: Module advancedbackups contains package org.fusesource.jansi, module org.fusesource.jansi exports package org.fusesource.jansi to advancedbackups
        at java.base/java.lang.module.Resolver.resolveFail(Unknown Source)
        at java.base/java.lang.module.Resolver.failTwoSuppliers(Unknown Source)
        at java.base/java.lang.module.Resolver.checkExportSuppliers(Unknown Source)
        at java.base/java.lang.module.Resolver.finish(Unknown Source)
        at java.base/java.lang.module.Configuration.<init>(Unknown Source)
        at java.base/java.lang.module.Configuration.resolveAndBind(Unknown Source)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.ModuleLayerHandler.buildLayer(ModuleLayerHandler.java:75)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.TransformationServicesHandler.buildTransformingClassLoader(TransformationServicesHandler.java:60)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.run(Launcher.java:106)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.main(Launcher.java:78)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
        at cpw.mods.bootstraplauncher@1.1.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141)
        at com.mohistmc.MohistMCStart.main(MohistMCStart.java:104)
```

**Comment by Tollainmear** [comment]
@Mgazul Hi, thanks for fixing the problem, after a test, I'm sure that the problem of incompat with ItemProductionLib was sovled in the latest build 514, however, the `crash` with `Advanced backups mod(ver3.4)` stills there.

Shall I create another issue to track this problem?
