### ISSUE TITLE
1.19.2 Failed to save chunk, getViewers()Ljava/util/List; is abstract

### ISSUE THREAD

**Issue by zhaodice** [Teneted/Tenet#2868]
**Is your feature request related to a problem? Please describe.**
Failed to save chunk

**Describe the solution you'd like**
Add a method with try {} like:
```
List safeGetViewers(net.minecraft.world.Container container){
  try{
     return Lists.newArrayList(container.getViewers())
  }catch(AbstractMethodError e){
     //print a warning
     return Lists.newArrayList()
  }
}

```
https://github.com/MohistMC/Mohist/blob/1.19.2/patches/minecraft/net/minecraft/server/level/ServerLevel.java.patch
replace all of `Lists.newArrayList(container.getViewers())` with `safeGetViewers(container)` 
for example , modify it:
```
    public void m_8712_(LevelChunk p_8713_) {
+      // Spigot Start
+      for (net.minecraft.world.level.block.entity.BlockEntity tileentity : p_8713_.m_62954_().values()) {
+         if (tileentity instanceof net.minecraft.world.Container container) {
+            for (org.bukkit.entity.HumanEntity h : Lists.newArrayList(container.getViewers())) { 
+               h.closeInventory();
+            }
+         }
+      }
+      // Spigot End
       p_8713_.m_187957_();
       p_8713_.m_187979_(this);
    }
```
to :
```
    public void m_8712_(LevelChunk p_8713_) {
+      // Spigot Start
+      for (net.minecraft.world.level.block.entity.BlockEntity tileentity : p_8713_.m_62954_().values()) {
+         if (tileentity instanceof net.minecraft.world.Container container) {
+            for (org.bukkit.entity.HumanEntity h : safeGetViewers(container)) { //safeGetViewers
+               h.closeInventory();
+            }
+         }
+      }
+      // Spigot End
       p_8713_.m_187957_();
       p_8713_.m_187979_(this);
    }
```
**Additional context**
```
java.util.concurrent.CompletionException: java.lang.AbstractMethodError: Method net/mcreator/rtdd/block/entity/B275BlockEntity.getViewers()Ljava/util/List; is abstract
        at java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source) ~[?:?]
        at java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source) ~[?:?]
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source) ~[?:?]
        at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:?]
        at net.minecraft.server.level.ChunkMap.m_140353_(ChunkMap.java:471) ~[server-1.19.2-20220805.130853-srg.jar%23230!/:?]
        at net.minecraft.server.level.ChunkMap.m_140280_(ChunkMap.java:442) ~[server-1.19.2-20220805.130853-srg.jar%23230!/:?]
        at net.minecraft.server.level.ServerChunkCache.m_201698_(ServerChunkCache.java:323) ~[server-1.19.2-20220805.130853-srg.jar%23230!/:?]
        at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:351) ~[server-1.19.2-20220805.130853-srg.jar%23230!/:?]
        at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:1083) ~[server-1.19.2-20220805.130853-srg.jar%23230!/:?]
        at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:327) ~[server-1.19.2-20220805.130853-srg.jar%23230!/:?]
        at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:1018) ~[server-1.19.2-20220805.130853-srg.jar%23230!/:?]
        at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:855) ~[server-1.19.2-20220805.130853-srg.jar%23230!/:?]
        at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:279) ~[server-1.19.2-20220805.130853-srg.jar%23230!/:?]
        at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: java.lang.AbstractMethodError: Method net/mcreator/rtdd/block/entity/B275BlockEntity.getViewers()Ljava/util/List; is abstract
        at net.mcreator.rtdd.block.entity.B275BlockEntity.getViewers(B275BlockEntity.java) ~[乡野forge1.19.2正式.jar%23228!/:?]
        at net.minecraft.server.level.ServerLevel.m_8712_(ServerLevel.java:943) ~[server-1.19.2-20220805.130853-srg.jar%23230!/:?]
        at net.minecraft.server.level.ChunkMap.m_202998_(ChunkMap.java:501) ~[server-1.19.2-20220805.130853-srg.jar%23230!/:?]
        ... 12 more
```

The core problem is the mod author doesn't implements "getViewers()Ljava/util/List" method from WorldlyContainer Class
mod source: https://github.com/6rbob/rtdd-forge/blob/master/src/main/java/net/mcreator/rtdd/block/entity/B275BlockEntity.java
so we can think this error as a warning.

**Comment by Mgazul** [comment]
Fixed
