### ISSUE TITLE
[1.20.1] LevelledMobs Plugin Does not Work with Modded Entities 

### ISSUE THREAD

**Issue by rafucuk** [Teneted/Tenet#2895]
**Minecraft Version :** 1.20.1

**Mohist Version :** mohist-1.20.1-520-server

**Operating System :** Ubuntu 20.04

**Concerned mod / plugin** : LevelledMobs (https://github.com/ArcanePlugins/LevelledMobs)

**Logs :** Link(s) of logs and crash reports if you have

**Description of issue :**
  Levelledmobs does not recognising modded entities 
  but if I test with arclight it recognises perfectly 
  so I was going to tell that to mod developers but I saw they are highly against "mohist"
  and no one reported this in here so

 I was using mohist and it didn't gave entities/mobs nametag or modified attributes, changed server software to arclight, it started to give mobs nametag and attributes. And there was a constantly looping error I will create a bug report for that too.

reported to discord too.

**Comment by rafucuk** [comment]
Created the bug report.

**Comment by killer2gudpl** [comment]
Technically speaking, the plugin is not supposed to get modded entities anyway. I wrote a fix for my private server to cover that (basically modified the source code) which mitigates that issue.

**Comment by rafucuk** [comment]
> Technically speaking, the plugin is not supposed to get modded entities anyway. I wrote a fix for my private server to cover that (basically modified the source code) which mitigates that issue.

can you share it?

**Comment by killer2gudpl** [comment]
@rafucuk sure, add me on Discord - Killer2gudPL

**Comment by rafucuk** [comment]
still parsing error but this time it is diffrent,

```
[15:49:18] [Server thread/WARN] [me.lokka30.levelledmobs.LevelledMobs]: [LevelledMobs] Task #1236 for LevelledMobs v3.15.1 b826 generated an exception
java.lang.NullPointerException: Cannot invoke "net.minecraft.world.entity.EntityType.m_20675_()" because the return value of "java.util.Map.get(Object)" is null
	at org.bukkit.craftbukkit.v1_20_R1.util.CraftMagicNumbers.getTranslationKey(CraftMagicNumbers.java:382) ~[forge-1.20.1-47.2.20-universal.jar%23221!/:?]
	at org.bukkit.entity.EntityType.translationKey(EntityType.java:467) ~[forge-1.20.1-47.2.20-universal.jar%23221!/:?]
	at me.lokka30.levelledmobs.nametag.KyoriNametags.generateComponent(KyoriNametags.java:27) ~[?:?]
	at me.lokka30.levelledmobs.nametag.NmsNametagSender.buildNametagComponent(NmsNametagSender.java:213) ~[?:?]
	at me.lokka30.levelledmobs.nametag.NmsNametagSender.sendNametagNonAsync(NmsNametagSender.java:78) ~[?:?]
	at me.lokka30.levelledmobs.nametag.NmsNametagSender.lambda$sendNametag$0(NmsNametagSender.java:45) ~[?:?]
	at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:78) ~[forge-1.20.1-47.2.20-universal.jar%23221!/:?]
	at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:416) ~[forge-1.20.1-47.2.20-universal.jar%23221!/:?]
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:1135) ~[server-1.20.1-20230612.114412-srg.jar%23216!/:?]
	at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:342) ~[server-1.20.1-20230612.114412-srg.jar%23216!/:?]
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:1074) ~[server-1.20.1-20230612.114412-srg.jar%23216!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:904) ~[server-1.20.1-20230612.114412-srg.jar%23216!/:?]
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:281) ~[server-1.20.1-20230612.114412-srg.jar%23216!/:?]
	at java.lang.Thread.run(Thread.java:842) [?:?]
```

this time the error shows EntityType is null, even it is a vanilla mob.
