### ISSUE TITLE
[1.20.1] LevelledMobs looped error

### ISSUE THREAD

**Issue by rafucuk** [Teneted/Tenet#2896]
**Minecraft Version :** Minecraft version

**Mohist Version :** Provide Mohist build number

**Operating System :** Provide the name of your OS

**Concerned mod / plugin** : Provide mod / plugin name and download link if possible

**Logs :** Link(s) of logs and crash reports if you have

**Steps to Reproduce :**
 1. Do this
 2. Then do that
 3. ...

**Description of issue :** I created a plugin report #2895 and this is continue of that report,
There is a error looping in the console about exception:

```
...
	at java.lang.Thread.run(Thread.java:840) [?:?]
[22:17:08] [Server thread/WARN] [me.lokka30.levelledmobs.LevelledMobs]: [LevelledMobs] Task #14660 for LevelledMobs v3.14.1 b817 generated an exception
java.util.NoSuchElementException: No value present
	at java.util.Optional.orElseThrow(Optional.java:377) ~[?:?]
	at org.bukkit.craftbukkit.v1_20_R1.util.CraftMagicNumbers.getTranslationKey(CraftMagicNumbers.java:381) ~[forge-1.20.1-47.2.20-universal.jar%23331!/:?]
	at org.bukkit.entity.EntityType.translationKey(EntityType.java:467) ~[forge-1.20.1-47.2.20-universal.jar%23331!/:?]
	at me.lokka30.levelledmobs.nametag.KyoriNametags.generateComponent(KyoriNametags.java:27) ~[?:?]
	at me.lokka30.levelledmobs.nametag.NmsNametagSender.buildNametagComponent(NmsNametagSender.java:213) ~[?:?]
	at me.lokka30.levelledmobs.nametag.NmsNametagSender.sendNametagNonAsync(NmsNametagSender.java:78) ~[?:?]
	at me.lokka30.levelledmobs.nametag.NmsNametagSender.lambda$sendNametag$0(NmsNametagSender.java:45) ~[?:?]
	at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:78) ~[forge-1.20.1-47.2.20-universal.jar%23331!/:?]
	at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:416) ~[forge-1.20.1-47.2.20-universal.jar%23331!/:?]
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:1135) ~[server-1.20.1-20230612.114412-srg.jar%23326!/:?]
	at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:341) ~[server-1.20.1-20230612.114412-srg.jar%23326!/:?]
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:1074) ~[server-1.20.1-20230612.114412-srg.jar%23326!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:904) ~[server-1.20.1-20230612.114412-srg.jar%23326!/:?]
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:281) ~[server-1.20.1-20230612.114412-srg.jar%23326!/:?]
	at java.lang.Thread.run(Thread.java:840) [?:?]
[22:17:08] [Server thread/WARN] [me.lokka30.levelledmobs.LevelledMobs]: [LevelledMobs] Task #14663 for LevelledMobs v3.14.1 b817 generated an exception
...
```

**Comment by rafucuk** [comment]
![image](https://github.com/MohistMC/Mohist/assets/33981808/120bbb2b-ce1f-4d0e-8520-ba8606d99a4b)
for more context

**Comment by killer2gudpl** [comment]
For me the error started with a newer mohist version, so as mentioned above, probably an issue with Paper version.
