### ISSUE TITLE
[1.20.1] Mob EntityType null error

### ISSUE THREAD

**Issue by rafucuk** [Teneted/Tenet#2937]
Mythicmobs returns a null EntityType:
```
[04:12:29] [Server thread/WARN] []: java.lang.NullPointerException: Cannot invoke "org.bukkit.entity.EntityType.getEntityClass()" because "entityType" is null
[04:12:29] [Server thread/WARN] []: 	at TRANSFORMER/forge@47.2.20/org.bukkit.craftbukkit.v1_20_R1.CraftRegionAccessor.spawnEntity(CraftRegionAccessor.java:420)
[04:12:29] [Server thread/WARN] []: 	at io.lumine.mythic.bukkit.adapters.BukkitEntityType.spawnEntity(BukkitEntityType.java:70)
[04:12:29] [Server thread/WARN] []: 	at io.lumine.mythic.bukkit.entities.BukkitCustom.spawn(BukkitCustom.java:37)
[04:12:29] [Server thread/WARN] []: 	at io.lumine.mythic.bukkit.adapters.BukkitEntityType.spawn(BukkitEntityType.java:39)
[04:12:29] [Server thread/WARN] []: 	at io.lumine.mythic.core.mobs.MobType.spawn(MobType.java:894)
[04:12:29] [Server thread/WARN] []: 	at io.lumine.mythic.core.mobs.MobExecutor.spawnMob(MobExecutor.java:563)
[04:12:29] [Server thread/WARN] []: 	at io.lumine.mythic.core.mobs.MobExecutor.spawnMob(MobExecutor.java:556)
[04:12:29] [Server thread/WARN] []: 	at io.lumine.mythic.bukkit.commands.mobs.SpawnCommand.onCommand(SpawnCommand.java:161)
[04:12:29] [Server thread/WARN] []: 	at io.lumine.mythic.bukkit.utils.commands.Command.onCommand(Command.java:64)
[04:12:29] [Server thread/WARN] []: 	at io.lumine.mythic.bukkit.utils.commands.Command.onCommand(Command.java:55)
[04:12:29] [Server thread/WARN] []: 	at io.lumine.mythic.bukkit.utils.commands.Command.onCommand(Command.java:55)
```

**Comment by rafucuk** [comment]
Well I have a lot of information right now, tested & source checked mythicmobs.
![image](https://github.com/MohistMC/Mohist/assets/33981808/c74fe229-e369-4530-bb99-d8822db8a27d)
issue is right here, spawnEntity does not returning forge mob types. 

I've checked mythicmobs source code and there is spawnEntity function.
![image](https://github.com/MohistMC/Mohist/assets/33981808/b2a3781e-041a-45d0-b95f-ab1de1f3ff38)

And no the issue is not with mythicmobs only, mythicmobs uses their custom entity types;
![image](https://github.com/MohistMC/Mohist/assets/33981808/5c36bab0-4e9a-4fad-97f4-a5d8e8d90346)
**BUT** there is also a custom entity type which if entity_type is not one of their custom entity types it will get bukkit entity type and use that.
![image](https://github.com/MohistMC/Mohist/assets/33981808/38129a53-a25b-4666-a44a-0548be298b0e)


So the only issue is the CraftRegionAccessor.java returning null entitytype

@Mgazul

**Comment by rafucuk** [comment]
_I've used recaf to get source code of mythicmobs for only searching purposes_

**Comment by rafucuk** [comment]
It is not only a mythicmobs problem, every plugin that uses CraftRegionAccessor's spawnEntity will error if used with forged entity, for example denizen uses that too it shows that it registered in "server.list_entity_types" (a variable that shows custom entities registered on server)
![image](https://github.com/MohistMC/Mohist/assets/33981808/2beaf109-be2b-4842-b50a-a4a55c97295b)
![image](https://github.com/MohistMC/Mohist/assets/33981808/aa3483ad-1c1f-4a91-b39d-ec9d8a97d765)

REINAPACK_KITSUNE is my custom mob and it gives similar issue in the console
![image](https://github.com/MohistMC/Mohist/assets/33981808/a46d2e4d-118f-49dc-b85c-3e50026e41cf)

**Comment by rafucuk** [comment]
I hope this will be enough, if any additional information needed, I will try my best.

**Comment by rafucuk** [comment]
![image](https://github.com/MohistMC/Mohist/assets/33981808/96a37f29-916f-4113-8026-a1fd5e468cd7)
also denizen returns entity type UNKNOWN

**Comment by rafucuk** [comment]
Changed title because it seems it is not only with mythicmobs.

**Comment by rafucuk** [comment]
#2895 & #2896 says fixed issues but they throwing similar errors.

**Comment by AlwaysReadyWBY** [comment]
Still not fixed yet.
[This is how modded entity types are added in mohist:](https://github.com/MohistMC/Mohist/blob/dc15e4197123cd15f2c94a09a1c0de256309c0e7/src/main/java/com/mohistmc/forge/ForgeInjectBukkit.java#L274)
[And this is how CraftRegionAccessor.spawnEntity creates an entity:](https://github.com/MohistMC/Mohist/blob/dc15e4197123cd15f2c94a09a1c0de256309c0e7/src/main/java/org/bukkit/craftbukkit/v1_20_R1/CraftRegionAccessor.java#L568)
It seems that CraftRegionAccessor.spawnEntity simply won't work for mod entity types.

**Comment by AlwaysReadyWBY** [comment]
I wonder if it is possible to fix CraftRegionAccessor.spawnEntity for mod entity types with
ForgeRegistries.ENTITY_TYPES.getValue(resourcelocation)
                .spawn(level,pos,mobspawntype);
or the like?
