### ISSUE TITLE
[1.20.1] Server Failed To Start

### ISSUE THREAD

**Issue by astatine-213** [Teneted/Tenet#2954]
**Minecraft Version :** {1.20.1}

**Mohist Version :** {build 549}

**Operating System :** {Windows}

**Logs :** {[2024-02-12-3.log](https://github.com/MohistMC/Mohist/files/14241034/2024-02-12-3.log)}

**Mod list :** {None. No mods installed.}

**Plugin list :** {None. No Plugins installed.}

**Description of issue :** {a plain server just can't start. Used cmd command "C:\Program Files\Java\jdk-18.0.1.1\bin\java.exe" -Xmx16G -jar mohist-1.20.1-549-server.jar. The error message says that "java.lang.NullPointerException: Cannot invoke "org.bukkit.Server.getPluginManager()" because the return value of "org.bukkit.Bukkit.getServer()" is null". How should I solve this problem? I've tried changing java versions(17.0.1LTS) and restarting everything I can }

**Comment by xchawai** [comment]
Same problem.

**Comment by xchawai** [comment]
> Same problem.

[22:52:23 ERROR]: Failed to start the minecraft server
java.lang.NullPointerException: Cannot invoke "org.bukkit.Server.getPluginManager()" because the return value of "org.bukkit.Bukkit.getServer()" is null
        at org.bukkit.permissions.PermissibleBase.clearPermissions(PermissibleBase.java:183) ~[forge-1.20.1-47.2.20-universal.jar%23197!/:?]
        at org.bukkit.permissions.PermissibleBase.recalculatePermissions(PermissibleBase.java:160) ~[forge-1.20.1-47.2.20-universal.jar%23197!/:?]
        at org.bukkit.permissions.PermissibleBase.<init>(PermissibleBase.java:29) ~[forge-1.20.1-47.2.20-universal.jar%23197!/:?]
        at org.bukkit.craftbukkit.v1_20_R1.command.ServerCommandSender.<init>(ServerCommandSender.java:26) ~[forge-1.20.1-47.2.20-universal.jar%23197!/:?]
        at org.bukkit.craftbukkit.v1_20_R1.command.CraftRemoteConsoleCommandSender.<init>(CraftRemoteConsoleCommandSender.java:13) ~[forge-1.20.1-47.2.20-universal.jar%23197!/:?]
        at net.minecraft.server.rcon.RconConsoleSource.<init>(RconConsoleSource.java:24) ~[server-1.20.1-20230612.114412-srg.jar%23192!/:?]
        at net.minecraft.server.dedicated.DedicatedServer.<init>(DedicatedServer.java:86) ~[server-1.20.1-20230612.114412-srg.jar%23192!/:?]
        at net.minecraft.server.Main.lambda$main$4(Main.java:274) ~[server-1.20.1-20230612.114412-srg.jar%23192!/:?]
        at net.minecraft.server.MinecraftServer.m_129872_(MinecraftServer.java:290) ~[server-1.20.1-20230612.114412-srg.jar%23192!/:?]
        at net.minecraft.server.Main.main(Main.java:265) ~[server-1.20.1-20230612.114412-srg.jar%23192!/:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.2.20.jar%23186!/:?]
        at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.serverService(CommonLaunchHandler.java:103) ~[fmlloader-1.20.1-47.2.20.jar%23186!/:?]
        at net.minecraftforge.fml.loading.targets.CommonServerLaunchHandler.lambda$makeService$0(CommonServerLaunchHandler.java:27) ~[fmlloader-1.20.1-47.2.20.jar%23186!/:?]
        at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.9.jar%23101!/:?]
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.9.jar%23101!/:?]
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.9.jar%23101!/:?]
        at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) [modlauncher-10.0.9.jar%23101!/:?]
        at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) [modlauncher-10.0.9.jar%23101!/:?]
        at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.9.jar%23101!/:?]
        at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.9.jar%23101!/:?]
        at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?]
        at com.mohistmc.MohistMCStart.main(MohistMCStart.java:106) [mohist-1.20.1-549-server.jar:1.20.1-579]

**Comment by YangYuPts** [comment]
Same problem.

**Comment by Mgazul** [comment]
Fixed
