### ISSUE TITLE
[1.20.4] Server Connection Issue

### ISSUE THREAD

**Issue by ysmreg** [Teneted/Tenet#2964]
**Minecraft Version :** 1.20.4

**Mohist Version :** 1.20.4

**Operating System :** Windows 11

**Logs :** 
[debug.log](https://github.com/MohistMC/Mohist/files/14327350/debug.log)

**Mod list :** geyser,floodgate,hydraulic(However, the error occurs even if there is no mod.)

**Plugin list :** None

**Description of issue :** When I try to connect from a client with forge 1.20.4-49.0.27 I get an error.
Client Logs:
`[192月2024 15:34:12.699] [Render thread/INFO] [net.minecraft.client.gui.screens.ConnectScreen/]: Connecting to localhost, 25565
[192月2024 15:34:12.700] [Server Connector #5/DEBUG] [net.minecraftforge.network.DualStackUtils/]: Detected IPv6 address: "0:0:0:0:0:0:0:1"
[192月2024 15:34:12.701] [Netty Client IO #10/DEBUG] [net.minecraftforge.network.filters.NetworkFilters/]: Injected net.minecraftforge.network.filters.VanillaConnectionNetworkFilter@79dbc21c into net.minecraft.network.Connection@3cd95343
[192月2024 15:34:16.756] [Render thread/INFO] [net.minecraft.client.gui.screens.ConnectScreen/]: Connecting to localhost, 25565
[192月2024 15:34:16.756] [Server Connector #6/DEBUG] [net.minecraftforge.network.DualStackUtils/]: Detected IPv6 address: "0:0:0:0:0:0:0:1"
[192月2024 15:34:16.757] [Netty Client IO #11/DEBUG] [net.minecraftforge.network.filters.NetworkFilters/]: Injected net.minecraftforge.network.filters.VanillaConnectionNetworkFilter@7935307 into net.minecraft.network.Connection@4291cd91
[192月2024 15:34:16.818] [Netty Client IO #11/DEBUG] [net.minecraftforge.network.ForgePacketHandler/FORGE_PACKET_HANDLER]: Received server connection with modlist [floodgate, forge, geyser_neoforge, hydraulic, minecraft, mohist]
[192月2024 15:34:16.818] [Netty Client IO #11/DEBUG] [net.minecraftforge.network.ForgePacketHandler/FORGE_PACKET_HANDLER]: Accepted server connection
[192月2024 15:34:16.819] [Netty Client IO #11/DEBUG] [net.minecraftforge.network.ForgePacketHandler/FORGE_PACKET_HANDLER]: Received server connection with channels [floodgate:form, floodgate:packet, floodgate:skin, floodgate:transfer, forge:handshake, forge:login, forge:tier_sorting, minecraft:register, minecraft:unregister]
[192月2024 15:34:16.819] [Netty Client IO #11/DEBUG] [net.minecraftforge.network.NetworkRegistry/NETREGISTRY]: Channel 'forge:tier_sorting' : Version test of 'PRESENT 1' from server : ACCEPTED
[192月2024 15:34:16.819] [Netty Client IO #11/DEBUG] [net.minecraftforge.network.NetworkRegistry/NETREGISTRY]: Channel 'forge:handshake' : Version test of 'PRESENT 0' from server : ACCEPTED
[192月2024 15:34:16.819] [Netty Client IO #11/DEBUG] [net.minecraftforge.network.NetworkRegistry/NETREGISTRY]: Channel 'forge:login' : Version test of 'PRESENT 0' from server : ACCEPTED
[192月2024 15:34:16.819] [Netty Client IO #11/DEBUG] [net.minecraftforge.network.NetworkRegistry/NETREGISTRY]: Channel 'minecraft:unregister' : Version test of 'PRESENT 0' from server : ACCEPTED
[192月2024 15:34:16.819] [Netty Client IO #11/DEBUG] [net.minecraftforge.network.NetworkRegistry/NETREGISTRY]: Channel 'minecraft:register' : Version test of 'PRESENT 0' from server : ACCEPTED
[192月2024 15:34:16.819] [Netty Client IO #11/DEBUG] [net.minecraftforge.network.NetworkRegistry/NETREGISTRY]: Accepting channel list from server
[192月2024 15:34:16.824] [Netty Client IO #11/DEBUG] [net.minecraftforge.network.ForgePacketHandler/FORGE_PACKET_HANDLER]: Expecting 19 registries: minecraft:command_argument_type, minecraft:recipe_serializer, minecraft:sound_event, minecraft:particle_type, minecraft:villager_profession, minecraft:item, minecraft:potion, minecraft:painting_variant, forge:fluid_type, minecraft:block_entity_type, forge:display_contexts, minecraft:block, forge:entity_data_serializers, minecraft:mob_effect, minecraft:stat_type, minecraft:menu, minecraft:enchantment, minecraft:fluid, minecraft:entity_type
[192月2024 15:34:16.825] [Netty Client IO #11/DEBUG] [net.minecraftforge.network.ForgePacketHandler/FORGE_PACKET_HANDLER]: Received registry data packet for minecraft:command_argument_type token 1
[192月2024 15:34:16.825] [Netty Client IO #11/DEBUG] [net.minecraftforge.network.ForgePacketHandler/FORGE_PACKET_HANDLER]: Received registry data packet for minecraft:recipe_serializer token 2
[192月2024 15:34:16.830] [Netty Client IO #11/DEBUG] [net.minecraftforge.network.ForgePacketHandler/FORGE_PACKET_HANDLER]: Received registry data packet for minecraft:sound_event token 3
[192月2024 15:34:16.831] [Netty Client IO #11/DEBUG] [net.minecraftforge.network.ForgePacketHandler/FORGE_PACKET_HANDLER]: Received registry data packet for minecraft:particle_type token 4
[192月2024 15:34:16.831] [Netty Client IO #11/DEBUG] [net.minecraftforge.network.ForgePacketHandler/FORGE_PACKET_HANDLER]: Received registry data packet for minecraft:villager_profession token 5
[192月2024 15:34:16.836] [Netty Client IO #11/DEBUG] [net.minecraftforge.network.ForgePacketHandler/FORGE_PACKET_HANDLER]: Received registry data packet for minecraft:item token 6
[192月2024 15:34:16.837] [Netty Client IO #11/DEBUG] [net.minecraftforge.network.ForgePacketHandler/FORGE_PACKET_HANDLER]: Received registry data packet for minecraft:potion token 7
[192月2024 15:34:16.837] [Netty Client IO #11/DEBUG] [net.minecraftforge.network.ForgePacketHandler/FORGE_PACKET_HANDLER]: Received registry data packet for minecraft:painting_variant token 8
[192月2024 15:34:16.838] [Netty Client IO #11/DEBUG] [net.minecraftforge.network.ForgePacketHandler/FORGE_PACKET_HANDLER]: Received registry data packet for forge:fluid_type token 9
[192月2024 15:34:16.838] [Netty Client IO #11/DEBUG] [net.minecraftforge.network.ForgePacketHandler/FORGE_PACKET_HANDLER]: Received registry data packet for minecraft:block_entity_type token 10
[192月2024 15:34:16.839] [Netty Client IO #11/DEBUG] [net.minecraftforge.network.ForgePacketHandler/FORGE_PACKET_HANDLER]: Received registry data packet for forge:display_contexts token 11
[192月2024 15:34:16.843] [Netty Client IO #11/DEBUG] [net.minecraftforge.network.ForgePacketHandler/FORGE_PACKET_HANDLER]: Received registry data packet for minecraft:block token 12
[192月2024 15:34:16.844] [Netty Client IO #11/DEBUG] [net.minecraftforge.network.ForgePacketHandler/FORGE_PACKET_HANDLER]: Received registry data packet for forge:entity_data_serializers token 13
[192月2024 15:34:16.845] [Netty Client IO #11/DEBUG] [net.minecraftforge.network.ForgePacketHandler/FORGE_PACKET_HANDLER]: Received registry data packet for minecraft:mob_effect token 14
[192月2024 15:34:16.845] [Netty Client IO #11/DEBUG] [net.minecraftforge.network.ForgePacketHandler/FORGE_PACKET_HANDLER]: Received registry data packet for minecraft:stat_type token 15
[192月2024 15:34:16.846] [Netty Client IO #11/DEBUG] [net.minecraftforge.network.ForgePacketHandler/FORGE_PACKET_HANDLER]: Received registry data packet for minecraft:menu token 16
[192月2024 15:34:16.846] [Netty Client IO #11/DEBUG] [net.minecraftforge.network.ForgePacketHandler/FORGE_PACKET_HANDLER]: Received registry data packet for minecraft:enchantment token 17
[192月2024 15:34:16.847] [Netty Client IO #11/DEBUG] [net.minecraftforge.network.ForgePacketHandler/FORGE_PACKET_HANDLER]: Received registry data packet for minecraft:fluid token 18
[192月2024 15:34:16.847] [Netty Client IO #11/DEBUG] [net.minecraftforge.network.ForgePacketHandler/FORGE_PACKET_HANDLER]: Received registry data packet for minecraft:entity_type token 19
[192月2024 15:34:16.848] [Netty Client IO #11/DEBUG] [net.minecraftforge.network.ForgePacketHandler/FORGE_PACKET_HANDLER]: Waiting for registries to load.
[192月2024 15:34:16.856] [Render thread/DEBUG] [net.minecraftforge.network.ForgePacketHandler/FORGE_PACKET_HANDLER]: Injecting registry snapshot from server.
[192月2024 15:34:17.074] [Render thread/DEBUG] [net.minecraftforge.network.ForgePacketHandler/FORGE_PACKET_HANDLER]: Snapshot injected.
[192月2024 15:34:17.074] [Netty Client IO #11/DEBUG] [net.minecraftforge.network.ForgePacketHandler/FORGE_PACKET_HANDLER]: Registry load complete, continuing handshake.
[192月2024 15:34:17.075] [Netty Client IO #11/DEBUG] [net.minecraftforge.network.ForgePacketHandler/FORGE_PACKET_HANDLER]: Received config sync from server for forge-server.toml
[192月2024 15:34:17.075] [Netty Client IO #11/DEBUG] [net.minecraftforge.common.ForgeConfig/FORGEMOD]: Forge config just got changed on the file system!
[192月2024 15:34:17.095] [Render thread/INFO] [net.minecraftforge.common.ForgeHooks/]: Connected to a modded server.
[192月2024 15:34:17.143] [Netty Client IO #11/WARN] [oshi.util.FileUtil/]: Configuration conflict: there is more than one oshi.architecture.properties file on the classpath: [jar:file:///C:/Users/ysmre/AppData/Roaming/.minecraft/libraries/com/github/oshi/oshi-core/6.4.5/oshi-core-6.4.5.jar!/oshi.architecture.properties, jar:file:/C:/Users/ysmre/AppData/Roaming/.minecraft/libraries/com/github/oshi/oshi-core/6.4.5/oshi-core-6.4.5.jar!/oshi.architecture.properties, jar:file:///C:/Users/ysmre/AppData/Roaming/.minecraft/libraries/com/github/oshi/oshi-core/6.4.5/oshi-core-6.4.5.jar!/oshi.architecture.properties, jar:file:/C:/Users/ysmre/AppData/Roaming/.minecraft/libraries/com/github/oshi/oshi-core/6.4.5/oshi-core-6.4.5.jar!/oshi.architecture.properties, jar:file:///C:/Users/ysmre/AppData/Roaming/.minecraft/libraries/com/github/oshi/oshi-core/6.4.5/oshi-core-6.4.5.jar!/oshi.architecture.properties, jar:file:/C:/Users/ysmre/AppData/Roaming/.minecraft/libraries/com/github/oshi/oshi-core/6.4.5/oshi-core-6.4.5.jar!/oshi.architecture.properties, jar:file:///C:/Users/ysmre/AppData/Roaming/.minecraft/libraries/com/github/oshi/oshi-core/6.4.5/oshi-core-6.4.5.jar!/oshi.architecture.properties, jar:file:/C:/Users/ysmre/AppData/Roaming/.minecraft/libraries/com/github/oshi/oshi-core/6.4.5/oshi-core-6.4.5.jar!/oshi.architecture.properties]
[192月2024 15:34:17.325] [IO-Worker-6/ERROR] [net.minecraft.Util/]: Caught exception in thread Thread[IO-Worker-6,5,main]
java.lang.NullPointerException: Cannot invoke "net.minecraft.client.multiplayer.MultiPlayerGameMode.m_105295_()" because "p_279248_.f_91072_" is null
	at net.minecraft.client.quickplay.QuickPlayLog.m_278666_(QuickPlayLog.java:72) ~[forge-1.20.4-49.0.19-client.jar!/:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[192月2024 15:34:17.552] [Render thread/WARN] [net.minecraft.client.multiplayer.ClientCommonPacketListenerImpl/]: Client disconnected with reason: Internal Exception: io.netty.handler.codec.DecoderException: java.lang.IndexOutOfBoundsException: readerIndex(1463) + length(1) exceeds writerIndex(1463): PooledUnsafeDirectByteBuf(ridx: 1463, widx: 1463, cap: 1463)
`
It was possible to connect to a regular forge server
![fg1204](https://github.com/MohistMC/Mohist/assets/33682244/8d4d4404-a975-47a5-8c1c-d811f21edf40)

**Comment by ysmreg** [comment]
This is closed due to a bug caused by the mod
