### ISSUE TITLE
[1.20.1] itemsadder plugin error message & texture issue

### ISSUE THREAD

**Issue by Ru-Nan-i** [Teneted/Tenet#2989]
**Minecraft Version :** 1.20.1

**Mohist Version :** 593

**Operating System :** Windows

**Concerned mod / plugin** : ItemsAdder_3.6.3-beta-13

**Logs :** [ItemsAdder] Unhandled exception number 64 occurred in onPacketSending(PacketEvent) for ItemsAdder
java.lang.UnsupportedOperationException: java.lang.ClassCastException: Cannot cast java.lang.String to net.minecraft.network.chat.Component
        at lonelibs.net.kyori.adventure.platform.bukkit.MinecraftComponentSerializerPatched.deserialize(MinecraftComponentSerializerPatched.java:206) ~[?:?]
        at dev.lone.LoneLibs.chat.Comp.nmsToComponent(Comp.java:188) ~[?:?]
        at ia.m.hI.a(SourceFile:24) ~[?:?]
        at ia.m.hG.i(SourceFile:135) ~[?:?]
        at ia.m.hz.onPacketSending(SourceFile:99) ~[?:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:219) ~[?:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokeUnpackedPacketSending(SortedPacketListenerList.java:204) ~[?:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) ~[?:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:139) ~[?:?]
        at com.comphenix.protocol.injector.PacketFilterManager.postPacketToListeners(PacketFilterManager.java:553) ~[?:?]
        at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:526) ~[?:?]
        at com.comphenix.protocol.injector.netty.manager.NetworkManagerInjector.onPacketSending(NetworkManagerInjector.java:100) ~[?:?]
        at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.processOutbound(NettyChannelInjector.java:553) ~[?:?]
        at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector$2.doProxyRunnable(NettyChannelInjector.java:456) ~[?:?]
        at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.proxyRunnable(NettyEventLoopProxy.java:43) ~[?:?]
        at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.execute(NettyEventLoopProxy.java:252) ~[?:?]
        at net.minecraft.network.Connection.handler$zgf000$sendImmediately$rewrite(Connection.java:2105) ~[server-1.20.1-20230612.114412-srg.jar%23266!/:?]
        at net.minecraft.network.Connection.m_129520_(Connection.java:207) ~[server-1.20.1-20230612.114412-srg.jar%23266!/:?]
        at net.minecraft.network.Connection.connectivity$wrapSend(Connection.java:575) ~[server-1.20.1-20230612.114412-srg.jar%23266!/:?]
        at net.minecraft.network.Connection.redirect$zbd000$connectivity$logErrorFor(Connection.java:561) ~[server-1.20.1-20230612.114412-srg.jar%23266!/:?]
        at net.minecraft.network.Connection.m_243124_(Connection.java:197) ~[server-1.20.1-20230612.114412-srg.jar%23266!/:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.m_243119_(ServerGamePacketListenerImpl.java:1719) ~[server-1.20.1-20230612.114412-srg.jar%23266!/:?]
        at net.minecraft.server.level.ServerPlayer.m_240418_(ServerPlayer.java:1637) ~[server-1.20.1-20230612.114412-srg.jar%23266!/:?]
        at net.minecraft.server.level.ServerPlayer.m_213846_(ServerPlayer.java:1631) ~[server-1.20.1-20230612.114412-srg.jar%23266!/:?]
        at org.bukkit.craftbukkit.v1_20_R1.entity.CraftPlayer.sendRawMessage(CraftPlayer.java:261) ~[forge-1.20.1-47.2.20-universal.jar%23271!/:?]
        at org.bukkit.craftbukkit.v1_20_R1.entity.CraftPlayer.sendRawMessage(CraftPlayer.java:251) ~[forge-1.20.1-47.2.20-universal.jar%23271!/:?]
        at org.bukkit.craftbukkit.v1_20_R1.entity.CraftPlayer.sendMessage(CraftPlayer.java:268) ~[forge-1.20.1-47.2.20-universal.jar%23271!/:?]
        at ia.m.qG.j(SourceFile:457) ~[?:?]
        at ia.m.qG.i(SourceFile:430) ~[?:?]
        at ia.m.qG.g(SourceFile:234) ~[?:?]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:78) ~[forge-1.20.1-47.2.20-universal.jar%23271!/:?]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:416) ~[forge-1.20.1-47.2.20-universal.jar%23271!/:?]
        at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:1135) ~[server-1.20.1-20230612.114412-srg.jar%23266!/:?]
        at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:346) ~[server-1.20.1-20230612.114412-srg.jar%23266!/:?]
        at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:1074) ~[server-1.20.1-20230612.114412-srg.jar%23266!/:?]
        at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:904) ~[server-1.20.1-20230612.114412-srg.jar%23266!/:?]
        at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:281) ~[server-1.20.1-20230612.114412-srg.jar%23266!/:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.ClassCastException: Cannot cast java.lang.String to net.minecraft.network.chat.Component
        at java.lang.Class.cast(Class.java:3889) ~[?:?]
        at lonelibs.net.kyori.adventure.platform.bukkit.MinecraftComponentSerializerPatched.deserialize(MinecraftComponentSerializerPatched.java:198) ~[?:?]
        ... 37 more

**Steps to Reproduce :**
 1. Server join, See log
 2. itemsadder(type: REAL_NOTE) block placed on grass block. After a certain period of time, the texture disappears.
 3. ...

**Description of issue :** Give all details about your issue
![2024-03-08_23 22 41](https://github.com/MohistMC/Mohist/assets/75291729/d40bbb1d-3f10-490d-8e72-665a3ff47200)

**Comment by killer2gudpl** [comment]
Same thing.
