### ISSUE TITLE
[1.18.2] Vulcan2.8.6反作弊无法正常启用

### ISSUE THREAD

**Issue by HalfSnowCN** [Teneted/Tenet#2992]
版本：1.18.2 #152

[21:35:31 INFO]: Rainbow0214 issued server command: /vulcan
[21:35:31 ERROR]: null
org.bukkit.command.CommandException: Cannot execute command 'vulcan' in plugin Vulcan v2.8.6 - plugin is disabled.
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:37) ~[forge-1.18.2-40.2.17-universal.jar%23101!/:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:148) ~[forge-1.18.2-40.2.17-universal.jar%23101!/:?]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.dispatchCommand(CraftServer.java:776) ~[forge-1.18.2-40.2.17-universal.jar%23101!/:7e
29f765-296df566-9fb885e8]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.m_9957_(ServerGamePacketListenerImpl.java:1733) ~[server-1.18.2-2022040
4.173914-srg.jar%2396!/:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.m_143628_(ServerGamePacketListenerImpl.java:1661) ~[server-1.18.2-20220
404.173914-srg.jar%2396!/:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.m_7388_(ServerGamePacketListenerImpl.java:1642) ~[server-1.18.2-2022040
4.173914-srg.jar%2396!/:?]
        at net.minecraft.network.protocol.game.ServerboundChatPacket.m_5797_(ServerboundChatPacket.java:35) ~[server-1.18.2-20220404.173914-
srg.jar%2396!/:?]
        at net.minecraft.network.protocol.game.ServerboundChatPacket.m_5797_(ServerboundChatPacket.java:6) ~[server-1.18.2-20220404.173914-s
rg.jar%2396!/:?]
        at net.minecraft.network.protocol.PacketUtils.m_131356_(PacketUtils.java:24) ~[server-1.18.2-20220404.173914-srg.jar%2396!/:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[server-1.18.2-20220404.173914-srg.jar%2396!/:?]
        at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:157) ~[server-1.18.2-20220404.173914-srg.jar%2396!/:
?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[server-1.18.2-20220404.17391
4-srg.jar%2396!/:?]
        at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:1006) ~[server-1.18.2-20220404.173914-srg.jar%2396!/:?]
        at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:168) ~[server-1.18.2-20220404.173914-srg.jar%2396!/:?]
        at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:131) ~[server-1.18.2-20220404.173914-srg.jar%2396!/:
?]
        at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:989) ~[server-1.18.2-20220404.173914-srg.jar%2396!/:?]
        at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:983) ~[server-1.18.2-20220404.173914-srg.jar%2396!/:?]
        at net.minecraft.util.thread.BlockableEventLoop.m_18701_(BlockableEventLoop.java:140) ~[server-1.18.2-20220404.173914-srg.jar%2396!/
:?]
        at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:969) ~[server-1.18.2-20220404.173914-srg.jar%2396!/:?]
        at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:879) ~[server-1.18.2-20220404.173914-srg.jar%2396!/:?]
        at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:287) ~[server-1.18.2-20220404.173914-srg.jar%2396!/:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]

**Comment by 0XPYEX0** [comment]
你这给的全是无效报错
```Cannot execute command 'vulcan' in plugin Vulcan v2.8.6 - plugin is disabled.```
```plugin is disabled.```
从这里就注定你这条没任何用处

请你给出开服时的报错，并且在 **_开头_** 和 **_结尾_** **各**用连续的三个``` ` ```符号括起来

**Comment by HalfSnowCN** [comment]
[latest.log.txt](https://github.com/MohistMC/Mohist/files/14546469/latest.log.txt)
