### ISSUE TITLE
[1.20.1] 无法使用superiorskyblock2插件

### ISSUE THREAD

**Issue by Alirea10** [Teneted/Tenet#2994]
**Minecraft Version :** 1.20.1

**Mohist Version :** mohist-1.20.1-572

**Operating System :** Windows11 23H2

**Concerned mod / plugin** : SuperiorSkyblock2

这是其官网：
https://bg-software.com/superiorskyblock/
这是其源码（值得一提的是他的源码也有很长时间没有更新，但是实际上测试版仍有部分更新。看起来没什么区别因为无论是那一个他都崩）：
https://github.com/BG-Software-LLC/SuperiorSkyblock2
这是下载链接：
稳定版：https://hub.bg-software.com/job/SuperiorSkyblock2%20-%20Stable%20Builds/1/artifact/target/SuperiorSkyblock2-2023.3.jar
测试版：https://hub.bg-software.com/job/SuperiorSkyblock2%20-%20Dev%20Builds/155/artifact/target/SuperiorSkyblock2-2023.3-b155.jar
这两个都是一样的报错

**Logs :** Link(s) of logs and crash reports if you have
```
[16:09:04 INFO]: [SuperiorSkyblock2] Enabling the module bank...
[16:09:04 INFO]: [SuperiorSkyblock2] Finished enabling the module bank (Took 7ms)
[16:09:04 INFO]: [SuperiorSkyblock2] Enabling the module missions...
[16:09:04 INFO]: [SuperiorSkyblock2] Registered mission miner_1
[16:09:04 INFO]: [SuperiorSkyblock2] Registered mission miner_2
[16:09:04 INFO]: [SuperiorSkyblock2] Registered mission miner_3
[16:09:04 INFO]: [SuperiorSkyblock2] Registered mission miner_4
[16:09:04 INFO]: [SuperiorSkyblock2] Registered mission miner_5
[16:09:05 INFO]: [SuperiorSkyblock2] Registered mission slayer_1
[16:09:05 INFO]: [SuperiorSkyblock2] Registered mission slayer_2
[16:09:05 INFO]: [SuperiorSkyblock2] Registered mission slayer_3
[16:09:05 INFO]: [SuperiorSkyblock2] Registered mission slayer_4
[16:09:05 INFO]: [SuperiorSkyblock2] Registered mission farmer_1
[16:09:05 INFO]: [SuperiorSkyblock2] Registered mission farmer_2
[16:09:05 INFO]: [SuperiorSkyblock2] Registered mission farmer_3
[16:09:05 INFO]: [SuperiorSkyblock2] Registered mission farmer_4
[16:09:05 INFO]: [SuperiorSkyblock2] Registered mission farmer_5
[16:09:05 INFO]: [SuperiorSkyblock2] Registered mission fisherman_1
[16:09:05 INFO]: [SuperiorSkyblock2] Registered mission fisherman_2
[16:09:05 INFO]: [SuperiorSkyblock2] Registered mission fisherman_3
[16:09:05 ERROR]: [SuperiorSkyblock2] An unexpected error occurred while enabling the plugin:
[16:09:05 WARN]: java.lang.NoClassDefFoundError: org/spigotmc/CustomTimingsHandler
[16:09:05 WARN]:        at com.bgsoftware.superiorskyblock.missions.island.timings.LegacyTimingsWrapper.<init>(LegacyTimingsWrapper.java:10)
[16:09:05 WARN]:        at com.bgsoftware.superiorskyblock.missions.island.timings.ITimings.of(ITimings.java:15)
[16:09:05 WARN]:        at com.bgsoftware.superiorskyblock.missions.IslandMissions.registerEventListener(IslandMissions.java:100)
[16:09:05 WARN]:        at com.bgsoftware.superiorskyblock.missions.IslandMissions.load(IslandMissions.java:52)
[16:09:05 WARN]:        at com.bgsoftware.superiorskyblock.mission.MissionsManagerImpl.loadMission(MissionsManagerImpl.java:476)
[16:09:05 WARN]:        at com.bgsoftware.superiorskyblock.module.missions.MissionsModule.canLoadCategory(MissionsModule.java:222)
[16:09:05 WARN]:        at com.bgsoftware.superiorskyblock.module.missions.MissionsModule.onEnable(MissionsModule.java:121)
[16:09:05 WARN]:        at com.bgsoftware.superiorskyblock.module.BuiltinModule.onEnable(BuiltinModule.java:24)
[16:09:05 WARN]:        at com.bgsoftware.superiorskyblock.module.ModulesManagerImpl.enableModule(ModulesManagerImpl.java:134)
[16:09:05 WARN]:        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
[16:09:05 WARN]:        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
[16:09:05 WARN]:        at java.base/java.util.LinkedList$LLSpliterator.forEachRemaining(LinkedList.java:1242)
[16:09:05 WARN]:        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
[16:09:05 WARN]:        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
[16:09:05 WARN]:        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
[16:09:05 WARN]:        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
[16:09:05 WARN]:        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[16:09:05 WARN]:        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
[16:09:05 WARN]:        at com.bgsoftware.superiorskyblock.module.ModulesManagerImpl.enableModules(ModulesManagerImpl.java:173)
[16:09:05 WARN]:        at com.bgsoftware.superiorskyblock.SuperiorSkyblockPlugin.reloadPlugin(SuperiorSkyblockPlugin.java:509)
[16:09:05 WARN]:        at com.bgsoftware.superiorskyblock.SuperiorSkyblockPlugin.onEnable(SuperiorSkyblockPlugin.java:237)
[16:09:05 WARN]:        at TRANSFORMER/forge@47.2.20/org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:347)
[16:09:05 WARN]:        at TRANSFORMER/forge@47.2.20/org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:336)
[16:09:05 WARN]:        at TRANSFORMER/forge@47.2.20/org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:482)
[16:09:05 WARN]:        at TRANSFORMER/forge@47.2.20/org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:549)
[16:09:05 WARN]:        at TRANSFORMER/forge@47.2.20/org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:462)
[16:09:05 WARN]:        at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_129815_(MinecraftServer.java:441)
[16:09:05 WARN]:        at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_130006_(MinecraftServer.java:341)
[16:09:05 WARN]:        at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.dedicated.DedicatedServer.m_7038_(DedicatedServer.java:224)
[16:09:05 WARN]:        at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:850)
[16:09:05 WARN]:        at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:281)
[16:09:05 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[16:09:05 WARN]: Caused by: java.lang.ClassNotFoundException: org.spigotmc.CustomTimingsHandler
[16:09:05 WARN]:        at TRANSFORMER/forge@47.2.20/com.mohistmc.bukkit.remapping.RemappingURLClassLoader.findClass(RemappingURLClassLoader.java:98)
[16:09:05 WARN]:        at com.bgsoftware.superiorskyblock.core.io.FileClassLoader.findClass(FileClassLoader.java:94)
[16:09:05 WARN]:        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587)
[16:09:05 WARN]:        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
[16:09:05 WARN]:        ... 32 more
```

**Steps to Reproduce :**
 1. 安装mohist
 2. **仅**添加此插件至plugin
 3. 启动
 4. 出现以上报错并被强制关服

**Description of issue :** Give all details about your issue

**Comment by Mgazul** [comment]
mohist已全面移除了Timings以及相关类
