### ISSUE TITLE
Typewriter PLugin Error

### ISSUE THREAD

**Issue by Unitei-Dev** [Teneted/Tenet#3010]
(https://mclo.gs/BKTyRvG)

**Minecraft Version : 1.20.1

**Mohist Version : mohist-1.20.1-590-server.jar

**Operating System : Linux 

[22:47:49 INFO]: Plugins (34): PlaceholderAPI, TopCollections, PhysicsControl, BetterCallFishing, ProtocolLib, Vault, Resources, WorldEdit, Essentials, (Typewriter), WorldGuard, SCore, MythicMobs, MythicCrucible, RewardSystem, ModelEngine, EssentialsSpawn, MythicDungeons, ValhallaMMO, ExecutableItems, ExecutableBlocks, Oraxen, MythicAchievements, MythicEnchants, TopBossSlayer, RPGRegions, WolfyUtilities, CustomPiglinsTrades, CustomFishing, CustomCrafting, TopMinion, ExecutableEvents, PlugManX (PlugMan), Mohist

[22:36:09] [Server thread/ERROR] [Minecraft]: Error occurred while enabling Typewriter v0.4.2 (Is it up to date?)
java.lang.NoSuchMethodError: 'io.papermc.paper.plugin.configuration.PluginMeta org.bukkit.plugin.Plugin.getPluginMeta()'
	at me.gabber235.typewriter.extensions.placeholderapi.TypewriteExpansion.getVersion(TypewriteExpansion.kt:22) ~[typewriter.jar:?]
	at me.clip.placeholderapi.expansion.manager.LocalExpansionManager.register(LocalExpansionManager.java:301) ~[PlaceholderAPI-2.11.5.jar:?]
	at me.clip.placeholderapi.expansion.PlaceholderExpansion.register(PlaceholderExpansion.java:147) ~[PlaceholderAPI-2.11.5.jar:?]
	at me.gabber235.typewriter.Typewriter.onEnableAsync(Typewriter.kt:104) ~[?:?]
	at com.github.shynixn.mccoroutine.bukkit.SuspendingJavaPlugin$onEnable$1.invokeSuspend(SuspendingJavaPlugin.kt:38) ~[?:?]
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) ~[?:?]
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106) ~[?:?]
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280) ~[?:?]
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85) ~[?:?]
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59) ~[?:?]
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source) ~[?:?]
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38) ~[?:?]
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source) ~[?:?]
	at com.github.shynixn.mccoroutine.bukkit.SuspendingJavaPlugin.onEnable(SuspendingJavaPlugin.kt:37) ~[?:?]
	at lirand.api.architecture.KotlinPlugin.onEnable(KotlinPlugin.kt:13) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:347) ~[forge-1.20.1-47.2.20-universal.jar%23347!/:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:336) ~[forge-1.20.1-47.2.20-universal.jar%23347!/:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:482) ~[forge-1.20.1-47.2.20-universal.jar%23347!/:?]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:549) ~[forge-1.20.1-47.2.20-universal.jar%23347!/:997de31d-ddc9a2dad-d2eba2c8-47.1.79]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:462) ~[forge-1.20.1-47.2.20-universal.jar%23347!/:997de31d-ddc9a2dad-d2eba2c8-47.1.79]
	at net.minecraft.server.MinecraftServer.m_129815_(MinecraftServer.java:441) ~[server-1.20.1-20230612.114412-srg.jar%23342!/:?]
	at net.minecraft.server.MinecraftServer.m_130006_(MinecraftServer.java:341) ~[server-1.20.1-20230612.114412-srg.jar%23342!/:?]
	at net.minecraft.server.dedicated.DedicatedServer.m_7038_(DedicatedServer.java:224) ~[server-1.20.1-20230612.114412-srg.jar%23342!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:848) ~[server-1.20.1-20230612.114412-srg.jar%23342!/:?]
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:281) ~[server-1.20.1-20230612.114412-srg.jar%23342!/:?]
	at java.lang.Thread.run(Thread.java:840) [?:?]
[22:36:09] [Server thread/INFO] [me.gabber235.typewriter.Typewriter]: [Typewriter] Disabling Typewriter v0.4.2

**Comment by Mgazul** [comment]
mohist is not compatible with plugins only used by paper

**Comment by Unitei-Dev** [comment]
okay, thanks
