### ISSUE TITLE
Mohist Server crashes

### ISSUE THREAD

**Issue by nekoniyah** [Teneted/Tenet#3033]
**Minecraft Version :** 1.20.1

**Mohist Version :** # 603

**Operating System :** Windows 11

**Logs :**
``` ███╗   ███╗  ██████╗  ██╗  ██╗ ██╗ ███████╗ ████████╗
 ████╗ ████║ ██╔═══██╗ ██║  ██║ ██║ ██╔════╝ ╚══██╔══╝
 ██╔████╔██║ ██║   ██║ ███████║ ██║ ███████╗    ██║   
 ██║╚██╔╝██║ ██║   ██║ ██╔══██║ ██║ ╚════██║    ██║   
 ██║ ╚═╝ ██║ ╚██████╔╝ ██║  ██║ ██║ ███████║    ██║   
 ╚═╝     ╚═╝  ╚═════╝  ╚═╝  ╚═╝ ╚═╝ ╚══════╝    ╚═╝   
Thanks for using Mohist - 1.20.1-638, Java(17.0.10) 61.0 PID: 1
Update in check...
If you don't want to enable update check, set check_update in mohist-config/mohist.yml to false
The latest Mohist version is 639 but you have 638. The latest version has been built on 2024-03-26 06:34:46. You should update to fix recent bugs!
Checking libraries, please wait...
All libraries are nice :)!
Searching incompatible mods...
[20:04:30 INFO]: ModLauncher running: args [--launchTarget, forgeserver, --fml.forgeVersion, 47.2.21, --fml.mcVersion, 1.20.1, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20230612.114412]
[20:04:30 INFO]: ModLauncher 10.0.9+10.0.9+main.dcd20f30 starting: java version 17.0.10 by Eclipse Adoptium; OS Linux arch amd64 version 5.4.0-163-generic
[20:04:32 INFO]: ImmediateWindowProvider not loading because launch target is forgeserver
[20:04:32 INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/home/container/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar%23111!/ Service=ModLauncher Env=SERVER
[20:04:33 WARN]: Attempted to select two dependency jars from JarJar which have the same identification: Mod File:  and Mod File: . Using Mod File: 
[20:04:33 INFO]: Found 13 dependencies adding them to mods collection
[20:04:37 INFO]: Compatibility level set to JAVA_17
[20:04:37 INFO]: Successfully loaded Mixin Connector [com.sonicether.soundphysics.MixinConnector]
[20:04:37 INFO]: Launching target 'forgeserver' with arguments []
[20:04:38 WARN]: Reference map 'EpheroLib-refmap.json' for epherolib.mixins.json could not be read. If this is a development environment you can ignore this message
[20:04:38 WARN]: Reference map 'dummmmmmy-forge-refmap.json' for dummmmmmy.mixins.json could not be read. If this is a development environment you can ignore this message
[20:04:38 WARN]: Reference map 'cristellib-forge-refmap.json' for cristellib.mixins.json could not be read. If this is a development environment you can ignore this message
[20:04:42 INFO]: Initializing MixinExtras via com.llamalad7.mixinextras.service.MixinExtrasServiceImpl(version=0.3.5).
Exception in thread "main" java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:32)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.run(Launcher.java:108)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.main(Launcher.java:78)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
        at cpw.mods.bootstraplauncher@1.1.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141)
        at com.mohistmc.MohistMCStart.main(MohistMCStart.java:108)
Caused by: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at MC-BOOTSTRAP/fmlloader@1.20.1-47.2.21/net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111)
        at MC-BOOTSTRAP/fmlloader@1.20.1-47.2.21/net.minecraftforge.fml.loading.targets.CommonLaunchHandler.serverService(CommonLaunchHandler.java:103)
        at MC-BOOTSTRAP/fmlloader@1.20.1-47.2.21/net.minecraftforge.fml.loading.targets.CommonServerLaunchHandler.lambda$makeService$0(CommonServerLaunchHandler.java:27)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30)
        ... 8 more
Caused by: java.lang.NoClassDefFoundError: net/minecraft/world/inventory/EnchantmentMenu
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.block.Blocks.<clinit>(Blocks.java:410)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.block.FireBlock.m_53484_(FireBlock.java:366)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.Bootstrap.m_135870_(Bootstrap.java:46)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.Main.main(Main.java:161)
        ... 16 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.world.inventory.EnchantmentMenu
        at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:157)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
        ... 20 more
```

**Mod list :**
![explorer_PjEIF5AvOk](https://github.com/MohistMC/Mohist/assets/114854571/59c5f497-b6a0-4b5e-b65e-def67c31dda1)
![explorer_Bq9VU6qLHK](https://github.com/MohistMC/Mohist/assets/114854571/36135c54-1342-469e-ba82-d17f52fb50da)
![explorer_KBvsehPMjK](https://github.com/MohistMC/Mohist/assets/114854571/4e64ff0f-a7c1-47b3-bd10-db6d494d2755)
![explorer_19odYQa2CU](https://github.com/MohistMC/Mohist/assets/114854571/1c778c9e-8c67-45ce-bb81-e4bbc946693e)

**Plugin list :**

![chrome_CUB7DyLMes](https://github.com/MohistMC/Mohist/assets/114854571/c03a97bc-f25e-4a0e-91d0-1d37e68fdcc0)

**Description of issue :** The server crashed on start up

**Comment by 1265775896** [comment]
Same here, I found it's pmmo's fault
