### ISSUE TITLE
[1.20.1] Cannot setup a new server

### ISSUE THREAD

**Issue by nschudlo** [Teneted/Tenet#3036]
**Minecraft Version :** 1.20.1

**Mohist Version :** 603

**Operating System :** Windows 10

**Mod list :** None

**Plugin list :** None

**Description of issue :** 
When following the instructions to start a new server on the ['Install Mohist on Windows' page](https://mohistmc.com/mohist/docs/installation/windows), I run into an issue almost immediately:

```
 ███╗   ███╗  ██████╗  ██╗  ██╗ ██╗ ███████╗ ████████╗
 ████╗ ████║ ██╔═══██╗ ██║  ██║ ██║ ██╔════╝ ╚══██╔══╝
 ██╔████╔██║ ██║   ██║ ███████║ ██║ ███████╗    ██║
 ██║╚██╔╝██║ ██║   ██║ ██╔══██║ ██║ ╚════██║    ██║
 ██║ ╚═╝ ██║ ╚██████╔╝ ██║  ██║ ██║ ███████║    ██║
 ╚═╝     ╚═╝  ╚═════╝  ╚═╝  ╚═╝ ╚═╝ ╚══════╝    ╚═╝

Thanks for using Mohist - 1.20.1-639, Java(17.0.10) 61.0 PID: 22284
Update in check...
If you don't want to enable update check, set check_update in mohist-config/mohist.yml to false
No update found, latest version: (639) current version: (639)
Checking libraries, please wait...
DownloadSource: MOHISTMC
Download percentage:
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "java.lang.Boolean.booleanValue()" because "this.jna" is null
        at org.jline.terminal.TerminalBuilder.doBuild(TerminalBuilder.java:443)
        at org.jline.terminal.TerminalBuilder.build(TerminalBuilder.java:362)
        at me.tongfei.progressbar.TerminalUtils.getTerminal(TerminalUtils.java:83)
        at me.tongfei.progressbar.TerminalUtils.hasCursorMovementSupport(TerminalUtils.java:37)
        at me.tongfei.progressbar.Util.createConsoleConsumer(Util.java:30)
        at me.tongfei.progressbar.Util.createConsoleConsumer(Util.java:22)
        at me.tongfei.progressbar.ProgressBarBuilder.build(ProgressBarBuilder.java:136)
        at com.mohistmc.libraries.LibrariesDownloadQueue.progressBar(LibrariesDownloadQueue.java:124)
        at com.mohistmc.feature.DefaultLibraries.run(DefaultLibraries.java:50)
        at com.mohistmc.MohistMCStart.main(MohistMCStart.java:77)
```

**Comment by nschudlo** [comment]
This seems related https://github.com/jline/jline3/issues/930, and looks like it was fixed in 3.25.1
