### ISSUE TITLE
[1.20.1] Spigot library loader does not work correctly

### ISSUE THREAD

**Issue by wtlgo** [Teneted/Tenet#3052]
**Minecraft Version :** 1.20.1

**Mohist Version :** 1.20.1-656, Java(17.0.1) 61.0 PID: 11696 / Build 620

**Operating System :** Windows 10

**Logs :** [latest.log](https://haste.mohistmc.com/ajojofogaw.sql)

**Mod list :** `/getmodlist` doesn't work, so here is `/mohist mods` instead
```log
[12:02:24 INFO]: Inside mods: (3) -> [mohist, forge, minecraft]
[12:02:24 INFO]: Client-only mods: (0) -> []
[12:02:24 INFO]: Server-only mods: (0) -> []
[12:02:24 INFO]: All mods: (3) -> [minecraft, forge, mohist]
```

**Plugin list :** https://haste.mohistmc.com/epefafiviw

**Description of issue :** 
It appears to me that the spigot library loader works weirdly in the last build of Mohist. E.g. [my plugin](https://www.spigotmc.org/resources/mikchan%E3%81%AEchat.103501/): 
```log
[11:57:10] [Server thread/INFO] [com.mohistmc.MohistMC]: [MikChanNoChat] Loading 2 libraries... please wait
[11:57:11] [Server thread/ERROR] [Minecraft]: Could not load 'plugins\s-MCnChat-103501-501860.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.RuntimeException: java.io.FileNotFoundException: https://repo.maven.apache.org/maven2/org/jetbrains/annotations/13/annotations-13.pom
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:149) ~[forge-1.20.1-47.2.23-universal.jar%23195!/:?]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:396) ~[forge-1.20.1-47.2.23-universal.jar%23195!/:?]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:304) ~[forge-1.20.1-47.2.23-universal.jar%23195!/:?]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.loadPlugins(CraftServer.java:436) ~[forge-1.20.1-47.2.23-universal.jar%23195!/:997de31d-ddc9a2dad-d2eba2c8-47.1.79]
	at net.minecraft.server.dedicated.DedicatedServer.m_7038_(DedicatedServer.java:216) ~[server-1.20.1-20230612.114412-srg.jar%23190!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:848) ~[server-1.20.1-20230612.114412-srg.jar%23190!/:?]
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:281) ~[server-1.20.1-20230612.114412-srg.jar%23190!/:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.RuntimeException: java.io.FileNotFoundException: https://repo.maven.apache.org/maven2/org/jetbrains/annotations/13/annotations-13.pom
	at mjson.Json.fetchContent(Json.java:298) ~[json-0.2.jar%23142!/:?]
	at mjson.Json.readXml(Json.java:525) ~[json-0.2.jar%23142!/:?]
	at org.bukkit.plugin.java.LibraryLoader.initDependencies(LibraryLoader.java:129) ~[forge-1.20.1-47.2.23-universal.jar%23195!/:?]
	at org.bukkit.plugin.java.LibraryLoader.initDependencies0(LibraryLoader.java:121) ~[forge-1.20.1-47.2.23-universal.jar%23195!/:?]
	at org.bukkit.plugin.java.LibraryLoader.createLoader(LibraryLoader.java:65) ~[forge-1.20.1-47.2.23-universal.jar%23195!/:?]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:145) ~[forge-1.20.1-47.2.23-universal.jar%23195!/:?]
	... 7 more
Caused by: java.io.FileNotFoundException: https://repo.maven.apache.org/maven2/org/jetbrains/annotations/13/annotations-13.pom
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1993) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589) ~[?:?]
	at java.net.URLConnection.getContent(URLConnection.java:753) ~[?:?]
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getContent(HttpsURLConnectionImpl.java:404) ~[?:?]
	at java.net.URL.getContent(URL.java:1175) ~[?:?]
	at mjson.Json.fetchContent(Json.java:291) ~[json-0.2.jar%23142!/:?]
	at mjson.Json.readXml(Json.java:525) ~[json-0.2.jar%23142!/:?]
	at org.bukkit.plugin.java.LibraryLoader.initDependencies(LibraryLoader.java:129) ~[forge-1.20.1-47.2.23-universal.jar%23195!/:?]
	at org.bukkit.plugin.java.LibraryLoader.initDependencies0(LibraryLoader.java:121) ~[forge-1.20.1-47.2.23-universal.jar%23195!/:?]
	at org.bukkit.plugin.java.LibraryLoader.createLoader(LibraryLoader.java:65) ~[forge-1.20.1-47.2.23-universal.jar%23195!/:?]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:145) ~[forge-1.20.1-47.2.23-universal.jar%23195!/:?]
	... 7 more
```

The correct URL must be `https://repo.maven.apache.org/maven2/org/jetbrains/annotations/13.0/annotations-13.0.pom`, but it tries to fetch `https://repo.maven.apache.org/maven2/org/jetbrains/annotations/13/annotations-13.pom` instead.

Spigot and paper on the other hand handle it correctly.

**Comment by wtlgo** [comment]
P.S. Tested on older version `Mohist - 1.20.1-637, Java(17.0.1) 61.0 PID: 18888 / Build 601`, and the same plugin loads correctly.
Something must have broken between build 601 and 620

**Comment by wtlgo** [comment]
Damn, this was quick. @Mgazul, you're a magician
