### ISSUE TITLE
[1.20.1] ItemsAdder not loading

### ISSUE THREAD

**Issue by ZARAEM** [Teneted/Tenet#3056]
1.20.1

Banner 569

**Operating System :** Debian

**Concerned mod / plugin** : ItemsAdder Plugin

**Logs :**
[22:42:24] [Server thread/ERROR]: Could not load 'plugins/[DL]-ItemsAdder_3.6.3-beta-13(1).jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.NullPointerException: Cannot invoke "com.mohistmc.mjson.Json.has(String)" because "json2Json" is null
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:152) ~[banner-1.20.1-569-server.jar:?]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:396) ~[banner-1.20.1-569-server.jar:?]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:303) ~[banner-1.20.1-569-server.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.loadPlugins(CraftServer.java:434) ~[banner-1.20.1-569-server.jar:?]
        at net.minecraft.server.dedicated.DedicatedServer.handler$zdd000$banner$initServer(DedicatedServer.java:686) ~[server-intermediary.jar:?]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:166) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:2069) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:265) ~[server-intermediary.jar:?]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "com.mohistmc.mjson.Json.has(String)" because "json2Json" is null
        at org.bukkit.plugin.java.LibraryLoader.initDependencies(LibraryLoader.java:133) ~[banner-1.20.1-569-server.jar:?]
        at org.bukkit.plugin.java.LibraryLoader.initDependencies0(LibraryLoader.java:118) ~[banner-1.20.1-569-server.jar:?]
        at org.bukkit.plugin.java.LibraryLoader.createLoader(LibraryLoader.java:67) ~[banner-1.20.1-569-server.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:147) ~[banner-1.20.1-569-server.jar:?]
        ... 8 more

**Steps to Reproduce :**
 1. Load Server

Cannot load plugin b/c of org.bukkit.plugin.InvalidPluginException: java.lang.NullPointerException: Cannot invoke "com.mohistmc.mjson.Json.has(String)" because "json2Json" is null

**Comment by Mgazul** [comment]
Please do not report banner errors on mohist

**Comment by ZARAEM** [comment]
Same error is present on latest mohist build

**Comment by Mgazul** [comment]
> Same error is present on latest mohist build

That should send mohist's error message instead of banner's

**Comment by ZARAEM** [comment]
> > Same error is present on latest mohist build
> 
> That should send mohist's error message instead of banner's

Here is the error on mohist:

[23:20:09 ERROR]: bootstrap method initialization exception initializing ItemsAdder v3.6.3-beta-13 (Is it up to date?)
java.lang.BootstrapMethodError: bootstrap method initialization exception
        at java.lang.invoke.BootstrapMethodInvoker.invoke(BootstrapMethodInvoker.java:188) ~[?:?]
        at java.lang.invoke.CallSite.makeSite(CallSite.java:316) ~[?:?]
        at java.lang.invoke.MethodHandleNatives.linkCallSiteImpl(MethodHandleNatives.java:274) ~[?:?]
        at java.lang.invoke.MethodHandleNatives.linkCallSite(MethodHandleNatives.java:264) ~[?:?]
        at dev.lone.itemsadder.Main.onLoad(SourceFile:180) ~[?:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.loadPlugins(CraftServer.java:441) ~[forge-1.20.1-47.2.23-universal.jar%23195!/:997de31d-ddc9a2dad-d2eba2c8-47.1.79]
        at net.minecraft.server.dedicated.DedicatedServer.m_7038_(DedicatedServer.java:216) ~[server-1.20.1-20230612.114412-srg.jar%23190!/:?]
        at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:848) ~[server-1.20.1-20230612.114412-srg.jar%23190!/:?]
        at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:281) ~[server-1.20.1-20230612.114412-srg.jar%23190!/:?]
        at java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "String.toCharArray()" because "v80PDirecDQSAC4iSdeaks1utdgXL3sX0u0oKrU9G.C9vxJkWNBNMZm2aUg" is null
        at v80PDirecDQSAC4iSdeaks1utdgXL3sX0u0oKrU9G.yVAtiiQEHG(v80PDirecDQSAC4iSdeaks1utdgXL3sX0u0oKrU9G.java) ~[?:?]
        at java.lang.invoke.BootstrapMethodInvoker.invoke(BootstrapMethodInvoker.java:170) ~[?:?]
        ... 9 more
        
        
        
        
        
        
        sorry, mohist is a different error

**Comment by Mgazul** [comment]
> > > Same error is present on latest mohist build
> > 
> > 
> > That should send mohist's error message instead of banner's
> 
> Here is the error on mohist:
> 
> [23:20:09 ERROR]: bootstrap method initialization exception initializing ItemsAdder v3.6.3-beta-13 (Is it up to date?) java.lang.BootstrapMethodError: bootstrap method initialization exception at java.lang.invoke.BootstrapMethodInvoker.invoke(BootstrapMethodInvoker.java:188) ~[?:?] at java.lang.invoke.CallSite.makeSite(CallSite.java:316) ~[?:?] at java.lang.invoke.MethodHandleNatives.linkCallSiteImpl(MethodHandleNatives.java:274) ~[?:?] at java.lang.invoke.MethodHandleNatives.linkCallSite(MethodHandleNatives.java:264) ~[?:?] at dev.lone.itemsadder.Main.onLoad(SourceFile:180) ~[?:?] at org.bukkit.craftbukkit.v1_20_R1.CraftServer.loadPlugins(CraftServer.java:441) ~[forge-1.20.1-47.2.23-universal.jar%23195!/:997de31d-ddc9a2dad-d2eba2c8-47.1.79] at net.minecraft.server.dedicated.DedicatedServer.m_7038_(DedicatedServer.java:216) ~[server-1.20.1-20230612.114412-srg.jar%23190!/:?] at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:848) ~[server-1.20.1-20230612.114412-srg.jar%23190!/:?] at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:281) ~[server-1.20.1-20230612.114412-srg.jar%23190!/:?] at java.lang.Thread.run(Thread.java:1583) [?:?] Caused by: java.lang.NullPointerException: Cannot invoke "String.toCharArray()" because "v80PDirecDQSAC4iSdeaks1utdgXL3sX0u0oKrU9G.C9vxJkWNBNMZm2aUg" is null at v80PDirecDQSAC4iSdeaks1utdgXL3sX0u0oKrU9G.yVAtiiQEHG(v80PDirecDQSAC4iSdeaks1utdgXL3sX0u0oKrU9G.java) ~[?:?] at java.lang.invoke.BootstrapMethodInvoker.invoke(BootstrapMethodInvoker.java:170) ~[?:?] ... 9 more
> 
> ```
>     sorry, mohist is a different error
> ```

Your ItemsAdder plug-in does not seem to be official. The plug-in bytecode has been modified.
