### ISSUE TITLE
WorldEdit & Worldguard

### ISSUE THREAD

**Issue by idunnoooooo** [Teneted/Tenet#307]
So when im using worldedit and worldguard plugins they work but u can't do anything with modded blocks using worldedit so i wanna use forge version of worldedit but then worldguard doesn't start cause worldedit plugin is required.

**Comment by Mgazul** [comment]
https://github.com/Mohist-Community/WorldEdit/releases/download/6.1.9/WorldEdit-6.1.9-SNAPSHOT-all.jar

**Comment by idunnoooooo** [comment]
@Mgazul it doesn't work. Unknown Command //wand etc

**Comment by Mgazul** [comment]
I only tested //set and //copy

**Comment by idunnoooooo** [comment]
@Mgazul i can't even make selection with wooden axe

**Comment by Mgazul** [comment]
Works for me

**Comment by idunnoooooo** [comment]
its a plugin or mod?

**Comment by Mgazul** [comment]
plugin

**Comment by idunnoooooo** [comment]
idk then. it doesn't show in /pl well i think i will just live with it.

**Comment by Mgazul** [comment]
![image](https://user-images.githubusercontent.com/23317456/83286849-3a097c80-a213-11ea-8063-a22518aadcab.png)

**Comment by idunnoooooo** [comment]
[16:57:03] [Server thread/ERROR] [Mohist]: Could not load plugins/WorldEdit-6.1.9-SNAPSHOT-all.jar in folder plugins because plugin invalid
org.bukkit.plugin.InvalidPluginException: java.lang.IllegalStateException: JavaPlugin requires org.bukkit.plugin.java.PluginClassLoader
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:130) ~[JavaPluginLoader.class:1.12.2-804c3e5]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:323) ~[SimplePluginManager.class:1.12.2-804c3e5]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:245) [SimplePluginManager.class:1.12.2-804c3e5]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.loadPlugins(CraftServer.java:389) [CraftServer.class:1.12.2-804c3e5]
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:341) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:316) [nz.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:590) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
Caused by: java.lang.IllegalStateException: JavaPlugin requires org.bukkit.plugin.java.PluginClassLoader
	at org.bukkit.plugin.java.JavaPlugin.<init>(JavaPlugin.java:48) ~[JavaPlugin.class:1.12.2-804c3e5]
	at com.sk89q.worldedit.bukkit.WorldEditPlugin.<init>(WorldEditPlugin.java:79) ~[WorldEditPlugin.class:?]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_252]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_252]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_252]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_252]
	at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_252]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:66) ~[PluginClassLoader.class:1.12.2-804c3e5]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:126) ~[JavaPluginLoader.class:1.12.2-804c3e5]
	... 7 more

**Comment by Mgazul** [comment]
Check if your jar is damaged

**Comment by idunnoooooo** [comment]
downloaded this jar 4 times already all got same error

**Comment by idunnoooooo** [comment]
Updating Mohist fixed this. Thanks so much!
