### ISSUE TITLE
[1.20.1] WorldGuard Candle_cake

### ISSUE THREAD

**Issue by MRMStudios** [Teneted/Tenet#3073]
**Minecraft Version :** 1.20.1

**Mohist Version :** 580 and more

**Operating System :** Linux

**Concerned mod / plugin** : Worldguard 

**Logs :**<html>
<body>

[00:02:30] [Server thread/ERROR] [Minecraft]: Could not pass event UseBlockEvent to WorldGuard v7.0.9+5934e49
--
274 | org.bukkit.event.EventException: null
275 | at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:304) ~[forge-1.20.1-47.2.23-universal.jar%231005!/:?]
276 | at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[forge-1.20.1-47.2.23-universal.jar%231005!/:?]
277 | at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:602) ~[forge-1.20.1-47.2.23-universal.jar%231005!/:?]
278 | at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:586) ~[forge-1.20.1-47.2.23-universal.jar%231005!/:?]
279 | at com.sk89q.worldguard.bukkit.util.Events.fireAndTestCancel(Events.java:60) ~[?:?]
280 | at com.sk89q.worldguard.bukkit.listener.EventAbstractionListener.onPlayerInteract(EventAbstractionListener.java:509) ~[?:?]
281 | at jdk.internal.reflect.GeneratedMethodAccessor256.invoke(Unknown Source) ~[?:?]
282 | at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
283 | at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
284 | at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[forge-1.20.1-47.2.23-universal.jar%231005!/:?]
285 | at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[forge-1.20.1-47.2.23-universal.jar%231005!/:?]
286 | at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:602) ~[forge-1.20.1-47.2.23-universal.jar%231005!/:?]
287 | at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:586) ~[forge-1.20.1-47.2.23-universal.jar%231005!/:?]
288 | at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:555) ~[forge-1.20.1-47.2.23-universal.jar%231005!/:?]
289 | at net.minecraft.server.level.ServerPlayerGameMode.m_7179_(ServerPlayerGameMode.java:439) ~[server-1.20.1-20230612.114412-srg.jar%231000!/:?]
290 | at net.minecraft.server.network.ServerGamePacketListenerImpl.m_6371_(ServerGamePacketListenerImpl.java:1589) ~[server-1.20.1-20230612.114412-srg.jar%231000!/:?]
291 | at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.m_5797_(ServerboundUseItemOnPacket.java:34) ~[server-1.20.1-20230612.114412-srg.jar%231000!/:?]
292 | at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.m_5797_(ServerboundUseItemOnPacket.java:8) ~[server-1.20.1-20230612.114412-srg.jar%231000!/:?]
293 | at net.minecraft.network.protocol.PacketUtils.m_263899_(PacketUtils.java:25) ~[server-1.20.1-20230612.114412-srg.jar%231000!/:?]
294 | at net.minecraft.server.TickTask.run(TickTask.java:18) ~[server-1.20.1-20230612.114412-srg.jar%231000!/:?]
295 | at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:151) ~[server-1.20.1-20230612.114412-srg.jar%231000!/:?]
296 | at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[server-1.20.1-20230612.114412-srg.jar%231000!/:?]
297 | at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:1027) ~[server-1.20.1-20230612.114412-srg.jar%231000!/:?]
298 | at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:173) ~[server-1.20.1-20230612.114412-srg.jar%231000!/:?]
299 | at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:124) ~[server-1.20.1-20230612.114412-srg.jar%231000!/:?]
300 | at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:1010) ~[server-1.20.1-20230612.114412-srg.jar%231000!/:?]
301 | at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:1004) ~[server-1.20.1-20230612.114412-srg.jar%231000!/:?]
302 | at net.minecraft.util.thread.BlockableEventLoop.m_18699_(BlockableEventLoop.java:112) ~[server-1.20.1-20230612.114412-srg.jar%231000!/:?]
303 | at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:989) ~[server-1.20.1-20230612.114412-srg.jar%231000!/:?]
304 | at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:906) ~[server-1.20.1-20230612.114412-srg.jar%231000!/:?]
305 | at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:281) ~[server-1.20.1-20230612.114412-srg.jar%231000!/:?]
306 | at java.lang.Thread.run(Thread.java:833) [?:?]
307 | Caused by: java.lang.NullPointerException: Cannot invoke "org.bukkit.Tag.isTagged(org.bukkit.Keyed)" because "org.bukkit.Tag.CANDLE_CAKES" is null
308 | at com.sk89q.worldguard.bukkit.util.Materials.isConsideredBuildingIfUsed(Materials.java:1346) ~[?:?]
309 | at com.sk89q.worldguard.bukkit.listener.RegionProtectionListener.lambda$onUseBlock$2(RegionProtectionListener.java:256) ~[?:?]
310 | at com.google.common.base.Predicate.test(Predicate.java:81) ~[guava-31.1-jre.jar%23151!/:?]
311 | at com.sk89q.worldguard.bukkit.event.block.AbstractBlockEvent.filterInternal(AbstractBlockEvent.java:132) ~[?:?]
312 | at com.sk89q.worldguard.bukkit.event.block.AbstractBlockEvent.filter(AbstractBlockEvent.java:124) ~[?:?]
313 | at com.sk89q.worldguard.bukkit.event.block.UseBlockEvent.filter(UseBlockEvent.java:39) ~[?:?]
314 | at com.sk89q.worldguard.bukkit.event.block.AbstractBlockEvent.filter(AbstractBlockEvent.java:160) ~[?:?]
315 | at com.sk89q.worldguard.bukkit.event.block.UseBlockEvent.filter(UseBlockEvent.java:39) ~[?:?]
316 | at com.sk89q.worldguard.bukkit.listener.RegionProtectionListener.onUseBlock(RegionProtectionListener.java:251) ~[?:?]
317 | at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
318 | at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
319 | at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
320 | at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
321 | at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[forge-1.20.1-47.2.23-universal.jar%231005!/:?]
322 | ... 31 more

</body>
</html>

**Steps to Reproduce :**
 1. Place a candle
 2. Place a cake on candle
 3. ensure yo dont have permission in region
 4. Eat cake, itll break the candle and eat a chunk of cake, throw the error, and allow you to eat the cake.

**Description of issue :** Give all details about your issue
[00:02:30] [Server thread/ERROR] [Minecraft]: Could not pass event UseBlockEvent to WorldGuard v7.0.9+5934e49
org.bukkit.event.EventException: null
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:304) ~[forge-1.20.1-47.2.23-universal.jar%231005!/:?]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[forge-1.20.1-47.2.23-universal.jar%231005!/:?]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:602) ~[forge-1.20.1-47.2.23-universal.jar%231005!/:?]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:586) ~[forge-1.20.1-47.2.23-universal.jar%231005!/:?]
at com.sk89q.worldguard.bukkit.util.Events.fireAndTestCancel(Events.java:60) ~[?:?]
at com.sk89q.worldguard.bukkit.listener.EventAbstractionListener.onPlayerInteract(EventAbstractionListener.java:509) ~[?:?]
at jdk.internal.reflect.GeneratedMethodAccessor256.invoke(Unknown Source) ~[?:?]
at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[forge-1.20.1-47.2.23-universal.jar%231005!/:?]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[forge-1.20.1-47.2.23-universal.jar%231005!/:?]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:602) ~[forge-1.20.1-47.2.23-universal.jar%231005!/:?]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:586) ~[forge-1.20.1-47.2.23-universal.jar%231005!/:?]
at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:555) ~[forge-1.20.1-47.2.23-universal.jar%231005!/:?]
at net.minecraft.server.level.ServerPlayerGameMode.m_7179_(ServerPlayerGameMode.java:439) ~[server-1.20.1-20230612.114412-srg.jar%231000!/:?]
at net.minecraft.server.network.ServerGamePacketListenerImpl.m_6371_(ServerGamePacketListenerImpl.java:1589) ~[server-1.20.1-20230612.114412-srg.jar%231000!/:?]
at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.m_5797_(ServerboundUseItemOnPacket.java:34) ~[server-1.20.1-20230612.114412-srg.jar%231000!/:?]
at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.m_5797_(ServerboundUseItemOnPacket.java:8) ~[server-1.20.1-20230612.114412-srg.jar%231000!/:?]
at net.minecraft.network.protocol.PacketUtils.m_263899_(PacketUtils.java:25) ~[server-1.20.1-20230612.114412-srg.jar%231000!/:?]
at net.minecraft.server.TickTask.run(TickTask.java:18) ~[server-1.20.1-20230612.114412-srg.jar%231000!/:?]
at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:151) ~[server-1.20.1-20230612.114412-srg.jar%231000!/:?]
at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[server-1.20.1-20230612.114412-srg.jar%231000!/:?]
at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:1027) ~[server-1.20.1-20230612.114412-srg.jar%231000!/:?]
at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:173) ~[server-1.20.1-20230612.114412-srg.jar%231000!/:?]
at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:124) ~[server-1.20.1-20230612.114412-srg.jar%231000!/:?]
at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:1010) ~[server-1.20.1-20230612.114412-srg.jar%231000!/:?]
at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:1004) ~[server-1.20.1-20230612.114412-srg.jar%231000!/:?]
at net.minecraft.util.thread.BlockableEventLoop.m_18699_(BlockableEventLoop.java:112) ~[server-1.20.1-20230612.114412-srg.jar%231000!/:?]
at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:989) ~[server-1.20.1-20230612.114412-srg.jar%231000!/:?]
at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:906) ~[server-1.20.1-20230612.114412-srg.jar%231000!/:?]
at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:[281](https://log.mtxserv.com/xC7qrnk#L281)) ~[server-1.20.1-20230612.114412-srg.jar%231000!/:?]
at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "org.bukkit.Tag.isTagged(org.bukkit.Keyed)" because "org.bukkit.Tag.CANDLE_CAKES" is null
at com.sk89q.worldguard.bukkit.util.Materials.isConsideredBuildingIfUsed(Materials.java:1346) ~[?:?]
at com.sk89q.worldguard.bukkit.listener.RegionProtectionListener.lambda$onUseBlock$2(RegionProtectionListener.java:256) ~[?:?]
at com.google.common.base.Predicate.test(Predicate.java:81) ~[guava-31.1-jre.jar%23151!/:?]
at com.sk89q.worldguard.bukkit.event.block.AbstractBlockEvent.filterInternal(AbstractBlockEvent.java:132) ~[?:?]
at com.sk89q.worldguard.bukkit.event.block.AbstractBlockEvent.filter(AbstractBlockEvent.java:124) ~[?:?]
at com.sk89q.worldguard.bukkit.event.block.UseBlockEvent.filter(UseBlockEvent.java:39) ~[?:?]
at com.sk89q.worldguard.bukkit.event.block.AbstractBlockEvent.filter(AbstractBlockEvent.java:160) ~[?:?]
at com.sk89q.worldguard.bukkit.event.block.UseBlockEvent.filter(UseBlockEvent.java:39) ~[?:?]
at com.sk89q.worldguard.bukkit.listener.RegionProtectionListener.onUseBlock(RegionProtectionListener.java:251) ~[?:?]
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[forge-1.20.1-47.2.23-universal.jar%231005!/:?]
... 31 more

**Comment by Mgazul** [comment]
The problem cannot be reproduced

**Comment by Caishangqi** [comment]
same problem, setting flag use deny will generate this error
