### ISSUE TITLE
Object2ObjectLinkedOpenHashMap cannot be cast to class ImmutableMap$Builder

### ISSUE THREAD

**Issue by Magi1053** [Teneted/Tenet#3075]
**Minecraft Version :** 1.20.1

**Mohist Version :** 673

**Operating System :** Linux

<details>
  <summary><b>Mod List</b></summary>
  
	- ad_astra 1.15.18
	- ad_astra__extra_additions 1.1.1
	- ad_astra_giselle_addon 6.5
	- advancedperipherals 0.7.38r
	- ae2 15.1.0
	- ae2insertexportcard 1.20.1-1.2.1
	- ae2wtlib 15.2.3-forge
	- aecapfix 0.8
	- aeinfinitybooster 1.20.1-1.0.0+20
	- aiimprovements 0.5.2
	- all_bark_all_bite 1.20.1-1.0.2
	- amendments 1.20-1.1.11
	- apotheosis 7.3.4
	- apotheoticcreation 1.0.0
	- aquaculture 2.5.1
	- aquatictorches 1.1.1
	- architectury 9.2.14
	- ars_artifice 1.20.1-2.0.4
	- ars_creo 4.0.1
	- ars_nouveau 4.9.0
	- arseng 1.1.5
	- astikorcarts 1.1.7
	- attributeslib 1.3.4
	- backhome 0.1.1
	- badpackets 0.4.3
	- balm 7.2.2
	- barkoplenty 1.0.0
	- bclib 3.0.14
	- beautify 2.0.2
	- beekeeperhut 2.0.0
	- betterdeserttemples 1.20-Forge-3.0.3
	- betterdungeons 1.20-Forge-4.0.3
	- betterend 4.0.11
	- betterendisland 1.20-Forge-2.0.6
	- betterfortresses 1.20-Forge-2.0.6
	- betterjungletemples 1.20-Forge-2.0.4
	- bettermineshafts 1.20-Forge-4.0.4
	- betternether 9.0.10
	- betteroceanmonuments 1.20-Forge-3.0.4
	- betterstrongholds 1.20-Forge-4.0.3
	- betterwitchhuts 1.20-Forge-3.0.3
	- biomesoplenty 18.0.0.598
	- bloodmagic 3.3.2-44
	- bluemap 3.20
	- bookshelf 20.1.9
	- botania 1.20.1-443-FORGE
	- botarium 2.3.3
	- caelus 3.1.0+1.20
	- carryon 2.1.2.7
	- cccbridge 1.6.3-forge
	- charmofundying 6.5.0+1.20.1
	- chefsdelight 1.0.3-forge-1.20.1
	- cloth_config 11.1.118
	- clumps 12.0.0.3
	- collective 7.40
	- computercraft 1.110.1
	- connectivity 1.20.1-5.5
	- connectormod 1.0.0-beta.40+1.20.1
	- consolefilter 1.20.1-2.0.0
	- cookingforblockheads 16.0.3
	- corpse 1.20.1-1.0.12
	- cratedelight 1.0.8-1.20.1-forge
	- create 0.5.1.f
	- create_connected 0.7.4-mc1.20.1
	- create_dd 0.2c.PREBETA
	- create_fully_automated 1.0.4
	- create_jetpack 4.2.1
	- create_mechanical_spawner 1.20.1-0.0.14.e-22
	- create_more_automation 0.3.0
	- create_new_age 1.1.2
	- create_structures 0.1.1
	- create_things_and_misc 1.0.0
	- create_tweaked_controllers 1.20.1-1.2.4
	- create_wizardry 1.20.12024
	- createdeco 2.0.1-1.20.1-forge
	- createframed 1.4.1
	- creategbd 1.3.0b-1.20.1
	- createliquidfuel 2.1.1-1.20.1
	- createsifter 1.20.1-1.8.1.e-22
	- createteleporters 1.2
	- creativecore 2.11.25
	- ctov 3.4.2
	- cucumber 7.0.8
	- cupboard 1.20.1-2.6
	- curios 5.7.2+1.20.1
	- cyanide 4.1.0
	- deep_dark_regrowth 1.2.5.1
	- doubledoors 5.4
	- duckyperiphs 1.20.1-1.3.1
	- dummmmmmy 1.20-1.8.14
	- dynview 2.3
	- earthtojavamobs 1.10.1
	- easy_npc 4.2.0
	- eccentrictome 1.20.1-1.10.2
	- elevatorid 1.20.1-1.9
	- embers 1.20.1-1.1.1
	- enderchests 1.20.1-1.2
	- enderitemod 1.5.1
	- endertanks 1.20.1-1.2
	- endrem 5.2.3-R-1.20.1
	- everycomp 1.20-2.6.40
	- fabric_api 0.92.0+1.11.3+1.20.1
	- fabric_api_base 0.4.31+ef105b4977
	- fabric_api_lookup_api_v1 1.6.36+67f9824077
	- fabric_biome_api_v1 13.0.13+dd0389a577
	- fabric_block_api_v1 1.0.11+0e6cb7f777
	- fabric_block_view_api_v2 1.0.1+0767707077
	- fabric_blockrenderlayer_v1 1.1.41+1d0da21e77
	- fabric_client_tags_api_v1 1.1.2+5d6761b877
	- fabric_command_api_v1 1.2.34+f71b366f77
	- fabric_command_api_v2 2.2.13+561530ec77
	- fabric_content_registries_v0 4.0.11+a670df1e77
	- fabric_convention_tags_v1 1.5.5+fa3d1c0177
	- fabric_data_attachment_api_v1 1.0.0+30ef839e77
	- fabric_data_generation_api_v1 12.3.4+369cb3a477
	- fabric_dimensions_v1 2.1.54+8005d10d77
	- fabric_entity_events_v1 1.6.0+6274ab9d77
	- fabric_events_interaction_v0 0.6.2+0d0bd5a777
	- fabric_game_rule_api_v1 1.0.40+683d4da877
	- fabric_item_api_v1 2.1.28+2272fc7f77
	- fabric_item_group_api_v1 4.0.12+c9161c2d77
	- fabric_key_binding_api_v1 1.0.37+561530ec77
	- fabric_lifecycle_events_v1 2.2.22+afab492177
	- fabric_loot_api_v2 1.2.1+eb28f93e77
	- fabric_message_api_v1 5.1.9+52cc178c77
	- fabric_mining_level_api_v1 2.1.50+561530ec77
	- fabric_model_loading_api_v1 1.0.3+6274ab9d77
	- fabric_models_v0 0.4.2+7c3892a477
	- fabric_networking_api_v1 1.3.11+503a202477
	- fabric_object_builder_api_v1 11.1.3+2174fc8477
	- fabric_particles_v1 1.1.2+78e1ecb877
	- fabric_recipe_api_v1 1.0.21+514a076577
	- fabric_registry_sync_v0 2.3.3+1c0ea72177
	- fabric_renderer_api_v1 3.2.1+1d29b44577
	- fabric_renderer_indigo 1.5.1+67f9824077
	- fabric_rendering_data_attachment_v1 0.3.37+a6081afc77
	- fabric_rendering_fluids_v1 3.0.28+4ac5e37a77
	- fabric_rendering_v1 3.0.8+1c0ea72177
	- fabric_resource_conditions_api_v1 2.3.8+9ad825cd77
	- fabric_resource_loader_v0 0.11.10+cefbb70477
	- fabric_screen_api_v1 2.0.8+45a670a577
	- fabric_screen_handler_api_v1 1.3.30+561530ec77
	- fabric_sound_api_v1 1.0.13+4f23bd8477
	- fabric_transfer_api_v1 3.3.4+b00938ec77
	- fabric_transitive_access_wideners_v1 4.3.1+1880499877
	- farmersdelight 1.20.1-1.2.4
	- farmingforblockheads 14.0.2
	- fastload 3.4.0
	- ferritecore 6.0.1
	- flatbedrock 3.0.1-build.18+mc1.20.1
	- flightlib 2.1.0
	- flowerseeds 1.1.2
	- flowerseedsbop 1.1.2
	- flowerymooblooms 2.0.1
	- flywheel 0.6.10-7
	- forge 47.2.21
	- framedblocks 9.2.1
	- framework 0.6.27
	- friendsandfoes 2.0.10
	- ftblibrary 2001.1.5
	- ftbquests 2001.3.5
	- ftbteams 2001.2.0
	- ftbxmodcompat 2.1.0
	- fulleng 1.6-1.20.1
	- galosphere 1.20.1-1.4.1
	- geckolib 4.4.4
	- glow_ink_plus 1.2.0
	- goblintraders 1.9.3
	- handcrafted 3.0.6
	- iceberg 1.1.21
	- idas 1.9.3+1.20.1
	- immersive_armors 1.6.1+1.20.1
	- infinitybuttons 1.20.1-4.0.2
	- integrated_api 1.5.0+1.20.1-forge
	- integrated_circuit 1.20.1-1.4.1
	- ironchest 1.20.1-14.4.4
	- ironjetpacks 7.0.3
	- irons_spellbooks 1.20.1-3.1.0
	- item_obliterator 1.7.0
	- itemcollectors 1.1.9
	- jade 11.8.0
	- jmc 1.17.4
	- jumbofurnace 4.0.0.5
	- kawaiidishes 1.10.2
	- kleeslabs 15.0.0
	- konkrete 1.8.0
	- kotlinforforge 4.10.0
	- kubejs 2001.6.4-build.138
	- kubejs_create 2001.2.5-build.2
	- leavesbegone 8.0.0
	- libipn 4.0.2
	- lithostitched 1.1.5
	- littleframes 1.3.7
	- littletiles 1.6.0-pre100
	- logprot 1.4
	- lootjs 1.20.1-2.11.0
	- lootr 0.7.31.77
	- luckperms 5.4.102
	- macawsbridgesbop 1.20-1.1
	- macawsroofsbop 1.20-1.0
	- magic_doorknob 1.20.1-1.0.6.1533
	- mcwbridges 2.1.0
	- mcwdoors 1.1.0
	- mcwfences 1.1.1
	- mcwfencesbop 1.20-1.0
	- mcwfurnitures 3.2.2
	- mcwfurnituresbop 1.20-1.1
	- mcwlights 1.0.6
	- mcwpaintings 1.0.5
	- mcwpaths 1.0.4
	- mcwroofs 2.3.0
	- mcwtrpdoors 1.1.2
	- mcwwindows 2.2.1
	- measurements 2.0.0
	- megacells 2.3.3-1.20.1
	- melody 1.0.2
	- memoryleakfix 1.1.5
	- merequester 1.20.1-1.1.4
	- minecraft 1.20.1
	- mixinextras 0.2.0-beta.9
	- mixinsquared 0.1.1
	- modernfix 5.15.0+mc1.20.1
	- mohist 1.20.1
	- moonlight 1.20-2.11.9
	- morered 4.0.0.4
	- moreredxcctcompat 1.20.1-1.0.0
	- mr_entitycount 2024.0128
	- mr_info_tools 1.2.3a
	- mr_limesplatus_ending 1-v1.1.0c
	- mutil 6.1.1
	- mysticaloaktree 1.20-1.11
	- naturescompass 1.20.1-1.11.2-forge
	- necronomicon 1.4.2
	- netherportalfix 13.0.1
	- observable 4.4.1
	- obsidianui 0.2.1+mc1.20.1
	- paraglider 20.1.3
	- patchouli 1.20.1-84-FORGE
	- pattysminingdimension 1.0.1
	- peripherals 1.12.2
	- pingwheel 1.8.0
	- placebo 8.6.1
	- playeranimator 1.0.2-rc1+1.20
	- playerplates 3.0.1+mc1.20.1
	- pneumaticcraft 6.0.14+mc1.20.1
	- polymorph 0.49.3+1.20.1
	- productivebees 1.20.1-12.4.3
	- productivelib 1.20.1-0.0.3
	- puzzlesaccessapi 8.0.7
	- puzzleslib 8.1.18
	- quark 4.0-439
	- railways 1.5.3+forge-mc1.20.1
	- rainshield 1.1.3
	- reborncore 5.8.7
	- rechiseled 1.1.5c
	- rechiseledcreate 1.0.2
	- regrowth 46.31.2
	- resourcefulconfig 2.1.2
	- resourcefullib 2.1.24
	- rhino 2001.2.2-build.18
	- rightclickharvest 3.2.3+1.20.1-forge
	- searchables 1.0.2
	- securitycraft 1.9.9
	- server_chat_log_history 1.4
	- sgjourney 0.6.22
	- shetiphiancore 1.20.1-1.2
	- simplemod 1.20.1
	- simpleshops 1.2.2
	- sliceanddice 3.2.0
	- smarterfarmers 1.20-1.8.3
	- solcarrot 1.15.1
	- sophisticatedbackpacks 3.20.3.1034
	- sophisticatedcore 0.6.12.589
	- spark 1.10.53
	- spectrelib 0.13.15+1.20.1
	- starlight 1.1.2+forge.1cda73c
	- storagedrawers 12.0.3
	- supermartijn642configlib 1.1.8
	- supermartijn642corelib 1.1.17
	- supplementaries 1.20-2.8.10
	- team_reborn_energy 3.0.0
	- techreborn 5.8.7
	- tectonic 2.3.1
	- terrablender 3.0.1.4
	- terralith 2.4.11
	- tetra 6.2.0
	- tetracelium 1.1.1
	- tetranomicon 1.5.3-1.20.1
	- tfmg 0.8.0b
	- timecontrol 1.6.0
	- tomeofblood 0.4.4
	- toms_trading_network 0.2.3
	- toofast 0.4.3.5
	- tradingpost 8.0.2
	- trashcans 1.0.18b
	- trashslot 15.1.0
	- treebark 1.0.0
	- useitemonblockevent 1.0.0.2
	- villagernames 7.3
	- visualworkbench 8.0.0
	- wands 2.6.9-release
	- wirelesschargers 1.0.9
	- wunderlib 1.1.5
	- yungsapi 1.20-Forge-4.0.4
	- zeta 1.0-14
  
</details>

**Plugin list :** None

**Description of issue :** Since the last ~40 builds I have been getting this error when I try to update mohist on my modpack server. Currently using build 638 and it is working but if I update to the latest version I get the following error:

```
Failed to load datapacks, can't proceed with server load. You can either fix your datapacks or reset to vanilla with --safeMode
java.util.concurrent.ExecutionException: java.lang.ClassCastException: class it.unimi.dsi.fastutil.objects.Object2ObjectLinkedOpenHashMap cannot be cast to class com.google.common.collect.ImmutableMap$Builder (it.unimi.dsi.fastutil.objects.Object2ObjectLinkedOpenHashMap is in module it.unimi.dsi.fastutil@8.5.12 of loader 'MC-BOOTSTRAP' @285f09de; com.google.common.collect.ImmutableMap$Builder is in module com.google.common@31.1-jre of loader 'MC-BOOTSTRAP' @285f09de)
        at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396) ~[?:?]
        at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073) ~[?:?]
        at net.minecraft.server.Main.main(Main.java:250) ~[server-1.20.1-20230612.114412-srg.jar%23696!/:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.2.23.jar%23190!/:?]
        at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.serverService(CommonLaunchHandler.java:103) ~[fmlloader-1.20.1-47.2.23.jar%23190!/:?]
        at net.minecraftforge.fml.loading.targets.CommonServerLaunchHandler.lambda$makeService$0(CommonServerLaunchHandler.java:27) ~[fmlloader-1.20.1-47.2.23.jar%23190!/:?]
        at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.9.jar%23102!/:?]
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.9.jar%23102!/:?]
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.9.jar%23102!/:?]
        at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) [modlauncher-10.0.9.jar%23102!/:?]
        at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) [modlauncher-10.0.9.jar%23102!/:?]
        at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.9.jar%23102!/:?]
        at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.9.jar%23102!/:?]
        at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?]
        at com.mohistmc.MohistMCStart.main(MohistMCStart.java:109) [mohist-1.20.1-637-server.jar:1.20.1-673]
Caused by: java.lang.ClassCastException: class it.unimi.dsi.fastutil.objects.Object2ObjectLinkedOpenHashMap cannot be cast to class com.google.common.collect.ImmutableMap$Builder (it.unimi.dsi.fastutil.objects.Object2ObjectLinkedOpenHashMap is in module it.unimi.dsi.fastutil@8.5.12 of loader 'MC-BOOTSTRAP' @285f09de; com.google.common.collect.ImmutableMap$Builder is in module com.google.common@31.1-jre of loader 'MC-BOOTSTRAP' @285f09de)
        at com.blakebr0.cucumber.helper.RecipeHelper.fireRecipeManagerLoadedEvent(RecipeHelper.java:74) ~[Cucumber-1.20.1-7.0.8.jar%23523!/:7.0.8]
        at net.minecraft.world.item.crafting.RecipeManager.handler$cog000$cucumber$apply(RecipeManager.java:6042) ~[server-1.20.1-20230612.114412-srg.jar%23696!/:?]
        at net.minecraft.world.item.crafting.RecipeManager.m_5787_(RecipeManager.java:67) ~[server-1.20.1-20230612.114412-srg.jar%23696!/:?]
        at net.minecraft.world.item.crafting.RecipeManager.m_5787_(RecipeManager.java:38) ~[server-1.20.1-20230612.114412-srg.jar%23696!/:?]
        at net.minecraft.server.packs.resources.SimplePreparableReloadListener.m_10789_(SimplePreparableReloadListener.java:13) ~[server-1.20.1-20230612.114412-srg.jar%23696!/:?]
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
        at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
        at net.minecraft.server.packs.resources.SimpleReloadInstance.m_143940_(SimpleReloadInstance.java:69) ~[server-1.20.1-20230612.114412-srg.jar%23696!/:?]
        at net.minecraft.Util.m_214652_(Util.java:783) ~[server-1.20.1-20230612.114412-srg.jar%23696!/:?]
        at net.minecraft.Util.m_214679_(Util.java:772) ~[server-1.20.1-20230612.114412-srg.jar%23696!/:?]
        at net.minecraft.server.Main.main(Main.java:220) ~[server-1.20.1-20230612.114412-srg.jar%23696!/:?]
        ... 16 more
```

**Comment by Mgazul** [comment]
It cannot be repaired. If repaired, all plugins related to recipes will become invalid.

**Comment by Magi1053** [comment]
@Mgazul How do I overcome this issue then?

**Comment by Mgazul** [comment]
Continue using 638 or delete the cucumber mod
