### ISSUE TITLE
Must remove the libraries folder after restarting

### ISSUE THREAD

**Issue by NamelessXiaoJiang** [Teneted/Tenet#3084]
**Minecraft Version :** 1.20.1

**Mohist Version :** 681

**Operating System :** ubunte

**Logs :** 
[2024-04-23-3.log](https://github.com/MohistMC/Mohist/files/15066857/2024-04-23-3.log)

```
Exception in thread "main" java.lang.IllegalArgumentException: Module JarJarFileSystems not known to this layer
        at java.base/java.lang.ModuleLayer.findLoader(ModuleLayer.java:890)
        at cpw.mods.cl.ModuleClassLoader.lambda$new$4(ModuleClassLoader.java:64)
        at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:273)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
        at java.base/java.util.AbstractList$RandomAccessSpliterator.tryAdvance(AbstractList.java:706)
        at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129)
        at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:647)
        at cpw.mods.cl.ModuleClassLoader.lambda$new$5(ModuleClassLoader.java:65)
        at cpw.mods.cl.ModuleClassLoader.<init>(ModuleClassLoader.java:71)
        at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:132)
        at com.mohistmc.MohistMCStart.main(MohistMCStart.java:109)
```

**Mod list :** 
```
[01:37:07 INFO]: 内部模组: (3) -> [forge, mohist, minecraft]
[01:37:07 INFO]: 仅客户端mod: (3) -> [exposure, flywheel, create]
[01:37:07 INFO]: 仅服务端mod: (0) -> []
[01:37:07 INFO]: 所有mod: (57) -> [tetra, betterdungeons, man_of_many_planes, createbigcannons, betterwitchhuts, amendments, geckolib, betteroceanmonuments, map_atlases, immersive_aircraft, netmusic, epicfight, ritchiesprojectilelib, citadel, alexsmobs, travelersbackpack, yungsapi, mixinextras, create_confectionery, create_dragon_lib, betterdeserttemples, railways, terralith, exposure, betterfortresses, forge, mohist, supplementaries, fightnbtintegration, minecraft, farmersdelight, alexscaves, moonlight, mixinsquared, do_a_barrel_roll, yungsbridges, flywheel, create, create_central_kitchen, mutil, createarmory, create_sa, yungsextras, armourers_workshop, betterstrongholds, butchersdelight, architectury, ftblibrary, itemfilters, ftbteams, ftbquests, alexsdelight, betterendisland, nbtedit, heartstone, bettermineshafts, betterjungletemples]
```

**Plugin list :** https://haste.mohistmc.com/eqixulacez

**Description of issue :** 
When I shut down the server and turn it back on, server can't work.
I remove the libraries folder and download them, the server work again

**Comment by chillgerne89** [comment]
I have this problem too. I have tested different versions and found that the issue occurs since MohistMC #511 in all updates. MohistMC #510 works fine for me. Maybe that helps you.

**Comment by NamelessXiaoJiang** [comment]
> 我也有这个问题。我测试了不同的版本，发现自 MohistMC #511 以来，所有更新中都出现了该问题。MohistMC #510 对我来说效果很好。也许这对你有帮助。

But I need forge 47.2.20 or above😢

**Comment by Mgazul** [comment]
尝试使用今天的最新构建

**Comment by NamelessXiaoJiang** [comment]
I try it,but still not working

**Comment by Mgazul** [comment]
> I try it,but still not working

It means it has nothing to do with the 511 update
