### ISSUE TITLE
All the mods 9 Failed to handle packet net.minecraft.network.protocol.game.ServerboundContainerClickPacket@3ad60024

### ISSUE THREAD

**Issue by funnycubeguy** [Teneted/Tenet#3094]
When interacting with all the mods 9 gregtech low pressure steam alloy smelter the items in the inventory (redstone + copper dust) jump around it is hard to get them in their slots. It spams the logs with the error below:

Failed to handle packet net.minecraft.network.protocol.game.ServerboundContainerClickPacket@3ad60024, suppressing error
java.lang.NullPointerException: null

The smells also stops after 1 ingot smelted. Need to replace the smelter every time

Mohist build 653 1.20.1 latest all the mods 9 pack.

![image](https://github.com/MohistMC/Mohist/assets/9994438/ad224f87-04aa-42e4-b77e-0e6f7c7ed3a3)

**Comment by Mgazul** [comment]
Please provide complete log

**Comment by funnycubeguy** [comment]
> Please provide complete log

https://pastes.dev/wHk4b68dMF

Whenever I add the item to the steamer it vanishes and those errors show

**Comment by funnycubeguy** [comment]
`[10:03:25 ERROR]: Failed to handle packet net.minecraft.network.protocol.game.ServerboundCustomPayloadPacket@40b13472, suppressing error
java.lang.ArrayIndexOutOfBoundsException: Index 4 out of bounds for length 4
        at com.refinedmods.refinedstorage.apiimpl.network.grid.CraftingGridBehavior.onRecipeTransfer(CraftingGridBehavior.java:202) ~[refinedstorage-1.12.4.jar%23904!/:?]
        at com.refinedmods.refinedstorageaddons.item.WirelessCraftingGrid.onRecipeTransfer(WirelessCraftingGrid.java:165) ~[refinedstorageaddons-0.10.0.jar%23905!/:?]
        at com.refinedmods.refinedstorage.network.grid.GridTransferMessage.lambda$handle$0(GridTransferMessage.java:64) ~[refinedstorage-1.12.4.jar%23904!/:?]
        at net.minecraftforge.network.NetworkEvent$Context.enqueueWork(NetworkEvent.java:212) ~[forge-1.20.1-47.2.30-universal.jar%231013!/:?]
        at com.refinedmods.refinedstorage.network.grid.GridTransferMessage.handle(GridTransferMessage.java:59) ~[refinedstorage-1.12.4.jar%23904!/:?]
        at net.minecraftforge.network.simple.IndexedMessageCodec.lambda$tryDecode$3(IndexedMessageCodec.java:115) ~[forge-1.20.1-47.2.30-universal.jar%231013!/:?]
        at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
        at net.minecraftforge.network.simple.IndexedMessageCodec.tryDecode(IndexedMessageCodec.java:115) ~[forge-1.20.1-47.2.30-universal.jar%231013!/:?]
        at net.minecraftforge.network.simple.IndexedMessageCodec.consume(IndexedMessageCodec.java:153) ~[forge-1.20.1-47.2.30-universal.jar%231013!/:?]
        at net.minecraftforge.network.simple.SimpleChannel.networkEventListener(SimpleChannel.java:63) ~[forge-1.20.1-47.2.30-universal.jar%231013!/:?]
        at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:263) ~[eventbus-6.0.5.jar%23149!/:?]
        at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:255) ~[eventbus-6.0.5.jar%23149!/:?]
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:319) ~[eventbus-6.0.5.jar%23149!/:?]
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:299) ~[eventbus-6.0.5.jar%23149!/:?]
        at net.minecraftforge.network.NetworkInstance.dispatch(NetworkInstance.java:68) ~[forge-1.20.1-47.2.30-universal.jar%231013!/:?]
        at net.minecraftforge.network.NetworkHooks.lambda$onCustomPayload$1(NetworkHooks.java:84) ~[forge-1.20.1-47.2.30-universal.jar%231013!/:?]
        at java.util.Optional.map(Optional.java:260) ~[?:?]
        at net.minecraftforge.network.NetworkHooks.onCustomPayload(NetworkHooks.java:84) ~[forge-1.20.1-47.2.30-universal.jar%231013!/:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.m_7423_(ServerGamePacketListenerImpl.java:2843) ~[server-1.20.1-20230612.114412-srg.jar%231008!/:?]
        at net.minecraft.network.protocol.game.ServerboundCustomPayloadPacket.m_5797_(ServerboundCustomPayloadPacket.java:35) ~[server-1.20.1-20230612.114412-srg.jar%231008!/:?]
        at net.minecraft.network.protocol.game.ServerboundCustomPayloadPacket.m_5797_(ServerboundCustomPayloadPacket.java:8) ~[server-1.20.1-20230612.114412-srg.jar%231008!/:?]
        at net.minecraft.network.protocol.PacketUtils.m_263899_(PacketUtils.java:25) ~[server-1.20.1-20230612.114412-srg.jar%231008!/:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[server-1.20.1-20230612.114412-srg.jar%231008!/:?]
        at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:151) ~[server-1.20.1-20230612.114412-srg.jar%231008!/:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[server-1.20.1-20230612.114412-srg.jar%231008!/:?]
        at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:1027) ~[server-1.20.1-20230612.114412-srg.jar%231008!/:?]
        at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:173) ~[server-1.20.1-20230612.114412-srg.jar%231008!/:?]
        at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:124) ~[server-1.20.1-20230612.114412-srg.jar%231008!/:?]
        at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:1010) ~[server-1.20.1-20230612.114412-srg.jar%231008!/:?]
        at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:1004) ~[server-1.20.1-20230612.114412-srg.jar%231008!/:?]
        at net.minecraft.util.thread.BlockableEventLoop.m_18699_(BlockableEventLoop.java:112) ~[server-1.20.1-20230612.114412-srg.jar%231008!/:?]
        at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:989) ~[server-1.20.1-20230612.114412-srg.jar%231008!/:?]
        at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:906) ~[server-1.20.1-20230612.114412-srg.jar%231008!/:?]
        at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:281) ~[server-1.20.1-20230612.114412-srg.jar%231008!/:?]
        at java.lang.Thread.run(Thread.java:840) [?:?]`

Here is another one the interface was broken on my server

**Comment by Mgazul** [comment]
> > Please provide complete log
> 
> https://pastes.dev/wHk4b68dMF
> 
> Whenever I add the item to the steamer it vanishes and those errors show

Using mohist latest build

**Comment by funnycubeguy** [comment]
> > > Please provide complete log
> > 
> > 
> > https://pastes.dev/wHk4b68dMF
> > Whenever I add the item to the steamer it vanishes and those errors show
> 
> Using mohist latest build

I installed the latest version now https://pastes.dev/eK6sPrN8s3

Same issue
