### ISSUE TITLE
Fix plz conflict plugins

### ISSUE THREAD

**Issue by Unitei-Dev** [Teneted/Tenet#3120]
https://mclo.gs/oHKX8IN

the PlaceholserAPI plugin conflicts with the Typewriter plugin, if I remove the PlaceholserAPI plugin everything works fine and stable

Minecraft Version : 1.20.1
Mohist Version : 
Operating System : linux
mod: 52 mods, but they don't conflict
plugin : Actions, AdvancedChests, Adyeshach, ajLeaderboards, AquaticCrates, BeaconPlus3, BetonQuest, BetonQuestGUI, BetterHealthBar, BetterHud, Boosters, BugReport, Chemdah, ChemdahUCExpand, CMILib, ConditionalEvents, ConsoleSpamFix, Craftorithm, CustomFishing, CustomNameplates, CustomPiglinsTrades, DarkAuctionsX, DeluxeMenus, DisableHUD, eco, EcoArmor, EcoEnchants, EcoItems, Economobs, EcoPets, EcoSkills, Essentials, EssentialsSpawn, ExecutableBlocks, ExecutableEvents, ExecutableItems, ExtraStorage, FeatheredBags, FeatheredElection, GeekMail-Pro, GlobalMarketPlus, HeadBlocks, HyronicFriends, Jobs, libreforge, LicenseManager, LuckPerms, MCCoroutine-Sample, MCoreAddon, MineRegion, MiningContest, MIReplacer, MMOCore, MMOItems, MMOXPAddon, ModelEngine, Mohist, Multiverse-Core, MythicAchievements, MythicChanger, MythicCrucible, MythicDungeons, MythicEnchants, MythicLib, MythicLibreforge, MythicMobs, MythicPrefixes, MythicTotem, NBTAPI, Oraxen, OutpostCommander, packetevents, PAPISign, PlaceholderAPI, PlayerPoints, PlugManX, Polymart, ProtocolLib, Reforges, RegionInteraction, RegionPlaceholders, Resources, RoyaleEconomy, RPGInventory, RPGRegions, SalakauCore, SCore, SkBee, SkinsRestorer, Skript, skript-placeholders, skript-reflect, Slabbo, TAB, Talismans, TigerReports, TigerReportsSupports, TopBossSlayer, TopCollections, TopMinion, TradeAudit, TradeSystem, UltimateAdvancementAPI, UltimateClans, UnrealCore, UnrealGUI, UnrealGUIPro, UnrealHeartBeat, UnrealHUD, UnrealKeyBoard, UnrealResource, Vault, VexView, WorldEdit, WorldGuard, XLTournaments, XPBoosterPlusPlus, Typewriter

 [19:54:07] [Server thread/ERROR] [Minecraft]: Error occurred while enabling Typewriter v0.4.2 (Is it up to date?)
java.lang.NoSuchMethodError: 'com.mohistmc.paper.plugin.configuration.PluginMeta org.bukkit.plugin.Plugin.getPluginMeta()'
	at me.gabber235.typewriter.extensions.placeholderapi.TypewriteExpansion.getVersion(TypewriteExpansion.kt:22) ~[Typewriter.jar:?]
	at me.clip.placeholderapi.expansion.manager.LocalExpansionManager.register(LocalExpansionManager.java:301) ~[PlaceholderAPI-2.11.5.jar:?]
	at me.clip.placeholderapi.expansion.PlaceholderExpansion.register(PlaceholderExpansion.java:147) ~[PlaceholderAPI-2.11.5.jar:?]
	at me.gabber235.typewriter.Typewriter.onEnableAsync(Typewriter.kt:104) ~[?:?]
	at com.github.shynixn.mccoroutine.bukkit.SuspendingJavaPlugin$onEnable$1.invokeSuspend(SuspendingJavaPlugin.kt:38) ~[?:?]
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) ~[?:?]
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106) ~[?:?]
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280) ~[?:?]
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85) ~[?:?]
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59) ~[?:?]
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source) ~[?:?]
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38) ~[?:?]
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source) ~[?:?]
	at com.github.shynixn.mccoroutine.bukkit.SuspendingJavaPlugin.onEnable(SuspendingJavaPlugin.kt:37) ~[?:?]
	at lirand.api.architecture.KotlinPlugin.onEnable(KotlinPlugin.kt:13) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:347) ~[forge-1.20.1-47.2.32-universal.jar%23309!/:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:336) ~[forge-1.20.1-47.2.32-universal.jar%23309!/:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:482) ~[forge-1.20.1-47.2.32-universal.jar%23309!/:?]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:547) ~[forge-1.20.1-47.2.32-universal.jar%23309!/:997de31d-ddc9a2dad-d2eba2c8-47.1.105]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:461) ~[forge-1.20.1-47.2.32-universal.jar%23309!/:997de31d-ddc9a2dad-d2eba2c8-47.1.105]
	at net.minecraft.server.MinecraftServer.m_129815_(MinecraftServer.java:441) ~[server-1.20.1-20230612.114412-srg.jar%23304!/:?]
	at net.minecraft.server.MinecraftServer.m_130006_(MinecraftServer.java:341) ~[server-1.20.1-20230612.114412-srg.jar%23304!/:?]
	at net.minecraft.server.dedicated.DedicatedServer.m_7038_(DedicatedServer.java:227) ~[server-1.20.1-20230612.114412-srg.jar%23304!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:836) ~[server-1.20.1-20230612.114412-srg.jar%23304!/:?]
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:281) ~[server-1.20.1-20230612.114412-srg.jar%23304!/:?]
	at java.lang.Thread.run(Thread.java:840) [?:?]

**Comment by Unitei-Dev** [comment]
[03:51:56 INFO]: [Typewriter] Loading Typewriter v0.4.2
[03:51:57 INFO]: [Typewriter] Loading adapter BasicAdapter (1)
[03:52:00 WARN]: [Typewriter] Failed to load adapter BasicAdapter (1). Skipping...
[03:52:00 WARN]: java.lang.NoSuchFieldException: BETTERNETHER_FIREFLY
[03:52:00 WARN]:        at java.base/java.lang.Class.getField(Class.java:2117)
[03:52:00 WARN]:        at me.gabber235.typewriter.adapters.EnumField$Companion.fromTypeToken(EntryBlueprint.kt:130)
[03:52:00 WARN]:        at me.gabber235.typewriter.adapters.FieldInfo$Companion.fromTypeToken(EntryBlueprint.kt:47)
[03:52:00 WARN]:        at me.gabber235.typewriter.adapters.editors.OptionalEditorKt$optional$1$4.invoke(OptionalEditor.kt:52)
[03:52:00 WARN]:        at me.gabber235.typewriter.adapters.editors.OptionalEditorKt$optional$1$4.invoke(OptionalEditor.kt:49)
[03:52:00 WARN]:        at me.gabber235.typewriter.adapters.ObjectEditor.generateFieldInfo$typewriter(CustomEditors.kt:137)
[03:52:00 WARN]:        at me.gabber235.typewriter.adapters.FieldInfo$Companion.fromTypeToken(EntryBlueprint.kt:33)
[03:52:00 WARN]:        at me.gabber235.typewriter.adapters.ObjectField$Companion.fromTypeToken(EntryBlueprint.kt:174)
[03:52:00 WARN]:        at me.gabber235.typewriter.adapters.AdapterLoaderImpl.constructEntryBlueprints(AdapterLoader.kt:217)
[03:52:00 WARN]:        at me.gabber235.typewriter.adapters.AdapterLoaderImpl.constructAdapter(AdapterLoader.kt:171)
[03:52:00 WARN]:        at me.gabber235.typewriter.adapters.AdapterLoaderImpl.loadAdapter(AdapterLoader.kt:156)
[03:52:00 WARN]:        at me.gabber235.typewriter.adapters.AdapterLoaderImpl.loadAdapters(AdapterLoader.kt:75)
[03:52:00 WARN]:        at me.gabber235.typewriter.Typewriter.onLoad(Typewriter.kt:80)
[03:52:00 WARN]:        at TRANSFORMER/forge@47.2.32/org.bukkit.craftbukkit.v1_20_R1.CraftServer.loadPlugins(CraftServer.java:440)
[03:52:00 WARN]:        at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.dedicated.DedicatedServer.m_7038_(DedicatedServer.java:219)
[03:52:00 WARN]:        at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:836)
[03:52:00 WARN]:        at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:281)
[03:52:00 WARN]:        at java.base/java.lang.Thread.run(Thread.java:840)
[03:52:00 WARN]: [Typewriter] 
---------------{ No Adapters Loaded }---------------
No adapters were loaded. 
You should always have at least the BasicAdapter loaded.
--------------------------------------------------

**Comment by Mgazul** [comment]
Typewriter only supports paper, we do not provide paper

**Comment by Unitei-Dev** [comment]
okay, no problem
