### ISSUE TITLE
Fix pLz plugin pathfinder and customfishing

### ISSUE THREAD

**Issue by Unitei-Dev** [Teneted/Tenet#3158]
Log: https://mclo.gs/GkbsYbc

pathfinder: https://www.spigotmc.org/resources/gps-pathfinder-minecraft-pathfinding-tool.104961/updates
customfishing: https://github.com/Xiao-MoMi/Custom-Fishing

**Minecraft Version :** 1.20.1

**Mohist Version :** 704

**Operating System :** Linux

[21:01:13 WARN]: An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
java.lang.NoClassDefFoundError: de/cubbossa/pathfinder/lib/cliententities/lib/packetevents/impl/injector/connection/PreChannelInitializer_v1_12
        at de.cubbossa.pathfinder.lib.cliententities.lib.packetevents.impl.injector.connection.ServerChannelHandler.channelRead(ServerChannelHandler.java:64) ~[?:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.82.Final.jar%23175!/:4.1.82.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.82.Final.jar%23175!/:4.1.82.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.82.Final.jar%23175!/:4.1.82.Final]
        at com.comphenix.protocol.injector.netty.manager.InjectionChannelInitializer.channelRead(InjectionChannelInitializer.java:26) ~[?:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.82.Final.jar%23175!/:4.1.82.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.82.Final.jar%23175!/:4.1.82.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.82.Final.jar%23175!/:4.1.82.Final]
        at ink.ptms.adyeshach.taboolib.module.nms.TinyProtocol$3.channelRead(TinyProtocol.java:150) ~[?:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.82.Final.jar%23175!/:4.1.82.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.82.Final.jar%23175!/:4.1.82.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.82.Final.jar%23175!/:4.1.82.Final]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[netty-transport-4.1.82.Final.jar%23175!/:4.1.82.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.82.Final.jar%23175!/:4.1.82.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.82.Final.jar%23175!/:4.1.82.Final]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[netty-transport-4.1.82.Final.jar%23175!/:4.1.82.Final]
        at io.netty.channel.epoll.AbstractEpollServerChannel$EpollServerSocketUnsafe.epollInReady(AbstractEpollServerChannel.java:120) ~[netty-transport-classes-epoll-4.1.82.Final.jar%23176!/:4.1.82.Final]
        at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe$1.run(AbstractEpollChannel.java:425) ~[netty-transport-classes-epoll-4.1.82.Final.jar%23176!/:4.1.82.Final]
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[netty-common-4.1.82.Final.jar%23172!/:4.1.82.Final]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[netty-common-4.1.82.Final.jar%23172!/:4.1.82.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[netty-common-4.1.82.Final.jar%23172!/:4.1.82.Final]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:406) ~[netty-transport-classes-epoll-4.1.82.Final.jar%23176!/:4.1.82.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.82.Final.jar%23172!/:4.1.82.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.82.Final.jar%23172!/:4.1.82.Final]
        at java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.lang.ClassNotFoundException: de.cubbossa.pathfinder.lib.cliententities.lib.packetevents.impl.injector.connection.PreChannelInitializer_v1_12
        ... 25 more

**Comment by Unitei-Dev** [comment]
[20:49:13] [Server thread/INFO] [net.momirealms.customfishing.CustomFishingPluginImpl]: [CustomFishing] Enabling CustomFishing v2.1.6.6
[20:49:13] [Server thread/ERROR] [net.momirealms.customfishing.CustomFishingPluginImpl]: [CustomFishing] Error occurred when loading reflections
java.lang.NoSuchFieldException: REMOVE_OPERATION
	at java.lang.Class.getDeclaredField(Class.java:2782) ~[?:?]
	at net.momirealms.customfishing.api.util.ReflectionUtils.load(ReflectionUtils.java:43) ~[?:?]
	at net.momirealms.customfishing.CustomFishingPluginImpl.onEnable(CustomFishingPluginImpl.java:116) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:347) ~[forge-1.20.1-47.2.32-universal.jar%23317!/:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:336) ~[forge-1.20.1-47.2.32-universal.jar%23317!/:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:482) ~[forge-1.20.1-47.2.32-universal.jar%23317!/:?]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:547) ~[forge-1.20.1-47.2.32-universal.jar%23317!/:997de31d-ddc9a2dad-d2eba2c8-47.1.105]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:461) ~[forge-1.20.1-47.2.32-universal.jar%23317!/:997de31d-ddc9a2dad-d2eba2c8-47.1.105]
	at net.minecraft.server.MinecraftServer.m_129815_(MinecraftServer.java:441) ~[server-1.20.1-20230612.114412-srg.jar%23312!/:?]
	at net.minecraft.server.MinecraftServer.m_130006_(MinecraftServer.java:341) ~[server-1.20.1-20230612.114412-srg.jar%23312!/:?]
	at net.minecraft.server.dedicated.DedicatedServer.m_7038_(DedicatedServer.java:227) ~[server-1.20.1-20230612.114412-srg.jar%23312!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:850) ~[server-1.20.1-20230612.114412-srg.jar%23312!/:?]
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:281) ~[server-1.20.1-20230612.114412-srg.jar%23312!/:?]
	at java.lang.Thread.run(Thread.java:1583) [?:?]
