### ISSUE TITLE
1.20.1 CoreProtect log spam

### ISSUE THREAD

**Issue by funnycubeguy** [Teneted/Tenet#3171]
Latest 705 mohist 1.20.1 build with the latest coreprotect. This fills my logs like crazy

`[23:11:11 ERROR]: Could not pass event InventoryMoveItemEvent to CoreProtect v22.4
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:304) ~[forge-1.20.1-47.3.1-universal.jar%23999!/:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[forge-1.20.1-47.3.1-universal.jar%23999!/:?]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:602) ~[forge-1.20.1-47.3.1-universal.jar%23999!/:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:586) ~[forge-1.20.1-47.3.1-universal.jar%23999!/:?]
        at net.minecraftforge.items.VanillaInventoryCodeHooks.lambda$extractHook$0(VanillaInventoryCodeHooks.java:64) ~[forge-1.20.1-47.3.1-universal.jar%23999!/:?]
        at java.util.Optional.map(Optional.java:260) ~[?:?]
        at net.minecraftforge.items.VanillaInventoryCodeHooks.extractHook(VanillaInventoryCodeHooks.java:46) ~[forge-1.20.1-47.3.1-universal.jar%23999!/:?]
        at net.minecraft.world.level.block.entity.HopperBlockEntity.m_155552_(HopperBlockEntity.java:224) ~[server-1.20.1-20230612.114412-srg.jar%23994!/:?]
        at dev.murad.shipping.block.rapidhopper.RapidHopperTileEntity.lambda$pushItemsTick$0(RapidHopperTileEntity.java:26) ~[littlelogistics-mc1.20.1-v1.20.1.2.jar%23805!/:1.20.1.2]
        at net.minecraft.world.level.block.entity.HopperBlockEntity.m_155578_(HopperBlockEntity.java:154) ~[server-1.20.1-20230612.114412-srg.jar%23994!/:?]
        at dev.murad.shipping.block.rapidhopper.RapidHopperTileEntity.pushItemsTick(RapidHopperTileEntity.java:26) ~[littlelogistics-mc1.20.1-v1.20.1.2.jar%23805!/:1.20.1.2]
        at net.minecraft.world.level.chunk.LevelChunk$BoundTickingBlockEntity.m_142224_(LevelChunk.java:786) ~[server-1.20.1-20230612.114412-srg.jar%23994!/:?]
        at net.minecraft.world.level.chunk.LevelChunk$RebindableTickingBlockEntityWrapper.m_142224_(LevelChunk.java:871) ~[server-1.20.1-20230612.114412-srg.jar%23994!/:?]
        at net.minecraft.world.level.Level.redirect$cnp000$observable$redirectTick(Level.java:8259) ~[server-1.20.1-20230612.114412-srg.jar%23994!/:?]
        at net.minecraft.world.level.Level.m_46463_(Level.java:614) ~[server-1.20.1-20230612.114412-srg.jar%23994!/:?]
        at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:435) ~[server-1.20.1-20230612.114412-srg.jar%23994!/:?]
        at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:1158) ~[server-1.20.1-20230612.114412-srg.jar%23994!/:?]
        at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:349) ~[server-1.20.1-20230612.114412-srg.jar%23994!/:?]
        at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:1074) ~[server-1.20.1-20230612.114412-srg.jar%23994!/:?]
        at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:904) ~[server-1.20.1-20230612.114412-srg.jar%23994!/:?]
        at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:281) ~[server-1.20.1-20230612.114412-srg.jar%23994!/:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.world.Container.getLocation()" because "this.inventory" is null
        at org.bukkit.craftbukkit.v1_20_R1.inventory.CraftInventory.getLocation(CraftInventory.java:540) ~[forge-1.20.1-47.3.1-universal.jar%23999!/:?]
        at net.coreprotect.listener.player.InventoryChangeListener.onInventoryMoveItemEvent(InventoryChangeListener.java:320) ~[?:?]
        at jdk.internal.reflect.GeneratedMethodAccessor284.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[forge-1.20.1-47.3.1-universal.jar%23999!/:?]
        ... 21 more`

**Comment by funnycubeguy** [comment]
https://pastes.dev/IL0IcO3o0C

More errors on all my servers with mohist. None with arclight

**Comment by sanik** [comment]
@Mgazul more info https://github.com/MohistMC/Mohist/issues/3181

**Comment by sanik** [comment]
@Mgazul I don't know English well, so my explanation might be a bit unclear. In short, we need to check for null on the container itself because it is passed during the creation of CraftInventory. When getLocation is called, it turns out to be null and causes spam.

Container container = HopperBlockEntity.getSourceContainer(level, dest); - NPE
