### ISSUE TITLE
WorldGuard

### ISSUE THREAD

**Issue by Kompanion8** [Teneted/Tenet#32]
Problem with WorldGuard plugin
Work fine on Spigot, but on Mohist :(
`[11:33:43] [Server thread/ERROR] [Mohist]: Error occurred while enabling WorldGuard v6.2.2-SNAPSHOT;8eeab68 (Is it up to date?)
java.lang.NoClassDefFoundError: com/sk89q/bukkit/util/CommandsManagerRegistration
    at com.sk89q.worldguard.bukkit.WorldGuardPlugin.onEnable(WorldGuardPlugin.java:171) ~[?:?]
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:177) ~[JavaPlugin.class:0615411]
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:327) [JavaPluginLoader.class:0615411]
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:399) [SimplePluginManager.class:0615411]
    at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:466) [CraftServer.class:0615411]
    at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:407) [CraftServer.class:0615411]
    at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:393) [MinecraftServer.class:?]
    at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:321) [nz.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:599) [MinecraftServer.class:?]
    at java.lang.Thread.run(Thread.java:748) [?:1.8.0_231]
Caused by: java.lang.ClassNotFoundException: com.sk89q.bukkit.util.CommandsManagerRegistration
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:118) ~[PluginClassLoader.class:0615411]
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:87) ~[PluginClassLoader.class:0615411]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_231]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_231]
    ... 10 more`

**Comment by FabioZumbi12** [comment]
`NoClassDefFoundError: com/sk89q/bukkit/util/CommandsManagerRegistration` seems to be nothing related with Mohist, but by the date of this release of We you is using, seems to be not compatible with your java version (sometimes throws NoClassDefFoundError because incompatible java version/scm)
