### ISSUE TITLE
Crash on login

### ISSUE THREAD

**Issue by denireilly** [Teneted/Tenet#320]
---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 6/4/20 12:35 AM
Description: Exception in server tick loop

java.lang.ExceptionInInitializerError: null
	at net.minecraft.server.management.PlayerList.func_72355_a(PlayerList.java:167) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.network.login.ServerLoginNetHandler.func_147326_c(ServerLoginNetHandler.java:140) ~[?:?] {re:classloading}
	at net.minecraft.network.login.ServerLoginNetHandler.func_73660_a(ServerLoginNetHandler.java:70) ~[?:?] {re:classloading}
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:224) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:144) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1028) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:402) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:933) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:775) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252] {}
Caused by: java.lang.RuntimeException: java.lang.NoSuchFieldException: chatSpamThresholdCount
	at java.util.concurrent.atomic.AtomicIntegerFieldUpdater$AtomicIntegerFieldUpdaterImpl.<init>(AtomicIntegerFieldUpdater.java:403) ~[?:1.8.0_252] {}
	at java.util.concurrent.atomic.AtomicIntegerFieldUpdater.newUpdater(AtomicIntegerFieldUpdater.java:88) ~[?:1.8.0_252] {}
	at net.minecraft.network.play.ServerPlayNetHandler.<clinit>(ServerPlayNetHandler.java:210) ~[?:?] {re:classloading,pl:accesstransformer:B}
	... 10 more
Caused by: java.lang.NoSuchFieldException: chatSpamThresholdCount
	at java.lang.Class.getDeclaredField(Class.java:2070) ~[?:1.8.0_252] {}
	at java.util.concurrent.atomic.AtomicIntegerFieldUpdater$AtomicIntegerFieldUpdaterImpl$1.run(AtomicIntegerFieldUpdater.java:390) ~[?:1.8.0_252] {}
	at java.util.concurrent.atomic.AtomicIntegerFieldUpdater$AtomicIntegerFieldUpdaterImpl$1.run(AtomicIntegerFieldUpdater.java:388) ~[?:1.8.0_252] {}
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_252] {}
	at java.util.concurrent.atomic.AtomicIntegerFieldUpdater$AtomicIntegerFieldUpdaterImpl.<init>(AtomicIntegerFieldUpdater.java:387) ~[?:1.8.0_252] {}
	at java.util.concurrent.atomic.AtomicIntegerFieldUpdater.newUpdater(AtomicIntegerFieldUpdater.java:88) ~[?:1.8.0_252] {}
	at net.minecraft.network.play.ServerPlayNetHandler.<clinit>(ServerPlayNetHandler.java:210) ~[?:?] {re:classloading,pl:accesstransformer:B}
	... 10 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.15.2
	Minecraft Version ID: 1.15.2
	Operating System: Linux (amd64) version 4.19-ovh-xxxx-std-ipv6-64
	Java Version: 1.8.0_252, Private Build
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Private Build
	Memory: 4027241512 bytes (3840 MB) / 4908908544 bytes (4681 MB) up to 4908908544 bytes (4681 MB)
	CPUs: 8
	JVM Flags: 2 total; -Xmx5000M -Xms5000M
	ModLauncher: 5.1.0+69+master.79f13f7
	ModLauncher launch target: fmlserver
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-2.2.0-service.jar eventbus PLUGINSERVICE 
		/forge-1.15.2-31.2.0.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.15.2-31.2.0.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.1.1-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.15.2-31.2.0.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.15.2-31.2.0.jar runtimedistcleaner PLUGINSERVICE 
		/forge-1.15.2-31.2.0.jar fml TRANSFORMATIONSERVICE 
	FML: 31.2
	Forge: net.minecraftforge:31.2.0
	FML Language Providers: 
		javafml@31.2
		minecraft@1
	Mod List: 
		forge-1.15.2-31.2.0-server.jar Minecraft {minecraft@1.15.2 DONE}
		Bookshelf-1.15.2-5.6.40.jar Bookshelf {bookshelf@5.6.40 DONE}
		pamhc2trees-1.15.2-1.0.5.jar Pam's HarvestCraft 2 Fruit Trees {pamhc2trees@version DONE}
		MekanismTools-1.15.2-9.10.7.420.jar Mekanism: Tools {mekanismtools@9.10.7 DONE}
		MekanismAdditions-1.15.2-9.10.7.420.jar Mekanism: Additions {mekanismadditions@9.10.7 DONE}
		pamhc2crops-1.15.2-1.0.5.jar Pam's HarvestCraft 2 Crops {pamhc2crops@version DONE}
		furniture-7.0.0-pre16-1.15.1.jar MrCrayfish's Furniture Mod {cfm@7.0.0-pre16 DONE}
		AppleSkin-mc1.15.2-forge-1.0.13.jar AppleSkin {appleskin@1.0.13 DONE}
		mapperbase-1.15.2-1.1.0.0.jar Mapper Base {mapperbase@1.15.2-1.1.0.0 DONE}
		MekanismGenerators-1.15.2-9.10.7.420.jar Mekanism: Generators {mekanismgenerators@9.10.7 DONE}
		Hwyla-forge-1.10.8-B72_1.15.2.jar Waila {waila@version DONE}
		jei-1.15.2-6.0.0.4.jar Just Enough Items {jei@6.0.0.4 DONE}
		simplylight-1.15.2-0.9.0.jar Simply Light {simplylight@1.15.2-0.9.0 DONE}
		Mekanism-1.15.2-9.10.7.420.jar Mekanism {mekanism@9.10.7 DONE}
		forge-1.15.2-31.2.0-universal.jar Forge {forge@31.2.0 DONE}
		paintings-1.15.2-7.0.0.0.jar Paintings ++ {paintings@1.14.4-6.0.1.5 DONE}
		WAWLA-1.15.2-3.0.2.jar WAWLA {wawla@3.0.2 DONE}
		pamhc2foodcore-1.15.2-1.0.3.jar Pam's HarvestCraft 2 Food Core {pamhc2foodcore@version DONE}
		roadstuff-1.15.2-3.1.0.jar Road Stuff {roadstuff@1.15.2-3.1.0 DONE}
		journeymap-1.15.2-5.7.0b2.jar Journeymap {journeymap@5.7.0b2 DONE}
		[1.15.2] SecurityCraft v1.8.18.1.jar SecurityCraft {securitycraft@v1.8.18.1 DONE}
	Player Count: 0 / 20; []
	Data Packs: mod:bookshelf (incompatible), mod:pamhc2trees (incompatible), mod:mekanismtools, mod:mekanismadditions, mod:pamhc2crops (incompatible), mod:cfm (incompatible), mod:appleskin (incompatible), mod:mapperbase, mod:mekanismgenerators, mod:waila (incompatible), mod:jei (incompatible), mod:simplylight (incompatible), mod:mekanism, mod:forge (incompatible), mod:paintings (incompatible), mod:wawla (incompatible), mod:pamhc2foodcore (incompatible), mod:roadstuff (incompatible), mod:journeymap (incompatible), mod:securitycraft (incompatible), vanilla, file/bukkit
	Is Modded: Definitely; Server brand changed to 'Mohist'
	Type: Dedicated Server (map_server.txt)

**Comment by magic0whi** [comment]
+1, 47e9550 still won't fix

**Comment by Mgazul** [comment]
fixed
