### ISSUE TITLE
[1.20.1] Bluemap Failed to load world

### ISSUE THREAD

**Issue by Jerry12228** [Teneted/Tenet#3209]
﻿

﻿

﻿

﻿
**Minecraft Version :** 1.20.1
﻿
**Mohist Version :** 757 (download from ci server)
﻿
**Operating System :** Centos 7.9
﻿
**Concerned mod / plugin** : Bluemap 5.0  (you could find it on https://www.spigotmc.org/)
﻿
**Logs :** It's very short, so I posted it here
for BlueMap
这是其中一个世界的报错, 另一个雷同
```
################################
 There is a problem with your BlueMap setup!
 Failed to load world world/DIM1#minecraft:the_end!
 Is the level.dat of that world present and not corrupted?
################################
[13:51:23 ERROR]: [BlueMap] Detailed error:
de.bluecolored.bluemap.common.config.ConfigurationException: java.nio.file.NoSuchFileException: world/DIM1/level.dat
        at de.bluecolored.bluemap.common.BlueMapService.loadMap(BlueMapService.java:230) ~[?:?]
        at de.bluecolored.bluemap.common.BlueMapService.getOrLoadMaps(BlueMapService.java:166) ~[?:?]
        at de.bluecolored.bluemap.common.BlueMapService.getOrLoadMaps(BlueMapService.java:149) ~[?:?]
        at de.bluecolored.bluemap.common.plugin.Plugin.load(Plugin.java:188) ~[?:?]
        at de.bluecolored.bluemap.common.plugin.Plugin.load(Plugin.java:113) ~[?:?]
        at de.bluecolored.bluemap.bukkit.BukkitPlugin.lambda$onEnable$0(BukkitPlugin.java:147) ~[?:?]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:78) [forge-1.20.1-47.3.1-universal.jar%23211!/:?]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:55) [forge-1.20.1-47.3.1-universal.jar%23211!/:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
        at java.lang.Thread.run(Thread.java:840) [?:?]
Caused by: java.nio.file.NoSuchFileException: world/DIM1/level.dat
        at sun.nio.fs.UnixException.translateToIOException(UnixException.java:92) ~[?:?]
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106) ~[?:?]
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111) ~[?:?]
        at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:218) ~[?:?]
        at java.nio.file.Files.newByteChannel(Files.java:380) ~[?:?]
        at java.nio.file.Files.newByteChannel(Files.java:432) ~[?:?]
        at java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:422) ~[?:?]
        at java.nio.file.Files.newInputStream(Files.java:160) ~[?:?]
        at de.bluecolored.bluemap.core.world.mca.MCAWorld.load(MCAWorld.java:270) ~[?:?]
        at de.bluecolored.bluemap.common.BlueMapService.loadMap(BlueMapService.java:227) ~[?:?]
        ... 10 more
```

﻿
﻿
**Steps to Reproduce :**
setup plugins and start server
﻿
**Description of issue :** 
这个插件无法加载末地和下界这两个世界
﻿

**Comment by starxjys** [comment]
可复现。
补充信息：

BlueMap-5.3-spigot.jar报错同上
BlueMap-5.3-paper.jar报错：
![image](https://github.com/user-attachments/assets/bcfd9a58-6d70-4690-9820-a4458f1b1c39)
```
[18:50:46 INFO]: [BlueMap] 小小墨正在连接 BlueMap v5.3 插件
[18:50:46 INFO]: [BlueMap] Saving all worlds once, to make sure the level.dat is present...
[18:50:46 WARN]: A manual (plugin-induced) save has been detected while server is configured to auto-save. This may affect performance.
[18:50:47 ERROR]: [BlueMap] 插件 BlueMap v5.3 在尝试为 class de.bluecolored.bluemap.bukkit.BukkitPlugin 注册事件时失败，因为 com/mohistmc/paper/threadedregions/scheduler/ScheduledTask 不存在。
[18:50:47 INFO]: [BlueMap] Loading...
[18:50:47 INFO]: [OpenInv] 小小墨正在连接 OpenInv v4.4.1 插件
[18:50:47 WARN]: Exception in thread "BlueMap-Load" java.lang.NoSuchMethodError: 'java.lang.String org.bukkit.Bukkit.getMinecraftVersion()'
[18:50:47 WARN]:        at de.bluecolored.bluemap.bukkit.BukkitPlugin.getMinecraftVersion(BukkitPlugin.java:161)
[18:50:47 WARN]:        at de.bluecolored.bluemap.common.plugin.Plugin.load(Plugin.java:132)
[18:50:47 WARN]:        at de.bluecolored.bluemap.common.plugin.Plugin.load(Plugin.java:113)
[18:50:47 WARN]:        at de.bluecolored.bluemap.bukkit.BukkitPlugin.lambda$onEnable$0(BukkitPlugin.java:136)
[18:50:47 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
```
forge版可正常使用。

spigot版和paper版在paper中验证功能正常。

**Comment by eerr992** [comment]
使用forge版吧,反正没区别

**Comment by glowingstone124** [comment]
原因是paper/spigot世界格式和forge不一致，bluemap报错则是因为call了mohist未实现的paper方法，这两个问题都不在未来的修复计划之内，请使用forge版来避免问题。
