### ISSUE TITLE
[1.15.2] Not compatible with forge message channel

### ISSUE THREAD

**Issue by denireilly** [Teneted/Tenet#322]
[04Jun2020 16:43:23.488] [User Authenticator #1/INFO] [net.minecraft.network.login.ServerLoginNetHandler/]: UUID of player SeaportSlime is 49ccf2c3-d57d-4a0f-bd40-537d3d73076c
[04Jun2020 16:43:23.534] [Netty Server IO #2/INFO] [journeymap/]: Dev Mode?
[04Jun2020 16:43:25.288] [Server thread/INFO] [net.minecraftforge.common.AdvancementLoadFix/]: Using new advancement loading for net.minecraft.advancements.PlayerAdvancements@5667f57b
[04Jun2020 16:43:25.372] [Server thread/INFO] [Waila/]: Syncing config to SeaportSlime (49ccf2c3-d57d-4a0f-bd40-537d3d73076c)
[04Jun2020 16:43:25.377] [Server thread/INFO] [net.minecraft.server.management.PlayerList/]: SeaportSlime[/127.0.0.1:57228] logged in with entity id 20 at ([world]-249.39263098217464, 60.15013696724972, -82.00779254321634)
[04Jun2020 16:43:25.396] [Netty Server IO #2/ERROR] [net.minecraft.command.arguments.ArgumentTypes/]: Could not serialize net.minecraftforge.server.command.ModIdArgument@2e53fd1 (class net.minecraftforge.server.command.ModIdArgument) - will not be sent to client!
[04Jun2020 16:43:25.396] [Netty Server IO #2/ERROR] [net.minecraft.command.arguments.ArgumentTypes/]: Could not serialize net.minecraftforge.server.command.EnumArgument@e945d47 (class net.minecraftforge.server.command.EnumArgument) - will not be sent to client!
[04Jun2020 16:43:27.982] [Server thread/ERROR] [net.minecraft.network.play.ServerPlayNetHandler/]: Couldn't register custom payload
java.lang.IllegalArgumentException: Channel must contain : separator (attempted to use )
	at org.bukkit.plugin.messaging.StandardMessenger.validateAndCorrectChannel(StandardMessenger.java:503) ~[?:?]
	at org.bukkit.craftbukkit.entity.CraftPlayer.addChannel(CraftPlayer.java:1229) ~[?:?]
	at net.minecraft.network.play.ServerPlayNetHandler.func_147349_a(ServerPlayNetHandler.java:2304) ~[?:?]
	at net.minecraft.network.play.client.CCustomPayloadPacket.func_148833_a(CCustomPayloadPacket.java:42) ~[?:?]
	at net.minecraft.network.play.client.CCustomPayloadPacket.func_148833_a(CCustomPayloadPacket.java:12) ~[?:?]
	at net.minecraft.network.PacketThreadUtil.lambda$checkThreadAndEnqueue$0(PacketThreadUtil.java:22) ~[?:?]
	at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) [?:?]
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) [?:?]
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:880) [?:?]
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:154) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) [?:?]
	at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:863) [?:?]
	at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:857) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(SourceFile:127) [?:?]
	at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:843) [?:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:779) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_151]
[04Jun2020 16:43:27.986] [Server thread/INFO] [net.minecraft.network.play.ServerPlayNetHandler/]: SeaportSlime lost connection: Invalid payload REGISTER!
[04Jun2020 16:43:27.995] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer/]: Ã?ÂSeaportSlime left the game
[04Jun2020 16:43:28.079] [Server thread/INFO] [net.minecraft.network.play.ServerPlayNetHandler/]: SeaportSlime lost connection: Invalid payload REGISTER!
[04Jun2020 16:43:28.080] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer/]: Ã?ÂSeaportSlime left the game

**Comment by Mgazul** [comment]
I know
