### ISSUE TITLE
This error occurs on Mohist Build 542 when using dynmap v3.0-SNAPSHOT-mohist and Dynmap-Essentials-HEAD module

### ISSUE THREAD

**Issue by Maks-Haswell** [Teneted/Tenet#324]
[08:39:44] [Server thread/ERROR] [Mohist]: Could not pass event WorldLoadEvent to dynmap v3.0-SNAPSHOT-mohist
org.bukkit.event.EventException: null
	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:38) ~[MethodHandleEventExecutor.class:1.12.2-8493328]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[TimedEventExecutor.class:1.12.2-8493328]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66) ~[RegisteredListener.class:1.12.2-8493328]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [SimplePluginManager.class:1.12.2-8493328]
	at net.minecraftforge.common.DimensionManager.initDimension(DimensionManager.java:320) [DimensionManager.class:1.12.2-8493328]
	at net.minecraft.server.MinecraftServer.func_71218_a(MinecraftServer.java:979) [MinecraftServer.class:?]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.getWorld(CraftServer.java:1075) [CraftServer.class:1.12.2-8493328]
	at com.earth2me.essentials.EssentialsConf.getLocation(EssentialsConf.java:357) [EssentialsX-2.17.2.0.jar:?]
	at com.earth2me.essentials.UserData.getHome(UserData.java:169) [EssentialsX-2.17.2.0.jar:?]
	at org.dynmap.essentials.DynmapEssentialsPlugin$HomesLayer.getMarkers(DynmapEssentialsPlugin.java:263) [Dynmap-Essentials-HEAD.jar:?]
	at org.dynmap.essentials.DynmapEssentialsPlugin$Layer.updateMarkerSet(DynmapEssentialsPlugin.java:118) [Dynmap-Essentials-HEAD.jar:?]
	at org.dynmap.essentials.DynmapEssentialsPlugin.updateMarkers(DynmapEssentialsPlugin.java:314) [Dynmap-Essentials-HEAD.jar:?]
	at org.dynmap.essentials.DynmapEssentialsPlugin.access$300(DynmapEssentialsPlugin.java:38) [Dynmap-Essentials-HEAD.jar:?]
	at org.dynmap.essentials.DynmapEssentialsPlugin$MarkerUpdate.run(DynmapEssentialsPlugin.java:298) [Dynmap-Essentials-HEAD.jar:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:64) [CraftTask.class:1.12.2-8493328]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:422) [CraftScheduler.class:1.12.2-8493328]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:830) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:466) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:778) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:624) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
Caused by: java.lang.ArrayIndexOutOfBoundsException: 15
	at org.dynmap.bukkit.helper.BukkitWorld.<init>(BukkitWorld.java:41) ~[?:?]
	at org.dynmap.bukkit.helper.BukkitWorld.<init>(BukkitWorld.java:30) ~[?:?]
	at org.dynmap.bukkit.DynmapPlugin.getWorld(DynmapPlugin.java:154) ~[?:?]
	at org.dynmap.bukkit.DynmapPlugin.access$300(DynmapPlugin.java:108) ~[?:?]
	at org.dynmap.bukkit.DynmapPlugin$19.onWorldLoad(DynmapPlugin.java:1502) ~[?:?]
	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:36) ~[MethodHandleEventExecutor.class:1.12.2-8493328]
	... 20 more

**Comment by TansuoTro** [comment]
The Dynmap-Essentials-HEAD module is not compatible with the special version of mohist dynmap,
 and cannot be repaired in a short time, which takes a little time.
