### ISSUE TITLE
1.20.1 救救孩子的NPC插件吧

### ISSUE THREAD

**Issue by windy664** [Teneted/Tenet#3257]
**Minecraft Version :** 1.20.1

**Mohist Version :** 796

**Operating System :** Provide the name of your OS

**Concerned mod / plugin** : Provide mod / plugin name and download link if possible

**Logs :** Link(s) of logs and crash reports if you have

**Steps to Reproduce :**
 1. Do this
 2. Then do that
 3. ...

**Description of issue :** Give all details about your issue

尝试过 公民2 跑不了 下面这个znpc也是跑不了

ady能跑，但是有时候npc会消失

[07:58:55] [Server thread/INFO] [io.github.gonalez.znpcs.ServersNPC]: [ServersNPC] 小小墨正在连接 ServersNPC v4.7 插件
[07:58:55] [Server thread/ERROR] [Minecraft]: Error occurred while enabling ServersNPC v4.7 (Is it up to date?)
java.lang.ExceptionInInitializerError: null
	at io.github.gonalez.znpcs.commands.Command.<clinit>(Command.java:33) ~[?:?]
	at io.github.gonalez.znpcs.ServersNPC.onEnable(ServersNPC.java:71) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:347) ~[forge-1.20.1-47.3.5-universal.jar%23357!/:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) ~[forge-1.20.1-47.3.5-universal.jar%23357!/:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[forge-1.20.1-47.3.5-universal.jar%23357!/:?]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:547) ~[forge-1.20.1-47.3.5-universal.jar%23357!/:997de31d-ddc9a2dad-d2eba2c8-47.1.105]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:461) ~[forge-1.20.1-47.3.5-universal.jar%23357!/:997de31d-ddc9a2dad-d2eba2c8-47.1.105]
	at net.minecraft.server.MinecraftServer.m_129815_(MinecraftServer.java:444) ~[server-1.20.1-20230612.114412-srg.jar%23352!/:?]
	at net.minecraft.server.MinecraftServer.m_130006_(MinecraftServer.java:344) ~[server-1.20.1-20230612.114412-srg.jar%23352!/:?]
	at net.minecraft.server.dedicated.DedicatedServer.m_7038_(DedicatedServer.java:232) ~[server-1.20.1-20230612.114412-srg.jar%23352!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:853) ~[server-1.20.1-20230612.114412-srg.jar%23352!/:?]
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:284) ~[server-1.20.1-20230612.114412-srg.jar%23352!/:?]
	at java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.lang.StringIndexOutOfBoundsException: Index 0 out of bounds for length 0
	at jdk.internal.util.Preconditions$1.apply(Preconditions.java:55) ~[?:?]
	at jdk.internal.util.Preconditions$1.apply(Preconditions.java:52) ~[?:?]
	at jdk.internal.util.Preconditions$4.apply(Preconditions.java:213) ~[?:?]
	at jdk.internal.util.Preconditions$4.apply(Preconditions.java:210) ~[?:?]
	at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:98) ~[?:?]
	at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:106) ~[?:?]
	at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:302) ~[?:?]
	at java.lang.String.checkIndex(String.java:4832) ~[?:?]
	at java.lang.StringLatin1.charAt(StringLatin1.java:46) ~[?:?]
	at java.lang.String.charAt(String.java:1555) ~[?:?]
	at org.objectweb.asm.Type.getObjectType(Type.java:253) ~[asm-9.7.jar:?]
	at org.objectweb.asm.commons.Remapper.mapType(Remapper.java:99) ~[asm-commons-9.7.jar:?]
	at com.mohistmc.bukkit.remapping.ReflectionHandler_24.redirectClassForName(ReflectionHandler.java:226) ~[forge-1.20.1-47.3.5-universal.jar%23357!/:?]
	at com.mohistmc.bukkit.remapping.ReflectionHandler_24.redirectClassForName(ReflectionHandler.java:220) ~[forge-1.20.1-47.3.5-universal.jar%23357!/:?]
	at io.github.gonalez.znpcs.cache.TypeCache$BaseCache.<init>(TypeCache.java:164) ~[?:?]
	at io.github.gonalez.znpcs.cache.TypeCache$BaseCache$MethodLoader.<init>(TypeCache.java:209) ~[?:?]
	at io.github.gonalez.znpcs.cache.CacheRegistry.<clinit>(CacheRegistry.java:803) ~[?:?]
	... 13 more
[07:58:55] [Server thread/INFO] [io.github.gonalez.znpcs.ServersNPC]: [ServersNPC] 小小墨正在与 ServersNPC v4.7 插件断开连接
[07:58:55] [Server thread/ERROR] [Minecraft]: Error occurred while disabling ServersNPC v4.7 (Is it up to date?)
java.lang.NoClassDefFoundError: Could not initialize class io.github.gonalez.znpcs.cache.CacheRegistry
	at io.github.gonalez.znpcs.npc.NPCType.<clinit>(NPCType.java:19) ~[?:?]
	at jdk.internal.misc.Unsafe.ensureClassInitialized0(Native Method) ~[?:?]
	at jdk.internal.misc.Unsafe.ensureClassInitialized(Unsafe.java:1160) ~[?:?]
	at jdk.internal.reflect.MethodHandleAccessorFactory.ensureClassInitialized(MethodHandleAccessorFactory.java:300) ~[?:?]
	at jdk.internal.reflect.MethodHandleAccessorFactory.newFieldAccessor(MethodHandleAccessorFactory.java:140) ~[?:?]
	at jdk.internal.reflect.ReflectionFactory.newFieldAccessor(ReflectionFactory.java:145) ~[?:?]
	at java.lang.reflect.Field.acquireOverrideFieldAccessor(Field.java:1200) ~[?:?]
	at java.lang.reflect.Field.getOverrideFieldAccessor(Field.java:1169) ~[?:?]
	at java.lang.reflect.Field.get(Field.java:444) ~[?:?]
	at com.google.gson.internal.bind.TypeAdapters$EnumTypeAdapter.<init>(TypeAdapters.java:886) ~[gson-2.10.jar%23154!/:?]
	at com.google.gson.internal.bind.TypeAdapters$29.create(TypeAdapters.java:930) ~[gson-2.10.jar%23154!/:?]
	at com.google.gson.Gson.getAdapter(Gson.java:546) ~[gson-2.10.jar%23154!/:?]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:160) ~[gson-2.10.jar%23154!/:?]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:295) ~[gson-2.10.jar%23154!/:?]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:130) ~[gson-2.10.jar%23154!/:?]
	at com.google.gson.Gson.getAdapter(Gson.java:546) ~[gson-2.10.jar%23154!/:?]
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory.create(CollectionTypeAdapterFactory.java:53) ~[gson-2.10.jar%23154!/:?]
	at com.google.gson.Gson.getAdapter(Gson.java:546) ~[gson-2.10.jar%23154!/:?]
	at com.google.gson.Gson.fromJson(Gson.java:1213) ~[gson-2.10.jar%23154!/:?]
	at com.google.gson.Gson.fromJson(Gson.java:1319) ~[gson-2.10.jar%23154!/:?]
	at com.google.gson.Gson.fromJson(Gson.java:1290) ~[gson-2.10.jar%23154!/:?]
	at io.github.gonalez.znpcs.configuration.Configuration.onLoad(Configuration.java:81) ~[?:?]
	at io.github.gonalez.znpcs.configuration.Configuration.<init>(Configuration.java:59) ~[?:?]
	at io.github.gonalez.znpcs.configuration.Configuration.<init>(Configuration.java:48) ~[?:?]
	at io.github.gonalez.znpcs.configuration.Configuration.<clinit>(Configuration.java:43) ~[?:?]
	at io.github.gonalez.znpcs.ServersNPC.onDisable(ServersNPC.java:83) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:349) ~[forge-1.20.1-47.3.5-universal.jar%23357!/:?]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:365) ~[forge-1.20.1-47.3.5-universal.jar%23357!/:?]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:508) ~[forge-1.20.1-47.3.5-universal.jar%23357!/:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:341) ~[forge-1.20.1-47.3.5-universal.jar%23357!/:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[forge-1.20.1-47.3.5-universal.jar%23357!/:?]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:547) ~[forge-1.20.1-47.3.5-universal.jar%23357!/:997de31d-ddc9a2dad-d2eba2c8-47.1.105]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:461) ~[forge-1.20.1-47.3.5-universal.jar%23357!/:997de31d-ddc9a2dad-d2eba2c8-47.1.105]
	at net.minecraft.server.MinecraftServer.m_129815_(MinecraftServer.java:444) ~[server-1.20.1-20230612.114412-srg.jar%23352!/:?]
	at net.minecraft.server.MinecraftServer.m_130006_(MinecraftServer.java:344) ~[server-1.20.1-20230612.114412-srg.jar%23352!/:?]
	at net.minecraft.server.dedicated.DedicatedServer.m_7038_(DedicatedServer.java:232) ~[server-1.20.1-20230612.114412-srg.jar%23352!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:853) ~[server-1.20.1-20230612.114412-srg.jar%23352!/:?]
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:284) ~[server-1.20.1-20230612.114412-srg.jar%23352!/:?]
	at java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.StringIndexOutOfBoundsException: Index 0 out of bounds for length 0 [in thread "Server thread"]
	at jdk.internal.util.Preconditions$1.apply(Preconditions.java:55) ~[?:?]
	at jdk.internal.util.Preconditions$1.apply(Preconditions.java:52) ~[?:?]
	at jdk.internal.util.Preconditions$4.apply(Preconditions.java:213) ~[?:?]
	at jdk.internal.util.Preconditions$4.apply(Preconditions.java:210) ~[?:?]
	at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:98) ~[?:?]
	at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:106) ~[?:?]
	at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:302) ~[?:?]
	at java.lang.String.checkIndex(String.java:4832) ~[?:?]
	at java.lang.StringLatin1.charAt(StringLatin1.java:46) ~[?:?]
	at java.lang.String.charAt(String.java:1555) ~[?:?]
	at org.objectweb.asm.Type.getObjectType(Type.java:253) ~[asm-9.7.jar:?]
	at org.objectweb.asm.commons.Remapper.mapType(Remapper.java:99) ~[asm-commons-9.7.jar:?]
	at com.mohistmc.bukkit.remapping.ReflectionHandler_24.redirectClassForName(ReflectionHandler.java:226) ~[forge-1.20.1-47.3.5-universal.jar%23357!/:?]
	at com.mohistmc.bukkit.remapping.ReflectionHandler_24.redirectClassForName(ReflectionHandler.java:220) ~[forge-1.20.1-47.3.5-universal.jar%23357!/:?]
	at io.github.gonalez.znpcs.cache.TypeCache$BaseCache.<init>(TypeCache.java:164) ~[?:?]
	at io.github.gonalez.znpcs.cache.TypeCache$BaseCache$MethodLoader.<init>(TypeCache.java:209) ~[?:?]
	at io.github.gonalez.znpcs.cache.CacheRegistry.<clinit>(CacheRegistry.java:803) ~[?:?]
	at io.github.gonalez.znpcs.commands.Command.<clinit>(Command.java:33) ~[?:?]
	at io.github.gonalez.znpcs.ServersNPC.onEnable(ServersNPC.java:71) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:347) ~[forge-1.20.1-47.3.5-universal.jar%23357!/:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) ~[forge-1.20.1-47.3.5-universal.jar%23357!/:?]
	... 9 more

**Comment by hu7x** [comment]
https://ci.citizensnpcs.co/job/Citizens2/3178/
使用这个版本的Citizens
