### ISSUE TITLE
[1.20.1] HappyHud not working

### ISSUE THREAD

**Issue by iSoulEs** [Teneted/Tenet#3266]
**Minecraft Version :** 1.20.1

**Mohist Version :** 811

**Operating System :** Windows 10

**Concerned mod / plugin** : HappyHUD-1.0.13-RELEASE, ItemsAdder_3.6.4-release-3, LoneLibs, MMOCore-1.12.1-52, MMOItems-6.10-24, ModelEngine-4.0.6, MythicLib-dist-1.6.2-58, MythicMobs-5.6.2, PlaceholderAPI-2.11.6, ProtocolLib
NO MODS

**Logs :** 
[latest.log](https://github.com/user-attachments/files/16409415/latest.log)

**Steps to Reproduce :**
 1. Create a customhud with happyhud
 2. stop and start the server, put the resourcepack
 3. the hud is not working due the bukkit event.

**Description of issue :** 

[04:56:44] [Server thread/ERROR] [Minecraft]: Could not pass event PlayerJoinEvent to HappyHUD v1.0.13-RELEASE
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:305) ~[forge-1.20.1-47.3.5-universal.jar%23203!/:?]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[forge-1.20.1-47.3.5-universal.jar%23203!/:?]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:603) ~[forge-1.20.1-47.3.5-universal.jar%23203!/:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:587) ~[forge-1.20.1-47.3.5-universal.jar%23203!/:?]
	at net.minecraft.server.players.PlayerList.m_11261_(PlayerList.java:272) ~[server-1.20.1-20230612.114412-srg.jar%23198!/:?]
	at net.minecraft.server.network.ServerLoginPacketListenerImpl.m_143699_(ServerLoginPacketListenerImpl.java:176) ~[server-1.20.1-20230612.114412-srg.jar%23198!/:?]
	at net.minecraft.server.network.ServerLoginPacketListenerImpl.m_10055_(ServerLoginPacketListenerImpl.java:163) ~[server-1.20.1-20230612.114412-srg.jar%23198!/:?]
	at net.minecraft.server.network.ServerLoginPacketListenerImpl.m_9933_(ServerLoginPacketListenerImpl.java:75) ~[server-1.20.1-20230612.114412-srg.jar%23198!/:?]
	at net.minecraft.network.Connection.m_129483_(Connection.java:272) ~[server-1.20.1-20230612.114412-srg.jar%23198!/:?]
	at net.minecraft.server.network.ServerConnectionListener.m_9721_(ServerConnectionListener.java:149) ~[server-1.20.1-20230612.114412-srg.jar%23198!/:?]
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:1172) ~[server-1.20.1-20230612.114412-srg.jar%23198!/:?]
	at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:360) ~[server-1.20.1-20230612.114412-srg.jar%23198!/:?]
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:1073) ~[server-1.20.1-20230612.114412-srg.jar%23198!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:909) ~[server-1.20.1-20230612.114412-srg.jar%23198!/:?]
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:285) ~[server-1.20.1-20230612.114412-srg.jar%23198!/:?]
	at java.lang.Thread.run(Thread.java:842) [?:?]
Caused by: java.lang.NullPointerException: Player is offline
	at java.util.Objects.requireNonNull(Objects.java:233) ~[?:?]
	at io.lumine.mythic.lib.api.player.MMOPlayerData.getPlayer(MMOPlayerData.java:301) ~[MythicLib-dist-1.6.2-58.jar:?]
	at io.lumine.mythic.lib.api.stat.handler.AttributeStatHandler.getFinalValue(AttributeStatHandler.java:72) ~[MythicLib-dist-1.6.2-58.jar:?]
	at io.lumine.mythic.lib.api.stat.StatInstance.getFinal(StatInstance.java:64) ~[MythicLib-dist-1.6.2-58.jar:?]
	at io.lumine.mythic.lib.api.stat.StatInstance.formatFinal(StatInstance.java:69) ~[MythicLib-dist-1.6.2-58.jar:?]
	at io.lumine.mythic.lib.manager.StatManager.format(StatManager.java:108) ~[MythicLib-dist-1.6.2-58.jar:?]
	at net.Indyuce.mmoitems.comp.placeholders.MMOItemsPlaceholders.onRequest(MMOItemsPlaceholders.java:84) ~[MMOItems-6.10-24.jar:?]
	at me.clip.placeholderapi.replacer.CharsReplacer.apply(CharsReplacer.java:119) ~[PlaceholderAPI-2.11.6.jar:?]
	at me.clip.placeholderapi.PlaceholderAPI.setBracketPlaceholders(PlaceholderAPI.java:126) ~[PlaceholderAPI-2.11.6.jar:?]
	at ch.andre601.mathexpansion.MathExpansion.onRequest(MathExpansion.java:82) ~[?:?]
	at me.clip.placeholderapi.replacer.CharsReplacer.apply(CharsReplacer.java:119) ~[PlaceholderAPI-2.11.6.jar:?]
	at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:71) ~[PlaceholderAPI-2.11.6.jar:?]
	at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:99) ~[PlaceholderAPI-2.11.6.jar:?]
	at com.ehhthan.happyhud.comp.parser.PlaceholderAPIParser.parse(PlaceholderAPIParser.java:10) ~[?:?]
	at com.ehhthan.happyhud.manager.ParserManager.parse(ParserManager.java:30) ~[?:?]
	at com.ehhthan.happyhud.api.hud.active.layer.TextActiveLayer.lambda$new$0(TextActiveLayer.java:38) ~[?:?]
	at com.ehhthan.happyhud.api.hud.active.layer.TextActiveLayer.update(TextActiveLayer.java:56) ~[?:?]
	at com.ehhthan.happyhud.api.hud.active.layer.TextActiveLayer.<init>(TextActiveLayer.java:43) ~[?:?]
	at com.ehhthan.happyhud.api.hud.active.layer.ActiveLayer.getLayer(ActiveLayer.java:27) ~[?:?]
	at com.ehhthan.happyhud.api.hud.active.element.ActiveElement.<init>(ActiveElement.java:34) ~[?:?]
	at com.ehhthan.happyhud.api.hud.active.element.ActiveLayout.<init>(ActiveLayout.java:22) ~[?:?]
	at com.ehhthan.happyhud.api.HudHolder.reloadLayouts(HudHolder.java:81) ~[?:?]
	at com.ehhthan.happyhud.api.HudHolder.initialize(HudHolder.java:47) ~[?:?]
	at com.ehhthan.happyhud.manager.HudHolderManager.onJoin(HudHolderManager.java:74) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:303) ~[forge-1.20.1-47.3.5-universal.jar%23203!/:?]
	... 15 more

**Comment by Unitei-Dev** [comment]
HappyHud is a bad plugin, use BetterHud https://www.spigotmc.org/resources/%E2%AD%90betterhud%E2%AD%90a-beautiful-hud-plugin-you-havent-seen-before%E2%9C%85auto-resource-pack-build%E2%9C%85.115559/

**Comment by iSoulEs** [comment]
> BetterHud

thnx! a will try

**Comment by iSoulEs** [comment]
Fixed with a replace, use BetterHud instead HappyHud!.  BetterHud is free and better.
