### ISSUE TITLE
[1.20.2] 精灵宝可梦模组的储存包包的问题

### ISSUE THREAD

**Issue by yuankun1** [Teneted/Tenet#3268]
核心mohist-1.20.2-164-server
模组:Pixelmon-1.20.2-9.2.8-server
插件: CobblemonInfo
我用CobblemonInfo插件吧精灵转换成精灵照片 放到 精灵宝可梦模组自带的包包 放进去打开看来直接报错
已经有给玩家的包包已经打不开了
[21:43:31 ERROR]: Failed to handle packet net.minecraft.network.protocol.game.ServerboundUseItemPacket@42ed1142, suppressing error
java.lang.IllegalArgumentException: Invalid PacketBuffer for openGui, found 33586 bytes
        at net.minecraftforge.common.extensions.IForgeServerPlayer.openMenu(IForgeServerPlayer.java:71) ~[forge-1.20.2-48.1.0-universal.jar%23163!/:?]
        at com.pixelmonmod.pixelmon.items.PokeBagItem.openPokeBag(PokeBagItem.java:95) ~[Pixelmon-1.20.2-9.2.8-server.jar%23156!/:9.2.8-pipe23961]
        at com.pixelmonmod.pixelmon.items.PokeBagItem.m_7203_(PokeBagItem.java:50) ~[Pixelmon-1.20.2-9.2.8-server.jar%23156!/:9.2.8-pipe23961]
        at net.minecraft.world.item.ItemStack.m_41682_(ItemStack.java:333) ~[server-1.20.2-20230921.100330-srg.jar%23158!/:?]
        at net.minecraft.server.level.ServerPlayerGameMode.m_6261_(ServerPlayerGameMode.java:376) ~[server-1.20.2-20230921.100330-srg.jar%23158!/:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.m_5760_(ServerGamePacketListenerImpl.java:1544) ~[server-1.20.2-20230921.100330-srg.jar%23158!/:?]
        at net.minecraft.network.protocol.game.ServerboundUseItemPacket.m_5797_(ServerboundUseItemPacket.java:29) ~[server-1.20.2-20230921.100330-srg.jar%23158!/:?]
        at net.minecraft.network.protocol.game.ServerboundUseItemPacket.m_5797_(ServerboundUseItemPacket.java:7) ~[server-1.20.2-20230921.100330-srg.jar%23158!/:?]
        at net.minecraft.network.protocol.PacketUtils.m_292130_(PacketUtils.java:23) ~[server-1.20.2-20230921.100330-srg.jar%23158!/:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[server-1.20.2-20230921.100330-srg.jar%23158!/:?]
        at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:156) ~[server-1.20.2-20230921.100330-srg.jar%23158!/:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[server-1.20.2-20230921.100330-srg.jar%23158!/:?]
        at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:1028) ~[server-1.20.2-20230921.100330-srg.jar%23158!/:?]
        at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:169) ~[server-1.20.2-20230921.100330-srg.jar%23158!/:?]
        at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:130) ~[server-1.20.2-20230921.100330-srg.jar%23158!/:?]
        at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:1011) ~[server-1.20.2-20230921.100330-srg.jar%23158!/:?]
        at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:1005) ~[server-1.20.2-20230921.100330-srg.jar%23158!/:?]
        at net.minecraft.util.thread.BlockableEventLoop.m_18699_(BlockableEventLoop.java:115) ~[server-1.20.2-20230921.100330-srg.jar%23158!/:?]
        at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:990) ~[server-1.20.2-20230921.100330-srg.jar%23158!/:?]
        at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:907) ~[server-1.20.2-20230921.100330-srg.jar%23158!/:?]
        at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:276) ~[server-1.20.2-20230921.100330-srg.jar%23158!/:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
[21:43:32 ERROR]: Failed to handle packet net.minecraft.network.protocol.game.ServerboundUseItemPacket@7bf9a691, suppressing error
java.lang.IllegalArgumentException: Invalid PacketBuffer for openGui, found 33586 bytes
        at net.minecraftforge.common.extensions.IForgeServerPlayer.openMenu(IForgeServerPlayer.java:71) ~[forge-1.20.2-48.1.0-universal.jar%23163!/:?]
        at com.pixelmonmod.pixelmon.items.PokeBagItem.openPokeBag(PokeBagItem.java:95) ~[Pixelmon-1.20.2-9.2.8-server.jar%23156!/:9.2.8-pipe23961]
        at com.pixelmonmod.pixelmon.items.PokeBagItem.m_7203_(PokeBagItem.java:50) ~[Pixelmon-1.20.2-9.2.8-server.jar%23156!/:9.2.8-pipe23961]
        at net.minecraft.world.item.ItemStack.m_41682_(ItemStack.java:333) ~[server-1.20.2-20230921.100330-srg.jar%23158!/:?]
        at net.minecraft.server.level.ServerPlayerGameMode.m_6261_(ServerPlayerGameMode.java:376) ~[server-1.20.2-20230921.100330-srg.jar%23158!/:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.m_5760_(ServerGamePacketListenerImpl.java:1544) ~[server-1.20.2-20230921.100330-srg.jar%23158!/:?]
        at net.minecraft.network.protocol.game.ServerboundUseItemPacket.m_5797_(ServerboundUseItemPacket.java:29) ~[server-1.20.2-20230921.100330-srg.jar%23158!/:?]
        at net.minecraft.network.protocol.game.ServerboundUseItemPacket.m_5797_(ServerboundUseItemPacket.java:7) ~[server-1.20.2-20230921.100330-srg.jar%23158!/:?]
        at net.minecraft.network.protocol.PacketUtils.m_292130_(PacketUtils.java:23) ~[server-1.20.2-20230921.100330-srg.jar%23158!/:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[server-1.20.2-20230921.100330-srg.jar%23158!/:?]
        at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:156) ~[server-1.20.2-20230921.100330-srg.jar%23158!/:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[server-1.20.2-20230921.100330-srg.jar%23158!/:?]
        at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:1028) ~[server-1.20.2-20230921.100330-srg.jar%23158!/:?]
        at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:169) ~[server-1.20.2-20230921.100330-srg.jar%23158!/:?]
        at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:130) ~[server-1.20.2-20230921.100330-srg.jar%23158!/:?]
        at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:1011) ~[server-1.20.2-20230921.100330-srg.jar%23158!/:?]
        at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:1005) ~[server-1.20.2-20230921.100330-srg.jar%23158!/:?]
        at net.minecraft.util.thread.BlockableEventLoop.m_18701_(BlockableEventLoop.java:139) ~[server-1.20.2-20230921.100330-srg.jar%23158!/:?]
        at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:991) ~[server-1.20.2-20230921.100330-srg.jar%23158!/:?]
        at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:907) ~[server-1.20.2-20230921.100330-srg.jar%23158!/:?]
        at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:276) ~[server-1.20.2-20230921.100330-srg.jar%23158!/:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
[21:43:32 ERROR]: Failed to handle packet net.minecraft.network.protocol.game.ServerboundUseItemPacket@5134cfad, suppressing error
java.lang.IllegalArgumentException: Invalid PacketBuffer for openGui, found 33586 bytes
        at net.minecraftforge.common.extensions.IForgeServerPlayer.openMenu(IForgeServerPlayer.java:71) ~[forge-1.20.2-48.1.0-universal.jar%23163!/:?]
        at com.pixelmonmod.pixelmon.items.PokeBagItem.openPokeBag(PokeBagItem.java:95) ~[Pixelmon-1.20.2-9.2.8-server.jar%23156!/:9.2.8-pipe23961]
        at com.pixelmonmod.pixelmon.items.PokeBagItem.m_7203_(PokeBagItem.java:50) ~[Pixelmon-1.20.2-9.2.8-server.jar%23156!/:9.2.8-pipe23961]
        at net.minecraft.world.item.ItemStack.m_41682_(ItemStack.java:333) ~[server-1.20.2-20230921.100330-srg.jar%23158!/:?]
        at net.minecraft.server.level.ServerPlayerGameMode.m_6261_(ServerPlayerGameMode.java:376) ~[server-1.20.2-20230921.100330-srg.jar%23158!/:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.m_5760_(ServerGamePacketListenerImpl.java:1544) ~[server-1.20.2-20230921.100330-srg.jar%23158!/:?]
        at net.minecraft.network.protocol.game.ServerboundUseItemPacket.m_5797_(ServerboundUseItemPacket.java:29) ~[server-1.20.2-20230921.100330-srg.jar%23158!/:?]
        at net.minecraft.network.protocol.game.ServerboundUseItemPacket.m_5797_(ServerboundUseItemPacket.java:7) ~[server-1.20.2-20230921.100330-srg.jar%23158!/:?]
        at net.minecraft.network.protocol.PacketUtils.m_292130_(PacketUtils.java:23) ~[server-1.20.2-20230921.100330-srg.jar%23158!/:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[server-1.20.2-20230921.100330-srg.jar%23158!/:?]
        at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:156) ~[server-1.20.2-20230921.100330-srg.jar%23158!/:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[server-1.20.2-20230921.100330-srg.jar%23158!/:?]
        at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:1028) ~[server-1.20.2-20230921.100330-srg.jar%23158!/:?]
        at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:169) ~[server-1.20.2-20230921.100330-srg.jar%23158!/:?]
        at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:130) ~[server-1.20.2-20230921.100330-srg.jar%23158!/:?]
        at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:1011) ~[server-1.20.2-20230921.100330-srg.jar%23158!/:?]
        at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:1005) ~[server-1.20.2-20230921.100330-srg.jar%23158!/:?]
        at net.minecraft.util.thread.BlockableEventLoop.m_18701_(BlockableEventLoop.java:139) ~[server-1.20.2-20230921.100330-srg.jar%23158!/:?]
        at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:991) ~[server-1.20.2-20230921.100330-srg.jar%23158!/:?]
        at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:907) ~[server-1.20.2-20230921.100330-srg.jar%23158!/:?]
        at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:276) ~[server-1.20.2-20230921.100330-srg.jar%23158!/:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]

**Comment by Akita041** [comment]
This is not a bug in Mohist, this is a bug in PixelmonMOD. The Pokemon backpack uses nbt to store data. When the data exceeds 32767bytes, the sent packets exceed the maximum limit and cannot be sent immediately. The client cannot accept processing, so please use a third-party fix, which may be considered a fix.Please Download at  [https://bbs.mc9y.net/resources/1063/](url)
