### ISSUE TITLE
[1.20.1] fabled 插件功能异常

### ISSUE THREAD

**Issue by Diauluo** [Teneted/Tenet#3274]
**Minecraft Version :1.20.1 Minecraft

**Mohist Version :Mohist-1.20.1-814-server

**Operating System : (Windows)

Description of issue :

fabled 插件的功能无法正常使用

[00:18:41 ERROR]: Could not pass event BlockBreakEvent to Fabled v1.0.0-R0.56-SNAPSHOT
java.lang.NoSuchMethodError: 'org.bukkit.entity.Item org.bukkit.World.dropItem(org.bukkit.Location, org.bukkit.inventory.ItemStack, java.util.function.Consumer)'
        at studio.magemonkey.fabled.dynamic.mechanic.ItemDropMechanic.execute(ItemDropMechanic.java:53) ~[?:?]
        at studio.magemonkey.fabled.dynamic.EffectComponent.executeChildren(EffectComponent.java:234) ~[?:?]
        at studio.magemonkey.fabled.dynamic.trigger.TriggerComponent.execute(TriggerComponent.java:47) ~[?:?]
        at studio.magemonkey.fabled.dynamic.trigger.TriggerComponent.trigger(TriggerComponent.java:27) ~[?:?]
        at studio.magemonkey.fabled.dynamic.TriggerHandler.trigger(TriggerHandler.java:157) ~[?:?]
        at studio.magemonkey.fabled.dynamic.TriggerHandler.apply(TriggerHandler.java:132) ~[?:?]
        at studio.magemonkey.fabled.dynamic.ComponentRegistry.lambda$register$0(ComponentRegistry.java:276) ~[?:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[forge-1.20.1-47.3.5-universal.jar%23229!/:?]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:603) ~[forge-1.20.1-47.3.5-universal.jar%23229!/:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:587) ~[forge-1.20.1-47.3.5-universal.jar%23229!/:?]
        at com.mohistmc.eventhandler.dispatcher.BlockEventDispatcher.onBlockBreak(BlockEventDispatcher.java:70) ~[forge-1.20.1-47.3.5-universal.jar%23229!/:?]
        at com.mohistmc.eventhandler.dispatcher.__BlockEventDispatcher_onBlockBreak_BreakEvent.invoke(.dynamic) ~[forge-1.20.1-47.3.5-universal.jar%23229!/:?]
        at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.5.jar%23150!/:?]
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:319) ~[eventbus-6.0.5.jar%23150!/:?]
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:299) ~[eventbus-6.0.5.jar%23150!/:?]
        at net.minecraftforge.common.ForgeHooks.onBlockBreakEvent(ForgeHooks.java:556) ~[forge-1.20.1-47.3.5-universal.jar%23229!/:?]
        at net.minecraft.server.level.ServerPlayerGameMode.m_9280_(ServerPlayerGameMode.java:321) ~[server-1.20.1-20230612.114412-srg.jar%23224!/:?]
        at net.minecraft.server.level.ServerPlayerGameMode.m_215116_(ServerPlayerGameMode.java:307) ~[server-1.20.1-20230612.114412-srg.jar%23224!/:?]
        at net.minecraft.server.level.ServerPlayerGameMode.m_214168_(ServerPlayerGameMode.java:275) ~[server-1.20.1-20230612.114412-srg.jar%23224!/:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.m_7502_(ServerGamePacketListenerImpl.java:1517) ~[server-1.20.1-20230612.114412-srg.jar%23224!/:?]
        at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.m_5797_(ServerboundPlayerActionPacket.java:42) ~[server-1.20.1-20230612.114412-srg.jar%23224!/:?]
        at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.m_5797_(ServerboundPlayerActionPacket.java:8) ~[server-1.20.1-20230612.114412-srg.jar%23224!/:?]
        at net.minecraft.network.protocol.PacketUtils.m_263899_(PacketUtils.java:25) ~[server-1.20.1-20230612.114412-srg.jar%23224!/:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[server-1.20.1-20230612.114412-srg.jar%23224!/:?]
        at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:151) ~[server-1.20.1-20230612.114412-srg.jar%23224!/:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[server-1.20.1-20230612.114412-srg.jar%23224!/:?]
        at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:1028) ~[server-1.20.1-20230612.114412-srg.jar%23224!/:?]
        at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:175) ~[server-1.20.1-20230612.114412-srg.jar%23224!/:?]
        at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:124) ~[server-1.20.1-20230612.114412-srg.jar%23224!/:?]
        at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:1011) ~[server-1.20.1-20230612.114412-srg.jar%23224!/:?]
        at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:1005) ~[server-1.20.1-20230612.114412-srg.jar%23224!/:?]
        at net.minecraft.util.thread.BlockableEventLoop.m_18701_(BlockableEventLoop.java:134) ~[server-1.20.1-20230612.114412-srg.jar%23224!/:?]
        at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:991) ~[server-1.20.1-20230612.114412-srg.jar%23224!/:?]
        at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:913) ~[server-1.20.1-20230612.114412-srg.jar%23224!/:?]
        at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:285) ~[server-1.20.1-20230612.114412-srg.jar%23224!/:?]
        at java.lang.Thread.run(Thread.java:1583) [?:?]

**Comment by Diauluo** [comment]
https://hub.spigotmc.org/javadocs/spigot/org/bukkit/World.html#dropItem(org.bukkit.Location,org.bukkit.inventory.ItemStack,java.util.function.Consumer)

**Comment by SNWCreations** [comment]
在最新版本无法复现
