### ISSUE TITLE
[1.20.1] ChunkByChunk world gen level.dat broken

### ISSUE THREAD

**Issue by Proxwian** [Teneted/Tenet#3276]
**Minecraft Version :** 1.20.1

**Mohist Version :** Any/Latest

**Operating System :** ubuntu

**Concerned mod / plugin** : ChunkByChunk

**Logs :** Link(s) of logs and crash reports if you have

**Steps to Reproduce :**
 1. Start server with ChunkByChunk
 2. Stop and run again
 3. Server can't start with error EoF exception

**Description of issue :** If start server with plain Forge core, it loads well

![image](https://github.com/user-attachments/assets/d481bfcd-8c2a-49e5-a5ed-65c6b24fca6b)

**Comment by Proxwian** [comment]
Deleting level.dat solves problem, but only for one restart and not always help

**Comment by Proxwian** [comment]
`[02:04:11 ERROR]: Failed to read chunk [-10, 6]
java.util.concurrent.CompletionException: net.minecraft.ReportedException: Loading NBT data
        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:332) ~[?:?]
        at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:347) ~[?:?]
        at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:636) ~[?:?]
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
        at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2162) ~[?:?]
        at com.mojang.datafixers.util.Either$Right.ifRight(Either.java:109) ~[datafixerupper-6.0.8.jar%23170!/:?]
        at net.minecraft.util.thread.ProcessorHandle.m_18717_(ProcessorHandle.java:29) ~[server-1.20.1-20230612.114412-srg.jar%23466!/:?]
        at net.minecraft.util.thread.ProcessorHandle$1.m_6937_(ProcessorHandle.java:44) ~[server-1.20.1-20230612.114412-srg.jar%23466!/:?]
        at net.minecraft.world.level.chunk.storage.IOWorker.m_223468_(IOWorker.java:236) ~[server-1.20.1-20230612.114412-srg.jar%23466!/:?]
        at net.minecraft.util.thread.StrictQueue$IntRunnable.run(StrictQueue.java:60) [server-1.20.1-20230612.114412-srg.jar%23466!/:?]
        at net.minecraft.util.thread.ProcessorMailbox.m_18759_(ProcessorMailbox.java:91) [server-1.20.1-20230612.114412-srg.jar%23466!/:?]
        at net.minecraft.util.thread.ProcessorMailbox.m_18747_(ProcessorMailbox.java:146) [server-1.20.1-20230612.114412-srg.jar%23466!/:?]
        at net.minecraft.util.thread.ProcessorMailbox.run(ProcessorMailbox.java:102) [server-1.20.1-20230612.114412-srg.jar%23466!/:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: net.minecraft.ReportedException: Loading NBT data
        at net.minecraft.nbt.CompoundTag.m_128413_(CompoundTag.java:479) ~[server-1.20.1-20230612.114412-srg.jar%23466!/:?]
        at net.minecraft.nbt.CompoundTag$1.m_7300_(CompoundTag.java:45) ~[server-1.20.1-20230612.114412-srg.jar%23466!/:?]
        at net.minecraft.nbt.CompoundTag$1.m_7300_(CompoundTag.java:32) ~[server-1.20.1-20230612.114412-srg.jar%23466!/:?]
        at net.minecraft.nbt.ListTag$1.m_7300_(ListTag.java:43) ~[server-1.20.1-20230612.114412-srg.jar%23466!/:?]
        at net.minecraft.nbt.ListTag$1.m_7300_(ListTag.java:26) ~[server-1.20.1-20230612.114412-srg.jar%23466!/:?]
        at net.minecraft.nbt.CompoundTag.m_128413_(CompoundTag.java:473) ~[server-1.20.1-20230612.114412-srg.jar%23466!/:?]
        at net.minecraft.nbt.CompoundTag$1.m_7300_(CompoundTag.java:45) ~[server-1.20.1-20230612.114412-srg.jar%23466!/:?]
        at net.minecraft.nbt.CompoundTag$1.m_7300_(CompoundTag.java:32) ~[server-1.20.1-20230612.114412-srg.jar%23466!/:?]
        at net.minecraft.nbt.NbtIo.m_128930_(NbtIo.java:153) ~[server-1.20.1-20230612.114412-srg.jar%23466!/:?]
        at net.minecraft.nbt.NbtIo.m_128934_(NbtIo.java:99) ~[server-1.20.1-20230612.114412-srg.jar%23466!/:?]
        at net.minecraft.nbt.NbtIo.m_128928_(NbtIo.java:95) ~[server-1.20.1-20230612.114412-srg.jar%23466!/:?]
        at net.minecraft.world.level.chunk.storage.RegionFileStorage.m_63706_(RegionFileStorage.java:65) ~[server-1.20.1-20230612.114412-srg.jar%23466!/:?]
        at net.minecraft.world.level.chunk.storage.IOWorker.m_223494_(IOWorker.java:186) ~[server-1.20.1-20230612.114412-srg.jar%23466!/:?]
        ... 8 more
Caused by: java.io.EOFException
        at java.io.DataInputStream.readByte(DataInputStream.java:273) ~[?:?]
        at net.minecraft.nbt.CompoundTag.m_128420_(CompoundTag.java:464) ~[server-1.20.1-20230612.114412-srg.jar%23466!/:?]
        at net.minecraft.nbt.CompoundTag$1.m_7300_(CompoundTag.java:41) ~[server-1.20.1-20230612.114412-srg.jar%23466!/:?]
        at net.minecraft.nbt.CompoundTag$1.m_7300_(CompoundTag.java:32) ~[server-1.20.1-20230612.114412-srg.jar%23466!/:?]
        at net.minecraft.nbt.CompoundTag.m_128413_(CompoundTag.java:473) ~[server-1.20.1-20230612.114412-srg.jar%23466!/:?]
        at net.minecraft.nbt.CompoundTag$1.m_7300_(CompoundTag.java:45) ~[server-1.20.1-20230612.114412-srg.jar%23466!/:?]
        at net.minecraft.nbt.CompoundTag$1.m_7300_(CompoundTag.java:32) ~[server-1.20.1-20230612.114412-srg.jar%23466!/:?]
        at net.minecraft.nbt.ListTag$1.m_7300_(ListTag.java:43) ~[server-1.20.1-20230612.114412-srg.jar%23466!/:?]
        at net.minecraft.nbt.ListTag$1.m_7300_(ListTag.java:26) ~[server-1.20.1-20230612.114412-srg.jar%23466!/:?]
        at net.minecraft.nbt.CompoundTag.m_128413_(CompoundTag.java:473) ~[server-1.20.1-20230612.114412-srg.jar%23466!/:?]
        at net.minecraft.nbt.CompoundTag$1.m_7300_(CompoundTag.java:45) ~[server-1.20.1-20230612.114412-srg.jar%23466!/:?]
        at net.minecraft.nbt.CompoundTag$1.m_7300_(CompoundTag.java:32) ~[server-1.20.1-20230612.114412-srg.jar%23466!/:?]
        at net.minecraft.nbt.NbtIo.m_128930_(NbtIo.java:153) ~[server-1.20.1-20230612.114412-srg.jar%23466!/:?]
        at net.minecraft.nbt.NbtIo.m_128934_(NbtIo.java:99) ~[server-1.20.1-20230612.114412-srg.jar%23466!/:?]
        at net.minecraft.nbt.NbtIo.m_128928_(NbtIo.java:95) ~[server-1.20.1-20230612.114412-srg.jar%23466!/:?]
        at net.minecraft.world.level.chunk.storage.RegionFileStorage.m_63706_(RegionFileStorage.java:65) ~[server-1.20.1-20230612.114412-srg.jar%23466!/:?]
        at net.minecraft.world.level.chunk.storage.IOWorker.m_223494_(IOWorker.java:186) ~[server-1.20.1-20230612.114412-srg.jar%23466!/:?]
        ... 8 more`
