### ISSUE TITLE
[1.20.1] Curtain Mod cannot run correctly

### ISSUE THREAD

**Issue by 0And1Story** [Teneted/Tenet#3280]
**Minecraft Version :** Minecraft 1.20.1

**Mohist Version :** Mohist-1.20.1-814

**Operating System :** Windows 11 23H2

**Concerned mod / plugin** : [Curtain Mod](https://www.curseforge.com/minecraft/mc-mods/curtain) (the forge version of the fabric mod "carpet")

**Logs :** Showed as below or [Pastebin](https://pastebin.com/uYivTkJA)

**Steps to Reproduce :**
 1. Issue the command `/player hsds spawn`, and the fake player joined the game.
 2. Issue other commands such as `/player hsds attack`, `/player hsds use` and so on, it runs successfully. (Sometimes the fake player is invisible and the operations are invalid.)
 3. Issue the command `/player hsds kill`, it shows `hsds lost connection: Killed` but not `hsds left the game`, and the fake player is still listed on the playerlist.
 4. Issue the command `/player hsds spawn` again, it failed and showed `Player hsds is already logged on`.

**Description of issue :** In short, the fake player spawned by Curtain Mod cannot left the game corretly using the command `/player kill`. This had happened on CatServer, and the bug has the same behavior. [[1.16.5] Forge-Carpet模组无法正常生成假人](https://github.com/Luohuayu/CatServer/issues/420) I don't know if it has some connections with the plugins EssentialX and AuthMe.

Server log:
```
[19:22:44] [Server thread/INFO] [net.minecraft.server.network.ServerGamePacketListenerImpl]: WitherMan233 issued server command: /minecraft:player hsds spawn
[19:22:44] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: hsds加入了游戏
[19:22:44] [Server thread/INFO] [net.minecraft.server.players.PlayerList]: hsds[local] logged in with entity id 489 at ([world]730.1039710897686, 204.5, 1311.1064914593712)
[19:22:44] [Craft Scheduler Thread - 4/WARN] [fr.xephi.authme.AuthMe]: [AuthMe] Plugin AuthMe v5.6.0-SNAPSHOT-b2614 generated an exception while executing task 34
java.lang.NullPointerException: Cannot invoke "java.net.InetSocketAddress.getAddress()" because the return value of "org.bukkit.entity.Player.getAddress()" is null
	at fr.xephi.authme.util.PlayerUtils.getPlayerIp(PlayerUtils.java:21) ~[?:?]
	at fr.xephi.authme.process.join.AsynchronousJoin.processJoin(AsynchronousJoin.java:96) ~[?:?]
	at fr.xephi.authme.process.Management.lambda$performJoin$7(Management.java:81) ~[?:?]
	at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:78) ~[forge-1.20.1-47.3.5-universal.jar%23229!/:?]
	at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:55) ~[forge-1.20.1-47.3.5-universal.jar%23229!/:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1583) [?:?]
[19:22:53] [Server thread/INFO] [net.minecraft.server.network.ServerGamePacketListenerImpl]: WitherMan233 issued server command: /minecraft:player hsds attack
[19:23:11] [Server thread/INFO] [net.minecraft.server.network.ServerGamePacketListenerImpl]: WitherMan233 issued server command: /minecraft:player hsds kill
[19:23:11] [Server thread/INFO] [net.minecraft.server.network.ServerGamePacketListenerImpl]: hsds lost connection: Killed
[19:23:11] [Server thread/ERROR] [net.minecraftforge.eventbus.EventBus]: Exception caught during firing event: Cannot invoke "dev.dubhe.curtain.features.player.menu.FakePlayerInventoryMenu.tick()" because the return value of "java.util.HashMap.get(Object)" is null
	Index: 3
	Listeners:
		0: HIGH
		1: ASM: class dev.architectury.event.forge.EventHandlerImplCommon event(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
		2: NORMAL
		3: ASM: dev.dubhe.curtain.events.rules.PlayerEventHandler@29a47259 onTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
		4: ASM: xaero.map.events.FMLCommonEvents@d56b204 handlePlayerTickStart(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
		5: ASM: xaero.common.events.FMLCommonEventHandler@158d2cf3 handlePlayerTickStart(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
		6: ASM: com.sk89q.worldedit.forge.ThreadSafeCache@401479e4 tickStart(Lnet/minecraftforge/event/TickEvent;)V
java.lang.NullPointerException: Cannot invoke "dev.dubhe.curtain.features.player.menu.FakePlayerInventoryMenu.tick()" because the return value of "java.util.HashMap.get(Object)" is null
	at TRANSFORMER/curtain@1.3.2/dev.dubhe.curtain.events.rules.PlayerEventHandler.onTick(PlayerEventHandler.java:27)
	at TRANSFORMER/curtain@1.3.2/dev.dubhe.curtain.events.rules.__PlayerEventHandler_onTick_PlayerTickEvent.invoke(.dynamic)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:319)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:299)
	at TRANSFORMER/forge@47.3.5/net.minecraftforge.event.ForgeEventFactory.onPlayerPreTick(ForgeEventFactory.java:944)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.entity.player.Player.m_8119_(Player.java:234)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.level.ServerPlayer.m_9240_(ServerPlayer.java:576)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.players.PlayerList.m_11286_(PlayerList.java:463)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.network.ServerGamePacketListenerImpl.m_7026_(ServerGamePacketListenerImpl.java:1706)
	at TRANSFORMER/curtain@1.3.2/dev.dubhe.curtain.features.player.patches.EntityPlayerMPFake.lambda$kill$2(EntityPlayerMPFake.java:128)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.TickTask.run(TickTask.java:18)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:151)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:1028)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:175)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:124)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:1011)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:1005)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.util.thread.BlockableEventLoop.m_18699_(BlockableEventLoop.java:112)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:990)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:913)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:285)
	at java.base/java.lang.Thread.run(Thread.java:1583)

[19:23:11] [Server thread/ERROR] [net.minecraft.util.thread.BlockableEventLoop]: Error executing task on Server
net.minecraft.ReportedException: Ticking player
	at net.minecraft.server.level.ServerPlayer.m_9240_(ServerPlayer.java:660) ~[server-1.20.1-20230612.114412-srg.jar%23224!/:?]
	at net.minecraft.server.players.PlayerList.m_11286_(PlayerList.java:463) ~[server-1.20.1-20230612.114412-srg.jar%23224!/:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.m_7026_(ServerGamePacketListenerImpl.java:1706) ~[server-1.20.1-20230612.114412-srg.jar%23224!/:?]
	at dev.dubhe.curtain.features.player.patches.EntityPlayerMPFake.lambda$kill$2(EntityPlayerMPFake.java:128) ~[curtain-mc1.20.1-1.3.2.jar%23214!/:1.3.2]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[server-1.20.1-20230612.114412-srg.jar%23224!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:151) ~[server-1.20.1-20230612.114412-srg.jar%23224!/:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[server-1.20.1-20230612.114412-srg.jar%23224!/:?]
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:1028) ~[server-1.20.1-20230612.114412-srg.jar%23224!/:?]
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:175) ~[server-1.20.1-20230612.114412-srg.jar%23224!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:124) ~[server-1.20.1-20230612.114412-srg.jar%23224!/:?]
	at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:1011) ~[server-1.20.1-20230612.114412-srg.jar%23224!/:?]
	at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:1005) ~[server-1.20.1-20230612.114412-srg.jar%23224!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_18699_(BlockableEventLoop.java:112) ~[server-1.20.1-20230612.114412-srg.jar%23224!/:?]
	at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:990) ~[server-1.20.1-20230612.114412-srg.jar%23224!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:913) ~[server-1.20.1-20230612.114412-srg.jar%23224!/:?]
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:285) ~[server-1.20.1-20230612.114412-srg.jar%23224!/:?]
	at java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "dev.dubhe.curtain.features.player.menu.FakePlayerInventoryMenu.tick()" because the return value of "java.util.HashMap.get(Object)" is null
	at dev.dubhe.curtain.events.rules.PlayerEventHandler.onTick(PlayerEventHandler.java:27) ~[curtain-mc1.20.1-1.3.2.jar%23214!/:1.3.2]
	at dev.dubhe.curtain.events.rules.__PlayerEventHandler_onTick_PlayerTickEvent.invoke(.dynamic) ~[curtain-mc1.20.1-1.3.2.jar%23214!/:1.3.2]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.5.jar%23150!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:319) ~[eventbus-6.0.5.jar%23150!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:299) ~[eventbus-6.0.5.jar%23150!/:?]
	at net.minecraftforge.event.ForgeEventFactory.onPlayerPreTick(ForgeEventFactory.java:944) ~[forge-1.20.1-47.3.5-universal.jar%23229!/:?]
	at net.minecraft.world.entity.player.Player.m_8119_(Player.java:234) ~[server-1.20.1-20230612.114412-srg.jar%23224!/:?]
	at net.minecraft.server.level.ServerPlayer.m_9240_(ServerPlayer.java:576) ~[server-1.20.1-20230612.114412-srg.jar%23224!/:?]
	... 16 more
[19:23:11] [Server thread/ERROR] [net.minecraftforge.eventbus.EventBus]: Exception caught during firing event: Cannot invoke "dev.dubhe.curtain.features.player.menu.FakePlayerInventoryMenu.tick()" because the return value of "java.util.HashMap.get(Object)" is null
	Index: 3
	Listeners:
		0: HIGH
		1: ASM: class dev.architectury.event.forge.EventHandlerImplCommon event(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
		2: NORMAL
		3: ASM: dev.dubhe.curtain.events.rules.PlayerEventHandler@29a47259 onTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
		4: ASM: xaero.map.events.FMLCommonEvents@d56b204 handlePlayerTickStart(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
		5: ASM: xaero.common.events.FMLCommonEventHandler@158d2cf3 handlePlayerTickStart(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
		6: ASM: com.sk89q.worldedit.forge.ThreadSafeCache@401479e4 tickStart(Lnet/minecraftforge/event/TickEvent;)V
java.lang.NullPointerException: Cannot invoke "dev.dubhe.curtain.features.player.menu.FakePlayerInventoryMenu.tick()" because the return value of "java.util.HashMap.get(Object)" is null
	at TRANSFORMER/curtain@1.3.2/dev.dubhe.curtain.events.rules.PlayerEventHandler.onTick(PlayerEventHandler.java:27)
	at TRANSFORMER/curtain@1.3.2/dev.dubhe.curtain.events.rules.__PlayerEventHandler_onTick_PlayerTickEvent.invoke(.dynamic)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:319)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:299)
	at TRANSFORMER/forge@47.3.5/net.minecraftforge.event.ForgeEventFactory.onPlayerPreTick(ForgeEventFactory.java:944)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.entity.player.Player.m_8119_(Player.java:234)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.level.ServerPlayer.m_9240_(ServerPlayer.java:576)
	at TRANSFORMER/curtain@1.3.2/dev.dubhe.curtain.features.player.patches.EntityPlayerMPFake.m_8119_(EntityPlayerMPFake.java:140)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.level.ServerLevel.m_8647_(ServerLevel.java:854)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.Level.m_46653_(Level.java:626)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.level.ServerLevel.m_184063_(ServerLevel.java:479)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.entity.EntityTickList.m_156910_(EntityTickList.java:54)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:459)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:1158)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:360)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:1073)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:909)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:285)
	at java.base/java.lang.Thread.run(Thread.java:1583)

[19:23:17] [Server thread/INFO] [net.minecraft.server.network.ServerGamePacketListenerImpl]: WitherMan233 issued server command: /minecraft:player hsds spawn
[19:23:17] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: [WitherMan233: Player hsds is already logged on]
```

**Comment by xmbhjQAQ** [comment]
Same problem

**Comment by JUSTPL4Y-AK** [comment]
same problem.I searched whole Internet and can't find out how to solve it.Has author solved this problem？
