### ISSUE TITLE
[1.18.2] 在验证安装出现了一个报错

### ISSUE THREAD

**Issue by 8MiYile** [Teneted/Tenet#3291]
这一份日志很奇怪 直接挂在服务端的初始化,这个是要删除什么文件吗
<details>
<summary>服务端运行日志</summary>

```
感谢使用Mohist - 1.18.2-187, Java(17.0.10) 61.0

官方交流QQ群: 158638
检查更新中...
如果不想启用更新检查，在mohist-config/mohist.yml中设置“check_update”为“false”
未发现更新。最新版本：(187)，当前版本：(187)
检查库文件中，请稍等...
库文件检查完成，未发现问题 :)
验证安装中，请稍等...
java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at com.mohistmc.action.Action.run(Action.java:103)
        at com.mohistmc.action.v_1_18_2$Install_1_18_2.install(v_1_18_2.java:195)
        at com.mohistmc.action.v_1_18_2$Install_1_18_2.<init>(v_1_18_2.java:80)
        at com.mohistmc.action.v_1_18_2.run(v_1_18_2.java:52)
        at com.mohistmc.MohistMCStart.main(MohistMCStart.java:85)
Caused by: java.io.IOException: Patch expected com/mojang/math/Matrix3f to have the checksum d5414b25 but it was 24c8162f
        at net.minecraftforge.binarypatcher.Patcher.patch(Patcher.java:197)
        at net.minecraftforge.binarypatcher.Patcher.process(Patcher.java:149)
        at net.minecraftforge.binarypatcher.ConsoleTool.main(ConsoleTool.java:161)
        ... 9 more
Exception in thread "main" java.lang.ExceptionInInitializerError
        at cpw.mods.niofs.union.UnionFileSystemProvider.newFileSystemInternal(UnionFileSystemProvider.java:115)
        at cpw.mods.niofs.union.UnionFileSystemProvider.newFileSystem(UnionFileSystemProvider.java:105)
        at cpw.mods.jarhandling.impl.Jar.<init>(Jar.java:75)
        at cpw.mods.jarhandling.SecureJar.from(SecureJar.java:58)
        at cpw.mods.jarhandling.SecureJar.from(SecureJar.java:50)
        at cpw.mods.jarhandling.SecureJar.from(SecureJar.java:42)
        at com.mohistmc.util.BootstrapLauncher.startServer(BootstrapLauncher.java:73)
        at com.mohistmc.MohistMCStart.main(MohistMCStart.java:104)
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make field static final java.lang.invoke.MethodHandles$Lookup java.lang.invoke.MethodHandles$Lookup.IMPL_LOOKUP accessible: module java.base does not "opens java.lang.invoke" to unnamed module @2fd3b621
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
        at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:178)
        at java.base/java.lang.reflect.Field.setAccessible(Field.java:172)
        at cpw.mods.niofs.union.UnionFileSystem.<clinit>(UnionFileSystem.java:45)
        ... 8 more
```
<details>

**Comment by Unitei-Dev** [comment]
As far as I remember 1.18.x - 1.19.x there is almost no support at all, and even if you run 10 percent of all resources on the market will run on this core
