### ISSUE TITLE
[1.20.1][Mohist-787]Cannot load any bukkit plugin from plugins folder(不能加载任何bukkit 的插件，包括mohistplugin.jar )

### ISSUE THREAD

**Issue by TheFairyTale** [Teneted/Tenet#3295]
Java: 17.0.12

**Minecraft Version :** 1.20.1

**Mohist Version :** Mohist build 787 (Mohist version 1.20.1-822 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT, Forge version 47.3.5, NeoForge version 47.1.105))

**Operating System :** Windows Server 2016 DataCenter Evaluation

**Logs :** 
```
[17:45:36 ERROR]: 在加載 'plugins\[权限组配置与管理]PermissionsEx.jar' 插件(目录 plugins)出错: org.bukkit.plugin.InvalidPluginException: java.lang.ExceptionInInitializerError
[17:45:36 ERROR]: 在加載 'plugins\[玩家行为记录与查询]CoreProtect-22.4.jar' 插件(目录 plugins)出错: org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: Could not initialize class com.mohistmc.bukkit.remapping.Remapper
[17:45:36 ERROR]: 在加載 'plugins\[可选前置]item-nbt-api-plugin.jar' 插件(目录 plugins)出错: org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: Could not initialize class com.mohistmc.bukkit.remapping.Remapper
[17:45:36 ERROR]: 在加載 'plugins\[可选前置]Vault.jar' 插件(目录 plugins)出错: org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: Could not initialize class com.mohistmc.bukkit.remapping.Remapper
[17:45:36 ERROR]: 在加載 'plugins\[可选前置]ProtocolLib.jar' 插件(目录 plugins)出错: org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: Could not initialize class com.mohistmc.bukkit.remapping.Remapper
[17:45:36 ERROR]: 在加載 'plugins\[MineBBS]-YukiNoaAPI.jar' 插件(目录 plugins)出错: org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: Could not initialize class com.mohistmc.bukkit.remapping.Remapper
[17:45:36 ERROR]: Could not load 'plugins\[MineBBS]-BanIt-1.1.5.jar' in folder 'plugins'
org.bukkit.plugin.UnknownDependencyException: Unknown dependency YukiNoaAPI. Please download and install YukiNoaAPI to run this plugin.
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:272) ~[forge-1.20.1-47.3.5-universal.jar%23505!/:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.loadPlugins(CraftServer.java:435) ~[forge-1.20.1-47.3.5-universal.jar%23505!/:997de31d-ddc9a2dad-d2eba2c8-47.1.105]
        at net.minecraft.server.dedicated.DedicatedServer.m_7038_(DedicatedServer.java:225) ~[server-1.20.1-20230612.114412-srg.jar%23500!/:?]
        at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:855) ~[server-1.20.1-20230612.114412-srg.jar%23500!/:?]
        at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:285) ~[server-1.20.1-20230612.114412-srg.jar%23500!/:?]
        at java.lang.Thread.run(Thread.java:842) [?:?]

[17:45:54 ERROR]: org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: Could not initialize class com.mohistmc.bukkit.remapping.Remapper
[17:45:54 ERROR]: Failed to load mohistplugins.jar
```

**Mod list :** [155 forge mods](https://pastebin.com/U2tGDbvS)

**Plugin list :** 
```
ls *.jar

Mode                LastWriteTime         Length Name                                                                  
----                -------------         ------ ----                                                                  
-a----        2024/8/10     17:28          66263 [MineBBS]-BanIt-1.1.5.jar                                             
-a----        2024/8/10     17:30         121693 [MineBBS]-YukiNoaAPI.jar                                              
-a----        2024/8/10     17:31        1069781 [可选前置]item-nbt-api-plugin.jar                                         
-a----        2024/8/10     17:31        1483042 [可选前置]ProtocolLib.jar                                                 
-a----        2024/8/10     17:30         272259 [可选前置]Vault.jar                                                       
-a----         2024/7/6     17:03         516632 [权限组配置与管理]PermissionsEx.jar                                           
-a----        2024/7/28     15:26         832017 [玩家行为记录与查询]CoreProtect-22.4.jar                                       
```

**Description of issue :** Cannot load any bukkit plugin from plugins folder while server starting. include mohistplugin.jar. no crash happen, just dont load any plugins.
不能加载任何bukkit 的插件，包括mohistplugin.jar 这个（好像是mohist自带的？）并不会崩服但是 ` /plugins ` 显示没加载任何插件。mohist核心是从官网上下载的

**Comment by TheFairyTale** [comment]
实际这个问题好像从当初用的77x、780开始就一直加载不了了

**Comment by Mgazul** [comment]
无法复现

**Comment by Mgazul** [comment]
你需要提供完整的日志
