### ISSUE TITLE
[1.20.1] 植物魔法海洋法杖无法正常使用

### ISSUE THREAD

**Issue by le592149692** [Teneted/Tenet#3321]
**Minecraft Version :** 1.20.1

**Mohist Version :** 1.20.1.839

**Operating System :** win11

**Concerned mod / plugin** : 植物魔法 版本1.20.1.446-forge

**Logs :** Link(s) of logs and crash reports if you have

**Steps to Reproduce :**
 1. 正常使用海洋法杖
 2. 在单人模式及某A核心试过均无以下问题

**Description of issue :** 服务器只装了植物魔法及其前置，海洋法杖无法正常放置水方块，具体表现为右键使用后水方块后间消失，然后服务器后台会刷出以下信息

[01:47:06 ERROR]: Failed to handle packet net.minecraft.network.protocol.game.ServerboundUseItemPacket@63f62fc8, suppressing error
java.lang.NullPointerException: Cannot invoke "net.minecraft.world.item.ItemStack.m_41720_()" because "itemstack" is null
        at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.getPlayerBucketEvent(CraftEventFactory.java:483) ~[forge-1.20.1-47.3.7-universal.jar%23345!/:?]
        at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.callPlayerBucketEmptyEvent(CraftEventFactory.java:473) ~[forge-1.20.1-47.3.7-universal.jar%23345!/:?]
        at net.minecraft.world.item.BucketItem.emptyContents(BucketItem.java:170) ~[server-1.20.1-20230612.114412-srg.jar%23340!/:?]
        at net.minecraft.world.item.BucketItem.emptyContents(BucketItem.java:151) ~[server-1.20.1-20230612.114412-srg.jar%23340!/:?]
        at net.minecraft.world.item.BucketItem.m_142073_(BucketItem.java:140) ~[server-1.20.1-20230612.114412-srg.jar%23340!/:?]
        at vazkii.botania.common.item.rod.SeasRodItem.m_7203_(SeasRodItem.java:64) ~[%5B植物魔法%5D%20Botania-1.20.1-446-FORGE.jar%23302!/:1.20.1-446-FORGE]
        at net.minecraft.world.item.ItemStack.m_41682_(ItemStack.java:328) ~[server-1.20.1-20230612.114412-srg.jar%23340!/:?]
        at net.minecraft.server.level.ServerPlayerGameMode.m_6261_(ServerPlayerGameMode.java:379) ~[server-1.20.1-20230612.114412-srg.jar%23340!/:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.m_5760_(ServerGamePacketListenerImpl.java:1652) ~[server-1.20.1-20230612.114412-srg.jar%23340!/:?]
        at net.minecraft.network.protocol.game.ServerboundUseItemPacket.m_5797_(ServerboundUseItemPacket.java:29) ~[server-1.20.1-20230612.114412-srg.jar%23340!/:?]
        at net.minecraft.network.protocol.game.ServerboundUseItemPacket.m_5797_(ServerboundUseItemPacket.java:7) ~[server-1.20.1-20230612.114412-srg.jar%23340!/:?]
        at net.minecraft.network.protocol.PacketUtils.m_263899_(PacketUtils.java:25) ~[server-1.20.1-20230612.114412-srg.jar%23340!/:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[server-1.20.1-20230612.114412-srg.jar%23340!/:?]
        at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:151) ~[server-1.20.1-20230612.114412-srg.jar%23340!/:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[server-1.20.1-20230612.114412-srg.jar%23340!/:?]
        at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:1025) ~[server-1.20.1-20230612.114412-srg.jar%23340!/:?]
        at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:175) ~[server-1.20.1-20230612.114412-srg.jar%23340!/:?]
        at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:124) ~[server-1.20.1-20230612.114412-srg.jar%23340!/:?]
        at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:1008) ~[server-1.20.1-20230612.114412-srg.jar%23340!/:?]
        at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:1002) ~[server-1.20.1-20230612.114412-srg.jar%23340!/:?]
        at net.minecraft.util.thread.BlockableEventLoop.m_18701_(BlockableEventLoop.java:134) ~[server-1.20.1-20230612.114412-srg.jar%23340!/:?]
        at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:988) ~[server-1.20.1-20230612.114412-srg.jar%23340!/:?]
        at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:913) ~[server-1.20.1-20230612.114412-srg.jar%23340!/:?]
        at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:285) ~[server-1.20.1-20230612.114412-srg.jar%23340!/:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]

**Comment by le592149692** [comment]
今天又发现同一模组的旅居者腰带的自动上一格高方块的功能会失效，单人模式测试了一下这个功能是正常的
