### ISSUE TITLE
[1.20.1] Loot table for Apothetic Additions

### ISSUE THREAD

**Issue by AlwaysReadyWBY** [Teneted/Tenet#3336]
**Minecraft Version :** 1.20.1

**Mohist Version :** 855

**Operating System :** Windows Server 2016 Datacenter

**Concerned mod / plugin** : 
Apothetic Additions([](https://www.curseforge.com/minecraft/mc-mods/apotheotic-additions))
Lootr([](https://modrinth.com/mod/lootr))

**Logs :** [Link(s) of logs and crash reports if you have](https://mclo.gs/MgfJA1A)

**Steps to Reproduce :**
 1. Find a loot chest with the loot table of "apotheotic_additions:chests/aa_spawner"
 2. Open the chest
 3. Unable to open the chest and error log appears:
 [15:29:19] [Server thread/ERROR] [noobanidus.mods.lootr.api.LootrAPI]: Unable to fill loot chest in minecraft:overworld at BlockPos{x=-578, y=-15, z=-1204} as the loot table 'apotheotic_additions:chests/aa_spawner' couldn't be resolved! Please search the loot table in `latest.log` to see if there are errors in loading.
[15:29:19] [Server thread/ERROR] [net.minecraft.network.protocol.PacketUtils]: Failed to handle packet net.minecraft.network.protocol.game.ServerboundUseItemOnPacket@6fe82a17, suppressing error
java.lang.NullPointerException: Cannot invoke "net.minecraft.resources.ResourceLocation.m_135827_()" because "minecraft" is null
	at org.bukkit.craftbukkit.v1_20_R1.util.CraftNamespacedKey.fromMinecraft(CraftNamespacedKey.java:24) ~[forge-1.20.1-47.3.7-universal.jar%23605!/:?]
	at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.callLootGenerateEvent(CraftEventFactory.java:1743) ~[forge-1.20.1-47.3.7-universal.jar%23605!/:?]
	at net.minecraft.world.level.storage.loot.LootTable.m_287188_(LootTable.java:155) ~[server-1.20.1-20230612.114412-srg.jar%23600!/:?]
	at noobanidus.mods.lootr.block.entities.LootrChestBlockEntity.unpackLootTable(LootrChestBlockEntity.java:279) ~[lootr-forge-1.20-0.7.34.86.jar%23513!/:0.7.34.86]
	at noobanidus.mods.lootr.data.ChestData.createInventory(ChestData.java:358) ~[lootr-forge-1.20-0.7.34.86.jar%23513!/:0.7.34.86]
	at noobanidus.mods.lootr.data.DataStorage.getInventory(DataStorage.java:338) ~[lootr-forge-1.20-0.7.34.86.jar%23513!/:0.7.34.86]
	at noobanidus.mods.lootr.util.ChestUtil.handleLootChest(ChestUtil.java:142) ~[lootr-forge-1.20-0.7.34.86.jar%23513!/:0.7.34.86]
	at noobanidus.mods.lootr.block.LootrChestBlock.m_6227_(LootrChestBlock.java:50) ~[lootr-forge-1.20-0.7.34.86.jar%23513!/:0.7.34.86]
	at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.m_60664_(BlockBehaviour.java:779) ~[server-1.20.1-20230612.114412-srg.jar%23600!/:?]
	at net.minecraft.server.level.ServerPlayerGameMode.m_7179_(ServerPlayerGameMode.java:483) ~[server-1.20.1-20230612.114412-srg.jar%23600!/:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.m_6371_(ServerGamePacketListenerImpl.java:1576) ~[server-1.20.1-20230612.114412-srg.jar%23600!/:?]
	at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.m_5797_(ServerboundUseItemOnPacket.java:34) ~[server-1.20.1-20230612.114412-srg.jar%23600!/:?]
	at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.m_5797_(ServerboundUseItemOnPacket.java:8) ~[server-1.20.1-20230612.114412-srg.jar%23600!/:?]
	at net.minecraft.network.protocol.PacketUtils.m_263899_(PacketUtils.java:25) ~[server-1.20.1-20230612.114412-srg.jar%23600!/:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[server-1.20.1-20230612.114412-srg.jar%23600!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:151) ~[server-1.20.1-20230612.114412-srg.jar%23600!/:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[server-1.20.1-20230612.114412-srg.jar%23600!/:?]
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:1025) ~[server-1.20.1-20230612.114412-srg.jar%23600!/:?]
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:175) ~[server-1.20.1-20230612.114412-srg.jar%23600!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:124) ~[server-1.20.1-20230612.114412-srg.jar%23600!/:?]
	at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:1008) ~[server-1.20.1-20230612.114412-srg.jar%23600!/:?]
	at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:1002) ~[server-1.20.1-20230612.114412-srg.jar%23600!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_18699_(BlockableEventLoop.java:112) ~[server-1.20.1-20230612.114412-srg.jar%23600!/:?]
	at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:987) ~[server-1.20.1-20230612.114412-srg.jar%23600!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:913) ~[server-1.20.1-20230612.114412-srg.jar%23600!/:?]
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:285) ~[server-1.20.1-20230612.114412-srg.jar%23600!/:?]
	at java.lang.Thread.run(Thread.java:1583) [?:?]

**Description of issue :** Look as if there are some bugs with loot table related to resource locations (or maybe namespacedkey?)

**Comment by AlwaysReadyWBY** [comment]
Probably related to some other mods though, or maybe the dependencies of this mod, I'm not sure.

**Comment by AlwaysReadyWBY** [comment]
It seems that this problem is on the mod side
