### ISSUE TITLE
Problem with net/minecraft/world/item/crafting/RecipeManager

### ISSUE THREAD

**Issue by ApostolDm** [Teneted/Tenet#3352]
**Minecraft Version :**  Mohist - 1.20.1

**Mohist Version :** 864 and 865

**Operating System :** 

```
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.4 LTS
Release:        22.04
Codename:       jammy
```

Core: 

```
5.15.0-122-generic
```

**Logs :** 

```
[17:52:36 ERROR]: Failed to create mod instance. ModID: blueprint, class com.teamabnormals.blueprint.core.Blueprint
java.lang.NoClassDefFoundError: net/minecraft/world/item/crafting/RecipeManager
        at java.lang.Class.getDeclaredFields0(Native Method) ~[?:?]
        at java.lang.Class.privateGetDeclaredFields(Class.java:3473) ~[?:?]
        at java.lang.Class.getDeclaredField(Class.java:2780) ~[?:?]
        at net.minecraftforge.fml.util.ObfuscationReflectionHelper.findField(ObfuscationReflectionHelper.java:221) ~[fmlcore-1.20.1-47.3.10.jar%23571!/:?]
        at com.teamabnormals.blueprint.core.util.DataUtil.<clinit>(DataUtil.java:73) ~[blueprint-1.20.1-7.1.0.jar%23431!/:7.1.0]
        at com.teamabnormals.blueprint.core.Blueprint.<init>(Blueprint.java:125) ~[blueprint-1.20.1-7.1.0.jar%23431!/:7.1.0]
        at jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62) ~[?:?]
        at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502) ~[?:?]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:486) ~[?:?]
        at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:83) ~[javafmllanguage-1.20.1-47.3.10.jar%23572!/:?]
        at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:123) ~[fmlcore-1.20.1-47.3.10.jar%23571!/:?]
        at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) [?:?]
        at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) [?:?]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387) [?:?]
        at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312) [?:?]
        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843) [?:?]
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808) [?:?]
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188) [?:?]
Caused by: java.lang.ClassNotFoundException: net.minecraft.world.item.crafting.RecipeManager
        at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:157) ~[securejarhandler-mohist-2.1.11.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
        ... 18 more
```

**Mod list :** 

```
     - abnormals_delight 5.0.0
        - advancementframes 1.20-2.2.7
        - advancementplaques 1.5.1
        - alexsdelight 1.5
        - alexsmobs 1.22.8
        - amendments 1.20-1.2.8
        - amplified_nether 1.2.5
        - another_furniture 1.20.1-3.0.1
        - antiqueatlas 9.2.1+item-forge-1.20.1
        - architectury 9.2.14
        - backpacked 3.0.0-beta.4
        - balm 7.3.6
                \-- kuma_api 20.1.8
        - bcc 4.0.8
        - bclib 3.0.14
        - beachparty 1.1.5
        - betterarcheology 1.1.9-1.20.1
        - bettercombat 1.8.5+1.20.1
        - betterdeserttemples 1.20-Forge-3.0.3
        - betterdungeons 1.20-Forge-4.0.4
        - betterend 4.0.11
        - betterendcities 1.0.0-1.20.1
        - betterendisland 1.20-Forge-2.0.6
        - betterfortresses 1.20-Forge-2.0.6
        - betterjungletemples 1.20-Forge-2.0.5
        - bettermineshafts 1.20-Forge-4.0.4
        - betteroceanmonuments 1.20-Forge-3.0.4
        - betterwitchhuts 1.20-Forge-3.0.3
        - biomesoplenty 18.0.0.598
        - blueprint 7.1.0
        - boss_music_mod 1.0.0
        - brewery 1.1.9
        - buzzier_bees 6.0.0
        - bygonenether 1.3.2
        - call_of_yucutan 1.0.11
        - canary 0.3.3
        - cataclysm 1.99.5
        - chalk 1.6.4
        - chefsdelight 1.0.3-forge-1.20.1
        - chimes 2.0.1
        - chunky 1.3.146
        - citadel 2.5.6
        - clayworks 3.0.1
        - clickadv 1.20.1-3.8
        - cloth_config 11.1.118
        - cold_sweat 2.2.5.1
        - conjurer_illager 1.1.6
        - connectorextras 1.11.2+1.20.1
                |-- amecsapi 1.5.3+mc1.20-pre1
                |-- connectorextras_architectury_bridge 1.11.2+1.20.1
                |-- connectorextras_emi_bridge 1.11.2+1.20.1
                |-- connectorextras_energy_bridge 1.11.2+1.20.1
                |-- connectorextras_geckolib_fabric_compat 1.11.2+1.20.1
                |-- connectorextras_jei_bridge 1.11.2+1.20.1
                |-- connectorextras_kubejs_bridge 1.11.2+1.20.1
                |-- connectorextras_modmenu_bridge 1.11.2+1.20.1
                        \-- modmenu 7.2.2
                |-- connectorextras_pehkui_bridge 1.11.2+1.20.1
                |-- connectorextras_rei_bridge 1.11.2+1.20.1
                |-- connectorextras_terrablender_bridge 1.11.2+1.20.1
                |-- forgeconfigapiport 8.0.0
                \-- reach_entity_attributes 2.4.0
        - connectormod 1.0.0-beta.46+1.20.1
        - copycats 1.20.1-1.3.4
        - coroutil 1.20.1-1.3.7
        - corpse 1.20.1-1.0.12
        - create 0.5.1.f
                \-- flywheel 0.6.10-7
        - creativecore 2.11.33
        - creeperoverhaul 3.0.2
        - cristellib 1.1.5
        - crittersandcompanions 1.20.1-2.1.6
        - cupboard 1.20.1-2.7
        - curios 5.9.1+1.20.1
        - curious_armor_stands 1.20-5.1.0
        - delightful 3.5.5
        - diet 2.1.1+1.20.1
        - dixtas_armory 0.0NONE
        - doapi 1.2.15
                \-- terraform 7.0.1
        - domesticationinnovation 1.7.1
        - dragonfight 1.20.1-4.6
        - dummmmmmy 1.20-1.8.17b
        - dungeons_enhanced 5.2.2
        - dungeons_plus 1.5.0
        - dynview 2.3
        - easymagic 8.0.1
        - elenaidodge2 1.1
                \-- playeranimator 1.0.2-rc1+1.20
        - enchdesc 17.0.16
        - endermanoverhaul 1.0.4
        - endersdelight 1.0.3
        - endrem 5.2.3-R-1.20.1
        - etched 3.0.2
        - everycomp 1.20-2.6.69
        - fabric_api 0.92.2+1.11.8+1.20.1
                |-- fabric_api_base 0.4.31+ef105b4977
                |-- fabric_api_lookup_api_v1 1.6.36+67f9824077
                |-- fabric_biome_api_v1 13.0.13+dc36698e77
                |-- fabric_block_api_v1 1.0.11+0e6cb7f777
                |-- fabric_block_view_api_v2 1.0.1+0767707077
                |-- fabric_blockrenderlayer_v1 1.1.41+1d0da21e77
                |-- fabric_client_tags_api_v1 1.1.2+5d6761b877
                |-- fabric_command_api_v1 1.2.34+f71b366f77
                |-- fabric_command_api_v2 2.2.13+561530ec77
                |-- fabric_content_registries_v0 4.0.11+a670df1e77
                |-- fabric_convention_tags_v1 1.5.5+fa3d1c0177
                |-- fabric_data_attachment_api_v1 1.0.0+30ef839e77
                |-- fabric_data_generation_api_v1 12.3.4+369cb3a477
                |-- fabric_dimensions_v1 2.1.54+8005d10d77
                |-- fabric_entity_events_v1 1.6.0+6274ab9d77
                |-- fabric_events_interaction_v0 0.6.2+0d0bd5a777
                |-- fabric_game_rule_api_v1 1.0.40+683d4da877
                |-- fabric_item_api_v1 2.1.28+4d0bbcfa77
                |-- fabric_item_group_api_v1 4.0.12+c9161c2d77
                |-- fabric_key_binding_api_v1 1.0.37+561530ec77
                |-- fabric_lifecycle_events_v1 2.2.22+afab492177
                |-- fabric_loot_api_v2 1.2.1+eb28f93e77
                |-- fabric_message_api_v1 5.1.9+52cc178c77
                |-- fabric_mining_level_api_v1 2.1.50+561530ec77
                |-- fabric_model_loading_api_v1 1.0.3+6274ab9d77
                |-- fabric_models_v0 0.4.2+7c3892a477
                |-- fabric_networking_api_v1 1.3.11+503a202477
                |-- fabric_object_builder_api_v1 11.1.3+2174fc8477
                |-- fabric_particles_v1 1.1.2+78e1ecb877
                |-- fabric_recipe_api_v1 1.0.21+514a076577
                |-- fabric_registry_sync_v0 2.3.3+1c0ea72177
                |-- fabric_renderer_api_v1 3.2.1+1d29b44577
                |-- fabric_renderer_indigo 1.5.2+b5b2da4177
                |-- fabric_rendering_data_attachment_v1 0.3.37+a6081afc77
                |-- fabric_rendering_fluids_v1 3.0.28+4ac5e37a77
                |-- fabric_rendering_v1 3.0.8+66e9a48f77
                |-- fabric_resource_conditions_api_v1 2.3.8+9ad825cd77
                |-- fabric_resource_loader_v0 0.11.10+bcd08ed377
                |-- fabric_screen_api_v1 2.0.8+45a670a577
                |-- fabric_screen_handler_api_v1 1.3.30+561530ec77
                |-- fabric_sound_api_v1 1.0.13+4f23bd8477
                |-- fabric_transfer_api_v1 3.3.5+631c9cd677
                \-- fabric_transitive_access_wideners_v1 4.3.1+1880499877
        - farmersdelight 1.20.1-1.2.4
        - farsight_view 1.20.1-3.7
        - feathers 1.1
        - ferritecore 6.0.1
        - forge 47.3.10
                \-- mohist 1.20.1
        - formations 1.0.2
        - formationsnether 1.0.5
        - framework 0.7.6
        - fruitsdelight 1.0.10
                \-- l2library 2.4.11
        - galosphere 1.20.1-1.3.2
        - gardens_of_the_dead 4.0.1
        - geckolib 4.4.7
        - geophilic_reforged 1.2.0
        - grapes_armor_logic 1.1
        - grapesbossdifficulty 1.0
        - grapesessential 1.0
        - grapestorcheslogic 1.0
        - harderspawners 46.25.3
        - heartstone 1.20-1.3.0
        - herbalbrews 1.0.8.1
        - iceberg 1.1.21
        - icterine 1.3.0
        - idas 1.10.1+1.20.1
        - immersive_weathering 1.20.1-2.0.2
        - incubation 4.0.2
        - integrated_api 1.5.1+1.20.1-forge
        - integrated_stronghold 1.1.1+1.20.1-forge
        - integrated_villages 1.0.1+1.20.1-forge
        - jei 15.8.2.25
        - kobolds 2.11.3
        - letmedespawn 1.2.1
        - letsdoaddon_compat 1.4.2
        - lionfishapi 1.9
        - lithostitched 1.1.5
        - lootr 0.7.34.85
        - luckys_armory 0.4.0.1
        - mcwpaintings 1.0.5
        - medievalend 1.0.1
        - mes 1.3.1-1.20-forge
        - minecraft 1.20.1
        - miners_delight 1.20.1-1.2.3
        - mns 1.0.1-1.20-forge
        - mobtimizations 1.20.1-1.0.0
        - modernfix 5.19.0+mc1.20.1
        - moonlight 1.20-2.12.9
                \-- mixinextras 0.3.6
        - moremobvariants 1.3.0.1
        - morevillagers 5.0.0
        - moyai 1.20-2.1.4
        - mr_dungeons_andtaverns 3.0.3.f
        - mr_dungeons_andtavernsancientcityoverhaul 1
        - mr_dungeons_andtavernspillageroutpostrework 1.1
        - mynethersdelight 1.20.1-1.7.5
        - naturalist 4.0.3
        - neruina 2.1.1
        - netherite_horse_armor 1.20.1-1.0.4
        - netherportalfix 13.0.1
        - nethers_exoticism 1.2.8
        - noisium 2.0.3+mc1.20-1.20.1
        - nyfsspiders 2.1.1
        - openloader 19.0.4
        - patchouli 1.20.1-84-FORGE
        - personality 4.0.0
        - playerrevive 2.0.25
        - polymorph 0.49.5+1.20.1
                \-- spectrelib 0.13.15+1.20.1
        - portfolio 1.20.1-1.3.5-forge
        - prism 1.0.5
        - puzzleslib 8.1.21
                \-- puzzlesaccessapi 8.0.7
        - quark 4.0-458
        - quarkdelight 1.0.0
        - regions_unexplored 0.5.5
        - resourcefulconfig 2.1.2
        - resourcefullib 2.1.28
        - royalvariations 1.0.0
        - saturn 0.1.3
        - sawmill 1.20-1.4.3
        - seedbags 1.0.1
        - shieldexp 1.1.7a
        - sleep_tight 1.20-1.1.19
        - smartbrainlib 1.14.2
        - smoothboot 0.0.4
        - sn0wfrogs_capybaras 1.1.0-mc1.20.1
        - sootychimneys 1.2.1
        - spark 1.10.53
        - spelunkery 1.20.1-0.3.5
        - structory 1.3.5
        - structure_gel 2.16.2
        - summer_sunset 1.0.0
        - supernatural 2.11.1
        - supplementaries 1.20-2.8.17
                \-- mixinsquared 0.1.1
        - suppsquared 1.20-1.1.14
        - takesapillage 1.0.3
        - terrablender 3.0.1.7
        - travelerstitles 1.20-Forge-4.0.2
        - treechop 0.19.0
        - tropicraft 9.6.3
        - upgrade_aquatic 6.0.0
        - valhelsia_core 1.1.2
        - valhelsia_furniture 1.1.3
        - valhelsia_structures 1.20.1-1.1.2
        - vc_gliders 1.1.5
                \-- palladiumcore 1.20-2.0.0.0
        - villagersellanimals 1.2.1
        - visualworkbench 8.0.0
        - voicechat 1.20.1-2.5.19
        - wardrobe 1.0.3
        - warriorsofpastepoch 1.0.0
        - wunderlib 1.1.5
        - yungsapi 1.20-Forge-4.0.5
        - zeta 1.0-19
        - zetter 0.21.5
```

**Plugin list :** nop

**Description of issue :** 

I saw commit with similar problem. 

```
https://github.com/MohistMC/Mohist/blob/1.20.1/patches/minecraft/net/minecraft/world/item/crafting/RecipeManager.java.patch
```

**Comment by K0rS1z** [comment]
> **Minecraft Version :** Mohist - 1.20.1
> 
> **Mohist Version :** 864 and 865
> 
> **Operating System :**
> 
> ```
> Distributor ID: Ubuntu
> Description:    Ubuntu 22.04.4 LTS
> Release:        22.04
> Codename:       jammy
> ```
> 
> Core:
> 
> ```
> 5.15.0-122-generic
> ```
> 
> **Logs :**
> 
> ```
> [17:52:36 ERROR]: Failed to create mod instance. ModID: blueprint, class com.teamabnormals.blueprint.core.Blueprint
> java.lang.NoClassDefFoundError: net/minecraft/world/item/crafting/RecipeManager
>         at java.lang.Class.getDeclaredFields0(Native Method) ~[?:?]
>         at java.lang.Class.privateGetDeclaredFields(Class.java:3473) ~[?:?]
>         at java.lang.Class.getDeclaredField(Class.java:2780) ~[?:?]
>         at net.minecraftforge.fml.util.ObfuscationReflectionHelper.findField(ObfuscationReflectionHelper.java:221) ~[fmlcore-1.20.1-47.3.10.jar%23571!/:?]
>         at com.teamabnormals.blueprint.core.util.DataUtil.<clinit>(DataUtil.java:73) ~[blueprint-1.20.1-7.1.0.jar%23431!/:7.1.0]
>         at com.teamabnormals.blueprint.core.Blueprint.<init>(Blueprint.java:125) ~[blueprint-1.20.1-7.1.0.jar%23431!/:7.1.0]
>         at jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62) ~[?:?]
>         at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502) ~[?:?]
>         at java.lang.reflect.Constructor.newInstance(Constructor.java:486) ~[?:?]
>         at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:83) ~[javafmllanguage-1.20.1-47.3.10.jar%23572!/:?]
>         at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:123) ~[fmlcore-1.20.1-47.3.10.jar%23571!/:?]
>         at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) [?:?]
>         at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) [?:?]
>         at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387) [?:?]
>         at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312) [?:?]
>         at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843) [?:?]
>         at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808) [?:?]
>         at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188) [?:?]
> Caused by: java.lang.ClassNotFoundException: net.minecraft.world.item.crafting.RecipeManager
>         at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:157) ~[securejarhandler-mohist-2.1.11.jar:?]
>         at java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
>         ... 18 more
> ```
> 
> **Mod list :**
> 
> ```
>      - abnormals_delight 5.0.0
>         - advancementframes 1.20-2.2.7
>         - advancementplaques 1.5.1
>         - alexsdelight 1.5
>         - alexsmobs 1.22.8
>         - amendments 1.20-1.2.8
>         - amplified_nether 1.2.5
>         - another_furniture 1.20.1-3.0.1
>         - antiqueatlas 9.2.1+item-forge-1.20.1
>         - architectury 9.2.14
>         - backpacked 3.0.0-beta.4
>         - balm 7.3.6
>                 \-- kuma_api 20.1.8
>         - bcc 4.0.8
>         - bclib 3.0.14
>         - beachparty 1.1.5
>         - betterarcheology 1.1.9-1.20.1
>         - bettercombat 1.8.5+1.20.1
>         - betterdeserttemples 1.20-Forge-3.0.3
>         - betterdungeons 1.20-Forge-4.0.4
>         - betterend 4.0.11
>         - betterendcities 1.0.0-1.20.1
>         - betterendisland 1.20-Forge-2.0.6
>         - betterfortresses 1.20-Forge-2.0.6
>         - betterjungletemples 1.20-Forge-2.0.5
>         - bettermineshafts 1.20-Forge-4.0.4
>         - betteroceanmonuments 1.20-Forge-3.0.4
>         - betterwitchhuts 1.20-Forge-3.0.3
>         - biomesoplenty 18.0.0.598
>         - blueprint 7.1.0
>         - boss_music_mod 1.0.0
>         - brewery 1.1.9
>         - buzzier_bees 6.0.0
>         - bygonenether 1.3.2
>         - call_of_yucutan 1.0.11
>         - canary 0.3.3
>         - cataclysm 1.99.5
>         - chalk 1.6.4
>         - chefsdelight 1.0.3-forge-1.20.1
>         - chimes 2.0.1
>         - chunky 1.3.146
>         - citadel 2.5.6
>         - clayworks 3.0.1
>         - clickadv 1.20.1-3.8
>         - cloth_config 11.1.118
>         - cold_sweat 2.2.5.1
>         - conjurer_illager 1.1.6
>         - connectorextras 1.11.2+1.20.1
>                 |-- amecsapi 1.5.3+mc1.20-pre1
>                 |-- connectorextras_architectury_bridge 1.11.2+1.20.1
>                 |-- connectorextras_emi_bridge 1.11.2+1.20.1
>                 |-- connectorextras_energy_bridge 1.11.2+1.20.1
>                 |-- connectorextras_geckolib_fabric_compat 1.11.2+1.20.1
>                 |-- connectorextras_jei_bridge 1.11.2+1.20.1
>                 |-- connectorextras_kubejs_bridge 1.11.2+1.20.1
>                 |-- connectorextras_modmenu_bridge 1.11.2+1.20.1
>                         \-- modmenu 7.2.2
>                 |-- connectorextras_pehkui_bridge 1.11.2+1.20.1
>                 |-- connectorextras_rei_bridge 1.11.2+1.20.1
>                 |-- connectorextras_terrablender_bridge 1.11.2+1.20.1
>                 |-- forgeconfigapiport 8.0.0
>                 \-- reach_entity_attributes 2.4.0
>         - connectormod 1.0.0-beta.46+1.20.1
>         - copycats 1.20.1-1.3.4
>         - coroutil 1.20.1-1.3.7
>         - corpse 1.20.1-1.0.12
>         - create 0.5.1.f
>                 \-- flywheel 0.6.10-7
>         - creativecore 2.11.33
>         - creeperoverhaul 3.0.2
>         - cristellib 1.1.5
>         - crittersandcompanions 1.20.1-2.1.6
>         - cupboard 1.20.1-2.7
>         - curios 5.9.1+1.20.1
>         - curious_armor_stands 1.20-5.1.0
>         - delightful 3.5.5
>         - diet 2.1.1+1.20.1
>         - dixtas_armory 0.0NONE
>         - doapi 1.2.15
>                 \-- terraform 7.0.1
>         - domesticationinnovation 1.7.1
>         - dragonfight 1.20.1-4.6
>         - dummmmmmy 1.20-1.8.17b
>         - dungeons_enhanced 5.2.2
>         - dungeons_plus 1.5.0
>         - dynview 2.3
>         - easymagic 8.0.1
>         - elenaidodge2 1.1
>                 \-- playeranimator 1.0.2-rc1+1.20
>         - enchdesc 17.0.16
>         - endermanoverhaul 1.0.4
>         - endersdelight 1.0.3
>         - endrem 5.2.3-R-1.20.1
>         - etched 3.0.2
>         - everycomp 1.20-2.6.69
>         - fabric_api 0.92.2+1.11.8+1.20.1
>                 |-- fabric_api_base 0.4.31+ef105b4977
>                 |-- fabric_api_lookup_api_v1 1.6.36+67f9824077
>                 |-- fabric_biome_api_v1 13.0.13+dc36698e77
>                 |-- fabric_block_api_v1 1.0.11+0e6cb7f777
>                 |-- fabric_block_view_api_v2 1.0.1+0767707077
>                 |-- fabric_blockrenderlayer_v1 1.1.41+1d0da21e77
>                 |-- fabric_client_tags_api_v1 1.1.2+5d6761b877
>                 |-- fabric_command_api_v1 1.2.34+f71b366f77
>                 |-- fabric_command_api_v2 2.2.13+561530ec77
>                 |-- fabric_content_registries_v0 4.0.11+a670df1e77
>                 |-- fabric_convention_tags_v1 1.5.5+fa3d1c0177
>                 |-- fabric_data_attachment_api_v1 1.0.0+30ef839e77
>                 |-- fabric_data_generation_api_v1 12.3.4+369cb3a477
>                 |-- fabric_dimensions_v1 2.1.54+8005d10d77
>                 |-- fabric_entity_events_v1 1.6.0+6274ab9d77
>                 |-- fabric_events_interaction_v0 0.6.2+0d0bd5a777
>                 |-- fabric_game_rule_api_v1 1.0.40+683d4da877
>                 |-- fabric_item_api_v1 2.1.28+4d0bbcfa77
>                 |-- fabric_item_group_api_v1 4.0.12+c9161c2d77
>                 |-- fabric_key_binding_api_v1 1.0.37+561530ec77
>                 |-- fabric_lifecycle_events_v1 2.2.22+afab492177
>                 |-- fabric_loot_api_v2 1.2.1+eb28f93e77
>                 |-- fabric_message_api_v1 5.1.9+52cc178c77
>                 |-- fabric_mining_level_api_v1 2.1.50+561530ec77
>                 |-- fabric_model_loading_api_v1 1.0.3+6274ab9d77
>                 |-- fabric_models_v0 0.4.2+7c3892a477
>                 |-- fabric_networking_api_v1 1.3.11+503a202477
>                 |-- fabric_object_builder_api_v1 11.1.3+2174fc8477
>                 |-- fabric_particles_v1 1.1.2+78e1ecb877
>                 |-- fabric_recipe_api_v1 1.0.21+514a076577
>                 |-- fabric_registry_sync_v0 2.3.3+1c0ea72177
>                 |-- fabric_renderer_api_v1 3.2.1+1d29b44577
>                 |-- fabric_renderer_indigo 1.5.2+b5b2da4177
>                 |-- fabric_rendering_data_attachment_v1 0.3.37+a6081afc77
>                 |-- fabric_rendering_fluids_v1 3.0.28+4ac5e37a77
>                 |-- fabric_rendering_v1 3.0.8+66e9a48f77
>                 |-- fabric_resource_conditions_api_v1 2.3.8+9ad825cd77
>                 |-- fabric_resource_loader_v0 0.11.10+bcd08ed377
>                 |-- fabric_screen_api_v1 2.0.8+45a670a577
>                 |-- fabric_screen_handler_api_v1 1.3.30+561530ec77
>                 |-- fabric_sound_api_v1 1.0.13+4f23bd8477
>                 |-- fabric_transfer_api_v1 3.3.5+631c9cd677
>                 \-- fabric_transitive_access_wideners_v1 4.3.1+1880499877
>         - farmersdelight 1.20.1-1.2.4
>         - farsight_view 1.20.1-3.7
>         - feathers 1.1
>         - ferritecore 6.0.1
>         - forge 47.3.10
>                 \-- mohist 1.20.1
>         - formations 1.0.2
>         - formationsnether 1.0.5
>         - framework 0.7.6
>         - fruitsdelight 1.0.10
>                 \-- l2library 2.4.11
>         - galosphere 1.20.1-1.3.2
>         - gardens_of_the_dead 4.0.1
>         - geckolib 4.4.7
>         - geophilic_reforged 1.2.0
>         - grapes_armor_logic 1.1
>         - grapesbossdifficulty 1.0
>         - grapesessential 1.0
>         - grapestorcheslogic 1.0
>         - harderspawners 46.25.3
>         - heartstone 1.20-1.3.0
>         - herbalbrews 1.0.8.1
>         - iceberg 1.1.21
>         - icterine 1.3.0
>         - idas 1.10.1+1.20.1
>         - immersive_weathering 1.20.1-2.0.2
>         - incubation 4.0.2
>         - integrated_api 1.5.1+1.20.1-forge
>         - integrated_stronghold 1.1.1+1.20.1-forge
>         - integrated_villages 1.0.1+1.20.1-forge
>         - jei 15.8.2.25
>         - kobolds 2.11.3
>         - letmedespawn 1.2.1
>         - letsdoaddon_compat 1.4.2
>         - lionfishapi 1.9
>         - lithostitched 1.1.5
>         - lootr 0.7.34.85
>         - luckys_armory 0.4.0.1
>         - mcwpaintings 1.0.5
>         - medievalend 1.0.1
>         - mes 1.3.1-1.20-forge
>         - minecraft 1.20.1
>         - miners_delight 1.20.1-1.2.3
>         - mns 1.0.1-1.20-forge
>         - mobtimizations 1.20.1-1.0.0
>         - modernfix 5.19.0+mc1.20.1
>         - moonlight 1.20-2.12.9
>                 \-- mixinextras 0.3.6
>         - moremobvariants 1.3.0.1
>         - morevillagers 5.0.0
>         - moyai 1.20-2.1.4
>         - mr_dungeons_andtaverns 3.0.3.f
>         - mr_dungeons_andtavernsancientcityoverhaul 1
>         - mr_dungeons_andtavernspillageroutpostrework 1.1
>         - mynethersdelight 1.20.1-1.7.5
>         - naturalist 4.0.3
>         - neruina 2.1.1
>         - netherite_horse_armor 1.20.1-1.0.4
>         - netherportalfix 13.0.1
>         - nethers_exoticism 1.2.8
>         - noisium 2.0.3+mc1.20-1.20.1
>         - nyfsspiders 2.1.1
>         - openloader 19.0.4
>         - patchouli 1.20.1-84-FORGE
>         - personality 4.0.0
>         - playerrevive 2.0.25
>         - polymorph 0.49.5+1.20.1
>                 \-- spectrelib 0.13.15+1.20.1
>         - portfolio 1.20.1-1.3.5-forge
>         - prism 1.0.5
>         - puzzleslib 8.1.21
>                 \-- puzzlesaccessapi 8.0.7
>         - quark 4.0-458
>         - quarkdelight 1.0.0
>         - regions_unexplored 0.5.5
>         - resourcefulconfig 2.1.2
>         - resourcefullib 2.1.28
>         - royalvariations 1.0.0
>         - saturn 0.1.3
>         - sawmill 1.20-1.4.3
>         - seedbags 1.0.1
>         - shieldexp 1.1.7a
>         - sleep_tight 1.20-1.1.19
>         - smartbrainlib 1.14.2
>         - smoothboot 0.0.4
>         - sn0wfrogs_capybaras 1.1.0-mc1.20.1
>         - sootychimneys 1.2.1
>         - spark 1.10.53
>         - spelunkery 1.20.1-0.3.5
>         - structory 1.3.5
>         - structure_gel 2.16.2
>         - summer_sunset 1.0.0
>         - supernatural 2.11.1
>         - supplementaries 1.20-2.8.17
>                 \-- mixinsquared 0.1.1
>         - suppsquared 1.20-1.1.14
>         - takesapillage 1.0.3
>         - terrablender 3.0.1.7
>         - travelerstitles 1.20-Forge-4.0.2
>         - treechop 0.19.0
>         - tropicraft 9.6.3
>         - upgrade_aquatic 6.0.0
>         - valhelsia_core 1.1.2
>         - valhelsia_furniture 1.1.3
>         - valhelsia_structures 1.20.1-1.1.2
>         - vc_gliders 1.1.5
>                 \-- palladiumcore 1.20-2.0.0.0
>         - villagersellanimals 1.2.1
>         - visualworkbench 8.0.0
>         - voicechat 1.20.1-2.5.19
>         - wardrobe 1.0.3
>         - warriorsofpastepoch 1.0.0
>         - wunderlib 1.1.5
>         - yungsapi 1.20-Forge-4.0.5
>         - zeta 1.0-19
>         - zetter 0.21.5
> ```
> 
> **Plugin list :** nop
> 
> **Description of issue :**
> 
> I saw commit with similar problem.
> 
> ```
> https://github.com/MohistMC/Mohist/blob/1.20.1/patches/minecraft/net/minecraft/world/item/crafting/RecipeManager.java.patch
> ```

Remove the mod sawmill-1.20-1.4.3.jar

**Comment by K0rS1z** [comment]
Remove the mod sawmill-1.20-1.4.3.jar
