### ISSUE TITLE
[1.20.1] Minecraft Transit Railway模组放置的轨道等数据无法在关服的时候保存

### ISSUE THREAD

**Issue by Lonmo0208** [Teneted/Tenet#3354]
**Minecraft Version :*1.20.1* 

**Mohist Version : 863 ~ 865, 867 (都出现相同问题,更早之前未测试)

**Operating System : Windows11 / Luixn （都出现相同问题）* 

**Concerned mod / plugin : https://cdn.modrinth.com/data/XKPAmI6u/versions/YLvg95i9/MTR-forge-1.20.1-3.2.2-hotfix-2.jar

**Logs :** Link(s) of logs and crash reports if you have：
没有错误报告，只有一条本人觉得可疑的输出日志
[03:48:46 INFO]: Stopped m.l.o.e.j.s.ServletContextHandler@7663af86{/,union:/G:/ef7094fc-b601-47a1-9d23-f9c57c52743a%20(1)/mods/MTR-forge-1.20.1-3.2.2-hotfix-2.jar%23480!/assets/mtr/website,STOPPED}

**Steps to Reproduce :
正常加入服务器 拿出Minecraft Transit Railway的轨道节点前后放置两个 两个拿出Minecraft Transit Railway模组的任意轨道连接器
分别右键两个节点 然后正常使用/stop关闭服务器 然后重新开服务器 会发现刚才的操作并没有被保存存档内

**Description of issue :
Minecraft Transit Railway模组在存档文件夹内有一个独立的文件夹名为 mtr 里面正常有所有维度在关闭服务器的时候保存下来的铁轨数据 但是在mohist的情况下关闭服务器 数据并没有被保存到里面

**Comment by Lonmo0208** [comment]
在867开服的时候出现了模组警告
[17:50:57 WARN]: FAILED ServerConnector@4d937025{HTTP/1.1, (http/1.1)}{0.0.0.0:8888}: java.io.IOException: Failed to bind to 0.0.0.0/0.0.0.0:8888
java.io.IOException: Failed to bind to 0.0.0.0/0.0.0.0:8888
        at mtr.libraries.org.eclipse.jetty.server.ServerConnector.openAcceptChannel(ServerConnector.java:349) ~[MTR-forge-1.20.1-3.2.2-hotfix-2.jar%23201!/:?]
        at mtr.libraries.org.eclipse.jetty.server.ServerConnector.open(ServerConnector.java:310) ~[MTR-forge-1.20.1-3.2.2-hotfix-2.jar%23201!/:?]
        at mtr.libraries.org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNetworkConnector.java:80) ~[MTR-forge-1.20.1-3.2.2-hotfix-2.jar%23201!/:?]
        at mtr.libraries.org.eclipse.jetty.server.ServerConnector.doStart(ServerConnector.java:234) ~[MTR-forge-1.20.1-3.2.2-hotfix-2.jar%23201!/:?]
        at mtr.libraries.org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73) ~[MTR-forge-1.20.1-3.2.2-hotfix-2.jar%23201!/:?]
        at mtr.libraries.org.eclipse.jetty.server.Server.doStart(Server.java:401) ~[MTR-forge-1.20.1-3.2.2-hotfix-2.jar%23201!/:?]
        at mtr.libraries.org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73) ~[MTR-forge-1.20.1-3.2.2-hotfix-2.jar%23201!/:?]
        at mtr.servlet.Webserver.start(Webserver.java:74) ~[MTR-forge-1.20.1-3.2.2-hotfix-2.jar%23201!/:?]
        at mtr.MTR.lambda$init$41(MTR.java:485) ~[MTR-forge-1.20.1-3.2.2-hotfix-2.jar%23201!/:?]
        at dev.architectury.event.forge.EventHandlerImplCommon.event(EventHandlerImplCommon.java:90) ~[architectury-9.2.14-forge.jar%23200!/:?]
        at dev.architectury.event.forge.__EventHandlerImplCommon_event_ServerStartingEvent.invoke(.dynamic) ~[architectury-9.2.14-forge.jar%23200!/:?]
        at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.5.jar%23150!/:?]
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:319) ~[eventbus-6.0.5.jar%23150!/:?]
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:299) ~[eventbus-6.0.5.jar%23150!/:?]
        at net.minecraftforge.server.ServerLifecycleHooks.handleServerStarting(ServerLifecycleHooks.java:112) ~[forge-1.20.1-47.3.10-universal.jar%23209!/:?]
        at net.minecraft.server.dedicated.DedicatedServer.m_7038_(DedicatedServer.java:272) ~[server-1.20.1-20230612.114412-srg.jar%23204!/:?]
        at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:856) ~[server-1.20.1-20230612.114412-srg.jar%23204!/:?]
        at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:286) ~[server-1.20.1-20230612.114412-srg.jar%23204!/:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.net.BindException: Address already in use: bind
        at sun.nio.ch.Net.bind0(Native Method) ~[?:?]
        at sun.nio.ch.Net.bind(Net.java:555) ~[?:?]
        at sun.nio.ch.ServerSocketChannelImpl.netBind(ServerSocketChannelImpl.java:337) ~[?:?]
        at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:294) ~[?:?]
        at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:89) ~[?:?]
        at mtr.libraries.org.eclipse.jetty.server.ServerConnector.openAcceptChannel(ServerConnector.java:344) ~[MTR-forge-1.20.1-3.2.2-hotfix-2.jar%23201!/:?]
        ... 18 more
[17:50:57 WARN]: FAILED Server@637df521{FAILED}[9.4.52.v20230823]: java.io.IOException: Failed to bind to 0.0.0.0/0.0.0.0:8888
java.io.IOException: Failed to bind to 0.0.0.0/0.0.0.0:8888
        at mtr.libraries.org.eclipse.jetty.server.ServerConnector.openAcceptChannel(ServerConnector.java:349) ~[MTR-forge-1.20.1-3.2.2-hotfix-2.jar%23201!/:?]
        at mtr.libraries.org.eclipse.jetty.server.ServerConnector.open(ServerConnector.java:310) ~[MTR-forge-1.20.1-3.2.2-hotfix-2.jar%23201!/:?]
        at mtr.libraries.org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNetworkConnector.java:80) ~[MTR-forge-1.20.1-3.2.2-hotfix-2.jar%23201!/:?]
        at mtr.libraries.org.eclipse.jetty.server.ServerConnector.doStart(ServerConnector.java:234) ~[MTR-forge-1.20.1-3.2.2-hotfix-2.jar%23201!/:?]
        at mtr.libraries.org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73) ~[MTR-forge-1.20.1-3.2.2-hotfix-2.jar%23201!/:?]
        at mtr.libraries.org.eclipse.jetty.server.Server.doStart(Server.java:401) ~[MTR-forge-1.20.1-3.2.2-hotfix-2.jar%23201!/:?]
        at mtr.libraries.org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73) ~[MTR-forge-1.20.1-3.2.2-hotfix-2.jar%23201!/:?]
        at mtr.servlet.Webserver.start(Webserver.java:74) ~[MTR-forge-1.20.1-3.2.2-hotfix-2.jar%23201!/:?]
        at mtr.MTR.lambda$init$41(MTR.java:485) ~[MTR-forge-1.20.1-3.2.2-hotfix-2.jar%23201!/:?]
        at dev.architectury.event.forge.EventHandlerImplCommon.event(EventHandlerImplCommon.java:90) ~[architectury-9.2.14-forge.jar%23200!/:?]
        at dev.architectury.event.forge.__EventHandlerImplCommon_event_ServerStartingEvent.invoke(.dynamic) ~[architectury-9.2.14-forge.jar%23200!/:?]
        at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.5.jar%23150!/:?]
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:319) ~[eventbus-6.0.5.jar%23150!/:?]
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:299) ~[eventbus-6.0.5.jar%23150!/:?]
        at net.minecraftforge.server.ServerLifecycleHooks.handleServerStarting(ServerLifecycleHooks.java:112) ~[forge-1.20.1-47.3.10-universal.jar%23209!/:?]
        at net.minecraft.server.dedicated.DedicatedServer.m_7038_(DedicatedServer.java:272) ~[server-1.20.1-20230612.114412-srg.jar%23204!/:?]
        at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:856) ~[server-1.20.1-20230612.114412-srg.jar%23204!/:?]
        at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:286) ~[server-1.20.1-20230612.114412-srg.jar%23204!/:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.net.BindException: Address already in use: bind
        at sun.nio.ch.Net.bind0(Native Method) ~[?:?]
        at sun.nio.ch.Net.bind(Net.java:555) ~[?:?]
        at sun.nio.ch.ServerSocketChannelImpl.netBind(ServerSocketChannelImpl.java:337) ~[?:?]
        at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:294) ~[?:?]
        at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:89) ~[?:?]
        at mtr.libraries.org.eclipse.jetty.server.ServerConnector.openAcceptChannel(ServerConnector.java:344) ~[MTR-forge-1.20.1-3.2.2-hotfix-2.jar%23201!/:?]
        ... 18 more
[17:50:57 WARN]: java.io.IOException: Failed to bind to 0.0.0.0/0.0.0.0:8888
[17:50:57 WARN]:        at TRANSFORMER/mtr@1.20.1-3.2.2-hotfix-2/mtr.libraries.org.eclipse.jetty.server.ServerConnector.openAcceptChannel(ServerConnector.java:349)
[17:50:57 WARN]:        at TRANSFORMER/mtr@1.20.1-3.2.2-hotfix-2/mtr.libraries.org.eclipse.jetty.server.ServerConnector.open(ServerConnector.java:310)
[17:50:57 WARN]:        at TRANSFORMER/mtr@1.20.1-3.2.2-hotfix-2/mtr.libraries.org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNetworkConnector.java:80)
[17:50:57 WARN]:        at TRANSFORMER/mtr@1.20.1-3.2.2-hotfix-2/mtr.libraries.org.eclipse.jetty.server.ServerConnector.doStart(ServerConnector.java:234)
[17:50:57 WARN]:        at TRANSFORMER/mtr@1.20.1-3.2.2-hotfix-2/mtr.libraries.org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
[17:50:57 WARN]:        at TRANSFORMER/mtr@1.20.1-3.2.2-hotfix-2/mtr.libraries.org.eclipse.jetty.server.Server.doStart(Server.java:401)
[17:50:57 WARN]:        at TRANSFORMER/mtr@1.20.1-3.2.2-hotfix-2/mtr.libraries.org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
[17:50:57 WARN]:        at TRANSFORMER/mtr@1.20.1-3.2.2-hotfix-2/mtr.servlet.Webserver.start(Webserver.java:74)
[17:50:57 WARN]:        at TRANSFORMER/mtr@1.20.1-3.2.2-hotfix-2/mtr.MTR.lambda$init$41(MTR.java:485)
[17:50:57 WARN]:        at TRANSFORMER/architectury@9.2.14/dev.architectury.event.forge.EventHandlerImplCommon.event(EventHandlerImplCommon.java:90)
[17:50:57 WARN]:        at TRANSFORMER/architectury@9.2.14/dev.architectury.event.forge.__EventHandlerImplCommon_event_ServerStartingEvent.invoke(.dynamic)
[17:50:57 WARN]:        at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73)
[17:50:57 WARN]:        at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:319)
[17:50:57 WARN]:        at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:299)
[17:50:57 WARN]:        at TRANSFORMER/forge@47.3.10/net.minecraftforge.server.ServerLifecycleHooks.handleServerStarting(ServerLifecycleHooks.java:112)
[17:50:57 WARN]:        at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.dedicated.DedicatedServer.m_7038_(DedicatedServer.java:272)
[17:50:57 WARN]:        at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:856)
[17:50:57 WARN]:        at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:286)
[17:50:57 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[17:50:57 WARN]: Caused by: java.net.BindException: Address already in use: bind
[17:50:57 WARN]:        at java.base/sun.nio.ch.Net.bind0(Native Method)
[17:50:57 WARN]:        at java.base/sun.nio.ch.Net.bind(Net.java:555)
[17:50:57 WARN]:        at java.base/sun.nio.ch.ServerSocketChannelImpl.netBind(ServerSocketChannelImpl.java:337)
[17:50:57 WARN]:        at java.base/sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:294)
[17:50:57 WARN]:        at java.base/sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:89)
[17:50:57 WARN]:        at TRANSFORMER/mtr@1.20.1-3.2.2-hotfix-2/mtr.libraries.org.eclipse.jetty.server.ServerConnector.openAcceptChannel(ServerConnector.java:344)
[17:50:57 WARN]:        ... 18 more

**Comment by Leonmmcoset** [comment]
我有同样的问题，但是说在新的mohist版本无法复现

**Comment by Lonmo0208** [comment]
> 我有同样的问题，但是说在新的mohist版本无法复现

你用新版本再试一次，出现同样问题在汇报一次试试？ 我这边都那么久了 也没人回复我处理一下

**Comment by Lonmo0208** [comment]
> 我有同样的问题，但是说在新的mohist版本无法复现

好的哥们 修了 
![463666d37962f634b5218b3b1d90215e](https://github.com/user-attachments/assets/d206c8a0-fbe2-40a3-9f60-4d8a892c2d4c)
