### ISSUE TITLE
[MC VERSION] LevelledMobs cant add nametags to mobs

### ISSUE THREAD

**Issue by RockeyWereWolf** [Teneted/Tenet#3375]
**Minecraft Version :** 1.20.1

**Mohist Version :** mohist-1.20.1-874-server.jar

**Operating System :** Ubuntru

**Concerned mod / plugin** : [LevelledMobs](https://www.spigotmc.org/resources/levelledmobs.74304/)

**Logs :** 
[15:14:13 WARN]: [LevelledMobs] Task #160605 for LevelledMobs v4.1.3 b68 generated an exception
java.lang.NoSuchMethodError: 'net.kyori.adventure.text.Component org.bukkit.entity.LivingEntity.name()'
        at io.github.arcaneplugins.levelledmobs.nametag.KyoriNametags.generateComponent(KyoriNametags.kt:66) ~[?:?]
        at io.github.arcaneplugins.levelledmobs.nametag.NmsNametagSender.buildNametagComponent(NmsNametagSender.kt:255) ~[?:?]
        at io.github.arcaneplugins.levelledmobs.nametag.NmsNametagSender.sendNametagNonAsync(NmsNametagSender.kt:71) ~[?:?]
        at io.github.arcaneplugins.levelledmobs.nametag.NmsNametagSender.sendNametag$lambda$0(NmsNametagSender.kt:39) ~[?:?]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:78) ~[forge-1.20.1-47.3.10-universal.jar%23223!/:?]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:416) ~[forge-1.20.1-47.3.10-universal.jar%23223!/:?]
        at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:1137) ~[server-1.20.1-20230612.114412-srg.jar%23218!/:?]
        at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:360) ~[server-1.20.1-20230612.114412-srg.jar%23218!/:?]
        at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:1071) ~[server-1.20.1-20230612.114412-srg.jar%23218!/:?]
        at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:910) ~[server-1.20.1-20230612.114412-srg.jar%23218!/:?]
        at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:286) ~[server-1.20.1-20230612.114412-srg.jar%23218!/:?]
        at java.lang.Thread.run(Thread.java:1583) [?:?]

**Steps to Reproduce :**
 1. Install the plugin
 2. Enable mob lvls at nametag
 3. See that there is no nametags of mobs at all and this error in console

**Description of issue :** I wrote all I know about the issue

**Comment by RockeyWereWolf** [comment]
@Mgazul Should I wait for a fix or it will take more than a week?
