### ISSUE TITLE
[1.20.1] 玩家无法发送聊天

### ISSUE THREAD

**Issue by BredyAK** [Teneted/Tenet#3377]
**Minecraft Version :** 1.20.1

**Mohist Version :** 879

**Operating System :** Debian GNU/Linux 9 (stretch) x86_64(Py3.7.8)

**Logs :** [https://mclo.gs/DVPJkIK](https://mclo.gs/DVPJkIK)（第 64 至 102 行）

**Mod list :** proxy-compatible-1.1.4（[https://modrinth.com/mod/proxy-compatible-forge](https://modrinth.com/mod/proxy-compatible-forge)，服务器运行于 Velocity 代理下，因此必须使用此 mod）

**Plugin list :** None / 无

**Description of issue :** 玩家无法发送聊天，发送任何聊天内容（非指令）均会出现以下错误：
```
Chain link failed, continuing to next one
java.lang.NullPointerException: Requires a decoration result to be set here
        at java.util.Objects.requireNonNull(Objects.java:259) ~[?:?]
        at net.minecraft.network.chat.PlayerChatMessage.requireResult(PlayerChatMessage.java:30) ~[server-1.20.1-20230612.114412-srg.jar%23200!/:?]
        at com.mohistmc.paper.adventure.ChatProcessor.<init>(ChatProcessor.java:80) ~[forge-1.20.1-47.3.10-universal.jar%23205!/:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.chat(ServerGamePacketListenerImpl.java:2978) ~[server-1.20.1-20230612.114412-srg.jar%23200!/:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.m_243086_(ServerGamePacketListenerImpl.java:1996) ~[server-1.20.1-20230612.114412-srg.jar%23200!/:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChat$12(ServerGamePacketListenerImpl.java:1842) ~[server-1.20.1-20230612.114412-srg.jar%23200!/:?]
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
        at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
```
聊天实际上是未成功发出的。但可以执行指令。

**Comment by Lonmo0208** [comment]
本人也遇到一样的问题
[22:36:31 ERROR]: Chain link failed, continuing to next one
java.lang.NullPointerException: Requires a decoration result to be set here
        at java.util.Objects.requireNonNull(Objects.java:259) ~[?:?]
        at net.minecraft.network.chat.PlayerChatMessage.requireResult(PlayerChatMessage.java:30) ~[server-1.20.1-20230612.114412-srg.jar%23536!/:?]
        at com.mohistmc.paper.adventure.ChatProcessor.<init>(ChatProcessor.java:80) ~[forge-1.20.1-47.3.10-universal.jar%23541!/:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.chat(ServerGamePacketListenerImpl.java:2978) ~[server-1.20.1-20230612.114412-srg.jar%23536!/:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.m_243086_(ServerGamePacketListenerImpl.java:1996) ~[server-1.20.1-20230612.114412-srg.jar%23536!/:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChat$12(ServerGamePacketListenerImpl.java:1842) ~[server-1.20.1-20230612.114412-srg.jar%23536!/:?]
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
        at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]

**Comment by BredyAK** [comment]
> 本人也遇到一样的问题 [22:36:31 ERROR]: Chain link failed, continuing to next one java.lang.NullPointerException: Requires a decoration result to be set here at java.util.Objects.requireNonNull(Objects.java:259) ~[?:?] at net.minecraft.network.chat.PlayerChatMessage.requireResult(PlayerChatMessage.java:30) ~[server-1.20.1-20230612.114412-srg.jar%23536!/:?] at com.mohistmc.paper.adventure.ChatProcessor.(ChatProcessor.java:80) ~[forge-1.20.1-47.3.10-universal.jar%23541!/:?] at net.minecraft.server.network.ServerGamePacketListenerImpl.chat(ServerGamePacketListenerImpl.java:2978) ~[server-1.20.1-20230612.114412-srg.jar%23536!/:?] at net.minecraft.server.network.ServerGamePacketListenerImpl.m_243086_(ServerGamePacketListenerImpl.java:1996) ~[server-1.20.1-20230612.114412-srg.jar%23536!/:?] at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChat$12(ServerGamePacketListenerImpl.java:1842) ~[server-1.20.1-20230612.114412-srg.jar%23536!/:?] at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?] at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?] at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?] at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]

老兄，又见面了，都在玩 Mohist 最新版呀

**Comment by Lonmo0208** [comment]
> > 本人也遇到一样的问题 [22:36:31 ERROR]: Chain link failed, continuing to next one java.lang.NullPointerException: Requires a decoration result to be set here at java.util.Objects.requireNonNull(Objects.java:259) ~[?:?] at net.minecraft.network.chat.PlayerChatMessage.requireResult(PlayerChatMessage.java:30) ~[server-1.20.1-20230612.114412-srg.jar%23536!/:?] at com.mohistmc.paper.adventure.ChatProcessor.(ChatProcessor.java:80) ~[forge-1.20.1-47.3.10-universal.jar%23541!/:?] at net.minecraft.server.network.ServerGamePacketListenerImpl.chat(ServerGamePacketListenerImpl.java:2978) ~[server-1.20.1-20230612.114412-srg.jar%23536!/:?] at net.minecraft.server.network.ServerGamePacketListenerImpl.m_243086_(ServerGamePacketListenerImpl.java:1996) ~[server-1.20.1-20230612.114412-srg.jar%23536!/:?] at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChat$12(ServerGamePacketListenerImpl.java:1842) ~[server-1.20.1-20230612.114412-srg.jar%23536!/:?] at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?] at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?] at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?] at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
> 
> 老兄，又见面了，都在玩 Mohist 最新版呀

是啊 hhh
这个问题可能是因为修我那个#3376导致的 
回退878吧hhh 真的是麻烦墨佬了

**Comment by Lonmo0208** [comment]
oh no 878 也有一样的问题。。。 那就不是为了修我那个3376的了
