### ISSUE TITLE
Fix all Eco plugins please

### ISSUE THREAD

**Issue by Unitei-Dev** [Teneted/Tenet#3408]
https://mclo.gs/72XdapY

Minecraft Version : 1.20.1

Mohist Version : 895

Operating System : Linux

Fix plz
[05:26:40] [Server thread/INFO] [Console]: [EcoItems] Enabling EcoItems v5.59.1
[05:26:40] [Server thread/INFO] [Console]: [EcoItems] Loading §xEcoItems
[05:26:40] [Server thread/INFO] [me.clip.placeholderapi.PlaceholderAPIPlugin]: [PlaceholderAPI] Successfully registered internal expansion: ecoitems [5.59.1]
[05:26:40] [Server thread/ERROR] [Minecraft]: Error occurred while enabling EcoItems v5.59.1 (Is it up to date?)
java.lang.LinkageError: loader constraint violation: when resolving method 'com.willfp.libreforge.ConfigArguments com.willfp.libreforge.ConfigArgumentsKt.arguments(kotlin.jvm.functions.Function1)' the class loader org.bukkit.plugin.java.PluginClassLoader @26458842 of the current class, com/willfp/ecoitems/libreforge/ConditionHasEcoItem, and the class loader org.bukkit.plugin.java.PluginClassLoader @1d63ea2b for the method's defining class, com/willfp/libreforge/ConfigArgumentsKt, have different Class objects for the type kotlin/jvm/functions/Function1 used in the signature (com.willfp.ecoitems.libreforge.ConditionHasEcoItem is in unnamed module of loader org.bukkit.plugin.java.PluginClassLoader @26458842, parent loader 'TRANSFORMER' @5709e10b; com.willfp.libreforge.ConfigArgumentsKt is in unnamed module of loader org.bukkit.plugin.java.PluginClassLoader @1d63ea2b, parent loader 'TRANSFORMER' @5709e10b)
    at com.willfp.ecoitems.libreforge.ConditionHasEcoItem.<clinit>(ConditionHasEcoItem.kt:18) ~[?:?]
    at com.willfp.ecoitems.EcoItemsPlugin.handleEnable(EcoItemsPlugin.kt:37) ~[?:?]
    at com.willfp.eco.core.EcoPlugin.handleLifecycle(EcoPlugin.java:738) ~[?:?]
    at com.willfp.eco.core.EcoPlugin.onEnable(EcoPlugin.java:472) ~[?:?]
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:348) ~[forge-1.20.1-47.3.11-universal.jar%23349!/:?]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338) ~[forge-1.20.1-47.3.11-universal.jar%23349!/:?]
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:484) ~[forge-1.20.1-47.3.11-universal.jar%23349!/:?]
    at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:547) ~[forge-1.20.1-47.3.11-universal.jar%23349!/:997de31d-ddc9a2dad-d2eba2c8-47.1.106]
    at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:461) ~[forge-1.20.1-47.3.11-universal.jar%23349!/:997de31d-ddc9a2dad-d2eba2c8-47.1.106]
    at net.minecraft.server.MinecraftServer.m_129815_(MinecraftServer.java:446) ~[server-1.20.1-20230612.114412-srg.jar%23344!/:?]
    at net.minecraft.server.MinecraftServer.m_130006_(MinecraftServer.java:346) ~[server-1.20.1-20230612.114412-srg.jar%23344!/:?]
    at net.minecraft.server.dedicated.DedicatedServer.m_7038_(DedicatedServer.java:233) ~[server-1.20.1-20230612.114412-srg.jar%23344!/:?]
    at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:856) ~[server-1.20.1-20230612.114412-srg.jar%23344!/:?]
    at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:286) ~[server-1.20.1-20230612.114412-srg.jar%23344!/:?]
    at java.lang.Thread.run(Thread.java:1583) [?:?]
[05:26:40] [Server thread/INFO] [Console]: [EcoItems] Disabling EcoItems v5.59.1
[05:26:40] [Server thread/INFO] [Console]: [EcoItems] Cleaning up...

**Comment by SNWCreations** [comment]
Can you reproduce it on pure-Bukkit server? It seems to be a Kotlin library conflict with other plugins.
