### ISSUE TITLE
Mohist does not work with atm9 pack anymore

### ISSUE THREAD

**Issue by funnycubeguy** [Teneted/Tenet#3418]
Due to the recent version of Supplementaries mohist will no longer load the atm9 all the mods modpack. 

https://www.curseforge.com/minecraft/mc-mods/supplementaries

https://pastes.dev/KtAGidWyDs

Please fix :)

**Comment by funnycubeguy** [comment]
Missing a fireblock class https://pastes.dev/SQEKxRKcbT

**Comment by MRMDevStudios** [comment]
Does not work on version 0.3.3a or 0.3.4 due to the supplimentaries mod not working anymore after the 1.20-3.0.0 update of the mod. 2 Errors seem to occur. One is the FireBlock event then after if you remove the fireblock mixin, you get this issue         "[22:09:21] [main/ERROR] [net.minecraftforge.eventbus.EventBus]: Exception caught during firing event: Cannot invoke "org.bukkit.craftbukkit.v1_20_R1.CraftServer.getTicksPerSpawns(org.bukkit.entity.SpawnCategory)" because the return value of "net.minecraft.world.level.Level.getCraftServer()" is null
	Index: 1
	Listeners:
		0: HIGH
		1: ASM: class net.mehvahdjukaar.moonlight.forge.MoonlightForge onTagUpdated(Lnet/minecraftforge/event/TagsUpdatedEvent;)V
		2: NORMAL
		3: ASM: net.minecraftforge.common.ForgeInternalHandler@3f7a5260 tagsUpdated(Lnet/minecraftforge/event/TagsUpdatedEvent;)V
		4: ASM: class net.mehvahdjukaar.supplementaries.common.events.forge.ServerEventsForge onTagUpdate(Lnet/minecraftforge/event/TagsUpdatedEvent;)V
java.lang.NullPointerException: Cannot invoke "org.bukkit.craftbukkit.v1_20_R1.CraftServer.getTicksPerSpawns(org.bukkit.entity.SpawnCategory)" because the return value of "net.minecraft.world.level.Level.getCraftServer()" is null
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.Level.<init>(Level.java:180)
	at TRANSFORMER/moonlight@1.20-2.13.22/net.mehvahdjukaar.moonlight.core.misc.FakeLevel.<init>(FakeLevel.java:71)
	at TRANSFORMER/supplementaries@1.20-3.1.1/net.mehvahdjukaar.supplementaries.common.utils.fake_level.BlockTestLevel.<init>(BlockTestLevel.java:18)
	at TRANSFORMER/moonlight@1.20-2.13.22/net.mehvahdjukaar.moonlight.core.misc.FakeLevel.lambda$get$1(FakeLevel.java:90)
	at java.base/java.util.Map.computeIfAbsent(Map.java:1054)
	at TRANSFORMER/moonlight@1.20-2.13.22/net.mehvahdjukaar.moonlight.core.misc.FakeLevel.get(FakeLevel.java:90)
	at TRANSFORMER/supplementaries@1.20-3.1.1/net.mehvahdjukaar.supplementaries.common.utils.fake_level.BlockTestLevel.get(BlockTestLevel.java:14)
	at TRANSFORMER/supplementaries@1.20-3.1.1/net.mehvahdjukaar.supplementaries.common.block.faucet.FaucetBehaviorsManager.parse(FaucetBehaviorsManager.java:101)
	at TRANSFORMER/moonlight@1.20-2.13.22/net.mehvahdjukaar.moonlight.api.misc.RegistryAccessJsonReloadListener.runReloads(RegistryAccessJsonReloadListener.java:28)
	at TRANSFORMER/moonlight@1.20-2.13.22/net.mehvahdjukaar.moonlight.core.Moonlight.afterDataReload(Moonlight.java:125)
	at TRANSFORMER/moonlight@1.20-2.13.22/net.mehvahdjukaar.moonlight.forge.MoonlightForge.onTagUpdated(MoonlightForge.java:71)
	at TRANSFORMER/moonlight@1.20-2.13.22/net.mehvahdjukaar.moonlight.forge.__MoonlightForge_onTagUpdated_TagsUpdatedEvent.invoke(.dynamic)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:319)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:299)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.ReloadableServerResources.m_206868_(ReloadableServerResources.java:90)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.WorldLoader.m_244809_(WorldLoader.java:44)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.Util.m_214652_(Util.java:783)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.Util.m_214679_(Util.java:772)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.Main.main(Main.java:220)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at MC-BOOTSTRAP/fmlloader@1.20.1-47.3.11/net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111)
	at MC-BOOTSTRAP/fmlloader@1.20.1-47.3.11/net.minecraftforge.fml.loading.targets.CommonLaunchHandler.serverService(CommonLaunchHandler.java:103)
	at MC-BOOTSTRAP/fmlloader@1.20.1-47.3.11/net.minecraftforge.fml.loading.targets.CommonServerLaunchHandler.lambda$makeService$0(CommonServerLaunchHandler.java:27)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.run(Launcher.java:108)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.main(Launcher.java:78)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
	at cpw.mods.bootstraplauncher@1.1.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141)
	at com.mohistmc.MohistMCStart.main(MohistMCStart.java:116)

[22:09:21] [main/WARN] [net.minecraft.server.Main]: Failed to load datapacks, can't proceed with server load. You can either fix your datapacks or reset to vanilla with --safeMode
java.util.concurrent.ExecutionException: java.lang.NullPointerException: Cannot invoke "org.bukkit.craftbukkit.v1_20_R1.CraftServer.getTicksPerSpawns(org.bukkit.entity.SpawnCategory)" because the return value of "net.minecraft.world.level.Level.getCraftServer()" is null
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396) ~[?:?]
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073) ~[?:?]
	at net.minecraft.server.Main.main(Main.java:250) ~[server-1.20.1-20230612.114412-srg.jar%23202!/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.3.11.jar%23192!/:?]
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.serverService(CommonLaunchHandler.java:103) ~[fmlloader-1.20.1-47.3.11.jar%23192!/:?]
	at net.minecraftforge.fml.loading.targets.CommonServerLaunchHandler.lambda$makeService$0(CommonServerLaunchHandler.java:27) ~[fmlloader-1.20.1-47.3.11.jar%23192!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.9.jar%23103!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.9.jar%23103!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.9.jar%23103!/:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) [modlauncher-10.0.9.jar%23103!/:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) [modlauncher-10.0.9.jar%23103!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.9.jar%23103!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.9.jar%23103!/:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?]
	at com.mohistmc.MohistMCStart.main(MohistMCStart.java:116) [mohist.jar:1.20.1-896]
Caused by: java.lang.NullPointerException: Cannot invoke "org.bukkit.craftbukkit.v1_20_R1.CraftServer.getTicksPerSpawns(org.bukkit.entity.SpawnCategory)" because the return value of "net.minecraft.world.level.Level.getCraftServer()" is null
	at net.minecraft.world.level.Level.<init>(Level.java:180) ~[server-1.20.1-20230612.114412-srg.jar%23202!/:?]
	at net.mehvahdjukaar.moonlight.core.misc.FakeLevel.<init>(FakeLevel.java:71) ~[moonlight-1.20-2.13.22-forge.jar%23199!/:?]
	at net.mehvahdjukaar.supplementaries.common.utils.fake_level.BlockTestLevel.<init>(BlockTestLevel.java:18) ~[supplementaries-1.20-3.1.3.jar%23200!/:?]
	at net.mehvahdjukaar.moonlight.core.misc.FakeLevel.lambda$get$1(FakeLevel.java:90) ~[moonlight-1.20-2.13.22-forge.jar%23199!/:?]
	at java.util.Map.computeIfAbsent(Map.java:1054) ~[?:?]
	at net.mehvahdjukaar.moonlight.core.misc.FakeLevel.get(FakeLevel.java:90) ~[moonlight-1.20-2.13.22-forge.jar%23199!/:?]
	at net.mehvahdjukaar.supplementaries.common.utils.fake_level.BlockTestLevel.get(BlockTestLevel.java:14) ~[supplementaries-1.20-3.1.3.jar%23200!/:?]
	at net.mehvahdjukaar.supplementaries.common.block.faucet.FaucetBehaviorsManager.parse(FaucetBehaviorsManager.java:101) ~[supplementaries-1.20-3.1.3.jar%23200!/:?]
	at net.mehvahdjukaar.moonlight.api.misc.RegistryAccessJsonReloadListener.runReloads(RegistryAccessJsonReloadListener.java:28) ~[moonlight-1.20-2.13.22-forge.jar%23199!/:?]
	at net.mehvahdjukaar.moonlight.core.Moonlight.afterDataReload(Moonlight.java:125) ~[moonlight-1.20-2.13.22-forge.jar%23199!/:?]
	at net.mehvahdjukaar.moonlight.forge.MoonlightForge.onTagUpdated(MoonlightForge.java:71) ~[moonlight-1.20-2.13.22-forge.jar%23199!/:?]
	at net.mehvahdjukaar.moonlight.forge.__MoonlightForge_onTagUpdated_TagsUpdatedEvent.invoke(.dynamic) ~[moonlight-1.20-2.13.22-forge.jar%23199!/:?]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.5.jar%23150!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:319) ~[eventbus-6.0.5.jar%23150!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:299) ~[eventbus-6.0.5.jar%23150!/:?]
	at net.minecraft.server.ReloadableServerResources.m_206868_(ReloadableServerResources.java:90) ~[server-1.20.1-20230612.114412-srg.jar%23202!/:?]
	at net.minecraft.server.WorldLoader.m_244809_(WorldLoader.java:44) ~[server-1.20.1-20230612.114412-srg.jar%23202!/:?]
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at net.minecraft.Util.m_214652_(Util.java:783) ~[server-1.20.1-20230612.114412-srg.jar%23202!/:?]
	at net.minecraft.Util.m_214679_(Util.java:772) ~[server-1.20.1-20230612.114412-srg.jar%23202!/:?]
	at net.minecraft.server.Main.main(Main.java:220) ~[server-1.20.1-20230612.114412-srg.jar%23202!/:?]
	... 16 more
"

This is as far as i got so far

**Comment by MRMDevStudios** [comment]
This is after the installation of 897   
[03:59:58 ERROR]: Exception caught during firing event: Receiver class net.mehvahdjukaar.supplementaries.common.utils.fake_level.BlockTestLevel does not define or inherit an implementation of the resolved method 'abstract net.minecraft.server.level.ServerLevel getMinecraftWorld()' of interface net.minecraft.world.level.LevelAccessor.
        Index: 3
        Listeners:
                0: HIGHEST
                1: net.minecraftforge.eventbus.EventBus$$Lambda$1611/0x00000133f0818000@1f97328b
                2: HIGH
                3: ASM: class net.mehvahdjukaar.moonlight.forge.MoonlightForge onTagUpdated(Lnet/minecraftforge/event/TagsUpdatedEvent;)V
                4: NORMAL
                5: net.minecraftforge.eventbus.EventBus$$Lambda$1611/0x00000133f0818000@1a4c006e
                6: ASM: class com.teammoeg.caupona.data.RecipeReloadListener onTagsUpdated(Lnet/minecraftforge/event/TagsUpdatedEvent;)V
                7: net.minecraftforge.eventbus.EventBus$$Lambda$1611/0x00000133f0818000@2bf1a4c1
                8: ASM: class com.enderio.machines.common.blockentity.task.SpawnerMachineTask reloadTags(Lnet/minecraftforge/event/TagsUpdatedEvent;)V
                9: ASM: class net.bdew.lib.recipes.RecipeReloadListener tagsUpdated(Lnet/minecraftforge/event/TagsUpdatedEvent;)V
                10: ASM: class glitchcore.forge.handlers.TagsUpdatedEventHandler onTagsUpdated(Lnet/minecraftforge/event/TagsUpdatedEvent;)V
                11: ASM: net.minecraftforge.common.ForgeInternalHandler@65f315a2 tagsUpdated(Lnet/minecraftforge/event/TagsUpdatedEvent;)V
                12: ASM: com.tom.createores.CreateOreExcavation@5c21707a reloadEvent(Lnet/minecraftforge/event/TagsUpdatedEvent;)V
                13: net.minecraftforge.eventbus.EventBus$$Lambda$1611/0x00000133f0818000@5ec195da
                14: ASM: class cofh.thermal.core.common.event.TCoreCommonSetupEvents tagsUpdated(Lnet/minecraftforge/event/TagsUpdatedEvent;)V
                15: net.minecraftforge.eventbus.EventBus$$Lambda$1611/0x00000133f0818000@7864e7e3
                16: ASM: com.ninni.twigs.events.MiscEvents@50b1e51b onTagsUpdated(Lnet/minecraftforge/event/TagsUpdatedEvent;)V
                17: ASM: me.desht.pneumaticcraft.common.event.MiscEventHandler@1ff00a91 onTagsUpdated(Lnet/minecraftforge/event/TagsUpdatedEvent;)V
                18: ASM: net.mehvahdjukaar.amendments.forge.AmendmentsForge@5c6699ba onTagUpdate(Lnet/minecraftforge/event/TagsUpdatedEvent;)V
                19: ASM: class blusunrize.immersiveengineering.common.world.Villages onTagsUpdated(Lnet/minecraftforge/event/TagsUpdatedEvent;)V
                20: ASM: class com.railwayteam.railways.forge.events.CommonEventsForge onTagsUpdated(Lnet/minecraftforge/event/TagsUpdatedEvent;)V
                21: ASM: class blusunrize.immersiveengineering.api.crafting.cache.CachedRecipeList onTagsUpdated(Lnet/minecraftforge/event/TagsUpdatedEvent;)V
                22: ASM: class com.stal111.forbidden_arcanus.common.event.DatapackEvents onTagsUpdate(Lnet/minecraftforge/event/TagsUpdatedEvent;)V
                23: ASM: class net.mehvahdjukaar.supplementaries.common.events.forge.ServerEventsForge onTagUpdate(Lnet/minecraftforge/event/TagsUpdatedEvent;)V
                24: ASM: com.blakebr0.mysticalagriculture.util.RecipeIngredientCache@40b08474 onTagsUpdated(Lnet/minecraftforge/event/TagsUpdatedEvent;)V
                25: ASM: com.blakebr0.cucumber.crafting.TagMapper@54b910ec onTagsUpdated(Lnet/minecraftforge/event/TagsUpdatedEvent;)V
                26: ASM: shetiphian.endertanks.common.misc.EventHandler@40623826 tagsUpdatedEvent(Lnet/minecraftforge/event/TagsUpdatedEvent;)V
                27: ASM: shetiphian.enderchests.common.misc.EventHandler@1e091359 tagsUpdatedEvent(Lnet/minecraftforge/event/TagsUpdatedEvent;)V
                28: LOWEST
                29: net.minecraftforge.eventbus.EventBus$$Lambda$1611/0x00000133f0818000@2d1d7f1
                30: net.minecraftforge.eventbus.EventBus$$Lambda$1611/0x00000133f0818000@2420bcc6
                31: net.minecraftforge.eventbus.EventBus$$Lambda$1611/0x00000133f0818000@769d82dd
                32: net.minecraftforge.eventbus.EventBus$$Lambda$1611/0x00000133f0818000@29992812
java.lang.AbstractMethodError: Receiver class net.mehvahdjukaar.supplementaries.common.utils.fake_level.BlockTestLevel does not define or inherit an implementation of the resolved method 'abstract net.minecraft.server.level.ServerLevel getMinecraftWorld()' of interface net.minecraft.world.level.LevelAccessor.
        at TRANSFORMER/forge@47.3.11/org.bukkit.craftbukkit.v1_20_R1.block.CraftBlock.getWorld(CraftBlock.java:98)
        at TRANSFORMER/forge@47.3.11/org.bukkit.craftbukkit.v1_20_R1.block.CraftBlockState.<init>(CraftBlockState.java:34)
        at TRANSFORMER/forge@47.3.11/org.bukkit.craftbukkit.v1_20_R1.block.CraftBlockStates.getBlockState(CraftBlockStates.java:437)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.block.LayeredCauldronBlock.changeLevel(LayeredCauldronBlock.java:87)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.core.cauldron.CauldronInteraction.m_175618_(CauldronInteraction.java:286)
        at TRANSFORMER/undergarden@0.8.14/quek.undergarden.registry.UGCauldronInteractions.lambda$static$0(UGCauldronInteractions.java:13)
        at TRANSFORMER/supplementaries@1.20-3.1.1/net.mehvahdjukaar.supplementaries.common.block.faucet.FaucetBehaviorsManager.parse(FaucetBehaviorsManager.java:114)
        at TRANSFORMER/moonlight@1.20-2.13.22/net.mehvahdjukaar.moonlight.api.misc.RegistryAccessJsonReloadListener.runReloads(RegistryAccessJsonReloadListener.java:28)
        at TRANSFORMER/moonlight@1.20-2.13.22/net.mehvahdjukaar.moonlight.core.Moonlight.afterDataReload(Moonlight.java:125)
        at TRANSFORMER/moonlight@1.20-2.13.22/net.mehvahdjukaar.moonlight.forge.MoonlightForge.onTagUpdated(MoonlightForge.java:71)
        at TRANSFORMER/moonlight@1.20-2.13.22/net.mehvahdjukaar.moonlight.forge.__MoonlightForge_onTagUpdated_TagsUpdatedEvent.invoke(.dynamic)
        at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73)
        at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:319)
        at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:299)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.ReloadableServerResources.m_206868_(ReloadableServerResources.java:90)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.WorldLoader.m_244809_(WorldLoader.java:44)
        at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
        at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.Util.m_214652_(Util.java:783)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.Util.m_214679_(Util.java:772)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.Main.main(Main.java:220)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at MC-BOOTSTRAP/fmlloader@1.20.1-47.3.11/net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111)
        at MC-BOOTSTRAP/fmlloader@1.20.1-47.3.11/net.minecraftforge.fml.loading.targets.CommonLaunchHandler.serverService(CommonLaunchHandler.java:103)
        at MC-BOOTSTRAP/fmlloader@1.20.1-47.3.11/net.minecraftforge.fml.loading.targets.CommonServerLaunchHandler.lambda$makeService$0(CommonServerLaunchHandler.java:27)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.run(Launcher.java:108)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.main(Launcher.java:78)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
        at cpw.mods.bootstraplauncher@1.1.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141)
        at com.mohistmc.MohistMCStart.main(MohistMCStart.java:116)

[03:59:58 WARN]: Failed to load datapacks, can't proceed with server load. You can either fix your datapacks or reset to vanilla with --safeMode
java.util.concurrent.ExecutionException: java.lang.AbstractMethodError: Receiver class net.mehvahdjukaar.supplementaries.common.utils.fake_level.BlockTestLevel does not define or inherit an implementation of the resolved method 'abstract net.minecraft.server.level.ServerLevel getMinecraftWorld()' of interface net.minecraft.world.level.LevelAccessor.
        at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396) ~[?:?]        at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073) ~[?:?]
        at net.minecraft.server.Main.main(Main.java:250) ~[server-1.20.1-20230612.114412-srg.jar%231022!/:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.3.11.jar%23192!/:?]
        at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.serverService(CommonLaunchHandler.java:103) ~[fmlloader-1.20.1-47.3.11.jar%23192!/:?]
        at net.minecraftforge.fml.loading.targets.CommonServerLaunchHandler.lambda$makeService$0(CommonServerLaunchHandler.java:27) ~[fmlloader-1.20.1-47.3.11.jar%23192!/:?]
        at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.9.jar%23103!/:?]
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.9.jar%23103!/:?]
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.9.jar%23103!/:?]
        at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) [modlauncher-10.0.9.jar%23103!/:?]
        at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) [modlauncher-10.0.9.jar%23103!/:?]
        at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.9.jar%23103!/:?]
        at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.9.jar%23103!/:?]
        at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?]
        at com.mohistmc.MohistMCStart.main(MohistMCStart.java:116) [mohist.jar:1.20.1-897]
Caused by: java.lang.AbstractMethodError: Receiver class net.mehvahdjukaar.supplementaries.common.utils.fake_level.BlockTestLevel does not define or inherit an implementation of the resolved method 'abstract net.minecraft.server.level.ServerLevel getMinecraftWorld()' of interface net.minecraft.world.level.LevelAccessor.
        at org.bukkit.craftbukkit.v1_20_R1.block.CraftBlock.getWorld(CraftBlock.java:98) ~[forge-1.20.1-47.3.11-universal.jar%231027!/:?]
        at org.bukkit.craftbukkit.v1_20_R1.block.CraftBlockState.<init>(CraftBlockState.java:34) ~[forge-1.20.1-47.3.11-universal.jar%231027!/:?]
        at org.bukkit.craftbukkit.v1_20_R1.block.CraftBlockStates.getBlockState(CraftBlockStates.java:437) ~[forge-1.20.1-47.3.11-universal.jar%231027!/:?]
        at net.minecraft.world.level.block.LayeredCauldronBlock.changeLevel(LayeredCauldronBlock.java:87) ~[server-1.20.1-20230612.114412-srg.jar%231022!/:?]
        at net.minecraft.core.cauldron.CauldronInteraction.m_175618_(CauldronInteraction.java:286) ~[server-1.20.1-20230612.114412-srg.jar%231022!/:?]
        at quek.undergarden.registry.UGCauldronInteractions.lambda$static$0(UGCauldronInteractions.java:13) ~[The_Undergarden-1.20.1-0.8.14.jar%23970!/:0.8.14]
        at net.mehvahdjukaar.supplementaries.common.block.faucet.FaucetBehaviorsManager.parse(FaucetBehaviorsManager.java:114) ~[supplementaries-1.20-3.1.3.jar%23965!/:?]
        at net.mehvahdjukaar.moonlight.api.misc.RegistryAccessJsonReloadListener.runReloads(RegistryAccessJsonReloadListener.java:28) ~[moonlight-1.20-2.13.22-forge.jar%23867!/:?]
        at net.mehvahdjukaar.moonlight.core.Moonlight.afterDataReload(Moonlight.java:125) ~[moonlight-1.20-2.13.22-forge.jar%23867!/:?]
        at net.mehvahdjukaar.moonlight.forge.MoonlightForge.onTagUpdated(MoonlightForge.java:71) ~[moonlight-1.20-2.13.22-forge.jar%23867!/:?]
        at net.mehvahdjukaar.moonlight.forge.__MoonlightForge_onTagUpdated_TagsUpdatedEvent.invoke(.dynamic) ~[moonlight-1.20-2.13.22-forge.jar%23867!/:?]
        at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.5.jar%23150!/:?]
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:319) ~[eventbus-6.0.5.jar%23150!/:?]
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:299) ~[eventbus-6.0.5.jar%23150!/:?]
        at net.minecraft.server.ReloadableServerResources.m_206868_(ReloadableServerResources.java:90) ~[server-1.20.1-20230612.114412-srg.jar%231022!/:?]
        at net.minecraft.server.WorldLoader.m_244809_(WorldLoader.java:44) ~[server-1.20.1-20230612.114412-srg.jar%231022!/:?]
        at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646) ~[?:?]
        at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
        at net.minecraft.Util.m_214652_(Util.java:783) ~[server-1.20.1-20230612.114412-srg.jar%231022!/:?]
        at net.minecraft.Util.m_214679_(Util.java:772) ~[server-1.20.1-20230612.114412-srg.jar%231022!/:?]
        at net.minecraft.server.Main.main(Main.java:220) ~[server-1.20.1-20230612.114412-srg.jar%231022!/:?]
        ... 16 more
        
        This is after the installation of 897
