### ISSUE TITLE
[1.20.1] The server is unable to load the QuickShop Hikari plugin properly

### ISSUE THREAD

**Issue by MC-Nirvana** [Teneted/Tenet#3422]
**Minecraft Version :** 1.20.1

**Mohist Version :** Mohist - 1.20.1-896

**Operating System :** Microsoft Windows 11 Professional Workstation Edition 24H2 26120.2222

**Concerned mod / plugin** : [QuickShop Hikari](https://modrinth.com/plugin/quickshop-hikari)

**Logs :** https://mclo.gs/UO7iVqZ

**Steps to Reproduce :**
 1. Store the plugins in the 'plugins' folder
 2. Start the server to initialize the plugin
 3. Unable to load plugin with error message

**Description of issue :** The server is unable to load the QuickShop-Hikari plugin correctly, and may even fail to initialize the plugin properly.

**Comment by SNWCreations** [comment]
Might be a dependency conflict between the plugin and the server. confliction happened at Aether (used by Spigot library loader and libby).

**Comment by MC-Nirvana** [comment]
But according to testing, spigot1.20.1 can use the plugin normally. Mainly because we have not found any similar alternatives so far. Otherwise, I may consider replacing this plugin.

**Comment by SNWCreations** [comment]
将这个留给Mgazul大佬吧，我觉得处理建议是升级Mohist的依赖项。

**Comment by MC-Nirvana** [comment]
希望能尽快修复吧，同类型的插件除了QS外基本没什么可以用了。

**Comment by TheFaser** [comment]
I have the same problem when using libby-2.0.0-snapshot on Mohist. On other bukkit platforms everything works
```java
[12:40:11] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: Starting minecraft server version 1.20.1
[12:40:11] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: Loading properties
[12:40:11] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: Default game type: SURVIVAL
[12:40:11] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Generating keypair
[12:40:12] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: Starting Minecraft server on *:17717
[12:40:12] [Server thread/INFO] [net.minecraft.server.network.ServerConnectionListener]: Using epoll channel type
[12:40:12] [Server thread/INFO] [Minecraft]: This server is running Mohist version 1.20.1-923 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT, Forge version 47.3.22, NeoForge version 47.1.106)
[12:40:13] [Server thread/INFO] [Minecraft]: Debug logging is enabled
[12:40:13] [Server thread/INFO] []: Server Ping Player Sample Count: 20
[12:40:13] [Server thread/INFO] [Minecraft]: Using 4 threads for Netty based IO
[12:40:14] [Server thread/INFO] [net.flectone.pulse.BukkitFlectonePulse]: [FlectonePulse] Loading FlectonePulse v0.3.0
[12:40:14] [Server thread/ERROR] [org.bukkit.craftbukkit.v1_20_R1.CraftServer]: java.lang.reflect.InvocationTargetException initializing FlectonePulse v0.3.0 (Is it up to date?)
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at net.flectone.pulse.library.libby.transitive.TransitiveDependencyHelper.<init>(TransitiveDependencyHelper.java:109) ~[?:?]
	at net.flectone.pulse.library.libby.LibraryManager.resolveTransitiveLibraries(LibraryManager.java:698) ~[?:?]
	at net.flectone.pulse.library.libby.LibraryManager.loadLibrary(LibraryManager.java:721) ~[?:?]
	at net.flectone.pulse.platform.LibraryResolver.loadLibrary(LibraryResolver.java:27) ~[?:?]
	at java.util.ArrayList.forEach(ArrayList.java:1596) ~[?:?]
	at net.flectone.pulse.platform.LibraryResolver.loadLibraries(LibraryResolver.java:31) ~[?:?]
	at net.flectone.pulse.platform.LibraryResolver.loadLibraries(LibraryResolver.java:35) ~[?:?]
	at net.flectone.pulse.BukkitFlectonePulse.onLoad(BukkitFlectonePulse.java:49) ~[?:?]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.loadPlugins(CraftServer.java:440) ~[forge-1.20.1-47.3.22-universal.jar%23483!/:997de31d-ddc9a2dad-d2eba2c8-47.1.106]
	at net.minecraft.server.dedicated.DedicatedServer.m_7038_(DedicatedServer.java:225) ~[server-1.20.1-20230612.114412-srg.jar%23478!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:856) ~[server-1.20.1-20230612.114412-srg.jar%23478!/:?]
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:286) ~[server-1.20.1-20230612.114412-srg.jar%23478!/:?]
	at java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.lang.reflect.InvocationTargetException
	at jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:74) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:486) ~[?:?]
	at net.flectone.pulse.library.libby.transitive.TransitiveDependencyHelper.<init>(TransitiveDependencyHelper.java:94) ~[?:?]
	... 12 more
Caused by: java.lang.IllegalAccessError: class org.eclipse.aether.supplier.RepositorySystemSupplier tried to access method 'void org.eclipse.aether.internal.impl.DefaultUpdateCheckManager.<init>(org.eclipse.aether.internal.impl.TrackingFileManager, org.eclipse.aether.impl.UpdatePolicyAnalyzer)' (org.eclipse.aether.supplier.RepositorySystemSupplier is in unnamed module of loader net.flectone.pulse.library.libby.classloader.IsolatedClassLoader @b4629fd; org.eclipse.aether.internal.impl.DefaultUpdateCheckManager is in module org.apache.maven.resolver.impl@1.7.3 of loader 'MC-BOOTSTRAP' @44f9779c)
	at org.eclipse.aether.supplier.RepositorySystemSupplier.getUpdateCheckManager(RepositorySystemSupplier.java:173) ~[?:?]
	at org.eclipse.aether.supplier.RepositorySystemSupplier.get(RepositorySystemSupplier.java:528) ~[?:?]
	at com.alessiodp.libby.maven.resolver.TransitiveDependencyCollector.newRepositorySystem(TransitiveDependencyCollector.java:178) ~[?:?]
	at com.alessiodp.libby.maven.resolver.TransitiveDependencyCollector.<init>(TransitiveDependencyCollector.java:56) ~[?:?]
	at jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:486) ~[?:?]
	at net.flectone.pulse.library.libby.transitive.TransitiveDependencyHelper.<init>(TransitiveDependencyHelper.java:94) ~[?:?]
	... 12 more
```

**Comment by Mgazul** [comment]
Fixed
