### ISSUE TITLE
[1.20.1] MythicMobs Bug

### ISSUE THREAD

**Issue by iSoulEs** [Teneted/Tenet#3452]
**Minecraft Version :** 1.20.1

**Mohist Version :** mohist-1.20.1-909

**Operating System :** Windows 10

**Concerned mod / plugin** : MythicMobs-5.8.0-SNAPSHOT 5279 

**Logs :** https://pastebin.com/1XxTcYrZ

**Steps to Reproduce :**
 
 1. Do "/mm reload "  or any mm command

**Description of issue :** 

The plugin seems to work fine, it has 2 strange errors that didn't happen before (it doesn't happen with MythicMobs-5.6.2).
When you are inside the server and use the reload or any command of the plugin, it throws an error, but you can do it from the console and it works perfectly. Also when entering the server, the following error will start to appear in the console.
[MythicMobs] An error occurred while adding an AIGoalSelector, enable debugging for a stack trace.

debug:

An error occurred while adding an AIGoalSelector, enable debugging for a stack trace.
[07:56:47 WARN]: java.lang.ClassCastException: class net.minecraft.world.entity.ai.control.BodyRotationControl cannot be cast to class net.minecraft.world.entity.ai.goal.GoalSelector (net.minecraft.world.entity.ai.control.BodyRotationControl and net.minecraft.world.entity.ai.goal.GoalSelector are in module minecraft@1.20.1 of loader 'TRANSFORMER' @6ee5f485)
[07:56:47 WARN]:        at io.lumine.mythic.core.volatilecode.v1_20_R1.VolatileAIHandlerImpl.addPathfinderGoals(VolatileAIHandlerImpl.java:195)
[07:56:47 WARN]:        at io.lumine.mythic.core.mobs.MobType.applyMobVolatileOptions(MobType.java:1283)
[07:56:47 WARN]:        at io.lumine.mythic.core.mobs.ActiveMob.setLevel(ActiveMob.java:494)
[07:56:47 WARN]:        at io.lumine.mythic.core.mobs.MobType.spawn(MobType.java:1018)
[07:56:47 WARN]:        at io.lumine.mythic.core.mobs.MobExecutor.spawnMob(MobExecutor.java:579)
[07:56:47 WARN]:        at io.lumine.mythic.core.mobs.MobExecutor.spawnMob(MobExecutor.java:572)
[07:56:47 WARN]:        at io.lumine.mythic.core.spawning.random.RandomSpawner.spawn(RandomSpawner.java:322)
[07:56:47 WARN]:        at io.lumine.mythic.core.spawning.random.RandomSpawnerManager.handleSpawnEvent(RandomSpawnerManager.java:166)
[07:56:47 WARN]:        at io.lumine.mythic.bukkit.listeners.MobListeners.lambda$load$8(MobListeners.java:170)
[07:56:47 WARN]:        at io.lumine.mythic.bukkit.utils.Delegates$ConsumerToBiConsumerSecond.accept(Delegates.java:144)
[07:56:47 WARN]:        at io.lumine.mythic.bukkit.utils.events.functional.single.EventListener.execute(EventListener.java:131)
[07:56:47 WARN]:        at TRANSFORMER/forge@47.3.5/org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[07:56:47 WARN]:        at TRANSFORMER/forge@47.3.5/org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:604)
[07:56:47 WARN]:        at TRANSFORMER/forge@47.3.5/org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:588)
[07:56:47 WARN]:        at TRANSFORMER/forge@47.3.5/org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.callCreatureSpawnEvent(CraftEventFactory.java:735)
[07:56:47 WARN]:        at TRANSFORMER/forge@47.3.5/org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.doEntityAddEventCalling(CraftEventFactory.java:656)
[07:56:47 WARN]:        at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.level.ServerLevel.m_8872_(ServerLevel.java:1065)
[07:56:47 WARN]:        at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.level.ServerLevel.m_7967_(ServerLevel.java:998)
[07:56:47 WARN]:        at java.base/java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411)
[07:56:47 WARN]:        at java.base/java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:734)
[07:56:47 WARN]:        at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
[07:56:47 WARN]:        at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.ServerLevelAccessor.m_47205_(ServerLevelAccessor.java:11)
[07:56:47 WARN]:        at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.NaturalSpawner.m_47038_(NaturalSpawner.java:197)
[07:56:47 WARN]:        at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.NaturalSpawner.m_47045_(NaturalSpawner.java:135)
[07:56:47 WARN]:        at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.NaturalSpawner.m_47029_(NaturalSpawner.java:125)
[07:56:47 WARN]:        at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.level.ServerChunkCache.m_8490_(ServerChunkCache.java:388)
[07:56:47 WARN]:        at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.level.ServerChunkCache.m_201698_(ServerChunkCache.java:342)
[07:56:47 WARN]:        at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:444)
[07:56:47 WARN]:        at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:1166)
[07:56:47 WARN]:        at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:360)
[07:56:47 WARN]:        at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:1071)
[07:56:47 WARN]:        at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:910)
[07:56:47 WARN]:        at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:286)
[07:56:47 WARN]:        at java.base/java.lang.Thread.run(Thread.java:842)

**Comment by Unitei-Dev** [comment]
MythicMobs paper plugin

**Comment by Unitei-Dev** [comment]
use 5.6.2

**Comment by iSoulEs** [comment]
> use 5.6.2
 Fixed on banner
 
https://github.com/MohistMC/Banner/commit/434ab8f4eab0cad323856d3938efbd28642d41c8

@Mgazul can you port this to fix the 1.20.1 forge version?
