### ISSUE TITLE
Issues with Aikar Timings?

### ISSUE THREAD

**Issue by Zilacon** [Teneted/Tenet#347]
First off i got 3 errors from 3 plugins spamming the consoles, all 3 have aikar timings in the errors. These plugins havent been changed or errored before, and ive never seen errors like these for these plugins.

```
[09:19:00 ERROR]: Could not pass event BlockPlaceEvent to mcMMO v1.5.09
 org.bukkit.event.EventException: null
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:63) ~[EventExecutor.class:1.12.2-b704e64]
	at org.bukkit.plugin.EventExecutor$$Lambda$2833/00000000786E8250.execute(Unknown Source) ~[?:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[TimedEventExecutor.class:1.12.2-b704e64]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66) ~[RegisteredListener.class:1.12.2-b704e64]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [SimplePluginManager.class:1.12.2-b704e64]
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callBlockPlaceEvent(CraftEventFactory.java:246) [CraftEventFactory.class:1.12.2-b704e64]
	at net.minecraftforge.event.world.BlockEvent$PlaceEvent.<init>(BlockEvent.java:219) [BlockEvent$PlaceEvent.class:1.12.2-b704e64]
	at net.minecraftforge.event.ForgeEventFactory.onPlayerBlockPlace(ForgeEventFactory.java:175) [ForgeEventFactory.class:1.12.2-b704e64]
	at net.minecraftforge.common.ForgeHooks.onPlaceItemIntoWorld(ForgeHooks.java:799) [ForgeHooks.class:1.12.2-b704e64]
	at net.minecraft.item.ItemStack.func_179546_a(ItemStack.java:197) [aip.class:?]
	at net.minecraft.server.management.PlayerInteractionManager.func_187251_a(PlayerInteractionManager.java:623) [or.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_184337_a(NetHandlerPlayServer.java:1142) [pa.class:?]
	at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(CPacketPlayerTryUseItemOnBlock.java:61) [ma.class:?]
	at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(CPacketPlayerTryUseItemOnBlock.java:13) [ma.class:?]
	at net.minecraft.network.PacketThreadUtil.lambda$checkThreadAndEnqueue$0(PacketThreadUtil.java:16) [hv.class:?]
	at net.minecraft.network.PacketThreadUtil$$Lambda$3216/0000000021174600.run(Unknown Source) [hv.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_252]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_252]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:839) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:466) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:778) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:624) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:821) [?:1.8.0_252]
Caused by: java.lang.NullPointerException
	at com.gmail.nossr50.util.StringUtils.getPrettyItemString(StringUtils.java:36) ~[?:?]
	at com.gmail.nossr50.util.StringUtils.getExplicitConfigMaterialDataString(StringUtils.java:338) ~[?:?]
	at com.gmail.nossr50.config.experience.ExperienceConfig.isSkillBlock(ExperienceConfig.java:213) ~[?:?]
	at com.gmail.nossr50.util.BlockUtils.affectedByGigaDrillBreaker(BlockUtils.java:172) ~[?:?]
	at com.gmail.nossr50.util.BlockUtils.shouldBeWatched(BlockUtils.java:33) ~[?:?]
	at com.gmail.nossr50.listeners.BlockListener.onBlockPlace(BlockListener.java:143) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor24.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:61) ~[EventExecutor.class:1.12.2-b704e64]
	... 23 more
```

```
[09:15:14 ERROR]: Could not pass event EntityDamageByEntityEvent to GriefPreventionPlus v13.3
 java.lang.NoClassDefFoundError: net/heyzeer0/mgh/api/bukkit/IBukkitEntity
	at com.apocgaming.gpp.listeners.EntityEventHandler.onEntityDamage(EntityEventHandler.java:161) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor417.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:61) ~[EventExecutor.class:1.12.2-b704e64]
	at org.bukkit.plugin.EventExecutor$$Lambda$2833/00000000786E8250.execute(Unknown Source) ~[?:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[TimedEventExecutor.class:1.12.2-b704e64]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66) ~[RegisteredListener.class:1.12.2-b704e64]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [SimplePluginManager.class:1.12.2-b704e64]
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callEvent(CraftEventFactory.java:189) [CraftEventFactory.class:1.12.2-b704e64]
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:715) [CraftEventFactory.class:1.12.2-b704e64]
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:586) [CraftEventFactory.class:1.12.2-b704e64]
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:745) [CraftEventFactory.class:1.12.2-b704e64]
	at net.minecraft.entity.EntityLivingBase.damageEntity_CB(EntityLivingBase.java:1643) [vp.class:?]
	at net.minecraft.entity.player.EntityPlayer.damageEntity_CB(EntityPlayer.java:1196) [aed.class:?]
	at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:1050) [vp.class:?]
	at net.minecraft.entity.player.EntityPlayer.func_70097_a(EntityPlayer.java:1091) [aed.class:?]
	at net.minecraft.entity.player.EntityPlayerMP.func_70097_a(EntityPlayerMP.java:822) [oq.class:?]
	at net.minecraft.entity.monster.EntityMob.func_70652_k(EntityMob.java:98) [ade.class:?]
	at net.minecraft.entity.ai.EntityAIAttackMelee.func_190102_a(EntityAIAttackMelee.java:179) [xo.class:?]
	at net.minecraft.entity.ai.EntityAIAttackMelee.func_75246_d(EntityAIAttackMelee.java:168) [xo.class:?]
	at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:129) [xf.class:?]
	at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:829) [vq.class:?]
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2648) [vp.class:?]
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:624) [vq.class:?]
	at net.minecraft.entity.monster.EntityMob.func_70636_d(EntityMob.java:44) [ade.class:?]
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2469) [vp.class:?]
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:333) [vq.class:?]
	at net.minecraft.entity.monster.EntityMob.func_70071_h_(EntityMob.java:49) [ade.class:?]
	at net.minecraft.entity.monster.EntitySpider.func_70071_h_(EntitySpider.java:85) [adn.class:?]
	at net.minecraft.world.World.func_72866_a(World.java:2407) [amu.class:?]
	at net.minecraft.world.World.func_72870_g(World.java:2358) [amu.class:?]
	at net.minecraft.world.World.func_72939_s(World.java:2129) [amu.class:?]
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:845) [oo.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:898) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:466) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:778) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:624) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:821) [?:1.8.0_252]
```

```
[09:13:44 ERROR]: Could not pass event InventoryCloseEvent to APOC-PayDay v3.0.25
 java.lang.AbstractMethodError: net/minecraft/inventory/IInventory.getLocation()Lorg/bukkit/Location;
	at org.bukkit.craftbukkit.v1_12_R1.inventory.CraftInventory.getLocation(CraftInventory.java:523) ~[CraftInventory.class:1.12.2-b704e64]
	at org.apocgaming.payday.listeners.ShopListener.onCloseChest(ShopListener.java:40) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor385.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:61) ~[EventExecutor.class:1.12.2-b704e64]
	at org.bukkit.plugin.EventExecutor$$Lambda$2833/00000000786E8250.execute(Unknown Source) ~[?:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[TimedEventExecutor.class:1.12.2-b704e64]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66) ~[RegisteredListener.class:1.12.2-b704e64]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [SimplePluginManager.class:1.12.2-b704e64]
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.handleInventoryCloseEvent(CraftEventFactory.java:1049) [CraftEventFactory.class:1.12.2-b704e64]
	at net.minecraft.network.NetHandlerPlayServer.func_147356_a(NetHandlerPlayServer.java:1866) [pa.class:?]
	at net.minecraft.network.play.client.CPacketCloseWindow.func_148833_a(CPacketCloseWindow.java:25) [lg.class:?]
	at net.minecraft.network.play.client.CPacketCloseWindow.func_148833_a(CPacketCloseWindow.java:10) [lg.class:?]
	at net.minecraft.network.PacketThreadUtil.lambda$checkThreadAndEnqueue$0(PacketThreadUtil.java:16) [hv.class:?]
	at net.minecraft.network.PacketThreadUtil$$Lambda$3216/0000000021174600.run(Unknown Source) [hv.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_252]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_252]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:839) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:466) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:778) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:624) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:821) [?:1.8.0_252]
```

Also when disabling the timings in the paper config its still active. The timings command is still fully functional and you can still get timing reports using "timings merged" so its definitely not disabled.

**Comment by TansuoTro** [comment]
Thanks for the feedback, I will fix this problem

**Comment by TansuoTro** [comment]
And
The links mentioned above are no longer valid, please resubmit the available links.

**Comment by Zilacon** [comment]
You guys need to recommend a different paste site then, this is the site your bot uses on the discord.
