### ISSUE TITLE
OpenTerrainGenerator error.

### ISSUE THREAD

**Issue by notsatvrn** [Teneted/Tenet#371]
**Describe the bug**
OpenTerrainGenerator refuses to work: `> [12:52:33 WARN]: [OTG] The biome Cold Plains tried to inherit mobs from itself.
> [12:52:33 ERROR]: Could not set generator for default world 'Biome Bundle': Plugin 'OpenTerrainGenerator v1.12.2 v9.0_r8
java.lang.IllegalStateException: Can not register to a locked registry. Modder should use Forge Register methods.
at net.minecraftforge.registries.NamespacedWrapper.register(NamespacedWrapper.java:46) ~[NamespacedWrapper.class:1.12.2-6b1591b]
at net.minecraftforge.registries.NamespacedWrapper.register(NamespacedWrapper.java:32) ~[NamespacedWrapper.class:1.12.2-6b1591b]
at com.pg85.otg.bukkit.biomes.OTGBiomeBase.createInstance(OTGBiomeBase.java:100) ~[?:?]
at com.pg85.otg.bukkit.biomes.BukkitBiome.forCustomBiome(BukkitBiome.java:40) ~[?:?]
at com.pg85.otg.bukkit.world.BukkitWorld.createBiomeFor(BukkitWorld.java:512) ~[?:?]
at com.pg85.otg.bukkit.world.BukkitWorld.createBiomeFor(BukkitWorld.java:453) ~[?:?]
at com.pg85.otg.network.ServerConfigProvider.createAndRegisterBiome(ServerConfigProvider.java:768) ~[?:?]
at com.pg85.otg.network.ServerConfigProvider.indexSettings(ServerConfigProvider.java:651) ~[?:?]
at com.pg85.otg.network.ServerConfigProvider.loadBiomes(ServerConfigProvider.java:228) ~[?:?]
at com.pg85.otg.network.ServerConfigProvider.loadSettings(ServerConfigProvider.java:144) ~[?:?]
at com.pg85.otg.network.ServerConfigProvider.<init>(ServerConfigProvider.java:83) ~[?:?]
at com.pg85.otg.bukkit.OTGPlugin.getDefaultWorldGenerator(OTGPlugin.java:151) ~[?:?]
at org.bukkit.craftbukkit.v1_12_R1.CraftServer.getGenerator(CraftServer.java:1274) [CraftServer.class:1.12.2-6b1591b]
at net.minecraft.world.World.<init>(World.java:222) [amu.class:?]
at net.minecraft.world.WorldServer.<init>(WorldServer.java:140) [oo.class:?]
at net.minecraft.server.MinecraftServer.loadAllWorlds(MinecraftServer.java:350) [MinecraftServer.class:?]
at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:316) [nz.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:590) [MinecraftServer.class:?]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]`

**To Reproduce**
Use the latest version of OpenTerrainGenerator as a plugin on the latest Mohist 1.12.2 (6b1591b).

**Expected behavior**
OTG loads and runs normally.

**Info (please complete the following information):**
Plugin: OTG v9.0_r8 (built from source).

**Additional context**
I have already contacted the OTG devs, and they told me to come here. Also I cannot use the mod version because of vanilla client incompatibility.

**Comment by Rabbit0w0** [comment]
We have noticed this error, we will fix this in 1-2 weeks. Sorry for this caused inconveniences to you.

**Comment by notsatvrn** [comment]
Any help?

**Comment by RomualdYT** [comment]
Go for RTG :)
