### ISSUE TITLE
与CrazyAuctionsPlus存在兼容性问题

### ISSUE THREAD

**Issue by Nothingness-Void** [Teneted/Tenet#375]
当在CrazyAuctionsPlus中下架自己商品而左键单击商品时会出现以下报错
[18:46:46] [Server thread/ERROR] [Mohist]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'ca' in plugin CrazyAuctionsPlus v1.1.4.3
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[PluginCommand.class:1.12.2-310ebdb]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:161) ~[SimpleCommandMap.class:1.12.2-310ebdb]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:748) ~[CraftServer.class:1.12.2-310ebdb]
	at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:1578) ~[pa.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:1420) ~[pa.class:?]
	at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(CPacketChatMessage.java:46) ~[la.class:?]
	at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(CPacketChatMessage.java:9) ~[la.class:?]
	at net.minecraft.network.PacketThreadUtil.lambda$checkThreadAndEnqueue$0(PacketThreadUtil.java:16) ~[hv.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_171]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_171]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:839) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:466) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:778) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:624) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_171]
Caused by: java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(Unknown Source) ~[?:1.8.0_171]
	at java.util.ArrayList$Itr.next(Unknown Source) ~[?:1.8.0_171]
	at studio.trc.bukkit.crazyauctionsplus.util.GUI.openShop(GUI.java:90) ~[?:?]
	at studio.trc.bukkit.crazyauctionsplus.command.PluginCommand.onCommand(PluginCommand.java:1237) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:43) ~[PluginCommand.class:1.12.2-310ebdb]
	... 15 more
亲测在别的服务端能够正常使用
求修复，已在插件作者哪边反馈了

**Comment by TansuoTro** [comment]
OK

**Comment by Rabbit0w0** [comment]
已收到！感谢您的反馈，我们将会尽快修复此漏洞，也请附上更详细的漏洞重现方法！

**Comment by Nothingness-Void** [comment]
> 已收到！感谢您的反馈，我们将会尽快修复此漏洞，也请附上更详细的漏洞重现方法！

上架某些模组物品时[抱枕mod-抱枕]会显示上架成功但商店里没有，在个人邮箱取回所购买物品时(全部物品，包括原版)无法取回,尝试取回则会在后台产生上述报错。

**Comment by Rabbit0w0** [comment]
> > 已收到！感谢您的反馈，我们将会尽快修复此漏洞，也请附上更详细的漏洞重现方法！
> 
> 上架某些模组物品时[抱枕mod-抱枕]会显示上架成功但商店里没有，在个人邮箱取回所购买物品时(全部物品，包括原版)无法取回,尝试取回则会在后台产生上述报错。

Actually, English is the only supported language in the project, please use English in the further
We have read CrazyAuctionsPlus's source code,and we will try to fix it.
事实上，英语是此项目唯一支持的语言，请在以后使用英语。
我们已经阅读了CrazyAuctionsPlus的源代码，并且我们会尝试去修复。
