### ISSUE TITLE
Complete failure when used with All the Mods 3 modpack.

### ISSUE THREAD

**Issue by Zilacon** [Teneted/Tenet#4]
WAAAAY too many crashes and errors to report.
Wizardry was one of the major ones which prevented the entire server from starting.
~~Then Quark started causing crashes and errors.~~
Then AutoLibMod needed to be removed cause it was causing massive walls of errors when players connected and did anything. This also caused the removal of Psi, MagicPsi, Morph-O-Tool, Akashic Tome.
Then when a player joins and teleports the server crashes again, and we cant figure out why.

~~Also all of the ConcurrentModificationException crashes i had posted about on the old Mohist are still a problem on this version as well.~~

**Comment by Mgazul** [comment]
Give me all the error reports because only you have so many problems so far

**Comment by braddevans** [comment]
server start bat:
```
@echo off

REM Don't edit these values unless you know what you are doing.
set SERVER_JAR=server.jar

REM You can edit these values if you wish.
set MIN_RAM=61803M
set MAX_RAM=61803M
set JAVA_PARAMETERS=-XX:+UseG1GC -Dsun.rmi.dgc.server.gcInterval=2147483646 -XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M -Dfml.readTimeout=180

echo Starting server1...
java -server -Xms%MIN_RAM% -Xmx%MAX_RAM% %JAVA_PARAMETERS% -jar %SERVER_JAR% nogui
Pause >nul
```

all the mods 3 issue 1: wizadry asm
```
Replaced NEW for net/minecraft/tileentity/TileEntityHopper to pl/asie/foamfix/common/TileEntityFasterHopper
Replaced INVOKESPECIAL for net/minecraft/tileentity/TileEntityHopper to pl/asie/foamfix/common/TileEntityFasterHopper
[wizardry ASM] Successfully patched -> 'func_70071_h_', 'onUpdate' with '()V'
Added INTERFACE: pl/asie/foamfix/api/IFoamFixMobSpawnerLogic
Spliced in METHOD: net.minecraft.tileentity.MobSpawnerBaseLogic.func_98279_f
Added FIELD: net.minecraft.tileentity.MobSpawnerBaseLogic.foamfix_activatedCache
Added FIELD: net.minecraft.tileentity.MobSpawnerBaseLogic.foamfix_activatedCachePESize
Added FIELD: net.minecraft.tileentity.MobSpawnerBaseLogic.foamfix_activatedCacheTime
Added FIELD: net.minecraft.tileentity.MobSpawnerBaseLogic.foamfix_forcedCache
Added FIELD: net.minecraft.tileentity.MobSpawnerBaseLogic.foamfix_forcedCacheTime
A problem occurred running the Server launcher.
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at red.mohist.Mohist.main(Mohist.java:99)
Caused by: net.minecraftforge.fml.relauncher.FMLSecurityManager$ExitTrappedException
        at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:49)
        at java.lang.SecurityManager.checkExit(Unknown Source)
        at java.lang.Runtime.exit(Unknown Source)
        at java.lang.System.exit(Unknown Source)
        at net.minecraft.launchwrapper.Launch.launch(Launch.java:138)
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
        ... 5 more
```

allthe mods 3| the between lands mod:
```
[22:30:08 INFO]: Successfully registered 1 Biomes for class net.minecraft.world.biome.Biome from aroma1997sdimension.
[22:31:37 INFO]: Initializing Village Addons...
[22:31:38 WARN]: java.lang.NoSuchMethodException: thebetweenlands.common.registries.RecipeRegistry.registerOreDictionary()
[22:31:38 WARN]:        at java.lang.Class.getDeclaredMethod(Unknown Source)
[22:31:38 WARN]:        at thelm.oredictinit.compat.CompatTheBetweenlands.register(CompatTheBetweenlands.java:18)
[22:31:38 WARN]:        at thelm.oredictinit.registry.OreDictRegisCore.initCompat(OreDictRegisCore.java:18)
[22:31:38 WARN]:        at thelm.oredictinit.lib.EventHandler.onRegistryWrapUp(EventHandler.java:24)
[22:31:38 WARN]:        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1761_EventHandler_onRegistryWrapUp_Event0.invoke(.dynamic)
[22:31:38 WARN]:        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
[22:31:38 WARN]:        at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:146)
[22:31:38 WARN]:        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:186)
[22:31:38 WARN]:        at thelm.wrapup.WrapUp.onVillagerProfessionRegisterLowest(WrapUp.java:97)
[22:31:38 WARN]:        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_911_WrapUp_onVillagerProfessionRegisterLowest_Register.invoke(.dynamic)
[22:31:38 WARN]:        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
[22:31:38 WARN]:        at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:146)
[22:31:38 WARN]:        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:186)
[22:31:38 WARN]:        at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:863)
[22:31:38 WARN]:        at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:627)
[22:31:38 WARN]:        at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:103)
[22:31:38 WARN]:        at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:329)
[22:31:38 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:167)
[22:31:38 WARN]:        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:608)
[22:31:38 WARN]:        at java.lang.Thread.run(Unknown Source)
[22:31:38 WARN]: java.lang.NoSuchMethodException: slimeknights.tconstruct.common.TinkerOredict.doTheOredict(net.minecraftforge.fml.common.event.FMLInitializationEvent)
[22:31:38 WARN]:        at java.lang.Class.getDeclaredMethod(Unknown Source)
[22:31:38 WARN]:        at thelm.oredictinit.compat.CompatTinkersConstruct.register(CompatTinkersConstruct.java:19)
[22:31:38 WARN]:        at thelm.oredictinit.registry.OreDictRegisCore.initCompat(OreDictRegisCore.java:18)
[22:31:38 WARN]:        at thelm.oredictinit.lib.EventHandler.onRegistryWrapUp(EventHandler.java:24)
[22:31:38 WARN]:        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1761_EventHandler_onRegistryWrapUp_Event0.invoke(.dynamic)
[22:31:38 WARN]:        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
[22:31:38 WARN]:        at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:146)
[22:31:38 WARN]:        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:186)
[22:31:38 WARN]:        at thelm.wrapup.WrapUp.onVillagerProfessionRegisterLowest(WrapUp.java:97)
[22:31:38 WARN]:        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_911_WrapUp_onVillagerProfessionRegisterLowest_Register.invoke(.dynamic)
[22:31:38 WARN]:        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
[22:31:38 WARN]:        at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:146)
[22:31:38 WARN]:        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:186)
[22:31:38 WARN]:        at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:863)
[22:31:38 WARN]:        at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:627)
[22:31:38 WARN]:        at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:103)
[22:31:38 WARN]:        at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:329)
[22:31:38 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:167)
[22:31:38 WARN]:        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:608)
[22:31:38 WARN]:        at java.lang.Thread.run(Unknown Source)
```

all the mods 3 advanced rocketary world gen:
```
Time: 9/8/19 10:46 PM
Description: Exception in server tick loop

java.lang.NullPointerException: Exception in server tick loop
	at zmaster587.advancedRocketry.dimension.DimensionManager.getTemperature(DimensionManager.java:227)
	at zmaster587.advancedRocketry.dimension.DimensionProperties.getAverageTemp(DimensionProperties.java:1488)
	at zmaster587.advancedRocketry.dimension.DimensionProperties.getOreGenProperties(DimensionProperties.java:297)
	at zmaster587.advancedRocketry.event.PlanetEventHandler.onWorldGen(PlanetEventHandler.java:155)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_2731_PlanetEventHandler_onWorldGen_GenerateMinable.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:186)
	at zmaster587.advancedRocketry.world.ore.OreGenerator.generate(OreGenerator.java:48)
	at net.minecraftforge.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:167)
	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1194)
	at net.minecraft.world.chunk.Chunk.populateCB(Chunk.java:1153)
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:169)
	at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:396)
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:358)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:322)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:608)
```
[crash-2019-09-08_22.46.35-server.txt](https://github.com/Mohist-Community/Mohist/files/3588106/crash-2019-09-08_22.46.35-server.txt)
[latest.log](https://github.com/Mohist-Community/Mohist/files/3588107/latest.log)
[wizardry.log](https://github.com/Mohist-Community/Mohist/files/3588087/wizardry.log)

**Comment by Mgazul** [comment]
I saw BetterFps in wizardd.log and it is not recommended.
The other two are too many mods, I can't judge the specific cause of the error.

**Comment by Zilacon** [comment]
Lol did you fix this? Why is it closed?

**Comment by Mgazul** [comment]
Since you have not responded for a long time, I have not given me a more detailed report.

**Comment by Zilacon** [comment]
How is the above not a detailed report? You were given several stack traces, the modpack, and specific mods on what is erroring...

**Comment by Mgazul** [comment]
That is not yours, do you have two accounts? If yes, please use the latest build run and send the report again

**Comment by Zilacon** [comment]
Braddevans is one my networks developers.

**Comment by Mgazul** [comment]
please use the latest build run and send the report again， thx

**Comment by Zilacon** [comment]
The server does not get past this point with latest build:
```


 /'\_/`\          /\ \       __          /\ \__   
/\      \     ___ \ \ \___  /\_\     ____\ \ ,_\  
\ \ \__\ \   / __`\\ \  _ `\\/\ \   /',__\\ \ \/  
 \ \ \_/\ \ /\ \L\ \\ \ \ \ \\ \ \ /\__, `\\ \ \_ 
  \ \_\\ \_\\ \____/ \ \_\ \_\\ \_\\/\____/ \ \__\
   \/_/ \/_/ \/___/   \/_/\/_/ \/_/ \/___/   \/__/


                        -- Mohist Development Group

Mohist Starting...
Loading libraries, please wait...
Transforming Class [net.minecraft.block.Block], Method [getExtendedState]
Transforming net.minecraft.block.Block Finished.
[wizardry ASM] Successfully patched -> 'func_70091_d', 'move' with '(Lnet/minecraft/entity/MoverType;DDD)V'
[wizardry ASM] Successfully patched -> 'func_191986_a', 'travel' with '(FFF)V'
[wizardry ASM] Successfully patched -> 'func_70071_h_', 'onUpdate' with '()V'
[wizardry ASM] Successfully patched -> 'func_70071_h_', 'onUpdate' with '()V'
A problem occurred running the Server launcher.
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at red.mohist.Mohist.main(Mohist.java:110)
Caused by: net.minecraftforge.fml.relauncher.FMLSecurityManager$ExitTrappedException
	at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:49)
	at java.lang.SecurityManager.checkExit(SecurityManager.java:761)
	at java.lang.Runtime.exit(Runtime.java:107)
	at java.lang.System.exit(System.java:344)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:138)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	... 5 more
APOC Server has shutdown! Restarting in 30 seconds...
```
@Mgazul

**Comment by Mgazul** [comment]
Send log file

**Comment by Zilacon** [comment]
That IS the log file...

**Comment by Mgazul** [comment]
logs/latest.log

**Comment by Zilacon** [comment]
[latest.log](https://github.com/Mohist-Community/Mohist/files/3713454/latest.log)

**Comment by Zilacon** [comment]
Any update on this?

**Comment by FabioZumbi12** [comment]
~~In this log, theres some errors with `1.12.2-randompatches-1.17.2.1.jar`, try the latest randompacthes version 1.19.1.1 (or try to remove).~~

And the other error... `[LaunchWrapper]: A critical problem occurred registering the ASM transformer class 
java.lang.ClassNotFoundException: 
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) `

This seems to be the same error as on KCauldron, using an outdated ASM version... not shure about this. This is the related problem: https://github.com/DiscordSRV/DiscordSRV/wiki/FAQ#fix-for-thermos-cauldron-and-early-kcauldron

**Comment by Mgazul** [comment]
The problem with randompatches I have fixed, now the main problem is: Wizardry mod

**Comment by Zilacon** [comment]
# Waiting Intensifies...
