### ISSUE TITLE
BlockState cannot be cast to org.bukkit.block.Block

### ISSUE THREAD

**Issue by SniperGER** [Teneted/Tenet#415]
**Describe the bug**
When launching a fresh install of Mohist 1.15.2, an error occurs after the worlds have been generated.

```
Description: Exception while ticking

java.lang.ClassCastException: net.minecraft.block.BlockState cannot be cast to org.bukkit.block.Block
	at net.minecraft.block.FallingBlock.func_225534_a_(FallingBlock.java:37) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.block.BlockState.func_227033_a_(BlockState.java:249) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.world.server.ServerWorld.func_205338_b(ServerWorld.java:637) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.world.server.ServerTickList.func_205365_a(ServerTickList.java:92) ~[?:?] {re:classloading}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:356) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1083) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:988) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:821) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_231] {}
```

**To Reproduce**
1. Install Mohist
2. Launch Mohist (`java -jar forge-1.15.2-31.2.0.jar`)
3. Wait for worlds to be generated
4. Error occurs

**Expected behavior**
Mohist should not crash when starting a server.

**Screenshots**

**Info (please complete the following information):**
- No mods or plugins, just a fresh install
- EULA accepted
- Launching works absolutely fine when generating a flat world

**Additional context**
Pastebin Log: https://pastebin.com/FY0W4AU8

**Comment by Rabbit0w0** [comment]
Use the latest build.This problem has fixed.

**Comment by SniperGER** [comment]
@Rabbit0w0 I'm using build 103 of Mohist-1.15.2, which is currently the latest available build.

**Comment by wdog5** [comment]
I will try to fix the bug
