### ISSUE TITLE
NullPointerException: Ticking entity

### ISSUE THREAD

**Issue by SniperGER** [Teneted/Tenet#422]
**Describe the bug**
When connecting to a fresh install of **Mohist 1.15.2**, an error occurs, resulting in disconnecting the player and shutting down the server.

```
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at net.minecraft.entity.ai.goal.GoalSelector.cleanupControls(GoalSelector.java:89) ~[?:?] {re:classloading}
	at net.minecraft.entity.ai.goal.GoalSelector.updateGoalStates(GoalSelector.java:66) ~[?:?] {re:classloading}
	at net.minecraft.entity.ai.goal.GoalSelector.func_75774_a(GoalSelector.java:55) ~[?:?] {re:classloading}
	at net.minecraft.entity.MobEntity.func_70626_be(MobEntity.java:645) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.entity.LivingEntity.func_70636_d(LivingEntity.java:2590) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.entity.MobEntity.func_70636_d(MobEntity.java:508) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.entity.monster.MonsterEntity.func_70636_d(SourceFile:39) ~[?:?] {re:classloading}
	at net.minecraft.entity.monster.GuardianEntity.func_70636_d(SourceFile:301) ~[?:?] {re:classloading}
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2429) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.entity.MobEntity.func_70071_h_(MobEntity.java:304) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:663) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.world.World.func_217390_a(World.java:782) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:456) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1083) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:988) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:821) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_231] {}
```

**To Reproduce**
1. Launch Mohist (`java -jar forge-1.15.2-31.2.0.jar`)
2. Connect to the server
3. Error occurs

**Expected behavior**
Mohist should not crash when connecting to the server.

**Screenshots**

**Info (please complete the following information):**
- No mods or plugins, just a fresh install
- EULA accepted
- Allocated RAM doesn't matter, crash occurs with default values, 1GB or 2GB allocated
- Error occurs with Builds 106 and 107 of **Mohist 1.15.2**

**Additional context**
Pastebin Log: https://pastebin.com/7PYwcywe

**Comment by SniperGER** [comment]
Issue has been resolved in a build from 108 to 131. Can't say for sure, but it's working now.
