### ISSUE TITLE
Piston with block in front of it isntant crash the server

### ISSUE THREAD

**Issue by uiytt** [Teneted/Tenet#434]
**Describe the bug**
When a block is placed in front of a piston, and the piston is then activated, the server crash with : 
```
java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
	at java.util.ArrayList.rangeCheck(ArrayList.java:657) ~[?:1.8.0_252]
	at java.util.ArrayList.get(ArrayList.java:433) ~[?:1.8.0_252]
	at net.minecraft.block.BlockPistonBase.func_176319_a(BlockPistonBase.java:446) ~[awj.class:?]
	at net.minecraft.block.BlockPistonBase.func_189539_a(BlockPistonBase.java:215) ~[awj.class:?]
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_189547_a(BlockStateContainer.java:476) ~[awu$a.class:?]
	at net.minecraft.world.WorldServer.func_147485_a(WorldServer.java:1530) ~[oo.class:?]
	at net.minecraft.world.WorldServer.func_147488_Z(WorldServer.java:1516) ~[oo.class:?]
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:470) ~[oo.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:885) ~[MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:466) ~[nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:778) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:624) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
```

**To Reproduce**
1. Install latest version of mohist from Jenkins
2. Place a piston
3. Place a block in front of it
4. Activate it with a lever or anything else

**Expected behavior**
No crash

**Info (please complete the following information):**
- Mod/Plugins Name: No Plugins / No Mods 
- Mohist version : 1.12.2-a139e30
- Forge version : 14.23.5.2854

**Additional context**
Crash report : https://hastebin.com/kedihateto.sql
Java version : 
openjdk version "1.8.0_252"
OpenJDK Runtime Environment (build 1.8.0_252-8u252-b09-1ubuntu1-b09)
OpenJDK 64-Bit Server VM (build 25.252-b09, mixed mode)

**Comment by Shawiizz** [comment]
Same as issue #386. Please check that your issue isn't already opened before open one for the next time.

**Comment by uiytt** [comment]
My bad
