### ISSUE TITLE
What is this issue?

### ISSUE THREAD

**Issue by noy98** [Teneted/Tenet#444]
**Describe the bug**

**To Reproduce**

**Expected behavior**

[22:09:22 WARN]: java.lang.NoSuchFieldException: networkManager
[22:09:22 WARN]:        at java.lang.Class.getField(Unknown Source)
[22:09:22 WARN]:        at red.mohist.bukkit.nms.proxy.ProxyClass.getField(ProxyClass.java:55)
[22:09:22 WARN]:        at com.gmail.thelimeglass.Utils.ReflectionUtil.getChannel(ReflectionUtil.java:41)
[22:09:22 WARN]:        at com.gmail.thelimeglass.Utils.Packets.PacketListener.remove(PacketListener.java:35)
[22:09:22 WARN]:        at com.gmail.thelimeglass.Utils.Packets.PacketListener.onQuit(PacketListener.java:29)
[22:09:22 WARN]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor67.execute(Unknown Source)
[22:09:22 WARN]:        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:61)
[22:09:22 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77)
[22:09:22 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66)
[22:09:22 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484)
[22:09:22 WARN]:        at net.minecraft.server.management.PlayerList.func_72367_e(PlayerList.java:538)
[22:09:22 WARN]:        at net.minecraft.server.management.PlayerList.disconnect(PlayerList.java:523)
[22:09:22 WARN]:        at net.minecraft.network.NetHandlerPlayServer.func_147231_a(NetHandlerPlayServer.java:1283)
[22:09:22 WARN]:        at net.minecraft.network.NetworkManager.func_179293_l(NetworkManager.java:473)
[22:09:22 WARN]:        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:232)
[22:09:22 WARN]:        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:923)
[22:09:22 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:466)
[22:09:22 WARN]:        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:778)
[22:09:22 WARN]:        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:624)
[22:09:22 WARN]:        at java.lang.Thread.run(Unknown Source)

**Screenshots**

**Info (please complete the following information):**
- Mod/Plugins Name: 
 - Mod/Plugins  Version: 

**Additional context**

When players join the server, this issue occurs.
It also occurs when players quit.

**Comment by MCUmbrella** [comment]
Please complete the issue template and upload the full log
