### ISSUE TITLE
Exception in server tick loop: 1.12.2 Mohist 

### ISSUE THREAD

**Issue by NovaPixell** [Teneted/Tenet#449]
Server Crash with the "Mohist-1.12.2-dde44c8-server.jar", latest release.

Time: 19/07/20 17.44
Description: Exception in server tick loop

java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1445)
	at java.util.HashMap$KeyIterator.next(HashMap.java:1469)
	at net.minecraft.entity.EntityTracker.func_72788_a(EntityTracker.java:293)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:911)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:466)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:778)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by Rabbit0w0** [comment]
how to reproduce it

**Comment by NovaPixell** [comment]
I don't know
