### ISSUE TITLE
FAWE doesn't work

### ISSUE THREAD

**Issue by ErriourMe** [Teneted/Tenet#5]
```
[05:38:59 WARN]: java.lang.NoSuchMethodError: net.minecraft.world.gen.ChunkProviderServer.getChunkAt(IILjava/lang/Runnable;Z)Lnet/minecraft/world/chunk/Chunk;
[05:38:59 WARN]:        at com.boydti.fawe.bukkit.v1_12.BukkitQueue_1_12.loadChunk(BukkitQueue_1_12.java:182)
[05:38:59 WARN]:        at com.boydti.fawe.bukkit.v1_12.BukkitQueue_1_12.loadChunk(BukkitQueue_1_12.java:51)
[05:38:59 WARN]:        at com.boydti.fawe.example.MappedFaweQueue$1.run(MappedFaweQueue.java:64)
[05:38:59 WARN]:        at com.boydti.fawe.example.MappedFaweQueue$1.run(MappedFaweQueue.java:56)
[05:38:59 WARN]:        at com.boydti.fawe.object.RunnableVal.run(RunnableVal.java:18)
[05:38:59 WARN]:        at com.boydti.fawe.util.TaskManager$3.run(TaskManager.java:348)
[05:38:59 WARN]:        at com.boydti.fawe.util.TaskManager$3.run(TaskManager.java:344)
[05:38:59 WARN]:        at com.boydti.fawe.object.RunnableVal.run(RunnableVal.java:18)
[05:38:59 WARN]:        at com.boydti.fawe.util.SetQueue$1.run(SetQueue.java:124)
[05:38:59 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:73)
[05:38:59 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:424)
[05:38:59 WARN]:        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:858)
[05:38:59 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:467)
[05:38:59 WARN]:        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:805)
[05:38:59 WARN]:        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:657)
[05:38:59 WARN]:        at java.lang.Thread.run(Thread.java:748)
```

```
[05:42:08 ERROR]: Could not pass event PlayerMoveEvent to FastAsyncWorldEdit v19.07.25-58243b6-1278-22.3.1
 org.bukkit.event.EventException: null
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:63) ~[EventExecutor.class:0b877cb]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66) ~[RegisteredListener.class:0b877cb]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:491) [SimplePluginManager.class:0b877cb]
        at net.minecraft.network.NetHandlerPlayServer.func_147347_a(NetHandlerPlayServer.java:832) [pa.class:?]
        at net.minecraft.network.play.client.CPacketPlayer.func_148833_a(CPacketPlayer.java:33) [lk.class:?]
        at net.minecraft.network.play.client.CPacketPlayer$Position.func_148833_a(CPacketPlayer.java:76) [lk$a.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_212]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_212]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:865) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:467) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:805) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:657) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: java.lang.ArrayIndexOutOfBoundsException: 69855
        at com.boydti.fawe.FaweCache.getBlock(FaweCache.java:91) ~[?:?]
        at com.sk89q.worldedit.bukkit.BukkitPlayer.getBlockInHand(BukkitPlayer.java:97) ~[?:?]
        at com.boydti.fawe.wrappers.PlayerWrapper.getBlockInHand(PlayerWrapper.java:68) ~[?:?]
        at com.sk89q.worldedit.LocalSession.getTool(LocalSession.java:1009) ~[?:?]
        at com.boydti.fawe.bukkit.listener.BrushListener.onPlayerMove(BrushListener.java:73) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor13.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:61) ~[EventExecutor.class:0b877cb]
        ... 14 more
```

Last build of core.

**Comment by Mgazul** [comment]
I installed FAWE and used it without your problem. How did you trigger the problem?

**Comment by ErriourMe** [comment]
The first when executing the command //set on undeleted blocks from schematic.
The second after inserting the schematic and canceling the action, and after that when flying through undeleted blocks.
