### ISSUE TITLE
Server Crash while loading a chunk.

### ISSUE THREAD

**Issue by NovaPixell** [Teneted/Tenet#511]
Here is the Crash Report:

https://paste.ubuntu.com/p/5p5wj9C8XX/

**Comment by NovaPixell** [comment]
More info:

[22:56:44] [Server thread/INFO] [net.minecraft.network.NetHandlerPlayServer]: NovaPixellissued server command:/tp -507845 89 347560
[22:56:48] [Server thread/ERROR] [Mohist]: TIMING_STACK_CORRUPTION - Report this to the plugin Minecraft(Look for errors above this in the logs) (TimingIdentifier{id=Minecraft:world - chunkLoad - Populate Neighbors} did not stopTiming)
java.lang.Throwable: null
	at co.aikar.timings.TimingHandler.stopTiming(TimingHandler.java:113) [TimingHandler.class:1.12.2-a20ff1b]
	at co.aikar.timings.TimingHandler.stopTimingIfSync(TimingHandler.java:91) [TimingHandler.class:1.12.2-a20ff1b]
	at co.aikar.timings.TimingHandler.close(TimingHandler.java:178) [TimingHandler.class:1.12.2-a20ff1b]
	at net.minecraft.server.management.PlayerChunkMap.func_72693_b(PlayerChunkMap.java:206) [ou.class:?]
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:453) [oo.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:885) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:466) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:778) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:624) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
[22:56:48] [Server thread/ERROR] [Mohist]: TIMING_STACK_CORRUPTION - Report this to the plugin Minecraft(Look for errors above this in the logs) (TimingIdentifier{id=Minecraft:world - syncChunkLoad} did not stopTiming)
java.lang.Throwable: null
	at co.aikar.timings.TimingHandler.stopTiming(TimingHandler.java:113) [TimingHandler.class:1.12.2-a20ff1b]
	at co.aikar.timings.TimingHandler.stopTimingIfSync(TimingHandler.java:91) [TimingHandler.class:1.12.2-a20ff1b]
	at co.aikar.timings.TimingHandler.close(TimingHandler.java:178) [TimingHandler.class:1.12.2-a20ff1b]
	at net.minecraft.server.management.PlayerChunkMap.func_72693_b(PlayerChunkMap.java:206) [ou.class:?]
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:453) [oo.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:885) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:466) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:778) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:624) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
[22:56:48] [Server thread/ERROR] [net.minecraft.server.MinecraftServer]: Encountered an unexpected exception
java.lang.NoClassDefFoundError: net/minecraft/world/World$3
	at net.minecraft.world.World.func_190524_a(World.java:732) ~[amu.class:?]
	at net.minecraft.world.World.func_175685_c(World.java:661) ~[amu.class:?]
	at net.minecraft.world.World.func_175722_b(World.java:607) ~[amu.class:?]
	at net.minecraft.world.World.markAndNotifyBlock(World.java:543) ~[amu.class:?]
	at net.minecraft.world.World.func_180501_a(World.java:523) ~[amu.class:?]
	at net.minecraft.block.BlockDynamicLiquid.func_176375_a(BlockDynamicLiquid.java:191) ~[aqe.class:?]
	at net.minecraft.block.BlockDynamicLiquid.func_180650_b(BlockDynamicLiquid.java:168) ~[aqe.class:?]
	at net.minecraft.world.World.func_189507_a(World.java:3100) ~[amu.class:?]
	at net.minecraft.world.gen.feature.WorldGenLiquids.func_180709_b(WorldGenLiquids.java:88) ~[bat.class:?]
	at net.minecraft.world.biome.BiomeDecorator.func_150513_a(BiomeDecorator.java:352) ~[ank.class:?]
	at net.minecraft.world.biome.BiomeDecorator.func_180292_a(BiomeDecorator.java:88) ~[ank.class:?]
	at net.minecraft.world.biome.Biome.func_180624_a(Biome.java:226) ~[anh.class:?]
	at net.minecraft.world.biome.BiomeForest.func_180624_a(BiomeForest.java:110) ~[anr.class:?]
	at net.minecraft.world.gen.ChunkGeneratorOverworld.func_185931_b(ChunkGeneratorOverworld.java:470) ~[aze.class:?]
	at org.bukkit.craftbukkit.v1_12_R1.generator.NormalChunkGenerator.func_185931_b(NormalChunkGenerator.java:44) ~[NormalChunkGenerator.class:1.12.2-a20ff1b]
	at co.aikar.timings.TimedChunkGenerator.func_185931_b(TimedChunkGenerator.java:99) ~[TimedChunkGenerator.class:1.12.2-a20ff1b]
	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1162) ~[axw.class:?]
	at net.minecraft.world.chunk.Chunk.populateCB(Chunk.java:1132) ~[axw.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.originalGetChunkAt(ChunkProviderServer.java:182) ~[on.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:154) ~[on.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:150) ~[on.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:146) ~[on.class:?]
	at net.minecraft.server.management.PlayerChunkMapEntry.func_187268_a(PlayerChunkMapEntry.java:126) ~[ot.class:?]
	at net.minecraft.server.management.PlayerChunkMap.func_72693_b(PlayerChunkMap.java:185) ~[ou.class:?]
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:453) ~[oo.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:885) ~[MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:466) ~[nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:778) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:624) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]

**Comment by Rabbit0w0** [comment]
looks not good, fix soon
