### ISSUE TITLE
GadgetsMenu

### ISSUE THREAD

**Issue by yuankun1** [Teneted/Tenet#543]
[21:19:32 WARN]: java.lang.NullPointerException
[21:19:32 WARN]:        at me.libraryaddict.disguise.disguisetypes.Disguise.createDisguise(Disguise.java:242)
[21:19:32 WARN]:        at me.libraryaddict.disguise.disguisetypes.MobDisguise.<init>(MobDisguise.java:29)
[21:19:32 WARN]:        at me.libraryaddict.disguise.disguisetypes.MobDisguise.<init>(MobDisguise.java:14)
[21:19:32 WARN]:        at com.yapzhenyie.GadgetsMenu.utils.cosmetics.morphs.LibDisguise.disguise(LibDisguise.java:40)
[21:19:32 WARN]:        at com.yapzhenyie.GadgetsMenu.cosmetics.morphs.MorphManager.equipMorph(MorphManager.java:53)
[21:19:32 WARN]:        at com.yapzhenyie.GadgetsMenu.player.PlayerManager.equipMorph(PlayerManager.java:582)
[21:19:32 WARN]:        at com.yapzhenyie.GadgetsMenu.menu.menus.MorphsMenu.onInvClickMorphs(MorphsMenu.java:234)
[21:19:32 WARN]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor173.execute(Unknown Source)
[21:19:32 WARN]:        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:61)
[21:19:32 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77)
[21:19:32 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66)
[21:19:32 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484)
[21:19:32 WARN]:        at net.minecraft.network.NetHandlerPlayServer.func_147351_a(NetHandlerPlayServer.java:2120)
[21:19:32 WARN]:        at net.minecraft.network.play.client.CPacketClickWindow.func_148833_a(CPacketClickWindow.java:38)
[21:19:32 WARN]:        at net.minecraft.network.play.client.CPacketClickWindow.func_148833_a(CPacketClickWindow.java:12)
[21:19:32 WARN]:        at net.minecraft.network.PacketThreadUtil.lambda$checkThreadAndEnqueue$0(PacketThreadUtil.java:16)
[21:19:32 WARN]:        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[21:19:32 WARN]:        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[21:19:32 WARN]:        at net.minecraft.util.Util.func_181617_a(SourceFile:46)
[21:19:32 WARN]:        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:843)
[21:19:32 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:471)
[21:19:32 WARN]:        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:781)
[21:19:32 WARN]:        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:627)
[21:19:32 WARN]:        at java.lang.Thread.run(Thread.java:748)
[21:19:32 WARN]: java.lang.NullPointerException
[21:19:32 WARN]:        at com.yapzhenyie.GadgetsMenu.utils.cosmetics.morphs.LibDisguise.disguise(LibDisguise.java:46)
[21:19:32 WARN]:        at com.yapzhenyie.GadgetsMenu.cosmetics.morphs.MorphManager.equipMorph(MorphManager.java:53)
[21:19:32 WARN]:        at com.yapzhenyie.GadgetsMenu.player.PlayerManager.equipMorph(PlayerManager.java:582)
[21:19:32 WARN]:        at com.yapzhenyie.GadgetsMenu.menu.menus.MorphsMenu.onInvClickMorphs(MorphsMenu.java:234)
[21:19:32 WARN]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor173.execute(Unknown Source)
[21:19:32 WARN]:        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:61)
[21:19:32 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77)
[21:19:32 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66)
[21:19:32 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484)
[21:19:32 WARN]:        at net.minecraft.network.NetHandlerPlayServer.func_147351_a(NetHandlerPlayServer.java:2120)
[21:19:32 WARN]:        at net.minecraft.network.play.client.CPacketClickWindow.func_148833_a(CPacketClickWindow.java:38)
[21:19:32 WARN]:        at net.minecraft.network.play.client.CPacketClickWindow.func_148833_a(CPacketClickWindow.java:12)
[21:19:32 WARN]:        at net.minecraft.network.PacketThreadUtil.lambda$checkThreadAndEnqueue$0(PacketThreadUtil.java:16)
[21:19:32 WARN]:        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[21:19:32 WARN]:        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[21:19:32 WARN]:        at net.minecraft.util.Util.func_181617_a(SourceFile:46)
[21:19:32 WARN]:        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:843)
[21:19:32 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:471)
[21:19:32 WARN]:        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:781)
[21:19:32 WARN]:        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:627)
[21:19:32 WARN]:        at java.lang.Thread.run(Thread.java:748)

**Comment by Mgazul** [comment]
Not detailed enough
