### ISSUE TITLE
[1.12.2] issues

### ISSUE THREAD

**Issue by 4Seasons11** [Teneted/Tenet#547]
**Describe the bug**
When player join, it causes errors and even when player quit, it causes errors, too.

**To Reproduce**

**Expected behavior**

**Screenshots**

join Event
`[18:04:44 WARN]: java.lang.NoSuchFieldException: networkManager
[18:04:44 WARN]:        at java.lang.Class.getField(Unknown Source)
[18:04:44 WARN]:        at red.mohist.bukkit.nms.proxy.ProxyClass.getField(ProxyClass.java:52)
[18:04:44 WARN]:        at com.gmail.thelimeglass.Utils.ReflectionUtil.getChannel(ReflectionUtil.java:41)
[18:04:44 WARN]:        at com.gmail.thelimeglass.Utils.Packets.PacketListener.create(PacketListener.java:68)
[18:04:44 WARN]:        at com.gmail.thelimeglass.Utils.Packets.PacketListener.onJoin(PacketListener.java:22)
[18:04:44 WARN]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor89.execute(Unknown Source)
[18:04:44 WARN]:        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:61)
[18:04:44 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77)
[18:04:44 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66)
[18:04:44 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484)
[18:04:44 WARN]:        at net.minecraft.server.management.PlayerList.playerLoggedIn(PlayerList.java:471)
[18:04:44 WARN]:        at net.minecraft.server.management.PlayerList.initializeConnectionToPlayer(PlayerList.java:245)
[18:04:44 WARN]:        at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.completeServerSideConnection(NetworkDispatcher.java:259)
[18:04:44 WARN]:        at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.access$100(NetworkDispatcher.java:70)
[18:04:44 WARN]:        at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:204)
[18:04:44 WARN]:        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:298)
[18:04:44 WARN]:        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:196)
[18:04:44 WARN]:        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:927)
[18:04:44 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:471)
[18:04:44 WARN]:        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:781)
[18:04:44 WARN]:        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:627)
[18:04:44 WARN]:        at java.lang.Thread.run(Unknown Source)`

Quit Event
`[18:04:50 WARN]: java.lang.NoSuchFieldException: networkManager
[18:04:50 WARN]:        at java.lang.Class.getField(Unknown Source)
[18:04:50 WARN]:        at red.mohist.bukkit.nms.proxy.ProxyClass.getField(ProxyClass.java:52)
[18:04:50 WARN]:        at com.gmail.thelimeglass.Utils.ReflectionUtil.getChannel(ReflectionUtil.java:41)
[18:04:50 WARN]:        at com.gmail.thelimeglass.Utils.Packets.PacketListener.remove(PacketListener.java:35)
[18:04:50 WARN]:        at com.gmail.thelimeglass.Utils.Packets.PacketListener.onQuit(PacketListener.java:29)
[18:04:50 WARN]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor90.execute(Unknown Source)
[18:04:50 WARN]:        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:61)
[18:04:50 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77)
[18:04:50 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66)
[18:04:50 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484)
[18:04:50 WARN]:        at net.minecraft.server.management.PlayerList.func_72367_e(PlayerList.java:538)
[18:04:50 WARN]:        at net.minecraft.server.management.PlayerList.disconnect(PlayerList.java:523)
[18:04:50 WARN]:        at net.minecraft.network.NetHandlerPlayServer.func_147231_a(NetHandlerPlayServer.java:1286)
[18:04:50 WARN]:        at net.minecraft.network.NetworkManager.func_179293_l(NetworkManager.java:473)
[18:04:50 WARN]:        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:232)
[18:04:50 WARN]:        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:927)
[18:04:50 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:471)
[18:04:50 WARN]:        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:781)
[18:04:50 WARN]:        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:627)
[18:04:50 WARN]:        at java.lang.Thread.run(Unknown Source)`

**Info (please complete the following information):**
- Mod/Plugins Name: Skellett 1.9.6b
 - Mod/Plugins  Version: 

**Additional context**

**Comment by Shawiizz** [comment]
Hi, please try again with latest build and tell if your error happens with latest or no.

**Comment by Shawiizz** [comment]
Closing due to no response.
if the problem persists, please open a new issue.
