### ISSUE TITLE
mySQL driver erroring for plugin connections.

### ISSUE THREAD

**Issue by Zilacon** [Teneted/Tenet#569]
When using a plugin that uses mysql and timezones it errors trying to make a connection:

```
[15:01:04 WARN]: [APOC-PayDay] Failed to create the database connection:
[15:01:04 WARN]: java.sql.SQLException: The server time zone value 'PDT' is unrecognized or represents more than one time zone. You must configure either the server or JDBC driver (via the 'serverTimezone' configuration property) to use a more specifc time zone value if you want to utilize time zone support.
[15:01:04 WARN]: 	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129)
[15:01:04 WARN]: 	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
[15:01:04 WARN]: 	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89)
[15:01:04 WARN]: 	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63)
[15:01:04 WARN]: 	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:73)
[15:01:04 WARN]: 	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:76)
[15:01:04 WARN]: 	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:836)
[15:01:04 WARN]: 	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:456)
[15:01:04 WARN]: 	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:246)
[15:01:04 WARN]: 	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:197)
[15:01:04 WARN]: 	at java.sql.DriverManager.getConnection(DriverManager.java:664)
[15:01:04 WARN]: 	at java.sql.DriverManager.getConnection(DriverManager.java:247)
[15:01:04 WARN]: 	at org.apocgaming.payday.database.Database.connect(Database.java:24)
[15:01:04 WARN]: 	at org.apocgaming.payday.database.Database.getConnection(Database.java:37)
[15:01:04 WARN]: 	at org.apocgaming.payday.dao.ServersDao.addServer(ServersDao.java:12)
[15:01:04 WARN]: 	at org.apocgaming.payday.dao.RewardsDao.checkServerRecord(RewardsDao.java:296)
[15:01:04 WARN]: 	at org.apocgaming.payday.services.RewardService.checkServerList(RewardService.java:560)
[15:01:04 WARN]: 	at org.apocgaming.payday.PayDay.onEnable(PayDay.java:63)
[15:01:04 WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:177)
[15:01:04 WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:318)
[15:01:04 WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:399)
[15:01:04 WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:477)
[15:01:04 WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:418)
[15:01:04 WARN]: 	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:386)
[15:01:04 WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:319)
[15:01:04 WARN]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:593)
[15:01:04 WARN]: 	at java.lang.Thread.run(Thread.java:823)
[15:01:04 WARN]: Caused by: 
[15:01:04 WARN]: com.mysql.cj.exceptions.InvalidConnectionAttributeException: The server time zone value 'PDT' is unrecognized or represents more than one time zone. You must configure either the server or JDBC driver (via the 'serverTimezone' configuration property) to use a more specifc time zone value if you want to utilize time zone support.
[15:01:04 WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[15:01:04 WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[15:01:04 WARN]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[15:01:04 WARN]: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[15:01:04 WARN]: 	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61)
[15:01:04 WARN]: 	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:85)
[15:01:04 WARN]: 	at com.mysql.cj.util.TimeUtil.getCanonicalTimezone(TimeUtil.java:132)
[15:01:04 WARN]: 	at com.mysql.cj.protocol.a.NativeProtocol.configureTimezone(NativeProtocol.java:2118)
[15:01:04 WARN]: 	at com.mysql.cj.protocol.a.NativeProtocol.initServerSession(NativeProtocol.java:2142)
[15:01:04 WARN]: 	at com.mysql.cj.jdbc.ConnectionImpl.initializePropsFromServer(ConnectionImpl.java:1310)
[15:01:04 WARN]: 	at com.mysql.cj.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:967)
[15:01:04 WARN]: 	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:826)
[15:01:04 WARN]: 	... 20 more
[15:01:04 WARN]: java.lang.NullPointerException
[15:01:04 WARN]: 	at org.apocgaming.payday.dao.ServersDao.addServer(ServersDao.java:12)
[15:01:04 WARN]: 	at org.apocgaming.payday.dao.RewardsDao.checkServerRecord(RewardsDao.java:296)
[15:01:04 WARN]: 	at org.apocgaming.payday.services.RewardService.checkServerList(RewardService.java:560)
[15:01:04 WARN]: 	at org.apocgaming.payday.PayDay.onEnable(PayDay.java:63)
[15:01:04 WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:177)
[15:01:04 WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:318)
[15:01:04 WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:399)
[15:01:04 WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:477)
[15:01:04 WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:418)
[15:01:04 WARN]: 	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:386)
[15:01:04 WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:319)
[15:01:04 WARN]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:593)
[15:01:04 WARN]: 	at java.lang.Thread.run(Thread.java:823)
```

**Comment by Shawiizz** [comment]
Can you tell me the plugin name please ?

**Comment by Zilacon** [comment]
The name is on the first line of the log.

**Comment by Shawiizz** [comment]
Ok ok, this evening i will make me a plugin with MySQL database to test.

**Comment by Zilacon** [comment]
Im guessing this problem also effects GriefPreventionPlus as ours just deadlocks while trying to load the claims.
So our plugin just throws an error as to why it cant connect, but GPP just sits there scratching its head.

This also is not an issue on magma or catserver.

**Comment by Rabbit0w0** [comment]
this seems strange, it must works, ill check it this evening
tell us the version
