### ISSUE TITLE
Random errors(ProtocolLib)

### ISSUE THREAD

**Issue by DolphinGamerYT** [Teneted/Tenet#60]
Hi,
I would like to do a server with mohist, but first I want to get raid of the error messages:

1. `[18:17:00 ERROR]: [Triton] Unhandled exception number 64 occured in onPacketSending(PacketEvent) for Triton
java.lang.NoClassDefFoundError: net/minecraft/client/renderer/culling/ICamera
at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:1.8.0_212]
at java.lang.Class.privateGetDeclaredMethods(Class.java:2701) ~[?:1.8.0_212]
at java.lang.Class.getDeclaredMethods(Class.java:1975) ~[?:1.8.0_212]
at com.comphenix.protocol.reflect.ExactReflection.getMethod(ExactReflection.java:75) ~[ProtocolLib.jar:?]
at com.comphenix.protocol.reflect.ExactReflection.getMethod(ExactReflection.java:86) ~[ProtocolLib.jar:?]
at com.comphenix.protocol.reflect.ExactReflection.getMethod(ExactReflection.java:70) ~[ProtocolLib.jar:?]
at com.comphenix.protocol.reflect.accessors.Accessors.getMethodAccessor(Accessors.java:243) ~[ProtocolLib.jar:?]
at com.comphenix.protocol.utility.MinecraftReflection.getBukkitEntity(MinecraftReflection.java:360) ~[ProtocolLib.jar:?]
at com.comphenix.protocol.injector.EntityUtilities.getEntityFromID(EntityUtilities.java:232) ~[ProtocolLib.jar:?]
at com.comphenix.protocol.injector.PacketFilterManager.getEntityFromID(PacketFilterManager.java:932) ~[ProtocolLib.jar:?]
at com.comphenix.protocol.wrappers.BukkitConverters$9.getSpecific(BukkitConverters.java:640) ~[ProtocolLib.jar:?]
at com.comphenix.protocol.wrappers.BukkitConverters$9.getSpecific(BukkitConverters.java:625) ~[ProtocolLib.jar:?]
at com.comphenix.protocol.reflect.StructureModifier.readInternal(StructureModifier.java:227) ~[ProtocolLib.jar:?]
at com.comphenix.protocol.reflect.StructureModifier.read(StructureModifier.java:195) ~[ProtocolLib.jar:?]
at com.comphenix.protocol.reflect.StructureModifier.readSafely(StructureModifier.java:258) ~[ProtocolLib.jar:?]
at com.rexcantor64.triton.h.d.a(ProtocolLibListener.java:178) ~[Triton-v2.3.0-NULLED.jar:?]
at com.rexcantor64.triton.h.d.onPacketSending(ProtocolLibListener.java:595) ~[Triton-v2.3.0-NULLED.jar:?]
at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) [ProtocolLib.jar:?]
at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) [ProtocolLib.jar:?]
at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:588) [ProtocolLib.jar:?]
at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:564) [ProtocolLib.jar:?]
at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:338) [ProtocolLib.jar:?]
at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:298) [ProtocolLib.jar:?]
at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:367) [ProtocolLib.jar:?]
at com.comphenix.protocol.injector.netty.ChannelInjector.access$800(ChannelInjector.java:66) [ProtocolLib.jar:?]
at com.comphenix.protocol.injector.netty.ChannelInjector$3.handleScheduled(ChannelInjector.java:332) [ProtocolLib.jar:?]
at com.comphenix.protocol.injector.netty.ChannelInjector$3.onMessageScheduled(ChannelInjector.java:302) [ProtocolLib.jar:?]
at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127) [ProtocolLib.jar:?]
at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95) [ProtocolLib.jar:?]
at net.minecraft.network.NetworkManager.func_150732_b(NetworkManager.java:247) [gw.class:?]
at net.minecraft.network.NetworkManager.func_179290_a(NetworkManager.java:179) [gw.class:?]
at net.minecraft.network.NetHandlerPlayServer.func_147359_a(NetHandlerPlayServer.java:1311) [pa.class:?]
at net.minecraft.entity.EntityTrackerEntry.func_151259_a(EntityTrackerEntry.java:369) [os.class:?]
at net.minecraft.entity.EntityTrackerEntry.func_151261_b(EntityTrackerEntry.java:375) [os.class:?]
at net.minecraft.entity.EntityTrackerEntry.func_111190_b(EntityTrackerEntry.java:343) [os.class:?]
at net.minecraft.entity.EntityTrackerEntry.func_73122_a(EntityTrackerEntry.java:292) [os.class:?]
at net.minecraft.entity.EntityTracker.func_72788_a(EntityTracker.java:293) [ol.class:?]
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:923) [MinecraftServer.class:?]
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:464) [nz.class:?]
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:784) [MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:627) [MinecraftServer.class:?]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.renderer.culling.ICamera
at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:110) ~[Mohist.jar:88d0186]
at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_212]
at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_212]
... 42 more`

2.`> [18:21:49 INFO]: false
> [18:21:55 INFO]: false
> [18:22:01 INFO]: false
> [18:22:02 INFO]: false
> [18:22:10 INFO]: false
> [18:22:13 INFO]: false`
Keeps getting spamed for no reason.

Mods that I have: https://wiki.winterzone.org
Plugins that I have: UltraPermissions, UltraCustomizer, Triton, ProtocolLib, PlaceholderAPI, KiteBoard

**Comment by DolphinGamerYT** [comment]
And mohist commands are not working :(

**Comment by Mgazul** [comment]
> And mohist commands are not working :(

#55
