### ISSUE TITLE
[1.16.4] Thermal mods crash on explosion

### ISSUE THREAD

**Issue by bigenergy** [Teneted/Tenet#611]
Drop the bomb and the server will crash
[crash-2020-11-02_02.51.18-server.txt](https://github.com/Mohist-Community/Mohist/files/5472037/crash-2020-11-02_02.51.18-server.txt)

**Comment by bigenergy** [comment]
Also, if you try to open any block from the thermal

```
[02:56:00] [Server thread/FATAL] [net.minecraft.util.concurrent.ThreadTaskExecutor/]: Error executing task on Server
io.netty.handler.codec.DecoderException: ByteArray with size 64 is bigger than allowed 1
	at net.minecraft.network.PacketBuffer.func_189425_b(PacketBuffer.java:92) ~[?:?]
	at net.minecraft.network.PacketBuffer.func_179251_a(PacketBuffer.java:86) ~[?:?]
	at net.minecraftforge.fml.network.FMLPlayMessages$OpenContainer.encode(FMLPlayMessages.java:289) ~[forge:?]
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec.lambda$tryEncode$4(IndexedMessageCodec.java:134) ~[forge:?]
	at java.util.Optional.ifPresent(Unknown Source) ~[?:1.8.0_221]
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec.tryEncode(IndexedMessageCodec.java:132) ~[forge:?]
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec.build(IndexedMessageCodec.java:147) ~[forge:?]
	at net.minecraftforge.fml.network.simple.SimpleChannel.encodeMessage(SimpleChannel.java:85) ~[forge:?]
	at net.minecraftforge.fml.network.simple.SimpleChannel.toBuffer(SimpleChannel.java:98) ~[forge:?]
	at net.minecraftforge.fml.network.simple.SimpleChannel.toVanillaPacket(SimpleChannel.java:129) ~[forge:?]
	at net.minecraftforge.fml.network.simple.SimpleChannel.sendTo(SimpleChannel.java:109) ~[forge:?]
	at net.minecraftforge.fml.network.NetworkHooks.openGui(NetworkHooks.java:237) ~[forge:?]
	at net.minecraftforge.fml.network.NetworkHooks.openGui(NetworkHooks.java:183) ~[forge:?]
	at cofh.core.block.TileBlockCoFH.func_225533_a_(TileBlockCoFH.java:70) ~[cofh_core:1.0.0]
	at net.minecraft.block.AbstractBlock$AbstractBlockState.func_227031_a_(AbstractBlock.java:640) ~[?:?]
	at net.minecraft.server.management.PlayerInteractionManager.func_219441_a(PlayerInteractionManager.java:478) ~[?:?]
	at net.minecraft.network.play.ServerPlayNetHandler.func_184337_a(ServerPlayNetHandler.java:1314) ~[?:?]
	at net.minecraft.network.play.client.CPlayerTryUseItemOnBlockPacket.func_148833_a(CPlayerTryUseItemOnBlockPacket.java:38) ~[?:?]
	at net.minecraft.network.play.client.CPlayerTryUseItemOnBlockPacket.func_148833_a(CPlayerTryUseItemOnBlockPacket.java:12) ~[?:?]
	at net.minecraft.network.PacketThreadUtil.lambda$checkThreadAndEnqueue$0(PacketThreadUtil.java:22) ~[?:?]
	at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) ~[?:?]
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:992) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:174) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:975) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:969) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(SourceFile:127) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:955) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:884) ~[?:?]
	at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:267) ~[?:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]
```

**Comment by Mgazul** [comment]
Test again

**Comment by bigenergy** [comment]
> Test again

crash on server start
[crash-2020-11-03_00.14.07-server.txt](https://github.com/Mohist-Community/Mohist/files/5478075/crash-2020-11-03_00.14.07-server.txt)

**Comment by bigenergy** [comment]
@Mgazul mohist-1.16.4-35.0.15
[crash-2020-11-12_19.51.33-server.txt](https://github.com/Mohist-Community/Mohist/files/5532007/crash-2020-11-12_19.51.33-server.txt)
and https://github.com/Mohist-Community/Mohist/issues/611#issuecomment-720173059 still bug
