### ISSUE TITLE
Crash with LivingThings mod

### ISSUE THREAD

**Issue by 469512345** [Teneted/Tenet#612]
Using the [LivingThings](https://www.curseforge.com/minecraft/mc-mods/living-things) mod, I'm getting a crash with the Owl entity, but not any others.

```
[00:17:22 ERROR]: Encountered an unexpected exception
java.lang.AssertionError: Unknown entity class com.tristankechlo.livingthings.entities.OwlEntity
	at org.bukkit.craftbukkit.v1_16_R2.entity.CraftEntity.getEntity(CraftEntity.java:387) ~[forge:?] {re:classloading}
	at net.minecraft.entity.Entity.getBukkitEntity(Entity.java:147) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at org.bukkit.craftbukkit.v1_16_R2.event.CraftEventFactory.callCreatureSpawnEvent(CraftEventFactory.java:578) ~[forge:?] {re:classloading}
	at org.bukkit.craftbukkit.v1_16_R2.event.CraftEventFactory.doEntityAddEventCalling(CraftEventFactory.java:519) ~[forge:?] {re:classloading}
	at net.minecraft.world.server.ServerWorld.addEntity0(ServerWorld.java:947) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.world.server.ServerWorld.addEntity(ServerWorld.java:878) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.entity.EntityType.spawn(EntityType.java:329) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.entity.EntityType.func_220342_a(EntityType.java:321) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.entity.EntityType.func_220331_a(EntityType.java:315) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.item.SpawnEggItem.func_195939_a(SpawnEggItem.java:80) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraftforge.common.ForgeHooks.onPlaceItemIntoWorld(ForgeHooks.java:605) ~[forge:?] {re:classloading}
	at net.minecraft.item.ItemStack.func_196084_a(ItemStack.java:236) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.management.PlayerInteractionManager.func_219441_a(PlayerInteractionManager.java:498) ~[?:?] {re:classloading}
	at net.minecraft.network.play.ServerPlayNetHandler.func_184337_a(ServerPlayNetHandler.java:1314) ~[?:?] {re:classloading}
	at net.minecraft.network.play.client.CPlayerTryUseItemOnBlockPacket.func_148833_a(CPlayerTryUseItemOnBlockPacket.java:38) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.network.play.client.CPlayerTryUseItemOnBlockPacket.func_148833_a(CPlayerTryUseItemOnBlockPacket.java:12) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.network.PacketThreadUtil.lambda$checkThreadAndEnqueue$0(PacketThreadUtil.java:22) ~[?:?] {re:classloading}
	at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?] {re:classloading}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?] {re:classloading}
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:992) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:174) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:975) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:969) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(SourceFile:127) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:955) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:884) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:267) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_265] {}
```

Using Mohist 1.16.3 #71. Is this a bug with the mod iteself or with mohist? Goes without saying that it does not occur on a forge server of the same version.

**Comment by Mgazul** [comment]
Test again

**Comment by 469512345** [comment]
Still occurring in debug-73.
I spawned in a spawn Owl egg and instantly this happened. A full log of the server can be seen [here](https://pastebin.com/wThDemxf) as there are other errors which may help identify the problem. This was taken on a fresh server install with no world etc.

```
[14:01:20 FATAL]: Preparing crash report with UUID e6d3f6dd-212d-4a6b-81e5-6cac54860963
[14:01:20 ERROR]: Encountered an unexpected exception
net.minecraft.crash.ReportedException: Exception ticking world
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1155) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:341) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:1047) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:880) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:267) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_265] {}
Caused by: java.lang.AssertionError: Unknown entity class com.tristankechlo.livingthings.entities.OwlEntity
	at org.bukkit.craftbukkit.v1_16_R2.entity.CraftEntity.getEntity(CraftEntity.java:387) ~[forge:?] {re:classloading}
	at net.minecraft.entity.Entity.getBukkitEntity(Entity.java:147) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at org.bukkit.craftbukkit.v1_16_R2.event.CraftEventFactory.callCreatureSpawnEvent(CraftEventFactory.java:578) ~[forge:?] {re:classloading}
	at org.bukkit.craftbukkit.v1_16_R2.event.CraftEventFactory.doEntityAddEventCalling(CraftEventFactory.java:519) ~[forge:?] {re:classloading}
	at net.minecraft.world.server.ServerWorld.addEntity0(ServerWorld.java:947) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.world.server.ServerWorld.addEntity(ServerWorld.java:878) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.world.IServerWorld.lambda$addAllEntities$0(IServerWorld.java:15) ~[?:?] {re:classloading}
	at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:419) ~[?:1.8.0_265] {}
	at java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:742) ~[?:1.8.0_265] {}
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:647) ~[?:1.8.0_265] {}
	at net.minecraft.world.IServerWorld.addAllEntities(IServerWorld.java:15) ~[?:?] {re:classloading}
	at net.minecraft.world.spawner.WorldEntitySpawner.func_234966_a_(WorldEntitySpawner.java:222) ~[?:?] {re:classloading}
	at net.minecraft.world.spawner.WorldEntitySpawner.func_234967_a_(WorldEntitySpawner.java:169) ~[?:?] {re:classloading}
	at net.minecraft.world.spawner.WorldEntitySpawner.func_234979_a_(WorldEntitySpawner.java:154) ~[?:?] {re:classloading}
	at net.minecraft.world.server.ServerChunkProvider.lambda$tickChunks$6(ServerChunkProvider.java:403) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at java.util.ArrayList.forEach(ArrayList.java:1259) ~[?:1.8.0_265] {}
	at net.minecraft.world.server.ServerChunkProvider.func_217220_m(ServerChunkProvider.java:390) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.world.server.ServerChunkProvider.func_217207_a(ServerChunkProvider.java:363) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:407) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1143) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	... 5 more
[14:01:20 ERROR]: 	Cause of unexpected exception was
java.lang.AssertionError: Unknown entity class com.tristankechlo.livingthings.entities.OwlEntity
	at org.bukkit.craftbukkit.v1_16_R2.entity.CraftEntity.getEntity(CraftEntity.java:387) ~[forge:?] {re:classloading}
	at net.minecraft.entity.Entity.getBukkitEntity(Entity.java:147) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at org.bukkit.craftbukkit.v1_16_R2.event.CraftEventFactory.callCreatureSpawnEvent(CraftEventFactory.java:578) ~[forge:?] {re:classloading}
	at org.bukkit.craftbukkit.v1_16_R2.event.CraftEventFactory.doEntityAddEventCalling(CraftEventFactory.java:519) ~[forge:?] {re:classloading}
	at net.minecraft.world.server.ServerWorld.addEntity0(ServerWorld.java:947) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.world.server.ServerWorld.addEntity(ServerWorld.java:878) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.world.IServerWorld.lambda$addAllEntities$0(IServerWorld.java:15) ~[?:?] {re:classloading}
	at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:419) ~[?:1.8.0_265] {}
	at java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:742) ~[?:1.8.0_265] {}
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:647) ~[?:1.8.0_265] {}
	at net.minecraft.world.IServerWorld.addAllEntities(IServerWorld.java:15) ~[?:?] {re:classloading}
	at net.minecraft.world.spawner.WorldEntitySpawner.func_234966_a_(WorldEntitySpawner.java:222) ~[?:?] {re:classloading}
	at net.minecraft.world.spawner.WorldEntitySpawner.func_234967_a_(WorldEntitySpawner.java:169) ~[?:?] {re:classloading}
	at net.minecraft.world.spawner.WorldEntitySpawner.func_234979_a_(WorldEntitySpawner.java:154) ~[?:?] {re:classloading}
	at net.minecraft.world.server.ServerChunkProvider.lambda$tickChunks$6(ServerChunkProvider.java:403) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at java.util.ArrayList.forEach(ArrayList.java:1259) ~[?:1.8.0_265] {}
	at net.minecraft.world.server.ServerChunkProvider.func_217220_m(ServerChunkProvider.java:390) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.world.server.ServerChunkProvider.func_217207_a(ServerChunkProvider.java:363) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:407) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1143) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:341) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:1047) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:880) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:267) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_265] {}
```
