### ISSUE TITLE
[1.12.2] Error on use Block.getType()

### ISSUE THREAD

**Issue by FabioZumbi12** [Teneted/Tenet#631]
I have a plugin where i using block.getType() and i having this error:

```
[23:11:50 ERROR]: Could not pass event PlayerInteractEvent to ButtonWarp v2.2.3
 org.bukkit.event.EventException: null        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:63) ~[EventExecutor.class:?]        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:73) ~[TimedEventExecutor.class:?]        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66) ~[RegisteredListener.class:?]        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) ~[SimplePluginManager.class:?]        at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:331) ~[CraftEventFactory.class:?]        at net.minecraft.server.management.PlayerInteractionManager.func_187251_a(PlayerInteractionManager.java:501) ~[or.class:?]        at net.minecraft.network.NetHandlerPlayServer.func_184337_a(NetHandlerPlayServer.java:1148) ~[pa.class:?]        at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(CPacketPlayerTryUseItemOnBlock.java:61) ~[ma.class:?]        at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(CPacketPlayerTryUseItemOnBlock.java:13) ~[ma.class:?]        at net.minecraft.network.PacketThreadUtil.lambda$checkThreadAndEnqueue$0(PacketThreadUtil.java:16) ~[hv.class:?]        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_262]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_262]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:843) [MinecraftServer.class:?]        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:470) [nz.class:?]        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:781) [MinecraftServer.class:?]        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:627) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_262]
Caused by: java.lang.NullPointerException        at com.codisimus.plugins.buttonwarp.ButtonWarpListener.onPlayerInteract(ButtonWarpListener.java:42) ~[?:?]        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor52.execute(Unknown Source) ~[?:?]        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:61) ~[EventExecutor.class:?]
        ... 17 more
```
I am using this version: mohist-1.12.2-104-server.jar
The tested blocks are concrete blocks!

The code snipet follows:
```
Material type = block.getType();
```

And also, it happens with more plugins using this method.

**Comment by Mgazul** [comment]
Please provide your plugin

**Comment by FabioZumbi12** [comment]
Its the ButtonWarp (a private version of an old public plugin). Btw it happens with my other plugin called redprotect, in this lines: https://github.com/FabioZumbi12/RedProtect/commit/f6b411347bd2867bc303b4d2a8a4f8afa4f3b5fd#diff-37b6da8d3c635bd4005ebfc7d628068af7719a823d979d971c3b19f429d77e9cL112

It was debug messages, but i have removed for now to do not get this errors.

**Comment by FabioZumbi12** [comment]
It seems happens only with concrete blocks!

**Comment by FabioZumbi12** [comment]
The error above allow people to break concrete blocks, but now i having this same error on getState(), but this error crash the server:

```

Hora: 20/11/20 00:38
Descrição: Exception ticking world

java.lang.NullPointerException: Exception ticking world
	at org.bukkit.craftbukkit.v1_12_R1.block.CraftBlock.getState(CraftBlock.java:299)
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.handleBlockGrowEvent(CraftEventFactory.java:794)
	at net.minecraft.block.BlockCrops.func_180650_b(BlockCrops.java:86)
	at net.minecraft.block.BlockBeetroot.func_180650_b(SourceFile:53)
	at net.minecraft.block.Block.func_180645_a(Block.java:517)
	at net.minecraft.world.WorldServer.func_147456_g(WorldServer.java:606)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:347)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:887)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:470)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:781)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:627)
	at java.lang.Thread.run(Thread.java:748)

```
