### ISSUE TITLE
[1.12.2] Error on block.CraftBlock.getState

### ISSUE THREAD

**Issue by FabioZumbi12** [Teneted/Tenet#639]
Now i having this error, but this error crash the server every time and reboot. Its seems not related with plugins and mods, occurs any time randonly.

```

Hora: 20/11/20 00:38
Descrição: Exception ticking world

java.lang.NullPointerException: Exception ticking world
	at org.bukkit.craftbukkit.v1_12_R1.block.CraftBlock.getState(CraftBlock.java:299)
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.handleBlockGrowEvent(CraftEventFactory.java:794)
	at net.minecraft.block.BlockCrops.func_180650_b(BlockCrops.java:86)
	at net.minecraft.block.BlockBeetroot.func_180650_b(SourceFile:53)
	at net.minecraft.block.Block.func_180645_a(Block.java:517)
	at net.minecraft.world.WorldServer.func_147456_g(WorldServer.java:606)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:347)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:887)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:470)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:781)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:627)
	at java.lang.Thread.run(Thread.java:748)

```

I dont know if is related with #631 but probably yes.

Mohist version: mohist-1.12.2-106-server.jar

If you add a try/catch in this section until you find a solution, just to do not crash the server, ill glad... the server its really rebooting every time :( 
Thank you!

**Comment by FabioZumbi12** [comment]
More details on getState, but with BlockConcrete:

```
[20:09:24 ERROR]: Encontrada uma exceção inesperada
 java.lang.NullPointerException: null
        at org.bukkit.craftbukkit.v1_12_R1.block.CraftBlock.getState(CraftBlock.java:299) ~[CraftBlock.class:?]
        at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.handleBlockFormEvent(CraftEventFactory.java:1226) ~[CraftEventFactory.class:?]
        at net.minecraft.block.BlockConcretePowder.func_192425_e(BlockConcretePowder.java:57) ~[apq.class:?]
        at net.minecraft.block.BlockConcretePowder.func_176213_c(BlockConcretePowder.java:73) ~[apq.class:?]
        at net.minecraft.world.chunk.Chunk.func_177436_a(Chunk.java:654) ~[axw.class:?]
        at net.minecraft.world.World.func_180501_a(World.java:513) ~[amu.class:?]
        at net.minecraft.entity.item.EntityFallingBlock.func_70071_h_(EntityFallingBlock.java:191) ~[ack.class:?]
        at net.minecraft.world.World.func_72866_a(World.java:2420) ~[amu.class:?]
        at net.minecraft.world.World.func_72870_g(World.java:2371) ~[amu.class:?]
        at net.minecraft.world.World.func_72939_s(World.java:2141) ~[amu.class:?]
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:744) ~[oo.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:900) ~[MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:470) ~[nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:781) ~[MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:627) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_272]
```

Using mohist build 112

**Comment by Irgendwer01** [comment]
@FabioZumbi12 can u maybe post here the mods and plugins list?

**Comment by FabioZumbi12** [comment]
Shure, here is:
>mohist mods
[17:05:16 INFO]: 10 [minecraft, backpacks16840, FML, grandeconomy, mohist, cfm, pixelextras, recipehandler, bibliocraft, forge, itemblacklist, mcp, trainercommands, pixelmon]

> Plugins (23): AutoSaveWorld, BetterAlias, ButtonWarp, ButtonWarpRandom, Ch
estShop, Essentials, EssentialsGeoIP, EssentialsSpawn, Grand-Economy-Vault-Integration, JDA
LibLoaderBukkit, LuckPerms, MarriageMaster, MaxBans, Multiverse-Core, PixelVip, PlugMan, RedBackups, RedProtect, TranslationAPI, UltimateChat, UltimateTrash, Vault, WorldEdit

**Comment by FabioZumbi12** [comment]
Teste without decoration MODs and the error stills. MODs tested:

> mohist mods
[17:05:16 INFO]: 10 [minecraft, FML, grandeconomy, mohist, pixelextras, forge, mcp, trainercommands, pixelmon]

**Comment by joaoespanhol** [comment]
good job
