### ISSUE TITLE
Exception ticking world

### ISSUE THREAD

**Issue by UrsusDeningeri** [Teneted/Tenet#640]
Minecraft version: 1.12.2
Mohist build: 107
Pastebin Crash report : https://pastebin.com/yxUCpnef

The server accidentally crashes for no reason. It doesn't even affect players online because it crashes when there are 0 or 15 players on the server. It never fell before, but this has happened since about Mohist build: 100. Mods and plugins haven't changed or updated since then.

---------------------------------------------------------------------------------------

Description: Exception ticking world

java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1445)
	at java.util.HashMap$KeyIterator.next(HashMap.java:1469)
	at net.minecraft.server.management.PlayerChunkMap.func_72693_b(PlayerChunkMap.java:133)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:351)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:887)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:470)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:781)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:627)
	at java.lang.Thread.run(Thread.java:748)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1445)
	at java.util.HashMap$KeyIterator.next(HashMap.java:1469)
	at net.minecraft.server.management.PlayerChunkMap.func_72693_b(PlayerChunkMap.java:133)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:351)

**Comment by PierreBouffartigue** [comment]
I have the same problem, it’s very annoying.

**Comment by UrsusDeningeri** [comment]
I agree with that that it's annoying. I'm currently trying to find out from which build it started to cause problems because I know that before I updated mohist so I had a version lower than 100 and the server didn't crash yet.

Sorry for bad english (translator)

**Comment by VoldirFr** [comment]
I have the same, will an update be soon available ?

**Comment by EpickaMC** [comment]
Hello, I also have this problem. The server has several crashes per day

**Comment by ghost** [comment]
yes me the same
