### ISSUE TITLE
[Fast Async World Edit Mohist 1.12.2] Problem with rotate and flip command

### ISSUE THREAD

**Issue by PierreBouffartigue** [Teneted/Tenet#656]
Hello, when I try to paste a selection after //flip or //rotate I get this error and the command does not work :
 ```
[20:15:39 ERROR]: [WorldEdit] An unexpected error occurred while handling a FAWE command
 java.lang.ArrayIndexOutOfBoundsException: 4096
        at com.sk89q.worldedit.world.registry.BundledBlockData.findById(BundledBlockData.java:363) ~[FastAsyncWorldEdit-mohist-all.jar:?]
        at com.sk89q.worldedit.world.registry.BundledBlockData.getStatesById(BundledBlockData.java:443) ~[FastAsyncWorldEdit-mohist-all.jar:?]
        at com.sk89q.worldedit.world.registry.LegacyBlockRegistry.getStates(LegacyBlockRegistry.java:60) ~[WorldEdit.jar:?]
        at com.sk89q.worldedit.extent.transform.BlockTransformExtent.transform(BlockTransformExtent.java:200) ~[FastAsyncWorldEdit-mohist-all.jar:?]
        at com.sk89q.worldedit.extent.transform.BlockTransformExtent.transform(BlockTransformExtent.java:183) ~[FastAsyncWorldEdit-mohist-all.jar:?]
        at com.sk89q.worldedit.extent.transform.BlockTransformExtent.cache(BlockTransformExtent.java:57) ~[FastAsyncWorldEdit-mohist-all.jar:?]
        at com.sk89q.worldedit.extent.transform.BlockTransformExtent.<init>(BlockTransformExtent.java:48) ~[FastAsyncWorldEdit-mohist-all.jar:?]
        at com.sk89q.worldedit.session.PasteBuilder.build(PasteBuilder.java:119) ~[FastAsyncWorldEdit-mohist-all.jar:?]
        at com.sk89q.worldedit.command.ClipboardCommands.paste(ClipboardCommands.java:476) ~[FastAsyncWorldEdit-mohist-all.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_271]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_271]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_271]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_271]
        at com.sk89q.worldedit.util.command.parametric.ParametricCallable.call(ParametricCallable.java:265) ~[FastAsyncWorldEdit-mohist-all.jar:?]
        at com.sk89q.worldedit.util.command.SimpleDispatcher.call(SimpleDispatcher.java:133) ~[FastAsyncWorldEdit-mohist-all.jar:?]
        at com.sk89q.worldedit.extension.platform.CommandManager$2.get(CommandManager.java:413) ~[FastAsyncWorldEdit-mohist-all.jar:?]
        at com.sk89q.worldedit.extension.platform.CommandManager.handleCommandTask(CommandManager.java:436) ~[FastAsyncWorldEdit-mohist-all.jar:?]
        at com.sk89q.worldedit.extension.platform.CommandManager.handleCommandOnCurrentThread(CommandManager.java:417) ~[FastAsyncWorldEdit-mohist-all.jar:?]
        at com.sk89q.worldedit.extension.platform.CommandManager$3$1.run(CommandManager.java:535) ~[FastAsyncWorldEdit-mohist-all.jar:?]
        at com.boydti.fawe.object.FawePlayer.lambda$runAction$2(FawePlayer.java:341) ~[FastAsyncWorldEdit-mohist-all.jar:?]
        at com.boydti.fawe.object.task.SimpleAsyncNotifyQueue.operate(SimpleAsyncNotifyQueue.java:25) [FastAsyncWorldEdit-mohist-all.jar:?]
        at com.boydti.fawe.object.task.AsyncNotifyQueue$1.run(AsyncNotifyQueue.java:15) [FastAsyncWorldEdit-mohist-all.jar:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:64) [CraftTask.class:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:50) [CraftAsyncTask.class:?]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) [ServerSchedulerReportingWrapper.class:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_271]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_271]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_271]
```

**Comment by Mgazul** [comment]
This has been fixed, a bug from FAWE
