### ISSUE TITLE
[1.16.4] Startup halt on headless check 

### ISSUE THREAD

**Issue by acl1704** [Teneted/Tenet#668]
Running in debian docker on a VPS. 1.12.2 works fine, 1.16.4 doesn't get past startup.

This check halts the startup process.

```Found java version 1.8.0_275
Exception in thread "main" 
java.awt.HeadlessException: 
No X11 DISPLAY variable was set, but this program performed an operation which requires it.
        at java.awt.GraphicsEnvironment.checkHeadless(GraphicsEnvironment.java:204)
        at java.awt.Window.<init>(Window.java:536)
        at java.awt.Frame.<init>(Frame.java:420)
        at net.minecraftforge.installer.InstallerPanel.run(InstallerPanel.java:408)
        at net.minecraftforge.installer.SimpleInstaller.launchGui(SimpleInstaller.java:170)
        at net.minecraftforge.installer.SimpleInstaller.main(SimpleInstaller.java:143)```

**Comment by Shawiizz** [comment]
Hello, you are trying to run the installer and that's not good. You need to run the installer on your pc and click on install server and then upload all files to your vps. After that you just need to run the file forge-xxx.jar

**Comment by acl1704** [comment]
Ah I was unaware that was a new step. The wiki needs an update for the 1.16.4 process, I was working off old info.
