### ISSUE TITLE
[1.12.2] Error plugin faction

### ISSUE THREAD

**Issue by Estanos** [Teneted/Tenet#67]
Hello

I have a problem with the faction plugin which does not load when launching the server

`[21:13:12 INFO]: [Factions 2.14.0] === ENABLE START ===
[21:13:12 ERROR]: Une erreur s'est produite lors de l'activation de Factions v2.14.0 (est-il Ó jour?)
 java.lang.IllegalStateException: java.lang.ClassNotFoundException: Failed to remap class com.massivecraft.factions.integration.herochat.ChannelFactionsAllies
        at com.massivecraft.massivecore.xlib.guava.reflect.ClassPath$ClassInfo.load(ClassPath.java:331) ~[?:?]
        at com.massivecraft.massivecore.util.ReflectionUtil.getPackageClasses(ReflectionUtil.java:481) ~[?:?]
        at com.massivecraft.massivecore.MassivePlugin.getClassesActive(MassivePlugin.java:446) ~[?:?]
        at com.massivecraft.massivecore.MassivePlugin.getClassesActive(MassivePlugin.java:416) ~[?:?]
        at com.massivecraft.massivecore.MassivePlugin.getClassesActiveIntegrations(MassivePlugin.java:391) ~[?:?]
        at com.massivecraft.massivecore.MassivePlugin.getClassesActive(MassivePlugin.java:337) ~[?:?]
        at com.massivecraft.massivecore.MassivePlugin.activateAuto(MassivePlugin.java:324) ~[?:?]
        at com.massivecraft.factions.Factions.onEnableInner(Factions.java:80) ~[?:?]
        at com.massivecraft.massivecore.MassivePlugin.onEnable(MassivePlugin.java:82) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:177) ~[JavaPlugin.class:802b14f]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:327) [JavaPluginLoader.class:802b14f]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:399) [SimplePluginManager.class:802b14f]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:466) [CraftServer.class:802b14f]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:407) [CraftServer.class:802b14f]
        at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:384) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:319) [nz.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:587) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_181]
Caused by: java.lang.ClassNotFoundException: Failed to remap class com.massivecraft.factions.integration.herochat.ChannelFactionsAllies
        at org.bukkit.plugin.java.PluginClassLoader.remappedFindClass(PluginClassLoader.java:186) ~[PluginClassLoader.class:802b14f]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:110) ~[PluginClassLoader.class:802b14f]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:87) ~[PluginClassLoader.class:802b14f]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_181]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_181]
        at red.mohist.common.remap.proxy.ProxyClassLoader.loadClass(ProxyClassLoader.java:14) ~[ProxyClassLoader.class:802b14f]
        at com.massivecraft.massivecore.xlib.guava.reflect.ClassPath$ClassInfo.load(ClassPath.java:328) ~[?:?]
        ... 17 more
Caused by: java.lang.NoClassDefFoundError: com/massivecraft/factions/integration/herochat/ChannelFactionsAbstract
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_181]
        at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_181]
        at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_181]
        at org.bukkit.plugin.java.PluginClassLoader.remappedFindClass(PluginClassLoader.java:178) ~[PluginClassLoader.class:802b14f]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:110) ~[PluginClassLoader.class:802b14f]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:87) ~[PluginClassLoader.class:802b14f]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_181]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_181]
        at red.mohist.common.remap.proxy.ProxyClassLoader.loadClass(ProxyClassLoader.java:14) ~[ProxyClassLoader.class:802b14f]
        at com.massivecraft.massivecore.xlib.guava.reflect.ClassPath$ClassInfo.load(ClassPath.java:328) ~[?:?]
        ... 17 more
Caused by: java.lang.ClassNotFoundException: Failed to remap class com.massivecraft.factions.integration.herochat.ChannelFactionsAbstract
        at org.bukkit.plugin.java.PluginClassLoader.remappedFindClass(PluginClassLoader.java:186) ~[PluginClassLoader.class:802b14f]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:110) ~[PluginClassLoader.class:802b14f]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:87) ~[PluginClassLoader.class:802b14f]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_181]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_181]
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_181]
        at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_181]
        at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_181]
        at org.bukkit.plugin.java.PluginClassLoader.remappedFindClass(PluginClassLoader.java:178) ~[PluginClassLoader.class:802b14f]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:110) ~[PluginClassLoader.class:802b14f]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:87) ~[PluginClassLoader.class:802b14f]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_181]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_181]
        at red.mohist.common.remap.proxy.ProxyClassLoader.loadClass(ProxyClassLoader.java:14) ~[ProxyClassLoader.class:802b14f]
        at com.massivecraft.massivecore.xlib.guava.reflect.ClassPath$ClassInfo.load(ClassPath.java:328) ~[?:?]
        ... 17 more
Caused by: java.lang.NoClassDefFoundError: com/dthielke/herochat/Channel
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_181]
        at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_181]
        at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_181]
        at org.bukkit.plugin.java.PluginClassLoader.remappedFindClass(PluginClassLoader.java:178) ~[PluginClassLoader.class:802b14f]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:110) ~[PluginClassLoader.class:802b14f]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:87) ~[PluginClassLoader.class:802b14f]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_181]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_181]
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_181]
        at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_181]
        at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_181]
        at org.bukkit.plugin.java.PluginClassLoader.remappedFindClass(PluginClassLoader.java:178) ~[PluginClassLoader.class:802b14f]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:110) ~[PluginClassLoader.class:802b14f]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:87) ~[PluginClassLoader.class:802b14f]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_181]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_181]
        at red.mohist.common.remap.proxy.ProxyClassLoader.loadClass(ProxyClassLoader.java:14) ~[ProxyClassLoader.class:802b14f]
        at com.massivecraft.massivecore.xlib.guava.reflect.ClassPath$ClassInfo.load(ClassPath.java:328) ~[?:?]
        ... 17 more
Caused by: java.lang.ClassNotFoundException: com.dthielke.herochat.Channel
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:118) ~[PluginClassLoader.class:802b14f]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:87) ~[PluginClassLoader.class:802b14f]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_181]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_181]
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_181]
        at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_181]
        at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_181]
        at org.bukkit.plugin.java.PluginClassLoader.remappedFindClass(PluginClassLoader.java:178) ~[PluginClassLoader.class:802b14f]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:110) ~[PluginClassLoader.class:802b14f]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:87) ~[PluginClassLoader.class:802b14f]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_181]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_181]
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_181]
        at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_181]
        at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_181]
        at org.bukkit.plugin.java.PluginClassLoader.remappedFindClass(PluginClassLoader.java:178) ~[PluginClassLoader.class:802b14f]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:110) ~[PluginClassLoader.class:802b14f]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:87) ~[PluginClassLoader.class:802b14f]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_181]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_181]
        at red.mohist.common.remap.proxy.ProxyClassLoader.loadClass(ProxyClassLoader.java:14) ~[ProxyClassLoader.class:802b14f]
        at com.massivecraft.massivecore.xlib.guava.reflect.ClassPath$ClassInfo.load(ClassPath.java:328) ~[?:?]
        ... 17 more`

**Comment by Mgazul** [comment]
Unable to determine the error because I encountered the same error on spigot
