### ISSUE TITLE
[1.16.4] Yet another inventory bug

### ISSUE THREAD

**Issue by Dum4G** [Teneted/Tenet#675]
### Minecraft 1.16.4
Mohist version 147
Affected mods: any with items that have container slots
No other mods or plugins installed for the test. Happened in CookingForBlockheads and christmasfestivity as well

### Description
Whenever I try to open any modded item with container slots the error occurs as soon as we open a custom interface. So when I place something in it the item gets back to my hand and the same error reoccurs. Interestingly enough an item with animation registers that something was placed in it

### Steps to reproduce 

1. Install buildersaddition-1.16.4-20201130b
2. Take a bookshelf
3. Click on it
4. Try to place anything in it
5. See an error
6. See an animation

### [Logs](https://gist.github.com/Dum4G/e24f6cbb2f2d77bec4fc743e8d3c0e5c)

```
[22:00:15] [Server thread/FATAL] [net.minecraft.util.concurrent.ThreadTaskExecutor/]: Error executing task on Server
java.lang.NullPointerException: null
	at net.minecraft.network.play.ServerPlayNetHandler.func_147351_a(ServerPlayNetHandler.java:2075) ~[?:?]
	at net.minecraft.network.play.client.CClickWindowPacket.func_148833_a(CClickWindowPacket.java:34) ~[?:?]
	at net.minecraft.network.play.client.CClickWindowPacket.func_148833_a(CClickWindowPacket.java:12) ~[?:?]
	at net.minecraft.network.PacketThreadUtil.lambda$checkThreadAndEnqueue$0(PacketThreadUtil.java:22) ~[?:?]
	at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) ~[?:?]
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:993) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:175) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:976) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:970) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(SourceFile:127) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:956) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:885) ~[?:?]
	at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:268) ~[?:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
```

**Comment by Sl0ter** [comment]
Same with the mod IronChest
