### ISSUE TITLE
[1.12.2][Mohist]: Error occurred while enabling Shop v1.8.1 (Is it up to date?) java.lang.NoClassDefFoundError: org/bukkit/block/data/BlockData

### ISSUE THREAD

**Issue by ProsperCraft** [Teneted/Tenet#68]
This plugin is unable to load-
https://www.spigotmc.org/resources/shop-a-simple-intuitive-shop-plugin.9628/

https://gist.github.com/ProsperCraft/0979a781e6e4ae6086b19b28dc808b92

Mohist-cdc8c79-server

`[06:06:54] [Server thread/INFO] [Mohist]: Enabling Shop v1.8.1
[06:06:54] [Server thread/ERROR] [Mohist]: Error occurred while enabling Shop v1.8.1 (Is it up to date?)
java.lang.NoClassDefFoundError: org/bukkit/block/data/BlockData
	at com.snowgears.shop.Shop.onEnable(Shop.java:120) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:177) ~[JavaPlugin.class:2b0299e]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:327) [JavaPluginLoader.class:2b0299e]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:399) [SimplePluginManager.class:2b0299e]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:466) [CraftServer.class:2b0299e]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:407) [CraftServer.class:2b0299e]
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:384) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:319) [nz.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:587) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: java.lang.ClassNotFoundException: org.bukkit.block.data.BlockData
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[PluginClassLoader.class:2b0299e]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:87) ~[PluginClassLoader.class:2b0299e]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_181]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_181]
	... 10 more`

**Comment by Mgazul** [comment]
The plugin uses 1.13+ stuff, can you provide a copy of the plugin? Because it is paid, I cannot test

**Comment by ProsperCraft** [comment]
So perhaps I should use an older version of the plugin..

**Comment by Mgazul** [comment]
Shop1.7.3.2 Working
