### ISSUE TITLE
[1.16.4] NPE when server starts

### ISSUE THREAD

**Issue by Shawiizz** [Teneted/Tenet#681]
[14:54:55 ERROR]: Encountered an unexpected exception                           java.lang.NullPointerException: null
at net.minecraft.world.storage.ServerWorldInfo.func_230409_a_(ServerWorldInfo.java:394) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
at net.minecraft.server.MinecraftServer.func_147139_a(MinecraftServer.java:1319) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}at net.minecraft.server.dedicated.DedicatedServer.func_230543_p_(DedicatedServer.java:309) ~[?:?] {re:classloading,pl:accesstransformer:B}
at net.minecraft.server.MinecraftServer.func_240800_l__(MinecraftServer.java:494) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:235) ~[?:?] {re:classloading,pl:accesstransformer:B}
at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:842) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:268) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252] {}

[14:54:55 FATAL]: Preparing crash report with UUID 979d8747-0987-4a0d-b1a8-1aa8d056104f

**Comment by Shawiizz** [comment]
(Happening with a fresh install of build 171)

**Comment by 27rogi** [comment]
I'm also getting this problem. Plus there's same bug with `Resourceful Bees` mod.

**Comment by Shawiizz** [comment]
This issue is fixed since 2 days
