### ISSUE TITLE
[1.16.4] Crash minecolonies

### ISSUE THREAD

**Issue by Kennar** [Teneted/Tenet#683]
The server does not start when there is mod minecolonies on the server:

`
Description: Exception in server tick loop

java.lang.NullPointerException: Exception in server tick loop
	at com.minecolonies.api.compatibility.CompatibilityManager.isCompost(CompatibilityManager.java:273) ~[minecolonies:0.13.515-ALPHA] {re:classloading}
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174) ~[?:1.8.0_242] {}
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948) ~[?:1.8.0_242] {}
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482) ~[?:1.8.0_242] {}
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[?:1.8.0_242] {}
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[?:1.8.0_242] {}
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_242] {}
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566) ~[?:1.8.0_242] {}
	at com.minecolonies.api.compatibility.CompatibilityManager.discoverCompostableItems(CompatibilityManager.java:570) ~[minecolonies:0.13.515-ALPHA] {re:classloading}
	at com.minecolonies.api.compatibility.CompatibilityManager.discover(CompatibilityManager.java:216) ~[minecolonies:0.13.515-ALPHA] {re:classloading}
	at com.minecolonies.coremod.colony.ColonyManager.onWorldTick(ColonyManager.java:647) ~[minecolonies:0.13.515-ALPHA] {re:classloading}
	at com.minecolonies.coremod.event.FMLEventHandler.onWorldTick(FMLEventHandler.java:37) ~[minecolonies:0.13.515-ALPHA] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_359_FMLEventHandler_onWorldTick_WorldTickEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-3.0.5-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297) ~[eventbus-3.0.5-service.jar:?] {}
	at net.minecraftforge.fml.hooks.BasicEventHooks.onPreWorldTick(BasicEventHooks.java:95) ~[forge:?] {re:classloading}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1138) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:352) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:1046) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:879) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:268) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242] {}
`

**Comment by Mgazul** [comment]
#654 Same problem
