### ISSUE TITLE
[1.12.2] incompatibility with thaumic wands

### ISSUE THREAD

**Issue by xemnes** [Teneted/Tenet#684]
pretty much the title.

when thaumic wands is installed, whenever the wand is placed in the wand slot of the arcane crafter, it gets deleted.

this error appears in the console:

> 16.12 06:48:15 [Server] FATAL Error executing task
> 16.12 06:48:15 [Server] INFO java.util.concurrent.ExecutionException: java.lang.ArrayIndexOutOfBoundsException: 15
> 16.12 06:48:15 [Server] INFO at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_265]
> 16.12 06:48:15 [Server] INFO at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_265]
> 16.12 06:48:15 [Server] INFO at net.minecraft.util.Util.runTask(SourceFile:531) [h.class:?]
> 16.12 06:48:15 [Server] INFO at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:843) [MinecraftServer.class:?]
> 16.12 06:48:15 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:470) [nz.class:?]
> 16.12 06:48:15 [Server] INFO at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:781) [MinecraftServer.class:?]
> 16.12 06:48:15 [Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:627) [MinecraftServer.class:?]
> 16.12 06:48:15 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_265]
> 16.12 06:48:15 [Server] INFO Caused by: java.lang.ArrayIndexOutOfBoundsException: 15
> 16.12 06:48:15 [Server] INFO at java.util.Arrays$ArrayList.set(Arrays.java:3846) ~[?:1.8.0_265]
> 16.12 06:48:15 [Server] INFO at net.minecraft.util.NonNullList.set(SourceFile:51) ~[fi.class:?]
> 16.12 06:48:15 [Server] INFO at net.minecraft.inventory.InventoryCrafting.setInventorySlotContents(InventoryCrafting.java:148) ~[afy.class:?]
> 16.12 06:48:15 [Server] INFO at net.minecraft.inventory.Slot.putStack(Slot.java:70) ~[agr.class:?]
> 16.12 06:48:15 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.inventory.CraftInventoryView.setItem(CraftInventoryView.java:121) ~[CraftInventoryView.class:?]
> 16.12 06:48:15 [Server] INFO at net.minecraft.inventory.Container.slotClick(Container.java:322) ~[afr.class:?]
> 16.12 06:48:15 [Server] INFO at net.minecraft.network.NetHandlerPlayServer.processClickWindow(NetHandlerPlayServer.java:2071) ~[pa.class:?]
> 16.12 06:48:15 [Server] INFO at net.minecraft.network.play.client.CPacketClickWindow.processPacket(CPacketClickWindow.java:38) ~[lf.class:?]
> 16.12 06:48:15 [Server] INFO at net.minecraft.network.play.client.CPacketClickWindow.processPacket(CPacketClickWindow.java:12) ~[lf.class:?]
> 16.12 06:48:15 [Server] INFO at net.minecraft.network.PacketThreadUtil.lambda$checkThreadAndEnqueue$0(PacketThreadUtil.java:16) ~[hv.class:?]
> 16.12 06:48:15 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_265]
> 16.12 06:48:15 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_265]
> 16.12 06:48:15 [Server] INFO at net.minecraft.util.Util.runTask(SourceFile:529) ~[h.class:?]
> 16.12 06:48:15 [Server] INFO ... 5 more

**Comment by xemnes** [comment]
only just noticed the tag "more info needed" is used. what kinds of info would you like? not sure how to diagnose it further for you.
