### ISSUE TITLE
Server closed  forcibly

### ISSUE THREAD

**Issue by 4Seasons11** [Teneted/Tenet#685]
`Description: Exception ticking world

java.lang.NoClassDefFoundError: net/minecraft/world/World$3
	at net.minecraft.world.World.func_190524_a(World.java:740)
	at net.minecraft.world.World.func_175685_c(World.java:666)
	at net.minecraft.world.World.func_175722_b(World.java:615)
	at net.minecraft.world.World.markAndNotifyBlock(World.java:551)
	at net.minecraft.world.World.func_180501_a(World.java:531)
	at net.minecraft.block.BlockBush.func_176475_e(BlockBush.java:71)
	at net.minecraft.block.BlockBush.func_180650_b(BlockBush.java:60)
	at net.minecraft.block.BlockCrops.func_180650_b(BlockCrops.java:72)
	at net.minecraft.block.Block.func_180645_a(Block.java:517)
	at net.minecraft.world.WorldServer.func_147456_g(WorldServer.java:607)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:348)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:890)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:467)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:784)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:630)
	at java.lang.Thread.run(Unknown Source)`

**Comment by Shawiizz** [comment]
Provide Minecraft version and Mohist version please.

**Comment by Shawiizz** [comment]
Closing due to inactivity.
