### ISSUE TITLE
[Error] GriefDefender + FAWE/WE

### ISSUE THREAD

**Issue by Flashback083** [Teneted/Tenet#7]
Hey, with GriefDefender (world protection plugin + players claims) the plugin can save claim into schematic and rollback them with the state at creation when we abandon the claim
It use WE function for that, but its seems there is an error when the schematic is rollback, and im pretty sure it was working in 238c25d build 
I'm using latest (17c9f3b)
Log : https://gist.github.com/Flashback083/fc40bfbb9b8578077354da51c804ed84
im not sure if its really a WorldEdit issue, but yeah, i prefer to let you know
Thanks for the help !

**Comment by Flashback083** [comment]
Ah important detail... i get the error but the schematic SEEMS to be rollback correctly

**Comment by Mgazul** [comment]
Use the latest build test to see if the error still exists

**Comment by Mgazul** [comment]
Is this problem solved with the latest build? Still have errors?

**Comment by Zilacon** [comment]
The server does not get past this point with latest build.

```


 /'\_/`\          /\ \       __          /\ \__   
/\      \     ___ \ \ \___  /\_\     ____\ \ ,_\  
\ \ \__\ \   / __`\\ \  _ `\\/\ \   /',__\\ \ \/  
 \ \ \_/\ \ /\ \L\ \\ \ \ \ \\ \ \ /\__, `\\ \ \_ 
  \ \_\\ \_\\ \____/ \ \_\ \_\\ \_\\/\____/ \ \__\
   \/_/ \/_/ \/___/   \/_/\/_/ \/_/ \/___/   \/__/


                        -- Mohist Development Group

Mohist Starting...
Loading libraries, please wait...
Transforming Class [net.minecraft.block.Block], Method [getExtendedState]
Transforming net.minecraft.block.Block Finished.
[wizardry ASM] Successfully patched -> 'func_70091_d', 'move' with '(Lnet/minecraft/entity/MoverType;DDD)V'
[wizardry ASM] Successfully patched -> 'func_191986_a', 'travel' with '(FFF)V'
[wizardry ASM] Successfully patched -> 'func_70071_h_', 'onUpdate' with '()V'
[wizardry ASM] Successfully patched -> 'func_70071_h_', 'onUpdate' with '()V'
A problem occurred running the Server launcher.
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at red.mohist.Mohist.main(Mohist.java:110)
Caused by: net.minecraftforge.fml.relauncher.FMLSecurityManager$ExitTrappedException
	at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:49)
	at java.lang.SecurityManager.checkExit(SecurityManager.java:761)
	at java.lang.Runtime.exit(Runtime.java:107)
	at java.lang.System.exit(System.java:344)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:138)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	... 5 more
APOC Server has shutdown! Restarting in 30 seconds...
```
@Mgazul

**Comment by Flashback083** [comment]
Its solved ! I lock, thanks for your work !
