### ISSUE TITLE
Invalid id 4096 - Server crashes on startup

### ISSUE THREAD

**Issue by rdmchr** [Teneted/Tenet#712]
My server crashes with the following exception
```
[23:03:37 ERROR]: Exception caught during firing event net.minecraftforge.event.RegistryEvent$Register@2eff1bcb:
 java.lang.RuntimeException: Invalid id 4096 - maximum id range exceeded.
        at net.minecraftforge.registries.ForgeRegistry.add(ForgeRegistry.java:291) ~[ForgeRegistry.class:1.12.2-c950429]
        at net.minecraftforge.registries.ForgeRegistry.add(ForgeRegistry.java:277) ~[ForgeRegistry.class:1.12.2-c950429]
        at net.minecraftforge.registries.ForgeRegistry.register(ForgeRegistry.java:109) ~[ForgeRegistry.class:1.12.2-c950429]
        at hellfirepvp.astralsorcery.common.registry.internal.PrimerEventHandler.lambda$fillRegistry$0(PrimerEventHandler.java:104) ~[PrimerEventHandler.class:?]
        at java.lang.Iterable.forEach(Iterable.java:75) ~[?:1.8.0_252]
        at hellfirepvp.astralsorcery.common.registry.internal.PrimerEventHandler.fillRegistry(PrimerEventHandler.java:104) ~[PrimerEventHandler.class:?]
        at hellfirepvp.astralsorcery.common.registry.internal.PrimerEventHandler.registerBlocks(PrimerEventHandler.java:59) ~[PrimerEventHandler.class:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1129_PrimerEventHandler_registerBlocks_Register.invoke(.dynamic) ~[?:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:96) ~[ASMEventHandler.class:1.12.2-c950429]
        at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:143) ~[EventBus$1.class:1.12.2-c950429]
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:186) [EventBus.class:1.12.2-c950429]
        at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:855) [GameData.class:1.12.2-c950429]
        at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:633) [Loader.class:1.12.2-c950429]
        at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:102) [FMLServerHandler.class:1.12.2-c950429]
        at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:329) [FMLCommonHandler.class:1.12.2-c950429]
        at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:171) [nz.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:593) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
[23:03:37 ERROR]: 499: net.minecraftforge.fml.common.eventhandler.EventBus$1@659057ab
[23:03:37 ERROR]: 500: net.minecraftforge.fml.common.eventhandler.EventBus$1@7b5df680
[23:03:37 ERROR]: 501: net.minecraftforge.fml.common.eventhandler.EventBus$1@5d7e436c
[23:03:37 ERROR]: 502: net.minecraftforge.fml.common.eventhandler.EventBus$1@7f249b7e
[23:03:37 ERROR]: 503: net.minecraftforge.fml.common.eventhandler.EventBus$1@18eeb63e
[23:03:37 ERROR]: 504: net.minecraftforge.fml.common.eventhandler.EventBus$1@c93ba55
[23:03:37 ERROR]: 505: net.minecraftforge.fml.common.eventhandler.EventBus$1@23d9fd88
[23:03:37 ERROR]: 506: net.minecraftforge.fml.common.eventhandler.EventBus$1@787d6de6
[23:03:37 ERROR]: 507: net.minecraftforge.fml.common.eventhandler.EventBus$1@15cf7b91
[23:03:37 ERROR]: 508: net.minecraftforge.fml.common.eventhandler.EventBus$1@41f3a6f
[23:03:37 ERROR]: 509: net.minecraftforge.fml.common.eventhandler.EventBus$1@68c6b2d9
[23:03:37 ERROR]: 510: net.minecraftforge.fml.common.eventhandler.EventBus$1@7b47e07a
[23:03:37 ERROR]: 511: net.minecraftforge.fml.common.eventhandler.EventBus$1@15ba0f70
[23:03:37 ERROR]: 512: net.minecraftforge.fml.common.eventhandler.EventBus$1@688b93ea
[23:03:37 ERROR]: 513: net.minecraftforge.fml.common.eventhandler.EventBus$1@3506b458
[23:03:37 ERROR]: 514: net.minecraftforge.fml.common.eventhandler.EventBus$1@7106d6b2
[23:03:37 ERROR]: 515: net.minecraftforge.fml.common.eventhandler.EventBus$1@3482866d
[23:03:37 ERROR]: 516: net.minecraftforge.fml.common.eventhandler.EventBus$1@a247d4
[23:03:37 ERROR]: 517: net.minecraftforge.fml.common.eventhandler.EventBus$1@8687ec
[23:03:37 ERROR]: 518: net.minecraftforge.fml.common.eventhandler.EventBus$1@47f27208
[23:03:37 ERROR]: 519: net.minecraftforge.fml.common.eventhandler.EventBus$1@67e33575
[23:03:37 ERROR]: 520: net.minecraftforge.fml.common.eventhandler.EventBus$1@75ed42ba
[23:03:37 ERROR]: 521: net.minecraftforge.fml.common.eventhandler.EventBus$1@4160020c
[23:03:37 ERROR]: 522: net.minecraftforge.fml.common.eventhandler.EventBus$1@15564a1a
[23:03:37 ERROR]: 523: LOW
[23:03:37 ERROR]: 524: net.minecraftforge.fml.common.eventhandler.EventBus$1@6b608d58
[23:03:37 ERROR]: 525: net.minecraftforge.fml.common.eventhandler.EventBus$1@7407fa1c
[23:03:37 ERROR]: 526: net.minecraftforge.fml.common.eventhandler.EventBus$1@35b6e6f2
[23:03:37 ERROR]: 527: net.minecraftforge.fml.common.eventhandler.EventBus$1@12976cc4
[23:03:37 ERROR]: 528: net.minecraftforge.fml.common.eventhandler.EventBus$1@7d723983
[23:03:37 ERROR]: 529: LOWEST
[23:03:37 ERROR]: 530: net.minecraftforge.fml.common.eventhandler.EventBus$1@36eefb2b
[23:03:37 ERROR]: 531: net.minecraftforge.fml.common.eventhandler.EventBus$1@346d0a72
[23:03:37 ERROR]: 532: net.minecraftforge.fml.common.eventhandler.EventBus$1@1db5b177
[23:03:37 ERROR]: 533: net.minecraftforge.fml.common.eventhandler.EventBus$1@71e72d63
[23:03:37 ERROR]: 534: net.minecraftforge.fml.common.eventhandler.EventBus$1@3091a7d7
[23:03:37 ERROR]: 535: net.minecraftforge.fml.common.eventhandler.EventBus$1@6cf3152d
[23:03:37 ERROR]: 536: net.minecraftforge.fml.common.eventhandler.EventBus$1@5c7d3fcd
[23:03:37 ERROR]: 537: net.minecraftforge.fml.common.eventhandler.EventBus$1@14398d14
[23:03:37 ERROR]: 538: net.minecraftforge.fml.common.eventhandler.EventBus$1@29ab2f5b
[23:03:37 ERROR]: 539: net.minecraftforge.fml.common.eventhandler.EventBus$1@5d851d3e
[23:03:37 ERROR]: 540: net.minecraftforge.fml.common.eventhandler.EventBus$1@68b3d214
[23:03:37 ERROR]: 541: net.minecraftforge.fml.common.eventhandler.EventBus$1@30baa33b
[23:03:37 ERROR]: 542: net.minecraftforge.fml.common.eventhandler.EventBus$1@409b8380
[23:03:37 ERROR]: 543: net.minecraftforge.fml.common.eventhandler.EventBus$1@35021a40
[23:03:37 ERROR]: 544: net.minecraftforge.fml.common.eventhandler.EventBus$1@43d74d86
[23:03:37 ERROR]: 545: net.minecraftforge.fml.common.eventhandler.EventBus$1@26918dbc
[23:03:37 ERROR]: 546: net.minecraftforge.fml.common.eventhandler.EventBus$1@3a0a8d6d
[23:03:37 ERROR]: 547: net.minecraftforge.fml.common.eventhandler.EventBus$1@1fff4076
[23:03:37 ERROR]: 548: net.minecraftforge.fml.common.eventhandler.EventBus$1@663d8572
[23:03:37 ERROR]: 549: net.minecraftforge.fml.common.eventhandler.EventBus$1@4c6b1864
[23:03:37 ERROR]: 550: net.minecraftforge.fml.common.eventhandler.EventBus$1@22648561
[23:03:37 ERROR]: Encountered an unexpected exception
[23:03:37 WARN]: Failed to identify net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1129_PrimerEventHandler_registerBlocks_Register (untransformed name: net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1129_PrimerEventHandler_registerBlocks_Register)
[23:03:37 ERROR]: This crash report has been saved to: D:\MC Eternal - Copy\.\crash-reports\crash-2020-12-25_23.03.37-server.txt
[23:03:37 INFO]: Stopping server
[23:03:37 INFO]: Saving worlds
[23:03:37 WARN]: Exception in thread "Server thread"
[23:03:37 WARN]: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Applied Energistics 2 (appliedenergistics2)
[23:03:37 WARN]: Caused by: java.lang.NullPointerException
[23:03:37 WARN]:        at appeng.core.AppEng.serverStopped(AppEng.java:271)
[23:03:37 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[23:03:37 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[23:03:37 WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[23:03:37 WARN]:        at java.lang.reflect.Method.invoke(Method.java:498)
[23:03:37 WARN]:        at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:632)
[23:03:37 WARN]:        at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
[23:03:37 WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[23:03:37 WARN]:        at java.lang.reflect.Method.invoke(Method.java:498)
[23:03:37 WARN]:        at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
[23:03:37 WARN]:        at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
[23:03:37 WARN]:        at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
[23:03:37 WARN]:        at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
[23:03:37 WARN]:        at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
[23:03:37 WARN]:        at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
[23:03:37 WARN]:        at com.google.common.eventbus.EventBus.post(EventBus.java:217)
[23:03:37 WARN]:        at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:215)
[23:03:37 WARN]:        at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:193)
[23:03:37 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[23:03:37 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[23:03:37 WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[23:03:37 WARN]:        at java.lang.reflect.Method.invoke(Method.java:498)
[23:03:37 WARN]:        at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
[23:03:37 WARN]:        at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
[23:03:37 WARN]:        at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
[23:03:37 WARN]:        at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
[23:03:37 WARN]:        at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
[23:03:37 WARN]:        at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
[23:03:37 WARN]:        at com.google.common.eventbus.EventBus.post(EventBus.java:217)
[23:03:37 WARN]:        at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:132)
[23:03:37 WARN]:        at net.minecraftforge.fml.common.Loader.serverStopped(Loader.java:856)
[23:03:37 WARN]:        at net.minecraftforge.fml.common.FMLCommonHandler.handleServerStopped(FMLCommonHandler.java:508)
[23:03:37 WARN]:        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:685)
[23:03:37 WARN]:        at java.lang.Thread.run(Thread.java:748)
```
Also another error without AE2 https://hastebin.com/ovunuziwuj.yaml
This is the crash report that is generated: https://hastebin.com/upiyizivak.sql

**Comment by Trackhe** [comment]
You need https://www.curseforge.com/minecraft/mc-mods/jeid
because your mods are registrying more blocks then 4096.
please close the issue if it helps.

MFG Trackhe

**Comment by rdmchr** [comment]
Fixed. Thank you very much.
