### ISSUE TITLE
AE2 throws exception on first startup

### ISSUE THREAD

**Issue by rdmchr** [Teneted/Tenet#713]
immediately after startup, I get this error:

```
[02:39:43 INFO]: Finished discovering compostables
[02:39:43 INFO]: Finished discovering compostables
[02:39:43 INFO]: Finished discovering lucky oreBlocks
[02:39:43 INFO]: Finished initiating sifter config
[02:39:43 INFO]: Finished discovering food
[02:39:43 INFO]: Finished discovering fuel
[02:39:43 WARN]: Enchantment: minecraft:sweeping_edge doesn't exist!
[02:39:43 WARN]: Enchantment: minecraft:sweeping_edge doesn't exist!
[02:39:43 WARN]: Enchantment: minecraft:sweeping_edge doesn't exist!
[02:39:43 WARN]: Enchantment: minecraft:sweeping_edge doesn't exist!
[02:39:43 WARN]: Enchantment: minecraft:sweeping_edge doesn't exist!
[02:39:43 WARN]: Done with enchantments
[02:39:44 INFO]: Unloading dimension 684
[02:39:44 INFO]: Unloading dimension 685
[02:39:44 INFO]: Unloading dimension 686
[02:39:44 INFO]: Unloading dimension 687
[02:39:44 INFO]: Unloading dimension 688
[02:39:44 INFO]: Unloading dimension 66
[02:39:44 INFO]: Unloading dimension -2
[02:39:44 INFO]: No FluxNetworkData found
[02:39:44 INFO]: FluxNetworkData has been successfully loaded
[02:39:47 INFO]: ThreadedAnvilChunkStorage (world): All chunks are saved
[02:39:47 INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[02:39:47 INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[02:39:47 INFO]: ThreadedAnvilChunkStorage (DIM144): All chunks are saved
[02:39:47 INFO]: ThreadedAnvilChunkStorage (DIM144): All chunks are saved
[02:39:47 INFO]: ThreadedAnvilChunkStorage (DIM-9999): All chunks are saved
[02:39:47 INFO]: ThreadedAnvilChunkStorage (DIM2): All chunks are saved
[02:39:48 INFO]: Deleted backup .\backups\world\Backup--world--2020-12-25--19-44.zip.
[02:39:49 OFF]: Message to players; Message: Server Backup done!
[02:39:49 INFO]: [AromaBackup] Server Backup done!
[02:39:50 INFO]: Unloading dimension 144
[02:39:53 ERROR]: Exception caught during firing event net.minecraftforge.event.entity.EntityJoinWorldEvent@73e6bcef:
 java.util.regex.PatternSyntaxException: Dangling meta character '*' near index 0
*salt*
^
        at java.util.regex.Pattern.error(Pattern.java:1969) ~[?:1.8.0_252]
        at java.util.regex.Pattern.sequence(Pattern.java:2137) ~[?:1.8.0_252]
        at java.util.regex.Pattern.expr(Pattern.java:2010) ~[?:1.8.0_252]
        at java.util.regex.Pattern.compile(Pattern.java:1702) ~[?:1.8.0_252]
        at java.util.regex.Pattern.<init>(Pattern.java:1352) ~[?:1.8.0_252]
        at java.util.regex.Pattern.compile(Pattern.java:1028) ~[?:1.8.0_252]
        at java.util.regex.Pattern.matches(Pattern.java:1133) ~[?:1.8.0_252]
        at mrriegel.instantunify.InstantUnify.lambda$replaceOptional$6(InstantUnify.java:174) ~[InstantUnify.class:?]
        at java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90) ~[?:1.8.0_252]
        at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1359) ~[?:1.8.0_252]
        at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126) ~[?:1.8.0_252]
        at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:499) ~[?:1.8.0_252]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:486) ~[?:1.8.0_252]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[?:1.8.0_252]
        at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230) ~[?:1.8.0_252]
        at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196) ~[?:1.8.0_252]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_252]
        at java.util.stream.ReferencePipeline.anyMatch(ReferencePipeline.java:516) ~[?:1.8.0_252]
        at mrriegel.instantunify.InstantUnify.replaceOptional(InstantUnify.java:174) ~[InstantUnify.class:?]
        at mrriegel.instantunify.InstantUnify.replace(InstantUnify.java:157) ~[InstantUnify.class:?]
        at mrriegel.instantunify.InstantUnify.spawn(InstantUnify.java:110) ~[InstantUnify.class:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_770_InstantUnify_spawn_EntityJoinWorldEvent.invoke(.dynamic) ~[?:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:96) ~[ASMEventHandler.class:1.12.2-c950429]
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:186) [EventBus.class:1.12.2-c950429]
        at net.minecraft.world.World.addEntity(World.java:1544) [amu.class:?]
        at net.minecraft.world.WorldServer.addEntity(WorldServer.java:1352) [oo.class:?]
        at net.minecraft.world.WorldServer.func_72838_d(WorldServer.java:1346) [oo.class:?]
        at net.minecraft.inventory.InventoryHelper.func_180173_a(SourceFile:46) [ty.class:?]
        at net.minecraft.inventory.InventoryHelper.func_180174_a(SourceFile:29) [ty.class:?]
        at net.minecraft.inventory.InventoryHelper.func_180175_a(SourceFile:15) [ty.class:?]
        at net.minecraft.block.BlockChest.func_180663_b(BlockChest.java:406) [api.class:?]
        at net.minecraft.world.chunk.Chunk.func_177436_a(Chunk.java:607) [axw.class:?]
        at net.minecraft.world.World.func_180501_a(World.java:506) [amu.class:?]
        at net.minecraft.world.World.func_175656_a(World.java:588) [amu.class:?]
        at appeng.worldgen.meteorite.ChunkOnly.setBlock(ChunkOnly.java:87) [ChunkOnly.class:?]
        at appeng.worldgen.meteorite.MeteoriteBlockPutter.put(MeteoriteBlockPutter.java:38) [MeteoriteBlockPutter.class:?]
        at appeng.worldgen.MeteoritePlacer.placeCrater(MeteoritePlacer.java:199) [MeteoritePlacer.class:?]
        at appeng.worldgen.MeteoritePlacer.spawnMeteorite(MeteoritePlacer.java:149) [MeteoritePlacer.class:?]
        at appeng.worldgen.MeteoriteWorldGen$MeteoriteSpawn.call(MeteoriteWorldGen.java:134) [MeteoriteWorldGen$MeteoriteSpawn.class:?]
        at appeng.hooks.TickHandler.processQueue(TickHandler.java:272) [TickHandler.class:?]
        at appeng.hooks.TickHandler.onTick(TickHandler.java:240) [TickHandler.class:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1771_TickHandler_onTick_TickEvent.invoke(.dynamic) [?:1.12.2-c950429]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:96) [ASMEventHandler.class:1.12.2-c950429]
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:186) [EventBus.class:1.12.2-c950429]
        at net.minecraftforge.fml.common.FMLCommonHandler.onPreWorldTick(FMLCommonHandler.java:283) [FMLCommonHandler.class:1.12.2-c950429]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:884) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:471) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:781) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:627) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
[02:39:53 ERROR]: Index: 55 Listeners:
[02:39:53 ERROR]: 0: HIGHEST
[02:39:53 ERROR]: 1: ASM: net.minecraftforge.common.ForgeInternalHandler@5d84d6a3 onEntityJoinWorld(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
[02:39:53 ERROR]: 2: ASM: mcjty.incontrol.ForgeEventHandlers@1a272560 onEntityJoinWorldLast(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
[02:39:53 ERROR]: 3: ASM: com.inventorypets.events.SunPetSpawnHandler@7fc4e213 onEntityJoinWorld(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
[02:39:53 ERROR]: 4: ASM: hellfirepvp.astralsorcery.common.util.BlockDropCaptureAssist@76464210 onDrop(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
[02:39:53 ERROR]: 5: HIGH
[02:39:53 ERROR]: 6: ASM: hellfirepvp.astralsorcery.common.constellation.perk.attribute.type.AttributeCritChance@dc154bd7 onArrowCt(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
[02:39:53 ERROR]: 7: NORMAL
[02:39:53 ERROR]: 8: ASM: class crazypants.enderio.base.handler.darksteel.PlayerAOEAttributeHandler handleJoin(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
[02:39:53 ERROR]: 9: ASM: class c4.champions.common.capability.CapabilityChampionship$EventHandler entityJoin(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
[02:39:53 ERROR]: 10: ASM: class electroblob.wizardry.data.WizardData onEntityJoinWorld(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
[02:39:53 ERROR]: 11: ASM: class electroblob.wizardry.entity.projectile.EntityLargeMagicFireball onEntityJoinWorldEvent(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
[02:39:53 ERROR]: 12: ASM: interface electroblob.wizardry.enchantment.Imbuement onEntityJoinWorld(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
[02:39:53 ERROR]: 13: ASM: class electroblob.wizardry.entity.projectile.EntityMagicFireball onEntityJoinWorldEvent(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
[02:39:53 ERROR]: 14: ASM: class com.feed_the_beast.ftbutilities.handlers.FTBUtilitiesWorldEventHandler onMobSpawned(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
[02:39:53 ERROR]: 15: ASM: class amerifrance.guideapi.util.EventHandler onPlayerJoinWorld(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
[02:39:53 ERROR]: 16: ASM: class flaxbeard.immersivepetroleum.common.EventHandler onEntityJoiningWorld(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
[02:39:53 ERROR]: 17: ASM: com.minecolonies.coremod.event.EventHandler@2be765e3 onEvent(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
[02:39:53 ERROR]: 18: ASM: baubles.common.event.EventHandlerEntity@6dbd638e playerJoin(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
[02:39:53 ERROR]: 19: ASM: INSTANCE onJoinWorld(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
[02:39:53 ERROR]: 20: ASM: com.github.alexthe666.iceandfire.event.ServerEvents@24175cae onEntityJoinWorld(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
[02:39:53 ERROR]: 21: ASM: hellfirepvp.astralsorcery.common.constellation.perk.attribute.type.AttributeArrowSpeed@b96d0033 onArrowFire(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
[02:39:53 ERROR]: 22: ASM: jds.bibliocraft.events.EventSpawn@3a1ad37a onSpawn(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
[02:39:53 ERROR]: 23: ASM: biomesoplenty.common.handler.SheepEventHandler@19b758a0 onEntityJoin(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
[02:39:53 ERROR]: 24: ASM: class buildcraft.lib.BCLibEventDist onEntityJoinWorld(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
[02:39:53 ERROR]: 25: ASM: INSTANCE onEntityJoinWorld(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
[02:39:53 ERROR]: 26: ASM: forestry.core.EventHandlerCore@45e0b758 handleVillagerAI(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
[02:39:53 ERROR]: 27: ASM: svenhjol.charm.enchanting.feature.Magnetic@6aac4d61 onEntityCreate(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
[02:39:53 ERROR]: 28: ASM: svenhjol.charm.tweaks.feature.RemoveNitwits@19195b07 onVillagerSpawn(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
[02:39:53 ERROR]: 29: ASM: com.blamejared.clumps.events.CommonEventHandler@6fa6d02e updateEntities(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
[02:39:53 ERROR]: 30: ASM: doggytalents.handler.EntitySpawn@5574c0e6 onEntitySpawn(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
[02:39:53 ERROR]: 31: ASM: pegbeard.dungeontactics.handlers.DTEventHandler@4c938170 onJoinWorld(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
[02:39:53 ERROR]: 32: ASM: class erebus.core.capabilities.base.EntityCapabilityHandler onPlayerJoin(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
[02:39:53 ERROR]: 33: ASM: com.phylogeny.extrabitmanipulation.armor.capability.ChiseledArmorSlotsEventHandler@6b24c3c6 markPlayerSlotsDirty(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
[02:39:53 ERROR]: 34: ASM: com.rwtema.extrautils2.items.DemonicIngotHandler@709987cf onJoin(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
[02:39:53 ERROR]: 35: ASM: com.rwtema.extrautils2.blocks.BlockCursedEarth$EventHandler@219c87f1 spawnInWorld(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
[02:39:53 ERROR]: 36: ASM: net.blay09.mods.farmingforblockheads.ZombieKillMerchantHandler@432f9742 onZombieSpawn(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
[02:39:53 ERROR]: 37: ASM: me.ichun.mods.ichunutil.common.core.event.EventHandlerServer@2ac50e7b onEntitySpawn(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
[02:39:53 ERROR]: 38: ASM: baguchan.hunterillager.event.EntityEventHandler@39592d4a onEntityJoin(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
[02:39:53 ERROR]: 39: ASM: levelup2.event.CombatSkillHandler@3df567f8 onArrowLoose(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
[02:39:53 ERROR]: 40: ASM: class mob_grinding_utils.capability.base.EntityCapabilityHandler onPlayerJoin(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
[02:39:53 ERROR]: 41: ASM: mekanism.common.item.ItemBlockCardboardBox@31341690 onEntitySpawn(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
[02:39:53 ERROR]: 42: ASM: class com.enderio.core.common.handlers.XPBoostHandler handleArrowFire(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
[02:39:53 ERROR]: 43: ASM: hellfirepvp.astralsorcery.common.event.listener.EventHandlerEntity@fd12244 onSpawnDropCloud(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
[02:39:53 ERROR]: 44: ASM: class com.rwtema.careerbees.effects.EffectDigging captureStacks(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
[02:39:53 ERROR]: 45: ASM: c4.champions.common.affix.AffixEvents@7d468353 onLivingJoinWorld(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
[02:39:53 ERROR]: 46: ASM: com.lothrazar.cyclicmagic.event.EventPlayerData@4a76e085 onJoinWorld(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
[02:39:53 ERROR]: 47: ASM: Block{cyclicmagic:imbuer} onJoinWorld(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
[02:39:53 ERROR]: 48: ASM: com.Fishmod.mod_LavaCow.util.ModEventHandler@10726619 onEntityJoinWorld(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
[02:39:53 ERROR]: 49: ASM: blusunrize.immersiveengineering.common.EventHandler@23a6a51c onEntityJoiningWorld(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
[02:39:53 ERROR]: 50: ASM: journeymap.server.events.ForgeEvents@12e99d3 onEntityJoinWorldEvent(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
[02:39:53 ERROR]: 51: ASM: com.builtbroken.ai.improvements.AIImprovements@2c67ebd4 onEntityJoinWorld(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
[02:39:53 ERROR]: 52: ASM: com.rwtema.extrautils2.villagers.EntityAINinjaPoof$Handler@7fd5d567 a(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
[02:39:53 ERROR]: 53: ASM: class com.rwtema.extrautils2.dimensions.workhousedim.WorldProviderSpecialDim onJoin(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
[02:39:53 ERROR]: 54: LOWEST
[02:39:53 ERROR]: 55: ASM: class mrriegel.instantunify.InstantUnify spawn(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
[02:39:53 ERROR]: 56: ASM: hellfirepvp.astralsorcery.common.constellation.perk.attribute.type.AttributeCritMultiplier@8bcd7c54 onArrowCt(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
[02:39:53 ERROR]: 57: ASM: fluxnetworks.common.CommonProxy@76cbd13c onEntityAdded(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
[02:39:53 ERROR]: 58: ASM: me.ichun.mods.hats.common.core.EventHandlerServer@74a214f4 onEntitySpawn(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
[02:39:53 ERROR]: 59: ASM: mcjty.incontrol.ForgeEventHandlers@1a272560 onEntityJoinWorld(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
```

**Comment by ghost** [comment]
Seems to be a conflict between InstantUnify and a meteorite. Got more than 1 meteorite?

**Comment by rdmchr** [comment]
I have AE2 installed which spawns some kind of meteorite. Could that cause the issue?
Also, in that case, is there any way to resolve this other than just remove InstantUnify?

**Comment by rdmchr** [comment]
I did some more investigating and found out, that the error only seems to occur when the server is generating a completely new world. This time the server even crashed after the error, but when I restarted the server it was fine and there was no error.

**Comment by Romaindu35** [comment]
This issue was open long time ago, this bug can be fixed now, if the bug is always here, please open new issue.
