### ISSUE TITLE
[1.16.4] Failure to find/write

### ISSUE THREAD

**Issue by M-AlNoaimi** [Teneted/Tenet#736]
Hi,
This is quite similar to this issue #734. However with some playing around it seems to only show up during the first startup of Mohist. I tested out with a old version which was build 170 and it kept the DIM folders outside of the world but now that's fixed I would assume. 
I'm not too sure why this is happening but could be the way it tries to access that specific directory. It's important to mention that this didn't exist at all from builds 203-210.

<details>
  <summary>Startup Logs</summary>

  ```
 [Server thread/WARN] [org.bukkit.craftbukkit.v1_16_R3.util.WorldUUID/]: Failed to write ./world/DIM-1/uid.dat
java.io.FileNotFoundException: ./world/DIM-1/uid.dat (No such file or directory)
	at java.io.FileOutputStream.open0(Native Method) ~[?:1.8.0_275]
	at java.io.FileOutputStream.open(FileOutputStream.java:270) ~[?:1.8.0_275]
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213) ~[?:1.8.0_275]
	at java.io.FileOutputStream.<init>(FileOutputStream.java:162) ~[?:1.8.0_275]
	at org.bukkit.craftbukkit.v1_16_R3.util.WorldUUID.getUUID(WorldUUID.java:42) ~[forge:?]
	at net.minecraft.world.server.ServerWorld.<init>(ServerWorld.java:186) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240787_a_(MinecraftServer.java:431) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240800_l__(MinecraftServer.java:363) ~[?:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:217) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:731) ~[?:?]
	at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:276) ~[?:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275]
  ```
</details>

However this could also be an issue with having Mohist inside a container in general, I can do more testing if necessary, let me know.

**Comment by joaoespanhol** [comment]
your problem is exactly the same as mine. #734

**Comment by M-AlNoaimi** [comment]
@joaoespanhol Yeah I know, however I'm getting this only on initial startup. Are you getting that message only then aswell? Or while the server is running?

**Comment by joaoespanhol** [comment]
> @joaoespanhol Yeah I know, however I'm getting this only on initial startup. Are you getting that message only then aswell? Or while the server is running?

same problem.
i0m getting this only on initial startup.

**Comment by M-AlNoaimi** [comment]
Ah I see, then I guess this is safe to close. I thought you got that error while the server was running, my bad :)
