### ISSUE TITLE
[1.16.4] Commands from WE mod are 'unknown'

### ISSUE THREAD

**Issue by KR33PYK1NG** [Teneted/Tenet#748]
Any command from the mod is shown as 'Unknown command' when used.
Tab-completion, though, works as expected:
![issue](https://user-images.githubusercontent.com/75280223/103484465-125d4100-4e00-11eb-9d1f-ac43a1f33ae9.png)

Versions used:
mohist-1.16.4-239-server
worldedit-forge-mc1.16.3-7.2.1-dist

**Comment by SSKirillSS** [comment]
Can confirm, same issue.

**Comment by joaoespanhol** [comment]
> Can confirm, same issue.
same problem for plugin.

**Comment by joaoespanhol** [comment]
Mohist/src/main/java/org/bukkit/plugin/java/JavaPluginLoader.java
org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:319) ~[forge:?] {re:classloading}

Mohist/src/main/java/org/bukkit/plugin/RegisteredListener.java
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[forge:?] {re:classloading}

Mohist/src/main/java/org/bukkit/plugin/SimplePluginManager.java

        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[forge:?] {re:classloading}
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:574) ~[forge:?] {re:classload
		
		
Mohist/src/main/java/org/bukkit/craftbukkit/v1_16_R3/event/CraftEventFactory.java
  at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:428) ~[forge:?] {re:classloading}
        at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:395) ~[forge:?] {re:classloading}

**Comment by Mgazul** [comment]
Currently there is no compatibility with plug-ins, so these problems are known, and there is no need to repeat errors about plug-ins (called spam)

**Comment by joaoespanhol** [comment]
> Atualmente não há compatibilidade com plug-ins, portanto, esses problemas são conhecidos e não há necessidade de repetir erros sobre plug-ins (chamados de spam)

found that the worldedit mod has the same behavior as the plugin

**Comment by Mgazul** [comment]
Because the forge command is not registered to bukkit

**Comment by joaoespanhol** [comment]
close ticket because is work 1.16.5-306



> Because the forge command is not registered to bukkit

close ticket because is work 1.16.5-306

**Comment by Mgazul** [comment]
#865
