### ISSUE TITLE
[1.16.4] world edit does not load correctly (plugin)

### ISSUE THREAD

**Issue by KaBoom13** [Teneted/Tenet#754]
When I try to load the worldedit plugin it does not load correctly, I tested on the version available on the website from the engine and the latest version which is available 7.2.1
I tested on the plugin itself and nothing else.
below are the console logs from these 2 tested versions:

[12:57:43] [Server thread/ERROR] [Minecraft/]: Error occurred while enabling WorldEdit v7.2.1+299386a (Is it up to date?)
java.lang.IllegalStateException: key 'minecraft:minecraft' already has an associated entity type
	at com.google.common.base.Preconditions.checkState(Preconditions.java:721) ~[server-1.16.4-20201102.104115-extra.jar:?]
	at com.sk89q.worldedit.registry.Registry.register(Registry.java:56) ~[?:?]
	at com.sk89q.worldedit.registry.NamespacedRegistry.register(NamespacedRegistry.java:55) ~[?:?]
	at com.sk89q.worldedit.bukkit.WorldEditPlugin.initializeRegistries(WorldEditPlugin.java:238) ~[?:?]
	at com.sk89q.worldedit.bukkit.WorldEditPlugin.onEnable(WorldEditPlugin.java:165) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[forge:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:351) ~[forge:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[forge:?]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:401) ~[forge:1.16.4-241]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:315) ~[forge:1.16.4-241]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:209) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:731) ~[?:?]
	at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:276) ~[?:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_271]

[12:45:08 ERROR]: Error occurred while enabling WorldEdit v6.1.9-0.3-SNAPSHOT (Is it up to date?)
java.lang.IllegalArgumentException: Channel must contain : separator (attempted to use WECUI)
        at org.bukkit.plugin.messaging.StandardMessenger.validateAndCorrectChannel(StandardMessenger.java:503) ~[forge:?] {re:classloading}
        at org.bukkit.plugin.messaging.StandardMessenger.registerIncomingPluginChannel(StandardMessenger.java:216) ~[forge:?] {re:classloading}
        at com.sk89q.worldedit.bukkit.WorldEditPlugin.onEnable(WorldEditPlugin.java:111) ~[?:?] {re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading}
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[forge:?] {re:classloading}
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:351) ~[forge:?] {re:classloading}
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[forge:?] {re:classloading}        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:401) ~[forge:1.16.4-241] {re:classloading}
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:315) ~[forge:1.16.4-241] {re:classloading}
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.reload(CraftServer.java:787) ~[forge:1.16.4-241] {re:classloading}
        at org.bukkit.Bukkit.reload(Bukkit.java:653) ~[forge:?] {re:classloading}
        at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:27) ~[forge:?] {re:classloading}
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:160) ~[forge:?] {re:classloading}
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:669) ~[forge:1.16.4-241] {re:classloading}
        at net.minecraft.network.play.ServerPlayNetHandler.func_147361_d(ServerPlayNetHandler.java:1799) ~[?:?] {re:classloading}
        at net.minecraft.network.play.ServerPlayNetHandler.func_147354_a(ServerPlayNetHandler.java:1646) ~[?:?] {re:classloading}
        at net.minecraft.network.play.client.CChatMessagePacket.func_148833_a(CChatMessagePacket.java:38) ~[?:?] {re:classloading}
        at net.minecraft.network.play.client.CChatMessagePacket.func_148833_a(CChatMessagePacket.java:8) ~[?:?] {re:classloading}
        at net.minecraft.network.PacketThreadUtil.lambda$checkThreadAndEnqueue$0(PacketThreadUtil.java:22) ~[?:?] {re:classloading}
        at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?] {re:classloading}
        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(ThreadTaskExecutor.java:136) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?] {re:classloading}
        at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:876) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:183) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(ThreadTaskExecutor.java:109) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:859) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:853) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(ThreadTaskExecutor.java:119) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:839) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:773) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:276) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_271] {}

written with google translate

**Comment by SSKirillSS** [comment]
![image](https://user-images.githubusercontent.com/38190325/103540854-75f07880-4eab-11eb-960b-84809c57574c.png)

**Comment by joaoespanhol** [comment]
close ticket because is work 1.16.5-306

@Mgazul

**Comment by RedstonedLife** [comment]
@KR33PY re-open this issue, The issue still exists
I use FAWE downloaded from https://mohist.mc
```[00:35:44] [Server thread/TRACE] [net.minecraftforge.fml.loading.ModJarURLHandler/CORE]: Loading modjar URL modjar://forge/org/bukkit/inventory/EquipmentSlot.class got resource org/bukkit/inventory/EquipmentSlot.class true
[00:35:44] [Server thread/INFO] [com.sk89q.worldedit.bukkit.WorldEditPlugin/]: [WorldEdit] Enabling WorldEdit v6.1.9;caf0ad9
[00:35:44] [Server thread/WARN] [com.sk89q.worldedit.bukkit.WorldEditPlugin/]: [WorldEdit] Loaded class ru.tehkode.permissions.PermissionManager from PermissionsEx v1.23.4 which is not a depend, softdepend or loadbefore of this plugin.
[00:35:44] [Server thread/INFO] [com.sk89q.wepif.PermissionsResolverManager/]: WEPIF: Using the Bukkit Permissions API.
[00:35:44] [Server thread/ERROR] [Minecraft/]: Error occurred while enabling WorldEdit v6.1.9;caf0ad9 (Is it up to date?)
java.lang.IllegalArgumentException: Channel must contain : separator (attempted to use WECUI)
	at org.bukkit.plugin.messaging.StandardMessenger.validateAndCorrectChannel(StandardMessenger.java:503) ~[forge:?]
	at org.bukkit.plugin.messaging.StandardMessenger.registerIncomingPluginChannel(StandardMessenger.java:216) ~[forge:?]
	at com.sk89q.worldedit.bukkit.WorldEditPlugin.onEnable(WorldEditPlugin.java:110) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[forge:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:351) ~[forge:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[forge:?]
	at com.boydti.fawe.bukkit.BukkitMain.onEnable(BukkitMain.java:78) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[forge:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:351) ~[forge:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[forge:?]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:401) ~[forge:1.16.4-299]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:315) ~[forge:1.16.4-299]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:209) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:731) ~[?:?]
	at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:276) ~[?:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_271]```
