### ISSUE TITLE
[1.12.2] compatibility: cannot use armor station block in tinkers compendium 

### ISSUE THREAD

**Issue by xemnes** [Teneted/Tenet#756]
pretty much the title, when trying to use the armor station from tinkers compendium, nothing happens, console spits out this error:

> 05.01 07:12:40 [Server] FATAL Error executing task
> 05.01 07:12:40 [Server] INFO java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: lance5057.tDefense.core.workstations.CompendiumWorkstations.getServerGuiElement(ILnet/minecraft/entity/player/EntityPlayer;Lnet/minecraft/world/World;III)Ljava/lang/Object;
> 05.01 07:12:40 [Server] INFO at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_265]
> 05.01 07:12:40 [Server] INFO at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_265]
> 05.01 07:12:40 [Server] INFO at net.minecraft.util.Util.runTask(SourceFile:531) [h.class:?]
> 05.01 07:12:40 [Server] INFO at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:843) [MinecraftServer.class:?]
> 05.01 07:12:40 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:470) [nz.class:?]
> 05.01 07:12:40 [Server] INFO at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:781) [MinecraftServer.class:?]
> 05.01 07:12:40 [Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:627) [MinecraftServer.class:?]
> 05.01 07:12:40 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_265]
> 05.01 07:12:40 [Server] INFO Caused by: java.lang.NoSuchMethodError: lance5057.tDefense.core.workstations.CompendiumWorkstations.getServerGuiElement(ILnet/minecraft/entity/player/EntityPlayer;Lnet/minecraft/world/World;III)Ljava/lang/Object;
> 05.01 07:12:40 [Server] INFO at lance5057.tDefense.proxy.CommonProxy.getServerGuiElement(CommonProxy.java:76) ~[CommonProxy.class:?]
> 05.01 07:12:40 [Server] INFO at net.minecraftforge.fml.common.network.NetworkRegistry.getRemoteGuiContainer(NetworkRegistry.java:249) ~[NetworkRegistry.class:?]
> 05.01 07:12:40 [Server] INFO at net.minecraftforge.fml.common.network.internal.FMLNetworkHandler.openGui(FMLNetworkHandler.java:94) ~[FMLNetworkHandler.class:?]
> 05.01 07:12:40 [Server] INFO at net.minecraft.entity.player.EntityPlayer.openGui(EntityPlayer.java:2735) ~[aed.class:?]
> 05.01 07:12:40 [Server] INFO at lance5057.tDefense.core.workstations.blocks.ArmorStationBlock.openGui(ArmorStationBlock.java:67) ~[ArmorStationBlock.class:?]
> 05.01 07:12:40 [Server] INFO at slimeknights.mantle.block.BlockInventory.onBlockActivated(BlockInventory.java:52) ~[BlockInventory.class:?]
> 05.01 07:12:40 [Server] INFO at net.minecraft.server.management.PlayerInteractionManager.processRightClickBlock(PlayerInteractionManager.java:580) ~[or.class:?]
> 05.01 07:12:40 [Server] INFO at net.minecraft.network.NetHandlerPlayServer.processTryUseItemOnBlock(NetHandlerPlayServer.java:1148) ~[pa.class:?]
> 05.01 07:12:40 [Server] INFO at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.processPacket(CPacketPlayerTryUseItemOnBlock.java:61) ~[ma.class:?]
> 05.01 07:12:40 [Server] INFO at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.processPacket(CPacketPlayerTryUseItemOnBlock.java:13) ~[ma.class:?]
> 05.01 07:12:40 [Server] INFO at net.minecraft.network.PacketThreadUtil.lambda$checkThreadAndEnqueue$0(PacketThreadUtil.java:16) ~[hv.class:?]
> 05.01 07:12:40 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_265]
> 05.01 07:12:40 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_265]
> 05.01 07:12:40 [Server] INFO at net.minecraft.util.Util.runTask(SourceFile:529) ~[h.class:?]
> 05.01 07:12:40 [Server] INFO ... 5 more

**Comment by xemnes** [comment]
for some reason, ater changing debug mode in console, its working now. how odd.
