### ISSUE TITLE
[1.7.10] java.lang.ClassNotFoundException: pw.prok.imagine.ImaginePoxy

### ISSUE THREAD

**Issue by dayd21git** [Teneted/Tenet#773]
Fix it!
```
[22:00:27 ERROR]: Could not dispatch event: kimagine to public void pw.prok.imagine.ImagineModContainer.constructMod(cpw.mods.fml.common.event.FMLConstructionEvent)
java.lang.IllegalStateException: java.lang.ClassNotFoundException: pw.prok.imagine.ImaginePoxy
        at pw.prok.imagine.inject.Creator.creator(Creator.java:24) ~[KImagine-0.2.0.jar:?]
        at pw.prok.imagine.inject.Creator.creator(Creator.java:16) ~[KImagine-0.2.0.jar:?]
        at pw.prok.imagine.inject.Injector.create(Injector.java:101) ~[KImagine-0.2.0.jar:?]
        at pw.prok.imagine.injectors.SidedProxyInjector.inject(SidedProxyInjector.java:23) ~[KImagine-0.2.0.jar:?]
        at pw.prok.imagine.injectors.SidedProxyInjector.inject(SidedProxyInjector.java:11) ~[KImagine-0.2.0.jar:?]
        at pw.prok.imagine.inject.AnnotationFieldInjector.inject(AnnotationFieldInjector.java:45) ~[KImagine-0.2.0.jar:?]
        at pw.prok.imagine.inject.AnnotationFieldInjector.inject(AnnotationFieldInjector.java:11) ~[KImagine-0.2.0.jar:?]
        at pw.prok.imagine.inject.Injector.injectInternal(Injector.java:88) ~[KImagine-0.2.0.jar:?]
        at pw.prok.imagine.inject.Injector.injectInternal(Injector.java:82) ~[KImagine-0.2.0.jar:?]
        at pw.prok.imagine.inject.Injector.inject(Injector.java:76) ~[KImagine-0.2.0.jar:?]
        at pw.prok.imagine.ImagineModContainer.constructMod(ImagineModContainer.java:59) ~[KImagine-0.2.0.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_271]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_271]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_271]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_271]
        at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[server-1.7.10.jar:?]
        at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[server-1.7.10.jar:?]
        at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) [server-1.7.10.jar:?]
        at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) [server-1.7.10.jar:?]
        at com.google.common.eventbus.EventBus.post(EventBus.java:275) [server-1.7.10.jar:?]
        at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212) [LoadController.class:1.7.10-26]
        at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190) [LoadController.class:1.7.10-26]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_271]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_271]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_271]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_271]
        at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) [server-1.7.10.jar:?]
        at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) [server-1.7.10.jar:?]
        at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) [server-1.7.10.jar:?]
        at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) [server-1.7.10.jar:?]
        at com.google.common.eventbus.EventBus.post(EventBus.java:275) [server-1.7.10.jar:?]
        at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119) [LoadController.class:1.7.10-26]
        at cpw.mods.fml.common.Loader.loadMods(Loader.java:513) [Loader.class:1.7.10-26]
        at cpw.mods.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:87) [FMLServerHandler.class:1.7.10-26]
        at cpw.mods.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:313) [FMLCommonHandler.class:1.7.10-26]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:177) [lt.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:646) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_271]
Caused by: java.lang.ClassNotFoundException: pw.prok.imagine.ImaginePoxy
        at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_271]
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:116) ~[launchwrapper.jar:?]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_271]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_271]
        at java.lang.Class.forName0(Native Method) ~[?:1.8.0_271]
        at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_271]
        at pw.prok.imagine.inject.Creator.creator(Creator.java:21) ~[KImagine-0.2.0.jar:?]
        ... 37 more
```

**Comment by TENIOS** [comment]
Same error.
Build 26.

**Comment by dayd21git** [comment]
It's been almost a month, and you still haven't figured out the problem?
LoL, kek

**Comment by Shawiizz** [comment]
If you're not happy then do a Forge + Bukkit software yourself.

**Comment by Shawiizz** [comment]
Also know that this error will not affect your server so you can ignore it

**Comment by dayd21git** [comment]
You could only warn me right away that there is no cause for concern. But you haven't done it for a month, have you? And people are waiting for any answer!
LoL, kek

**Comment by Shawiizz** [comment]
lol
