### ISSUE TITLE
[1.12.2]plugin error

### ISSUE THREAD

**Issue by Ru-Nan-i** [Teneted/Tenet#782]
https://www.curseforge.com/minecraft/bukkit-plugins/bgmplay

This error occurred when the existing generic bucket worked normally This plug-in is really an important plug-in for server development. Please help me. I asked the plug-in developer, but they said there was no problem with the plugin.

[23:09:06 ERROR]: null
 org.bukkit.command.CommandException: Unhandled exception executing command 'bgm' in plugin BgmPlay v1.0.3-RELEASE
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[PluginCommand.class:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[SimpleCommandMap.class:?]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:752) ~[CraftServer.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:1587) ~[pa.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:1426) ~[pa.class:?]
        at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(CPacketChatMessage.java:46) ~[la.class:?]
        at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(CPacketChatMessage.java:9) ~[la.class:?]
        at net.minecraft.network.PacketThreadUtil.lambda$checkThreadAndEnqueue$0(PacketThreadUtil.java:16) ~[hv.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_261]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_261]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:846) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:467) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:784) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:630) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_261]
Caused by: java.lang.NumberFormatException: null
        at java.lang.Integer.parseInt(Unknown Source) ~[?:1.8.0_261]
        at java.lang.Integer.parseInt(Unknown Source) ~[?:1.8.0_261]
        at com.dochsoft.bgmplay.worldBgm.WorldBgmCommand.playStartNewBgm(WorldBgmCommand.java:158) ~[?:?]
        at com.dochsoft.bgmplay.worldBgm.WorldBgmCommand.setBgmEachWorld(WorldBgmCommand.java:123) ~[?:?]
        at com.dochsoft.bgmplay.worldBgm.WorldBgmCommand.onCommand(WorldBgmCommand.java:48) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:43) ~[PluginCommand.class:?]
        ... 15 more

**Comment by Mgazul** [comment]
Check your configuration file
