### ISSUE TITLE
[1.16.4] bugs while installing (#294)

### ISSUE THREAD

**Issue by Palette-Pixel** [Teneted/Tenet#803]
[Mohist] Creating forge server jar. This can take 1 minute.
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at com.mohistmc.util.InstallUtils.run(InstallUtils.java:113)
        at com.mohistmc.util.InstallUtils.startInstallation(InstallUtils.java:99)
        at com.mohistmc.MohistMCStart.main(MohistMCStart.java:37)
Caused by: java.io.IOException: Patch expected net/minecraft/world/server/ServerChunkProvider to have the checksum c24d2df3 but it was 2bad2e1e
        at net.minecraftforge.binarypatcher.Patcher.patch(Patcher.java:162)
        at net.minecraftforge.binarypatcher.Patcher.process(Patcher.java:114)
        at net.minecraftforge.binarypatcher.ConsoleTool.main(ConsoleTool.java:128)
        ... 7 more

**Comment by Mgazul** [comment]
fixed

**Comment by Palette-Pixel** [comment]
> fixed

still not resolved. how can I have a fixed one?
