### ISSUE TITLE
[1.16.4] another bug found (#295, #296)

### ISSUE THREAD

**Issue by Palette-Pixel** [Teneted/Tenet#804]
Checking libraries, please wait...
All libraries are nice :) !
Checking the installation, please wait.
Finished the install verification process !
Update in check...
If you don't want to enable update check, set check_update in mohist-config/mohist.yml to false
No update found, latest version: (1-1.16.4-295) current version: (1-1.16.4-295)
[13:53:22 INFO]: ModLauncher running: args [--gameDir, ., --launchTarget, fmlserver, --fml.forgeVersion, 35.1.37, -
-fml.mcpVersion, 20201102.104115, --fml.mcVersion, 1.16.4, --fml.forgeGroup, net.minecraftforge]
[13:53:22 INFO]: ModLauncher 8.0.9+86+master.3cf110c starting: java version 11.0.9.1 by Debian
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by cpw.mods.modlauncher.SecureJarHandler (file:/home/new-mine/libraries/cpw/mods
/modlauncher/8.0.9/modlauncher-8.0.9.jar) to field java.util.jar.Manifest.jv
WARNING: Please consider reporting this to the maintainers of cpw.mods.modlauncher.SecureJarHandler
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[13:53:22 FATAL]: Found no coremod provider. Cannot run
[13:53:23 ERROR]: Service failed to load fml
cpw.mods.modlauncher.api.IncompatibleEnvironmentException: No coremod library found
        at net.minecraftforge.fml.loading.FMLLoader.onInitialLoad(FMLLoader.java:138) ~[mohist-1.16.4-295-server.ja
r:35.1] {}
        at net.minecraftforge.fml.loading.FMLServiceProvider.onLoad(FMLServiceProvider.java:122) ~[mohist-1.16.4-29
5-server.jar:35.1] {}
        at cpw.mods.modlauncher.TransformationServiceDecorator.onLoad(TransformationServiceDecorator.java:53) ~[mod
launcher-8.0.9.jar:?] {}
        at cpw.mods.modlauncher.TransformationServicesHandler.lambda$loadTransformationServices$11(TransformationSe
rvicesHandler.java:131) ~[modlauncher-8.0.9.jar:?] {}
        at java.util.HashMap$Values.forEach(HashMap.java:976) [?:?] {}
        at cpw.mods.modlauncher.TransformationServicesHandler.loadTransformationServices(TransformationServicesHand
ler.java:131) [modlauncher-8.0.9.jar:?] {}
        at cpw.mods.modlauncher.TransformationServicesHandler.initializeTransformationServices(TransformationServic
esHandler.java:56) [modlauncher-8.0.9.jar:?] {}

**Comment by Palette-Pixel** [comment]
and this one is from #296

[15:50:30 INFO]: ModLauncher running: args [--gameDir, ., --launchTarget, fmlserver, --fml.forgeVersion, 35.1.37, --fml.mcpVersion, 20201102.104115, --fml.mcVersion, 1.16.4, --fml.forgeGroup, net.minecraftforge]
[15:50:30 INFO]: ModLauncher 8.0.9+86+master.3cf110c starting: java version 11.0.9.1 by Debian
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by cpw.mods.modlauncher.SecureJarHandler (file:/home/mcserver-beta/libraries/cpw/mods/modlauncher/8.0.9/modlauncher-8.0.9.jar) to field java.util.jar.Manifest.jv
WARNING: Please consider reporting this to the maintainers of cpw.mods.modlauncher.SecureJarHandler
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[15:50:30 FATAL]: Found no coremod provider. Cannot run
[15:50:30 ERROR]: Service failed to load fml
cpw.mods.modlauncher.api.IncompatibleEnvironmentException: No coremod library found
        at net.minecraftforge.fml.loading.FMLLoader.onInitialLoad(FMLLoader.java:138) ~[mohist-1.16.4-296-server.jar:35.1] {}
        at net.minecraftforge.fml.loading.FMLServiceProvider.onLoad(FMLServiceProvider.java:122) ~[mohist-1.16.4-296-server.jar:35.1] {}
        at cpw.mods.modlauncher.TransformationServiceDecorator.onLoad(TransformationServiceDecorator.java:53) ~[modlauncher-8.0.9.jar:?] {}
        at cpw.mods.modlauncher.TransformationServicesHandler.lambda$loadTransformationServices$11(TransformationServicesHandler.java:131) ~[modlauncher-8.0.9.jar:?] {}
        at java.util.HashMap$Values.forEach(HashMap.java:976) [?:?] {}
        at cpw.mods.modlauncher.TransformationServicesHandler.loadTransformationServices(TransformationServicesHandler.java:131) [modlauncher-8.0.9.jar:?] {}
        at cpw.mods.modlauncher.TransformationServicesHandler.initializeTransformationServices(TransformationServicesHandler.java:56) [modlauncher-8.0.9.jar:?] {}
        at cpw.mods.modlauncher.Launcher.run(Launcher.java:76) [modlauncher-8.0.9.jar:?] {}
        at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {}
        at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:64) [mohist-1.16.4-296-server.jar:?] {}
        at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:61) [mohist-1.16.4-296-server.jar:?] {}
        at net.minecraftforge.server.ServerMain.startMohistServer(ServerMain.java:58) [mohist-1.16.4-296-server.jar:?] {}
        at com.mohistmc.MohistMCStart.main(MohistMCStart.java:47) [mohist-1.16.4-296-server.jar:1.16.4-296] {}
[15:50:30 ERROR]: Found 1 services that failed to load : [fml]
[15:50:30 INFO]: [net.minecraftforge.server.ServerMain$Runner:runLauncher:66]: The server is missing critical libraries and cannot load. Please run the installer to correct this

**Comment by Shawiizz** [comment]
Should be fixed on build 299.

**Comment by gXLg** [comment]
It appears again in 1.16.5-347 (current version)

**Comment by darksoon** [comment]
and in 1-1.16.5-350

first startup works, after stop and restart without any changes:

`                                      Welcome to Mohist 1.16.5 ! - Mohist Developement Group
Checking libraries, please wait...
All libraries are nice :) !
Checking the installation, please wait.
[Mohist] Creating forge server jar. This can take 1 minute.
Finished the install verification process !
Update in check...
If you don't want to enable update check, set check_update in mohist-config/mohist.yml to false
No update found, latest version: (1-1.16.5-350) current version: (1-1.16.5-350)
[15:42:33 INFO]: ModLauncher running: args [--gameDir, ., --launchTarget, fmlserver, --fml.forgeVersion, 36.0.13, --fml.mcpVersion, 20210115.111550, --fml.mcVersion, 1.16.5, --fml.forgeGroup, net.minecraftforge]
[15:42:33 INFO]: ModLauncher 8.0.9+86+master.3cf110c starting: java version 1.8.0_271 by Oracle Corporation
[15:42:33 FATAL]: Found no coremod provider. Cannot run
[15:42:33 ERROR]: Service failed to load fml
cpw.mods.modlauncher.api.IncompatibleEnvironmentException: No coremod library found
        at net.minecraftforge.fml.loading.FMLLoader.onInitialLoad(FMLLoader.java:138) ~[mohist-1.16.5-347-server.jar:36.0] {}
        at net.minecraftforge.fml.loading.FMLServiceProvider.onLoad(FMLServiceProvider.java:122) ~[mohist-1.16.5-347-server.jar:36.0] {}
        at cpw.mods.modlauncher.TransformationServiceDecorator.onLoad(TransformationServiceDecorator.java:53) ~[modlauncher-8.0.9.jar:?] {}
        at cpw.mods.modlauncher.TransformationServicesHandler.lambda$loadTransformationServices$11(TransformationServicesHandler.java:131) ~[modlauncher-8.0.9.jar:?] {}
        at java.util.HashMap$Values.forEach(Unknown Source) [?:1.8.0_271] {}
        at cpw.mods.modlauncher.TransformationServicesHandler.loadTransformationServices(TransformationServicesHandler.java:131) [modlauncher-8.0.9.jar:?] {}
        at cpw.mods.modlauncher.TransformationServicesHandler.initializeTransformationServices(TransformationServicesHandler.java:56) [modlauncher-8.0.9.jar:?] {}
        at cpw.mods.modlauncher.Launcher.run(Launcher.java:76) [modlauncher-8.0.9.jar:?] {}
        at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {}
        at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:66) [mohist-1.16.5-347-server.jar:?] {}
        at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:63) [mohist-1.16.5-347-server.jar:?] {}
        at net.minecraftforge.server.ServerMain.main(ServerMain.java:60) [mohist-1.16.5-347-server.jar:?] {}
[15:42:33 ERROR]: Found 1 services that failed to load : [fml]
[15:42:33 INFO]: [net.minecraftforge.server.ServerMain$Runner:runLauncher:68]: The server is missing critical libraries and cannot load. Please run the installer to correct this`

**Comment by Shawiizz** [comment]
use 345

**Comment by Shawiizz** [comment]
Fixed in latest build.
