### ISSUE TITLE
NullPointerException when placing Applied Energistics 2 cables and buses (1.16.5-321)

### ISSUE THREAD

**Issue by ajruckman** [Teneted/Tenet#839]
Using 
- Mohist 1.16.5-321
- Applied Energistics 8.2.0-beta.3

Occurs whenever anyone places cables or similar blocks. This does not occur in the equivalent (vanilla) Forge versions.

```
[18:52:48 FATAL]: Error executing task on Server
[18:52:48 WARN]: java.lang.NullPointerException
[18:52:48 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callBlockPlaceEvent(CraftEventFactory.java:299)
[18:52:48 WARN]:        at net.minecraft.item.BlockItem.func_195942_a(BlockItem.java:76)
[18:52:48 WARN]:        at appeng.block.AEBaseBlockItem.func_195942_a(AEBaseBlockItem.java:131)
[18:52:48 WARN]:        at appeng.parts.PartPlacement.place(PartPlacement.java:242)
[18:52:48 WARN]:        at appeng.core.api.ApiPart.placeBus(ApiPart.java:39)
[18:52:48 WARN]:        at appeng.items.parts.PartItem.func_195939_a(PartItem.java:50)
[18:52:48 WARN]:        at net.minecraftforge.common.ForgeHooks.onPlaceItemIntoWorld(ForgeHooks.java:612)
[18:52:48 WARN]:        at net.minecraft.item.ItemStack.func_196084_a(ItemStack.java:209)
[18:52:48 WARN]:        at net.minecraft.server.management.PlayerInteractionManager.func_219441_a(PlayerInteractionManager.java:449)
[18:52:48 WARN]:        at net.minecraft.network.play.ServerPlayNetHandler.func_184337_a(ServerPlayNetHandler.java:1394)
[18:52:48 WARN]:        at net.minecraft.network.play.client.CPlayerTryUseItemOnBlockPacket.func_148833_a(CPlayerTryUseItemOnBlockPacket.java:38)
[18:52:48 WARN]:        at net.minecraft.network.play.client.CPlayerTryUseItemOnBlockPacket.func_148833_a(CPlayerTryUseItemOnBlockPacket.java:12)
[18:52:48 WARN]:        at net.minecraft.network.PacketThreadUtil.lambda$checkThreadAndEnqueue$0(PacketThreadUtil.java:22)
[18:52:48 WARN]:        at net.minecraft.network.PacketThreadUtil$$Lambda$9618/0x0000000000000000.run(Unknown Source)
[18:52:48 WARN]:        at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18)
[18:52:48 WARN]:        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(ThreadTaskExecutor.java:136)
[18:52:48 WARN]:        at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23)
[18:52:48 WARN]:        at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:869)
[18:52:48 WARN]:        at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:183)
[18:52:48 WARN]:        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(ThreadTaskExecutor.java:109)
[18:52:48 WARN]:        at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:852)
[18:52:48 WARN]:        at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:846)
[18:52:48 WARN]:        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(ThreadTaskExecutor.java:119)
[18:52:48 WARN]:        at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:832)
[18:52:48 WARN]:        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:765)
[18:52:48 WARN]:        at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:276)
[18:52:48 WARN]:        at net.minecraft.server.MinecraftServer$$Lambda$7723/0x0000000000000000.run(Unknown Source)
[18:52:48 WARN]:        at java.lang.Thread.run(Thread.java:823)
```

**Comment by ajruckman** [comment]
Also I'm sure this is unrelated, but this occurs every time an item is inserted or removed from a ME network:
```
[19:12:24 WARN]: Unhandled statistic: Stat{name=minecraft.custom:minecraft.items_inserted, formatter=net.minecraft.stats.IStatFormatter$$Lambda$1822/0x0000000000000000@e409cce}
```

**Comment by ajruckman** [comment]
It seems like Mohist can't handle a `DirectionalPlaceContext` with a null `PlayerEntity player`, although this comment suggests that it should be able to deal with this: https://github.com/P3pp3rF1y/Reliquary/issues/410#issuecomment-614241852
