### ISSUE TITLE
[1.12.2] Actually Additions worm causes Null Pointer

### ISSUE THREAD

**Issue by gabearro** [Teneted/Tenet#847]
When using the FTB Revelations pack I found that if you right click dirt or tilled soil with the worm from actually additions you get a really vague null pointer.

Stacktrace:
```
[09:21:15 FATAL]: Error executing task
 java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_252]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_252]
	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:846) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:467) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:784) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:630) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
Caused by: java.lang.NullPointerException
```

**Comment by Mgazul** [comment]
Incomplete information

**Comment by gabearro** [comment]
I'm unable to reproduce at this time, I checked back on the logs and that was the entire stacktrace that was produced by placing worms. A server restart did fix this though so I am not sure what the issue was. I do know it triggered literally the second the worm gets placed and renders.

**Comment by Shawiizz** [comment]
If you can reproduce this again, open a new issue.
