### ISSUE TITLE
[1.16.5]放不了ae的玻璃线缆

### ISSUE THREAD

**Issue by Remering** [Teneted/Tenet#849]
放ae的线（玻璃线缆、智能线缆、包层线缆、致密线缆）就会听到玻璃打掉的声音并且后台疯狂报npe
```
[18:34:39 WARN]: java.lang.NullPointerException
[18:34:39 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callBlockPlaceEvent(CraftEventFactory
.java:299)
[18:34:39 WARN]:        at net.minecraft.item.BlockItem.func_195942_a(BlockItem.java:76)
[18:34:39 WARN]:        at appeng.block.AEBaseBlockItem.func_195942_a(AEBaseBlockItem.java:131)
[18:34:39 WARN]:        at appeng.parts.PartPlacement.place(PartPlacement.java:242)
[18:34:39 WARN]:        at appeng.core.api.ApiPart.placeBus(ApiPart.java:39)
[18:34:39 WARN]:        at appeng.items.parts.PartItem.func_195939_a(PartItem.java:50)
[18:34:39 WARN]:        at net.minecraftforge.common.ForgeHooks.onPlaceItemIntoWorld(ForgeHooks.java:612)
[18:34:39 WARN]:        at net.minecraft.item.ItemStack.func_196084_a(ItemStack.java:209)
[18:34:39 WARN]:        at net.minecraft.server.management.PlayerInteractionManager.func_219441_a(PlayerInteractionManag
er.java:449)
[18:34:39 WARN]:        at net.minecraft.network.play.ServerPlayNetHandler.func_184337_a(ServerPlayNetHandler.java:1394)

[18:34:39 WARN]:        at net.minecraft.network.play.client.CPlayerTryUseItemOnBlockPacket.func_148833_a(CPlayerTryUseI
temOnBlockPacket.java:38)
[18:34:39 WARN]:        at net.minecraft.network.play.client.CPlayerTryUseItemOnBlockPacket.func_148833_a(CPlayerTryUseI
temOnBlockPacket.java:12)
[18:34:39 WARN]:        at net.minecraft.network.PacketThreadUtil.lambda$checkThreadAndEnqueue$0(PacketThreadUtil.java:2
2)
[18:34:39 WARN]:        at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18)
[18:34:39 WARN]:        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(ThreadTaskExecutor.java:136)
[18:34:39 WARN]:        at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23)
[18:34:39 WARN]:        at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:869)
[18:34:39 WARN]:        at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:183)
[18:34:39 WARN]:        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(ThreadTaskExecutor.java:109)
[18:34:39 WARN]:        at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:852)
[18:34:39 WARN]:        at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:846)
[18:34:39 WARN]:        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(ThreadTaskExecutor.java:97)
[18:34:39 WARN]:        at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:831)
[18:34:39 WARN]:        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:765)
[18:34:39 WARN]:        at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:276)
[18:34:39 WARN]:        at java.base/java.lang.Thread.run(Thread.java:834)
```
Mohist version: `1.16.5-320`

**Comment by Mgazul** [comment]
Provide more useful information: mohist version

**Comment by Remering** [comment]
Mohist version: `1.16.5-320`

**Comment by Mgazul** [comment]
322+ version has been fixed

**Comment by Remering** [comment]
Ok, thanks for your contributions!
