### ISSUE TITLE
noclassdeffounderror: o on attempt to enable saberfactions

### ISSUE THREAD

**Issue by IronworksProductions** [Teneted/Tenet#855]
SaberfactionsX fails to enable with this stacktrace:
[07:42:37] [Server thread/ERROR] [Minecraft]: Could not load 'plugins/SaberFactionsX.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: o
at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[JavaPluginLoader.class:537f1d6]
at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:330) ~[SimplePluginManager.class:537f1d6]
at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:252) [SimplePluginManager.class:537f1d6]
at org.bukkit.craftbukkit.v1_12_R1.CraftServer.loadPlugins(CraftServer.java:322) [CraftServer.class:537f1d6]
at net.minecraft.server.MinecraftServer.loadAllWorlds(MinecraftServer.java:416) [MinecraftServer.class:?]
at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:321) [nz.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:688) [MinecraftServer.class:?]
at java.lang.Thread.run(Thread.java:823) [?:1.8.0_272]
Caused by: java.lang.NoClassDefFoundError: o
at sun.misc.Unsafe.ensureClassInitialized(Native Method) ~[?:1.8.0_272]
at java.lang.J9VMInternals.initialize(J9VMInternals.java:88) ~[?:1.8.0_272]
at java.lang.Class.forName(Class.java:424) ~[?:1.8.0_272]
at org.bukkit.plugin.java.PluginClassLoader.(PluginClassLoader.java:74) ~[PluginClassLoader.class:537f1d6]
at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:127) ~[JavaPluginLoader.class:537f1d
(full log was large enough to even crash ubuntu pastebin)
Dev said that there was an unimplemented method missing in mohist required for it to enable. This bug also exists on latest magma btw.

**Comment by Shawiizz** [comment]
Please specify the Minecraft version (1.12.2/1.7.10/1.16.5)

**Comment by IronworksProductions** [comment]
its a bug on 1.12.2 latest mohist #184

**Comment by Shawiizz** [comment]
Yo, which unimplemented method it is ?

**Comment by IronworksProductions** [comment]
Unfortunately I do not know the exact method. The dev Driftay did say they messaged one of you about adding it on the 8th of January though

**Comment by Shawiizz** [comment]
Hello, is this still an issue today ?
