### ISSUE TITLE
[1.12.2] CraftEnhance plugin don't work

### ISSUE THREAD

**Issue by Ru-Nan-i** [Teneted/Tenet#863]
https://www.spigotmc.org/resources/1-9-1-16-custom-recipes-and-crafting-craftenhance.65058/
CraftEnhance plugin don't work in mohist

 java.lang.IllegalArgumentException: key
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122) ~[minecraft_server.1.12.2.jar:?]
        at org.bukkit.NamespacedKey.<init>(NamespacedKey.java:48) ~[NamespacedKey.class:?]
        at org.bukkit.craftbukkit.v1_12_R1.util.CraftNamespacedKey.fromMinecraft(CraftNamespacedKey.java:16) ~[CraftNamespacedKey.class:?]
        at net.minecraftforge.oredict.ShapelessOreRecipe.toBukkitRecipe(ShapelessOreRecipe.java:168) ~[ShapelessOreRecipe.class:?]
        at net.minecraftforge.oredict.ShapelessOreRecipe.toBukkitRecipe(ShapelessOreRecipe.java:49) ~[ShapelessOreRecipe.class:?]
        at com.mohistmc.recipe.RecipeUtils.toBukkitRecipe(RecipeUtils.java:15) ~[RecipeUtils.class:?]
        at org.bukkit.craftbukkit.v1_12_R1.inventory.RecipeIterator.next(RecipeIterator.java:31) ~[RecipeIterator.class:?]
        at org.bukkit.craftbukkit.v1_12_R1.inventory.RecipeIterator.next(RecipeIterator.java:10) ~[RecipeIterator.class:?]
        at java.util.Iterator.forEachRemaining(Unknown Source) ~[?:1.8.0_281]
        at com.dutchjelly.craftenhance.crafthandling.RecipeLoader.<init>(RecipeLoader.java:58) ~[?:?]
        at com.dutchjelly.craftenhance.crafthandling.RecipeLoader.getInstance(RecipeLoader.java:35) ~[?:?]
        at com.dutchjelly.craftenhance.CraftEnhance.onDisable(CraftEnhance.java:126) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:179) ~[JavaPlugin.class:?]
        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:341) ~[JavaPluginLoader.class:?]
        at com.dutchjelly.craftenhance.CraftEnhance.onCommand(CraftEnhance.java:141) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:43) ~[PluginCommand.class:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[SimpleCommandMap.class:?]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:752) ~[CraftServer.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:1588) ~[pa.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:1427) ~[pa.class:?]
        at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(CPacketChatMessage.java:46) ~[la.class:?]
        at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(CPacketChatMessage.java:9) ~[la.class:?]
        at net.minecraft.network.PacketThreadUtil.lambda$checkThreadAndEnqueue$0(PacketThreadUtil.java:16) ~[hv.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_281]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_281]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:846) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:467) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:784) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:630) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_281]
[18:05:41 ERROR]: null
 org.bukkit.command.CommandException: Unhandled exception executing command 'ceh' in plugin CraftEnhance v2.4.2
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[PluginCommand.class:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[SimpleCommandMap.class:?]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:752) ~[CraftServer.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:1588) ~[pa.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:1427) ~[pa.class:?]
        at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(CPacketChatMessage.java:46) ~[la.class:?]
        at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(CPacketChatMessage.java:9) ~[la.class:?]
        at net.minecraft.network.PacketThreadUtil.lambda$checkThreadAndEnqueue$0(PacketThreadUtil.java:16) ~[hv.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_281]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_281]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:846) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:467) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:784) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:630) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_281]
Caused by: java.lang.NoClassDefFoundError: com/dutchjelly/craftenhance/commandhandling/CustomCmdHandler
        at com.dutchjelly.craftenhance.CraftEnhance.onCommand(CraftEnhance.java:144) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:43) ~[PluginCommand.class:?]
        ... 15 more
Caused by: java.lang.ClassNotFoundException: Failed to remap class com.dutchjelly.craftenhance.commandhandling.CustomCmdHandler
        at org.bukkit.plugin.java.PluginClassLoader.remappedFindClass(PluginClassLoader.java:190) ~[PluginClassLoader.class:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:104) ~[PluginClassLoader.class:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:81) ~[PluginClassLoader.class:?]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_281]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_281]
        at com.dutchjelly.craftenhance.CraftEnhance.onCommand(CraftEnhance.java:144) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:43) ~[PluginCommand.class:?]
        ... 15 more
Caused by: java.lang.IllegalStateException: zip file closed
        at java.util.zip.ZipFile.ensureOpen(Unknown Source) ~[?:1.8.0_281]
        at java.util.zip.ZipFile.getEntry(Unknown Source) ~[?:1.8.0_281]
        at java.util.jar.JarFile.getEntry(Unknown Source) ~[?:1.8.0_281]
        at java.util.jar.JarFile.getJarEntry(Unknown Source) ~[?:1.8.0_281]
        at org.bukkit.plugin.java.PluginClassLoader.remappedFindClass(PluginClassLoader.java:156) ~[PluginClassLoader.class:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:104) ~[PluginClassLoader.class:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:81) ~[PluginClassLoader.class:?]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_281]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_281]
        at com.dutchjelly.craftenhance.CraftEnhance.onCommand(CraftEnhance.java:144) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:43) ~[PluginCommand.class:?]
        ... 15 more

**Comment by Paneedah** [comment]
Hia mate!
Your issue is based in the fact that you're using the wrong version of the CraftEnchance plugin!
Switch to version (1.12)CraftEnhance-2.4.1

Here's a link to their files!
https://dev.bukkit.org/projects/craftenhance/files

I don't recommend it though, I've had issues where modded items do not work with their crafting recipes.
If you need a custom crafting recipe plugin, I have one custom made, feel free to contact me via discord!
PandaZツ# 0690

**Comment by Ru-Nan-i** [comment]
I Switch to version (1.12)CraftEnhance-2.4.1 but plugin don't work in mohist

**Comment by SparkGNRK** [comment]
Working using (1.12)CraftEnhance-2.4.1 and mohist build 307
