### ISSUE TITLE
WorldGuard could not pass event BreakBlockEvent

### ISSUE THREAD

**Issue by ghost** [Teneted/Tenet#875]
WorldGuard version: 7.0.4-beta1
Platform version: Mohist 1.16.5 (#336 build)
```
[21:35:06 ERROR]: Could not pass event BreakBlockEvent to WorldGuard v7.0.4-beta1;bc551da
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:319) ~[?:?] {re:classloading}
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[?:?] {re:classloading}
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[?:?] {re:classloading}
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:574) ~[?:?] {re:classloading}
        at com.sk89q.worldguard.bukkit.util.Events.fireAndTestCancel(Events.java:60) ~[?:?] {re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading}
        at com.sk89q.worldguard.bukkit.listener.debounce.legacy.AbstractEventDebounce.debounce(AbstractEventDebounce.java:56) ~[?:?] {re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading}
        at com.sk89q.worldguard.bukkit.listener.debounce.legacy.BlockEntityEventDebounce.debounce(BlockEntityEventDebounce.java:36) ~[?:?] {re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading}
        at com.sk89q.worldguard.bukkit.listener.EventAbstractionListener.onEntityChangeBlock(EventAbstractionListener.java:317) ~[?:?] {re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading}
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {re:classloading,re:classloading}
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?] {re:classloading,re:classloading}
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?] {re:classloading,re:classloading}
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?] {}
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:315) ~[?:?] {re:classloading}
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[?:?] {re:classloading}
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[?:?] {re:classloading}
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:574) ~[?:?] {re:classloading}
        at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callEntityChangeBlockEvent(CraftEventFactory.java:1078) ~[?:?] {re:classloading}
        at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callEntityChangeBlockEvent(CraftEventFactory.java:1070) ~[?:?] {re:classloading}
        at net.minecraft.entity.ai.brain.task.FarmTask.func_212833_d_(FarmTask.java:98) ~[?:?] {re:classloading}
        at net.minecraft.entity.ai.brain.task.FarmTask.func_212833_d_(FarmTask.java:27) ~[?:?] {re:classloading}
        at net.minecraft.entity.ai.brain.task.Task.func_220377_c(SourceFile:63) ~[?:?] {re:classloading}
        at net.minecraft.entity.ai.brain.task.MultiTask.lambda$updateTask$4(MultiTask.java:52) ~[?:?] {re:classloading}
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source) ~[?:?] {}
        at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source) ~[?:?] {}
        at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source) ~[?:?] {}
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source) ~[?:?] {}
        at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:?] {}
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:?] {}
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source) ~[?:?] {}
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source) ~[?:?] {}
        at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:?] {}
        at java.util.stream.ReferencePipeline.forEach(Unknown Source) ~[?:?] {}
        at net.minecraft.entity.ai.brain.task.MultiTask.func_212833_d_(MultiTask.java:51) ~[?:?] {re:classloading}
        at net.minecraft.entity.ai.brain.task.Task.func_220377_c(SourceFile:63) ~[?:?] {re:classloading}
        at net.minecraft.entity.ai.brain.Brain.func_218222_e(SourceFile:521) ~[?:?] {re:classloading}
        at net.minecraft.entity.ai.brain.Brain.func_218210_a(SourceFile:466) ~[?:?] {re:classloading}
        at net.minecraft.entity.merchant.villager.VillagerEntity.func_70619_bc(VillagerEntity.java:212) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
        at net.minecraft.entity.MobEntity.func_70626_be(MobEntity.java:761) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.entity.LivingEntity.func_70636_d(LivingEntity.java:2847) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
        at net.minecraft.entity.MobEntity.func_70636_d(MobEntity.java:546) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.entity.AgeableEntity.func_70636_d(AgeableEntity.java:142) ~[?:?] {re:classloading}
        at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2591) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
        at net.minecraft.entity.MobEntity.func_70071_h_(MobEntity.java:342) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.entity.merchant.villager.VillagerEntity.func_70071_h_(VillagerEntity.java:251) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
        at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:689) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
        at net.minecraft.world.World.func_217390_a(World.java:733) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:462) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1011) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:333) ~[?:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:925) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:761) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:276) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at java.lang.Thread.run(Unknown Source) [?:?] {}
Caused by: java.lang.NoSuchMethodError: net.minecraft.world.server.ServerWorld.getChunkAt(II)Lnet/minecraft/world/chunk/Chunk;
        at com.sk89q.worldedit.bukkit.adapter.impl.Spigot_v1_16_R3.getBlock(Spigot_v1_16_R3.java:348) ~[?:?] {re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading}
        at com.sk89q.worldedit.bukkit.BukkitWorld.getBlock(BukkitWorld.java:441) ~[?:?] {re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading}
        at com.sk89q.worldguard.chest.SignChestProtection.isProtected(SignChestProtection.java:36) ~[?:?] {re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading}
        at com.sk89q.worldguard.bukkit.BukkitWorldConfiguration.isChestProtected(BukkitWorldConfiguration.java:413) ~[?:?] {re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading}
        at com.sk89q.worldguard.bukkit.listener.ChestProtectionListener.lambda$onBreakBlock$2(ChestProtectionListener.java:103) ~[?:?] {re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading}
        at com.sk89q.worldguard.bukkit.event.block.AbstractBlockEvent.filterInternal(AbstractBlockEvent.java:132) ~[?:?] {re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading}
        at com.sk89q.worldguard.bukkit.event.block.AbstractBlockEvent.filter(AbstractBlockEvent.java:124) ~[?:?] {re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading}
        at com.sk89q.worldguard.bukkit.event.block.BreakBlockEvent.filter(BreakBlockEvent.java:39) ~[?:?] {re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading}
        at com.sk89q.worldguard.bukkit.event.block.AbstractBlockEvent.filter(AbstractBlockEvent.java:160) ~[?:?] {re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading}
        at com.sk89q.worldguard.bukkit.event.block.BreakBlockEvent.filter(BreakBlockEvent.java:39) ~[?:?] {re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading}
        at com.sk89q.worldguard.bukkit.listener.ChestProtectionListener.onBreakBlock(ChestProtectionListener.java:103) ~[?:?] {re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading}
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {re:classloading,re:classloading}
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?] {re:classloading,re:classloading}
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?] {re:classloading,re:classloading}
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?] {}
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:315) ~[?:?] {re:classloading}
        ... 52 more
```

**Comment by Shawiizz** [comment]
![unknown-8](https://user-images.githubusercontent.com/55449195/106395045-52fcaa00-6400-11eb-9e5c-a78b5b86c4ca.png)

**Comment by ghost** [comment]
Why? This is important plugin, and WorldGuard don't work properly.

**Comment by Shawiizz** [comment]
Read the message on the screen i sent above.

**Comment by joaoespanhol** [comment]
I don't have this problem, I use worldguard, worldedit and redprotect
Try other version

**Comment by ghost** [comment]
Other version of plugin or Mohist build?
