### ISSUE TITLE
[1.7.10] Holographic Displays plugin not supported

### ISSUE THREAD

**Issue by bagomot** [Teneted/Tenet#88]
```
[HolographicDisplays] Enabling HolographicDisplays v1.8.8
java.lang.NoSuchFieldException: d
	at java.lang.Class.getDeclaredField(Class.java:2070)
	at com.gmail.filoghost.holograms.utils.ReflectionUtils.putInPrivateStaticMap(ReflectionUtils.java:10)
	at com.gmail.filoghost.holograms.nms.v1_7_R4.NmsManagerImpl.registerCustomEntity(NmsManagerImpl.java:43)
	at com.gmail.filoghost.holograms.nms.v1_7_R4.NmsManagerImpl.registerCustomEntities(NmsManagerImpl.java:28)
	at com.gmail.filoghost.holograms.HolographicDisplays.onEnable(HolographicDisplays.java:139)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316)
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:368)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:410)
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:439)
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:373)
	at net.minecraft.server.MinecraftServer.func_71243_i(MinecraftServer.java:521)
	at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:495)
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:455)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:338)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:645)
	at java.lang.Thread.run(Thread.java:745)

******************************************************
     HolographicDisplays was unable to register
     custom entities, the plugin will be disabled.
     Are you using the correct Bukkit version?
******************************************************
```

**Comment by Tanguygab** [comment]
Armor Stands have been added in 1.8 so you can't use ArmorStand or Holograms in 1.7.10

**Comment by bagomot** [comment]
This version supports Cauldron 1.7.10: https://dev.bukkit.org/projects/holographic-displays/files/830374

**Comment by Tanguygab** [comment]
Have you tried on a normal Spigot server ?

**Comment by bagomot** [comment]
Yes, I tested on spigot-1.7.10-SNAPSHOT-b1657. All versions of the HD plugin is correctly work from 1.8.8 to 2.2.6 (as announced by the plugin developer).
The plugin of all these versions does not work on Mohist with version higher af2f6ad.
