### ISSUE TITLE
[FATAL]: Error executing task

### ISSUE THREAD

**Issue by BillZhucn** [Teneted/Tenet#886]
When a player ignites a nuke, the FATAL error executing task appears and spamming in the console.
Latest.log is attached and error is extracted and pasted below.
[latest.log](https://github.com/Mohist-Community/Mohist/files/5915984/latest.log)

```
version
[11:49:15 INFO]: This server is running Mohist version 1.12.2-185 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT, Forge version 14.23.5.2855)
```

```
[11:37:44 INFO]: Player LY_LanYu/  placed a nuke at dim 0: 98/73/305.
[11:38:20 INFO]: Nuke at dim 0: 98/73/305 was ignited indirectly.
[11:38:22 FATAL]: Error executing task
 java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: key
        at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_275]
        at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_275]
        at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:846) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:467) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:784) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:630) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275]
Caused by: java.lang.IllegalArgumentException: key
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122) ~[minecraft_server.1.12.2.jar:?]
        at org.bukkit.NamespacedKey.<init>(NamespacedKey.java:48) ~[NamespacedKey.class:?]
        at org.bukkit.craftbukkit.v1_12_R1.util.CraftNamespacedKey.fromMinecraft(CraftNamespacedKey.java:16) ~[CraftNamespacedKey.class:?]
        at net.minecraftforge.oredict.ShapedOreRecipe.toBukkitRecipe(ShapedOreRecipe.java:262) ~[ShapedOreRecipe.class:?]
        at net.minecraftforge.oredict.ShapedOreRecipe.toBukkitRecipe(ShapedOreRecipe.java:54) ~[ShapedOreRecipe.class:?]
        at com.mohistmc.recipe.RecipeUtils.toBukkitRecipe(RecipeUtils.java:15) ~[RecipeUtils.class:?]
        at org.bukkit.craftbukkit.v1_12_R1.inventory.CraftInventoryCrafting.getRecipe(CraftInventoryCrafting.java:122) ~[CraftInventoryCrafting.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147351_a(NetHandlerPlayServer.java:2102) ~[pa.class:?]
        at net.minecraft.network.play.client.CPacketClickWindow.func_148833_a(CPacketClickWindow.java:38) ~[lf.class:?]
        at net.minecraft.network.play.client.CPacketClickWindow.func_148833_a(CPacketClickWindow.java:12) ~[lf.class:?]
        at net.minecraft.network.PacketThreadUtil.lambda$checkThreadAndEnqueue$0(PacketThreadUtil.java:16) ~[hv.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_275]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_275]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
        ... 5 more
[11:38:22 FATAL]: Error executing task
 java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: key
        at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_275]
        at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_275]
        at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:846) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:467) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:784) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:630) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275]
Caused by: java.lang.IllegalArgumentException: key
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122) ~[minecraft_server.1.12.2.jar:?]
        at org.bukkit.NamespacedKey.<init>(NamespacedKey.java:48) ~[NamespacedKey.class:?]
        at org.bukkit.craftbukkit.v1_12_R1.util.CraftNamespacedKey.fromMinecraft(CraftNamespacedKey.java:16) ~[CraftNamespacedKey.class:?]
        at net.minecraftforge.oredict.ShapedOreRecipe.toBukkitRecipe(ShapedOreRecipe.java:262) ~[ShapedOreRecipe.class:?]
        at net.minecraftforge.oredict.ShapedOreRecipe.toBukkitRecipe(ShapedOreRecipe.java:54) ~[ShapedOreRecipe.class:?]
        at com.mohistmc.recipe.RecipeUtils.toBukkitRecipe(RecipeUtils.java:15) ~[RecipeUtils.class:?]
        at org.bukkit.craftbukkit.v1_12_R1.inventory.CraftInventoryCrafting.getRecipe(CraftInventoryCrafting.java:122) ~[CraftInventoryCrafting.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147351_a(NetHandlerPlayServer.java:2102) ~[pa.class:?]
        at net.minecraft.network.play.client.CPacketClickWindow.func_148833_a(CPacketClickWindow.java:38) ~[lf.class:?]
        at net.minecraft.network.play.client.CPacketClickWindow.func_148833_a(CPacketClickWindow.java:12) ~[lf.class:?]
        at net.minecraft.network.PacketThreadUtil.lambda$checkThreadAndEnqueue$0(PacketThreadUtil.java:16) ~[hv.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_275]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_275]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
        ... 5 more
[11:38:22 FATAL]: Error executing task
 java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: key
        at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_275]
        at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_275]
        at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:846) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:467) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:784) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:630) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275]
Caused by: java.lang.IllegalArgumentException: key
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122) ~[minecraft_server.1.12.2.jar:?]
        at org.bukkit.NamespacedKey.<init>(NamespacedKey.java:48) ~[NamespacedKey.class:?]
        at org.bukkit.craftbukkit.v1_12_R1.util.CraftNamespacedKey.fromMinecraft(CraftNamespacedKey.java:16) ~[CraftNamespacedKey.class:?]
        at net.minecraftforge.oredict.ShapedOreRecipe.toBukkitRecipe(ShapedOreRecipe.java:262) ~[ShapedOreRecipe.class:?]
        at net.minecraftforge.oredict.ShapedOreRecipe.toBukkitRecipe(ShapedOreRecipe.java:54) ~[ShapedOreRecipe.class:?]
        at com.mohistmc.recipe.RecipeUtils.toBukkitRecipe(RecipeUtils.java:15) ~[RecipeUtils.class:?]
        at org.bukkit.craftbukkit.v1_12_R1.inventory.CraftInventoryCrafting.getRecipe(CraftInventoryCrafting.java:122) ~[CraftInventoryCrafting.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147351_a(NetHandlerPlayServer.java:2102) ~[pa.class:?]
        at net.minecraft.network.play.client.CPacketClickWindow.func_148833_a(CPacketClickWindow.java:38) ~[lf.class:?]
        at net.minecraft.network.play.client.CPacketClickWindow.func_148833_a(CPacketClickWindow.java:12) ~[lf.class:?]
        at net.minecraft.network.PacketThreadUtil.lambda$checkThreadAndEnqueue$0(PacketThreadUtil.java:16) ~[hv.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_275]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_275]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
        ... 5 more
[11:38:23 FATAL]: Error executing task
 java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: key
        at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_275]
        at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_275]
        at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:846) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:467) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:784) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:630) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275]
Caused by: java.lang.IllegalArgumentException: key
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122) ~[minecraft_server.1.12.2.jar:?]
        at org.bukkit.NamespacedKey.<init>(NamespacedKey.java:48) ~[NamespacedKey.class:?]
        at org.bukkit.craftbukkit.v1_12_R1.util.CraftNamespacedKey.fromMinecraft(CraftNamespacedKey.java:16) ~[CraftNamespacedKey.class:?]
        at net.minecraftforge.oredict.ShapedOreRecipe.toBukkitRecipe(ShapedOreRecipe.java:262) ~[ShapedOreRecipe.class:?]
        at net.minecraftforge.oredict.ShapedOreRecipe.toBukkitRecipe(ShapedOreRecipe.java:54) ~[ShapedOreRecipe.class:?]
        at com.mohistmc.recipe.RecipeUtils.toBukkitRecipe(RecipeUtils.java:15) ~[RecipeUtils.class:?]
        at org.bukkit.craftbukkit.v1_12_R1.inventory.CraftInventoryCrafting.getRecipe(CraftInventoryCrafting.java:122) ~[CraftInventoryCrafting.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147351_a(NetHandlerPlayServer.java:2102) ~[pa.class:?]
        at net.minecraft.network.play.client.CPacketClickWindow.func_148833_a(CPacketClickWindow.java:38) ~[lf.class:?]
        at net.minecraft.network.play.client.CPacketClickWindow.func_148833_a(CPacketClickWindow.java:12) ~[lf.class:?]
        at net.minecraft.network.PacketThreadUtil.lambda$checkThreadAndEnqueue$0(PacketThreadUtil.java:16) ~[hv.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_275]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_275]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
        ... 5 more
[11:38:30 FATAL]: Error executing task
 java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: key
        at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_275]
        at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_275]
        at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:846) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:467) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:784) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:630) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275]
Caused by: java.lang.IllegalArgumentException: key
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122) ~[minecraft_server.1.12.2.jar:?]
        at org.bukkit.NamespacedKey.<init>(NamespacedKey.java:48) ~[NamespacedKey.class:?]
        at org.bukkit.craftbukkit.v1_12_R1.util.CraftNamespacedKey.fromMinecraft(CraftNamespacedKey.java:16) ~[CraftNamespacedKey.class:?]
        at net.minecraftforge.oredict.ShapedOreRecipe.toBukkitRecipe(ShapedOreRecipe.java:262) ~[ShapedOreRecipe.class:?]
        at net.minecraftforge.oredict.ShapedOreRecipe.toBukkitRecipe(ShapedOreRecipe.java:54) ~[ShapedOreRecipe.class:?]
        at com.mohistmc.recipe.RecipeUtils.toBukkitRecipe(RecipeUtils.java:15) ~[RecipeUtils.class:?]
        at org.bukkit.craftbukkit.v1_12_R1.inventory.CraftInventoryCrafting.getRecipe(CraftInventoryCrafting.java:122) ~[CraftInventoryCrafting.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147351_a(NetHandlerPlayServer.java:2102) ~[pa.class:?]
        at net.minecraft.network.play.client.CPacketClickWindow.func_148833_a(CPacketClickWindow.java:38) ~[lf.class:?]
        at net.minecraft.network.play.client.CPacketClickWindow.func_148833_a(CPacketClickWindow.java:12) ~[lf.class:?]
        at net.minecraft.network.PacketThreadUtil.lambda$checkThreadAndEnqueue$0(PacketThreadUtil.java:16) ~[hv.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_275]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_275]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
        ... 5 more
[11:38:47 FATAL]: Error executing task
 java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: key
        at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_275]
        at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_275]
        at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:846) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:467) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:784) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:630) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275]
Caused by: java.lang.IllegalArgumentException: key
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122) ~[minecraft_server.1.12.2.jar:?]
        at org.bukkit.NamespacedKey.<init>(NamespacedKey.java:48) ~[NamespacedKey.class:?]
        at org.bukkit.craftbukkit.v1_12_R1.util.CraftNamespacedKey.fromMinecraft(CraftNamespacedKey.java:16) ~[CraftNamespacedKey.class:?]
        at net.minecraftforge.oredict.ShapedOreRecipe.toBukkitRecipe(ShapedOreRecipe.java:262) ~[ShapedOreRecipe.class:?]
        at net.minecraftforge.oredict.ShapedOreRecipe.toBukkitRecipe(ShapedOreRecipe.java:54) ~[ShapedOreRecipe.class:?]
        at com.mohistmc.recipe.RecipeUtils.toBukkitRecipe(RecipeUtils.java:15) ~[RecipeUtils.class:?]
        at org.bukkit.craftbukkit.v1_12_R1.inventory.CraftInventoryCrafting.getRecipe(CraftInventoryCrafting.java:122) ~[CraftInventoryCrafting.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147351_a(NetHandlerPlayServer.java:2102) ~[pa.class:?]
        at net.minecraft.network.play.client.CPacketClickWindow.func_148833_a(CPacketClickWindow.java:38) ~[lf.class:?]
        at net.minecraft.network.play.client.CPacketClickWindow.func_148833_a(CPacketClickWindow.java:12) ~[lf.class:?]
        at net.minecraft.network.PacketThreadUtil.lambda$checkThreadAndEnqueue$0(PacketThreadUtil.java:16) ~[hv.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_275]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_275]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
        ... 5 more
[11:40:02 FATAL]: Error executing task
 java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: key
        at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_275]
        at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_275]
        at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:846) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:467) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:784) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:630) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275]
Caused by: java.lang.IllegalArgumentException: key
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122) ~[minecraft_server.1.12.2.jar:?]
        at org.bukkit.NamespacedKey.<init>(NamespacedKey.java:48) ~[NamespacedKey.class:?]
        at org.bukkit.craftbukkit.v1_12_R1.util.CraftNamespacedKey.fromMinecraft(CraftNamespacedKey.java:16) ~[CraftNamespacedKey.class:?]
        at net.minecraftforge.oredict.ShapedOreRecipe.toBukkitRecipe(ShapedOreRecipe.java:262) ~[ShapedOreRecipe.class:?]
        at net.minecraftforge.oredict.ShapedOreRecipe.toBukkitRecipe(ShapedOreRecipe.java:54) ~[ShapedOreRecipe.class:?]
        at com.mohistmc.recipe.RecipeUtils.toBukkitRecipe(RecipeUtils.java:15) ~[RecipeUtils.class:?]
        at org.bukkit.craftbukkit.v1_12_R1.inventory.CraftInventoryCrafting.getRecipe(CraftInventoryCrafting.java:122) ~[CraftInventoryCrafting.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147351_a(NetHandlerPlayServer.java:2102) ~[pa.class:?]
        at net.minecraft.network.play.client.CPacketClickWindow.func_148833_a(CPacketClickWindow.java:38) ~[lf.class:?]
        at net.minecraft.network.play.client.CPacketClickWindow.func_148833_a(CPacketClickWindow.java:12) ~[lf.class:?]
        at net.minecraft.network.PacketThreadUtil.lambda$checkThreadAndEnqueue$0(PacketThreadUtil.java:16) ~[hv.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_275]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_275]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
        ... 5 more
[11:40:25 FATAL]: Error executing task
 java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: key
        at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_275]
        at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_275]
        at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:846) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:467) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:784) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:630) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275]
Caused by: java.lang.IllegalArgumentException: key
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122) ~[minecraft_server.1.12.2.jar:?]
        at org.bukkit.NamespacedKey.<init>(NamespacedKey.java:48) ~[NamespacedKey.class:?]
        at org.bukkit.craftbukkit.v1_12_R1.util.CraftNamespacedKey.fromMinecraft(CraftNamespacedKey.java:16) ~[CraftNamespacedKey.class:?]
        at net.minecraftforge.oredict.ShapedOreRecipe.toBukkitRecipe(ShapedOreRecipe.java:262) ~[ShapedOreRecipe.class:?]
        at net.minecraftforge.oredict.ShapedOreRecipe.toBukkitRecipe(ShapedOreRecipe.java:54) ~[ShapedOreRecipe.class:?]
        at com.mohistmc.recipe.RecipeUtils.toBukkitRecipe(RecipeUtils.java:15) ~[RecipeUtils.class:?]
        at org.bukkit.craftbukkit.v1_12_R1.inventory.CraftInventoryCrafting.getRecipe(CraftInventoryCrafting.java:122) ~[CraftInventoryCrafting.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147351_a(NetHandlerPlayServer.java:2102) ~[pa.class:?]
        at net.minecraft.network.play.client.CPacketClickWindow.func_148833_a(CPacketClickWindow.java:38) ~[lf.class:?]
        at net.minecraft.network.play.client.CPacketClickWindow.func_148833_a(CPacketClickWindow.java:12) ~[lf.class:?]
        at net.minecraft.network.PacketThreadUtil.lambda$checkThreadAndEnqueue$0(PacketThreadUtil.java:16) ~[hv.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_275]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_275]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
        ... 5 more
```

**Comment by Shawiizz** [comment]
Hi, please look at [this](https://github.com/Mohist-Community/Mohist/issues/892#issuecomment-774463050) comment ^^
