### ISSUE TITLE
Errors when reloading dynmap v3.0-SNAPSHOT-mohist with Mohist version 1.12.2-185

### ISSUE THREAD

**Issue by BillZhucn** [Teneted/Tenet#887]
The only file I modified is world.txt. here it is: https://pastebin.com/UiHkRuTC
It is in a valid YAML form.
When reload dynmap this error appears.

```
version
[20:31:36 INFO]: This server is running Mohist version 1.12.2-185 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT, Forge version 14.23.5.2855)
```
```
dynmap reload
[20:26:02 INFO]: Reloading Dynmap...
[20:26:02 INFO]: 正在禁用 dynmap v3.0-SNAPSHOT-mohist
[20:26:02 INFO]: [dynmap] Unloaded 11 components.
[20:26:02 INFO]: [dynmap] Stopping map renderer...
[20:26:03 INFO]: [dynmap] Saved 47 pending tile renders in world 'world'
[20:26:03 INFO]: [dynmap] Disabled
[20:26:03 INFO]: 正在启用 dynmap v3.0-SNAPSHOT-mohist
[20:26:03 ERROR]: 使用了未注册的插件类加载器启用插件 dynmap v3.0-SNAPSHOT-mohist
[20:26:03 INFO]: [dynmap] Starting Scheduled Write Job (markerAPI).
[20:26:03 ERROR]: Invalid BasicBlock. type: 1, meta: 10
[20:26:03 ERROR]: Invalid BasicBlock. type: 1, meta: 11
[20:26:03 ERROR]: Invalid BasicBlock. type: 1, meta: 12
[20:26:03 ERROR]: Invalid BasicBlock. type: 1, meta: 13
[20:26:03 ERROR]: Invalid BasicBlock. type: 1, meta: 14
[20:26:03 ERROR]: Invalid BasicBlock. type: 1, meta: 15
[20:26:03 INFO]: [dynmap] Using LuckPerms 5.2.35 for access control
[20:26:03 INFO]: [dynmap] Mod Support processing completed
[20:26:04 ERROR]: 启用 dynmap v3.0-SNAPSHOT-mohist 时发生错误 (它是最新的吗？)
 java.lang.NoClassDefFoundError: org/dynmap/snakeyaml/parser/ParserImpl$ParseDocumentContent
        at org.dynmap.snakeyaml.parser.ParserImpl$ParseDocumentStart.produce(ParserImpl.java:233) ~[?:?]
        at org.dynmap.snakeyaml.parser.ParserImpl$ParseImplicitDocumentStart.produce(ParserImpl.java:207) ~[?:?]
        at org.dynmap.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:158) ~[?:?]
        at org.dynmap.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:148) ~[?:?]
        at org.dynmap.snakeyaml.composer.Composer.getSingleNode(Composer.java:107) ~[?:?]
        at org.dynmap.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:139) ~[?:?]
        at org.dynmap.snakeyaml.Yaml.loadFromReader(Yaml.java:524) ~[?:?]
        at org.dynmap.snakeyaml.Yaml.load(Yaml.java:467) ~[?:?]
        at org.dynmap.ConfigurationNode.load(ConfigurationNode.java:87) ~[?:?]
        at org.dynmap.DynmapCore.enableCore(DynmapCore.java:486) ~[?:?]
        at org.dynmap.bukkit.DynmapPlugin.doEnable(DynmapPlugin.java:930) ~[?:?]
        at org.dynmap.bukkit.DynmapPlugin.onEnable(DynmapPlugin.java:910) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:177) ~[JavaPlugin.class:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:318) [JavaPluginLoader.class:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:399) [SimplePluginManager.class:?]
        at org.dynmap.bukkit.DynmapPlugin$BukkitServer.reload(DynmapPlugin.java:251) [Dynmap-3.0-SNAPSHOT-mohist.jar:?]
        at org.dynmap.DynmapCore.processCommand(DynmapCore.java:1446) [Dynmap-3.0-SNAPSHOT-mohist.jar:?]
        at org.dynmap.bukkit.DynmapPlugin.onCommand(DynmapPlugin.java:1003) [Dynmap-3.0-SNAPSHOT-mohist.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:43) [PluginCommand.class:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) [SimpleCommandMap.class:?]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:752) [CraftServer.class:?]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchServerCommand(CraftServer.java:738) [CraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71333_ah(DedicatedServer.java:510) [nz.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:468) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:784) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:630) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275]
Caused by: java.lang.ClassNotFoundException: Failed to remap class org.dynmap.snakeyaml.parser.ParserImpl$ParseDocumentContent
        at org.bukkit.plugin.java.PluginClassLoader.remappedFindClass(PluginClassLoader.java:190) ~[PluginClassLoader.class:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:104) ~[PluginClassLoader.class:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:81) ~[PluginClassLoader.class:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_275]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_275]
        ... 27 more
Caused by: java.lang.IllegalStateException: zip file closed
        at java.util.zip.ZipFile.ensureOpen(ZipFile.java:686) ~[?:1.8.0_275]
        at java.util.zip.ZipFile.getEntry(ZipFile.java:315) ~[?:1.8.0_275]
        at java.util.jar.JarFile.getEntry(JarFile.java:240) ~[?:1.8.0_275]
        at java.util.jar.JarFile.getJarEntry(JarFile.java:223) ~[?:1.8.0_275]
        at org.bukkit.plugin.java.PluginClassLoader.remappedFindClass(PluginClassLoader.java:156) ~[PluginClassLoader.class:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:104) ~[PluginClassLoader.class:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:81) ~[PluginClassLoader.class:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_275]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_275]
        ... 27 more
[20:26:04 INFO]: Dynmap reloaded
dynmap
[20:26:25 INFO]: Dynmap failed to initialize properly: commands not available
```

**Comment by BillZhucn** [comment]
I restart the server and dynmap works fine. 
When I reload it, another error appears. It should be the problem of reloading this plugin.

**Comment by Shawiizz** [comment]
Just don't use reload command. It's a dangerous command and it shouldn't be used at all.
