### ISSUE TITLE
[1.12.2] Error when player craft some itens

### ISSUE THREAD

**Issue by brunoxkk0** [Teneted/Tenet#892]
### Information
Mohist version 1.12.2-185 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT, Forge version 14.23.5.2854)

### Description
When a player tries to craft items on the server, sometimes this error appears on the console.

### Error
``` java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: key
        at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_275]
        at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_275]
        at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:846) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:467) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:784) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:630) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275]
Caused by: java.lang.IllegalArgumentException: key
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122) ~[minecraft_server.1.12.2.jar:?]
        at org.bukkit.NamespacedKey.<init>(NamespacedKey.java:48) ~[NamespacedKey.class:?]
        at org.bukkit.craftbukkit.v1_12_R1.util.CraftNamespacedKey.fromMinecraft(CraftNamespacedKey.java:16) ~[CraftNamespacedKey.class:?]
        at net.minecraftforge.oredict.ShapedOreRecipe.toBukkitRecipe(ShapedOreRecipe.java:262) ~[ShapedOreRecipe.class:?]
        at net.minecraftforge.oredict.ShapedOreRecipe.toBukkitRecipe(ShapedOreRecipe.java:54) ~[ShapedOreRecipe.class:?]
        at com.mohistmc.recipe.RecipeUtils.toBukkitRecipe(RecipeUtils.java:15) ~[RecipeUtils.class:?]
        at org.bukkit.craftbukkit.v1_12_R1.inventory.CraftInventoryCrafting.getRecipe(CraftInventoryCrafting.java:122) ~[CraftInventoryCrafting.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147351_a(NetHandlerPlayServer.java:2102) ~[pa.class:?]
        at net.minecraft.network.play.client.CPacketClickWindow.func_148833_a(CPacketClickWindow.java:38) ~[lf.class:?]
        at net.minecraft.network.play.client.CPacketClickWindow.func_148833_a(CPacketClickWindow.java:12) ~[lf.class:?]
        at net.minecraft.network.PacketThreadUtil.lambda$checkThreadAndEnqueue$0(PacketThreadUtil.java:16) ~[hv.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_275]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_275]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
        ... 5 more

**Comment by SekiAlpha** [comment]
Include plugin and mod details too.

**Comment by brunoxkk0** [comment]
This error looks like some other issues: #879 #863 #886

**Comment by EverNife** [comment]
Add IllegalArgumentException here 

https://github.com/Mohist-Community/Mohist/blob/1.12.2/src/main/java/com/mohistmc/recipe/RecipeUtils.java#L16

May fix this issue

**Comment by Shawiizz** [comment]
i merged the pr, try [this](https://ci.codemc.io/job/Mohist-Community/job/Mohist-1.12.2/186/) build
