### ISSUE TITLE
[1.12.2] NickNamer plugin error

### ISSUE THREAD

**Issue by Ru-Nan-i** [Teneted/Tenet#893]
https://www.spigotmc.org/resources/nicknamer-integrated-api.5341/

This plugin is deprecated on mohist server.

**Comment by Shawiizz** [comment]
Hi, can you give useful informations like which mohist build are you using and also give your logs please ?

**Comment by Ru-Nan-i** [comment]
I use mohist1.12.2 185
This plugin need to PacketListenerAPI


[23:13:42 INFO]: [NickNamer] Java Version: 1.8.0_281
[23:13:42 INFO]: Enabling NickNamer v3.18.6-SNAPSHOT
[23:13:42 INFO]: [ReflectionHelper/MinecraftVersion] I am loaded from package org.inventivetalent.nicknamer.reflection.minecraft
[23:13:42 INFO]: [ReflectionHelper/MinecraftVersion] Version is v1_12_R1 (11201)
[23:13:42 ERROR]: Error occurred while enabling NickNamer v3.18.6-SNAPSHOT (Is it up to date?)
 java.lang.ExceptionInInitializerError: null
        at org.inventivetalent.nicknamer.api.NickNamerAPI.init(NickNamerAPI.java:140) ~[?:?]
        at org.inventivetalent.apihelper.RegisteredAPI.init(RegisteredAPI.java:55) ~[?:?]
        at org.inventivetalent.apihelper.APIManager.initAPI(APIManager.java:96) ~[?:?]
        at org.inventivetalent.apihelper.APIManager.initAPI(APIManager.java:127) ~[?:?]
        at org.inventivetalent.nicknamer.NickNamerPlugin.onEnable(NickNamerPlugin.java:181) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:177) ~[JavaPlugin.class:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:318) ~[JavaPluginLoader.class:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:399) ~[SimplePluginManager.class:?]
        at com.mohistmc.util.pluginmanager.PluginManagers.loadPluginCommand(PluginManagers.java:55) ~[PluginManagers.class:?]
        at com.mohistmc.command.PluginCommand.execute(PluginCommand.java:48) ~[PluginCommand.class:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[SimpleCommandMap.class:?]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:752) ~[CraftServer.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:1588) ~[pa.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:1427) ~[pa.class:?]
        at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(CPacketChatMessage.java:46) ~[la.class:?]
        at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(CPacketChatMessage.java:9) ~[la.class:?]
        at net.minecraft.network.PacketThreadUtil.lambda$checkThreadAndEnqueue$0(PacketThreadUtil.java:16) ~[hv.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_281]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_281]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:846) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:467) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:784) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:630) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_281]
Caused by: java.lang.IllegalArgumentException: class cannot be null
        at org.inventivetalent.nicknamer.reflection.resolver.MemberResolver.<init>(MemberResolver.java:20) ~[?:?]
        at org.inventivetalent.nicknamer.reflection.resolver.MethodResolver.<init>(MethodResolver.java:14) ~[?:?]
        at org.inventivetalent.nicknamer.api.PacketListener.<clinit>(PacketListener.java:69) ~[?:?]
        ... 25 more

**Comment by wdog5** [comment]
Is it up to date?
It is normal

**Comment by Ru-Nan-i** [comment]
Yes it is up to date

**Comment by wdog5** [comment]
Is it up to date?
This information you don‘t care，it is normal

**Comment by SparkGNRK** [comment]
Working using latest 1.12.2 supporting versions: NickNamer_v3.14.1-SNAPSHOT & PacketListenerAPI_v3.7.9-SNAPSHOT
