### ISSUE TITLE
Butcher

### ISSUE THREAD

**Issue by Skyere** [Teneted/Tenet#895]
Butcher doesn't kill entity(
Mohist 1.12.2 last build
World edit from mohist

**Comment by Shawiizz** [comment]
Hi, do you have any error to give please ?

**Comment by Skyere** [comment]
>butcher
[16:41:03 INFO]: Running 1.12 registry dumper!
[16:41:04 WARN]: java.lang.IllegalArgumentException: Cannot set property PropertyDirection{name=facing, clazz=class net.minecraft.util.EnumFacing, values=[north, south, west, east]} to down on block immersiveruins:iegencon1, it is not an allowed value
[16:41:04 WARN]:        at pl.asie.foamfix.common.FoamyBlockState.func_177226_a(FoamyBlockState.java:59)
[16:41:04 WARN]:        at net.mcreator.immersiveruins.block.BlockIegencon1$BlockCustom.func_176203_a(BlockIegencon1.java:118)
[16:41:04 WARN]:        at com.boydti.fawe.bukkit.v1_12.NMSRegistryDumper.dataValues(NMSRegistryDumper.java:112)
[16:41:04 WARN]:        at com.boydti.fawe.bukkit.v1_12.NMSRegistryDumper.getStates(NMSRegistryDumper.java:76)
[16:41:04 WARN]:        at com.boydti.fawe.bukkit.v1_12.NMSRegistryDumper.getProperties(NMSRegistryDumper.java:66)
[16:41:04 WARN]:        at com.boydti.fawe.bukkit.v1_12.NMSRegistryDumper.run(NMSRegistryDumper.java:53)
[16:41:04 WARN]:        at com.boydti.fawe.bukkit.FaweBukkit.getVersion(FaweBukkit.java:606)
[16:41:04 WARN]:        at com.boydti.fawe.bukkit.FaweBukkit.getQueue(FaweBukkit.java:631)
[16:41:04 WARN]:        at com.boydti.fawe.bukkit.FaweBukkit.getNewQueue(FaweBukkit.java:407)
[16:41:04 WARN]:        at com.boydti.fawe.util.SetQueue.getNewQueue(SetQueue.java:248)
[16:41:04 WARN]:        at com.boydti.fawe.object.FawePlayer.getFaweQueue(FawePlayer.java:413)
[16:41:04 WARN]:        at com.sk89q.worldedit.EditSession.<init>(EditSession.java:226)
[16:41:04 WARN]:        at com.boydti.fawe.util.EditSessionBuilder.build(EditSessionBuilder.java:195)
[16:41:04 WARN]:        at com.sk89q.worldedit.LocalSession.createEditSession(LocalSession.java:1343)
[16:41:04 WARN]:        at com.sk89q.worldedit.command.UtilityCommands.butcher(UtilityCommands.java:510)
[16:41:04 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[16:41:04 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[16:41:04 WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[16:41:04 WARN]:        at java.lang.reflect.Method.invoke(Method.java:498)
[16:41:04 WARN]:        at com.sk89q.worldedit.util.command.parametric.ParametricCallable.call(ParametricCallable.java:265)
[16:41:04 WARN]:        at com.sk89q.worldedit.util.command.SimpleDispatcher.call(SimpleDispatcher.java:133)
[16:41:04 WARN]:        at com.sk89q.worldedit.extension.platform.CommandManager$2.get(CommandManager.java:413)
[16:41:04 WARN]:        at com.sk89q.worldedit.extension.platform.CommandManager.handleCommandTask(CommandManager.java:436)
[16:41:04 WARN]:        at com.sk89q.worldedit.extension.platform.CommandManager.handleCommandOnCurrentThread(CommandManager.java:417)
[16:41:04 WARN]:        at com.sk89q.worldedit.extension.platform.CommandManager$3$1.run(CommandManager.java:535)
[16:41:04 WARN]:        at com.boydti.fawe.object.FawePlayer.lambda$runAction$2(FawePlayer.java:341)
[16:41:04 WARN]:        at com.boydti.fawe.object.task.SimpleAsyncNotifyQueue.operate(SimpleAsyncNotifyQueue.java:25)
[16:41:04 WARN]:        at com.boydti.fawe.object.task.AsyncNotifyQueue$1.run(AsyncNotifyQueue.java:15)
[16:41:04 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:64)
[16:41:04 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:50)
[16:41:04 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[16:41:04 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[16:41:04 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[16:41:04 WARN]:        at java.lang.Thread.run(Thread.java:748)
[16:41:04 INFO]: Using adapter: com.boydti.fawe.bukkit.v1_12.FaweAdapter_1_12@2ad42ede
[16:41:04 INFO]: =========================================
[16:41:04 INFO]: (FAWE) Potentially unsafe extent blocked: net.coreprotect.worldedit.CoreProtectLogger
[16:41:04 INFO]: (FAWE)  - For area restrictions, it is recommended to use the FaweAPI
[16:41:04 INFO]: (FAWE)  - For block logging, it is recommended to use use BlocksHub
[16:41:04 INFO]: (FAWE)  - To allow this plugin add it to the FAWE `allowed-plugins` list
[16:41:04 INFO]: (FAWE)  - To hide this message set `debug` to false in the FAWE config.yml
[16:41:04 INFO]: (FAWE) Note on CoreProtect: 
[16:41:04 INFO]: (FAWE)  - If you disable CP's WE logger (CP config) and this still shows, please update CP
[16:41:04 INFO]: (FAWE)  - Use BlocksHub and set `debug` false in the FAWE config
[16:41:04 INFO]: (FAWE) Killed 37 entities in a radius of -1.

**Comment by Skyere** [comment]
but after this all entity are alive(

**Comment by SparkGNRK** [comment]
Working, commands need args to also kills passives animals (//butcher -a)
