### ISSUE TITLE
Mod Crash - TheAbyss - 1.16.5

### ISSUE THREAD

**Issue by Zekirax** [Teneted/Tenet#905]
with mohist 1.16.5-345

[10:52:14 ERROR]: Could not find parent net/minecraft/client/renderer/entity/layers/LayerRenderer for class net/yezon/theabyss/entity/NetherScorpionEntity$GlowingLayer in classloader cpw.mods.modlauncher.TransformingClassLoader@35e8316e on thread Thread[Server thread,5,SERVER]
[10:52:14 ERROR]: An error occurred building event handler
java.lang.ClassNotFoundException: net.minecraft.client.renderer.entity.layers.LayerRenderer
        at java.lang.ClassLoader.findClass(ClassLoader.java:523) ~[?:1.8.0_241] {}
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_241] {}
        at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:106) ~[modlauncher-8.0.9.jar:?] {re:classloading}
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_241] {}
        at net.minecraftforge.eventbus.EventSubclassTransformer.buildEvents(EventSubclassTransformer.java:62) ~[eventbus-4.0.0.jar:?] {}
        at net.minecraftforge.eventbus.EventSubclassTransformer.transform(EventSubclassTransformer.java:44) ~[eventbus-4.0.0.jar:?] {}
        at net.minecraftforge.eventbus.EventBusEngine.processClass(EventBusEngine.java:21) ~[eventbus-4.0.0.jar:?] {}
        at net.minecraftforge.eventbus.service.ModLauncherService.processClassWithFlags(ModLauncherService.java:20) ~[eventbus-4.0.0.jar:4.0.0+65+master.6080a3f] {}
        at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:85) ~[modlauncher-8.0.9.jar:?] {}
        at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-8.0.9.jar:?] {}
        at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:265) ~[modlauncher-8.0.9.jar:?] {}
        at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136) ~[modlauncher-8.0.9.jar:?] {re:classloading}
        at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98) ~[modlauncher-8.0.9.jar:?] {re:classloading}
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_241] {}
        at java.lang.Class.getDeclaringClass0(Native Method) ~[?:1.8.0_241] {}
        at java.lang.Class.getDeclaringClass(Class.java:1235) ~[?:1.8.0_241] {}
        at java.lang.Class.getEnclosingClass(Class.java:1277) ~[?:1.8.0_241] {}
        at java.lang.Class.getSimpleBinaryName(Class.java:1443) ~[?:1.8.0_241] {}
        at java.lang.Class.getSimpleName(Class.java:1309) ~[?:1.8.0_241] {}
        at org.bukkit.craftbukkit.v1_16_R3.SpigotTimings.getEntityTimings(SpigotTimings.java:94) ~[forge:1.16.5-345] {re:classloading}
        at net.minecraft.entity.Entity.<init>(Entity.java:250) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:abnormals_core.mixins.json:EntityMixin,pl:mixin:APP:extraboats.mixins.json:EntityMixin,pl:mixin:APP:quark.mixins.json:EntityMixin,pl:mixin:APP:betterendforge.mixins.json:EntityMixin,pl:mixin:APP:structure_gel.mixins.json:EntityMixin,pl:mixin:APP:imm_ptl_mixins.json:common.collision.MixinEntity,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.entity.LivingEntity.<init>(LivingEntity.java:244) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:caelus.mixins.json:LivingEntityMixin,pl:mixin:APP:imm_ptl_mixins.json:common.MixinLivingEntity,pl:mixin:APP:imm_ptl_mixins.json:common.collision.MixinLivingEntity_C,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.entity.MobEntity.<init>(MobEntity.java:121) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.entity.CreatureEntity.<init>(CreatureEntity.java:15) ~[?:?] {re:mixin,re:classloading}
        at net.minecraft.entity.monster.MonsterEntity.<init>(SourceFile:30) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:betterendforge.mixins.json:MonsterEntityMixin,pl:mixin:A}
        at net.minecraft.entity.monster.SpiderEntity.<init>(SpiderEntity.java:50) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:dungeons_mobs.mixins.json:SpiderEntityMixin,pl:mixin:A}
        at net.yezon.theabyss.entity.NetherScorpionEntity$CustomEntity.<init>(NetherScorpionEntity.java:130) ~[theabyss:?] {re:classloading}
        at net.minecraft.entity.EntityType.func_200721_a(EntityType.java:454) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at xreliquary.items.MobCharmRegistry.isNonBossMob(MobCharmRegistry.java:88) ~[xreliquary:1.16.3-1.3.4.1061] {re:classloading}
        at xreliquary.items.MobCharmRegistry.registerDynamicCharmDefinitions(MobCharmRegistry.java:80) ~[xreliquary:1.16.3-1.3.4.1061] {re:classloading}
        at xreliquary.Reliquary.worldStart(Reliquary.java:58) ~[xreliquary:1.16.3-1.3.4.1061] {re:classloading}
        at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-4.0.0.jar:?] {}
        at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-4.0.0.jar:?] {}
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
        at net.minecraft.server.MinecraftServer.func_240787_a_(MinecraftServer.java:435) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:imm_ptl_mixins.json:common.MixinMinecraftServer,pl:mixin:APP:imm_ptl_mixins.json:common.portal_generation.MixinMinecraftServer_P,pl:mixin:APP:imm_ptl_peripheral_mixins.json:common.alternate_dimension.MixinMinecraftServer_A,pl:mixin:APP:imm_ptl_peripheral_mixins.json:common.altius_world.MixinMinecraftServer_A,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_240800_l__(MinecraftServer.java:356) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:imm_ptl_mixins.json:common.MixinMinecraftServer,pl:mixin:APP:imm_ptl_mixins.json:common.portal_generation.MixinMinecraftServer_P,pl:mixin:APP:imm_ptl_peripheral_mixins.json:common.alternate_dimension.MixinMinecraftServer_A,pl:mixin:APP:imm_ptl_peripheral_mixins.json:common.altius_world.MixinMinecraftServer_A,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:217) ~[?:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:723) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:imm_ptl_mixins.json:common.MixinMinecraftServer,pl:mixin:APP:imm_ptl_mixins.json:common.portal_generation.MixinMinecraftServer_P,pl:mixin:APP:imm_ptl_peripheral_mixins.json:common.alternate_dimension.MixinMinecraftServer_A,pl:mixin:APP:imm_ptl_peripheral_mixins.json:common.altius_world.MixinMinecraftServer_A,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:276) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:imm_ptl_mixins.json:common.MixinMinecraftServer,pl:mixin:APP:imm_ptl_mixins.json:common.portal_generation.MixinMinecraftServer_P,pl:mixin:APP:imm_ptl_peripheral_mixins.json:common.alternate_dimension.MixinMinecraftServer_A,pl:mixin:APP:imm_ptl_peripheral_mixins.json:common.altius_world.MixinMinecraftServer_A,pl:mixin:A,pl:runtimedistcleaner:A}
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_241] {}
        Suppressed: java.lang.ClassNotFoundException
                at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:282) ~[modlauncher-8.0.9.jar:?] {}
                at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136) ~[modlauncher-8.0.9.jar:?] {re:classloading}
                at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98) ~[modlauncher-8.0.9.jar:?] {re:classloading}
                at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_241] {}
                at net.minecraftforge.eventbus.EventSubclassTransformer.buildEvents(EventSubclassTransformer.java:62) ~[eventbus-4.0.0.jar:?] {}
                at net.minecraftforge.eventbus.EventSubclassTransformer.transform(EventSubclassTransformer.java:44) ~[eventbus-4.0.0.jar:?] {}
                at net.minecraftforge.eventbus.EventBusEngine.processClass(EventBusEngine.java:21) ~[eventbus-4.0.0.jar:?] {}
                at net.minecraftforge.eventbus.service.ModLauncherService.processClassWithFlags(ModLauncherService.java:20) ~[eventbus-4.0.0.jar:4.0.0+65+master.6080a3f] {}
                at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:85) ~[modlauncher-8.0.9.jar:?] {}
                at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-8.0.9.jar:?] {}
                at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:265) ~[modlauncher-8.0.9.jar:?] {}
                at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136) ~[modlauncher-8.0.9.jar:?] {re:classloading}
                at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98) ~[modlauncher-8.0.9.jar:?] {re:classloading}
                at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_241] {}
                at java.lang.Class.getDeclaringClass0(Native Method) ~[?:1.8.0_241] {}
                at java.lang.Class.getDeclaringClass(Class.java:1235) ~[?:1.8.0_241] {}
                at java.lang.Class.getEnclosingClass(Class.java:1277) ~[?:1.8.0_241] {}
                at java.lang.Class.getSimpleBinaryName(Class.java:1443) ~[?:1.8.0_241] {}
                at java.lang.Class.getSimpleName(Class.java:1309) ~[?:1.8.0_241] {}
                at org.bukkit.craftbukkit.v1_16_R3.SpigotTimings.getEntityTimings(SpigotTimings.java:94) ~[forge:1.16.5-345] {re:classloading}
                at net.minecraft.entity.Entity.<init>(Entity.java:250) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:abnormals_core.mixins.json:EntityMixin,pl:mixin:APP:extraboats.mixins.json:EntityMixin,pl:mixin:APP:quark.mixins.json:EntityMixin,pl:mixin:APP:betterendforge.mixins.json:EntityMixin,pl:mixin:APP:structure_gel.mixins.json:EntityMixin,pl:mixin:APP:imm_ptl_mixins.json:common.collision.MixinEntity,pl:mixin:A,pl:runtimedistcleaner:A}
                at net.minecraft.entity.LivingEntity.<init>(LivingEntity.java:244) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:caelus.mixins.json:LivingEntityMixin,pl:mixin:APP:imm_ptl_mixins.json:common.MixinLivingEntity,pl:mixin:APP:imm_ptl_mixins.json:common.collision.MixinLivingEntity_C,pl:mixin:A,pl:runtimedistcleaner:A}
                at net.minecraft.entity.MobEntity.<init>(MobEntity.java:121) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
                at net.minecraft.entity.CreatureEntity.<init>(CreatureEntity.java:15) ~[?:?] {re:mixin,re:classloading}
                at net.minecraft.entity.monster.MonsterEntity.<init>(SourceFile:30) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:betterendforge.mixins.json:MonsterEntityMixin,pl:mixin:A}
                at net.minecraft.entity.monster.SpiderEntity.<init>(SpiderEntity.java:50) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:dungeons_mobs.mixins.json:SpiderEntityMixin,pl:mixin:A}
                at net.yezon.theabyss.entity.NetherScorpionEntity$CustomEntity.<init>(NetherScorpionEntity.java:130) ~[theabyss:?] {re:classloading}
                at net.minecraft.entity.EntityType.func_200721_a(EntityType.java:454) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
                at xreliquary.items.MobCharmRegistry.isNonBossMob(MobCharmRegistry.java:88) ~[xreliquary:1.16.3-1.3.4.1061] {re:classloading}
                at xreliquary.items.MobCharmRegistry.registerDynamicCharmDefinitions(MobCharmRegistry.java:80) ~[xreliquary:1.16.3-1.3.4.1061] {re:classloading}
                at xreliquary.Reliquary.worldStart(Reliquary.java:58) ~[xreliquary:1.16.3-1.3.4.1061] {re:classloading}
                at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-4.0.0.jar:?] {}
                at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-4.0.0.jar:?] {}
                at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
                at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
                at net.minecraft.server.MinecraftServer.func_240787_a_(MinecraftServer.java:435) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:imm_ptl_mixins.json:common.MixinMinecraftServer,pl:mixin:APP:imm_ptl_mixins.json:common.portal_generation.MixinMinecraftServer_P,pl:mixin:APP:imm_ptl_peripheral_mixins.json:common.alternate_dimension.MixinMinecraftServer_A,pl:mixin:APP:imm_ptl_peripheral_mixins.json:common.altius_world.MixinMinecraftServer_A,pl:mixin:A,pl:runtimedistcleaner:A}
                at net.minecraft.server.MinecraftServer.func_240800_l__(MinecraftServer.java:356) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:imm_ptl_mixins.json:common.MixinMinecraftServer,pl:mixin:APP:imm_ptl_mixins.json:common.portal_generation.MixinMinecraftServer_P,pl:mixin:APP:imm_ptl_peripheral_mixins.json:common.alternate_dimension.MixinMinecraftServer_A,pl:mixin:APP:imm_ptl_peripheral_mixins.json:common.altius_world.MixinMinecraftServer_A,pl:mixin:A,pl:runtimedistcleaner:A}
                at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:217) ~[?:?] {re:classloading,pl:accesstransformer:B}
                at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:723) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:imm_ptl_mixins.json:common.MixinMinecraftServer,pl:mixin:APP:imm_ptl_mixins.json:common.portal_generation.MixinMinecraftServer_P,pl:mixin:APP:imm_ptl_peripheral_mixins.json:common.alternate_dimension.MixinMinecraftServer_A,pl:mixin:APP:imm_ptl_peripheral_mixins.json:common.altius_world.MixinMinecraftServer_A,pl:mixin:A,pl:runtimedistcleaner:A}
                at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:276) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:imm_ptl_mixins.json:common.MixinMinecraftServer,pl:mixin:APP:imm_ptl_mixins.json:common.portal_generation.MixinMinecraftServer_P,pl:mixin:APP:imm_ptl_peripheral_mixins.json:common.alternate_dimension.MixinMinecraftServer_A,pl:mixin:APP:imm_ptl_peripheral_mixins.json:common.altius_world.MixinMinecraftServer_A,pl:mixin:A,pl:runtimedistcleaner:A}
                at java.lang.Thread.run(Thread.java:748) [?:1.8.0_241] {}
[10:52:14 FATAL]: Attempted to load class net/yezon/theabyss/entity/NetherScorpionEntity$GlowingLayer for invalid dist DEDICATED_SERVER
[10:52:14 ERROR]: Exception caught during firing event: Attempted to load class net/yezon/theabyss/entity/NetherScorpionEntity$GlowingLayer for invalid dist DEDICATED_SERVER
        Index: 2
        Listeners:
                0: NORMAL
                1: ASM: class com.endertech.minecraft.forge.world.GameWorld$WorldData onWorldLoad(Lnet/minecraftforge/event/world/WorldEvent$Load;)V
                2: net.minecraftforge.eventbus.EventBus$$Lambda$2763/837354325@75286bc3
                3: net.minecraftforge.eventbus.EventBus$$Lambda$2763/837354325@10aaabe3
                4: net.minecraftforge.eventbus.EventBus$$Lambda$2763/837354325@4cd9a8a8
                5: net.minecraftforge.eventbus.EventBus$$Lambda$2763/837354325@55c4f4e5
                6: ASM: class mod.beethoven92.betterendforge.common.event.forge.WorldLoadHandler addDimensionalSpacing(Lnet/minecraftforge/event/world/WorldEvent$Load;)V
                7: ASM: class com.simibubi.create.events.CommonEvents onLoadWorld(Lnet/minecraftforge/event/world/WorldEvent$Load;)V
                8: ASM: class com.github.alexthe666.rats.server.events.CommonEvents worldLoad(Lnet/minecraftforge/event/world/WorldEvent$Load;)V
java.lang.RuntimeException: Attempted to load class net/yezon/theabyss/entity/NetherScorpionEntity$GlowingLayer for invalid dist DEDICATED_SERVER
        at net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:71)
        at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:85)
        at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120)
        at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:265)
        at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136)
        at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        at java.lang.Class.getDeclaringClass0(Native Method)
        at java.lang.Class.getDeclaringClass(Class.java:1235)
        at java.lang.Class.getEnclosingClass(Class.java:1277)
        at java.lang.Class.getSimpleBinaryName(Class.java:1443)
        at java.lang.Class.getSimpleName(Class.java:1309)
        at org.bukkit.craftbukkit.v1_16_R3.SpigotTimings.getEntityTimings(SpigotTimings.java:94)
        at net.minecraft.entity.Entity.<init>(Entity.java:250)
        at net.minecraft.entity.LivingEntity.<init>(LivingEntity.java:244)
        at net.minecraft.entity.MobEntity.<init>(MobEntity.java:121)
        at net.minecraft.entity.CreatureEntity.<init>(CreatureEntity.java:15)
        at net.minecraft.entity.monster.MonsterEntity.<init>(SourceFile:30)
        at net.minecraft.entity.monster.SpiderEntity.<init>(SpiderEntity.java:50)
        at net.yezon.theabyss.entity.NetherScorpionEntity$CustomEntity.<init>(NetherScorpionEntity.java:130)
        at net.minecraft.entity.EntityType.func_200721_a(EntityType.java:454)
        at xreliquary.items.MobCharmRegistry.isNonBossMob(MobCharmRegistry.java:88)
        at xreliquary.items.MobCharmRegistry.registerDynamicCharmDefinitions(MobCharmRegistry.java:80)
        at xreliquary.Reliquary.worldStart(Reliquary.java:58)
        at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247)
        at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239)
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
        at net.minecraft.server.MinecraftServer.func_240787_a_(MinecraftServer.java:435)
        at net.minecraft.server.MinecraftServer.func_240800_l__(MinecraftServer.java:356)
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:217)
        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:723)
        at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:276)
        at java.lang.Thread.run(Thread.java:748)

[10:52:14 ERROR]: Encountered an unexpected exception
[10:52:14 FATAL]: Preparing crash report with UUID fbeac49b-6224-4e5b-88aa-b48c0e1540eb

list of mods:
![image](https://user-images.githubusercontent.com/74112819/107143316-b6bd3080-6934-11eb-81c9-3ab733c195c2.png)

Thanks For help :)

**Comment by laboriens** [comment]
have you tried with the version

TheAbyss 2.0.0 1.16.4
because the version you use is no longer on curseforge

**Comment by Zekirax** [comment]
Yes

**Comment by Zekirax** [comment]
When I put The Abyss alone it's work. It's incompatible with another mod. And with forge it's work.

**Comment by laboriens** [comment]
i see in els log a conflict between the abyss and reliquary

**Comment by Shawiizz** [comment]
Try again. If the issue is still here, tell me and I will reopen this issue.

**Comment by Zekirax** [comment]
[14:49:11 FATAL]: Attempted to load class net/yezon/theabyss/entity/NetherScorpionEntity$GlowingLayer for invalid dist DEDICATED_SERVER
[14:49:11 ERROR]: Exception caught during firing event: Attempted to load class net/yezon/theabyss/entity/NetherScorpionEntity$GlowingLayer for invalid dist DEDICATED_SERVER
        Index: 2
        Listeners:
                0: NORMAL
                1: ASM: class com.endertech.minecraft.forge.world.GameWorld$WorldData onWorldLoad(Lnet/minecraftforge/event/world/WorldEvent$Load;)V
                2: net.minecraftforge.eventbus.EventBus$$Lambda$2756/814470259@255c49a8
                3: net.minecraftforge.eventbus.EventBus$$Lambda$2756/814470259@3d05ad10
                4: net.minecraftforge.eventbus.EventBus$$Lambda$2756/814470259@c15bee1
                5: net.minecraftforge.eventbus.EventBus$$Lambda$2756/814470259@583e4402
                6: ASM: class mod.beethoven92.betterendforge.common.event.forge.WorldLoadHandler addDimensionalSpacing(Lnet/minecraftforge/event/world/WorldEvent$Load;)V
                7: ASM: class com.simibubi.create.events.CommonEvents onLoadWorld(Lnet/minecraftforge/event/world/WorldEvent$Load;)V
                8: ASM: class com.github.alexthe666.rats.server.events.CommonEvents worldLoad(Lnet/minecraftforge/event/world/WorldEvent$Load;)V
java.lang.RuntimeException: Attempted to load class net/yezon/theabyss/entity/NetherScorpionEntity$GlowingLayer for invalid dist DEDICATED_SERVER
        at net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:71)
        at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:85)
        at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120)
        at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:265)
        at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136)
        at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        at java.lang.Class.getDeclaringClass0(Native Method)
        at java.lang.Class.getDeclaringClass(Class.java:1235)
        at java.lang.Class.getEnclosingClass(Class.java:1277)
        at java.lang.Class.getSimpleBinaryName(Class.java:1443)
        at java.lang.Class.getSimpleName(Class.java:1309)
        at org.bukkit.craftbukkit.v1_16_R3.SpigotTimings.getEntityTimings(SpigotTimings.java:94)
        at net.minecraft.entity.Entity.<init>(Entity.java:250)
        at net.minecraft.entity.LivingEntity.<init>(LivingEntity.java:244)
        at net.minecraft.entity.MobEntity.<init>(MobEntity.java:121)
        at net.minecraft.entity.CreatureEntity.<init>(CreatureEntity.java:15)
        at net.minecraft.entity.monster.MonsterEntity.<init>(SourceFile:30)
        at net.minecraft.entity.monster.SpiderEntity.<init>(SpiderEntity.java:50)
        at net.yezon.theabyss.entity.NetherScorpionEntity$CustomEntity.<init>(NetherScorpionEntity.java:132)
        at net.minecraft.entity.EntityType.func_200721_a(EntityType.java:454)
        at xreliquary.items.MobCharmRegistry.isNonBossMob(MobCharmRegistry.java:88)
        at xreliquary.items.MobCharmRegistry.registerDynamicCharmDefinitions(MobCharmRegistry.java:80)
        at xreliquary.Reliquary.worldStart(Reliquary.java:58)
        at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247)
        at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239)
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
        at net.minecraft.server.MinecraftServer.func_240787_a_(MinecraftServer.java:435)
        at net.minecraft.server.MinecraftServer.func_240800_l__(MinecraftServer.java:356)
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:217)
        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:723)
        at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:276)
        at java.lang.Thread.run(Thread.java:748)

I also updated to mohist to vesrion 358.
