### ISSUE TITLE
Connection error

### ISSUE THREAD

**Issue by imagreez** [Teneted/Tenet#930]
```java
io.netty.channel.unix.Errors$NativeIoException: writeAddress(..) failed: Connection reset by peer
        at io.netty.channel.unix.Errors.newIOException(Errors.java:122) ~[netty-all-4.1.24.Final.jar:4.1.24.Final]
        at io.netty.channel.unix.Errors.ioResult(Errors.java:146) ~[netty-all-4.1.24.Final.jar:4.1.24.Final]
        at io.netty.channel.unix.FileDescriptor.writeAddress(FileDescriptor.java:138) ~[netty-all-4.1.24.Final.jar:4.1.24.Final]
        at io.netty.channel.epoll.AbstractEpollChannel.doWriteBytes(AbstractEpollChannel.java:361) ~[netty-all-4.1.24.Final.jar:4.1.24.Final]
        at io.netty.channel.epoll.AbstractEpollStreamChannel.writeBytes(AbstractEpollStreamChannel.java:274) ~[netty-all-4.1.24.Final.jar:4.1.24.Final]
````

**Comment by Shawiizz** [comment]
Same as #241, it's not an issue. Check your network connexion and try again.

**Comment by imagreez** [comment]
its an issue, I tried on magma and it works perfectlythe connection

**Comment by Shawiizz** [comment]
I can't reproduce your issue. And note that this can also happen on a normal forge server.
