### ISSUE TITLE
[1.7.10] ProtocolLib error: unable to retrieve current Minecraft version

### ISSUE THREAD

**Issue by bagomot** [Teneted/Tenet#97]
Mohist build: b53ab74

```
[ProtocolLib] Loading ProtocolLib v3.6.5-SNAPSHOT-b217
[ProtocolLib] [ProtocolLibrary] Unable to retrieve current Minecraft version. Assuming (MC: 1.8.8)
java.lang.ClassCastException: java.lang.Boolean cannot be cast to java.lang.String
        at com.comphenix.protocol.ProtocolConfig.getIgnoreVersionCheck(ProtocolConfig.java:343) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.ProtocolLibrary.verifyMinecraftVersion(ProtocolLibrary.java:474) [ProtocolLib.jar:?]
        at com.comphenix.protocol.ProtocolLibrary.onLoad(ProtocolLibrary.java:216) [ProtocolLib.jar:?]
        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugins(CraftServer.java:349) [CraftServer.class:b53ab74]
        at net.minecraft.world.storage.SaveHandler.initBukkitData(SaveHandler.java:462) [ayq.class:?]
        at net.minecraft.world.storage.SaveHandler.func_75757_d(SaveHandler.java:138) [ayq.class:?]
        at net.minecraft.world.World.<init>(World.java:361) [ahb.class:?]
        at net.minecraft.world.WorldServer.<init>(WorldServer.java:162) [mt.class:?]
        at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:378) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:338) [lt.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:646) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_241]
```

**Comment by Mgazul** [comment]
use https://github.com/dmulloy2/ProtocolLib/releases/download/3.7.0/ProtocolLib.jar
