### ISSUE TITLE
[1.12.2] Incompatibilities with OpenJ9

### ISSUE THREAD

**Issue by Zilacon** [Teneted/Tenet#98]
```
[13:00:47 ERROR]: Failed to create block entity snowrealmagic:snow
 java.lang.InstantiationException: snownee.snow.EntityFallingSnow
	at java.lang.J9VMInternals.newInstanceImpl(Native Method) ~[?:1.8.0_242]
	at java.lang.Class.newInstance(Class.java:1852) ~[?:1.8.0_242]
	at net.minecraft.tileentity.TileEntity.create(TileEntity.java:114) [avj.class:?]
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.loadEntities(AnvilChunkLoader.java:505) [aye.class:?]
	at net.minecraftforge.common.chunkio.ChunkIOProvider.syncCallback(ChunkIOProvider.java:102) [ChunkIOProvider.class:7b33d82]
	at net.minecraftforge.common.chunkio.ChunkIOExecutor.tick(ChunkIOExecutor.java:174) [ChunkIOExecutor.class:7b33d82]
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:870) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:468) [nz.class:?]
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:778) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:621) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:821) [?:1.8.0_242]
```
```
[13:00:47 ERROR]: A TileEntity snowrealmagic:snow(snownee.snow.EntityFallingSnow) has thrown an exception during loading, its state cannot be restored. Report this to the mod author
 java.lang.InstantiationException: snownee.snow.EntityFallingSnow
	at java.lang.J9VMInternals.newInstanceImpl(Native Method) ~[?:1.8.0_242]
	at java.lang.Class.newInstance(Class.java:1852) ~[?:1.8.0_242]
	at net.minecraft.tileentity.TileEntity.create(TileEntity.java:114) [avj.class:?]
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.loadEntities(AnvilChunkLoader.java:505) [aye.class:?]
	at net.minecraftforge.common.chunkio.ChunkIOProvider.syncCallback(ChunkIOProvider.java:102) [ChunkIOProvider.class:7b33d82]
	at net.minecraftforge.common.chunkio.ChunkIOExecutor.tick(ChunkIOExecutor.java:174) [ChunkIOExecutor.class:7b33d82]
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:870) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:468) [nz.class:?]
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:778) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:621) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:821) [?:1.8.0_242]
```

**Comment by Mgazul** [comment]
Unable to determine the cause of the problem, forgeserver or sponge is working properly?

**Comment by Zilacon** [comment]
Sponge? This is on bukkit/forge?
The server runs with this error but it wont generate several types of entities. Ive seen twilight forest entities throw this same J9VM error.

**Comment by vico93** [comment]
I heard in Forge discord their server will not run on OpenJ9, only Hotspot.

**Comment by Zilacon** [comment]
Thats false, we can run the forge server all the way back to 1.5.2 on OpenJ9 with no problems.

**Comment by vico93** [comment]
But...but... (both came from the official Forge's discord server and for high-profile members):

![image](https://user-images.githubusercontent.com/3485505/75127234-ca787400-569c-11ea-942c-d13ae18be08f.png)
![image](https://user-images.githubusercontent.com/3485505/75127249-d95f2680-569c-11ea-8ea1-a5e2ef8fdb1b.png)

**Comment by CraftDream** [comment]
> Sponge? This is on bukkit/forge?
> The server runs with this error but it wont generate several types of entities. Ive seen twilight forest entities throw this same J9VM error.

Sponge, don't you know? It's almost like mods / plugins, but it only supports plug-ins developed based on the spongeapi. (and the spongeapi is more like a mod?)

**Comment by Zilacon** [comment]
Of course i know what sponge is, i was questioning what it had to do with using oj9 with a bukkit/forge server. Sponge is horrible in my eyes. Weve tried using it in the past, way too many performance issues, and too little of a ecosystem for plugins and support.

I could run 10 times more players on a single mohist server then i could on a sponge server. I watched 2 entire competing networks die because they switched to sponge. Devco and ToastyNetworks used to be huge, then they switched to sponge and their 400+ playerbase dropped to a few dozen due to the amount of lag.

Bukkit/Forge hybrid servers are the way to go for modded servers. But theres too many individuals trying to make their own versions, instead of joining forces and working together to make something amazing. Theres 16 different hybrid server projects now, but yet mohist is the only one that focuses on mod compatibility across the board, and adds small performance improvements. If those other 15 projects merged with mohist everything would be getting fixed. And then mgazul would have more time to spend with his kids instead of fixing everything himself.

**Comment by CraftDream** [comment]
> Of course i know what sponge is, i was questioning what it had to do with using oj9 with a bukkit/forge server. Sponge is horrible in my eyes. Weve tried using it in the past, way too many performance issues, and too little of a ecosystem for plugins and support.
> 
> I could run 10 times more players on a single mohist server then i could on a sponge server. I watched 2 entire competing networks die because they switched to sponge. Devco and ToastyNetworks used to be huge, then they switched to sponge and their 400+ playerbase dropped to a few dozen due to the amount of lag.
> 
> Bukkit/Forge hybrid servers are the way to go for modded servers. But theres too many individuals trying to make their own versions, instead of joining forces and working together to make something amazing. Theres 16 different hybrid server projects now, but yet mohist is the only one that focuses on mod compatibility across the board, and adds small performance improvements. If those other 15 projects merged with mohist everything would be getting fixed. And then mgazul would have more time to spend with his kids instead of fixing everything himself.

Obviously that's not possible at the moment, but I also hope that one day.

**Comment by Mgazul** [comment]
I looked up a lot of resources, and this is in Class <? Extends TileEntity> ? Related, not compatible with openj9, and I can't modify the code of mohist, because it will break the compatibility of a lot of mods
