### ISSUE TITLE
extratnt Issue

### ISSUE THREAD

**Issue by KubiRemPL** [Teneted/Tenet#988]
Hello.
I am using a mod named extratnt in version 1.0.0. It gives me errors when using mohist. Tested on vanilla forge client and it works as it should. Tested on mohist-1.16.5-376-server.jar with only extratnt installed.

That's the error log (Sorry I can't use a paste site)

```
[16:10:01] [Server thread/FATAL] [net.minecraftforge.common.ForgeMod/]: Preparing crash report with UUID 432b89c0-c2d5-474f-836d-7b72b744a8fa
[16:10:01] [Server thread/FATAL] [net.minecraft.util.concurrent.ThreadTaskExecutor/]: Error executing task on Server
[16:10:01] [Server thread/WARN] [/]: net.minecraft.crash.ReportedException: Exception while updating neighbours
[16:10:01] [Server thread/WARN] [/]: 	at net.minecraft.world.World.func_190524_a(World.java:491)
[16:10:01] [Server thread/WARN] [/]: 	at net.minecraft.world.World.func_195593_d(World.java:425)
[16:10:01] [Server thread/WARN] [/]: 	at net.minecraft.world.server.ServerWorld.func_230547_a_(ServerWorld.java:1585)
[16:10:01] [Server thread/WARN] [/]: 	at net.minecraft.world.World.markAndNotifyBlock(World.java:349)
[16:10:01] [Server thread/WARN] [/]: 	at net.minecraftforge.common.ForgeHooks.onPlaceItemIntoWorld(ForgeHooks.java:710)
[16:10:01] [Server thread/WARN] [/]: 	at net.minecraft.item.ItemStack.func_196084_a(ItemStack.java:212)
[16:10:01] [Server thread/WARN] [/]: 	at net.minecraft.server.management.PlayerInteractionManager.func_219441_a(PlayerInteractionManager.java:447)
[16:10:01] [Server thread/WARN] [/]: 	at net.minecraft.network.play.ServerPlayNetHandler.func_184337_a(ServerPlayNetHandler.java:1394)
[16:10:01] [Server thread/WARN] [/]: 	at net.minecraft.network.play.client.CPlayerTryUseItemOnBlockPacket.func_148833_a(CPlayerTryUseItemOnBlockPacket.java:38)
[16:10:01] [Server thread/WARN] [/]: 	at net.minecraft.network.play.client.CPlayerTryUseItemOnBlockPacket.func_148833_a(CPlayerTryUseItemOnBlockPacket.java:12)
[16:10:01] [Server thread/WARN] [/]: 	at net.minecraft.network.PacketThreadUtil.lambda$checkThreadAndEnqueue$0(PacketThreadUtil.java:22)
[16:10:01] [Server thread/WARN] [/]: 	at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18)
[16:10:01] [Server thread/WARN] [/]: 	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(ThreadTaskExecutor.java:136)
[16:10:01] [Server thread/WARN] [/]: 	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23)
[16:10:01] [Server thread/WARN] [/]: 	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:872)
[16:10:01] [Server thread/WARN] [/]: 	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:183)
[16:10:01] [Server thread/WARN] [/]: 	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(ThreadTaskExecutor.java:109)
[16:10:01] [Server thread/WARN] [/]: 	at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:855)
[16:10:01] [Server thread/WARN] [/]: 	at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:849)
[16:10:01] [Server thread/WARN] [/]: 	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(ThreadTaskExecutor.java:119)
[16:10:01] [Server thread/WARN] [/]: 	at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:835)
[16:10:01] [Server thread/WARN] [/]: 	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:768)
[16:10:01] [Server thread/WARN] [/]: 	at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:276)
[16:10:01] [Server thread/WARN] [/]: 	at java.lang.Thread.run(Thread.java:748)
[16:10:01] [Server thread/WARN] [/]: Caused by: java.lang.NoSuchMethodError: net.flytre.extratnt.publicized.TntEntityPublic.func_70016_h(DDD)V
[16:10:01] [Server thread/WARN] [/]: 	at net.flytre.extratnt.publicized.TntEntityPublic.update(TntEntityPublic.java:33)
[16:10:01] [Server thread/WARN] [/]: 	at net.flytre.extratnt.block.GeyserTntBlock.lambda$new$0(GeyserTntBlock.java:14)
[16:10:01] [Server thread/WARN] [/]: 	at net.flytre.extratnt.publicized.TntBlockPublic.explode(TntBlockPublic.java:80)
[16:10:01] [Server thread/WARN] [/]: 	at net.flytre.extratnt.publicized.TntBlockPublic.catchFire(TntBlockPublic.java:37)
[16:10:01] [Server thread/WARN] [/]: 	at net.flytre.extratnt.publicized.TntBlockPublic.func_220069_a(TntBlockPublic.java:52)
[16:10:01] [Server thread/WARN] [/]: 	at net.minecraft.block.AbstractBlock$AbstractBlockState.func_215697_a(AbstractBlock.java:581)
[16:10:01] [Server thread/WARN] [/]: 	at net.minecraft.world.World.func_190524_a(World.java:475)
[16:10:01] [Server thread/WARN] [/]: 	... 23 more
```

**Comment by KR33PYK1NG** [comment]
ExtraTNT is not working on the latest Forge/Mohist version.
