### ISSUE TITLE
[1.7.10] throwing item nether portal.

### ISSUE THREAD

**Issue by Ru-Nan-i** [Teneted/Tenet#991]
There is a problem that the server stop when throwing an item on the nether portal.

Description: Exception ticking world entities

java.lang.IndexOutOfBoundsException: Index: 228, Size: 228
	at java.util.ArrayList.rangeCheck(Unknown Source)
	at java.util.ArrayList.remove(Unknown Source)
	at net.minecraft.world.World.func_72939_s(World.java:2494)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:674)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:980)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:437)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:835)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:692)
	at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:

**Comment by KR33PYK1NG** [comment]
1.7.10 is no longer supported, sorry.
